import type { LifeEventDef } from '@/lib/engine/types';

export const ADULT_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'adult_buy_flat_mirpur',
    text: 'জীবনের বহু বছরের সঞ্চয় আর প্রভিডেন্ট ফান্ডের টাকা ভাঙায়া মিরপুরে একখান তিন রুমের ফ্ল্যাট কেনার প্রস্তাব আসলো!',
    minAge: 35,
    maxAge: 55,
    weight: 9,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'sign_flat_deed',
        text: 'এককালীন ব্যাংকের লোন নিয়া ফ্ল্যাটের দলিল রেজিস্ট্রি কর',
        outcomeText: 'নিজের বাড়ির মালিক হইলি! গৃহপ্রবেশে আত্মীয়স্বজনরে কাচ্চি খাওয়াইয়া আনন্দ করলি!',
        tone: 'good',
        effects: { money: -500, happiness: 25, looks: 10 },
      },
      {
        id: 'delay_investment',
        text: 'ঝুঁকি না নিয়া ভাড়া বাড়িতেই থাকার সিদ্ধান্ত নে',
        outcomeText: 'টাকা ব্যাংকে রইলো, কিন্তু পরের বছর বাড়িওয়ালা ২০% ভাড়া বাড়ায়া দিলো!',
        tone: 'neutral',
        effects: { happiness: -8, money: 50 },
      },
    ],
  },
  {
    id: 'adult_doctor_beef_ban',
    text: 'বার্ষিক মেডিকেল চেকআপের পর ডাক্তার প্রেসক্রিপশনে লাল কালিতে গোল দাগ দিয়া কইলো, "কোলেস্টেরল আকাশচুম্বী! গরুর মাংস, কাচ্চি, তেহারি আজীবন নিষিদ্ধ!"',
    minAge: 40,
    maxAge: 62,
    weight: 8,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'strictly_follow_diet',
        text: 'কান্দা মন নিয়া ওটস আর উচ্ছে করলা ভাজি খাওয়ার নিয়ত কর',
        outcomeText: 'স্বাস্থ্য ফিরে আসলো, প্রেসার নরমাল হইলো! জীবন বাঁইচা গেল!',
        tone: 'good',
        effects: { health: 25, happiness: -10 },
      },
      {
        id: 'cheat_day_kacchi',
        text: 'ডাক্তারের প্রেসক্রিপশন পকেটে রাইখা নাজিরাবাজারে এক প্লেট স্পেশাল কাচ্চি খাইতে যা',
        outcomeText: 'জিভের তৃপ্তি মিটলো, কিন্তু পরদিন সকালে বুক ধড়ফড় কইরা ইসিজি রুমে দৌড়াইতে হইলো!',
        tone: 'bad',
        effects: { health: -18, happiness: 10 },
      },
    ],
  },
  {
    id: 'adult_child_school_bribe',
    text: 'ছেলের নামিদামি স্কুলে ভর্তির জন্য এক দালাল কইলো, "ভাই, ম্যানেজমেন্ট কোটায় এক লাখ টাকা দিলে সিট কনফার্ম!"',
    minAge: 32,
    maxAge: 45,
    weight: 8,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'refuse_bribe',
        text: 'সততার সহিত ঘাড় নাড়া: "হারাম টাকায় ছেলের পড়াশোনা করামু না!"',
        outcomeText: 'ছেলে সাধারণ স্কুলে মেধার জোরে টপার হইলো! সমাজে তোর সম্মান বাড়লো!',
        tone: 'good',
        effects: { karma: 20, happiness: 15, smarts: 10 },
      },
      {
        id: 'pay_admission_bribe',
        text: 'ভবিষ্যতের কথা ভাইবা ধারকর্জ কইরা টাকাটা দালালের হাতে তুইলা দে',
        outcomeText: 'ছেলে নামি স্কুলে ঢুকলো ঠিকই, কিন্তু রাতে বিবেকের দংশনে ঘুম হইলো না।',
        tone: 'bad',
        effects: { money: -300, karma: -15, happiness: 5 },
      },
    ],
  },
  {
    id: 'adult_ancestral_land_dispute',
    text: 'গ্রামের বাড়ির দাদার রেখে যাওয়া ভিটা জমি নিয়া চাচাতো ভাইরা নোটিশ পাঠাইলো: "ভাগাভাগি না হইলে কোর্টে মামলা!"',
    minAge: 38,
    maxAge: 60,
    weight: 8,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'peaceful_settlement',
        text: 'শালিস ডাইকা নিজের ভাগের একটু ছাড় দিয়া আপোষ কর',
        outcomeText: 'পারিবারিক রক্তক্ষয়ী ঝামেলা মিটলো। শান্তি বজায় রইলো!',
        tone: 'good',
        effects: { karma: 18, happiness: 15, health: 5 },
      },
      {
        id: 'fight_court_case',
        text: 'আইনজীবী ধইরা দেওয়ানি মামলা ঠুকে দে: "এক ইঞ্চি জমিও ছাড়ুম না!"',
        outcomeText: '১০ বছর ধইরা কোর্টের বারান্দায় জুতার তলা ক্ষইলো, উকিল ধনী হইলো আর তোর পকেট ফাঁকা!',
        tone: 'bad',
        effects: { money: -400, health: -15, happiness: -25 },
      },
    ],
  },
  {
    id: 'adult_share_market_crash',
    text: 'শেয়ার বাজারে ইনভেস্ট কইরা কোটিপতি হওয়ার স্বপ্ন দেখতেছিলি, হঠাৎ সূচক ধস নামিয়া লাল বাত্তি জ্বইলা গেল!',
    minAge: 36,
    maxAge: 58,
    weight: 7,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'sell_remaining_cut_loss',
        text: 'দেরি না কইরা যা বাঁচে তা তুইল্যা ব্যবসা থিকা হাত গুটাও',
        outcomeText: 'ক্ষতি হইলো ঠিকই, কিন্তু সর্বস্বান্ত হওয়া থিকা বাইচা গেলি। একখান শিক্ষা হইলো!',
        tone: 'neutral',
        effects: { money: -200, smarts: 15, happiness: -10 },
      },
      {
        id: 'panic_borrow_double',
        text: 'ক্ষতি পোষাইতে আরও ধার কইরা নতুন শেয়ার কিনলি',
        outcomeText: 'বাজার আরও পইড়া নিঃস্ব হইয়া গেলি! মাথায় হাত দিয়া ফুটপাতে বইসা কান্দন!',
        tone: 'bad',
        effects: { money: -600, health: -15, happiness: -25 },
      },
    ],
  },
  {
    id: 'adult_hajj_pilgrimage',
    text: 'স্ত্রীকে নিয়া পবিত্র হজ্ব পালনের জন্য কাফেলায় নাম লেখানোর সামর্থ্য হইলো। মন পবিত্র অনুশোচনায় উদ্বেলিত!',
    minAge: 45,
    maxAge: 64,
    weight: 9,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'perform_hajj_sincerely',
        text: 'সমস্ত অতীত পাপের ক্ষমা চাইয়া স্ত্রী সহ হজ্ব সম্পন্ন কর',
        outcomeText: 'হাজী সাব উপাধি পাইলি, মনের সমস্ত অশান্তি দূর হইয়া এক অপূর্ব আত্মিক প্রশান্তি আসলো!',
        tone: 'good',
        effects: { money: -400, karma: 25, happiness: 25, health: 10 },
      },
      {
        id: 'postpone_for_business',
        text: 'ব্যবসায়িক কাজে সময় দিতে গিয়া এই বছর হজ্ব পিছাইয়া দাও',
        outcomeText: 'টাকা জমলো কিন্তু অন্তরে এক অপরাধবোধের কাঁটা বিধে রইলো।',
        tone: 'neutral',
        effects: { money: 100, karma: -5 },
      },
    ],
  },
  {
    id: 'adult_first_child_born',
    text: 'হাসপাতালে নার্স কোলে তুইলা দিলো তোর প্রথম সন্তান! এক পলক দেইখা চোখের পানিতে গাল ভাইসা গেল!',
    minAge: 30,
    maxAge: 40,
    weight: 9,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'distribute_sweet_boxes',
        text: 'মহল্লা ও আত্মীয়দের মাঝে ১০০ কেজি প্রিমিয়াম রসগোল্লা বিলাও',
        outcomeText: 'সবাই দোয়া করলো! সন্তানের আগমনে বাড়িটা খুশির স্বর্গে পরিণত হইলো!',
        tone: 'good',
        effects: { money: -80, happiness: 25, karma: 20 },
      },
      {
        id: 'quiet_gratitude_prayer',
        text: 'সৃষ্টিকর্তার শুকরিয়া আদায় করে সন্তানের কানে আজান দাও',
        outcomeText: 'এক অপূর্ব দায়িত্ববোধে অন্তর পূর্ণ হলো। জীবনের নতুন অধ্যায়ের সূচনা!',
        tone: 'good',
        effects: { happiness: 25, smarts: 10, karma: 15 },
      },
    ],
  },
  {
    id: 'adult_promotion_manager',
    text: 'প্রতিষ্ঠানের বোর্ড মিটিংয়ে তোরে জেনারেল ম্যানেজার পদে প্রমোশন আর আলাদা শীতাতপ নিয়ন্ত্রিত কেবিন দেওয়া হইলো!',
    minAge: 35,
    maxAge: 50,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'celebrate_with_team',
        text: 'টিম মেম্বারদের ফাইভ স্টার হোটেলে গ্র্যান্ড ডিনারের ট্রিট দাও',
        outcomeText: 'টিমের সবাই তোর প্রতি বিশ্বস্ত হলো! কাজের গতি দ্বিগুণ বেড়ে গেল!',
        tone: 'good',
        effects: { money: -150, happiness: 25, looks: 12, smarts: 14 },
      },
      {
        id: 'act_bossy_strict',
        text: 'প্রথম দিনেই সবার কাজের ওপর কড়া নজরদারি ও বকাঝকা শুরু করো',
        outcomeText: 'সবাই পেছনে তোরে স্বৈরাচার বলে গালি দিতে লাগলো, অফিসে চাপা ক্ষোভ!',
        tone: 'bad',
        effects: { karma: -15, happiness: -10 },
      },
    ],
  },
  {
    id: 'adult_midlife_gym_crush',
    text: 'বয়স বাড়তেই পেট সামনে বের হয়ে শার্টের বোতাম ছিঁড়ে যাওয়ার উপক্রম! ভুঁড়ি কমানোর যুদ্ধ!',
    minAge: 35,
    maxAge: 52,
    weight: 7,
    tone: 'funny',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'buy_treadmill_run',
        text: 'দামি ট্রেডমিল কিনে প্রতিদিন ভোরে ঘাম ঝরিয়ে দৌড়াও',
        outcomeText: 'তিন মাসে ৫ কেজি ওজন কমলো! শরীর হালকা, পুরোনো ফিটনেস ফিরে পেলে!',
        tone: 'good',
        effects: { health: 22, looks: 15, happiness: 18, money: -70 },
      },
      {
        id: 'use_treadmill_cloth_hanger',
        text: 'দুই দিন দৌড়ে ট্রেডমিলকে জামাকাপড় ঝুলানোর স্ট্যান্ড বানিয়ে ফেলো',
        outcomeText: 'টাকা নষ্ট, ভুঁড়ি আরও বাড়লো! বন্ধুদের হাসি-ঠাট্টার শিকার হলে!',
        tone: 'funny',
        effects: { money: -70, happiness: -10, health: -6 },
      },
    ],
  },
  {
    id: 'adult_in_laws_extended_stay',
    text: 'শ্বশুর-শাশুড়ি তিন মাসের জন্য তোদের দুই রুমের বাসায় বেড়াতে আসলো। ড্রয়িংরুমে পা ফেলার জায়গা নেই!',
    minAge: 32,
    maxAge: 48,
    weight: 7,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'serve_in_laws_warmly',
        text: 'হাসিমুখে প্রতিদিন মাছ-মাংস আর ফলমূল এনে তাদের সেবা যত্ন করো',
        outcomeText: 'শ্বশুর-শাশুড়ি তোরে নিজের ছেলের চেয়েও বেশি ভালোবেসে সম্পত্তির অংশ লিখে দিলো!',
        tone: 'good',
        effects: { money: 150, karma: 22, happiness: 20 },
      },
      {
        id: 'stay_late_at_office',
        text: 'বাসার ভিড় এড়াতে প্রতিদিন রাত ১২টা পর্যন্ত অফিসে বসে কাটাও',
        outcomeText: 'স্ত্রী সন্দেহের চোখে তাকালো, সংসারে প্রতিদিন তুলকালাম ঝগড়া শুরু হইলো!',
        tone: 'bad',
        effects: { happiness: -24, health: -10 },
      },
    ],
  },
  {
    id: 'adult_daughter_wedding_arrangements',
    text: 'মেয়ের বিয়ের বয়স হইলো। সেরা বরযাত্রী সমাগম ও ৫০ ডেগ কাচ্চি বিরিয়ানির বিশাল আয়োজন!',
    minAge: 45,
    maxAge: 58,
    weight: 9,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'grand_wedding_feast',
        text: 'কমিউনিটি সেন্টারে জমকালো ঢাকাইয়া আয়োজনে ধুমধাম করে বিদায় দাও',
        outcomeText: 'মেয়ের চোখে আনন্দের জল! পুরো সমাজের মানুষ তোর আতিথেয়তার প্রশংসা করলো!',
        tone: 'good',
        effects: { money: -600, happiness: 25, karma: 20, looks: 10 },
      },
      {
        id: 'simple_mosque_wedding',
        text: 'মসজিদে অনাড়ম্বর আকদ করিয়ে জমানো টাকা মেয়ের ব্যাংক একাউন্টে দাও',
        outcomeText: 'অপচয় বাঁচলো, মেয়ে সুখে শান্তিতে নিজের নতুন সংসার গুছিয়ে নিলো!',
        tone: 'good',
        effects: { money: -100, smarts: 18, happiness: 25 },
      },
    ],
  },
  {
    id: 'adult_pension_scheme_dps',
    text: '১০ বছরের ব্যাংকের ডিপিএস মেয়াদ পূর্ণ হইলো! এককালীন ২০ লাখ টাকা হাতে আসলো!',
    minAge: 42,
    maxAge: 58,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'buy_village_land',
        text: 'গ্রামের হাইওয়ের পাশে নির্ভেজাল এক খণ্ড জমি রেজিস্ট্রি করো',
        outcomeText: 'কয়েক বছরেই জমির দাম তিনগুণ বাড়লো! দূরদর্শী সিদ্ধান্তের সুফল পেলে!',
        tone: 'good',
        effects: { money: 500, smarts: 16, happiness: 24 },
      },
      {
        id: 'lend_to_brother_in_law',
        text: 'শালার ভুয়া ব্যবসায় পুরো টাকাটা লগ্নী করে দাও',
        outcomeText: 'শালা টাকা মেরে পালিয়ে গেল! পারিবারিক দাওয়াতে হাতাহাতি!',
        tone: 'bad',
        effects: { money: -500, happiness: -25, karma: -10 },
      },
    ],
  },
  {
    id: 'adult_diabetes_sweet_temptation',
    text: 'ডায়াবেটিস ধরা পড়ছে। অথচ কাজিনের ছেলের সুন্নতে খতনার দাওয়াতে সামনে রসগোল্লা আর কাচ্চির পাহাড়!',
    minAge: 40,
    maxAge: 58,
    weight: 8,
    tone: 'funny',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'eat_boiled_salad',
        text: 'লোভ দমন করে কেবল শসা আর সালাদ চিবিয়ে পানি খাও',
        outcomeText: 'সুগার নিয়ন্ত্রণে রইলো! নিজের আত্মনিয়ন্ত্রণে গর্ব বোধ করলে!',
        tone: 'good',
        effects: { health: 18, smarts: 10, happiness: 10 },
      },
      {
        id: 'secret_roshogolla_spree',
        text: 'লুকিয়ে চারটা গরম রসগোল্লা মুখে পুরে ঢোক গিলে ফেলো',
        outcomeText: 'পরের দিন সকালে সুগার ১৬ পার! ডাক্তারের কড়া ইনজেকশনের গুঁতা জুটলো!',
        tone: 'bad',
        effects: { health: -20, happiness: -15 },
      },
    ],
  },
  {
    id: 'adult_car_accident_settlement',
    text: 'এয়ারপোর্ট রোডে এক বেপরোয়া বাসের ধাক্কায় তোর গাড়ির ডান পাশের দরজা চ্যাপ্টা!',
    minAge: 35,
    maxAge: 55,
    weight: 7,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'claim_insurance_calmly',
        text: 'জিডি করে ইনস্যুরেন্স কোম্পানির কাছ থেকে সম্পূর্ণ ক্ষতিপূরণ আদায় করো',
        outcomeText: 'কোনো মারামারি ছাড়াই গাড়ি নতুনের মতো মেরামত হয়ে আসলো!',
        tone: 'good',
        effects: { smarts: 14, happiness: 12, money: -30 },
      },
      {
        id: 'beat_bus_driver',
        text: 'রাস্তায় নেমে বাস ড্রাইভারের কলার ধরে মারপিট শুরু করো',
        outcomeText: 'বাকি বাসের ড্রাইভাররা এসে তোরে ঘিরে গণধোলাই দিলো! হাসপাতাল যাত্রা!',
        tone: 'bad',
        effects: { health: -22, happiness: -25, looks: -8 },
      },
    ],
  },
  {
    id: 'adult_building_committee_president',
    text: 'ফ্ল্যাটের মালিকরা মিলে সর্বসম্মতিক্রমে তোরে বিল্ডিং কল্যাণ সমিতির সভাপতি নির্বাচিত করলো!',
    minAge: 38,
    maxAge: 58,
    weight: 7,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'fix_water_pump_solar',
        text: 'রুফটপে সোলার প্যানেল বসিয়ে পানির পাম্পের বিল অর্ধেক করে দাও',
        outcomeText: 'সব ফ্ল্যাটের বাসিন্দারা তোরে প্রশংসায় ভাসালো! সম্মান বহুগুণ বাড়লো!',
        tone: 'good',
        effects: { smarts: 16, karma: 20, happiness: 22 },
      },
      {
        id: 'embezzle_service_charge',
        text: 'সার্ভিস চার্জের তহবিল থেকে নিজের ফ্ল্যাটের কাজ করিয়ে নাও',
        outcomeText: 'অডিটে চুরি ধরা পড়লো! সাধারণ সভায় প্রকাশ্য বেইজ্জতি!',
        tone: 'bad',
        effects: { karma: -25, happiness: -25, looks: -12 },
      },
    ],
  },
  {
    id: 'adult_son_foreign_university',
    text: 'ছেলে কানাডার নামিদামি বিশ্ববিদ্যালয়ে স্কলারশিপ নিয়ে পড়ার সুযোগ পেয়েছে! লাখ টাকার টিউশন ফি প্রয়োজন!',
    minAge: 46,
    maxAge: 59,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'finance_son_education',
        text: 'সঞ্চয় ভেঙে ছেলের উচ্চশিক্ষার খরচ হাসিমুখে বহন করো',
        outcomeText: 'ছেলে বিদেশে গিয়ে শীর্ষ ফলাফল করলো! পুরো পরিবারের মুখ উজ্জ্বল!',
        tone: 'good',
        effects: { money: -400, happiness: 25, karma: 20 },
      },
      {
        id: 'stop_son_travel',
        text: 'ভয়ে টাকা খরচ না করে ছেলেকে স্থানীয় সাধারণ কলেজে ভর্তি করাও',
        outcomeText: 'ছেলে হতাশায় ভেঙে পড়লো, বাবার সাথে সম্পর্কের চিরতরে ফাটল ধরলো!',
        tone: 'bad',
        effects: { happiness: -25, karma: -15 },
      },
    ],
  },
  {
    id: 'adult_nephew_job_recommendation',
    text: 'বেকার অলস ভাগ্নের জন্য বোনের কান্না: "তোর প্রতিষ্ঠানে একখান বড় অফিসার পদে ঢুকিয়ে দে!"',
    minAge: 40,
    maxAge: 56,
    weight: 7,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'test_skill_first',
        text: 'কড়া ইন্টারভিউ নিয়ে যোগ্যতার ভিত্তিতে ট্রেনিং দিয়ে এন্ট্রি লেভেলে রাখো',
        outcomeText: 'ভাগ্নে ধীরে ধীরে কাজ শিখলো, বোনও তোর সুবিচারের প্রশংসা করলো!',
        tone: 'good',
        effects: { smarts: 14, karma: 15, happiness: 15 },
      },
      {
        id: 'blindly_appoint_nephew',
        text: 'যোগ্যতা ছাড়াই বড় পোস্টে বসিয়ে দাও',
        outcomeText: 'ভাগ্নে বড় ক্লায়েন্টের ডিল ফাঁসিয়ে দিলো! ম্যানেজমেন্টের কাছে তোরে জবাবদিহি করতে হইলো!',
        tone: 'bad',
        effects: { money: -150, happiness: -20, karma: -10 },
      },
    ],
  },
  {
    id: 'adult_gold_necklace_anniversary',
    text: 'তাঁতীবাজারের বিখ্যাত স্বর্ণালঙ্কার দোকান থেকে স্ত্রীর জন্য ২২ ক্যারেটের সীতা হার কিনতে গেলি!',
    minAge: 36,
    maxAge: 55,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'buy_certified_gold',
        text: 'হলমার্ক করা নিখুঁত ডিজাইনের ভারী গহনা উপহার দাও',
        outcomeText: 'স্ত্রী আনন্দে তোরে বুকে জড়িয়ে ধরলো! সংসারে ভালোবাসার নতুন জোয়ার!',
        tone: 'good',
        effects: { money: -250, happiness: 25, looks: 10 },
      },
      {
        id: 'buy_cheap_gold_plated',
        text: 'টাকা বাঁচাতে গিয়ে সিটি গোল্ডের গহনা আসল বলে চালিয়ে দাও',
        outcomeText: 'দুই সপ্তাহেই রঙ উঠে তামা বের হলো! স্ত্রী কান্নাকাটি করে বাবার বাড়ি চলে গেল!',
        tone: 'bad',
        effects: { karma: -20, happiness: -25 },
      },
    ],
  },
  {
    id: 'adult_tax_audit_notice',
    text: 'জাতীয় রাজস্ব বোর্ড (এনবিআর) থেকে আয়কর নথির অডিট নোটিশ পাঠালো! ভয়ের ঠাণ্ডা স্রোত!',
    minAge: 38,
    maxAge: 58,
    weight: 7,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'hire_competent_cpa',
        text: 'ভালো ট্যাক্স আইনজীবী ধরে সমস্ত রসিদ ও নথি পরিষ্কারভাবে দাখিল করো',
        outcomeText: 'ক্লিন সার্টিফিকেট পেলে! কোনো জরিমানা ছাড়াই ঝামেলা শেষ!',
        tone: 'good',
        effects: { smarts: 16, money: -50, happiness: 16 },
      },
      {
        id: 'ignore_tax_notice',
        text: 'চিঠি ড্রয়ারে রেখে ভুলে যাওয়ার ভান করো',
        outcomeText: 'ব্যাংক একাউন্ট জব্দ! দ্বিগুণ জরিমানা দিয়ে ছাড়াতে নাভিশ্বাস উঠলো!',
        tone: 'bad',
        effects: { money: -350, happiness: -25 },
      },
    ],
  },
  {
    id: 'adult_business_expansion_branch',
    text: 'ব্যবসায় ভালো মুনাফা হওয়ায় চট্টগ্রামে নতুন একখান পাইকারি শাখা খোলার প্রস্তাব এলো!',
    minAge: 38,
    maxAge: 55,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'expand_calculated_risk',
        text: 'বাজার যাচাই করে বিশ্বস্ত ম্যানেজারের মাধ্যমে শাখা চালু করো',
        outcomeText: 'প্রথম বছর থেকেই কাঁচা টাকার বন্যা! ব্যবসার পরিধি দেশজুড়ে বিস্তৃত হলো!',
        tone: 'good',
        effects: { money: 600, smarts: 18, happiness: 25 },
      },
      {
        id: 'stay_content_local',
        text: 'নতুন ঝামেলায় না গিয়ে পুরনো দোকান নিয়েই সন্তুষ্ট থাকো',
        outcomeText: 'নিরাপদ ব্যবসা, পরিবারের সাথে শান্তিতে সময় কাটালে!',
        tone: 'neutral',
        effects: { happiness: 10, smarts: 6 },
      },
    ],
  },
  {
    id: 'adult_house_renovation_roof',
    text: 'বর্ষার পানিতে ছাদ চুইয়ে ড্রয়িংরুমে পানি পড়ছে! রাজমিস্ত্রি ডেকে মেরামতের কাজ শুরু!',
    minAge: 35,
    maxAge: 55,
    weight: 7,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'waterproof_chemical_coat',
        text: 'উন্নত কেমিক্যাল কোটিং ও টাইলস বসিয়ে ছাদ মজবুত করো',
        outcomeText: 'পানি পড়া স্থায়ীভাবে বন্ধ হলো! ছাদে সুন্দর বাগান বানানোর সুযোগ হলো!',
        tone: 'good',
        effects: { money: -80, happiness: 18, looks: 8 },
      },
      {
        id: 'cheap_cement_patch',
        text: 'সস্তা সিমেন্ট দিয়ে জোড়াতালি দাও',
        outcomeText: 'পরের বৃষ্টিতেই সিলিং ফ্যান দিয়ে ঝরনার মতো পানি পড়া শুরু হলো!',
        tone: 'bad',
        effects: { money: -30, happiness: -15, health: -4 },
      },
    ],
  },
  {
    id: 'adult_charity_iftar_distribution',
    text: 'পবিত্র রমজান মাসে চকবাজারের এতিম ও দরিদ্রদের মাঝে ৫০০ প্যাকেট বিশেষ ইফতার বিতরণের সুযোগ!',
    minAge: 35,
    maxAge: 59,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'sponsor_and_serve_personally',
        text: 'নিজের হাতে গরম তেহারি আর খেজুরের প্যাকেট তুলে দাও',
        outcomeText: 'অসহায় মানুষের মুখের তৃপ্তির হাসি তোর আত্মাকে শান্তিতে ভরিয়ে দিলো!',
        tone: 'good',
        effects: { money: -100, karma: 25, happiness: 25 },
      },
      {
        id: 'take_credit_photos_only',
        text: 'ব্যানার টানিয়ে ক্যামেরায় ছবি তুলে সোশ্যাল মিডিয়ায় প্রচার করো',
        outcomeText: 'মানুষ তোরে লোকদেখানো দাতা বলে ব্যঙ্গ করলো, আত্মতৃপ্তি মিললো না!',
        tone: 'bad',
        effects: { karma: -12, looks: -5 },
      },
    ],
  },
  {
    id: 'adult_heart_attack_scare',
    text: 'রাতের বেলা গুরুপাক খাওয়ার পর হঠাৎ বুকে তীব্র ব্যথা ও শ্বাসকষ্ট! ন্যাশনাল হার্ট ফাউন্ডেশনে ইমার্জেন্সি!',
    minAge: 45,
    maxAge: 59,
    weight: 8,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'emergency_angiogram_lifestyle',
        text: 'দ্রুত এনজিওগ্রাম করিয়ে ব্লকে রিং পরাও এবং জীবনযাত্রায় আমূল পরিবর্তন আনো',
        outcomeText: 'মৃত্যুর মুখ থেকে ফিরে আসলে! নতুন জীবনের মূল্য উপলব্ধি করলে!',
        tone: 'good',
        effects: { health: 15, money: -300, smarts: 14, happiness: 15 },
      },
      {
        id: 'blame_gas_take_antacid',
        text: 'সাধারণ গ্যাসের ব্যথা ভেবে অ্যান্টাসিড খেয়ে শুয়ে থাকো',
        outcomeText: 'আইসিইউতে লাইফ সাপোর্টে যেতে হলো! একটুর জন্য জীবন রক্ষা পেল!',
        tone: 'bad',
        effects: { health: -25, money: -400, happiness: -25 },
      },
    ],
  },
  {
    id: 'adult_old_friend_success_jealousy',
    text: 'ক্লাব ক্লাবের রিইউনিয়নে গিয়ে দেখলে পেছনের বেঞ্চের এক বন্ধু এখন দেশের শীর্ষ ধনী ব্যবসায়ী!',
    minAge: 36,
    maxAge: 54,
    weight: 7,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'congratulate_warmly',
        text: 'আন্তরিক অভিনন্দন জানিয়ে পুরনো দিনের মজার স্মৃতি নিয়ে আড্ডা দাও',
        outcomeText: 'বন্ধু খুশি হয়ে তোর কোম্পানিতে বড় একখানা সাপ্লাই কন্ট্রাক্ট অফার করলো!',
        tone: 'good',
        effects: { money: 250, smarts: 12, happiness: 22 },
      },
      {
        id: 'burn_with_envy',
        text: 'মনে মনে হিংসায় জ্বলে গিয়ে বন্ধুদের কাছে তার বদনাম করো',
        outcomeText: 'নিজের হীনমন্যতায় মন বিষিয়ে উঠলো, আসরের আনন্দ মাটি হলো!',
        tone: 'bad',
        effects: { happiness: -18, karma: -12 },
      },
    ],
  },
  {
    id: 'adult_family_vacation_sajek',
    text: 'স্ত্রী ও ছেলেমেয়েদের নিয়ে সাজেক ভ্যালির মেঘের দেশে পারিবারিক ভ্রমণের আয়োজন!',
    minAge: 35,
    maxAge: 52,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'enjoy_chander_gari_clouds',
        text: 'খোলা চান্দের গাড়ির ছাদে বসে পাহাড়ি হাওয়ায় মেঘ ছুঁয়ে দেখো',
        outcomeText: 'ছেলেমেয়েরা আনন্দে আত্মহারা! পারিবারিক বাঁধন আরও সুদৃঢ় হলো!',
        tone: 'good',
        effects: { happiness: 25, health: 10, money: -100 },
      },
      {
        id: 'complain_about_roads',
        text: 'উঁচু-নিচু পাহাড়ি রাস্তা নিয়ে পুরো পথ স্ত্রীর সাথে খিটখিট করো',
        outcomeText: 'ভ্রমণের আনন্দ নষ্ট! হোটেলের রুমে সবাই মুখ কালো করে বসে রইলো!',
        tone: 'bad',
        effects: { happiness: -16, health: -4 },
      },
    ],
  },
  {
    id: 'adult_haji_camp_sendoff',
    text: 'আশকোনা হাজী ক্যাম্পে বৃদ্ধ পিতা-মাতাকে পবিত্র হজের কাফেলায় তুলে দেওয়ার আবেগঘন মুহূর্ত!',
    minAge: 40,
    maxAge: 58,
    weight: 9,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'hug_parents_tearful_dua',
        text: 'পায়ের ধুলো নিয়ে মা-বাবার কাছে নিজের সব ভুলের মাফ চাও',
        outcomeText: 'মা-বাবার মনভরা দোয়া পেলে! আত্মায় স্বর্গীয় প্রশান্তি অনুভব করলে!',
        tone: 'good',
        effects: { karma: 25, happiness: 25, health: 6 },
      },
      {
        id: 'rush_leave_for_meeting',
        text: 'জরুরি কাজের অজুহাতে বিদায় না জানিয়েই গাড়ি নিয়ে চলে যাও',
        outcomeText: 'মা-বাবার চোখ ছলছল করলো! সারাটা জীবন এই অনুশোচনা বয়ে বেড়াতে হবে!',
        tone: 'bad',
        effects: { karma: -25, happiness: -22 },
      },
    ],
  },
];

