import type { LifeEventDef } from '@/lib/engine/types';

export const ADULT_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'adult_buy_flat_mirpur',
    text: 'লাইফের সব জমানো ট্যাকা আর বউয়ের গয়না বেইচা মিরপুরে একখান তিন রুমের ফ্লাট কিনার ফাপড় নিছোস!',
    minAge: 35,
    maxAge: 55,
    weight: 9,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'sign_flat_deed',
        text: 'লোন নিয়া বুক ফুলাইয়া ফ্লাটের দলিলে সিগনেচার মার!',
        outcomeText: 'ফ্লাট কিনছোস ঠিকই, কিন্তু মিরপুরের জ্যামে ডেইলি তোর অন্ডকোষ ফাইট্টা যাওয়ার দশা! আর লোনের কিস্তি দিতে গিয়া তুই এহন বউয়ের প্যান্টি পইড়া ঘুরতাছোস!',
        tone: 'bad',
        effects: { money: -500, happiness: -20, health: -15 },
      },
      {
        id: 'delay_investment',
        text: 'ডরে মুইতা দিয়া ফ্লাট কেনা ক্যান্সেল কইরা ভাড়া বাসায় থাক!',
        outcomeText: 'ট্যাকা বাঁচাইলি ঠিকই, কিন্তু বাড়িওয়ালা তোর ভাড়া বাড়ায়া তোরে ডাইরেক্ট রাস্তা ফালায়া দিলো! বউয়ের গাইল খায়া এহন তুই পার্কে ঘুমাস!',
        tone: 'bad',
        effects: { happiness: -25, karma: -10, fame: -20 },
      },
    ],
  },
  {
    id: 'adult_doctor_beef_ban',
    text: 'ডাক্তার হালায় তোর টেস্ট রিপোর্ট দেইখা কয়, "তোর তো গু-মুত সব জ্যাম! গরু, খাসি, কাচ্চি সব আজীবন নিষিদ্ধ!"',
    minAge: 40,
    maxAge: 62,
    weight: 8,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'strictly_follow_diet',
        text: 'কাইন্দা কাইন্দা ছাগলের লাহান ঘাস-পাতা খাওয়া শুরু কর!',
        outcomeText: 'ঘাস খায়া তোর বডি ফিট হইছে ঠিকই, কিন্তু ঘাসের চোটে তোর হাগু শক্ত হইয়া বাইর হইতে চায় না! বাথরুমে চিল্লায়া তোর জান শেষ!',
        tone: 'funny',
        effects: { health: 25, happiness: -20, smarts: 10 },
      },
      {
        id: 'cheat_day_kacchi',
        text: 'ডাক্তারের গুষ্টি কিলাইয়া নাজিরাবাজারে ডাবল খাসির কাচ্চি গিল!',
        outcomeText: 'কাচ্চি খায়া তুই এমুন পাদ দিলি যে তোর হার্ট ডাইরেক্ট ব্লক! আইসিইউতে (ICU) পইড়া এহন তুই পাইপ দিয়া তরল হাগু করতাছোস!',
        tone: 'bad',
        effects: { health: -35, happiness: -10, money: -150 },
      },
    ],
  },
  {
    id: 'adult_child_school_bribe',
    text: 'পোলারে ভিআইপি স্কুলে ভর্তি করাইতে গিয়া এক দালাল কয়, "মামা, এক লাখ ট্যাকা ঘুষ দিলে সিট কনফার্ম!"',
    minAge: 32,
    maxAge: 45,
    weight: 8,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'refuse_bribe',
        text: 'নীতিবান সাইজা ক: "হারাম ট্যাকায় পোলারে পড়ামু না, হালায়!"',
        outcomeText: 'পোলা ভালো স্কুলে চান্স পায় নাই বইলা তোরে গাইল দিতাছে! আর বউ তোরে রাত্রে খাটে উঠতে দেয় না, সোফায় শুইয়া হস্তমৈথুন কর এহন!',
        tone: 'bad',
        effects: { happiness: -30, looks: -10, karma: 15 },
      },
      {
        id: 'pay_admission_bribe',
        text: 'চুপচাপ ঘুষের ট্যাকা দালালের হাতে ধরাইয়া দে!',
        outcomeText: 'দালাল ট্যাকা নিয়া লাপাত্তা! পোলাও চান্স পায় নাই, আর তুই ট্যাকা হারাইয়া এহন ছিলা কুত্তার লাহান রাস্তায় রাস্তায় ঘুরতাছোস!',
        tone: 'bad',
        effects: { money: -300, happiness: -35, smarts: -20 },
      },
    ],
  },
  {
    id: 'adult_ancestral_land_dispute',
    text: 'দাদার গ্রামের ভিটা নিয়া তোর হারামি চাচাতো ভাইরা নোটিশ পাঠাইছে: "জমি ছাড়, নাইলে কোর্টে মামলা!"',
    minAge: 38,
    maxAge: 60,
    weight: 8,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'peaceful_settlement',
        text: 'ডরে মুইতা দিয়া শালিস ডাইকা নিজের ভাগের জমি ছাইড়া দে!',
        outcomeText: 'ভাইরা জমি মাইরা দিলো আর তুই হালায় কাপুরুষের লাহান হাইরা গেলি! বউ তোরে থুতু দিয়া বাপের বাড়ি চইলা গেছে!',
        tone: 'bad',
        effects: { karma: -10, happiness: -30, fame: -25 },
      },
      {
        id: 'fight_court_case',
        text: 'রামদা বাইর কইরা মামলা ঠুকে দে: "এক ইঞ্চি জমিও ছাড়ুম না হালায়!"',
        outcomeText: 'মামলা চালাইতে গিয়া উকিল তোর পাছা মাইরা সব ট্যাকা নিয়া গেছে! ১০ বছর পর তুই কোর্টের বারান্দায় ন্যাংটা হইয়া ভিক্কা করতাছোস!',
        tone: 'bad',
        effects: { money: -400, health: -20, happiness: -35 },
      },
    ],
  },
  {
    id: 'adult_share_market_crash',
    text: 'শেয়ার বাজারে উরাধুরা ইনভেস্ট কইরা কোটিপতি হওয়ার স্বপ্ন দেখতেছিলি, হঠাত সূচক ধইসা লাল বাত্তি!',
    minAge: 36,
    maxAge: 58,
    weight: 7,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'sell_remaining_cut_loss',
        text: 'লস খাইয়া যা আছে হেইডা তুইলা মার্কেট থিকা চম্পট দে!',
        outcomeText: 'লস তো খাইলিই, পাওনাদাররা আইসা তোর লুঙ্গি খুইলা নিয়া গেলো! তুই এহন রাস্তায় নুনু বাইর কইরা দৌড়াইতাছোস!',
        tone: 'funny',
        effects: { money: -250, happiness: -20, looks: -30 },
      },
      {
        id: 'panic_borrow_double',
        text: 'লস পোষাইতে কিডনি বেইচা আরও ট্যাকা শেয়ার বাজারে ঢাল!',
        outcomeText: 'মার্কেট আরও ডাউনে! তুই এহন ডাইরেক্ট ফইন্নি! বউ তোরে তালাক দিয়া তোর বেস্ট ফ্রেন্ডের লগে ভাইগা গেছে!',
        tone: 'bad',
        effects: { money: -600, health: -30, happiness: -40 },
      },
    ],
  },
  {
    id: 'adult_promotion_manager',
    text: 'অফিসে তোরে জেনারেল ম্যানেজার বানাইয়া একখান এসি কেবিন দিছে! তুই এহন পুরাই গডফাদার!',
    minAge: 35,
    maxAge: 50,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'celebrate_with_team',
        text: 'টিমের পোলাপাইনরে ফাইভ স্টার হোটেলে গ্র্যান্ড ডিনারের ট্রিট দে!',
        outcomeText: 'ট্রিট দিতে গিয়া বিল আইলো তোর তিন মাসের বেতন! বিল দিতে না পাইরা তুই হোটেলের বাথরুম ধুইতাছোস, আর তোর চামচারা হাসতাছে!',
        tone: 'bad',
        effects: { money: -350, happiness: -25, fame: -15 },
      },
      {
        id: 'act_bossy_strict',
        text: 'বস সাইজা সবার পাছা মারা শুরু কর আর কথায় কথায় গাইল দে!',
        outcomeText: 'পোলাপাইন মেজাজ ফায়ার কইরা তোর এসি কেবিনের লক আটকাইয়া ভিতরে পচা ডিমের গ্যাস ছাইড়া দিছে! তুই গ্যাসে বেহুঁশ, ইজ্জত পুরাই জিরো!',
        tone: 'funny',
        effects: { karma: -25, happiness: -20, health: -15 },
      },
    ],
  },
  {
    id: 'adult_midlife_gym_crush',
    text: 'বয়স বাড়তেই তোর ভুঁড়ি বাইর হইয়া প্যান্টের চেইন লাগাইতে পারতাছোস না! তুই এহন জ্যান্ত হাতি!',
    minAge: 35,
    maxAge: 52,
    weight: 7,
    tone: 'funny',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'buy_treadmill_run',
        text: 'দামি ট্রেডমিল কিন্না কুত্তার লাহান দৌড়ানি শুরু কর!',
        outcomeText: 'দৌড়াইতে গিয়া তুই এমুন আছাড় খাইলি, তোর নাক ভাইঙ্গা তরমুজ! ট্রেডমিল এহন বউয়ের ব্রা শুকানোর স্ট্যান্ড!',
        tone: 'funny',
        effects: { health: -15, looks: -20, money: -80 },
      },
      {
        id: 'ignore_and_eat',
        text: 'ভুঁড়ির গুষ্টি কিলাইয়া ডেইলি রাইতে ডাবল কাচ্চি গিল!',
        outcomeText: 'ভুঁড়ি ফুইলা এমুন হইছে যে তুই নিজের নুনু নিজেই দেখতে পারস না! বাথরুমে গিয়া মুততে গেলে এহন আয়না লাগে!',
        tone: 'bad',
        effects: { health: -30, happiness: -15, looks: -25 },
      },
    ],
  },
  {
    id: 'adult_in_laws_extended_stay',
    text: 'শ্বশুর-শাশুড়ি তিন মাসের লাইগা তোর দুই রুমের বাসায় হানাদারি দিতে আইছে! তোর প্রাইভেসি পুরাই বাঁশ!',
    minAge: 32,
    maxAge: 48,
    weight: 7,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'serve_in_laws_warmly',
        text: 'দাঁত কেল্লায়া তাগো সেবা কর আর ডেইলি খাসির মাংস আন!',
        outcomeText: 'তোর সেবা পাইয়া তারা আর বাসাই ছাড়তে চায় না! তোর আর বউয়ের সেক্স লাইফ এক্কেরে লাল বাত্তি, তুই এহন মাস্টারবেশন কইরা দিন পার করস!',
        tone: 'bad',
        effects: { money: -150, happiness: -30, karma: 10 },
      },
      {
        id: 'stay_late_at_office',
        text: 'বাসায় না গিয়া রাইত ১২টা পর্যন্ত অফিসে পইড়া থাক!',
        outcomeText: 'তুই অফিসে, আর তোর বউ বাসায় এলাকার এক জিম ট্রেইনারের লগে লীলাখেলা শুরু করছে! তুই হালায় ডাইরেক্ট কোকোল্ড (Cuckold)!',
        tone: 'bad',
        effects: { happiness: -40, fame: -30, karma: -10 },
      },
    ],
  },
  {
    id: 'adult_daughter_wedding_arrangements',
    text: 'মাইয়ার বিয়ার বয়স হইছে! জামাই পার্টি ৫০ ডেগ কাচ্চির ডিমান্ড দিয়া তোর পাছা মারার প্ল্যান করতাছে!',
    minAge: 45,
    maxAge: 58,
    weight: 9,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'grand_wedding_feast',
        text: 'জমি বেইচা কমিউনিটি সেন্টারে ধুমধাম কইরা কাচ্চি খাওয়া!',
        outcomeText: 'বিয়া তো হইলো, কিন্তু কাচ্চি পইড়া গিয়া তোর প্যান্ট নষ্ট হইলো আর তুই ফকির হইয়া গেলি! এহন রাস্তায় বইসা মুড়ি বেচ হালায়!',
        tone: 'bad',
        effects: { money: -700, happiness: -20, fame: 20 },
      },
      {
        id: 'simple_mosque_wedding',
        text: 'মসজিদে বিয়া পড়াইয়া ট্যাকা বাঁচাইয়া ফাপড় নে!',
        outcomeText: 'জামাই পার্টি ক্ষেইপা গিয়া বিয়ার দিনই তালাকের ফাপড় নিতাছে! তোর মাইয়া কান্দে আর তুই হার্ট অ্যাটাক কইরা হাসপাতালে পইড়া আছোস!',
        tone: 'bad',
        effects: { health: -25, happiness: -35, karma: -15 },
      },
    ],
  },
  {
    id: 'adult_pension_scheme_dps',
    text: '১০ বছরের ডিপিএস ফাটায়া তোর হাতে একলগে ২০ লাখ ট্যাকা! তুই এহন এলাকার বিল গেটস!',
    minAge: 42,
    maxAge: 58,
    weight: 8,
    tone: 'good',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'buy_village_land',
        text: 'গ্রামে গিয়া হাইওয়ের পাশে নির্ভেজাল জমি কিন্না ফালায় রাখ!',
        outcomeText: 'জমি কিনছোস ঠিকই, কিন্তু এলাকার চেয়ারম্যান হালায় জমি দখল কইরা তোরে ওই জমিতেই মুততে দেয় না! তুই ডরে মামলাও করতে পারস না!',
        tone: 'bad',
        effects: { money: -500, happiness: -30, smarts: -15 },
      },
      {
        id: 'lend_to_brother_in_law',
        text: 'শালার ভুয়া ব্যবসায় পুরা ট্যাকাটা লগ্নী কইরা দে!',
        outcomeText: 'শালা ট্যাকা মাইরা বিদেশী মাইয়া নিয়া দুবাইতে হানিমুন করতাছে! আর তুই তোর বউয়ের ঝাড়ুর বাড়ি খায়া বাথরুমে কান্দতাছোস!',
        tone: 'funny',
        effects: { money: -500, happiness: -35, karma: -20 },
      },
    ],
  },
  {
    id: 'adult_diabetes_sweet_temptation',
    text: 'তোর ডায়াবেটিস! কিন্তু দাওয়াতে সামনে রসগোল্লা আর কাচ্চির পাহাড়, তোর জিহ্বা দিয়া সুনামির লাহান লালা ঝরতাছে!',
    minAge: 40,
    maxAge: 58,
    weight: 8,
    tone: 'funny',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'eat_boiled_salad',
        text: 'লোভ দমন কইরা ছাগলের লাহান শসা আর সালাদ চাবা!',
        outcomeText: 'সালাদ খাইতে গিয়া তোর গলায় গাজর আটকাইয়া তুই এমুন বিষম খাইলি, পাবলিক ভাবলো তোর মৃগী রোগ উঠছে! ইজ্জত পুরাই জিরো!',
        tone: 'bad',
        effects: { health: -10, happiness: -20, fame: -15 },
      },
      {
        id: 'secret_roshogolla_spree',
        text: 'লুকায়ে ৪টা গরম রসগোল্লা একলগে গপাগপ গিল্যা ফ্যাল!',
        outcomeText: 'পরের দিন সুগার উইঠা এক্কেরে ২৫! ডাক্তার তোরে এমুন ইনজেকশন দিলো, তোর পাছা ফুইলা ফুটবল হইয়া গেলো! এহন বইতে পারস না!',
        tone: 'funny',
        effects: { health: -25, happiness: -15, looks: -10 },
      },
    ],
  },
  {
    id: 'adult_car_accident_settlement',
    text: 'এয়ারপোর্ট রোডে এক বেপরোয়া বাস তোর নতুন গাড়ির পাছায় এমুন ধাক্কা মারলো, গাড়ি চ্যাপ্টা!',
    minAge: 35,
    maxAge: 55,
    weight: 7,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'claim_insurance_calmly',
        text: 'ভদ্র পোলার লাহান ইনস্যুরেন্সে ক্লেইম কইরা ট্যাকা বাইর কর!',
        outcomeText: 'ইনস্যুরেন্স কোম্পানি বাটপারি কইরা তোরে মাত্র ৫০০ ট্যাকা ধরাইয়া দিছে! তুই রাগে নিজের চুল নিজে ছিঁড়া টাকলু হইয়া গেলি!',
        tone: 'bad',
        effects: { money: -100, happiness: -25, looks: -10 },
      },
      {
        id: 'beat_bus_driver',
        text: 'রাস্তায় নাইম্মা বাস ড্রাইভারের কলার ধইরা গাইল দে!',
        outcomeText: 'বাসের হেল্পার আর পাবলিক মিল্লা তোরে এমুন গণধোলাই দিলো, তুই হাগু কইরা দিছোস রাস্তায়! ভিডিও ফেসবুকে ভাইরাল, তুই "হাগু-মামা"!',
        tone: 'bad',
        effects: { health: -30, happiness: -40, fame: -25 },
      },
    ],
  },
  {
    id: 'adult_tax_audit_notice',
    text: 'এনবিআর (NBR) থিকা তোর নামে ইনকাম ট্যাক্সের লাল নোটিশ আইছে! তোর ডরে প্যান্টের ভিতর জলপ্রপাত!',
    minAge: 38,
    maxAge: 58,
    weight: 7,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'hire_competent_cpa',
        text: 'ট্যাক্স উকিল ধইরা মোটা ট্যাকা দিয়া সব ফাইল ক্লিয়ার কর!',
        outcomeText: 'উকিল তোরে বাঁশ দিয়া তোর সব জমানো ট্যাকা ফিস হিসেবে নিয়া গেছে! তুই এহন ডাইরেক্ট ফইন্নি, বউ তোরে লাথি মারছে!',
        tone: 'bad',
        effects: { money: -300, happiness: -30, karma: -10 },
      },
      {
        id: 'ignore_tax_notice',
        text: 'ড্যাম কেয়ার ভাব নিয়া নোটিশ দিয়া পাছা মুইছা ফালায়া দে!',
        outcomeText: 'পরের দিন পুলিশ আইসা তোরে কোমরে দড়ি বাইন্ধা নিয়া গেলো! জেলের ভিতরে কয়েদিরা তোরে দিয়া ডেইলি তাগো পাও টিপায়!',
        tone: 'bad',
        effects: { health: -20, happiness: -45, fame: -30 },
      },
    ],
  },
  {
    id: 'adult_heart_attack_scare',
    text: 'রাইতে গরুর মাংস দিয়া ভাত খাওয়ার পর তোর বুকে এমুন ব্যথা, মনে হইতাছে আজরাইল তোর সামনে ড্যান্স দিতাছে!',
    minAge: 45,
    maxAge: 59,
    weight: 8,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'emergency_angiogram_lifestyle',
        text: 'হাসপাতালে গিয়া ৫ লাখ ট্যাকা দিয়া এনজিওগ্রাম কইরা রিং পরা!',
        outcomeText: 'রিং পরাইছে ঠিকই, কিন্তু বিল দিতে গিয়া তোর বাড়ি বেইচা দিতে হইছে! তুই এহন রিং পরা সুস্থ ফকির!',
        tone: 'neutral',
        effects: { health: 15, money: -500, happiness: -25 },
      },
      {
        id: 'blame_gas_take_antacid',
        text: 'গ্যাসের ব্যথা ভাইবা দুইটা অ্যান্টাসিড খায়া হাগু করতে বয়!',
        outcomeText: 'হাগু করতে গিয়া তুই কমোডের উপ্রে হার্ট অ্যাটাক কইরা কাইত হইয়া পড়লি! ন্যাংটা অবস্থায় তোরে আইসিইউতে নিয়া গেলো, পুরাই বেইজ্জতি!',
        tone: 'bad',
        effects: { health: -35, happiness: -40, looks: -25 },
      },
    ],
  },
  {
    id: 'adult_son_foreign_university',
    text: 'তোর পোলা কানাডায় পড়ার লাইগা বাপের সব ট্যাকা চুষা নেওয়ার প্ল্যান করতাছে!',
    minAge: 46,
    maxAge: 59,
    weight: 8,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'finance_son_education',
        text: 'সঞ্চয় ভাইঙ্গা পোলারে কানাডায় পাঠায়া দে!',
        outcomeText: 'পোলা কানাডায় গিয়া সাদা মাইয়া বিয়া কইরা তোরে ব্লক মাইরা দিছে! তুই এহন দেশে বইসা রাস্তার কুত্তারে বিস্কুট খাওয়াচ্ছোস!',
        tone: 'bad',
        effects: { money: -600, happiness: -35, karma: -15 },
      },
      {
        id: 'stop_son_travel',
        text: 'ট্যাকা না দিয়া পোলারে ধইরা এলাকার টংয়ের দোকানে চাকরিতে ঢুকা!',
        outcomeText: 'পোলা রাগে তরকারি কাটার বটি নিয়া তোরে দৌড়ানি দিছে! তুই জান বাঁচাইতে বাথরুমে লুকায়া আছোস দুই দিন ধইরা!',
        tone: 'funny',
        effects: { health: -10, happiness: -25, fame: -20 },
      },
    ],
  },
  {
    id: 'adult_old_friend_success_jealousy',
    text: 'স্কুলের রিইউনিয়নে গিয়া দেখস যেই হালায় ফেল করতো, সে এহন প্রাডো (Prado) নিয়া আইছে!',
    minAge: 36,
    maxAge: 54,
    weight: 7,
    tone: 'bad',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'congratulate_warmly',
        text: 'তেল মাইরা তারে গিয়া জড়ায়ে ধইরা ক: "মামা, আমি তো জানতাম তুই একদিন ফাটায়ে দিবি!"',
        outcomeText: 'সে তোরে সবার সামনে ফইন্নি বইলা অপমান কইরা ১০০ ট্যাকার একখান নোট ধরাইয়া দিলো! তোর ইজ্জত ডাইরেক্ট নর্দমায়!',
        tone: 'bad',
        effects: { money: 10, happiness: -30, fame: -25 },
      },
      {
        id: 'burn_with_envy',
        text: 'হিংসায় জ্বইলা গিয়া পাবলিকের সামনে তার নামে আজেবাজে গীবত গা!',
        outcomeText: 'তার বডিগার্ড আইসা তোরে ধইরা এমুন পিটানি দিলো, তুই মুইতা দিছোস! ভিডিও পুরা টিকটকে ভাইরাল, তুই "মুতা-মামা"!',
        tone: 'bad',
        effects: { health: -20, happiness: -40, looks: -30 },
      },
    ],
  },
  {
    id: 'ad_job_vs_business',
    text: 'বাপজানে কইতাছে, "নবাবপুরের দোকানে গদিতে বয় হালায়!" আর তোর শখ কর্পোরেট টাই পইড়া মাইয়া পটানো!',
    minAge: 25,
    maxAge: 55,
    weight: 9,
    tone: 'neutral',
    category: 'adult',
    source: 'fallback',
    choices: [
      {
        id: 'job_vs_biz_nawabpur_godi',
        text: 'বাপের লগে দোকানে বইসা তেল-কালি মাইখা গদিতে রাজত্ব কর!',
        outcomeText: 'গদিতে বইসা তুই এমুন মোটা হইছোস যে তোর পাছা চেয়ারে আটকায়া যায়! ট্যাকা কামাইলি কিন্তু এহন বিছানায় পারফর্ম করতে পারস না!',
        tone: 'funny',
        effects: { money: 200, happiness: -15, looks: -25 },
      },
      {
        id: 'job_vs_biz_corporate_tie',
        text: 'সিভি হাতে নিয়া কর্পোরেট দাসত্ব করতে যা!',
        outcomeText: 'টাই পইড়া মাইয়া পটাইতে গিয়া দেখস বসের মাইয়া! বস তোরে ধইরা এমুন বাঁশ দিলো, তুই এহন বেকার আর তোর নামে মামলা!',
        tone: 'bad',
        effects: { money: -50, happiness: -35, fame: -20 },
      },
      {
        id: 'job_vs_biz_chill_bike',
        text: 'কোনোটাই না, বাপের ট্যাকা চুরি কইরা বাইক নিয়া চিল মার!',
        outcomeText: 'বাপ পুলিশে দিয়া তোরে জেলে ঢুকায়া দিছে! জেলের ভিতরে তুই এহন বাথরুম পরিষ্কার করস আর বিড়ি টাইন্না দিন পার করস!',
        tone: 'bad',
        effects: { happiness: -40, karma: -30, money: -100 },
      },
    ],
  },
];