import type { LifeEventDef } from '@/lib/engine/types';

export const CHILD_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'child_window_glass_break',
    text: 'গলির মইধ্যে টেপ-টেনিস খেলতে গিয়া তোর উরাধুরা ছক্কায় খবির চাচার ড্রয়িংরুমের কাঁচ ফাইট্টা চৌচির! চাচা লাঠি নিয়া বাইর হইছে!',
    minAge: 7,
    maxAge: 12,
    weight: 9,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'run_usain_bolt',
        text: 'উসাইন বোল্ট সাইজা এক্কেরে চোখের পলকে দৌড়াইয়া ভাগ হালায়!',
        outcomeText: 'দৌড়াইতে গিয়া তুই ডাইরেক্ট ড্রেনে পইড়া গু-মুত মাখামাখি! চাচার হাত থিকা বাঁচলি, তয় তুই এহন জ্যান্ত ডাস্টবিন!',
        tone: 'funny',
        effects: { happiness: -10, karma: -8, looks: -20, health: -5 },
      },
      {
        id: 'confess_apologize',
        text: 'কান ধইরা চাচার সামনে দাঁড়া: "ভুল হইয়া গেছে চাচা, মাফ কইরা দেন!"',
        outcomeText: 'চাচা মাফ তো করলোই না, উল্টা বাপের কাছে বিচার দিয়া তোর পাছায় এমুন বেতের বাড়ি দেওয়াইলো, তুই পুরাই লাল বান্দর!',
        tone: 'bad',
        effects: { health: -15, happiness: -20, karma: 10 },
      },
      {
        id: 'blame_bowler',
        text: 'বোলারের দিকে আঙ্গুল তুইলা ফাপড় দে: "হালায় নো-বল করছিল!"',
        outcomeText: 'তোর ফাপড় শুইনা পোলাপাইন মিল্লা তোরে এমুন মাইর দিলো, তোর নাক দিয়া সর্দি আর রক্ত একলগে বাইর হইলো!',
        tone: 'bad',
        effects: { smarts: -5, karma: -15, health: -10 },
      },
    ],
  },
  {
    id: 'child_raw_mango_theft',
    text: 'দুপুরে কড়া রোদে বড় বাড়ির আম গাছে কাঁচা আম দেইখা তোর জিহ্বা দিয়া এক বালতি লালা ঝরতাছে!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'throw_brick',
        text: 'আধলা ইট মাইরা কড়ার ডাল থিকা আম নামা!',
        outcomeText: 'আম তো পড়লো না, ইট ঘুইরা ডাইরেক্ট তোর চান্দিতে পইড়া এক্কেরে সিঙাড়া ফুইলা গেলো! তুই ব্যথায় মুইতা দিলি!',
        tone: 'bad',
        effects: { happiness: -15, health: -20, smarts: -10 },
      },
      {
        id: 'climb_tree',
        text: 'বান্দরের লাহান গাছে উইঠা আম পাড়!',
        outcomeText: 'গাছে উইঠা দেখস লাল পিঁপড়ার বাসা! পিঁপড়া তোর আন্ডারওয়ারে ঢুইকা এমুন কামড় দিলো, তুই লাফ দিয়া নিচে পইড়া প্যান্ট ফাটায় ফেললি!',
        tone: 'funny',
        effects: { health: -15, happiness: -10, looks: -20 },
      },
    ],
  },
  {
    id: 'child_kite_roof_battle',
    text: 'সাকরাইনে পুরান ঢাকার ছাদে ঘুড়ি লড়াই! তোর চিল ঘুড়ি হালায় পাশের বাড়ির পঙ্খীরাজের লগে প্যাঁচ খাইছে!',
    minAge: 9,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'pull_hard_manja',
        text: 'মাঞ্জা দেওয়া ধারালো সুতা দিয়া সজোরে একখান হ্যাঁচকা টান মার!',
        outcomeText: 'ভোকাট্টা! কিন্তু টান মারতে গিয়া তোর আঙ্গুল কাইটা হাড় বাইর হইয়া গেলো! রক্ত দেইখা তুই নিজেই বেহুঁশ!',
        tone: 'bad',
        effects: { happiness: -10, health: -20, smarts: 6 },
      },
      {
        id: 'let_loose',
        text: 'সুতা হালকা ছাইড়া দিয়া কৌশলে প্যাঁচ কাটাও!',
        outcomeText: 'তোর সুতাই কাইটা গেলো! পাশের ছাদের ফইন্নিরা তোরে "লুজার" বইলা খেপাইলো। তুই রাগে থুতু মারতে গিয়া নিজের গায়েই ফালাইলি!',
        tone: 'funny',
        effects: { happiness: -20, looks: -10 },
      },
    ],
  },
  {
    id: 'child_exam_math_fail',
    text: 'অঙ্কের ক্লাসে স্যার খাতা ফেরত দিয়া ডাক দিলো: "এই নবাবের ব্যাটা, তুই তো আন্ডা পাইছস, খাঁটি ঘোড়ার ডিম!"',
    minAge: 9,
    maxAge: 12,
    weight: 8,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'hide_report_card',
        text: 'আম্মার সই নিজেই বাটপারি কইরা খাতায় বসায়ে দে!',
        outcomeText: 'আম্মার সই জাল করতে গিয়া কলমের কালি ভাইঙ্গা পুরা মুখে মাখামাখি! আব্বা ধইরা তোরে কানমলা দিয়া বাথরুমে মুরগা বানাইয়া রাখলো!',
        tone: 'bad',
        effects: { health: -15, happiness: -25, karma: -15 },
      },
      {
        id: 'cry_and_study',
        text: 'ফ্যাঁচফ্যাঁচ কইরা কাইন্দা প্রতিজ্ঞা কর: "সামনে ফাটাফাটি রেজাল্ট করমু!"',
        outcomeText: 'কান্দতে গিয়া নাকের বিশাল একখান সর্দি গিলা ফেললি! স্যার ঘিন্না খায়া তোরে ক্লাস থিকা বাইর কইরা দিলো!',
        tone: 'funny',
        effects: { smarts: 5, happiness: -15, looks: -20 },
      },
    ],
  },
  {
    id: 'child_street_food_chotpoti',
    text: 'স্কুল ছুটির পর গেটের সামনে মামার ঝাল ঝাল চটপটির ঘ্রাণে তোর নাকের লোম খাড়া হইয়া গেছে!',
    minAge: 7,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'eat_double_spicy',
        text: 'টিফিনের পুরা ট্যাকা দিয়া এক্সট্রা টক-ঝাল ফুচকা গিল!',
        outcomeText: 'এক্সট্রা টক খায়া তোর পাতলা পায়খানা! বাথরুমে যাওয়ার আগেই প্যান্টে হাগু, পুরা স্কুল তোর গু-এর গন্ধে বেহুঁশ!',
        tone: 'bad',
        effects: { happiness: -20, health: -25, money: -30, fame: -20 },
      },
      {
        id: 'save_money',
        text: 'জিভে জল আইলেও লোভ সামলায়া বাড়ি চইলা যা!',
        outcomeText: 'লোভ সামলাইতে গিয়া তোর জিহ্বা দিয়া এক বালতি লালা বাইর হইলো! লালা পইড়া তোর জুতা পিছলা হইয়া ড্রেনে আছাড় খাইলি!',
        tone: 'funny',
        effects: { health: -10, happiness: -15, looks: -10 },
      },
    ],
  },
  {
    id: 'child_carrom_cheat',
    text: 'ক্লাবের ক্যারাম বোর্ডে লাস্ট গুটি নেওয়ার সময় দোস্ত তোরে কইলো, "তুই তো হাত নাড়াইছস, ফাউল!"',
    minAge: 9,
    maxAge: 12,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'argue_loudly',
        text: 'বোর্ডের উপর থাপ্পর মাইরা ক: "তুই কানা নাকি রে ফইন্নি?"',
        outcomeText: 'তুই চিল্লায়া ফাপড় নিতে গেলি, আর পোলাপাইন তোরে ধইরা বোর্ডের বরিক পাউডার তোর মুখে মাইখা ভূত বানায়া দিলো!',
        tone: 'bad',
        effects: { happiness: -15, karma: -10, looks: -20 },
      },
      {
        id: 'rematch',
        text: 'ভাব নিয়া ক: "চল আরেক দান খেলি, দুধ কা দুধ পানি কা পানি হইবো!"',
        outcomeText: 'রিম্যাচ খেলতে গিয়া তুই স্ট্রাইকার দিয়া নিজের আঙ্গুল এমুন থ্যাঁতলাইলি, নখ উইঠা গেলো! তুই কাইন্দা পুরাই লেডিজ!',
        tone: 'funny',
        effects: { health: -15, happiness: -10, smarts: -5 },
      },
    ],
  },
  {
    id: 'child_rainy_football',
    text: 'ঝুম বৃষ্টি নামছে! আরমানিটোলার মাঠে পানি জইমা এক হাঁটু কাদা। তুই খালি গায়ে ফুটবল পিটাইতে নামছোস!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'dive_slide_tackle',
        text: 'কাদায় ডাইভ দিয়া এমুন একখান স্লাইড মারলি যে গোলকিপার সহ জালে!',
        outcomeText: 'স্লাইড মারতে গিয়া কুকুরের তাজা হাগুর উপ্রে ডাইরেক্ট মুখ ঘইষা গেলি! পুরাই গু-মাখা মারাদোনা তুই!',
        tone: 'bad',
        effects: { happiness: -10, looks: -30, health: -10 },
      },
      {
        id: 'stand_goalie',
        text: 'কাদা কম লাগাইতে গোলকিপার হইয়া পোস্টের তলায় দাঁড়া!',
        outcomeText: 'গোল ঠেকাইতে গিয়া বল ডাইরেক্ট তোর অন্ডকোষে হিট করলো! তুই ব্যথায় কোঁকাইতে কোঁকাইতে কাদার মইধ্যে কাইত!',
        tone: 'funny',
        effects: { health: -25, happiness: -20, looks: -5 },
      },
    ],
  },
  {
    id: 'child_bicycle_crash',
    text: 'বড় ভাইয়ের ফিনিক্স সাইকেল নিয়া পাড়ার ঢালে স্পিডে নামতে গিয়া ব্রেক ফেইল! চান্দি গরম অবস্থা!',
    minAge: 10,
    maxAge: 12,
    weight: 7,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'jump_to_drain',
        text: 'সাইকেল ছাইড়া পাশের ড্রেনে ডাইভ দে!',
        outcomeText: 'ড্রেনে ডাইভ দিয়া মরা ইঁদুরের লগে তোর ফেস-টু-ফেস দেখা! গন্ধে তুই বমি কইরা ড্রেন ভাসাইলি!',
        tone: 'funny',
        effects: { health: -15, smarts: 5, looks: -25 },
      },
      {
        id: 'hit_vegetable_cart',
        text: 'সরাসরি সবজির ভ্যানে গিয়া গুঁতা মার!',
        outcomeText: 'পচা টমেটো আর কুমড়ার ভর্তা হইয়া গেলি! সবজিয়ালা তোরে দিয়াই সবজি চাটাইয়া পরিষ্কার করাইলো, পুরাই চাকর তুই!',
        tone: 'bad',
        effects: { health: -15, happiness: -25, money: -50 },
      },
    ],
  },
  {
    id: 'child_science_fair',
    text: 'স্কুলের বিজ্ঞান মেলায় আলুর ব্যাটারি দিয়া লাইট জ্বালাইতে গিয়া উল্টা শর্টসার্কিট হইয়া ধোঁয়া বাইর হইলো!',
    minAge: 10,
    maxAge: 12,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'explain_magic',
        text: 'চাপাবাজি কইরা স্যাররে ক: "স্যার, এটা তো ম্যাজিক ধোঁয়ার প্রজেক্ট!"',
        outcomeText: 'স্যার ফাপড় ধইরা তোরে কারেন্টের তার দিয়া ছ্যাঁকা দিলো! তুই লাফাইয়া পুরা প্রজেক্ট ভাইঙ্গা ফেললি!',
        tone: 'bad',
        effects: { smarts: -10, happiness: -20, health: -10 },
      },
      {
        id: 'embarrassed_run',
        text: 'লজ্জায় টেবিলের তলে গিয়া লুকায়া থাক!',
        outcomeText: 'টেবিলের তলে গিয়া লুকাইতে গিয়া স্যারের প্যান্ট টাইন্না খুইলা ফালালি! স্যার পুরাই ন্যাংটা, তুই স্কুল থিকা ডাইরেক্ট রাস্টিকেট!',
        tone: 'funny',
        effects: { happiness: -30, karma: -20, fame: 20 },
      },
    ],
  },
  {
    id: 'child_eid_cow_market',
    text: 'কোরবানির ঈদের আগে বাপের লগে গাবতলীর হাটে গেছস। বিশাল এক লাল পাহলওয়ান গরু দেইখা ভয় লাগতাছে!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    requiredFlags: ['religion_muslim'],
    tags: ['islam'],
    choices: [
      {
        id: 'feed_grass',
        text: 'বুক ফুলাইয়া গরুর মুখে সবুজ ঘাস তুইলা দে!',
        outcomeText: 'গরু ঘাস না খায়া তোর হাত চাইটা দিলো! গরুর লালায় তোর পুরা হাত ভিজা, তুই বমি কইরা আব্বার লুঙ্গি নষ্ট করলি!',
        tone: 'funny',
        effects: { happiness: -10, health: -5, looks: -15 },
      },
      {
        id: 'scared_backtrack',
        text: 'গরুর গর্জন শুইনা বাপের লুঙ্গি টাইন্যা চিল্লান দে!',
        outcomeText: 'ডরে তুই গরুর গোবরের উপ্রে স্লিপ কাইটা চিৎ হইয়া পড়লি! পুরা পিঠ গোবর-মাখা, বেপারীরা হাসতে হাসতে বেহুঁশ!',
        tone: 'bad',
        effects: { happiness: -20, looks: -25, fame: -10 },
      },
    ],
  },
  {
    id: 'child_shankharibazar_puja',
    text: 'শাঁখারীবাজারে দুর্গাপূজার ধুমধাম! চারদিকে ঢাকের বাদ্য আর ধুনুচি নাচের গন্ধ। তুই মণ্ডপে গেছস!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    requiredFlags: ['religion_hindu'],
    tags: ['hinduism'],
    choices: [
      {
        id: 'dhunuchi_dance',
        text: 'ঢাকের তালে ধুনুচি হাতে উরাধুরা নাচন দে!',
        outcomeText: 'নাচতে গিয়া ধুনুচির জ্বলন্ত কয়লা তোর প্যান্টের ভিতরে ঢুকলো! পাছা পুইড়া তুই এমুন লাফ দিলি, পুরা মন্ডপে তুই ভাইরাল!',
        tone: 'funny',
        effects: { happiness: -15, health: -20, fame: 20 },
      },
      {
        id: 'eat_prasad',
        text: 'কাড়াকাড়ি কইরা খিচুড়ি প্রসাদের লাইনে গিয়া ঢোক!',
        outcomeText: 'কাড়াকাড়ি কইরা খাইতে গিয়া গলার ভিতরে খিচুড়ি আটকাইয়া চোখ বাইর হইয়া গেলো! মাইনষে পিঠে কিল মাইরা তোর জান বাঁচাইলো!',
        tone: 'bad',
        effects: { health: -15, happiness: -10, looks: -5 },
      },
    ],
  },
  {
    id: 'child_marbles_gulti_game',
    text: 'গলির মোড়ে মার্বেল খেলা! তোর নিশানা বরাবর দোস্তগো চকচকা কাঁচের মার্বেল সাজানো!',
    minAge: 7,
    maxAge: 11,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'aim_bullseye_marble',
        text: 'এক চোখ বুইজা আঙ্গুল ছিটকায়া বুলেট শট মার!',
        outcomeText: 'গুলি মারতে গিয়া মার্বেল পিছলায়া তোর নিজের দাঁতে লাইগা দাঁত ভাইঙ্গা গেলো! ফোকলা দাঁতে তুই এহন পুরাই চুদির ভাই!',
        tone: 'bad',
        effects: { health: -20, happiness: -25, looks: -25 },
      },
      {
        id: 'miss_marble_dust',
        text: 'হাতের কাঁপুনিতে মার্বেল ডাইরেক্ট ড্রেনে ফালায়া দে!',
        outcomeText: 'মার্বেল ড্রেনে ফালায়া তুই ড্রেনে হাত ঢুকাইলি! হাত বাইর কইরা দেখস একতাল গু তোর হাতে! দোস্তরা তোরে গু-মামা ডাকতাছে!',
        tone: 'funny',
        effects: { happiness: -20, looks: -30, fame: -10 },
      },
    ],
  },
  {
    id: 'child_lattu_spinning',
    text: 'নতুন কাঠের লাটিমে সুতলি প্যাঁচায়া মাটিতে স্পিন করানোর কেরামতি দেখাইতাছস!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'spin_on_palm',
        text: 'ঘুরন্ত লাটিম এক টানে হাতের তালুতে তুইলা ফাপড় নে!',
        outcomeText: 'তালুতে লাটিম ঘুরাইতে গিয়া লাটিমের পেরেক তোর তালু ফুটা কইরা দিলো! রক্ত দেইখা তুই প্যান্টে মুইতা দিলি!',
        tone: 'bad',
        effects: { health: -20, happiness: -25, smarts: -5 },
      },
      {
        id: 'hit_friends_toe',
        text: 'ছোঁড়ার সময় কন্ট্রোল হারায়া দোস্তের বুড়ো আঙ্গুলে ডাইরেক্ট হিট কর!',
        outcomeText: 'দোস্তের আঙ্গুলে লাইগা দোস্ত এমুন চিল্লান দিলো, ওর মা আইসা তোর কান এমুন মলা দিলো যে কান ছিঁড়া হাতে চইলা আসলো!',
        tone: 'bad',
        effects: { health: -10, karma: -20, happiness: -15 },
      },
    ],
  },
  {
    id: 'child_goli_cricket_six_sewer',
    text: 'তোর একখান উরাধুরা বাঘা শটে ক্রিকেট বল সটান গিয়া পড়লো গলির খোলা নর্দমায়!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'fish_ball_with_stick',
        text: 'লাঠি দিয়া কাদা-প্যাঁক ঘেঁইটা বল উদ্ধার কর!',
        outcomeText: 'বল বাইর কইরা তুই ওই গু-মাখা বল দিয়াই খেলা শুরু করলি! বোলিং করতে গিয়া তোর পুরা মুখে গু ছিইটা পড়লো!',
        tone: 'funny',
        effects: { health: -15, looks: -25, happiness: -20 },
      },
      {
        id: 'force_younger_kid',
        text: 'ছোট এক পিচ্চিরে ধমক দিয়া ড্রেনে নামাইয়া দে!',
        outcomeText: 'পিচ্চিরে ড্রেনে নামাইতে গিয়া তুই নিজেই পিছলায়া ড্রেনে পড়লি! মাইনষে তোরে ড্রেন থিকা তুইলা ধুইয়া পিটাইলো!',
        tone: 'bad',
        effects: { karma: -25, health: -10, happiness: -30 },
      },
    ],
  },
  {
    id: 'child_dhol_ramadan_sehri',
    text: 'রোজার মাসে রাইত সাড়ে তিনটায় সেহরির কাসিদা আর ঢোলের আওয়াজে ঘুম ভাঙলো: "উঠো রোযাদার...!"',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'wake_up_sehri_kacchi',
        text: 'চোখ কচলায়া টেবিলে গিয়া ঘুমন্ত অবস্থায় মাংসের ঝোল দিয়া ভাত খা!',
        outcomeText: 'কাচ্চি খাইতে গিয়া ঘুমের চোটে তুই ভাতের বদলে প্লেটের হাড্ডি গিলা ফেললি! গলায় হাড্ডি আটকাইয়া এমুন চিল্লান দিলি, পুরা মহল্লা উইঠা গেলো!',
        tone: 'bad',
        effects: { health: -20, happiness: -15, smarts: -10 },
      },
      {
        id: 'pull_blanket_sleep',
        text: 'লেপ মুড়ি দিয়া কানের ভিতর বালিশ গুঁইজা ঘুম দে!',
        outcomeText: 'লেপ মুড়ি দিয়া ঘুমাইলি, সকালে উইঠা ক্ষিধায় তুই নিজের প্যান্ট কামড়াইয়া ছিঁড়া ফেললি! রোজার দিন তুই পুরাই পাগলা কুত্তা!',
        tone: 'funny',
        effects: { happiness: -20, looks: -10, health: -10 },
      },
    ],
  },
  {
    id: 'child_pigeon_whistle_roof',
    text: 'বড় চাচার লগে আরমানিটোলার ছাদে গিয়া গিরিবাজ কবুতর উড়াইয়া শিস বাজাইতাছস!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'whistle_loud_catch_pigeon',
        text: 'জোরসে বাঁশি বাজা: অন্যের একখান লাল-চিলে কবুতর ধইরা ফ্যাল!',
        outcomeText: 'কবুতর ধরতে গিয়া কবুতর তোর ডাইরেক্ট হা করা মুখে হাগু কইরা দিলো! তুই ফ্রেশ কবুতরের গু খায়া বমি কইরা পুরা ছাদ ভাসাইলি!',
        tone: 'funny',
        effects: { health: -15, happiness: -20, looks: -20 },
      },
      {
        id: 'slip_on_moss',
        text: 'ছাদের শেওলায় পা পিছলায়া আলতো আছাড় খা!',
        outcomeText: 'পিছলা খায়া তুই ডাইরেক্ট ছাদের কিনারা থিকা ঝুইলা পড়লি! চাচা তোর প্যান্ট ধইরা টান মারলো, প্যান্ট খুইলা তুই ন্যাংটা হইয়া বাঁচলি!',
        tone: 'bad',
        effects: { health: -10, happiness: -30, looks: -30 },
      },
    ],
  },
  {
    id: 'child_shakhari_bazar_shankha',
    text: 'শাঁখারীবাজারের সরু গলিতে শাঁখা কাটার টুংটাং শব্দ আর বাজনার সুরে তুই বাপের লগে খাড়াইয়া আছোস!',
    minAge: 6,
    maxAge: 12,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'blow_conch_shell',
        text: 'দোকানের একখান শাঁখ মুখে নিয়া ফুঁ মারার ফাপড় নে!',
        outcomeText: 'ফুঁ দিতে গিয়া তোর সর্দি আর থুতু মিইলা শাঁখের ভিতরে এমুন জ্যাম লাগলো, শাঁখ থিকা প্যাঁক কইরা আওয়াজ বাইর হইলো! দোকানদার তোরে ঝাড়ু দিয়া পিটাইলো!',
        tone: 'bad',
        effects: { happiness: -20, looks: -15, karma: -10 },
      },
      {
        id: 'eat_sweet_sandesh',
        text: 'পাশের মিষ্টির দোকান থিকা ক্ষীরকদম্ব গিল্যা ফ্যাল!',
        outcomeText: 'মিষ্টি খাইতে গিয়া দেখস ভিতরে জ্যান্ত তেলাপোকা! তুই তেলাপোকা অর্ধেক চাবাইয়া ফেলছোস! বমি কইরা পুরা শাঁখারীবাজার ভাসাইলি!',
        tone: 'funny',
        effects: { health: -25, happiness: -30, money: -20 },
      },
    ],
  },
  {
    id: 'child_chowk_bazar_iftar_chola',
    text: 'চকবাজারের ইফতারির বাজারে আব্বার হাত ধইরা বড় বাপের পোলায় খায় কিনতে গেছস! পুরাই চিপা অবস্থা!',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'taste_boro_bap',
        text: 'তেল-মশলা মাখানো স্পেশাল ইফতারি ধইরা চেখে দ্যাখ!',
        outcomeText: 'খাইতে গিয়া কড়া ঝালে তোর নাক-কান দিয়া ধোঁয়া বাইর হইলো! পানি খাইতে গিয়া তুই অন্যের শরবতের গ্লাসে মুখ লাগাইয়া লাথি খাইলি!',
        tone: 'bad',
        effects: { health: -15, happiness: -20, karma: -10 },
      },
      {
        id: 'lost_in_crowd',
        text: 'ভিড়ের চোটে আব্বার হাত ছাইড়া এদিক-ওদিক তাকাও!',
        outcomeText: 'আব্বার হাত ছাইড়া তুই এক হিজড়ার শাড়ি ধইরা টান দিলি! হিজড়ারা তোরে ধইরা এমুন ড্যান্স দেওয়াইলো, তোর ইজ্জতের ফালুদা!',
        tone: 'funny',
        effects: { happiness: -30, looks: -20, fame: 15 },
      },
    ],
  },
  {
    id: 'child_school_punishment_murga',
    text: 'পড়াশোনায় ফাঁকি দেওয়ায় কড়া স্যার তোরে কান ধইরা ডেস্কে মুরগা বানায়া রাখলো!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'endure_murga',
        text: 'দাঁত কামড়াইয়া কান ধইরা মুরগা হইয়া থাক!',
        outcomeText: 'মুরগা হইয়া থাকতে গিয়া তুই এমুন বিকট শব্দে পাদ দিলি, পুরা ক্লাস গন্ধে স্কুল ছুটি দিয়া দিলো! তুই পুরাই গ্যাস-চেম্বার!',
        tone: 'funny',
        effects: { smarts: -5, health: -5, happiness: -25, fame: 20 },
      },
      {
        id: 'fake_faint_floor',
        text: 'চোখ উল্টাইয়া মেঝেতে মাথা ঘুরায়া পড়ার ভান কর!',
        outcomeText: 'অজ্ঞান হওয়ার ভান করতে গিয়া তুই আসলিতেই ডেস্কে মাথা ঠুইকা বেহুঁশ! উইঠা দেখস তোর মাথা ফুইলা এক্কেরে তরমুজ!',
        tone: 'bad',
        effects: { health: -25, smarts: -10, happiness: -20 },
      },
    ],
  },
  {
    id: 'child_ice_cream_bell_chase',
    text: 'দুপুরের কড়া রোদে গলিতে কুলফি মালাইওয়ালার টিংটিং ঘণ্টার আওয়াজে তোর লালা বাইর হইতাছে!',
    minAge: 6,
    maxAge: 10,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'buy_kulfi_malai',
        text: 'মাটির ভাঁড়ের মালাই কুলফি কিন্না কুত্তার লাহান চাইটা খা!',
        outcomeText: 'কুলফি খাইতে গিয়া তোর জিহ্বা বরফের লগে আটকায়া গেলো! টান মারতে গিয়া জিহ্বার ছাল উইঠা রক্তারক্তি!',
        tone: 'bad',
        effects: { health: -20, happiness: -15, money: -20 },
      },
      {
        id: 'drop_ice_cream',
        text: 'দৌড়াইতে গিয়া কুলফি মাটিতে ফালায়া ছ্যাব্রা কর!',
        outcomeText: 'কুলফি মাটিতে পইড়া গেলো, তুই ওই কাদা-মাখা কুলফিটাই চাইটা খাইলি ফইন্নির লাহান! পোলাপাইন দেইখা তোরে "গু-খোর" উপাধি দিলো!',
        tone: 'funny',
        effects: { happiness: -30, looks: -25, money: -20 },
      },
    ],
  },
  {
    id: 'child_monsoon_paper_boat_race',
    text: 'রাস্তায় বৃষ্টির পচা পানি জইমা একাকার। দোস্তগো লগে খাতার পাতা ছিঁড়া নৌকা বানাইলি!',
    minAge: 7,
    maxAge: 11,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'speed_boat_craft',
        text: 'ডাবল ভাঁজ দিয়া স্পিডবোট বানাইয়া পচা পানিতে ছাড়!',
        outcomeText: 'নৌকা ছাড়তে গিয়া তুই ড্রেনের পচা ম্যানহোলে ডাইরেক্ট পইড়া গেলি! গু-মুত খায়া তুই যখন উঠলি, মাইনষে ভাবলো তুই ড্রেনের ড্রাকুলা!',
        tone: 'bad',
        effects: { health: -25, happiness: -20, looks: -30 },
      },
      {
        id: 'tear_math_homework',
        text: 'ভুল কইরা অঙ্কের হোমওয়ার্কের পাতা ছিঁড়া নৌকা বানা!',
        outcomeText: 'অঙ্কের খাতা ছিঁড়তে গিয়া তুই ভুলে আব্বার অফিসের দরকারী ফাইল ছিঁড়া নৌকা বানাইলি! রাইতে তোর পাছায় আব্বা এমুন বেল্ট মারলো, তুই বইতে পারস না!',
        tone: 'bad',
        effects: { health: -20, happiness: -30, smarts: -15 },
      },
    ],
  },
  {
    id: 'child_bhuter_golpo_rooftop',
    text: 'লোডশেডিংয়ের রাইতে ছাদে শীতলপাটি বিছাইয়া কাজিনরা মিল্লা পেত্নীর গল্প শুনতাছস!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'make_ghost_sound',
        text: 'আন্ধারে আচমকা "হুপ্প্প" কইরা কাজিনগো ভয় দেখা!',
        outcomeText: 'ভয় দেখাইতে গিয়া তুই অন্ধকারে হোঁচট খায়া ডাইরেক্ট ছাদের পানির ট্যাংকের ভিতরে পড়লি! মাইনষে ভাবলো আসল ভূত আইছে, কেউ তোরে তুইলা আনলো না!',
        tone: 'funny',
        effects: { health: -15, happiness: -20, karma: -10 },
      },
      {
        id: 'scared_pee_pants',
        text: 'পেত্নীর গল্প শুইনা ডরে কাঁপতে কাঁপতে ঘরে দৌড় দে!',
        outcomeText: 'ডরে তুই প্যান্টেই হাগু-মুত একাকার কইরা দিলি! গন্ধে কাজিনরা তোরে ছাদ থিকা লাথি দিয়া নিচে পাঠায়া দিলো!',
        tone: 'bad',
        effects: { happiness: -30, health: -10, looks: -25 },
      },
    ],
  },
  {
    id: 'child_stray_dog_bark_run',
    text: 'স্কুল থিকা ফিরনের টাইমে পাড়ার কালু কুত্তা তোরে দেইখা সজোরে ঘেউ ঘেউ কইরা তেড়ে আসলো!',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'pretend_pick_stone',
        text: 'মাটি থিকা ইট তোলার ফাপড় নে হালায়!',
        outcomeText: 'ইট তুলতে গিয়া তুই তাজা গোবরে হাত ঢুকাইলি! গোবর দিয়া কুত্তারে মারতে গিয়া তোর নিজের মুখেই গোবর ছিইটা পড়লো!',
        tone: 'funny',
        effects: { smarts: -5, happiness: -25, looks: -20 },
      },
      {
        id: 'run_screaming',
        text: 'পিছনে না তাকায়া উসাইন বোল্ট সাইজা দৌড় মার!',
        outcomeText: 'দৌড়াইতে গিয়া তুই এক্কেরে কাদার মইধ্যে স্লাইড খাইলি! কুত্তা তোর উপ্রে আইসা মুইতা দিয়া গেলো! তুই পুরাই টয়লেট!',
        tone: 'bad',
        effects: { health: -15, looks: -30, happiness: -30 },
      },
    ],
  },
  {
    id: 'child_chandan_teep_wedding',
    text: 'মামার গায়ে হলুদে তোরে জরিদার পাঞ্জাবি পরাইয়া চন্দনের ফোঁটা দেওয়া হইলো, তুই পুরাই বান্দর!',
    minAge: 6,
    maxAge: 10,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'pose_for_dslr',
        text: 'ক্যামেরাম্যানের সামনে দাঁড়াইয়া আলগা পোজ দে!',
        outcomeText: 'পোজ দিতে গিয়া তুই স্টেজ থিকা উল্টায়া ডাইরেক্ট হলুদের বালতিতে! তুই পুরাই জ্যান্ত কাঁচামরিচ-হলুদ বাটা হইয়া গেলি!',
        tone: 'funny',
        effects: { looks: -25, happiness: -20, fame: 15 },
      },
      {
        id: 'smear_haldi_cousin',
        text: 'হলুদের বাটি থিকা হলুদ নিয়া কাজিনের নাকে ঘইষা দে!',
        outcomeText: 'কাজিন তোর প্যান্টের ভিতরে হলুদ ভইরা দিলো! জ্বলুনিতে তুই ন্যাংটা হইয়া পুরা বিয়া বাড়ি দৌড়াদৌড়ি করলি!',
        tone: 'bad',
        effects: { happiness: -30, karma: -15, looks: -20 },
      },
    ],
  },
  {
    id: 'child_gollachut_borofpani',
    text: 'বিকেলে স্কুলের মাঠে বরফ-পানি খেলা! তুই দলের লাস্ট প্লেয়ার, সবাই তোর দিকে তাকায়া আছে!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'sprint_touch_line',
        text: 'বাতাসের বেগে দৌড়াইয়া দাগ ছুঁইয়া ফ্যাল!',
        outcomeText: 'দৌড়াইতে গিয়া তোর প্যান্ট ফাইট্টা এক্কেরে চুরমার! পুরা স্কুলের পোলাপাইনের সামনে তোর ন্যাংটা পাছা ভাইরাল!',
        tone: 'funny',
        effects: { health: 5, happiness: -20, looks: -30 },
      },
      {
        id: 'get_tagged_out',
        text: 'দম ফুরায়া দাগের দুই হাত আগে ধরা খায়া বরফ হ!',
        outcomeText: 'বরফ হইয়া খাড়ায়া আছোস, এক কুত্তা আইসা তোর পায়ে ঠ্যাং তুইলা মুইতা দিলো! তুই নড়তেও পারলি না, পুরাই স্ট্যাচু অব হাগু!',
        tone: 'bad',
        effects: { health: -10, happiness: -25, looks: -20 },
      },
    ],
  },
  {
    id: 'child_pickpocket_circus_fair',
    text: 'লালবাগের মেলায় নাগরদোলা দেইখা দিল খুশ! পকেটে বাপের দেওয়া ৫০ ট্যাকার কড়কড়া নোট!',
    minAge: 7,
    maxAge: 12,
    weight: 7,
    tone: 'neutral',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'ride_nagordola',
        text: 'উঁচু কাঠের নাগরদোলায় উইঠা আসমানে ডানা মেল!',
        outcomeText: 'নাগরদোলা থিকা তোর পেটের সব ফুচকা বমি হইয়া নিচের পাবলিকের মাথায় পড়লো! পাবলিক তোরে ধইরা এমুন পিটাইলো, তুই ছিলা মুরগি!',
        tone: 'bad',
        effects: { happiness: -30, money: -30, health: -20 },
      },
      {
        id: 'buy_tin_pistol',
        text: 'পটকা ফুটার টিনের রিভলবার কিন্না ফুটানি মার!',
        outcomeText: 'পটকা ফুটাইতে গিয়া তোর প্যান্টে আগুন ধইরা গেলো! তুই কান্দতে কান্দতে ড্রেনের পানিতে বইসা আগুন নিভাইলি!',
        tone: 'funny',
        effects: { happiness: -20, money: -40, health: -15 },
      },
    ],
  },
  {
    id: 'child_dadi_pickles_stealing',
    text: 'দুপুরে দাদীর রোদে দেওয়া কাঁচা আমের তেলের আচারের বয়াম ছাদে চকচক করতাছে!',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'steal_pickle_spoon',
        text: 'চুপিসারে বয়ামের ঢাকনা খুইলা গপাগপ আচার গিল!',
        outcomeText: 'খাইতে গিয়া আচারের কড়া ঝাল ডাইরেক্ট তোর নাকে ঢুকলো! তুই এমুন হাঁচি দিলি যে দাদীর পুরা আচারের বয়াম ভাইঙ্গা ছ্যাব্রা! দাদী তোরে ঝাড়ুপেটা করলো!',
        tone: 'bad',
        effects: { happiness: -25, health: -15, karma: -20 },
      },
      {
        id: 'cover_with_net',
        text: 'কাক যাতে মুখ না দেয় তাই জাল ভালো কইরা বাঁইধা দে!',
        outcomeText: 'ভালো সাজতে গিয়া তুই বয়ামের ভিতরে কাকের হাগু দেইখা ফালাইলি! দাদী তোরে ওই হাগু-মাখা আচারই জোর কইরা খাওয়াইলো! তুই বমি কইরা শেষ!',
        tone: 'funny',
        effects: { karma: -5, happiness: -30, health: -20 },
      },
    ],
  },
];