import type { LifeEventDef } from '@/lib/engine/types';

export const CHILD_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'child_window_glass_break',
    text: 'গলির মইধ্যে টেপ-টেনিস ক্রিকেট খেলতে গিয়া তোর সোজা ছক্কায় খবির চাচার ড্রয়িংরুমের কাঁচ ফাইট্টা চৌচির!',
    minAge: 7,
    maxAge: 12,
    weight: 9,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'run_usain_bolt',
        text: 'উসাইন বোল্টের লাহান এক্কেবারে চোখের পলকে দৌড়াইয়া ভাগ!',
        outcomeText: 'চাচার হাত থিকা তো বাঁচলি, কিন্তু ব্যাটটা গলির মইধ্যে পইড়া রইলো।',
        tone: 'funny',
        effects: { happiness: 5, karma: -8 },
      },
      {
        id: 'confess_apologize',
        text: 'কান ধইরা চাচার সামনে দাঁড়া: "ভুল হইয়া গেছে চাচা!"',
        outcomeText: 'চাচা বাপের কাছে বিচার দিলো, আব্বা কাঁচের দাম দিল আর তোর পিঠে ধুমধাম কিল পড়লো!',
        tone: 'bad',
        effects: { health: -6, happiness: -10, karma: 10 },
      },
      {
        id: 'blame_bowler',
        text: 'বোলারের দিকে আঙ্গুল তুইলা ক: "হালায় নো-বল করছিল!"',
        outcomeText: 'দুই দলে তুমুল গ্যাঞ্জাম শুরু হইলো, খেলা পণ্ড!',
        tone: 'bad',
        effects: { smarts: 4, karma: -5 },
      },
    ],
  },
  {
    id: 'child_raw_mango_theft',
    text: 'দুপুরে কড়া রোদে বড় বাড়ির আম গাছে ঝুলন্ত কাঁচা আম দেইখা জিভে পানি চইলা আসছে!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'throw_brick',
        text: 'আধলা ইট মারিয়া কড়ার ডাল থিকা আম নামা',
        outcomeText: 'ধপাস কইরা দুইটা আম পড়লো! লবণ-মরিচ দিয়া মাখায়া খাইতে পুরাই অমৃত!',
        tone: 'good',
        effects: { happiness: 15, health: -2 },
      },
      {
        id: 'climb_tree',
        text: 'বান্দরের লাহান গাছে উইঠা আম পাড়',
        outcomeText: 'ডাল ভাইঙ্গা নিচে পড়লি, প্যান্ট ছিঁড়লো কিন্তু ব্যাগে পাঁচটা আম!',
        tone: 'funny',
        effects: { health: -5, happiness: 10, smarts: 5 },
      },
    ],
  },
  {
    id: 'child_kite_roof_battle',
    text: 'পৌষ সংক্রান্তিতে পুরান ঢাকার ছাদে ঘুড়ি লড়াই! তোর চিল ঘুড়ি পাশের বাড়ির পঙ্খীরাজের লগে প্যাঁচ খাইছে!',
    minAge: 9,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'pull_hard_manja',
        text: 'ধারালো সুতা দিয়া সজোরে একখান হ্যাঁচকা টান মার!',
        outcomeText: 'ভোকাট্টা! বিপক্ষের ঘুড়ি কাইটা আকাশে হারাইলো, পুরা ছাদে জয়োল্লাস!',
        tone: 'good',
        effects: { happiness: 18, smarts: 6 },
      },
      {
        id: 'let_loose',
        text: 'সুতা হালকা ছাইড়া দিয়া কৌশলে প্যাঁচ কাটাও',
        outcomeText: 'তোর সুতাই কাইটা গেল। পাশের বাড়ির পোলাপাইন মুখে ভেঙচি কাটলো।',
        tone: 'bad',
        effects: { happiness: -8 },
      },
    ],
  },
  {
    id: 'child_exam_math_fail',
    text: 'অঙ্কের ক্লাসে স্যার খাতা ফেরত দিয়া ডাক দিলো: "এই নবাবের ব্যাটা, এইদিকে আয়! তুই তো খাঁটি রসগোল্লা পাইছস!"',
    minAge: 9,
    maxAge: 12,
    weight: 8,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'hide_report_card',
        text: 'আম্মার সই নিজেই জাল কইরা খাতায় বসায়া দে',
        outcomeText: 'সই দেইখা আম্মার চোখ কপালে! হাতেনাতে ধরা খাইয়া ডালের চামচের বাড়ি জুটলো।',
        tone: 'bad',
        effects: { health: -8, happiness: -12, karma: -10 },
      },
      {
        id: 'cry_and_study',
        text: 'কান্দাকাটি কইরা প্রতিজ্ঞা কর: "সামনে ফাটাফাটি রেজাল্ট করমু!"',
        outcomeText: 'আম্মার দয়া হইলো, কাচ্চি খাওয়াইয়া প্রাইভেট মাস্টারের কড়া নজরদারিতে দিলো।',
        tone: 'neutral',
        effects: { smarts: 12, happiness: -4 },
      },
    ],
  },
  {
    id: 'child_street_food_chotpoti',
    text: 'স্কুল ছুটির পর গেটের সামনে মামার ঝাল ঝাল চটপটি আর ফুচকার ঘ্রাণে মাথা নষ্ট!',
    minAge: 7,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'eat_double_spicy',
        text: 'টিফিনের পুরা ট্যাকা দিয়া এক্সট্রা টক-ঝাল ফুচকা খাও',
        outcomeText: 'স্বাদে পুরাই আগুন! কিন্তু রাইতে পেটের ভিতর ঢোলের আওয়াজ শুরু হইলো।',
        tone: 'funny',
        effects: { happiness: 14, health: -6, money: -30 },
      },
      {
        id: 'save_money',
        text: 'জিভে জল আইলেও লোভ সামলায়া বাড়ি চইলা যাও',
        outcomeText: 'সুস্থ পেট, কিন্তু সারারাত স্বপ্নে ফুচকার বাটি দেখলি।',
        tone: 'neutral',
        effects: { health: 5, happiness: -4 },
      },
    ],
  },
  {
    id: 'child_carrom_cheat',
    text: 'ক্লাবের ক্যারাম বোর্ডে শেষ লাল গুটিটা গর্তে নেওয়ার সময় বন্ধু তোরে কইলো, "তুই তো হাত নাড়াইছস, ফাউল!"',
    minAge: 9,
    maxAge: 12,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'argue_loudly',
        text: 'বোর্ডের উপর হাত চাপড়াইয়া ক: "তুই কানা নাকি রে হালায়?"',
        outcomeText: 'তর্ক থিকা কাইজ্জা! ক্যারাম বোর্ড উল্টায়া পুরা আড্ডা ভন্ডুল।',
        tone: 'bad',
        effects: { happiness: -5, karma: -6 },
      },
      {
        id: 'rematch',
        text: 'শান্ত হইয়া ক: "চল আরেক দান খেলি, দুধ কা দুধ পানি কা পানি হইবো!"',
        outcomeText: 'পরের দানেই এক টানে বোর্ড সাফ কইরা চ্যাম্পিয়ন হইলি!',
        tone: 'good',
        effects: { happiness: 15, smarts: 8 },
      },
    ],
  },
  {
    id: 'child_rainy_football',
    text: 'ঝুম বৃষ্টি নামছে! আরমানিটোলার মাঠে পানি জইমা এক হাঁটু কাদা। পোলাপানরা খালি গায়ে ফুটবল নিয়া নামছে!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'dive_slide_tackle',
        text: 'কাদায় ডাইভ দিয়া এমন একখান স্লাইড মারলি যে গোলকিপার সহ জালে!',
        outcomeText: 'গোওওওল! মহল্লার হিরো বনে গেলি, কাদা মাখা শরীর নিয়া সবাই কাঁধে তুললো!',
        tone: 'good',
        effects: { happiness: 20, looks: -4, health: 5 },
      },
      {
        id: 'stand_goalie',
        text: 'কাদা কম লাগাইতে গোলকিপার হইয়া পোস্টের তলায় দাঁড়া',
        outcomeText: 'বৃষ্টির পানিতে ভিইজা হাঁচি দিতে দিতে ঠান্ডা লাগাইলি।',
        tone: 'bad',
        effects: { health: -8, happiness: 2 },
      },
    ],
  },
  {
    id: 'child_bicycle_crash',
    text: 'বড় ভাইয়ের ফিনিক্স সাইকেল নিয়া পাড়ার ঢালে স্পিডে নামতে গিয়া ব্রেক কড়া হইয়া কাইত হইলি!',
    minAge: 10,
    maxAge: 12,
    weight: 7,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'jump_to_drain',
        text: 'সাইকেল ছাইড়া পাশের ঘাসের ওপর লাফ দে',
        outcomeText: 'হাঁটু ছড়লো ঠিকই, কিন্তু হাড্ডি ভাঙলো না। সাইকেলের রিং একটু টাল হইলো।',
        tone: 'neutral',
        effects: { health: -5, smarts: 6 },
      },
      {
        id: 'hit_vegetable_cart',
        text: 'সরাসরি সবজির ভ্যানে গিয়া গুঁতা মার',
        outcomeText: 'টমেটোর জুস হইয়া গেলি! সবজিওয়ালা বাপের কাছ থিকা জরিমানা উশুল করলো।',
        tone: 'bad',
        effects: { health: -10, happiness: -12, money: -50 },
      },
    ],
  },
  {
    id: 'child_science_fair',
    text: 'স্কুলের বিজ্ঞান মেলায় আলুর ব্যাটারি দিয়া লাইট জ্বালাইতে গিয়া উল্টা শর্টসার্কিট হইয়া ধোঁয়া বাইর হইলো!',
    minAge: 10,
    maxAge: 12,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'explain_magic',
        text: 'কনফিডেন্স নিয়া স্যাররে ক: "স্যার, এটা তো ধোঁয়ার রকেট প্রজেক্ট!"',
        outcomeText: 'স্যার তোর উপস্থিত বুদ্ধি দেইখা হাইসা ৩য় পুরস্কার ধরাইয়া দিল!',
        tone: 'good',
        effects: { smarts: 10, happiness: 12 },
      },
      {
        id: 'embarrassed_run',
        text: 'টেবিলের তলায় লুকায়া কান্দন শুরু কর',
        outcomeText: 'বন্ধুরা ভিডিও কইরা ফেসবুকে ছাইড়া দিল। পুরা স্কুলে হাসাহাসি!',
        tone: 'bad',
        effects: { happiness: -10, looks: -5 },
      },
    ],
  },
  {
    id: 'child_eid_cow_market',
    text: 'কোরবানির ঈদের আগে বাপের লগে গাবতলীর হাটে গেছস। বিশাল এক লাল পাহলওয়ান গরু দেইখা ভয় লাগতাছে!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    requiredFlags: ['religion_muslim'],
    tags: ['islam'],
    choices: [
      {
        id: 'feed_grass',
        text: 'সাহস কইরা গরুর মুখে সবুজ ঘাস তুইলা দে',
        outcomeText: 'গরুটা তোর গাল চাইটা আদর দিলো! আব্বা তোর সাহস দেইখা খুশি!',
        tone: 'good',
        effects: { happiness: 12, karma: 8 },
      },
      {
        id: 'scared_backtrack',
        text: 'গরুর গর্জন শুইনা বাপের লুঙ্গি টাইন্যা চিল্লাইয়া ওঠ',
        outcomeText: 'বাপের লুঙ্গি প্রায় খইলা যাওয়ার উপক্রম! হাটের সব বেপারী হাসলো।',
        tone: 'funny',
        effects: { happiness: -5, looks: -4 },
      },
    ],
  },
  {
    id: 'child_shankharibazar_puja',
    text: 'শাঁখারীবাজারে দুর্গাপূজার ধুমধাম! চারদিকে ঢাকের বাদ্য আর ধুনুচি নাচের গন্ধ। মা তোরে নতুন জামা পরাইয়া মণ্ডপে নিয়া গেছেন!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    requiredFlags: ['religion_hindu'],
    tags: ['hinduism'],
    choices: [
      {
        id: 'dhunuchi_dance',
        text: 'ঢাকের তালে ধুনুচি হাতে নাচন দে',
        outcomeText: 'তোর নাচ দেইখা মণ্ডপের মুরব্বিরা প্রশংসা করলো আর পেট ভইরা নারকেলের নাড়ু খাইতে দিল!',
        tone: 'good',
        effects: { happiness: 15, fame: 5, karma: 6 },
      },
      {
        id: 'eat_prasad',
        text: 'খিচুড়ি প্রসাদের লাইনে গিয়া দাঁড়াও',
        outcomeText: 'গরম গরম খিচুড়ি আর লাবড়া খাইয়া পুরাই তৃপ্তি পাইলা!',
        tone: 'good',
        effects: { happiness: 12, health: 4 },
      },
    ],
  },
  {
    id: 'child_marbles_gulti_game',
    text: 'গলির মোড়ে মার্বেল খেলা! তোর নিশানা বরাবর বন্ধুদের চকচকা কাঁচের মার্বেল সাজানো!',
    minAge: 7,
    maxAge: 11,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'aim_bullseye_marble',
        text: 'এক চোখ বুইজা আঙ্গুল ছিটকায়া বুলেট শট মার!',
        outcomeText: 'টক্কাস! মেইন মার্বেলে লাইগা সব কাইত! পকেট ভইরা মার্বেল জিতলি!',
        tone: 'good',
        effects: { happiness: 15, smarts: 6 },
      },
      {
        id: 'miss_marble_dust',
        text: 'হাতের কাঁপনিতে মার্বেল ড্রেনে ফেল',
        outcomeText: 'নিজের মার্বেলও হারাইলি, বন্ধুদের ভেঙচি খাইয়া চোখ ছলছল!',
        tone: 'bad',
        effects: { happiness: -6 },
      },
    ],
  },
  {
    id: 'child_lattu_spinning',
    text: 'নতুন কাঠের লাটিমে সুতলি প্যাঁচায়া মাটিতে স্পিন করানোর কেরামতি দেখাইতাছস!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'spin_on_palm',
        text: 'ঘূর্ণায়মান লাটিম এক টানে হাতের তালুতে তোল!',
        outcomeText: 'হাতের তালুতে লাটিম বনবন কইরা ঘুরলো! পাড়ার পোলাপাইন ধন্য ধন্য করলো!',
        tone: 'good',
        effects: { happiness: 16, looks: 8, smarts: 5 },
      },
      {
        id: 'hit_friends_toe',
        text: 'ছোঁড়ার সময় নিয়ন্ত্রণ হারায়া দোস্তের বুড়ো আঙ্গুলে মার',
        outcomeText: 'দোস্ত চিঁহিঁহিঁ চিল্লাইয়া কান্দন শুরু করলো, লাটিম বাজেয়াপ্ত!',
        tone: 'bad',
        effects: { karma: -6, happiness: -8 },
      },
    ],
  },
  {
    id: 'child_goli_cricket_six_sewer',
    text: 'তোর একখান বাঘা শটে ক্রিকেট বল সটান গিয়া পড়লো গলির খোলা নর্দমায়!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'fish_ball_with_stick',
        text: 'লাঠি দিয়া কাদা-প্যাঁক ঘেঁটে বল উদ্ধার কর',
        outcomeText: 'বল তো উদ্ধার হইলো, কিন্তু কাপড়ে যে গন্ধ ছড়াইলো তাতে আম্মা ঘরে ঢুকতে দিলো না!',
        tone: 'funny',
        effects: { looks: -6, health: -4, happiness: 6 },
      },
      {
        id: 'force_younger_kid',
        text: 'ছোট এক পিচ্চিরে ধমক দিয়া ড্রেনে নামাও',
        outcomeText: 'পিচ্চির বড় ভাই আইসা তোরে একখান চড় বসাইলো! মাটির সাথে মিশে গেলি।',
        tone: 'bad',
        effects: { karma: -12, happiness: -10, health: -4 },
      },
    ],
  },
  {
    id: 'child_dhol_ramadan_sehri',
    text: 'রোজার মাসে রাত সাড়ে তিনটায় সেহরির কাসিদা আর ঢোলের আওয়াজে ঘুম ভাঙলো: "উঠো রোযাদার...!"',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'wake_up_sehri_kacchi',
        text: 'চোখ কচলায়া টেবিলে গিয়া গরম ভাতের লগে মাংসের ঝোল খাও',
        outcomeText: 'রোজা রাখার নিয়ত করলি। পরিবারের সবাই তোরে সাবাশ দিলো!',
        tone: 'good',
        effects: { happiness: 15, karma: 10, health: 4 },
      },
      {
        id: 'pull_blanket_sleep',
        text: 'লেপ মুড়ি দিয়া কানের ভেতর বালিশ গুজলি',
        outcomeText: 'সেহরি মিস! সকালে ক্ষুধা আর তৃষ্ণায় পেট চোঁ চোঁ করলি!',
        tone: 'neutral',
        effects: { happiness: -4, health: -2 },
      },
    ],
  },
  {
    id: 'child_pigeon_whistle_roof',
    text: 'বড় চাচার লগে আরমানিটোলার ছাদে গিয়া গিরিবাজ কবুতর উড়াইয়া শিস বাজাইতাছস!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'whistle_loud_catch_pigeon',
        text: 'জোরসে বাঁশি বাজা: অন্যের একখান লাল-চিলে কবুতর নামায়া খাঁচায় ভর!',
        outcomeText: 'কইতর শিকারে ওস্তাদ বনে গেলি! চাচা খুশিতে তোরে চানাচুর খাওয়াইলো!',
        tone: 'good',
        effects: { happiness: 18, smarts: 6 },
      },
      {
        id: 'slip_on_moss',
        text: 'ছাদের শেওলায় পা পিছলায়া আলতো আছাড় খাও',
        outcomeText: 'প্যান্টের পিছন ভেজা, তবে চাচা শক্ত হাতে ধইরা ফেলায় বিপদ কাটলো!',
        tone: 'funny',
        effects: { health: -3, looks: -2 },
      },
    ],
  },
  {
    id: 'child_shakhari_bazar_shankha',
    text: 'শাঁখারীবাজারের সরু গলিতে শাঁখা কাটার টুংটাং শব্দ আর বাজনার সুরে প্রাণ জুড়ায়া যায়!',
    minAge: 6,
    maxAge: 12,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'blow_conch_shell',
        text: 'দোকানের একখান শাঁখ মুখে নিয়া ফু মারার চেষ্টা কর',
        outcomeText: 'গাল ফুলাইয়া একখান গম্ভীর আওয়াজ তুললি! কারিগর মামা হাইসা পিঠ চাপড়াইলো!',
        tone: 'good',
        effects: { happiness: 12, health: 4 },
      },
      {
        id: 'eat_sweet_sandesh',
        text: 'পাশের মিষ্টির দোকান থিকা ক্ষীরকদম্ব খাও',
        outcomeText: 'মুখের ভিতর মিষ্টির ফোয়ারা! দিনটা পুরাই মাখন হইয়া গেল!',
        tone: 'good',
        effects: { happiness: 14, money: -20 },
      },
    ],
  },
  {
    id: 'child_chowk_bazar_iftar_chola',
    text: 'চকবাজারের ইফতারির বাজারে আব্বার হাত ধইরা বড় বাপের পোলায় খায় কিনতে গেছস!',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'taste_boro_bap',
        text: '১২ পদের মাংস আর ডিম দিয়া মাখানো স্পেশাল ইফতারি চেখে দেখ',
        outcomeText: 'স্বাদে মাতোয়ারা! ঢাকাইয়া ঐতিহ্যের আসল স্বাদ কলিজায় গেঁথে গেল!',
        tone: 'good',
        effects: { happiness: 16, health: 6 },
      },
      {
        id: 'lost_in_crowd',
        text: 'ভিড়ের চোটে আব্বার হাত ছাইড়া এক সেকেন্ড ডানে তাকাও',
        outcomeText: 'আব্বা দৌড়ায়া আইসা হাত খামচায়া ধরলো: "হারামজাদা, হারাবি নাকি!"',
        tone: 'bad',
        effects: { happiness: -8, smarts: 4 },
      },
    ],
  },
  {
    id: 'child_school_punishment_murga',
    text: 'পড়াশোনায় গাফিলতি করায় ক্লাসের কড়া শিক্ষক তোরে কান ধইরা ডেস্কে মুরগা বানায়া রাখলো!',
    minAge: 8,
    maxAge: 12,
    weight: 8,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'endure_murga',
        text: 'দাঁত কামড়ায়া কান ধইরা মুরগা হইয়া থাক',
        outcomeText: 'হাঁটুতে খিল ধইরা গেল, কিন্তু পরে পড়ায় ফাঁকি না দেওয়ার শিক্ষা হইলো।',
        tone: 'neutral',
        effects: { smarts: 10, health: -4, happiness: -10 },
      },
      {
        id: 'fake_faint_floor',
        text: 'চোখ উল্টায়া মেঝেতে মাথা ঘুরায়া পড়ার ভান কর',
        outcomeText: 'স্যার ভয় পাইয়া পানি ছিটাইলো আর ছুটি দিয়া দিলো! কিন্তু আম্মা ডাক্তার ডাকলো!',
        tone: 'funny',
        effects: { smarts: 6, happiness: 4, karma: -8 },
      },
    ],
  },
  {
    id: 'child_ice_cream_bell_chase',
    text: 'দুপুরের কড়া রোদে গলিতে কুल्फी মালাইওয়ালার টিংটিং ঘণ্টার আওয়াজ!',
    minAge: 6,
    maxAge: 10,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'buy_kulfi_malai',
        text: 'মাটির ভাঁড়ের মালাই কুल्फी কিনে জিভ দিয়া চেটে খাও',
        outcomeText: 'ঠান্ডা মালাই গলধঃকরণ কইরা কলিজা ঠান্ডা! পরমানন্দ!',
        tone: 'good',
        effects: { happiness: 15, health: 2, money: -20 },
      },
      {
        id: 'drop_ice_cream',
        text: 'দৌড়াইতে গিয়া কুल्फी মাটিতে ফেলে ছ্যাব্রা কর',
        outcomeText: 'মাটির পিঁপড়ারা ভোজ খাইলো, তুই রাস্তার মাঝে হাঁউমাউ কইরা কাঁদলি!',
        tone: 'bad',
        effects: { happiness: -12, money: -20 },
      },
    ],
  },
  {
    id: 'child_monsoon_paper_boat_race',
    text: 'সূত্রাপুরের রাস্তায় বৃষ্টির পানি জমে একাকার। বন্ধুদের সাথে খাতার পাতা ছিঁড়া নৌকা বানাইলি!',
    minAge: 7,
    maxAge: 11,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'speed_boat_craft',
        text: 'ডাবল ভাঁজ দিয়া মজবুত স্পিডবোট বানায়া স্রোতে ছাড়!',
        outcomeText: 'তোর নৌকা সবার আগে গিয়া কালভার্টে ঠেকলো! প্রথম স্থান অধিকার!',
        tone: 'good',
        effects: { happiness: 16, smarts: 8 },
      },
      {
        id: 'tear_math_homework',
        text: 'ভুল কইরা অঙ্কের হোমওয়ার্কের পাতা ছিঁড়া নৌকা বানা',
        outcomeText: 'নৌকা ভালোই ভাসলো, কিন্তু পরদিন ক্লাসে বেতের গুঁতা কপালে জুটলো!',
        tone: 'bad',
        effects: { happiness: -6, smarts: -4, health: -4 },
      },
    ],
  },
  {
    id: 'child_bhuter_golpo_rooftop',
    text: 'লোডশেডিংয়ের রাতে ছাদে শীতলপাটি বিছাইয়া কাজিনরা মিল্লা পুরান ঢাকার পুরনো বাড়ির ভূতের গল্প শুনতাছস!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'make_ghost_sound',
        text: 'অন্ধকারে আচমকা "হুপ্প্প" কইরা কাজিনদের চমকাও',
        outcomeText: 'ছোট খালাতো বোন চিল্লাইয়া ডালভাত একাকার করলো! আম্মা কান মইলা দিলো।',
        tone: 'funny',
        effects: { happiness: 10, karma: -5 },
      },
      {
        id: 'scared_pee_pants',
        text: 'পেত্নীর গল্প শুইনা ভয়ে কাঁপতে কাঁপতে ঘরে দৌড় দে',
        outcomeText: 'সারারাত বাতি জ্বালায়া ঘুমানো লাগলো, পানির পিপাসায় ছটফট করলি!',
        tone: 'bad',
        effects: { happiness: -8, health: -2 },
      },
    ],
  },
  {
    id: 'child_stray_dog_bark_run',
    text: 'চাকরি শেষে ফিরতি গলিতে পাড়ার কালু কুত্তা তোরে দেইখা সজোরে ঘেউ ঘেউ কইরা তেড়ে আসলো!',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'pretend_pick_stone',
        text: 'মাটি থিকা ইট তোলার নাটক কর',
        outcomeText: 'কালু কুত্তা থমকে দাঁড়াইয়া লেজ গুটায়ে পিছু হটলো! উপস্থিত বুদ্ধির জয়!',
        tone: 'good',
        effects: { smarts: 12, happiness: 10 },
      },
      {
        id: 'run_screaming',
        text: 'পিছনে তাকায়া অন্ধের লাহান দৌড় মার',
        outcomeText: 'হোঁচট খাইয়া নর্দমার পাড়ে পড়লি! হাঁটু ছুলে একাকার!',
        tone: 'bad',
        effects: { health: -8, looks: -4, happiness: -10 },
      },
    ],
  },
  {
    id: 'child_chandan_teep_wedding',
    text: 'মামার গায়ে হলুদে তোরে জরিদার পাঞ্জাবি পরাইয়া চন্দনের ফোঁটা দেওয়া হইলো!',
    minAge: 6,
    maxAge: 10,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'pose_for_dslr',
        text: 'ক্যামেরাম্যানের সামনে দাঁড়াইয়া মিষ্টি একখান পোজ দে',
        outcomeText: 'হলুদের অ্যালবামে তোর হাসিমুখের ছবি সবার মধ্যমণি হইলো!',
        tone: 'good',
        effects: { looks: 12, happiness: 14 },
      },
      {
        id: 'smear_haldi_cousin',
        text: 'হলুদের বাটি থিকা হলুদ লইয়া কাজিনের নাকে ঘইষা দে',
        outcomeText: 'মারামারি শুরু হইয়া পাঞ্জাবি নষ্ট! বকা খাইয়া হলুদের আসর থিকা আউট!',
        tone: 'funny',
        effects: { happiness: 8, karma: -4, looks: -5 },
      },
    ],
  },
  {
    id: 'child_gollachut_borofpani',
    text: 'বিকেলে স্কুলের মাঠে বরফ-পানি আর গোল্লাছুটের ধামাকা খেলা! তুই দলের শেষ ভরসা!',
    minAge: 8,
    maxAge: 12,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'sprint_touch_line',
        text: 'বাতাসের বেগে দৌড়ায়া দাগ ছুঁইয়া ফেল!',
        outcomeText: 'জয়ধ্বনি! তোর দল ম্যাচ জিতলো, তোরে পিঠ চাপড়ে অভিনন্দন জানানো হইলো!',
        tone: 'good',
        effects: { health: 8, happiness: 16, looks: 4 },
      },
      {
        id: 'get_tagged_out',
        text: 'দম ফুরায়া দাগের দুই হাত আগে ধরা খাও',
        outcomeText: 'দল হাইরা গেল, তবে সবাই মিল্লা লেবুর শরবত খাইয়া দুঃখ ভুললি।',
        tone: 'neutral',
        effects: { health: 4, happiness: 2 },
      },
    ],
  },
  {
    id: 'child_pickpocket_circus_fair',
    text: 'লালবাগের মেলায় নাগরদোলা দেইখা দিল খুশ! হাতে বাপের দেওয়া ৫০ টাকার চকচকে নোট!',
    minAge: 7,
    maxAge: 12,
    weight: 7,
    tone: 'neutral',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'ride_nagordola',
        text: 'উঁচু কাঠের নাগরদোলায় চইড়া আসমানে ডানা মেলো',
        outcomeText: 'মাথা বনবন কইরা ঘুরলো আর দিল খুশিতে ভরে উঠলো!',
        tone: 'good',
        effects: { happiness: 18, money: -30 },
      },
      {
        id: 'buy_tin_pistol',
        text: 'পটকা ফুটার টিনের একখান রিভলবার কিনলি',
        outcomeText: 'ফট ফট শব্দে পুরা বাড়ি কাঁপাইলি, বাপের মেজাজ গরম হইলো!',
        tone: 'funny',
        effects: { happiness: 12, money: -40, karma: -4 },
      },
    ],
  },
  {
    id: 'child_dadi_pickles_stealing',
    text: 'দুপুরে দাদীর রোদে দেওয়া কাঁচা আমের তেলের আচারের বয়াম ছাদে চকচক করতাছে!',
    minAge: 7,
    maxAge: 12,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'steal_pickle_spoon',
        text: 'চুপিসারে বয়ামের ঢাকনা খুইলা দুই চামচ আচার মুখে পুরে নাও',
        outcomeText: 'তেল-ঝাল-মশলায় জিভ নাচলো! কিন্তু মুখের হলুদ দাগ দেইখা দাদী ধইরা ফেললো!',
        tone: 'funny',
        effects: { happiness: 14, health: -2, karma: -5 },
      },
      {
        id: 'cover_with_net',
        text: 'কাক যাতে মুখ না দেয় তাই জাল ভালো কইরা বাঁইধা দাও',
        outcomeText: 'দাদী তোর ভালো মানুষী দেইখা নিজ হাতে এক বাটি আচার খাইতে দিলো!',
        tone: 'good',
        effects: { karma: 12, happiness: 15 },
      },
    ],
  },
];

