import type { LifeEventDef } from '@/lib/engine/types';

export const INFANT_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'infant_birth_dhaka',
    text: 'আব্বে হালায়! তুই দুনিয়ায় আইসাই পুরা মহল্লায় চান্দি গরম কইরা দিছত! ফ্যামিলি তোরে দেইখা ভাবতাছে এই বান্দরের বাচ্চা কার?!',
    minAge: 0,
    maxAge: 0,
    weight: 10,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_cry_loud',
        text: 'ফাইট্টা যাওয়া মাইকের লাহান চিক্কর দিয়া কান্দন শুরু কর!',
        outcomeText: 'তোর চিল্লানিতে নার্স ডরে তোরে ফ্লোরে ফালায়া দিছে! মাথা ফুইলা আলু, তয় আম্মা আইসা মাইক অফ কইরা দুধ খাওয়াইলো!',
        tone: 'bad',
        effects: { happiness: 10, health: -15, looks: -5 },
      },
      {
        id: 'infant_smile_sweet',
        text: 'ফোকলা দাঁতে বান্দরের লাহান একখান হাসি দে!',
        outcomeText: 'তোর হাসি দেইখা ডাক্তার কয়, "হায়রে, হালায় তো জাইম্মা বাটপার হইবো!" পুরা ফ্যামিলি হাসতে হাসতে কাইত!',
        tone: 'funny',
        effects: { happiness: 15, looks: 5, karma: -5 },
      },
      {
        id: 'infant_sleep_peace',
        text: 'প্যাকেট থিকা বাইর হইয়াই নাক ডাইকা ঘুম দে!',
        outcomeText: 'সবাই ভাবলো তুই মইরা ভূত হইয়া গেছোস! আব্বা ডরে ডাক্তারে ডাকলো, তুই ঘুম থিকা উইঠা হাই তুললি! পুরাই হারামি তুই!',
        tone: 'good',
        effects: { health: 10, smarts: 10, happiness: 5 },
      },
    ],
  },
  {
    id: 'infant_first_word',
    text: 'আব্বে পিচ্চি! এহন তোর মুখ ফুটবো! ক দেহি, কার নাম লইবি পয়লা? আম্মা না আব্বা?',
    minAge: 1,
    maxAge: 2,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'say_amma',
        text: 'তোতলাইয়া ক: "আ... আ... হালারপুত!"',
        outcomeText: 'আম্মা টাসকি খাইয়া বেহুঁশ! আব্বা গিয়া তোরে ডাইরেক্ট বাথরুমে চুবাইয়া আনলো! তুই পয়লা দিনেই গাইল দিয়া ভাইরাল!',
        tone: 'bad',
        effects: { happiness: -20, smarts: 15, fame: 20 },
      },
      {
        id: 'say_biryani',
        text: 'স্পষ্ট গলার আওয়াজে ক: "কাচ্চি দে হালায়!"',
        outcomeText: 'দাদা হাসতে হাসতে কইলো, "খাঁটি ঢাকাইয়া রক্ত!" তোরে ডাইরেক্ট নান্নার বিরিয়ানির হাড়ির সামনে নিয়া বসাইলো!',
        tone: 'good',
        effects: { happiness: 25, money: 10, health: -5 },
      },
    ],
  },
  {
    id: 'infant_diaper_leak',
    text: 'আব্বার বুকের উপ্রে শুইয়া আছোস, হঠাত তোর পেটের মইধ্যে জিলাপির প্যাঁচ শুরু হইলো!',
    minAge: 1,
    maxAge: 1,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'leak_flood',
        text: 'কোনো কথা নাই, ডাইরেক্ট ব্যারেজ খুইলা আব্বার মুখে হাগু মাইরা দে!',
        outcomeText: 'তোর তরল হাগু ডাইরেক্ট আব্বার হা করা মুখে! আব্বা বমি কইরা পুরা ঘর ভাসাইলো, তুই খিলখিল কইরা হাসলি পুরাই সাইকো!',
        tone: 'funny',
        effects: { happiness: 20, health: 5, karma: -20 },
      },
      {
        id: 'hold_it',
        text: 'ভদ্র সাইজা হাগু চাপাইয়া রাখ!',
        outcomeText: 'চাপতে গিয়া তোর গ্যাস উইঠা পেট ফুইলা বেলুন! হঠাত এমুন পাদ দিলি, গন্ধে পুরা ফ্যামিলি অজ্ঞান! তুই পুরাই গ্যাস-বোমা!',
        tone: 'bad',
        effects: { health: -10, happiness: -15, looks: -5 },
      },
    ],
  },
  {
    id: 'infant_feeding_cerelac',
    text: 'আম্মা তোরে সেরেলাক খাওয়াইতে আনছে, কিন্তু তোর নজর টেবিলের মুরগির হাড্ডির দিকে!',
    minAge: 1,
    maxAge: 2,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'spit_cerelac',
        text: 'সেরেলাক মুখে নিয়া পিচকারির লাহান আম্মার মুখে থুতু মার!',
        outcomeText: 'আম্মা মেজাজ ফায়ার কইরা তোরে এমুন একখান চিমটি কাটলো, তোর পাছা লাল! সেরেলাকের বদলে তোরে কাঁচা মরিচ চিবাইতে দিলো!',
        tone: 'bad',
        effects: { health: -15, happiness: -20, karma: -10 },
      },
      {
        id: 'grab_chicken_bone',
        text: 'সেরেলাক ফালাইয়া মুরগির হাড্ডি ধইরা কুত্তার লাহান চাবা!',
        outcomeText: 'হাড্ডি তো চাবাইলি, কিন্তু গলার ভিতরে আটকায়া তুই নীল হইয়া গেলি! আব্বা উল্টা কইরা ঝুলাইয়া হাড্ডি বাইর করলো, জান বাঁচলো হালায়!',
        tone: 'funny',
        effects: { health: -20, happiness: 10, looks: -5 },
      },
    ],
  },
  {
    id: 'infant_fall_bed',
    text: 'খাট থিকা ডিগবাজি খাওয়ার ট্রেনিং নিতে গিয়া সোজা ফ্লোরের টাইলসে মুখ থুবড়া পড়লি!',
    minAge: 2,
    maxAge: 3,
    weight: 7,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'cry_ambulance',
        text: 'সাইরেন বাজাইয়া পুরা মহল্লার ঘুম হারাম কইরা কান্দ!',
        outcomeText: 'তোর কান্দন শুইনা আম্মা দৌড়াইয়া আইসা দেইখা কয়, "নাক হালায় চ্যাপ্টা হইয়া ব্যাঙের লাহান হইয়া গেছে!" তুই আজীবন ব্যাঙ-নাক!',
        tone: 'bad',
        effects: { health: -15, looks: -25, happiness: -10 },
      },
      {
        id: 'brave_laugh',
        text: 'রক্ত বাইর হইলেও ভ্যাবলার লাহান হাইসা ফাপড় নে!',
        outcomeText: 'দাদী দেইখা কয়, "আমাগো বংশের পোলা তো, পুরাই গন্ডার!" কিন্তু তোর সামনের দুইটা কচি দাঁত ভাইঙ্গা তুই ফোকলা!',
        tone: 'funny',
        effects: { health: -20, looks: -15, smarts: 10 },
      },
    ],
  },
  {
    id: 'infant_cousin_toy',
    text: 'খালাতো ভাই তোর ফেভারিট খেলনা গাড়ি টাইন্যা নিয়া ভেংচি কাটতাছে!',
    minAge: 3,
    maxAge: 4,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'bite_ear',
        text: 'চিপায় ধইরা হালার কানের লতিতে কুত্তার লাহান কামড় দে!',
        outcomeText: 'খালাতো ভাই মুইতা দিয়া কান্দন শুরু করলো! খালা আইসা তোর চুল ধইরা এমুন টান দিলো, তুই পুরাই টাকলু হইয়া গেলি!',
        tone: 'bad',
        effects: { happiness: 15, karma: -15, looks: -20 },
      },
      {
        id: 'snitch_amma',
        text: 'খালাতো ভাইয়ের প্যান্ট টাইন্যা খুইলা দিয়া ভোঁ দৌড় দে!',
        outcomeText: 'খালাতো ভাই ন্যাংটা হইয়া ড্রয়িংরুমে মেহমানগো সামনে গিয়া পড়লো! তুই চিপায় বইসা শয়তানের হাসি হাসলি!',
        tone: 'good',
        effects: { smarts: 20, happiness: 25, karma: -10 },
      },
    ],
  },
  {
    id: 'infant_vaccine_pain',
    text: 'হাসপাতালে নার্স আন্টি একখান বিশাল সাইজের সুঁই নিয়া তোর পাছায় ফুড়াইতে আইতাছে!',
    minAge: 1,
    maxAge: 3,
    weight: 6,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'bite_doctor',
        text: 'ডাক্তারের হাতে এমুন একখান কামড় দে, মাংস উইঠা আসে!',
        outcomeText: 'ডাক্তার চিল্লান দিয়া সুঁই তোর পাছার বদলে আব্বার পাছায় ঢুকায়া দিলো! তুই জান বাঁচায়া খিলখিল কইরা হাসলি!',
        tone: 'funny',
        effects: { happiness: 25, smarts: 15, karma: -20 },
      },
      {
        id: 'take_it_like_boss',
        text: 'হিরো সাইজা সুঁইয়ের গুঁতা চুপচাপ হজম কর!',
        outcomeText: 'সুঁই ঢোকার লগে লগে তুই ব্যথায় অজ্ঞান! প্যান্টে হাগু-মুত একাকার! ডাক্তার তোরে ড্রেনে ফালায়া দেওয়ার বুদ্ধি দিলো!',
        tone: 'bad',
        effects: { health: 10, happiness: -30, looks: -15 },
      },
    ],
  },
  {
    id: 'infant_eid_salami_piggy',
    text: 'ঈদের দিন মুরব্বিরা তোরে ৫০০ ট্যাকা সালামি দিছে। আম্মা কয়, "দে আমার কাছে রাখ, পরে দিমুনে।"',
    minAge: 4,
    maxAge: 5,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'give_amma',
        text: 'ভ্যাবলার লাহান আম্মার হাতে ট্যাকা তুইলা দে!',
        outcomeText: 'হেই ট্যাকা আর জিন্দেগিতে পাস নাই! ওই ট্যাকা দিয়া আম্মা নিজের লাইগা শাড়ি কিন্না তোরে কাঁচকলা দেখাইলো!',
        tone: 'bad',
        effects: { money: -500, smarts: -15, happiness: -20 },
      },
      {
        id: 'hide_in_pants',
        text: 'প্যান্টের চিপায় ডাইরেক্ট আন্ডারওয়ারের ভিতরে ট্যাকা লুকায়া রাখ!',
        outcomeText: 'ট্যাকা লুকাইলি ঠিকই, কিন্তু আন্ডারওয়ারের ঘামে আর মুতে ট্যাকা গইলা ছিঁড়া গেলো! তুই এহন ফকিরের ঘরের ফকির!',
        tone: 'funny',
        effects: { money: -500, smarts: 10, happiness: -15 },
      },
    ],
  },
  {
    id: 'infant_wall_graffiti',
    text: 'হাতে লাল মার্কার পাইয়া ড্রয়িংরুমের নতুন দেওয়াল এক্কেরে ফালাফালা কইরা আঁকিবুঁকি করছোস!',
    minAge: 3,
    maxAge: 5,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'proud_artist',
        text: 'পিকাসো সাইজা দেওয়ালের সামনে দাঁড়াইয়া পোজ দে!',
        outcomeText: 'আব্বা আইসা তোর প্যান্ট খুইলা ওই লাল মার্কার দিয়া তোর পাছায় পুরা বাংলাদেশের ম্যাপ আঁইকা দিলো! পুরাই আর্ট গ্যালারি!',
        tone: 'bad',
        effects: { happiness: -25, health: -15, looks: -20 },
      },
      {
        id: 'blame_cat',
        text: 'বিলাইয়ের মুখে মার্কার ঘইষা দিয়া ক: "বিলাই আঁকছে!"',
        outcomeText: 'বিলাই মেজাজ ফায়ার কইরা তোর মুখে এমুন খামচি দিলো, তুই আজীবন টাইগার-মুখা হইয়া গেলি! আব্বাও বাটপারি ধইরা পিটাইলো!',
        tone: 'bad',
        effects: { smarts: -10, health: -20, looks: -25 },
      },
    ],
  },
  {
    id: 'infant_rainy_mud',
    text: 'পুরান ঢাকার গলিতে বৃষ্টির পচা পানি জমছে। তুই ডাইরেক্ট ড্রেনের কাদার মইধ্যে লাফালাফি করতাছোস!',
    minAge: 4,
    maxAge: 5,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'jump_mud',
        text: 'গু-মুত মাখা পানিতে হাতির লাহান ঝাঁপ দে!',
        outcomeText: 'ঝাঁপ দিতে গিয়া ড্রেনের মরা ইঁদুর ডাইরেক্ট তোর মুখের ভিতর! তুই বমি করতে করতে এক্কেরে আইসিইউ (ICU) যাওয়ার দশা!',
        tone: 'bad',
        effects: { health: -30, happiness: -20, looks: -20 },
      },
      {
        id: 'push_friend_mud',
        text: 'দোস্তরে ধাক্কা দিয়া কাদার মইধ্যে ফালায়া দে!',
        outcomeText: 'দোস্ত কাদায় পইড়া কাইন্দা দিলো! ওর মা আইসা তোরে ধইরা ড্রেনের পানিতে চুবানি দিয়া দিলো! তুই পুরাই পচা শুঁটকি!',
        tone: 'funny',
        effects: { karma: -20, happiness: -15, health: -15 },
      },
    ],
  },
  {
    id: 'infant_chilli_bite',
    text: 'টেবিলে শুঁটকি ভর্তার লগে থাকা বোম্বাই মরিচরে চকলেট ভাইবা গপ কইরা মুখে ভরলি!',
    minAge: 3,
    maxAge: 4,
    weight: 5,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'drink_water_tub',
        text: 'ঝালের চোটে চিল্লান দিয়া পুরা জগ ভইরা পানি গিল!',
        outcomeText: 'নাক-মুখ দিয়া আগুন বাইর হইতাছে! পানি খাইতে গিয়া তুই হিসু কইরা পুরা প্যান্ট ভাসায়া দিলি! চান্দি পুরাই কয়লা!',
        tone: 'bad',
        effects: { health: -20, happiness: -30, looks: -10 },
      },
      {
        id: 'sugar_cube',
        text: 'চিনির কৌটায় হাত ডুবাইয়া এক খাবলা চিনি মুখে দে!',
        outcomeText: 'চিনি খাইতে গিয়া দেখস চিনির তলে লাল পিঁপড়া ভর্তি! পিঁপড়া তোর জিহ্বা আর ঠোঁট কামড়াইয়া পুরাই বেলুন বানায়া দিলো!',
        tone: 'bad',
        effects: { smarts: -5, health: -15, looks: -20 },
      },
    ],
  },
  {
    id: 'infant_kg_admission',
    text: 'কিন্ডারগার্টেন স্কুলে ইন্টারভিউ! প্রিন্সিপাল ম্যাডাম জিগাইলো, "বলো তো বাবা, আপেলের রঙ কী?"',
    minAge: 4,
    maxAge: 5,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'answer_red',
        text: 'আতেল সাইজা ক: "রেড কালার ম্যাডাম!"',
        outcomeText: 'ম্যাডাম খুশি হইলো, কিন্তু তুই ওভারস্মার্ট সাজতে গিয়া ম্যাডামের টেবিলে রাখা চায়ের কাপ উল্টায়া দিলি! ডাইরেক্ট রিজেক্ট!',
        tone: 'bad',
        effects: { smarts: 10, happiness: -20, karma: -10 },
      },
      {
        id: 'answer_kacchi',
        text: 'কড়া গলায় ক: "আপেল দিয়া বাল ফালাবো, আমি কাচ্চি খামু!"',
        outcomeText: 'প্রিন্সিপাল টাসকি খাইয়া বেহুঁশ! আব্বা তোরে ধইরা কানমলা দিয়া বাইর কইরা আনলো। তুই মূর্খই থাকলি হালায়!',
        tone: 'funny',
        effects: { happiness: 15, smarts: -20, fame: 20 },
      },
    ],
  },
  {
    id: 'infant_bangles_break',
    text: 'দাদীর আলমারি থিকা শখের কাঁচের চুড়ি বাইর কইরা ফ্লোরে আছাড় মাইরা ভাইঙ্গা ফেললি!',
    minAge: 2,
    maxAge: 4,
    weight: 5,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'laugh_shards',
        text: 'চুড়ি ভাঙ্গার টুংটাং শব্দ শুইনা তালি বাজাইয়া নাচ!',
        outcomeText: 'নাচতে গিয়া কাঁচের টুকরা ডাইরেক্ট তোর পায়ের তলায় ঘচাং কইরা ঢুকলো! রক্তারক্তি অবস্থা, আর দাদীর ঝাড়ুর বাড়ি ফ্রি!',
        tone: 'bad',
        effects: { health: -25, happiness: -20, karma: -15 },
      },
      {
        id: 'pretend_scared',
        text: 'ভয়ের নাটক কইরা ডাইরেক্ট প্যান্টে হাগু কইরা দে!',
        outcomeText: 'দাদী তোর হাগু দেইখা ঘিন্না খাইয়া চইলা গেলো! তুই বাটপারি কইরা বাঁচলি ঠিকই, কিন্তু হাগু মাখা অবস্থায় বইসা থাকলি আধা ঘন্টা!',
        tone: 'funny',
        effects: { smarts: 15, happiness: -10, looks: -20 },
      },
    ],
  },
  {
    id: 'infant_hair_cut_mundan',
    text: 'মাথা ন্যাড়া করনের জন্য নাপিত মামা ক্ষুর নিয়া হাজির। তুই ডরে কাঁপতাছোস!',
    minAge: 1,
    maxAge: 2,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_bite_barber',
        text: 'নাপিতের আঙ্গুলে কুত্তার লাহান কামড় বসায়া দে!',
        outcomeText: 'নাপিত উরেব্বাস বইলা ক্ষুর টাইন্না সরাইলো, কিন্তু তোর মাথার মাঝখানে এক্কেরে হাইওয়ের লাহান রাস্তা হইয়া গেলো! তুই পুরাই জোকার!',
        tone: 'funny',
        effects: { happiness: 15, looks: -30, karma: -10 },
      },
      {
        id: 'infant_sit_like_buddha',
        text: 'সাধু বাবার লাহান শান্ত হইয়া বইসা থাক!',
        outcomeText: 'মাথা ন্যাড়া হইয়া চকচকা বেলুন! কিন্তু ন্যাড়া মাথায় মশা এমুন কামড় দিলো, তোর পুরা চান্দি ফুইলা এক্কেরে কাঁঠাল হইয়া গেলো!',
        tone: 'bad',
        effects: { health: -15, looks: -20, happiness: -10 },
      },
    ],
  },
  {
    id: 'infant_cat_tail_pull',
    text: 'উঠানের হুলো বিলাইটা ঘুমাইতাছে। তার লেজ দেইখা তোর চুলকানি শুরু হইলো!',
    minAge: 2,
    maxAge: 4,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_yank_tail',
        text: 'খপ কইরা লেজ ধইরা একখান হ্যাঁচকা টান দে!',
        outcomeText: 'বিলাই ঘুইরা এমুন এক খামচি দিলো, তোর প্যান্ট খুইলা গেলো আর তোর পাছায় তিনটা পারমানেন্ট দাগ পইড়া গেলো! বিলাইয়ের বাঁশ!',
        tone: 'bad',
        effects: { health: -20, happiness: -25, karma: -15 },
      },
      {
        id: 'ride_the_cat',
        text: 'বিলাইয়ের পিঠের উপ্রে ঘোড়ার লাহান উইঠা বসার ট্রাই কর!',
        outcomeText: 'বিলাই ডরে এমুন লাফ দিলো, তুই ছিটকাইয়া গিয়া সোজা ড্রেনের ময়লার বালতিতে ল্যান্ডিং করলি! পুরাই ডাস্টবিন তুই!',
        tone: 'funny',
        effects: { health: -15, looks: -25, happiness: -20 },
      },
    ],
  },
  {
    id: 'infant_mosque_microphone_imitate',
    text: 'মসজিদের আজান শুইনা স্টিলের গ্লাস মুখের সামনে ধইরা তুইও পকপক শুরু করছোস!',
    minAge: 3,
    maxAge: 5,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_sing_sweet_azan',
        text: 'আজানের সুর নকল কইরা পুরা পাড়া মাথায় তোল!',
        outcomeText: 'দাদা শুইনা আইসা তোরে কোলে নিতে গেলো, আর তুই দাদার মুখের উপ্রে এমুন একখান বমি করলি! সুরের লগে বমি ফ্রি!',
        tone: 'funny',
        effects: { happiness: 10, karma: -10, health: -5 },
      },
      {
        id: 'infant_drop_glass',
        text: 'সুর বাদ দিয়া গ্লাসটা দাদীর মাথার উপ্রে ফালায়া দে!',
        outcomeText: 'দাদীর কপাল ফুইলা আলু! দাদী তোরে ঝাড়ু দিয়া এমুন পিটানি দিলো, তুই তিনদিন সোজা হইয়া বইতে পারলি না!',
        tone: 'bad',
        effects: { health: -20, happiness: -30, karma: -20 },
      },
    ],
  },
  {
    id: 'infant_sibling_sharing_fight',
    text: 'আম্মা তোরে আর তোর বড় ভাইরে এক বাটি চানাচুর দিছে। বাটিতে হাতাহাতি শুরু!',
    minAge: 4,
    maxAge: 5,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_hog_bowl',
        text: 'পুরা বাটি মুখে উপুড় কইরা গপাগপ গিল!',
        outcomeText: 'চানাচুরের ঝাল আর মটরশুটি ডাইরেক্ট তোর নাকের ফুটায় গিয়া আটকাইলো! শ্বাস বন্ধ হইয়া তোর চোখ বাইর হইয়া আসার দশা!',
        tone: 'bad',
        effects: { health: -25, happiness: -20, smarts: -10 },
      },
      {
        id: 'infant_spit_in_bowl',
        text: 'বাটির চানাচুরে থুতু ফালায়া দে, যাতে ভাই না খাইতে পারে!',
        outcomeText: 'ভাই তোর চালাকি বুইঝা ওই থুতু মাখা চানাচুর ডাইরেক্ট তোর প্যান্টের ভিতরে ঢাইলা দিলো! ঝালে তোর অণ্ডকোষ পুরাই ফায়ার!',
        tone: 'bad',
        effects: { smarts: 10, health: -20, happiness: -30, karma: -15 },
      },
    ],
  },
];