import type { LifeEventDef } from '@/lib/engine/types';

export const INFANT_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'infant_birth_dhaka',
    text: 'আব্বে হালায়! তুই তো দুনিয়ায় আইসাই পুরা মহল্লায় চান্দি গরম কইরা দিছত! এহন তুই সবার কইলজার টুকরা।',
    minAge: 0,
    maxAge: 0,
    weight: 10,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_cry_loud',
        text: 'এক্কেরে ফাটা বাঁশের লাহান চিক্কর দিয়া কান্দন শুরু কর',
        outcomeText: 'তোর কান্দন শুইনা আম্মা দৌড়াইয়া আইসা কোলে তুইলা দুধ খাওয়াইলো।',
        tone: 'good',
        effects: { happiness: 10, health: 5 },
      },
      {
        id: 'infant_smile_sweet',
        text: 'ফোকলা দাঁতে মিষ্টি একখান হাসি দে',
        outcomeText: 'খালা-ফুপুরা দেইখা কয়, "হায়রে সোনাটা এক্কেবারে বাপের লাহান কিউট!"',
        tone: 'good',
        effects: { happiness: 15, looks: 5 },
      },
      {
        id: 'infant_sleep_peace',
        text: 'সব ভন্ডামি বাদ দিয়া নাক ডাইকা ঘুম দে',
        outcomeText: 'শান্তিতে ঘুমাইলি, বাড়িশুদ্ধ মানুষ হাঁফ ছাড়লো।',
        tone: 'neutral',
        effects: { health: 10 },
      },
    ],
  },
  {
    id: 'infant_first_word',
    text: 'আব্বে পিচ্চি! এহন তো তোর মুখ ফুটবো! ক দেহি, কার নাম লইবি পয়লা?',
    minAge: 1,
    maxAge: 2,
    weight: 8,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'say_amma',
        text: 'কড়া গলায় ক: "আম্মা!"',
        outcomeText: 'আম্মা খুশিতে তোরে মিষ্টি খাওয়াইয়া দিল। আব্বা অবশ্য একটু মুখ কালা করলো।',
        tone: 'good',
        effects: { happiness: 10, smarts: 5 },
      },
      {
        id: 'say_abba',
        text: 'আদুরে সুরে ক: "আব্বা!"',
        outcomeText: 'আব্বা গদগদ হইয়া মহল্লার সবাইকে বিরিয়ানি খাওয়াইলো!',
        tone: 'good',
        effects: { happiness: 12, money: 10 },
      },
      {
        id: 'say_biryani',
        text: 'স্পষ্ট ডাক দে: "কাচ্চি!"',
        outcomeText: 'দাদা হাইসা কয়, "খাঁটি ঢাকাইয়া রক্ত, নাজিরাবাজারের পোলা!"',
        tone: 'funny',
        effects: { happiness: 15, smarts: 8 },
      },
    ],
  },
  {
    id: 'infant_diaper_leak',
    text: 'বাবার বুকের উপর শুইয়া আছিলি, হঠাৎ পেটের মধ্যে বুদবুদ আওয়াজ হইলো!',
    minAge: 1,
    maxAge: 1,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'leak_flood',
        text: 'এক্কেবারে ব্যারেজ ছাইড়া হাগা দিয়া আব্বার নতুন জামা ভিজায়া দে',
        outcomeText: 'আব্বা চিক্কর দিয়া উঠলো, "হায়রে হালায়, আমার আড়ংয়ের কুর্তা শেষ!"',
        tone: 'funny',
        effects: { happiness: 10, health: 5 },
      },
      {
        id: 'hold_it',
        text: 'কষ্ট কইরা চাপাইয়া রাখ',
        outcomeText: 'পেটে গ্যাস জইমা আধা ঘণ্টা চিঁ চিঁ করলি।',
        tone: 'bad',
        effects: { health: -5, happiness: -5 },
      },
    ],
  },
  {
    id: 'infant_feeding_cerelac',
    text: 'আম্মা তোরে চামচ ভইরা সেরেলাক খাওয়াইতে আনছে, কিন্তু তোর নজর টেবিলে রাখা মুরগির ঝোলে!',
    minAge: 1,
    maxAge: 2,
    weight: 6,
    tone: 'neutral',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'spit_cerelac',
        text: 'সেরেলাক থুতু দিয়া আম্মার শাড়িতে মার',
        outcomeText: 'আম্মা মৃদু ধমক দিয়া মুরগির নরম মাংস চটকায়া দিল। খায়া পুরাই মাখন!',
        tone: 'good',
        effects: { health: 8, happiness: 10 },
      },
      {
        id: 'eat_quietly',
        text: 'ভালো ছেলের লাহান সেরেলাক গিলা ফেল',
        outcomeText: 'পেট ভরলো কিন্তু মন ভরলো না।',
        tone: 'neutral',
        effects: { health: 5 },
      },
    ],
  },
  {
    id: 'infant_fall_bed',
    text: 'খাট থিকা ডিগবাজি খাওয়ার ট্রেনিং নিতে গিয়া ধপাস কইরা ফ্লোরে পইড়া গেলি!',
    minAge: 2,
    maxAge: 3,
    weight: 7,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'cry_ambulance',
        text: 'সাইরেন বাজায়া মরা কান্দন শুরু কর',
        outcomeText: 'আম্মা দৌড়ায়া আইসা বুকে জড়ায়া নিলো। কপালে ছোট একখান আলু ফুললো।',
        tone: 'bad',
        effects: { health: -5, happiness: -5 },
      },
      {
        id: 'brave_laugh',
        text: 'মাটিতে বইসাই ভ্যাবলার লাহান হাস',
        outcomeText: 'দাদী দেইখা কয়, "আমগো বংশের পোলা তো, লোহা দিয়া বানানো!"',
        tone: 'funny',
        effects: { health: -2, looks: 5, smarts: 5 },
      },
    ],
  },
  {
    id: 'infant_cousin_toy',
    text: 'খালাতো ভাই তোর প্রিয় প্লাস্টিকের গাড়িটা টাইন্যা নিয়া দৌড় দিছে!',
    minAge: 3,
    maxAge: 4,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'bite_ear',
        text: 'চিপায় ধইরা হালার কানের লতিতে কামড় দে',
        outcomeText: 'খালাতো ভাই চিল্লাইয়া কান্দন দিলো, গাড়ি ফেরত পাইলি কিন্তু খালার বকা শুনলি।',
        tone: 'funny',
        effects: { happiness: 8, karma: -5 },
      },
      {
        id: 'snitch_amma',
        text: 'আম্মার কাছে যাইয়া ফ্যাঁচফ্যাঁচ কর',
        outcomeText: 'আম্মা খালাতো ভাইরে ধমক দিয়া গাড়ি উদ্ধার কইরা দিলো।',
        tone: 'good',
        effects: { happiness: 6, smarts: 5 },
      },
    ],
  },
  {
    id: 'infant_vaccine_pain',
    text: 'হাসপাতালে নিয়া নার্স আন্টি একখান সুঁই হাতে নিয়া তোর দিকে হাসিমুখে তাকাইলো!',
    minAge: 1,
    maxAge: 3,
    weight: 6,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'bite_doctor',
        text: 'ডাক্তারের হাতে একখান কামড় মার',
        outcomeText: 'ডাক্তার চমকাইয়া সুঁই ফেলায় দিলো, পুরা চেম্বারে তোলপাড়!',
        tone: 'funny',
        effects: { happiness: 10, karma: -5 },
      },
      {
        id: 'take_it_like_boss',
        text: 'দাঁত কিড়মিড় কইরা সুঁইয়ের গুঁতা সহ্য কর',
        outcomeText: 'নার্স আন্টি আদর কইরা চকলেট দিলো। রোগ প্রতিরোধ ক্ষমতা বাড়লো!',
        tone: 'good',
        effects: { health: 12, happiness: 2 },
      },
    ],
  },
  {
    id: 'infant_eid_salami_piggy',
    text: 'ঈদের দিন মুরুব্বিরা তোরে ৫০০ ট্যাকা সালামি দিলো। আম্মা কয়, "দে আমার কাছে জমা রাখ।"',
    minAge: 4,
    maxAge: 5,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'give_amma',
        text: 'বিশ্বাসের সহিত আম্মার হাতে ট্যাকা তুইল্যা দে',
        outcomeText: 'হেই ট্যাকা আর জিন্দেগিতে কোনোদিন ফেরত পাইলি না! ফুড়ুৎ!',
        tone: 'bad',
        effects: { money: -500, smarts: 8 },
      },
      {
        id: 'hide_in_pants',
        text: 'প্যান্টের ইলাস্টিকের চিপায় ট্যাকা গুঁইজা রাখ',
        outcomeText: 'আম্মার চোখ ফাঁকি দিয়া ট্যাকা বাঁচাইলি, বিকালে আইসক্রিম কিনলি!',
        tone: 'good',
        effects: { money: 100, happiness: 15 },
      },
    ],
  },
  {
    id: 'infant_wall_graffiti',
    text: 'হাতে লাল রঙের মার্কার পাইয়া ড্রয়িংরুমের নতুন সাদা দেওয়াল এক্কেবারে ক্যানভাস বানায়া দিছত!',
    minAge: 3,
    maxAge: 5,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'proud_artist',
        text: 'দেওয়ালের সামনে দাঁড়াইয়া বড়লোক আর্টিস্টের লাহান পোজ দে',
        outcomeText: 'আম্মা মাথায় হাত দিয়া বইসা পড়লো, আব্বা ফটো তুইলা ফেসবুকে দিল!',
        tone: 'funny',
        effects: { happiness: 10, looks: 5 },
      },
      {
        id: 'blame_cat',
        text: 'বিড়ালের দিকে আঙ্গুল তুইলা ক: "মিউ মিউ করসে!"',
        outcomeText: 'তোর চালাকি দেইখা সবাই হাসলো, কিন্তু থাপড়ানি থিকা বাইচা গেলি।',
        tone: 'neutral',
        effects: { smarts: 6 },
      },
    ],
  },
  {
    id: 'infant_rainy_mud',
    text: 'পুরান ঢাকার গলিতে বৃষ্টি হইয়া পানি জমছে। পোলাপানরা কাদায় লাফালাফি করতাছে!',
    minAge: 4,
    maxAge: 5,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'jump_mud',
        text: 'কাপড়চোপড় সহ নোংরা পানিতে ঝাঁপ দে',
        outcomeText: 'প্রচণ্ড মজা পাইলি, লেকিন আম্মা বাড়ি ফিরা ঝাড়ুর বাড়ি দিয়া গোসল করাইলো।',
        tone: 'funny',
        effects: { happiness: 15, health: -5 },
      },
      {
        id: 'watch_balcony',
        text: 'বারান্দা থিকা কাগজির নৌকা বানায়া ভাসায়া দে',
        outcomeText: 'নৌকা নালায় ভাসায়া শান্তি পাইলি, ঠান্ডা বাতাস মন ভালো কইরা দিলো।',
        tone: 'good',
        effects: { happiness: 8, smarts: 5 },
      },
    ],
  },
  {
    id: 'infant_chilli_bite',
    text: 'টেবিলে শুঁটকি ভর্তার লগে থাকা কাঁচামরিচরে মিষ্টি চকলেট ভাইবা এক কামড় মারলি!',
    minAge: 3,
    maxAge: 4,
    weight: 5,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'drink_water_tub',
        text: 'জিহ্বা বাইর কইরা পুরা জগ ভইরা পানি খা',
        outcomeText: 'ঝাল কমলো না, নাক-মুখ দিয়া ধোঁয়া বাইর হইলো! চান্দি গরম!',
        tone: 'bad',
        effects: { health: -8, happiness: -10 },
      },
      {
        id: 'sugar_cube',
        text: 'চিনির কৌটায় হাত ডুবায়া চিনি মুখে দে',
        outcomeText: 'চিনির জোরে ঝাল কমলো। ঢাকাইয়া ঝাল খাওয়ার প্রথম তালিম পাইলি!',
        tone: 'neutral',
        effects: { smarts: 5, health: -2 },
      },
    ],
  },
  {
    id: 'infant_rickshaw_bell',
    text: 'মামার লগে রিকশায় চড়ছস। রিকশাওয়ালার টুংটাং বেল বাজাইতে মন চাইতেছে!',
    minAge: 3,
    maxAge: 5,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'ring_bell',
        text: 'হাত বাড়ায়া ক্রমাগত টুং টুং কইরা বেল বাজা',
        outcomeText: 'রিকশাওয়ালা মামা হাইসা কয়, "ওস্তাদ, আপনিই চালান!" মনটা পুরাই চিল!',
        tone: 'good',
        effects: { happiness: 12, looks: 3 },
      },
      {
        id: 'sit_quiet',
        text: 'বাতাস খাইতে খাইতে নাজিরাবাজারের রাস্তা দেখ',
        outcomeText: 'বিরিয়ানির গন্ধ পাইয়া জিভে জল চইলা আসলো।',
        tone: 'neutral',
        effects: { happiness: 6 },
      },
    ],
  },
  {
    id: 'infant_kg_admission',
    text: 'কিন্ডারগার্টেন স্কুলে ইন্টারভিউ! প্রিন্সিপাল ম্যাডাম জিগাইলো, "আপেল এর রঙ কী?"',
    minAge: 4,
    maxAge: 5,
    weight: 8,
    tone: 'neutral',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'answer_red',
        text: 'স্মার্ট সুরে ক: "লাল রঙের ম্যাডাম!"',
        outcomeText: 'ম্যাডাম খুশি হইয়া ভর্তি ফর্মে সাইন দিলো। আব্বা গর্বে চওড়া!',
        tone: 'good',
        effects: { smarts: 10, happiness: 8 },
      },
      {
        id: 'answer_kacchi',
        text: 'কড়া গলায় ক: "আপেল দিয়া কি করুম, আমি কাচ্চি খামু!"',
        outcomeText: 'প্রিন্সিপাল হাইসা খুন! স্পেশাল কোটায় চান্স হইয়া গেল!',
        tone: 'funny',
        effects: { happiness: 15, looks: 5 },
      },
    ],
  },
  {
    id: 'infant_bangles_break',
    text: 'দাদীর কাঠের আলমারি থিকা কাঁচের চুড়ি বাইর কইরা মেঝেতে আছাড় মারলি!',
    minAge: 2,
    maxAge: 4,
    weight: 5,
    tone: 'bad',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'laugh_shards',
        text: 'টুংটাং ভাঙার শব্দ শুইনা তালি বাজায়া নাচ',
        outcomeText: 'দাদী দৌড়াইয়া আইসা তোরে কোলে তুললো আর মাখন গালি দিলো!',
        tone: 'funny',
        effects: { happiness: 5, karma: -5 },
      },
      {
        id: 'pretend_scared',
        text: 'ভয়ের নাটক কইরা কান্দা কান্দা মুখ বানায়া ফেল',
        outcomeText: 'দাদী উল্টা তোরে সান্ত্বনা দিয়া মিষ্টি খাওয়াইলো। পুরাই অভিনেতা!',
        tone: 'good',
        effects: { smarts: 8, looks: 4 },
      },
    ],
  },
  {
    id: 'infant_pigeon_feather',
    text: 'ছাদে কবুতরের খাঁচার সামনে একটা রঙিন পালক পইড়া আছে। খাইতে মন চাইতেছে!',
    minAge: 2,
    maxAge: 3,
    weight: 5,
    tone: 'neutral',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'eat_feather',
        text: 'সোজা মুখে দিয়া চিবাইতে থাক',
        outcomeText: 'গলায় খোঁচা খাইয়া কাশতে কাশতে হালত খারাপ! আম্মা আইসা উদ্ধার করলো।',
        tone: 'bad',
        effects: { health: -8, happiness: -6 },
      },
      {
        id: 'play_wind',
        text: 'বাতাসে ফু দিয়া উড়াইয়া খেল',
        outcomeText: 'পালকটা উড়তে উড়তে আকাশে হারাইয়া গেল। সুন্দর শৈশব!',
        tone: 'good',
        effects: { happiness: 10, smarts: 3 },
      },
    ],
  },
  {
    id: 'infant_hair_cut_mundan',
    text: 'মাথা ন্যাড়া করনের জন্য নাপিত মামা ক্ষুর নিয়া হাজির। পুরা খান্দান তোরে ঘিরা ধইরা দাঁড়াইছে!',
    minAge: 1,
    maxAge: 2,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_bite_barber',
        text: 'নাপিতের আঙ্গুলে ঠাস কইরা কামড় বসায়া দে',
        outcomeText: 'নাপিত উরেব্বাস বইলা ক্ষুর সরায় নিলো! আব্বা তোরে কোলে নিয়া বুঝাইলো।',
        tone: 'funny',
        effects: { happiness: 10, karma: -5 },
      },
      {
        id: 'infant_sit_like_buddha',
        text: 'এক্কেবারে সাধু বাবার লাহান শান্ত হইয়া বইসা থাক',
        outcomeText: 'মাথা ন্যাড়া হইয়া চকচকা বেলুন! দাদী সরিষার তেল ডইলা নজর কাটাইলো।',
        tone: 'good',
        effects: { looks: 10, health: 5, smarts: 5 },
      },
    ],
  },
  {
    id: 'infant_bakarkhani_soak',
    text: 'সকালের নাস্তায় আব্বা গরম দুধে বাকরখানি চুবাইয়া খাইতেছে। তোর জিহ্বায় লালা ঝরতেছে!',
    minAge: 2,
    maxAge: 3,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_grab_milk_bowl',
        text: 'দুধের বাটিতে দুই হাত ঢুকায়া বাকরখানি ছোঁ মার',
        outcomeText: 'গরম দুধের ছিটা খাইলি কিন্তু বাকরখানির মচমচে টুকরা মুখে দিয়া স্বর্গ পাইলি!',
        tone: 'good',
        effects: { happiness: 14, health: 4 },
      },
      {
        id: 'infant_beg_sweetly',
        text: 'হাত বাড়ায়া ক: "আব্বা... খামু!"',
        outcomeText: 'আব্বা গদগদ হইয়া নরম বাকরখানি চটকায়া মুখে তুইলা দিলো। খাঁটি ঢাকাইয়া খানা!',
        tone: 'good',
        effects: { happiness: 12, looks: 5 },
      },
    ],
  },
  {
    id: 'infant_walker_derby',
    text: 'প্লাস্টিকের চাকাঅলা ওয়াকারে চইড়া লম্বা বারান্দায় স্পিড টেস্ট দিতাছস! সামনে দাদীর পানের বাটা!',
    minAge: 1,
    maxAge: 2,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_ram_paan_box',
        text: 'ব্রেক না কইস্যা সরাসরি পানের বাটায় ধাক্কা মার!',
        outcomeText: 'ধুপধাপ কইরা চুন, সুপারি, জর্দা মেঝেময় ছড়ায়া পড়লো! দাদী মাথায় হাত দিয়া হাসলো।',
        tone: 'funny',
        effects: { happiness: 12, karma: -4 },
      },
      {
        id: 'infant_drift_turn',
        text: 'শেষ মুহূর্তে চাকা ঘুরায়া ড্রিফট মার',
        outcomeText: 'ওয়াকার কাত হইয়া পড়লি না, ব্যালেন্স ধইরা সুপারহিরোর লাহান হাসলি!',
        tone: 'good',
        effects: { smarts: 8, happiness: 10 },
      },
    ],
  },
  {
    id: 'infant_buriganga_boat_trip',
    text: 'সদরঘাট থিকা বাদামতলী ঘাটে নৌকায় চইড়া যাওয়ার সময় বিশাল স্টিমারের ভুউউ আওয়াজে কান ঝালাপালা!',
    minAge: 3,
    maxAge: 5,
    weight: 6,
    tone: 'neutral',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_wave_steamer',
        text: 'দুই হাত উড়াইয়া স্টিমারের দিকে টা-টা কর',
        outcomeText: 'স্টিমারের ক্যাপটেন হাইসা হাত নাড়াইলো! মনটা খুশিতে ডানা মেললো।',
        tone: 'good',
        effects: { happiness: 15, looks: 6 },
      },
      {
        id: 'infant_hide_in_lap',
        text: 'ভয়ে চোখ বুইজা আম্মার বোরখার চিপায় মুখ লুকাও',
        outcomeText: 'আম্মা বুকে জড়ায়া আদর দিলো, ভয়ের চোট কেটে গেল।',
        tone: 'neutral',
        effects: { happiness: 5, health: 5 },
      },
    ],
  },
  {
    id: 'infant_cat_tail_pull',
    text: 'উঠানের হুলো বিড়ালটা রোদে পিঠ দিয়া ঘুমাইতেছিল। তার তুলতুলে লেজ দেইখা লোভ সামলানো কঠিন!',
    minAge: 2,
    maxAge: 4,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_yank_tail',
        text: 'সজোরে খপ কইরা লেজ ধইরা একখান হ্যাঁচকা টান দে!',
        outcomeText: 'মিঁয়াওওও চিল্লাইয়া বিড়াল এক লাফে ছাদে! হাতে হালকা আঁচড় খাইলি।',
        tone: 'bad',
        effects: { health: -5, happiness: -4, karma: -6 },
      },
      {
        id: 'infant_pet_gently',
        text: 'আদুরে সুরে পিঠে হাত বুলায়া দে',
        outcomeText: 'বিড়ালটা ঘড়ঘড় আওয়াজ কইরা তোর পায়ের কাছে গড়াগড়ি দিলো!',
        tone: 'good',
        effects: { happiness: 12, karma: 8 },
      },
    ],
  },
  {
    id: 'infant_bangles_seller_bell',
    text: 'গলির মুখে চুড়িওয়ালি আন্টি বাঁশের ডালায় রকমারি কাঁচের চুড়ি নিয়া ডাক পারতেছে: "চুউউড়ি নিবেন গো!"',
    minAge: 3,
    maxAge: 5,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_wear_tiny_bangle',
        text: 'একজোড়া লাল রেশমি চুড়ি হাতে পইরা নাচানাচি কর',
        outcomeText: 'টুংটুং মিষ্টি শব্দে পুরা বাড়ি মুখরিত হইলো! খালা কইলো রূপের রানী/রাজা!',
        tone: 'good',
        effects: { looks: 8, happiness: 12 },
      },
      {
        id: 'infant_stare_dazed',
        text: 'চোখ গোল গোল কইরা রঙের মেলা দেখতে থাক',
        outcomeText: 'চুড়িওয়ালি আন্টি খুশি হইয়া একটা রঙিন ফিতা ফাউ দিলো!',
        tone: 'good',
        effects: { happiness: 8, smarts: 5 },
      },
    ],
  },
  {
    id: 'infant_lalbagh_lawn_crawl',
    text: 'লালবাগ কেল্লার সবুজ মাঠে শীতের দুপুরে ফ্যামিলি পিকনিক। কচি ঘাসে তুই হামাগুড়ি দিতাছস!',
    minAge: 2,
    maxAge: 4,
    weight: 7,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_crawl_flowers',
        text: 'রঙিন ফুলের বাগানের দিকে ঝড়ের বেগে হামাগুড়ি দে',
        outcomeText: 'একখান হলুদ গাঁদা ফুল ছিঁড়া কানে গুঁজলি! ছবি তুইলা ফ্রেমে টানানো হইলো।',
        tone: 'good',
        effects: { happiness: 15, looks: 8 },
      },
      {
        id: 'infant_eat_grass',
        text: 'এক খাবলা ঘাস মুখে দিয়া চিবাইতে থাক',
        outcomeText: 'আব্বা দৌড়ায়া আইসা মুখ থিকা ঘাস বাইর করলো আর খিলখিল হাসলো!',
        tone: 'funny',
        effects: { health: -3, happiness: 6 },
      },
    ],
  },
  {
    id: 'infant_mosque_microphone_imitate',
    text: 'মহল্লার মসজিদের আজান শুইনা স্টিলের গ্লাস মুখের সামনে ধইরা তুইও সুর মিলাইতে লাগলি!',
    minAge: 3,
    maxAge: 5,
    weight: 6,
    tone: 'good',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_sing_sweet_azan',
        text: 'ভাঙ্গা ভাঙ্গা বুলিতে আজানের সুর নকল কর',
        outcomeText: 'দাদা শুইনা বুকে জড়ায়া দোয়া দিলো: "আমার পুতের মুখে কত নুর!"',
        tone: 'good',
        effects: { karma: 12, happiness: 10, smarts: 6 },
      },
      {
        id: 'infant_drop_glass',
        text: 'সুর শেষ কইরা গ্লাস মেঝের উপর ঝনঝন কইরা ফেলে দে',
        outcomeText: 'বিকট শব্দে আম্মা আঁতকে উঠলো, তয় তোর মিষ্টি হাসিতে রাগ গলে পানি!',
        tone: 'funny',
        effects: { happiness: 8 },
      },
    ],
  },
  {
    id: 'infant_spoon_bang_pot',
    text: 'রান্নাঘরে আম্মা বিরিয়ানি রানতাছে, তুই তলায় বইসা ডালের চামচ দিয়া ডেকচিতে ড্রাম বাজাচ্ছস!',
    minAge: 1,
    maxAge: 3,
    weight: 6,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_rockstar_beat',
        text: 'রকস্টার ড্রামারের লাহান তা ধিন ধিন কইরা পেটাও!',
        outcomeText: 'বিকট বাজনায় বাড়িশুদ্ধ মানুষ কাঁপলো, কিন্তু তোর তাল এক্কেবারে নির্ভুল!',
        tone: 'funny',
        effects: { happiness: 14, smarts: 6 },
      },
      {
        id: 'infant_lick_pot_bottom',
        text: 'বাজনা বাদ দিয়া ডেকচির নিচে লাইগা থাকা ভাতের কণা চাট',
        outcomeText: 'মশলার ঝাঁজে হেঁচকি শুরু হইলো, আম্মা মিষ্টি পানি খাওয়াইলো।',
        tone: 'neutral',
        effects: { health: -2, happiness: 6 },
      },
    ],
  },
  {
    id: 'infant_sibling_sharing_fight',
    text: 'আম্মা তোরে আর তোর বড় ভাইরে এক প্যাকেট চানাচুর ভাগ কইরা খাইতে দিছে। বাটিতে হাতাহাতি!',
    minAge: 4,
    maxAge: 5,
    weight: 7,
    tone: 'funny',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_hog_bowl',
        text: 'পুরা বাটি দুই হাতে জাপটে ধইরা মুখে উবুর কইরা দে!',
        outcomeText: 'চানাচুর নাকে-মুখে ঢুকলো, ভাই কান্দন দিলো আর আম্মা তোরে এক চিমটি কাটলো!',
        tone: 'bad',
        effects: { health: -3, karma: -6, happiness: 8 },
      },
      {
        id: 'infant_share_fairly',
        text: 'একটা একটা কইরা গুনে গুনে অর্ধেক ভাইয়ের পাতে দে',
        outcomeText: 'ভাই খুশি হইয়া তোরে চকলেট উপহার দিলো! ভাই-বোনের মহব্বত বাড়লো।',
        tone: 'good',
        effects: { karma: 10, happiness: 12, smarts: 5 },
      },
    ],
  },
  {
    id: 'infant_power_cut_handfan',
    text: 'তপ্ত বৈশাখের রাতে হঠাৎ লোডশেডিং! ঘামে শরীর ভিইজা চটচট করতেছে!',
    minAge: 2,
    maxAge: 4,
    weight: 6,
    tone: 'neutral',
    category: 'childhood',
    source: 'fallback',
    choices: [
      {
        id: 'infant_fan_dadi',
        text: 'তালপাতার পাখা হাতে নিয়া দাদীরে উল্টা বাতাস করার চেষ্টা কর',
        outcomeText: 'দাদী তোর আদর দেইখা কান্দা কান্দা হইয়া চুমুর পর চুমু বসাইলো!',
        tone: 'good',
        effects: { karma: 12, happiness: 14, looks: 4 },
      },
      {
        id: 'infant_whine_heat',
        text: 'ঘামের চোটে মেঝেতে গড়াগড়ি দিয়া ফ্যাঁচফ্যাঁচ কর',
        outcomeText: 'আম্মা বারান্দায় নিয়া ঠান্ডা বাতাসে ঘুম পাড়ায়া দিলো।',
        tone: 'neutral',
        effects: { health: 4, happiness: -2 },
      },
    ],
  },
];

