import type { LifeEventDef } from '@/lib/engine/types';

export const SENIOR_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'senior_ramna_park_walk',
    text: 'ভোরে রমনা পার্কে প্রাতঃভ্রমণে গিয়া ৫০ বছর আগের স্কুলের এক দোস্তের লগে দেখা হইয়া গেল!',
    minAge: 65,
    maxAge: 85,
    weight: 9,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'hug_and_cha_adda',
        text: 'বুকে জড়ায়ে ধইরা পার্কে বইসা কাঁচা ছোলার লগে আদা চা খাও',
        outcomeText: 'শৈশবের স্মৃতি রোমন্থন কইরা প্রাণখুলে হাসলি। রক্তচাপ নরমাল হইয়া শরীর ফুরফুরে!',
        tone: 'good',
        effects: { happiness: 25, health: 10 },
      },
      {
        id: 'brag_about_sons',
        text: 'নিজের ছেলেমেয়েরা বিদেশে কত কামায় হেই ফুডানি মারতে থাক',
        outcomeText: 'দোস্ত মুখ বাঁকা কইরা চইলা গেল। একাকীত্ব আরও বাড়ি জাঁকিয়ে বসলো।',
        tone: 'bad',
        effects: { happiness: -10, karma: -8 },
      },
    ],
  },
  {
    id: 'senior_spoil_grandkids',
    text: 'নাতনি বায়না ধরলো: "দাদু, আম্মায় চকলেট খাইতে মানা করছে, তুমি গোপনে ট্যাকা দাও না!"',
    minAge: 65,
    maxAge: 90,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'secret_chocolate_money',
        text: 'পকেট থিকা ১০০ টাকার নোট বাইর কইরা খিলখিল কইরা হাসো',
        outcomeText: 'নাতনি গালে চুমু দিয়া তোরে "বেস্ট দাদু" ঘোষণা করলো! মেয়ের মিষ্টি বকা খাইলি!',
        tone: 'good',
        effects: { happiness: 25, karma: 10, money: -20 },
      },
      {
        id: 'strict_advice',
        text: 'দাঁত নষ্ট হওয়ার ভয় দেখায়া নাতনিকে লম্বা নসিহত দাও',
        outcomeText: 'নাতনি মুখ গোমড়া কইরা দৌড়ায়া গেল। মন খারাপ লাগলো।',
        tone: 'neutral',
        effects: { happiness: -5 },
      },
    ],
  },
  {
    id: 'senior_tea_stall_politics',
    text: 'পাড়ার চায়ের দোকানে সমবয়সী মুরুব্বিরা দেশ ও আন্তর্জাতিক রাজনীতি নিয়া গরম বাহাসে জড়াইছে!',
    minAge: 66,
    maxAge: 88,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'shout_revolutionary_view',
        text: 'টেবিলে হাত থাপড়াইয়া ঐতিহাসিক যুক্তি পেশ কর!',
        outcomeText: 'তোর পাণ্ডিত্য শুইনা সবাই স্তব্ধ! চায়ের দোকানদার তোরে স্পেশাল মালাই চা উপহার দিলো!',
        tone: 'good',
        effects: { happiness: 15, smarts: 8 },
      },
      {
        id: 'sip_silently',
        text: 'ঝামেলা এড়ায়া নীরবে বিস্কুট ভিজায়া চা খাও',
        outcomeText: 'শান্তিপূর্ণ সন্ধ্যা। রক্তচাপ বাড়লো না, পরম শান্তিতে বাড়ি ফিরলি।',
        tone: 'neutral',
        effects: { health: 6, happiness: 5 },
      },
    ],
  },
  {
    id: 'senior_will_and_testament',
    text: 'উকিল সাব ড্রয়িংরুমে আইসা বসলো। সম্পত্তির উইল বণ্টন নিয়া ছেলেমেয়েদের মধ্যে হালকা চাপা গুঞ্জন!',
    minAge: 70,
    maxAge: 95,
    weight: 8,
    tone: 'neutral',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'equal_charity_division',
        text: 'সব ছেলেমেয়েকে সমান অধিকার দিয়া এতিমখানায় এক তৃতীয়াংশ দান কর',
        outcomeText: 'সবাই তোর নিরপেক্ষতা মানিয়া নিলো। পরকালের জন্য সেরা সঞ্চয় রেখে গেলি!',
        tone: 'good',
        effects: { karma: 25, happiness: 25 },
      },
      {
        id: 'favor_eldest_son',
        text: 'বড় ছেলের নামে বেশি লিখে বাকিদের বঞ্চিত কর',
        outcomeText: 'ছোট মেয়েরা অভিমানে কান্দাকাটি করলো। পরিবারে ফাটল ধইরা অশান্তি বাড়লো।',
        tone: 'bad',
        effects: { karma: -25, happiness: -20 },
      },
    ],
  },
  {
    id: 'senior_golden_anniversary',
    text: 'স্ত্রীর সাথে দাম্পত্য জীবনের ৫০ বছর পূর্ণ হইলো! নাতি-নাতনিরা কেক নিয়া পুরা বাড়ি সাজাইছে!',
    minAge: 68,
    maxAge: 92,
    weight: 9,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'gift_gold_bangle',
        text: 'সঞ্চয়ের টাকায় স্ত্রীর হাতে একজোড়া সোনার চুড়ি পরাইয়া দাও',
        outcomeText: 'বৃদ্ধা স্ত্রীর চোখে আনন্দের অশ্রু! তোর হাতে হাত রাইখা কইলো, "তুমিই আমার সাত জনমের সাথী!"',
        tone: 'good',
        effects: { happiness: 25, looks: 10, money: -150 },
      },
      {
        id: 'emotional_speech',
        text: 'পরিবারের সবার সামনে জীবনের সুখ-দুখের গল্প শুনাও',
        outcomeText: 'পুরা পরিবারের সবাই আবেগাপ্লুত হইয়া তোদের দোয়া করলো। পরম তৃপ্তি!',
        tone: 'good',
        effects: { happiness: 25, karma: 20 },
      },
    ],
  },
  {
    id: 'senior_peaceful_contemplation',
    text: 'শেষ বয়সে বারান্দায় বইসা এক কাপ লাল চা হাতে সূর্যাস্ত দেখতাছস। এক পা কবরে রাইখা জীবনের হিসাব মিলাইলি!',
    minAge: 75,
    maxAge: 105,
    weight: 10,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'grateful_heart',
        text: 'সৃষ্টিকর্তার দরবারে মাথা নত কইরা শুকরিয়া জানাও',
        outcomeText: '"জীবনে বহু চুদুর বুদুর করসিলাম, কিন্তু জীবন নিয়া খেলা কইরা দিনশেষে শান্তিতেই মরতে পারতাছি!"',
        tone: 'good',
        effects: { happiness: 25, karma: 25, health: 5 },
      },
    ],
  },
  {
    id: 'senior_grandson_ssc_gpa5',
    text: 'তোর আদরের নাতি এসএসসিতে গোল্ডেন জিপিএ-৫ পাইছে! মহল্লা কাঁপিয়ে মিষ্টি বিতরণের ধুম!',
    minAge: 65,
    maxAge: 85,
    weight: 8,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'buy_grandson_watch',
        text: 'নাতির হাতে নিজের ৫০ বছরের পুরনো ঐতিহ্যবাহী সুইস ঘড়ি পরিয়ে দাও',
        outcomeText: 'নাতি তোর কদমবুসি করে জড়িয়ে ধরলো! বংশের মুখে উজ্জ্বল আলো!',
        tone: 'good',
        effects: { happiness: 25, karma: 20, looks: 8 },
      },
      {
        id: 'distribute_jilapi_mosque',
        text: 'মহল্লার মসজিদে ৫ মন গরম জিলাপি তবারক বিলাও',
        outcomeText: 'নামাজের পর মুসল্লিরা দুই হাত তুলে তোর পরিবারের জন্য প্রাণভরে দোয়া করলো!',
        tone: 'good',
        effects: { money: -60, karma: 25, happiness: 25 },
      },
    ],
  },
  {
    id: 'senior_morning_walk_dhanmondi_lake',
    text: 'বাহাদুর শাহ পার্কে সমবয়সী মুরুব্বিদের সাথে হাসির ক্লাবে গোল হয়ে দাঁড়িয়ে প্রাণখোলা হাসি!',
    minAge: 62,
    maxAge: 88,
    weight: 8,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'laugh_heartily_arms_up',
        text: 'দুই হাত আসমানে তুলে হা হা হা করে প্রাণখুলে হাসো',
        outcomeText: 'ফুসফুসে নির্মল অক্সিজেন ঢুকলো! রক্ত সঞ্চালন বেড়ে শরীর ঝরঝরে!',
        tone: 'good',
        effects: { health: 22, happiness: 24 },
      },
      {
        id: 'cough_fit_bench',
        text: 'হাসতে গিয়ে দম আটকে বিষম খেয়ে বেঞ্চে বসে পড়ো',
        outcomeText: 'বন্ধুরা পিঠ চাপড়ে লেবু-পানি খাওয়ালো, তবে মনে কোনো বিষাদ রইলো না।',
        tone: 'funny',
        effects: { health: -4, happiness: 10 },
      },
    ],
  },
  {
    id: 'senior_arthritis_knee_pain',
    text: 'শীতের রাতে হাঁটুর তীব্র বাতের ব্যথায় সিঁড়ি ভাঙা দায়! খাটের সাথে পা আটকে যাওয়ার দশা!',
    minAge: 68,
    maxAge: 90,
    weight: 8,
    tone: 'bad',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'warm_mustard_oil_massage',
        text: 'কালোজিরা ও রসুনের গরম সরিষার তেল হাঁটুতে নিয়মিত মালিশ করো',
        outcomeText: 'ব্যথা অনেকটাই সহনীয় হলো! সকালে ছড়ি ভর দিয়ে স্বাচ্ছন্দ্যে হাঁটতে পারলে!',
        tone: 'good',
        effects: { health: 15, happiness: 12 },
      },
      {
        id: 'complain_bitterly_curse',
        text: 'ব্যথার চোটে সারাদিন শুয়ে শুয়ে ঘরের সবাইকে গালমন্দ করো',
        outcomeText: 'বাড়ির সবার মন খারাপ হলো, সংসারে অশান্তির ছায়া নেমে আসলো।',
        tone: 'bad',
        effects: { happiness: -20, karma: -12 },
      },
    ],
  },
  {
    id: 'senior_hearing_aid_adjustment',
    text: 'কানে নতুন ডিজিটাল হিয়ারিং এইড লাগাতেই আশপাশের ফিসফাস সব পরিষ্কার শোনা যাচ্ছে!',
    minAge: 65,
    maxAge: 92,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'eavesdrop_in_laws_gossip',
        text: 'বধূর চাপা প্রশংসা ও ভালোবাসার কথা শুনে মুচকি হাসো',
        outcomeText: 'সংসারের গোপন ভালোবাসা বুঝতে পারলে, সম্পর্কের বরফ গলে পানি!',
        tone: 'good',
        effects: { happiness: 22, smarts: 10 },
      },
      {
        id: 'turn_off_aid_peace',
        text: 'পারিবারিক খিটিরমিটির সময় হিয়ারিং এইডের সুইচ বন্ধ করে আরামে ঘুমাও',
        outcomeText: 'পরম নির্লিপ্ততা! পৃথিবীর সব কোলাহল বাইরে রেখে শান্তির ঘুম!',
        tone: 'good',
        effects: { happiness: 25, health: 8 },
      },
    ],
  },
  {
    id: 'senior_pigeon_hobby_rooftop',
    text: 'পুরান ঢাকার পৈতৃক বাড়ির ছাদে ৫০টি দুধসাদা সিরাজী কবুতরকে গম ছিটিয়ে পরম শান্তিতে সময় কাটাও!',
    minAge: 62,
    maxAge: 85,
    weight: 8,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'whistle_fly_pigeons',
        text: 'আকাশে কবুতরের ঝাঁক উড়িয়ে নীল আকাশের সৌন্দর্য উপভোগ করো',
        outcomeText: 'পাখির ডানার ঝাপটায় হৃদয়ের সমস্ত ক্লান্তি দূর হয়ে গেল!',
        tone: 'good',
        effects: { happiness: 25, health: 10 },
      },
      {
        id: 'gift_pair_to_neighbor',
        text: 'প্রতিবেশীর ছোট বাচ্চাকে একজোড়া কচি কবুতর উপহার দাও',
        outcomeText: 'বাচ্চাটির মুখের নিষ্পাপ হাসিতে মন ভরে উঠলো!',
        tone: 'good',
        effects: { karma: 18, happiness: 20 },
      },
    ],
  },
  {
    id: 'senior_granddaughter_wedding_gift',
    text: 'নাতনির বিদায়ের ক্ষণে তোর মা ও দাদীর রেখে যাওয়া শতবর্ষের খাঁটি সোনার হারটি তার গলায় তুলে দিলে!',
    minAge: 66,
    maxAge: 95,
    weight: 9,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'bless_with_tears',
        text: 'নাতনির মাথায় হাত রেখে জীবনের শ্রেষ্ঠ আশীর্বাদ করো',
        outcomeText: 'নাতনি কেঁদে বুক ভাসালো! প্রজন্মের পর প্রজন্ম বয়ে চলা ঐতিহ্যের পবিত্র রূপ!',
        tone: 'good',
        effects: { happiness: 25, karma: 25 },
      },
      {
        id: 'tell_ancient_love_story',
        text: 'নিজের তরুণ বয়সের প্রেমের মিষ্টি স্মৃতি শুনিয়ে সবাইকে হাসাও',
        outcomeText: 'কান্নার বিদায়ের মাঝেও এক স্নিগ্ধ হাসির আবহ তৈরি হলো!',
        tone: 'good',
        effects: { happiness: 25, looks: 8 },
      },
    ],
  },
  {
    id: 'senior_old_radio_transistor',
    text: 'বাবার আমলের কাঠের মারফি রেডিওটা ধুলো ঝেড়ে চালু করতেই ভেসে আসলো পুরনো দিনের কালজয়ী গান!',
    minAge: 65,
    maxAge: 90,
    weight: 7,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'listen_vintage_songs',
        text: 'চায়ের কাপে চুমুক দিয়ে সত্তরের দশকের গানের সুরে হারিয়ে যাও',
        outcomeText: 'হারিয়ে যাওয়া সোনালী দিনগুলো চোখের সামনে ভেসে উঠলো! পরম তৃপ্তি!',
        tone: 'good',
        effects: { happiness: 24, health: 6 },
      },
      {
        id: 'repair_antenna_wire',
        text: 'তামার তার দিয়ে অ্যান্টেনা মেরামত করতে গিয়ে কারেন্টের মৃদু শক খাও',
        outcomeText: 'হাত একটু ঝিনঝিন করলো, কিন্তু রেডিওর শব্দ ক্রিস্টাল ক্লিয়ার হয়ে গেল!',
        tone: 'funny',
        effects: { health: -3, happiness: 10 },
      },
    ],
  },
  {
    id: 'senior_mosque_elder_seat',
    text: 'মহল্লার প্রাচীন মসজিদে তোর জন্য সামনের কাতারের চেয়ারটি নির্দিষ্ট রাখা হয়। সবাই তোর দোয়া চায়!',
    minAge: 70,
    maxAge: 98,
    weight: 8,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'pray_sincerely_for_youth',
        text: 'মহল্লার তরুণদের সুপথ ও সফলতার জন্য দীর্ঘ মোনাজাত করো',
        outcomeText: 'সবাই পরম শ্রদ্ধায় তোর হাত চুম্বন করলো! সমাজে মুরুব্বির মর্যাদা অটুট!',
        tone: 'good',
        effects: { karma: 25, happiness: 25 },
      },
      {
        id: 'scold_kids_in_mosque',
        text: 'পেছনের কাতারের দুষ্টু বাচ্চাদের লাঠি উঁচিয়ে ধমক দাও',
        outcomeText: 'বাচ্চারা ভয়ে পালালো ঠিকই, কিন্তু তাদের বাবা-মা একটু অসন্তুষ্ট হলো।',
        tone: 'neutral',
        effects: { karma: -5, smarts: 4 },
      },
    ],
  },
  {
    id: 'senior_scam_call_lottery',
    text: 'ফোনে এক ভন্ড কলার বললো, "চাচাজান, আপনি ২৫ লাখ টাকার লটারি জিতেছেন! ৫০০০ টাকা বিকাশ করুন!"',
    minAge: 65,
    maxAge: 90,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'scold_scammer_dhakaiya',
        text: 'কড়া ঢাকাইয়া গলায় ঝাড়ি দাও: "আব্বে হালায়, আমারে মাইঙ্কা চিপায় ফালাইতে চাস? বাপের বয়সি মাইনষের লগে চুদুর বুদুর!"',
        outcomeText: 'প্রতারক ভয়ে তড়িঘড়ি ফোন কেটে দিল! উপস্থিত বুদ্ধির দারুণ বিজয়!',
        tone: 'good',
        effects: { smarts: 18, happiness: 20 },
      },
      {
        id: 'send_token_money_scam',
        text: 'লোভে পড়ে পেনশনের টাকা থেকে বিকাশ করে দাও',
        outcomeText: 'টাকা মেরে ফোন বন্ধ! পেনশনের কষ্টার্জিত টাকা হারিয়ে মাথায় হাত!',
        tone: 'bad',
        effects: { money: -100, happiness: -25 },
      },
    ],
  },
  {
    id: 'senior_cataract_eye_surgery',
    text: 'চোখের ছানি অপারেশনের পর ডাক্তার ব্যান্ডেজ খুললো। দীর্ঘদিনের ঝাপসা দুনিয়া হঠাৎ ঝলমলে পরিষ্কার!',
    minAge: 66,
    maxAge: 88,
    weight: 8,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'admire_grandkids_faces',
        text: 'ছোট ছোট নাতি-নাতনিদের সুন্দর মুখগুলো অপলক দৃষ্টিতে তাকিয়ে দেখো',
        outcomeText: 'চোখে খুশির অশ্রু! আবার বই পড়ার ও কোরআন তিলাওয়াতের আলো ফিরে পেলে!',
        tone: 'good',
        effects: { health: 25, happiness: 25, looks: 6 },
      },
      {
        id: 'rub_eyes_too_soon',
        text: 'খুশিতে সাথে সাথেই হাত দিয়ে চোখ রগড়ে ফেলো',
        outcomeText: 'চোখে লাল হয়ে জ্বালা শুরু হলো, আবার অ্যান্টিবায়োটিক ড্রপ দিতে হলো!',
        tone: 'bad',
        effects: { health: -8, happiness: -10 },
      },
    ],
  },
  {
    id: 'senior_old_photo_album',
    text: 'আলমারির নিচ থেকে ১৯৬০-৭০ এর দশকের সাদাকালো অ্যালবাম বের করে পুরনো বন্ধুদের মুখ খুঁজলি!',
    minAge: 68,
    maxAge: 95,
    weight: 7,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'share_stories_with_family',
        text: 'পরিবারের সবাইকে ডেকে প্রতিটি ছবির পেছনের রোমাঞ্চকর ইতিহাস শুনাও',
        outcomeText: 'সবাই মুগ্ধ হয়ে শুনলো! পরিবারের অতীত ইতিহাস অমর হয়ে রইলো!',
        tone: 'good',
        effects: { happiness: 24, smarts: 10, karma: 12 },
      },
      {
        id: 'cry_over_lost_friends',
        text: 'মারা যাওয়া দোস্তদের কথা মনে করে একা একা নীরব অশ্রু ফেলো',
        outcomeText: 'হৃদয় ভারী হলো, কিন্তু ভালোবাসার স্মৃতিগুলো চিরন্তন হয়ে রইলো।',
        tone: 'neutral',
        effects: { happiness: -6, karma: 10 },
      },
    ],
  },
  {
    id: 'senior_walking_stick_gift',
    text: 'বড় ছেলে বিদেশ থেকে রুপার কারুকাজ করা বার্মিজ সেগুন কাঠের একখানা ছড়ি এনে উপহার দিলো!',
    minAge: 67,
    maxAge: 95,
    weight: 8,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'walk_proudly_in_alley',
        text: 'ছড়ি ঠক ঠক করে রাজকীয় ভঙ্গিতে মহল্লায় সান্ধ্যকালীন হাঁটাহাঁটি করো',
        outcomeText: 'মুরুব্বি হিসেবে তোর ব্যক্তিত্ব এক্কেবারে জমিদারের মতো ফুটে উঠলো!',
        tone: 'good',
        effects: { looks: 12, happiness: 20 },
      },
      {
        id: 'keep_it_in_showcase',
        text: 'যত্ন করে সাজিয়ে রেখে সাধারণ বাঁশের লাঠি ব্যবহার করতে থাকো',
        outcomeText: 'মায়া করে দামি জিনিস ব্যবহারে কুণ্ঠা বোধ করলে, সাধারণ জীবনযাপনই বজায় রইলো।',
        tone: 'neutral',
        effects: { happiness: 8 },
      },
    ],
  },
  {
    id: 'senior_dementia_memory_lapse',
    text: 'পাড়ার মোড় থেকে চা খেয়ে ফেরার পথে হঠাৎ মনে করতে পারলে না কোন গলিতে তোর বাসা!',
    minAge: 75,
    maxAge: 100,
    weight: 8,
    tone: 'bad',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'ask_local_shopkeeper',
        text: 'শান্ত হয়ে পরিচিত মিষ্টির দোকানদারের কাছে গিয়ে নাম ঠিকানা বলো',
        outcomeText: 'দোকানদার শ্রদ্ধার সাথে হাত ধরে বাসায় পৌঁছে দিলো! মহল্লার ভালোবাসায় চোখ সজল!',
        tone: 'good',
        effects: { happiness: 15, karma: 12 },
      },
      {
        id: 'wander_in_panic',
        text: 'আতঙ্কিত হয়ে রোদে এলোমেলো হাঁটতে থাকো',
        outcomeText: 'ডিহাইড্রেশনে রাস্তায় মাথা ঘুরে পড়ে গেলে! স্থানীয় যুবকরা উদ্ধার করে হাসপাতালে নিলো!',
        tone: 'bad',
        effects: { health: -20, happiness: -22 },
      },
    ],
  },
  {
    id: 'senior_library_donation',
    text: 'জীবনের ৫০ বছরে তিল তিল করে জমানো ৫০০০ দুর্লভ বাংলা বই ও পাণ্ডুলিপি গণগ্রন্থাগারে দান করার ইচ্ছা!',
    minAge: 68,
    maxAge: 92,
    weight: 8,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'donate_to_public_library',
        text: 'তোর নামে আলাদা কর্নার করে শিক্ষার্থীদের জন্য উন্মুক্ত করে দাও',
        outcomeText: 'শিক্ষা মন্ত্রণালয় তোরে আজীবন সম্মাননা পদক দিলো! জ্ঞানের আলো ছড়িয়ে রইলো!',
        tone: 'good',
        effects: { karma: 25, happiness: 25, smarts: 20 },
      },
      {
        id: 'sell_to_paper_scrap',
        text: 'অলসতা করে ভাঙাড়ির দোকানে ওজন দরে বিক্রি করে দাও',
        outcomeText: 'মূল্যবান জ্ঞান ধ্বংস হলো, নিজের বিবেকের কাছে আজীবন ছোট হয়ে রইলে!',
        tone: 'bad',
        effects: { money: 50, karma: -25, happiness: -25 },
      },
    ],
  },
  {
    id: 'senior_grandchild_smartphone_lesson',
    text: '১২ বছরের নাতি তোরে স্মার্টফোনে হোয়াটসঅ্যাপে ভিডিও কল করা আর ইউটিউবে গজল শোনা শেখাচ্ছে!',
    minAge: 65,
    maxAge: 90,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'learn_video_calling',
        text: 'মনোযোগ দিয়ে শিখে বিদেশের ছেলেমেয়েদের সাথে প্রতিদিন ভিডিওতে কথা বলো',
        outcomeText: 'দূরত্ব ঘুচে গেল! একাকীত্ব মুছে গিয়ে পরিবার আবার এক আঙিনায় এলো!',
        tone: 'good',
        effects: { happiness: 25, smarts: 12 },
      },
      {
        id: 'press_wrong_buttons',
        text: 'ভুল বোতাম টিপে সারারাত ফ্ল্যাশলাইট অন রেখে ব্যাটারি ফুরিয়ে ফেলো',
        outcomeText: 'নাতি দেখে খিলখিল করে হাসলো! মিষ্টি পারিবারিক খুনসুটি!',
        tone: 'funny',
        effects: { happiness: 14 },
      },
    ],
  },
  {
    id: 'senior_legacy_tree_planting',
    text: 'পৈতৃক ভিটার আঙিনায় ভবিষ্যৎ প্রজন্মের মিষ্টি ফলের ছায়ার জন্য একখানা আম ও কাঁঠালের চারা রোপণ করলে!',
    minAge: 65,
    maxAge: 88,
    weight: 7,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'water_plant_daily',
        text: 'প্রতিদিন নিজ হাতে গাছের গোড়ায় পানি ও সার দিয়ে যত্ন নাও',
        outcomeText: 'গাছ তরতর করে বড় হলো! নিজের হাতের স্মৃতি প্রকৃতির বুকে অমর করে রাখলে!',
        tone: 'good',
        effects: { karma: 25, happiness: 24, health: 8 },
      },
      {
        id: 'let_goats_eat_seedling',
        text: 'বেড়া না দিয়ে ফেলে রাখলে ছাগল এসে চারা মুড়িয়ে খেয়ে গেল',
        outcomeText: 'মন খারাপ হলো, তবে নতুন করে আবার চারা লাগানোর শপথ নিলে!',
        tone: 'neutral',
        effects: { happiness: -6 },
      },
    ],
  },
  {
    id: 'senior_childhood_friend_passing',
    text: '১৯৫৫ সালের স্কুলের শেষ জীবিত বন্ধুটির পরলোকগমনের খবর আসলো। শৈশবের শেষ সাক্ষীটিও চলে গেল!',
    minAge: 75,
    maxAge: 100,
    weight: 9,
    tone: 'bad',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'attend_janaza_dua',
        text: 'লাঠিতে ভর দিয়ে তার জানাজায় শরিক হয়ে বন্ধুর রুহের মাগফিরাত কামনা করো',
        outcomeText: 'মৃত্যুর নিশ্চিত সত্যতা অন্তরে শান্তি এনে দিলো। বন্ধুর স্মৃতি অমলিন রইলো!',
        tone: 'good',
        effects: { karma: 22, happiness: 10, health: -4 },
      },
      {
        id: 'sink_into_deep_depression',
        text: 'ঘরের দরজা বন্ধ করে খাওয়া-দাওয়া ছেড়ে দিয়ে একা কেঁদে কাটাও',
        outcomeText: 'শরীর ভেঙে পড়লো, রক্তচাপ কমে দুর্বল হয়ে পড়লে।',
        tone: 'bad',
        effects: { health: -18, happiness: -25 },
      },
    ],
  },
  {
    id: 'senior_neighbor_dispute_arbitration',
    text: 'মহল্লার দুই বনেদি ভাইয়ের ২০ বছরের জমিজমা বিরোধ মেটাতে সবাই তোর দরবারে শালিস বসালো!',
    minAge: 68,
    maxAge: 95,
    weight: 8,
    tone: 'neutral',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'fair_unbiased_verdict',
        text: 'কোরআন ও আইনের আলোকে নিখুঁত নিরপেক্ষ বণ্টন ফয়সালা করে দাও',
        outcomeText: 'দুই ভাই তোর পায়ে ধরে কেঁদে কোলাকুলি করলো! রক্তপাত এড়ানোর মহৎ পুণ্য!',
        tone: 'good',
        effects: { karma: 25, happiness: 25, smarts: 16 },
      },
      {
        id: 'accept_sweet_box_bribe',
        text: 'এক ভাইয়ের পক্ষপাতিত্ব করে অবিচার রায় দাও',
        outcomeText: 'অন্য ভাই বদদোয়া দিলো! সমাজে তোর আজীবনের অর্জিত সম্মান মাটিতে মিশে গেল!',
        tone: 'bad',
        effects: { karma: -25, happiness: -25, looks: -10 },
      },
    ],
  },
  {
    id: 'senior_winter_sunbathing_mustard_oil',
    text: 'মাঘের মিষ্টি রোদে ছাদে ইজি চেয়ারে বসে কাশ্মীরি শাল জড়িয়ে খাঁটি সরিষার তেল মালিশের আনন্দ!',
    minAge: 65,
    maxAge: 95,
    weight: 8,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'soak_winter_sunshine',
        text: 'ভিটামিন ডি মেখে উষ্ণতায় চোখ বুজে আয়েশ করো',
        outcomeText: 'হাড্ডির জোড়াগুলো নরম হলো, বাতজ্বর কমে পরম শান্তি অনুভব করলে!',
        tone: 'good',
        effects: { health: 20, happiness: 22 },
      },
      {
        id: 'fall_asleep_get_sunburned',
        text: 'ঘুমের ঘোরে অতিরিক্ত কড়া রোদে তিন ঘণ্টা পুড়ে থাকো',
        outcomeText: 'চামড়া লাল হয়ে জ্বালা করলো! রাতে বরফ ঘষতে হলো!',
        tone: 'funny',
        effects: { health: -6, happiness: -6 },
      },
    ],
  },
  {
    id: 'senior_centenarian_birthday_dhaka',
    text: 'আলহামদুলিল্লাহ! চার প্রজন্মের নাতি-পুতিদের ঘিরে আজ তোর শততম জন্মদিন পালন হচ্ছে!',
    minAge: 85,
    maxAge: 105,
    weight: 10,
    tone: 'good',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'blow_hundred_candles',
        text: 'মুখে ফোকলা দাঁতের মিষ্টি হাসি দিয়ে পরিবারের সবাইকে বুকে জড়িয়ে ধরো',
        outcomeText: 'একটি পরিপূর্ণ, অর্থপূর্ণ জীবনের গৌরবময় সমাপ্তি লগ্ন! সবার চোখে তুই এক জীবন্ত কিংবদন্তি!',
        tone: 'good',
        effects: { happiness: 25, karma: 25, health: 10 },
      },
    ],
  },
];

