import type { LifeEventDef } from '@/lib/engine/types';

export const SENIOR_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'senior_ramna_park_walk',
    text: 'ভোরে রমনা পার্কে হাঁটতে গিয়া দেখস তোর ৭১ সালের পুরান দোস্ত, যেই হালায় তোর ৫ ট্যাকা মাইরা দিছিলো!',
    minAge: 65,
    maxAge: 85,
    weight: 9,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'hug_and_demand_money',
        text: 'জড়ায়ে ধইরা ক: "হালায়, ৫৩ বছরের সুদসহ আমার ৫ ট্যাকা বাইর কর!"',
        outcomeText: 'দোস্ত হাসতে গিয়া তার ফোকলা দাঁতের পাটি খুইলা তোর চায়ের কাপে পইড়া গেলো! তুই ঘিন্না খায়া বমি কইরা দিলি!',
        tone: 'funny',
        effects: { happiness: 15, health: -5, money: 5 },
      },
      {
        id: 'brag_about_america_son',
        text: 'আলগা ভাব নিয়া ক: "আমার পোলা তো আমেরিকায় ইঞ্জিনিয়ার!"',
        outcomeText: 'দোস্ত তোর ফাপড় ধইরা ফালালো! প্রমাণ দিয়া কইলো তোর পোলা দুবাইতে বাথরুম ধোয়! তোর ইজ্জত পুরাই ডাস্টবিনে!',
        tone: 'bad',
        effects: { happiness: -20, karma: -15, fame: -20 },
      },
    ],
  },
  {
    id: 'senior_spoil_grandkids',
    text: 'নাতনি আইসা ফিসফিস কইরা কয়: "দাদু, টিকটকে ভিডিও বানামু, ১০০ ট্যাকা দেও না!"',
    minAge: 65,
    maxAge: 90,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'secret_sweaty_money',
        text: 'লুঙ্গির চিপা থিকা ঘামে ভেজা গন্ধওয়ালা ১০০ ট্যাকার নোট বাইর কইরা দে!',
        outcomeText: 'নোটের গন্ধে নাতনি ওয়াক থু কইরা বমি কইরা দিলো! তয় ট্যাকা ঠিকই নিছে। তুই পুরাই বজ্জাত দাদু!',
        tone: 'funny',
        effects: { happiness: 20, karma: -5, money: -100 },
      },
      {
        id: 'strict_rock_candy',
        text: 'ট্যাকা না দিয়া ১০ বছরের পুরান পাথরের লাহান শক্ত একখান লজেন্স ধরায়া দে!',
        outcomeText: 'লজেন্স কামড়াইতে গিয়া নাতনির দাঁত ভাইঙ্গা গেলো! পোলার বউ আইসা তোরে এমুন গাইল দিলো, কান দিয়া ধোঁয়া বাইর হইলো!',
        tone: 'bad',
        effects: { happiness: -25, health: -5, karma: -20 },
      },
    ],
  },
  {
    id: 'senior_tea_stall_politics',
    text: 'মহল্লার টংয়ে বইসা সমবয়সী মুরব্বিরা ট্রাম্প আর বাইডেন নিয়া উরাধুরা গ্যাঞ্জাম লাগাইছে!',
    minAge: 66,
    maxAge: 88,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'shout_revolutionary_view',
        text: 'টেবিলে থাপ্পর মাইরা এক্কেরে কড়া একখান ডায়লগ দে!',
        outcomeText: 'থাপ্পর মারতে গিয়া তোর আলগা দাঁত খুইলা ডাইরেক্ট চা-ওয়ালার ডেকচির ভিতরে গিয়া পড়লো! পাবলিক তোরে ধইরা পিটাইলো!',
        tone: 'bad',
        effects: { happiness: -15, looks: -25, health: -10 },
      },
      {
        id: 'fake_philosopher_quote',
        text: 'আতেল সাইজা কার্ল মার্ক্স-এর নাম নিয়া ফাপড় দে!',
        outcomeText: 'এক ইয়াং পোলা আইসা তোর ভুল ধইরা তোরে "আক্কেল-লেস মুরব্বি" ডাকলো! অপমানে তোর বিস্কুট গলায় আটকায়া গেলো!',
        tone: 'bad',
        effects: { smarts: -15, fame: -20, health: -5 },
      },
    ],
  },
  {
    id: 'senior_will_and_testament',
    text: 'তুই জিন্দা থাকতেই তোর পোলাপাইন সম্পত্তির ভাগ নিয়া ড্রয়িংরুমে কুরুক্ষেত্র লাগাইছে!',
    minAge: 70,
    maxAge: 95,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'troll_leave_to_cat',
        text: 'উকিলরে বইলা সব সম্পত্তি তোর পোষা ছাগলের নামে লেইখা দে!',
        outcomeText: 'পোলাপাইন কাইন্দা ভাসায়া দিলো আর ছাগলরে বিরিয়ানি খাওয়ানো শুরু করলো! তুই ইজি চেয়ারে বইসা শয়তানের হাসি হাসলি!',
        tone: 'good',
        effects: { happiness: 30, smarts: 20, karma: -10 },
      },
      {
        id: 'favor_eldest_son',
        text: 'বড় পোলারে বেশি সম্পত্তি লেইখা দিয়া বাকিগুলারে বাঁশ দে!',
        outcomeText: 'ছোট মাইয়াগো মেজাজ ফায়ার! তারা তোর ছড়ি ভাইঙ্গা নর্দমায় ফালাইলো আর ডায়াবেটিসের ওষুধ লুকায়া রাখলো! তুই পুরাই মাইঙ্কা চিপায়!',
        tone: 'bad',
        effects: { health: -20, happiness: -30, karma: -25 },
      },
    ],
  },
  {
    id: 'senior_golden_anniversary',
    text: 'বউয়ের লগে বিয়ার ৫০ বছর! বুড়ি তোর দিকে ইমোশনাল লুক দিয়া তাকায়া আছে!',
    minAge: 68,
    maxAge: 92,
    weight: 9,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'gift_gold_nosepin',
        text: 'লুকায়া রাখা ট্যাকা দিয়া একখান সোনার নাকফুল পরাইয়া দে!',
        outcomeText: 'পড়াইতে গিয়া বুড়ি এমুন একখান হাঁচি দিলো, নাকফুল উইড়া গিয়া ডাইরেক্ট নাতির চোখে পড়লো! রোমান্স পুরাই আইসিইউতে!',
        tone: 'funny',
        effects: { happiness: 10, money: -100, health: -10 },
      },
      {
        id: 'emotional_speech_mistake',
        text: 'স্পিচ দিতে গিয়া ভুল কইরা ক: "আমি তো আসলে তোর ছোট বোনরে বিয়া করতে চাইছিলাম!"',
        outcomeText: 'বুড়ি রাগে চান্দি গরম কইরা তোর লুঙ্গির উপ্রে গরম চা ঢাইলা দিলো! তোর অণ্ডকোষ পুইড়া এক্কেরে কাবাব!',
        tone: 'bad',
        effects: { health: -30, happiness: -40, karma: -20 },
      },
    ],
  },
  {
    id: 'senior_peaceful_contemplation',
    text: 'বারান্দায় বইসা আসমানের দিকে চাইয়া লাইফের হিসাব মিলাইতাছোস, হঠাত একখান কাক আইসা মাথার উপ্রে ঘুরতাছে!',
    minAge: 75,
    maxAge: 105,
    weight: 10,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'grateful_heart_crow',
        text: 'আসমানে চাইয়া উপরওয়ালার কাছে শুকরিয়া আদায় কর!',
        outcomeText: 'মুখ হা কইরা শুকরিয়া আদায় করার টাইমে কাক ডাইরেক্ট তোর মুখে একতাল তরল হাগু কইরা দিলো! "আশীর্বাদ" পুরাই ডাইরেক্ট গিললি!',
        tone: 'bad',
        effects: { happiness: -20, health: -15, looks: -10 },
      },
    ],
  },
  {
    id: 'senior_grandson_ssc_gpa5',
    text: 'তোর নাতি এসএসসিতে এ-প্লাস পাইছে! তয় তুই জানস হালায় প্রশ্ন ফাঁস কইরা পাস করছে!',
    minAge: 65,
    maxAge: 85,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'give_vintage_watch',
        text: 'নাতির হাতে নিজের ৫০ বছরের পুরান সুইস ঘড়িটা পরাইয়া দে!',
        outcomeText: 'হারামজাদা ঘড়িটা বেইচা ফ্রি-ফায়ারের ডায়মন্ড কিনছে! তুই রাগে লাঠি দিয়া ওর চান্দি ফাটায়া দিলি!',
        tone: 'good',
        effects: { happiness: 10, money: -50, karma: -10 },
      },
      {
        id: 'brag_with_jilapi',
        text: 'মসজিদে ৫ মন জিলাপি বিলাইয়া ফাপড় নে!',
        outcomeText: 'পরের দিন পেপারে আইলো তোর নাতি অঙ্কে ডাব্বা মারছে! পুরা মহল্লা তোর মাগনা জিলাপি খায়া তোরে ধইরা রোস্ট করলো!',
        tone: 'bad',
        effects: { money: -60, fame: -30, happiness: -30 },
      },
    ],
  },
  {
    id: 'senior_morning_walk_dhanmondi_lake',
    text: 'রমনা পার্কে সমবয়সী মুরব্বিগো লগে গোল হইয়া লাফিং ক্লাবে হাসির প্র্যাকটিস!',
    minAge: 62,
    maxAge: 88,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'laugh_heartily_arms_up',
        text: 'দুই হাত আসমানে তুইলা খ্যাঁক খ্যাঁক কইরা গলা ফাটায়া হাস!',
        outcomeText: 'হাসতে গিয়া তোর লুঙ্গির গিট খুইলা ডাইরেক্ট পায়ের গোড়ালিতে! পার্কের আন্টিরা দেইখা চিল্লান দিয়া বেহুঁশ!',
        tone: 'bad',
        effects: { looks: -30, fame: 20, happiness: -20 },
      },
      {
        id: 'force_fake_laugh',
        text: 'ফাপড় নিয়া জোর কইরা আলগা হাসি দে!',
        outcomeText: 'জোর দিতে গিয়া তুই প্যান্টে হালকা হাগু কইরা দিলি! পেঙ্গুইনের লাহান পা ফাঁক কইরা লেংড়াইতে লেংড়াইতে বাড়ি ফিরলি!',
        tone: 'bad',
        effects: { health: -15, happiness: -25, karma: -10 },
      },
    ],
  },
  {
    id: 'senior_arthritis_knee_pain',
    text: 'শীতের রাইতে হাঁটুর বাতের ব্যথায় চান্দি গরম! এহন আবার তোর বাথরুমে যাওয়ার প্রেশার আইছে!',
    minAge: 68,
    maxAge: 90,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'warm_mustard_garlic_oil',
        text: 'রসুন আর কালোজিরা মিশানো কড়া গন্ধের সরিষার তেল হাঁটুতে ডলা দে!',
        outcomeText: 'তেলের এমুন পচা গন্ধ যে মশা সব মইরা গেলো! বউ গন্ধে তোরে খাট থিকা লাথি মাইরা নিচে ফালায়া দিলো, তয় হাঁটু পুরাই ফ্রি!',
        tone: 'good',
        effects: { health: 20, happiness: -10, looks: -5 },
      },
      {
        id: 'walk_alone_to_bathroom',
        text: 'কাউরে না ডাইকা হিরো সাইজা একলা বাথরুমে যাওয়ার ট্রাই কর!',
        outcomeText: 'পিছলা খাইয়া ডাইরেক্ট কমোডের ভিতরে মাথা ভইরা কাইত! গু-মুত মাইখা চিল্লান শুরু করলি, পুরা ফ্যামিলি আইসা তোর এই অবস্থা দেখলো!',
        tone: 'bad',
        effects: { health: -20, happiness: -40, looks: -25 },
      },
    ],
  },
  {
    id: 'senior_hearing_aid_adjustment',
    text: 'কানে নতুন ডিজিটাল মেশিন লাগাইতেই বাসার চিপা-চাপার ফিসফাস সব ডাইরেক্ট ব্রেনে হিট করতাছে!',
    minAge: 65,
    maxAge: 92,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'eavesdrop_in_laws_gossip',
        text: 'পোলার বউয়ের ফিসফাস আড়ি পাইতা শোন!',
        outcomeText: 'শুনলি বউ তোরে "খিটখিটে বুইড়া" ডাকতাছে! তুই শোধ নিতে চুপিসারে বাসার ওয়াইফাইয়ের তার কাইটা দিলি! পুরাই মাফিয়া!',
        tone: 'good',
        effects: { smarts: 15, karma: -10, happiness: 20 },
      },
      {
        id: 'turn_volume_max',
        text: 'আলগা ভাব নিয়া মেশিনের ভলিউম এক্কেরে ফুল কইরা দে!',
        outcomeText: 'ঠিক ওই টাইমেই কানের কাছের মসজিদে মাইকে আজান দিলো! তোর কানের পর্দা ফাইট্টা তুই ডাইরেক্ট বেহুঁশ গিয়া পড়লি!',
        tone: 'bad',
        effects: { health: -25, happiness: -20 },
      },
    ],
  },
  {
    id: 'senior_pigeon_hobby_rooftop',
    text: 'ছাদে উইঠা কবুতর পালতাছোস, হঠাত দেখস পাশের বাড়ির বিলাই তোর কবুতরের দিকে নজর দিতাছে!',
    minAge: 62,
    maxAge: 85,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'feed_pigeons_aay_aay',
        text: 'বিলাই ইগনোর কইরা "আয় আয়" বইলা গম ছিটা!',
        outcomeText: 'সব কবুতর তোর গায়ের উপ্রে আইসা পড়লো! একটা কবুতর হালায় ডাইরেক্ট তোর হা করা মুখের ভিতর হাগু কইরা দিলো! ফ্রেশ প্রোটিন!',
        tone: 'bad',
        effects: { happiness: -20, health: -10, looks: -15 },
      },
      {
        id: 'chase_cat_with_stick',
        text: 'হাতে লাঠি নিয়া বিলাইরে দৌড়ানি দে!',
        outcomeText: 'দৌড়াইতে গিয়া তুই নিজেই কবুতরের খোপের উপ্রে ভাইঙ্গা পড়লি! পালক আর গু মাইখা তুই পুরাই প্রমাণ সাইজের মুরগি হইয়া গেলি!',
        tone: 'bad',
        effects: { health: -15, looks: -20, happiness: -25 },
      },
    ],
  },
  {
    id: 'senior_granddaughter_wedding_gift',
    text: 'নাতনির বিয়ার বিদায়! তোর মা-দাদীর আমলের ১০০ বছরের পুরান সোনার হারটা তার গলায় পরাইতে গেলি!',
    minAge: 66,
    maxAge: 95,
    weight: 9,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'bless_with_necklace_sneeze',
        text: 'গলায় হার পরাইয়া কাইন্দা দোয়া করার ট্রাই কর!',
        outcomeText: 'দোয়া করতে গিয়া এমুন একখান হাঁচি দিলি, তোর নাকের বিশাল সর্দি ডাইরেক্ট নাতনির ব্রাইডাল মেকআপের উপ্রে পইড়া লেপ্টে গেলো!',
        tone: 'bad',
        effects: { happiness: -15, looks: -20, karma: -10 },
      },
      {
        id: 'roast_the_groom',
        text: 'মাইক হাতে নিয়া নতুন জামাইরে উরাধুরা রোস্টিং শুরু কর!',
        outcomeText: 'তোর ডায়লগে পুরা সেন্টারের পাবলিক হাসতে হাসতে কাইত! জামাইর মুখ কালা, কিন্তু তুই পুরাই আলফা-দাদু হিসেবে ইজ্জত কামাইলি!',
        tone: 'good',
        effects: { fame: 25, happiness: 20, smarts: 15 },
      },
    ],
  },
  {
    id: 'senior_old_radio_transistor',
    text: 'বাপের আমলের কাঠের মারফি রেডিওটা বাইর করছোস। হালায় সাউন্ড আসতাছে না, খালি ঘ্যাঁড় ঘ্যাঁড় করতাছে!',
    minAge: 65,
    maxAge: 90,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'slap_radio_fix',
        text: 'পুরান আমলের মেকানিক সাইজা রেডিওর চান্দিতে কষে দুইখান থাপ্পড় মার!',
        outcomeText: 'রেডিও চালু হইলো ঠিকই, কিন্তু ফুল ভলিউমে হারবাল ওষুধের সেক্স-পাওয়ার বড়ির এডভার্টাইজ বাজানো শুরু করলো! মেহমানদের সামনে তোর ইজ্জত পাংচার!',
        tone: 'bad',
        effects: { happiness: -20, fame: -15, looks: -10 },
      },
      {
        id: 'repair_antenna_bare_hands',
        text: 'খালি হাতে অ্যান্টেনার তার জোড়া লাগানোর ফাপড় নে!',
        outcomeText: 'কারেন্টের এমুন শট খাইলি যে তোর চুল খাড়া হইয়া আইনস্টাইন হইয়া গেলো! ডরে তুই প্যান্টে দুই ফোঁটা মুইতাও দিছোস!',
        tone: 'bad',
        effects: { health: -20, happiness: -15 },
      },
    ],
  },
  {
    id: 'senior_mosque_elder_seat',
    text: 'মসজিদে সামনের কাতারে তোর ভিআইপি প্লাস্টিকের চেয়ার! কিন্তু আইজকা দেখস এক পিচ্চি ওইখানে বইসা আছে!',
    minAge: 70,
    maxAge: 98,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'pray_sincerely_sleep',
        text: 'পিচ্চিরে সরাইয়া চেয়ারে বইসা বিশাল ইমোশনাল মোনাজাত শুরু কর!',
        outcomeText: 'মোনাজাত করতে করতে তুই ঘুমায়া গেলি! মাইকের সামনে হা কইরা এমুন নাক ডাকলি, পুরা মহল্লার মাইনষে তোর নাসিকা-গর্জন শুনলো!',
        tone: 'funny',
        effects: { fame: 15, happiness: -10, karma: -5 },
      },
      {
        id: 'hit_kid_with_stick',
        text: 'মেজাজ ফায়ার কইরা ছড়ি দিয়া পিচ্চির মাথায় একখান বাড়ি দে!',
        outcomeText: 'পিচ্চির বাপ আছিলো এলাকার মাস্তান! সে তোর চেয়ার ভাইঙ্গা তোরে জুতার র‍্যাকের চিপায় পাঠায়া দিলো! ইজ্জত এক্কেরে জিরো!',
        tone: 'bad',
        effects: { karma: -25, fame: -20, happiness: -30 },
      },
    ],
  },
  {
    id: 'senior_scam_call_lottery',
    text: 'ফোনে জিনের বাদশা কয়, "চাচাজান, আপনে ২৫ লাখের লটারি পাইছেন! জলদি ৫০০০ ট্যাকা বিকাশ করেন!"',
    minAge: 65,
    maxAge: 90,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'scold_scammer_dhakaiya',
        text: 'কড়া ঢাকাইয়া ভাষায় বাটপারের চৌদ্দগুষ্ঠি উদ্ধার কইরা গাইল দে!',
        outcomeText: 'তোর এমুন ক্রিয়েটিভ গাইল শুইনা জিনের বাদশা কাইন্দা দিয়া তওবা পইড়া লাইন কাইটা দিছে! তুই পুরাই লেজেন্ড!',
        tone: 'good',
        effects: { smarts: 25, happiness: 20 },
      },
      {
        id: 'send_wife_secret_money',
        text: 'লোভে পইড়া বউয়ের ব্রা-এর চিপায় লুকাইয়া রাখা ট্যাকা চুরি কইরা বিকাশ মাইরা দে!',
        outcomeText: 'ট্যাকা গিয়া লাল বাত্তি! বউ ট্যাকা চুরির কথা ধইরা ফালাইয়া তোরে ঝাড়ু দিয়া এমুন পিটানি দিলো, তোর পিঠের ছাল উইঠা গেলো!',
        tone: 'bad',
        effects: { money: -100, health: -20, happiness: -35 },
      },
    ],
  },
  {
    id: 'senior_cataract_eye_surgery',
    text: 'চোখের ছানি অপারেশনের পর ডাক্তার ব্যান্ডেজ খুললো। অনেকদিন পর দুনিয়া এক্কেরে ফোরকে (4K) ক্লিয়ার!',
    minAge: 66,
    maxAge: 88,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'admire_wife_wrinkles',
        text: 'খুশিতে বউয়ের মুখের দিকে ড্যাবড্যাব কইরা তাকা!',
        outcomeText: 'বউয়ের রিঙ্কেল দেইখা তুই টাসকি খাইয়া কইয়া ফালালি, "ইমা, আপনি কে?" বউ রাগে তোর এক সপ্তাহের খাওয়া বন্ধ কইরা দিলো!',
        tone: 'bad',
        effects: { happiness: -20, health: -10, karma: -15 },
      },
      {
        id: 'rub_eyes_too_soon',
        text: 'চুলকানির চোটে চোখ হাত দিয়া উরাধুরা ডইলা ফ্যাল!',
        outcomeText: 'ডলতে গিয়া লেন্স ঘুইরা গেছে! এহন তুই দুনিয়া উল্টা দেখতাছোস আর চক্কর খাইয়া বমি কইরা পুরা বিছানা ভাসাইলি!',
        tone: 'bad',
        effects: { health: -25, happiness: -20 },
      },
    ],
  },
  {
    id: 'senior_old_photo_album',
    text: 'আলমারির নিচ থিকা পুরান অ্যালবাম বাইর করছোস। হালায় সব অতীত আইসা তোর চান্দিতে হিট করতাছে!',
    minAge: 68,
    maxAge: 95,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'show_handsome_photos',
        text: 'নাতি-নাতনিগো ডাইকা তোর ইয়াং বয়সের হ্যান্ডসাম ছবি দেখাইয়া ফুটানি মার!',
        outcomeText: 'তারা দেখলো তুই বেলবটম প্যান্ট পইড়া রাস্তার রোমিওর লাহান খাড়ায়া আছোস! তোরে নিয়া টিকটকে মিম বানায়া ভাইরাল কইরা দিলো!',
        tone: 'bad',
        effects: { fame: 20, happiness: -15, looks: -10 },
      },
      {
        id: 'cry_over_ex_lover',
        text: 'পুরান প্রেমিকার ছবি বাইর কইরা চুপিচুপি ফ্যাঁচফ্যাঁচ কইরা কান্দ!',
        outcomeText: 'বউ আইসা ধইরা ফালাইলো! অ্যালবাম ছিঁড়া তরকারিতে এক্সট্রা মরিচ দিয়া তোরে খাওয়াইলো, তিনদিন ধইরা তোর পাছা জ্বলতাছে!',
        tone: 'bad',
        effects: { health: -15, happiness: -25, karma: -20 },
      },
    ],
  },
  {
    id: 'senior_walking_stick_gift',
    text: 'বড় পোলা বিদেশ থিকা একখান স্মার্ট ভিআইপি ছড়ি পাঠাইছে! তুই তো পাইয়া পুরাই গডফাদার!',
    minAge: 67,
    maxAge: 95,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'poke_street_dog',
        text: 'রাস্তায় বাইর হইয়া ছড়ি দিয়া পাড়ার কুত্তারে খোঁচা মাইরা ফাপড় নে!',
        outcomeText: 'কুত্তা ছড়ি কামড়াইয়া ধইরা দৌড়! তুই ছড়ি বাঁচাইতে গিয়া কুত্তার পিছে পিছে হাঁপাইতে হাঁপাইতে পুরাই হার্ট অ্যাটাকের দশা!',
        tone: 'bad',
        effects: { health: -20, happiness: -15, looks: -20 },
      },
      {
        id: 'beat_servant_stick',
        text: 'জমিদার সাইজা কাজের পোলারে ছড়ি দিয়া একখান বাড়ি দে!',
        outcomeText: 'ছড়ি হালায় দুই টুকরা হইয়া গেলো! মেইড ইন চায়না মাল দিয়া পোলা তোরে স্ক্যাম করছে! তুই রাগে গালি দিয়া প্রেসার বাড়াইলি!',
        tone: 'bad',
        effects: { money: -50, happiness: -25, karma: -15 },
      },
    ],
  },
  {
    id: 'senior_dementia_memory_lapse',
    text: 'টং থিকা চা খায়া ফিরনের টাইমে হঠাত ব্রেন ব্ল্যাংক! নিজের বাড়ির গলি হালায় কোনদিকে?!',
    minAge: 75,
    maxAge: 100,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'threaten_rickshaw_puller',
        text: 'রিকশাওয়া্লারে ধমক দিয়া ক: "চিনস আমারে? ঠিকানায় নিয়া যা!"',
        outcomeText: 'সে তোরে ভুল ঠিকানায় নিয়া গেলো! তুই অন্যের বেডরুমে ঢুইকা চোর হিসেবে এমুন মাইর খাইলি, তোর দাঁত নড়ে গেলো!',
        tone: 'bad',
        effects: { health: -30, happiness: -30, smarts: -15 },
      },
      {
        id: 'pee_in_panic',
        text: 'ডরে প্যান্টে আধা মুইতা দিয়া চিপায় গিয়া খাড়া!',
        outcomeText: 'ওয়ার্ড কমিশনার তোরে তার দেওয়ালে মুততে দেইখা ধরলো! তোরে দিয়া তোর নিজের গেঞ্জি দিয়া দেওয়াল মুছাইলো! ইজ্জতের ফালুদা!',
        tone: 'bad',
        effects: { fame: -30, happiness: -40, looks: -25 },
      },
    ],
  },
  {
    id: 'senior_library_donation',
    text: 'তোর ঘরে ৫০ বছরের জমানো পুরান পেপার আর ম্যাগাজিনের পাহাড় জইমা আছে!',
    minAge: 68,
    maxAge: 92,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'donate_to_public_library',
        text: 'সব বই আর ম্যাগাজিন এলাকার পাবলিক লাইব্রেরিতে দান মাইরা দে!',
        outcomeText: 'লাইব্রেরিয়ান তোর বইয়ের চিপায় পুরান আমলের "প্রাপ্তবয়স্কদের" ম্যাগাজিন পাইয়া গেলো! পোলাপাইনের কাছে তুই এহন লেজেন্ড দাদু!',
        tone: 'funny',
        effects: { fame: 30, happiness: 10, karma: -10 },
      },
      {
        id: 'sell_to_paper_scrap',
        text: 'ভাঙ্গারির দোকানে কেজি দরে সব বেইচা দে!',
        outcomeText: 'ভাঙ্গারিওয়ালা পাল্লায় বাটপারি কইরা ১০০ কেজি মাল মাত্র ৫০ ট্যাকা দিয়া নিয়া গেলো! তুই হালায় পুরাই স্ক্যাম খাইলি!',
        tone: 'bad',
        effects: { money: 10, smarts: -20, happiness: -15 },
      },
    ],
  },
  {
    id: 'senior_grandchild_smartphone_lesson',
    text: 'তোর পোলাপাইন তোরে স্মার্টফোন ধরাইয়া ফেসবুক চালানো শিখাইতাছে!',
    minAge: 65,
    maxAge: 90,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'comment_mashaallah_bikini',
        text: 'ফেসবুকে ঢুইকাই একটা ছবিতে "মাশাআল্লাহ" কমেন্ট কর!',
        outcomeText: 'তুই হালায় এক মাইয়ার বিকিনি পরা ছবিতে "মাশাআল্লাহ" কমেন্ট করছোস! ফ্যামিলি গ্রুপ চ্যাটে সবাই তোরে নিয়া ছি ছি করতাছে!',
        tone: 'bad',
        effects: { fame: -25, happiness: -20, karma: -15 },
      },
      {
        id: 'press_random_live_button',
        text: 'না বুইঝা লাইভ (Live) বাটনে চাপ দিয়া বইসা থাক!',
        outcomeText: 'তুই ফেসবুকে লাইভে গিয়া নাক খুঁইটা নাকের ময়লা খাইতাছোস! ৫০০ মাইনষে লাইভ দেখলো, তোর নাতি লজ্জায় বাসা থিকা ভাইগা গেছে!',
        tone: 'bad',
        effects: { looks: -30, fame: -20, happiness: -25 },
      },
    ],
  },
  {
    id: 'senior_legacy_tree_planting',
    text: 'পৈতৃক ভিটায় ভবিষ্যৎ জেনারেশনের লাইগা একখান আম গাছের চারা লাগানোর ফাপড় নিছোস!',
    minAge: 65,
    maxAge: 88,
    weight: 7,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'dig_septic_tank',
        text: 'হাতে কোদাল নিয়া নিজেই উরাধুরা গর্ত খোঁড়া শুরু কর!',
        outcomeText: 'কোদালের কোপে তুই মাটির তলের সেপটিক ট্যাংক ফাটাইয়া দিছোস! পুরা উঠানে ডাইরেক্ট তরল হাগুর বন্যা, তুইও তার মইধ্যে ডুব দিছোস!',
        tone: 'bad',
        effects: { health: -20, happiness: -35, looks: -30 },
      },
      {
        id: 'force_lazy_grandson',
        text: 'তোর অলস নাতিরে ধইরা আন গাছ লাগানোর কামে!',
        outcomeText: 'হারামজাদা চারাটারে উল্টা কইরা মানে শিকড় উপ্রে দিয়া লাগাইছে! তুই রাগে ওর টাকলু মাথায় এমুন থাপ্পড় দিলি যে শব্দ মহল্লা পার হইয়া গেলো!',
        tone: 'funny',
        effects: { happiness: -10, smarts: 10, karma: -5 },
      },
    ],
  },
  {
    id: 'senior_childhood_friend_passing',
    text: 'তোর লাইফের সবচেয়ে পুরান কম্পিটিটর আর দোস্ত হালায় পটল তুলছে! খবর আইসা পৌঁছাইছে!',
    minAge: 75,
    maxAge: 100,
    weight: 9,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'fake_cry_janaza',
        text: 'জানাজায় গিয়া মাইকের সামনে আলগা কাইন্দা দোয়া কর!',
        outcomeText: 'কান্দনের ফাঁকে তুই কইয়া ফালালি, "হালায় মরার আগে আমার ৫০০ ট্যাকা দিয়া গেলো না!" মাইকে পুরা মহল্লা শুইনা ফেললো, ইজ্জত জিরো!',
        tone: 'bad',
        effects: { fame: -20, karma: -15, happiness: -10 },
      },
      {
        id: 'refuse_to_go_ego',
        text: 'ইগো দেখাইয়া জানাজায় না গিয়া ঘরে বইসা থাক!',
        outcomeText: 'রাইতে দোস্তের ভূত তোর স্বপ্নে আইসা তোর মুখের উপ্রে পাদ দিয়া গেলো! সকালে উইঠা দেখস তোর মুখ দিয়া আসলেও গু-এর গন্ধ বাইর হইতাছে!',
        tone: 'bad',
        effects: { health: -15, happiness: -25, karma: -20 },
      },
    ],
  },
  {
    id: 'senior_neighbor_dispute_arbitration',
    text: 'মহল্লার দুই মাস্তানের জমি নিয়া গ্যাঞ্জাম! তোরে বানাইছে প্রধান বিচারপতি, শালিস বইসা গেছে!',
    minAge: 68,
    maxAge: 95,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'badass_verdict_teeth_fly',
        text: 'টেবিলে থাপ্পড় মাইরা এক্কেরে কড়া একখান জাজমেন্ট ফালায়া দে!',
        outcomeText: 'ডায়লগ দিতে গিয়া তোর আলগা দাঁত ফস্কা গিয়া ডাইরেক্ট ইউপি চেয়ারম্যানের কপালের মাঝখানে হিট করলো! শালিস বাদ দিয়া সবাই তোরে দৌড়ানি দিলো!',
        tone: 'bad',
        effects: { looks: -25, health: -10, fame: -20 },
      },
      {
        id: 'eat_bribe_sweets_diarrhea',
        text: 'এক পার্টির ঘুষ দেওয়া দুই বাক্স প্রিমিয়াম মিষ্টি একলাই গপাগপ গিল!',
        outcomeText: 'মিষ্টি খায়া শালিসের মাঝখানেই তোর বিকট ডাইরিয়া শুরু! প্যান্ট নষ্ট কইরা তুই জাজমেন্ট রাইখাই বাথরুমের দিকে দৌড় দিলি!',
        tone: 'bad',
        effects: { health: -25, happiness: -30, karma: -20 },
      },
    ],
  },
  {
    id: 'senior_winter_sunbathing_mustard_oil',
    text: 'মাঘ মাসের শীত! ছাদে ইজি চেয়ারে বইসা সরিষার তেল মাইখা রোদে আরাম নিবি!',
    minAge: 65,
    maxAge: 95,
    weight: 8,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'strip_oil_massage_crow',
        text: 'গামছা পইড়া তেল মাইখা রোদে চিৎ হইয়া নাক ডাইকা ঘুমা!',
        outcomeText: 'এক্কান কাক তোর তেলতেলা চকচকা ভুঁড়িরে ল্যান্ডিং প্যাড ভাইবা ওইখানেই বিশাল একখান হাগু কইরা দিলো! ঘুম ভাইঙ্গা দেখস তুই গু-মাখা পরোটা!',
        tone: 'bad',
        effects: { health: -10, happiness: -25, looks: -20 },
      },
      {
        id: 'pay_barber_massage',
        text: 'পাড়ার নাপিতে ডাইকা আইন্যা উরাধুরা মালিশ করা!',
        outcomeText: 'নাপিত হালায় তোর পাও এমুন মোচড় দিলো যে তোর হিপ জয়েন্ট খুইলা গেলো! তুই ছাদে পইড়া মরা ছাগলের লাহান চিল্লান শুরু করলি!',
        tone: 'bad',
        effects: { health: -30, happiness: -20, money: -20 },
      },
    ],
  },
  {
    id: 'senior_centenarian_birthday_dhaka',
    text: 'তোর ১০০ বছর পূর্তি! পোলাপাইন বিশাল কেক আইন্না ১০০টা ক্যান্ডেল জ্বালাইছে!',
    minAge: 85,
    maxAge: 105,
    weight: 10,
    tone: 'funny',
    category: 'senior',
    source: 'fallback',
    choices: [
      {
        id: 'blow_hundred_candles_passout',
        text: 'বুক ভইরা শ্বাস নিয়া ১০০টা মোমবাতি একলগে ফুঁ দিয়া নিভানোর ফাপড় নে!',
        outcomeText: 'ফুঁ দিতে গিয়া তোর ফোকলা দাঁতের পাটি উইড়া গিয়া কেকের মইধ্যে গাঁইথা গেলো, আর তুই অক্সিজেনের অভাবে ডাইরেক্ট বেহুঁশ! বেস্ট বার্থডে এভার!',
        tone: 'funny',
        effects: { health: -20, happiness: 10, fame: 30, looks: -15 },
      },
    ],
  },
];