import type { LifeEventDef } from '@/lib/engine/types';

export const TEEN_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'teen_ssc_admit_lost',
    text: 'এসএসসি পরীক্ষার আর দুই দিন বাকি! ড্রয়ার খুইলা দেখস তোর এডমিট কার্ড হাওয়া! ডরে তোর চান্দির চুল খাড়া হইয়া গেছে!',
    minAge: 15,
    maxAge: 17,
    weight: 9,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'search_dustbin',
        text: 'গু-মুত মাখা পুরান কাগজের স্তূপ ঘাইটা এডমিট কার্ড বাইর কর!',
        outcomeText: 'তেলাপোকার হাগু মাখা এডমিট কার্ড পাইছোস! পরীক্ষার হলে গন্ধে স্যার তোরে ঘাড়ধাক্কা দিয়া বাইর কইরা দিলো!',
        tone: 'good',
        effects: { happiness: 15, smarts: 5, looks: -10 },
      },
      {
        id: 'confess_father',
        text: 'বাপের পাও ধইরা ফ্যাঁচফ্যাঁচ কইরা কাইন্দা সত্যি কথা ক!',
        outcomeText: 'বাপে তোরে এমুন লাথি মারলো যে তুই উইড়া গিয়া ড্রেনে পড়লি! এডমিট কার্ড বাইর হইলো ঠিকই, কিন্তু তোর পাছা ফাইট্টা দুই টুকরা!',
        tone: 'neutral',
        effects: { happiness: -20, health: -15 },
      },
    ],
  },
  {
    id: 'teen_coaching_crush',
    text: 'উদ্ভাসের কোচিংয়ে সামনের বেঞ্চের কড়া মাইয়ার দিকে চোখ আটকাইছে। মাইয়াও ঘাড় ঘুরাইয়া এক্কেরে লুক দিলো!',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'pass_tissue_note',
        text: 'নিজের ঘাম মোছা টিস্যুতে কড়া শায়রি লেইখা মাইয়ার দিকে ফিক্কা মার!',
        outcomeText: 'তোর ঘামের গন্ধে মাইয়া ডাইরেক্ট বমি কইরা দিলো! পুরা কোচিংয়ে তুই "বমি-মামা" নামে ফেমাস হইয়া গেলি!',
        tone: 'bad',
        effects: { happiness: -15, looks: -20, fame: 15 },
      },
      {
        id: 'hesitate_look_down',
        text: 'লজ্জায় লাল হইয়া নাকের সর্দি টাইন্না গিল্যা ফ্যাল!',
        outcomeText: 'মাইয়া তোর সর্দি গিলা দেইখা ওয়াক থু দিয়া পল্টি নিলো! তুই হালায় আজীবন সিঙ্গেলই থাকবি!',
        tone: 'bad',
        effects: { happiness: -10, smarts: -5, looks: -10 },
      },
    ],
  },
  {
    id: 'teen_bike_borrow_flex',
    text: 'বড় ভাইয়ের এফজেড (FZ) হোন্ডা ধার নিয়া ফুটানি মারতে গিয়া ব্রেক ফেইল! ডাইরেক্ট টংয়ের দোকানে গিয়া গুঁতা!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'pay_tea_stall',
        text: 'চা-মামার পাও ধইরা ভাইঙ্গা যাওয়া কাপের ট্যাকা গুন হালায়!',
        outcomeText: 'বড় ভাই হোন্ডার স্ক্র্যাচ দেইখা তোর প্যান্ট খুইলা গরম চা ঢাইলা দিলো! পাছা পুইড়া এক্কেরে কাবাব!',
        tone: 'bad',
        effects: { money: -50, health: -15, happiness: -20 },
      },
      {
        id: 'accelerate_run',
        text: 'পিকআপ তুইলা এক্কেরে উসাইন বোল্ট সাইজা ভোঁ দৌড় দে!',
        outcomeText: 'দৌড়াইতে গিয়া ড্রেনের চিপায় চাকা আটকায়া ডাইরেক্ট গু-এর স্তূপে ল্যান্ডিং! বড় ভাইয়ের মাইর আর গু-এর গন্ধ, লাইফ তেজপাতা!',
        tone: 'bad',
        effects: { karma: -20, happiness: -25, looks: -15 },
      },
    ],
  },
  {
    id: 'teen_first_mustache_shave',
    text: 'ঠোঁটের উপ্রে কচি গোঁফ উঠতেই আব্বার রেজার দিয়া নবাবের লাহান শেভ করতে গিয়া ঠোঁট কাইটা রক্তারক্তি!',
    minAge: 14,
    maxAge: 16,
    weight: 6,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'alum_stone',
        text: 'চিপা থিকা বাথরুমের পুরান ফিটকিরি বাইর কইরা কষে ডলা দে!',
        outcomeText: 'ফিটকিরির জ্বলুনিতে তুই প্যান্টে মুইতা দিলি! ঠোঁট ফুইলা এক্কেরে বান্দরের পাছা হইয়া গেলো!',
        tone: 'funny',
        effects: { health: -10, smarts: -5, looks: -15 },
      },
      {
        id: 'stick_toilet_paper',
        text: 'হাগু করার টিস্যু ছিঁড়া থুতু দিয়া কাটা জায়গায় লাগায়া স্কুলে যা!',
        outcomeText: 'টিস্যুর গন্ধে তুই নিজেই বেহুঁশ! স্কুলে গেলে পোলাপাইন তোরে "গু-মুখা" বইলা খেপাইলো!',
        tone: 'bad',
        effects: { looks: -20, happiness: -15 },
      },
    ],
  },
  {
    id: 'teen_bunk_biryani',
    text: 'দোস্তরা ফাপড় নিলো: "কিসের ফিজিক্স কোচিং, চল নাজিরাবাজারে গিয়া নান্নার বিরিয়ানি উড়াইয়া আসি!"',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'join_biryani_bunk',
        text: 'বই-খাতা ড্রেনে ফালাইয়া ডাইরেক্ট নান্নার বিরিয়ানির ডেকচিতে ঝাঁপ দে!',
        outcomeText: 'খাইতে খাইতে বিরিয়ানির তলে মরা ইঁদুর পালি! বমি কইরা পুরা দোকান ভাসাইলি, স্যার উল্টা আব্বারে নালিশ দিলো!',
        tone: 'funny',
        effects: { happiness: -20, health: -15, karma: -10 },
      },
      {
        id: 'stay_in_class',
        text: 'আতেল সাইজা ক্লাসের ফার্স্ট বেঞ্চে গিয়া খ্যাঁকখ্যাঁক কর!',
        outcomeText: 'স্যার কঠিন পড়া ধরলো, তুই না পাইরা ডরে প্যান্টে হাগু কইরা দিলি! বিরিয়ানিও মিস, ইজ্জতও মিস!',
        tone: 'bad',
        effects: { smarts: -5, happiness: -25, looks: -10 },
      },
    ],
  },
  {
    id: 'teen_football_tournament',
    text: 'লালবাগ বনাম আরমানিটোলার মহল্লা কাপ ফাইনাল! তুই নামছোস লেফট উইঙ্গার হইয়া!',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'banana_kick_goal',
        text: 'বক্সের বাইরে থিকা আলগা ফাপড় নিয়া বানানা কিক মার!',
        outcomeText: 'কিক মারতে গিয়া তোর জুতা উইড়া গিয়া রেফারির মুখে পড়লো! রেফারি লাল কার্ড দিয়া তোরে লাথি মাইরা বাইর করলো!',
        tone: 'bad',
        effects: { happiness: -20, looks: -10, fame: -5 },
      },
      {
        id: 'pass_to_striker',
        text: 'বলটা ডাইরেক্ট স্ট্রাইকার দোস্তের আন্ডারওয়ার বরাবর পাস দে!',
        outcomeText: 'বল গিয়া দোস্তের অন্ডকোষে ডাইরেক্ট হিট! দোস্ত বেহুঁশ, তুই পুরাই কিলার! ম্যাচ বাতিল!',
        tone: 'funny',
        effects: { happiness: -10, karma: -20 },
      },
    ],
  },
  {
    id: 'teen_night_gaming_parlor',
    text: 'রাইতে আব্বা ঘুমাইলেই চুপিচুপি জানলা গইলা মহল্লার গেমিং পার্লারে ফিফা (FIFA) পিটাইতে গেলি!',
    minAge: 15,
    maxAge: 17,
    weight: 7,
    tone: 'neutral',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'win_fifa_pot',
        text: 'টানা ৫ ম্যাচ জিতা পোলাপাইনের সব ট্যাকা চুষা নে!',
        outcomeText: 'ট্যাকা তো পাইলি, কিন্তু ভোরে জানলা দিয়া ঢুকতে গিয়া আব্বার গায়ের উপ্রে পড়লি! আব্বা তোরে ছিলা মুর্গি বানাইলো!',
        tone: 'funny',
        effects: { money: 100, happiness: -15, health: -20 },
      },
      {
        id: 'lose_all_money',
        text: 'উরাধুরা ম্যাচ হাইরা পকেটের সব ট্যাকা গুবলেট কর!',
        outcomeText: 'ট্যাকা হারায়ে ডরে তুই গেমিং পার্লারের বাথরুমে লুকাইলি! সকালে মেথর আইসা তোরে ঝাড়ু দিয়া পিটাইলো!',
        tone: 'bad',
        effects: { money: -50, happiness: -30, looks: -10 },
      },
    ],
  },
  {
    id: 'teen_sakrain_festival',
    text: 'সাকরাইন উৎসব! ছাদ থিকা ফায়ারব্রেথিং আর গান বাজতাছে। দোস্ত একখান ফানুস ধরাইয়া দিলো!',
    minAge: 14,
    maxAge: 17,
    weight: 9,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'release_lantern_wish',
        text: 'আসমানে ফানুস উড়াইয়া একখান কড়া মাইয়ার লাইগা দোয়া কর!',
        outcomeText: 'তোর ফানুস গিয়া পাশের বাড়ির মুরগির খোপে আগুন ধরাইলো! পুরা মহল্লা তোরে পোড়া মুরগির লাহান পিটাইলো!',
        tone: 'bad',
        effects: { happiness: -25, health: -15, karma: -20 },
      },
      {
        id: 'fire_spinning_charka',
        text: 'মুখে কেরোসিন নিয়া আগুনের ভলকানো বানা হালায়!',
        outcomeText: 'আগুন ডাইরেক্ট তোর নিজের লুঙ্গিতে ধইরা গেলো! ন্যাংটা হইয়া ছাদের উপ্রে দৌড়ানি, পুরা মহল্লায় তুই ভাইরাল!',
        tone: 'funny',
        effects: { happiness: -20, health: -15, fame: 20, looks: -25 },
      },
    ],
  },
  {
    id: 'teen_roof_eye_contact',
    text: 'বিকালে ছাদের রেলিঙে খাড়াইয়া পাশের ছাদের এক কড়া মাইয়ার লগে চোখাচোখি! মাইয়াও একপলক তাকাইলো!',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'smile_wave_roof',
        text: 'দাঁত বাইর কইরা বান্দরের লাহান একখান হাসি দে!',
        outcomeText: 'তোর হলুদ দাঁত আর মুখের গন্ধ দূর থিকাই টের পাইয়া মাইয়া বমি কইরা দিলো! প্রেম পুরাই ডাস্টবিনে!',
        tone: 'bad',
        effects: { happiness: -20, looks: -15 },
      },
      {
        id: 'whistle_loudly',
        text: 'দুই আঙ্গুল মুখে দিয়া ফইন্নির লাহান শিষ বাজা!',
        outcomeText: 'শিষ শুইনা মাইয়ার বাপ ডাইরেক্ট বন্দুক বাইর করছে! তুই মুততে মুততে ছাদ থিকা লাফ দিলি গবরের স্তূপে!',
        tone: 'funny',
        effects: { happiness: -15, health: -10, looks: -10 },
      },
    ],
  },
  {
    id: 'teen_sakrain_fire_eating',
    text: 'সাকরাইনে মহল্লার বড় ভাইরা মুখে কেরোসিন নিয়া মশাল জ্বালাইতাছে! তোরেও কইলো, "আয় ভাতিজা, আগুন ছাড়!"',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'spit_fire_pro',
        text: 'কেরোসিন মুখে নিয়া ড্রাগন সাইজা ফুঁ দে হালায়!',
        outcomeText: 'আগুন তোর ভ্রু আর চুল পুড়াইয়া পুরাই টাকলু বানায়া দিলো! তুই এহন মহল্লার এলিয়েন, মাইয়ারা দেইখা ভয় পায়!',
        tone: 'bad',
        effects: { happiness: -20, looks: -30, smarts: -5 },
      },
      {
        id: 'choke_kerosene',
        text: 'কেরোসিন গিল্যা ফ্যাল আর গলার ভিতরে ব্লাস্ট কর!',
        outcomeText: 'তুই কেরোসিন খাইয়া এমন পাদ দিলি যে পাদের লগে আগুন বাইর হইলো! পুরাই সুপারপাওয়ার, তয় পাছা পুইড়া কয়লা!',
        tone: 'funny',
        effects: { health: -20, happiness: 10, fame: 25 },
      },
    ],
  },
  {
    id: 'teen_tuition_fee_treat',
    text: 'আম্মা তোরে মাসের প্রাইভেট মাস্টারের বেতন বাবদ ২০০০ ট্যাকা দিছে। দোস্তরা কইলো, "চল রয়াল বুফে খায়া উড়াই!"',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'spend_tuition_buffet',
        text: 'মাস্টারের ট্যাকা মাইরা রয়াল বুফেতে গিয়া কুত্তার লাহান গিল!',
        outcomeText: 'খাইতে খাইতে তোর বদহজম! বাথরুমে গিয়া কমোড ভাইঙ্গা ফেললি! মাস্টার আইসা বাপের সামনে তোরে ন্যাংটা করলো!',
        tone: 'bad',
        effects: { happiness: -25, health: -15, karma: -20 },
      },
      {
        id: 'pay_master_honestly',
        text: 'সব লোভ সামলাইয়া মাস্টারের হাতে ট্যাকা তুইলা দে!',
        outcomeText: 'মাস্টার ট্যাকা পাইয়া খুশি হইয়া তোরে কড়া একখান বাঁশ দেওয়া অংক ধরাইলো! তুই সারারাত কাইন্দা বালিশ ভিজাইলি!',
        tone: 'funny',
        effects: { smarts: 10, karma: 10, happiness: -15 },
      },
    ],
  },
  {
    id: 'teen_hsc_practical_frog',
    text: 'ল্যাবে বায়োলজির জ্যান্ত ব্যাঙ কাটতে গিয়া তোর হাতের ব্যাঙ লাফ দিয়া ডাইরেক্ট ম্যাডামের বুকের উপ্রে!',
    minAge: 16,
    maxAge: 17,
    weight: 7,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'catch_flying_frog',
        text: 'সুপারম্যান সাইজা ম্যাডামের গায়ের উপ্রে থিকা ব্যাঙ ধর!',
        outcomeText: 'ব্যাঙ ধরতে গিয়া ম্যাডামের শাড়িতে টান লাইগা ছিঁড়া গেলো! ম্যাডাম তোরে স্যান্ডেল দিয়া পিটাইয়া পুরা ল্যাব ঘুরাইলো!',
        tone: 'bad',
        effects: { smarts: -5, happiness: -25, looks: -10 },
      },
      {
        id: 'laugh_at_teacher',
        text: 'ম্যাডামের চিল্লানি শুইনা খ্যাঁক খ্যাঁক কইরা দাঁত কেল্লায়া হাস!',
        outcomeText: 'ম্যাডাম রাগে তোর প্যান্টের ভিতরে জ্যান্ত ব্যাঙ ঢুকায়া দিলো! তুই পুরা ল্যাবে লাফাইলি, ইজ্জত জিরো!',
        tone: 'funny',
        effects: { happiness: -20, karma: -15 },
      },
    ],
  },
  {
    id: 'teen_carrom_club_bet',
    text: 'গলির ক্লাবের ক্যারাম বোর্ডে ২০০ টাকার বাজি! বোর্ডের সব গুটি ছড়াইয়া ছিটাইয়া আছে!',
    minAge: 14,
    maxAge: 17,
    weight: 7,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'trick_shot_pocket',
        text: 'বোর্ডে পাউডার মাইরা এক্কেরে বুলেট স্পিডে স্ট্রাইক কর!',
        outcomeText: 'স্ট্রাইকার উইড়া গিয়া ডাইরেক্ট বড় ভাইয়ের চোখে! তোরে ধইরা বোর্ডের উপ্রে ফালায়া ক্যারাম খেললো পোলাপাইন!',
        tone: 'bad',
        effects: { money: -20, happiness: -20, health: -15 },
      },
      {
        id: 'foul_penalty',
        text: 'হাউকাউ কইরা স্ট্রাইকারডারে গর্তে ফালায়া দে!',
        outcomeText: 'ট্যাকা তো হারলিয়, পোলাপাইন তোরে ধইরা ড্রেনের পচা পানি খাওয়াইলো! তুই পুরাই ফইন্নি!',
        tone: 'bad',
        effects: { money: -50, happiness: -25, looks: -10 },
      },
    ],
  },
  {
    id: 'teen_bunk_cinema_hall',
    text: 'কলেজ ফাঁকি দিয়া দোস্তগো লগে মধুমিতা সিনেমা হলে নতুন বাংলা ছবির ফার্স্ট ডে ফার্স্ট শো দেখতে গেছস!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'whistle_in_hall',
        text: 'নায়কের এন্ট্রিতে সিটের উপ্রে খাড়াইয়া লুঙ্গি তুইলা ড্যান্স দে!',
        outcomeText: 'তোর ড্যান্স দেইখা পিছনের পাবলিক তোর পাছায় পচা ডিম মারলো! গন্ধ নিয়া হল থিকা বাইর হইলি!',
        tone: 'bad',
        effects: { happiness: -15, looks: -20 },
      },
      {
        id: 'bump_into_uncle',
        text: 'ইন্টারভালে বাথরুমে বিড়ি খাইতে গিয়া মেজো চাচার সামনে পড়!',
        outcomeText: 'চাচা তোর জ্বলন্ত বিড়ি ধইরা তোর নিজের প্যান্টের ভিতরে ঢুকায়া দিলো! পুইড়া একাকার, আর বাসায় গিয়া ডাবল মাইর!',
        tone: 'bad',
        effects: { health: -15, happiness: -30, karma: -15 },
      },
    ],
  },
  {
    id: 'teen_dhakaiya_wedding_gate_toll',
    text: 'খালাতো বোনের বিয়াতে গেট ধইরা বরযাত্রী আটকাইলি: "এক লাখ ট্যাকা ছাড়া হালায় গেট খুলুম না!"',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'bargain_hard_gate',
        text: 'ফিতা টাইন্যা ধইরা উরাধুরা বার্গেনিং কর!',
        outcomeText: 'বরের ভাইরা তোরে ধইরা এমুন একখান লাথি মারলো, তুই গিয়া ডাইরেক্ট ডাস্টবিনে পড়লি! ট্যাকা জিরো, গন্ধ ১০০!',
        tone: 'bad',
        effects: { money: 0, happiness: -20, looks: -15 },
      },
      {
        id: 'shove_gate_break',
        text: 'বরের ভাইগো লগে ডাইরেক্ট রেসলিং শুরু কইরা দে!',
        outcomeText: 'তোর প্যান্ট ধইরা টাইন্না খুইলা ফালালো! ন্যাংটা হইয়া বিয়া বাড়িতে দৌড়, তোর ছবি এহন ফেসবুকে ভাইরাল!',
        tone: 'funny',
        effects: { happiness: -30, fame: 30, looks: -25 },
      },
    ],
  },
  {
    id: 'teen_bakarkhani_morning_line',
    text: 'শীতের সকালে আনন্দ বেকারিতে মচমচা বাকরখানি আনতে গিয়া দেখস বিশাল লম্বা লাইন!',
    minAge: 13,
    maxAge: 16,
    weight: 6,
    tone: 'neutral',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'line_patience',
        text: 'ভদ্র পোলার লাহান লাইনে খাড়ায়া বাকরখানি ল!',
        outcomeText: 'তোর সামনে আইসা বাকরখানি শেষ! তুই হালায় খালি প্যাকেট চাটতে চাটতে বাড়ি গেলি, আম্মার গাইল ফ্রি!',
        tone: 'bad',
        effects: { happiness: -10, karma: 5 },
      },
      {
        id: 'cut_line_sneaky',
        text: 'চিপা দিয়া ঘুইসা মুরব্বিগো ধাক্কা মাইরা সামনে যা!',
        outcomeText: 'মুরব্বিরা তোরে ধইরা গরম চুলার উপ্রে বসায়া দিলো! পাছা পুইড়া লাল, আর বাকরখানিও জুটলো না!',
        tone: 'bad',
        effects: { karma: -15, happiness: -25, health: -10 },
      },
    ],
  },
  {
    id: 'teen_gym_deshi_akada',
    text: 'বডিতে তাকত বাড়াইতে পাড়ার দেশি আখড়ায় গিয়া লোহার ভারী ডাম্বেল তুলতে লাগলি!',
    minAge: 15,
    maxAge: 17,
    weight: 7,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'pump_iron_consistently',
        text: 'বডি দেখানোর লাইগা ৫০ কেজি ডাম্বেল তুইলা ফাপড় নে!',
        outcomeText: 'ডাম্বেল তুলতে গিয়া তোর প্যান্ট ফাইট্টা হাগু বাইর হইয়া গেলো! পুরা জিমের মানুষ গন্ধ শুইকা বেহুঁশ!',
        tone: 'bad',
        effects: { health: -5, looks: -20, happiness: -25 },
      },
      {
        id: 'drop_dumbbell_foot',
        text: 'আলগা ভাব নিতে গিয়া ডাম্বেল পায়ের উপ্রে ফালা!',
        outcomeText: 'পায়ের আঙ্গুল চ্যাপ্টা হইয়া ভর্তা! এহন পাও বাইন্ধা মহল্লায় লেংড়াইয়া হাঁট, মাইয়ারা দেইখা থুতু মারে!',
        tone: 'bad',
        effects: { health: -20, happiness: -20, looks: -10 },
      },
    ],
  },
  {
    id: 'teen_eid_chand_raat_mehendi',
    text: 'ঈদের চাঁদ দেখা গেছে! চান্দ রাইতে পুরা মহল্লা লাইটিং আর পটকার আওয়াজে কাঁপতাছে!',
    minAge: 13,
    maxAge: 17,
    weight: 9,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'burst_tarabati_rooftop',
        text: 'ছাদে গিয়া উরাধুরা তারাবাতি আর পটকা ফোটাইয়া চান্দি গরম কর!',
        outcomeText: 'পটকা তোর হাতের মইধ্যেই ফুটলো! আঙ্গুল কালা হইয়া গেলো, ঈদের দিন তুই পুরাই পঙ্গু হিরো!',
        tone: 'bad',
        effects: { happiness: -15, health: -10, looks: -5 },
      },
      {
        id: 'stay_up_all_night_adda',
        text: 'সারা রাইত টংয়ে বইসা আড্ডা মার আর বিড়ি টান!',
        outcomeText: 'ফজরের নামাজে খাড়ায়া তুই ঘুমের চোটে ডাইরেক্ট ইমাম সাহেবের গায়ের উপ্রে পড়লি! পুরা মসজিদ থিকা ঘাড়ধাক্কা!',
        tone: 'funny',
        effects: { happiness: -20, karma: -15, fame: -10 },
      },
    ],
  },
  {
    id: 'teen_college_election_slogan',
    text: 'কলেজের ইলেকশনে দুই গ্রুপের পুরাই গ্যাঞ্জাম! এক নেতা তোরে মিছিলে যাইতে ডাকলো!',
    minAge: 16,
    maxAge: 17,
    weight: 7,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'shout_slogan_front',
        text: 'গলা ফাটায়া মিছিলে চিল্লা: "অমুক ভাইয়ের চরিত্র, ফুলের মতো পবিত্র!"',
        outcomeText: 'অপোনেন্ট গ্রুপ আইসা তোরে ধইরা ড্রেনের পানিতে চুবাইলো! পবিত্রতা তোর গু-মুত মাখা শার্টে বাইর হইলো!',
        tone: 'bad',
        effects: { health: -15, happiness: -25, karma: -10 },
      },
      {
        id: 'slip_away_library',
        text: 'গ্যাঞ্জাম দেইখা লাইব্রেরিতে গিয়া চিপায় লুকা!',
        outcomeText: 'লাইব্রেরিতে গিয়া দেখস প্রিন্সিপাল ঘুমানোর ট্রাই করতাছে! তোরে দেইখা ভাবলো চোর, ধইরা পুলিশে দিলো!',
        tone: 'funny',
        effects: { smarts: -10, happiness: -20 },
      },
    ],
  },
  {
    id: 'teen_cricket_tournament_sponsor',
    text: 'মহল্লার নাইট ক্রিকেট টুর্নামেন্টের জন্য তোরে চাঁদা তোলার কঠিন ডিউটি দেওয়া হইলো!',
    minAge: 14,
    maxAge: 17,
    weight: 7,
    tone: 'neutral',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'collect_from_local_businessman',
        text: 'বিরিয়ানি চাচার কাছে গিয়া তেল মাইরা ট্যাকা খসা!',
        outcomeText: 'চাচা ট্যাকা তো দিলোই না, উল্টা তোরে দিয়া দোকানের এঁঠো প্লেট ধোয়াইলো পুরা ২ ঘন্টা! তুই পুরাই ফইন্নি ডিশওয়াশার!',
        tone: 'bad',
        effects: { money: 0, smarts: -5, happiness: -20 },
      },
      {
        id: 'pocket_some_cash',
        text: 'চাঁদার ট্যাকা থিকা ৫০০ ট্যাকা নিজের পকেটে মাইরা দে!',
        outcomeText: 'ধরা খাইয়া পোলাপাইন তোরে উলংগ কইরা গাছে বাইন্ধা রাখলো! সারারাত মশা তোর পাছায় কামড়াইয়া লাল কইরা দিছে!',
        tone: 'bad',
        effects: { karma: -30, happiness: -35, looks: -15 },
      },
    ],
  },
  {
    id: 'teen_smoking_corner_scare',
    text: 'বন্ধুদের পাল্লায় পইড়া নির্জন গলির কোনায় জীবনে প্রথম গোল্ডলিফ সিগারেটে টান দিতাছস! হঠাৎ সামনে বড় ভাই!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'throw_cigarette_drain',
        text: 'সিগারেট গিলা ফালায়া কাইশা সালাম দে বড় ভাইরে!',
        outcomeText: 'গরম বিড়ি তুই গিল্যা ফালাইছোস! পেট পুইড়া এমন একখান পাদ দিলি, বড় ভাই গন্ধে বেহুঁশ হইয়া পড়লো!',
        tone: 'funny',
        effects: { health: -15, happiness: 10, looks: -5 },
      },
      {
        id: 'run_like_cheetah',
        text: 'কোনো দিকে না তাকায়া উসাইন বোল্ট সাইজা ভাগ!',
        outcomeText: 'দৌড়াইতে গিয়া ডাইরেক্ট একটা ষাঁড়ের লগে গুঁতা! ষাঁড় তোরে শিং দিয়া গুতায়া ড্রেনে ফালাইলো!',
        tone: 'bad',
        effects: { health: -20, happiness: -25, looks: -10 },
      },
    ],
  },
  {
    id: 'teen_tailor_eid_fit',
    text: 'ঈদের আগের দিন দর্জির দোকান থিকা পাঞ্জাবি আনলি। পইড়া দেখস এইডা পাঞ্জাবি না, এক্কেরে মশারির নেট!',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'wear_tight_panjabi',
        text: 'শ্বাস আটকায়া টাইট পাঞ্জাবি পইড়াই মহল্লায় ভাব নে!',
        outcomeText: 'ভাব নিতে গিয়া এক্কেরে পেটের বোতাম ফাইট্টা তোর ভুঁড়ি বাইর হইয়া গেলো! মাইনষে ভাবলো তুই প্রেগন্যান্ট!',
        tone: 'funny',
        effects: { happiness: -15, looks: -25 },
      },
      {
        id: 'force_tailor_fix',
        text: 'দর্জির কলার ধইরা ক: "হালায় এইডা কী বানাইছোস?"',
        outcomeText: 'দর্জি রেগে তোর পাঞ্জাবির পিছনে এমন এক ফুটা করলো যে তোর লাল আন্ডারওয়ার পুরা মহল্লা দেখলো!',
        tone: 'bad',
        effects: { looks: -30, happiness: -20 },
      },
    ],
  },
  {
    id: 'teen_badminton_foggy_night',
    text: 'কুয়াশাচ্ছন্ন শীতের রাতে গলির রাস্তায় হ্যালোজেন লাইটের নিচে ব্যাডমিন্টন টুর্নামেন্ট! তীব্র স্ম্যাশ ম্যাচ!',
    minAge: 14,
    maxAge: 17,
    weight: 7,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'jump_smash_winner',
        text: 'আসমানে উইড়া উরাধুরা বুলেট স্ম্যাশ মার হালায়!',
        outcomeText: 'স্ম্যাশ মারতে গিয়া তোর প্যান্ট ফাইট্টা গেলো! ঠান্ডার রাইতে তোর পাছায় বাতাস লাইগা তুই পুরাই ফ্রিজ!',
        tone: 'funny',
        effects: { health: -10, happiness: -20, looks: -15 },
      },
      {
        id: 'tangle_net_fall',
        text: 'আলগা ফাপড় নিতে গিয়া নেটের উপ্রে মুখ থুবড়া পড়!',
        outcomeText: 'নেট তো ছিঁড়লিয়, তুই মাটির উপ্রে পইড়া তোর সামনের দুই দাঁত ভাইঙ্গা ফোকলা হইয়া গেলি! এহন হাসলে বাঁশি বাজে!',
        tone: 'bad',
        effects: { health: -20, money: -30, happiness: -25 },
      },
    ],
  },
  {
    id: 'teen_street_fight_bhai',
    text: 'পাশের পাড়ার ছেলেদের লগে মাঠ দখল নিয়া চরম বচসা! হাতাহাতির উপক্রম!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'fight_with_stick',
        text: 'হাতে স্টাম্প নিয়া অপোনেন্টের চান্দি ফাটাইতে দৌড় দে!',
        outcomeText: 'অপোনেন্টের এক থাপ্পরে তোর স্টাম্প তোরই পিছন দিয়া ঢুকায়া দেওয়ার দশা! তুই কাইন্দা বাপের নাম ভুইলা গেলি!',
        tone: 'bad',
        effects: { health: -30, happiness: -35, karma: -20 },
      },
      {
        id: 'call_area_senior_elder',
        text: 'ডরে মুইতা দিয়া মহল্লার মুরব্বিরে ডাইকা আন!',
        outcomeText: 'মুরব্বি আইসা উল্টা তোরেই কানের নিচে দিলো গ্যাঞ্জাম করার লাইগা! তুই পুরাই বলির পাঁঠা!',
        tone: 'bad',
        effects: { smarts: -10, karma: -10, happiness: -20 },
      },
    ],
  },
  {
    id: 'teen_love_letter_interception',
    text: 'ক্রাশকে লেখা রোমান্টিক প্রেমপত্র খাতার ভিতর থিকা পইড়া গিয়া সোজা হেডমাস্টারের হাতে!',
    minAge: 14,
    maxAge: 16,
    weight: 7,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'claim_poetry_assignment',
        text: 'চাপাবাজি কইরা ক: "স্যার, এইডা তো কাজী নজরুলের আনরিলিজড কবিতা!"',
        outcomeText: 'স্যার তোর চাপাবাজি ধইরা তোর মুখে কালি মাইখা পুরা স্কুল ঘুরাইলো! তুই এহন "কালা মকসদ"!',
        tone: 'bad',
        effects: { smarts: -15, happiness: -30, looks: -20 },
      },
      {
        id: 'get_parents_called',
        text: 'প্যান্টে হাগু কইরা দিয়া স্যারের পাও ধইরা কান্দ!',
        outcomeText: 'তোর হাগুর গন্ধে স্যার তোরে স্কুল থিকাই টিসি (TC) দিয়া বাইর কইরা দিলো! বাপে তোরে রিকশা কিনা দিছে!',
        tone: 'bad',
        effects: { happiness: -40, smarts: -20, fame: -15 },
      },
    ],
  },
  {
    id: 'teen_chawk_bazar_eid_shopping',
    text: 'চকবাজার আর ইসলামপুরের পাইকারি কাপড়ের বাজারে আম্মার লগে ভারী শপিং ব্যাগ নিয়া হাঁটা!',
    minAge: 13,
    maxAge: 17,
    weight: 6,
    tone: 'neutral',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'carry_all_bags_dutiful',
        text: 'কুলি সাইজা সব বস্তা কান্ধে নিয়া আম্মার পিছে পিছে হাঁট!',
        outcomeText: 'ভার সইতে না পাইরা তুই ডাইরেক্ট কাদার মইধ্যে উপুড় হইয়া পড়লি! সব জামাকাপড় কাদা, আম্মার উরাধুরা মাইর খাইলি!',
        tone: 'bad',
        effects: { karma: -5, happiness: -20, health: -10 },
      },
      {
        id: 'whine_and_drop_bag',
        text: 'রাস্তায় ঘ্যানঘ্যান কইরা বস্তা ফালায়া দিয়া বইসা পড়!',
        outcomeText: 'আম্মা তোরে ফালায়া থুইয়া চইলা গেলো! তুই চকবাজারে হারায়া গিয়া সারা রাইত কান্দলি, পরে পুলিশ তোরে উদ্ধার করলো!',
        tone: 'bad',
        effects: { happiness: -30, karma: -15 },
      },
    ],
  },
  {
    id: 'game_football_rage',
    text: 'রাইত জাইগা ফোনে 4-2-4 ফরমেশনে উরাধুরা এটাক দিয়া ফুটবল খেলতাছোস। হঠাত দেখস রাইট উইঙ্গার ফাঁকা পোস্টে গোল মিস মারছে! জিন্দেগি পুরাই তেজপাতা!',
    minAge: 13,
    maxAge: 25,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'phone_throw_rage',
        text: 'চান্দি গরম কইরা আইফোন আছাড় মাইরা ভাইঙ্গা ফ্যাল!',
        outcomeText: 'ফোন তো ভাঙলিয়, বাপে দেইখা তোরে ধইরা ফ্যানের লগে ঝুলাইয়া সারারাত পিটাইলো! জিন্দেগি পুরাই ফালুদা!',
        tone: 'bad',
        effects: { money: -150, smarts: -15, happiness: -30 },
      },
      {
        id: 'cool_substitute_mastermind',
        text: 'ব্রেন খাটাইয়া উইঙ্গার চেঞ্জ কইরা পেপ গার্দিওলা সাজ!',
        outcomeText: 'নতুন প্লেয়ার নাইম্মা নিজের গোলেই বল ঢুকায়া দিলো! তুই রাগে নিজের চুল নিজে ছিঁড়া টাকলু হইয়া গেলি!',
        tone: 'funny',
        effects: { smarts: -10, happiness: -20, looks: -15 },
      },
    ],
  },
  {
    id: 'teen_first_crush',
    text: 'স্কুল ছুটির পর গেটের সামনে খাড়াইয়া আছোস ক্রাশরে এক নজর দেখবি বইলা। হঠাত দেখস ক্রাশের বড় ভাই, মানে লালবাগের ত্রাস "কালা মকসদ" বাইক নিয়া খাড়াইয়া আছে!',
    minAge: 13,
    maxAge: 17,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'crush_salam_bhai',
        text: 'বুক ফুলাইয়া গিয়া ক: "মামা, তোমার বইনরে আমি বিয়া করুম!"',
        outcomeText: 'কালা মকসদ তোর প্যান্ট খুইলা তোরে বাইকের পিছনে বাইন্ধা পুরা লালবাগ ঘুরাইলো! তোর ইজ্জত আর পাছা দুইটাই শেষ!',
        tone: 'bad',
        effects: { health: -20, happiness: -40, looks: -30 },
      },
      {
        id: 'crush_usain_bolt_run',
        text: 'উসাইন বোল্ট সাইজা ক্রাশের সামনে দিয়া দৌড় দে!',
        outcomeText: 'দৌড়াইতে গিয়া কলার খোসায় পা পিছলাইয়া সোজা ড্রেনে! ক্রাশ তোর এই অবস্থা দেইখা থুতু দিয়া চইলা গেলো!',
        tone: 'bad',
        effects: { happiness: -25, looks: -20 },
      },
      {
        id: 'crush_swagger_walk',
        text: 'আলগা ভাব নিয়া শাহরুখ খান সাইজা হাইটা যা!',
        outcomeText: 'শাহরুখ খান সাজতে গিয়া হোঁচট খাইয়া কালা মকসদের বাইকের উপ্রে পড়লি! বাইক ভাইঙ্গা তোর বাপের লাখ ট্যাকা জরিমানা!',
        tone: 'bad',
        effects: { money: -100, health: -15, happiness: -30 },
      },
    ],
  },
  {
    id: 'teen_eid_salami',
    text: 'ঈদের সকালে নতুন আতর মাইখা ঈদগাহে নামাজ পইড়া আসলা। পাড়ার মুরুব্বিদের কদমবুসি করতেই পকেটে কচকচা সালামির নোট আসতে লাগলো!',
    minAge: 13,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    requiredFlags: ['religion_muslim'],
    tags: ['islam'],
    choices: [
      {
        id: 'collect_all_salami',
        text: 'নবাব সাইজা সব চাচার পকেট হাতাইয়া সালামি উশুল কর!',
        outcomeText: 'এক কঞ্জুস চাচা তোর পকেটের ট্যাকা উল্টা মাইরা দিলো! তুই সালামি চাইতে গিয়া পুরাই ফকির হইয়া বাড়ি ফিরলি!',
        tone: 'bad',
        effects: { money: -100, happiness: -20 },
      },
      {
        id: 'treat_friends',
        text: 'সালামির ট্যাকা দিয়া পোলাপাইনরে কাচ্চি ভাইতে নিয়া যা!',
        outcomeText: 'খাইতে গিয়া বিল আইলো তোর ট্যাকার ডাবল! বিল দিতে না পাইরা তুই আর তোর দোস্তরা হোটেলে থালা-বাসন ধুইলি রাইত ১২টা পর্যন্ত!',
        tone: 'funny',
        effects: { happiness: -25, fame: -15, money: -200 },
      },
    ],
  },
  {
    id: 'teen_janmashtami_procession',
    text: 'পুরান ঢাকার ঐতিহাসিক জন্মাষ্টমীর বিশাল শোভাযাত্রা! শ্রীকৃষ্ণ সাজা পোলাপাইন, রঙিন ব্যানার আর ঢাকের বাদ্যে রাস্তা মুখরিত!',
    minAge: 13,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    requiredFlags: ['religion_hindu'],
    tags: ['hinduism'],
    choices: [
      {
        id: 'join_flute_band',
        text: 'ঢাকের তালে উরাধুরা নাগিন ড্যান্স শুরু কইরা দে!',
        outcomeText: 'তোর নাগিন ড্যান্স দেইখা একটা আসল সাপ বাইর হইয়া তোরে ধাওয়া করলো! তুই মুততে মুততে দৌড়াইলি পুরা শাঁখারীবাজার!',
        tone: 'funny',
        effects: { happiness: -15, fame: 20, health: -10 },
      },
      {
        id: 'distribute_sweets',
        text: 'সবার মইধ্যে বাতাসা আর জিলাপি কাড়াকাড়ি কইরা গিল!',
        outcomeText: 'খাইতে গিয়া জিলাপি গলায় আটকায়া তোর চোখ বাইর হইয়া গেলো! মাইনষে তোরে উল্টা কইরা ঝুলাইয়া পিঠ চাপড়াইয়া জান বাঁচাইলো!',
        tone: 'bad',
        effects: { happiness: -20, health: -15 },
      },
    ],
  },
];