import type { LifeEventDef } from '@/lib/engine/types';

export const TEEN_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'teen_ssc_admit_lost',
    text: 'এসএসসি পরীক্ষার আর দুই দিন বাকি, হঠাৎ দেখলি টেবিলের ড্রয়ারে তোর এডমিট কার্ড নাই! কলিজার পানি শুকায়া কাঠ!',
    minAge: 15,
    maxAge: 17,
    weight: 9,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'search_dustbin',
        text: 'পুরা ঘর তছনছ কইরা পুরোনো খাতার স্তূপ ঘেঁটে বের কর',
        outcomeText: 'ফিজিক্স বইয়ের চিপায় এডমিট কার্ড উদ্ধার! শুকরিয়া আদায় কইরা হাঁফ ছাড়লি।',
        tone: 'good',
        effects: { happiness: 15, smarts: 5 },
      },
      {
        id: 'confess_father',
        text: 'কাঁদতে কাঁদতে আব্বারে গিয়া সত্যি কথা ক',
        outcomeText: 'আব্বার বকা খাইয়া স্কুলে দৌড়ায়া ডুপ্লিকেট এডমিট আনলি। চান্দি পুরাই গরম!',
        tone: 'neutral',
        effects: { happiness: -8, health: -4 },
      },
    ],
  },
  {
    id: 'teen_coaching_crush',
    text: 'উদ্ভাসের কোচিং ক্লাসে সামনের বেঞ্চের এক মায়ার দিকে চোখ আটকে গেল। সেও ঘাড় ঘুরায়া এক নজর তাকাইলো!',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'pass_tissue_note',
        text: 'টিস্যু পেপারে সুন্দর কইরা ঢাকাইয়া একখান মিষ্টি শায়েরি লেইখা পাঠা',
        outcomeText: 'সে নোট পইড়া মুচকি হাসলো! কোচিংয়ের পর চকলেট খাওয়াইয়া ভাব জমাইলি!',
        tone: 'good',
        effects: { happiness: 18, looks: 8 },
      },
      {
        id: 'hesitate_look_down',
        text: 'লজ্জা পাইয়া খাতার দিকে তাকায়া অঙ্কের হিজিবিজি কাট',
        outcomeText: 'মায়ায় ভাবলো তুই অহংকারী! চান্স মিস কইরা আফসোস করলি।',
        tone: 'neutral',
        effects: { happiness: -5, smarts: 5 },
      },
    ],
  },
  {
    id: 'teen_bike_borrow_flex',
    text: 'বড় ভাইয়ের ইয়ামাহা এফজেড হোন্ডা ধার নিয়া গলির মোড়ে এক চক্কর মারলি। হঠাৎ ব্রেক স্লিপ কইরা চায়ের দোকানে গুঁতা!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'pay_tea_stall',
        text: 'চায়ের দোকানদারের ২০টা ভাঙা কাপের দাম পকেট থিকা পরিশোধ কর',
        outcomeText: 'ট্যাকা সব ফুড়ুৎ! বড় ভাই হোন্ডার স্ক্র্যাচ দেইখা কানের নিচে একখান চড় বসাইলো।',
        tone: 'bad',
        effects: { money: -50, health: -6, happiness: -12 },
      },
      {
        id: 'accelerate_run',
        text: 'হোন্ডা স্টার্ট দিয়া ঝড়ের বেগে পাড়ায় চম্পট দে',
        outcomeText: 'চায়ের মামা বাপের কাছে নালিশ পাঠাইলো। রাতে ঘরে ভাত বন্ধ!',
        tone: 'bad',
        effects: { karma: -15, happiness: -10 },
      },
    ],
  },
  {
    id: 'teen_first_mustache_shave',
    text: 'নাকে হালকা গোঁফের রেখা উঠতেই আব্বার রেজার দিয়া একা একা কামাইতে গিয়া কাইটা রক্তপাত!',
    minAge: 14,
    maxAge: 16,
    weight: 6,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'alum_stone',
        text: 'ফিটকিরি ঘইষা ক্ষত স্থানে লাগা',
        outcomeText: 'আরেব্বাস! তীব্র জ্বালায় চোখ দিয়া পানি বাইর হইলো, কিন্তু রক্ত বন্ধ!',
        tone: 'funny',
        effects: { health: -4, smarts: 6 },
      },
      {
        id: 'stick_toilet_paper',
        text: 'টিস্যু পেপারের টুকরা আঠা দিয়া মুখে লাগায়া স্কুলে যা',
        outcomeText: 'স্কুলে বন্ধুরা তোরে "কাটা নবাব" উপাধি দিলো। পুরা ক্লাসে হাসির রোল!',
        tone: 'bad',
        effects: { looks: -8, happiness: -8 },
      },
    ],
  },
  {
    id: 'teen_bunk_biryani',
    text: 'বন্ধুরা কয়: "আজকে ফিজিক্স কোচিং ফাঁকি দিয়া নাজিরাবাজারের নান্নার বিরিয়ানি খাইতে যামু, চল!"',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'join_biryani_bunk',
        text: 'বইয়ের ব্যাগ কাঁধে নিয়া সোজা নাজিরাবাজারের মোড়ে রওনা দে',
        outcomeText: 'রগ চাবায়া আর মোরগ পোলাও খাইয়া স্বর্গসুখ পেলি! কিন্তু টিচার আব্বারে ফোন দিয়া দিছে!',
        tone: 'funny',
        effects: { happiness: 20, health: 5, karma: -8 },
      },
      {
        id: 'stay_in_class',
        text: 'ভালো ছাত্রের লাহান কোচিংয়ে বইসা নোট লেখ',
        outcomeText: 'স্যার কঠিন টেস্ট নিলো, তুই একাই ফুল মার্কস পেলি।',
        tone: 'good',
        effects: { smarts: 14, happiness: 5 },
      },
    ],
  },
  {
    id: 'teen_football_tournament',
    text: 'লালবাগ বনাম আরমানিটোলা আন্তঃমহল্লা ফুটবল টুর্নামেন্টের ফাইনাল! তুই নামছস লেফট উইঙ্গার হিসেবে!',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'banana_kick_goal',
        text: 'বক্সের বাইরে থিকা বাঁকা বানানা কিকে টপ কর্নারে বল পাঠা!',
        outcomeText: 'অবিশ্বাস্য গোল! পুরা মাঠ তোর নামে স্লোগান দিলো! ট্রফি নিয়া বাড়ি ফিরলি!',
        tone: 'good',
        effects: { happiness: 25, looks: 10, health: 8 },
      },
      {
        id: 'pass_to_striker',
        text: 'স্বার্থপর না হইয়া স্ট্রাইকার দোস্তরে নিখুঁত পাস বাড়া',
        outcomeText: 'দোস্ত গোল করলো, দুই বন্ধু মিলে বিজয়ের আনন্দ উদযাপন করলি!',
        tone: 'good',
        effects: { happiness: 18, karma: 10 },
      },
    ],
  },
  {
    id: 'teen_night_gaming_parlor',
    text: 'রাতে সবাই ঘুমাইলে চুপিচুপি জানলা দিয়া বাইর হইয়া গলির মোড়ের গেমিং পার্লারে ফিফা খেলতে গেলি!',
    minAge: 15,
    maxAge: 17,
    weight: 7,
    tone: 'neutral',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'win_fifa_pot',
        text: 'টানা ৫ ম্যাচ জিইতা ৫০০ টাকার টুর্নামেন্ট প্রাইজ পকেটে ভর!',
        outcomeText: 'টাকা জিতলি কিন্তু সকালে চোখ লাল দেইখা আম্মা কান মইলে দিল!',
        tone: 'funny',
        effects: { money: 50, happiness: 12, health: -6 },
      },
      {
        id: 'lose_all_money',
        text: 'টানা হাইরা পকেটের সব টিফিনের টাকা খোয়া দে',
        outcomeText: 'পকেট পুরাই গড়ের মাঠ! ভোরে চোরের মতো ঘরে ঢুইকা শুইলি।',
        tone: 'bad',
        effects: { money: -50, happiness: -15 },
      },
    ],
  },
  {
    id: 'teen_sakrain_festival',
    text: 'শাকরাইন উৎসব! ছাদ থিকা ফায়ারব্রেথিং আর গান বাজনা চলতাছে। বন্ধু একখান ফানুস জ্বালাইতে দিল!',
    minAge: 14,
    maxAge: 17,
    weight: 9,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'release_lantern_wish',
        text: 'মনে মনে সুন্দরী বউ আর অঢেল টাকার দোয়া কইরা ফানুস আকাশে ওড়া',
        outcomeText: 'ফানুসটা তারার লাহান মিটিমিটি কইরা উড়লো। মনটা আনন্দে ভইরা গেল!',
        tone: 'good',
        effects: { happiness: 18, looks: 5 },
      },
      {
        id: 'fire_spinning_charka',
        text: 'আতশবাজির চরকি ঘুরাইয়া উল্লাস কর',
        outcomeText: 'হাতের তালুতে একটু আগুন ছ্যাঁকা লাগলো, লেকিন আমেজ পুরাই জোস!',
        tone: 'funny',
        effects: { happiness: 14, health: -4 },
      },
    ],
  },
  {
    id: 'teen_roof_eye_contact',
    text: 'বিকেলে ছাদের রেলিঙে দাঁড়ায়া পাশের বাসার ছাদের এক মায়ারের লগে চোখাচোখি! সেও ওড়না সামলায়া একপলক তাকাইলো!',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'smile_wave_roof',
        text: 'মুচকি হাইসা আলতো কইরা হাত নাড়া',
        outcomeText: 'সেও লজ্জা পাইয়া হাসলো আর ওড়নার কোনা দাঁতে কাটলো! বুকের ভিতর তোলপাড়!',
        tone: 'good',
        effects: { happiness: 20, looks: 8 },
      },
      {
        id: 'whistle_loudly',
        text: 'ছাদে দাঁড়াইয়া ঢাকাইয়া কায়দায় শিষ মার',
        outcomeText: 'তার বাপ ছাদ থিকা বাইর হইয়া একখান কড়া চোখ দিল! এক লাফে সিঁড়িতে ভাগলি!',
        tone: 'bad',
        effects: { happiness: -8, looks: -4 },
      },
    ],
  },
  {
    id: 'teen_sakrain_fire_eating',
    text: 'শাকরাইনে বড় ভাইরা কেরোসিন মুখে নিয়া মশাল জ্বালায়া আগুন ওড়াইতেছে! তোরেও একখান ট্রাই দিতে ডাকলো!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'spit_fire_pro',
        text: 'বুকের পাটা শক্ত কইরা কুয়াশার মতো কেরোসিন ফু দিয়া আকাশে আগুন ছড়াও!',
        outcomeText: 'বিশাল আগুনের গোল্লা! পুরা ছাদ বাহবা দিলো, তুই শাকরাইনের নায়ক!',
        tone: 'good',
        effects: { happiness: 22, looks: 12, smarts: 6 },
      },
      {
        id: 'choke_kerosene',
        text: 'কেরোসিন গিল্যা ফেলে কাশতে কাশতে হালত খারাপ কর',
        outcomeText: 'গলা জ্বইলা কয়লা! ডাক্তার ডাকাইয়া গ্যাস্ট্রিকের ওষুধ খাওয়াইতে হইলো!',
        tone: 'bad',
        effects: { health: -15, happiness: -12 },
      },
    ],
  },
  {
    id: 'teen_tuition_fee_treat',
    text: 'আম্মা তোরে মাসের প্রাইভেট মাস্টারের বেতন বাবদ ২০০০ টাকা দিছে। দোস্তরা কইলো, "চল আজকে রয়াল বুফে উড়াই!"',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'spend_tuition_buffet',
        text: 'সব টাকা ফালুদা আর কাচ্চিতে উড়াইয়া দে',
        outcomeText: 'পেট ভইরা খাইতে পুরাই মাখন! কিন্তু মাস শেষে মাস্টার বাসায় আইসা আব্বার কাছে বেতন চাইলো! চামড়া লাল!',
        tone: 'bad',
        effects: { happiness: 15, health: -10, karma: -15 },
      },
      {
        id: 'pay_master_honestly',
        text: 'লোভ সামলায়া মাস্টারের হাতে টাকা তুইল্যা দে',
        outcomeText: 'মাস্টার খুশি হইয়া স্পেশাল সাজেশন দিলো, পরীক্ষায় কমন পাইলি!',
        tone: 'good',
        effects: { smarts: 14, karma: 12, happiness: 10 },
      },
    ],
  },
  {
    id: 'teen_hsc_practical_frog',
    text: 'কলেজের বায়োলজি ল্যাব ক্লাসে জ্যান্ত ব্যাঙ ডিসেকশন করতে গিয়া তোর হাতের ব্যাঙ লাফ দিয়া ম্যাডামের গায়ে!',
    minAge: 16,
    maxAge: 17,
    weight: 7,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'catch_flying_frog',
        text: 'সুপারম্যানের মতো শূন্যে লাফ দিয়া ব্যাঙ ধইরা ফেল!',
        outcomeText: 'সবাই হাততালি দিলো! ম্যাডাম ভয় থিকা বাঁচিয়া তোরে ফুল মার্কস দিলো!',
        tone: 'good',
        effects: { smarts: 12, happiness: 16, looks: 6 },
      },
      {
        id: 'laugh_at_teacher',
        text: 'ম্যাডামের চিল্লাইয়া উঠা দেইখা খ্যাঁক খ্যাঁক কইরা হাস',
        outcomeText: 'ল্যাব থিকা বহিষ্কার! এক সপ্তাহের জন্য প্র্যাকটিক্যাল ক্লাস বন্ধ!',
        tone: 'bad',
        effects: { happiness: -12, karma: -10 },
      },
    ],
  },
  {
    id: 'teen_carrom_club_bet',
    text: 'গলির ক্লাবের ক্যারাম বোর্ডে ২০০ টাকার বাজি ধরা ম্যাচ! বোর্ডের সব গুটি ছড়ানো!',
    minAge: 14,
    maxAge: 17,
    weight: 7,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'trick_shot_pocket',
        text: 'ডাবল রিবাউন্ড দিয়া লাল গুটি পকেটে নাও!',
        outcomeText: 'খাপের খাপ! সবাই স্তব্ধ, প্রতিপক্ষের মুখ চুন! ২০০ টাকা পকেটে ভরলি!',
        tone: 'good',
        effects: { money: 20, happiness: 18, smarts: 8 },
      },
      {
        id: 'foul_penalty',
        text: 'স্ট্রাইকার গর্তে ফেলে জরিমানা গুনে হারো',
        outcomeText: 'পকেটের টাকা ফুড়ুৎ! বন্ধুরা তোরে কানমলা দিয়া বিদায় করলো।',
        tone: 'bad',
        effects: { money: -20, happiness: -10 },
      },
    ],
  },
  {
    id: 'teen_bunk_cinema_hall',
    text: 'কলেজ ফাঁকি দিয়া দোস্তদের লগে মধুমিতা সিনেমা হলে নতুন বাংলা ছবির ফার্স্ট ডে ফার্স্ট শো দেখতে গেছস!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'whistle_in_hall',
        text: 'নায়কের এন্ট্রির লগে লগে সিটের উপর দাঁড়াইয়া শিষ আর তালি বাজা!',
        outcomeText: 'সিনেমা হলের উন্মাদনা পুরাই তুঙ্গে! গরম শিঙাড়া আর চা খাইয়া দিল খুশ!',
        tone: 'good',
        effects: { happiness: 22, looks: 4 },
      },
      {
        id: 'bump_into_uncle',
        text: 'ইন্টারভালে পপকর্ন কিনতে গিয়া মেজো চাচার মুখোমুখি!',
        outcomeText: 'চাচার কড়া থাপ্পড় খাইয়া হল থিকা বের হইলি! আব্বার বিচার বসলো!',
        tone: 'bad',
        effects: { health: -8, happiness: -18, karma: -8 },
      },
    ],
  },
  {
    id: 'teen_dhakaiya_wedding_gate_toll',
    text: 'খালাতো বোনের বিয়েতে কমিউনিটি সেন্টারের গেটে ফিতা টাইন্যা বরযাত্রী আটকাইলি: "এক লাখ ট্যাকা ছাড়া গেট খুলুম না!"',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'bargain_hard_gate',
        text: 'টানটান দরকষাকষি কইরা নগদ ২০ হাজার টাকা উশুল কর!',
        outcomeText: 'বরের বন্ধুরা হেরে টাকা দিতে বাধ্য হইলো! সব কাজিনরা মিল্লা পার্টি করলি!',
        tone: 'good',
        effects: { money: 50, happiness: 25, smarts: 10 },
      },
      {
        id: 'shove_gate_break',
        text: 'বরের বড় ভাইদের ধাক্কায় ফিতা ছিঁড়ে ছিটকে পড়ো',
        outcomeText: 'গেট ভাইঙ্গা বর ঢুকে গেল, এক পয়সাও জুটলো না! পুরা বেইজ্জতি!',
        tone: 'bad',
        effects: { happiness: -12, looks: -5 },
      },
    ],
  },
  {
    id: 'teen_bakarkhani_morning_line',
    text: 'শীতের সকালে আনন্দ বেকারি থেকে মচমচে বাকরখানি আনতে গেছস। দোকানে বিশাল লম্বা লাইন!',
    minAge: 13,
    maxAge: 16,
    weight: 6,
    tone: 'neutral',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'line_patience',
        text: 'চাদর মুড়ি দিয়া লাইনে দাঁড়াইয়া গরম বাকরখানি কেনো',
        outcomeText: 'মুহূর্তেই তাজা বাকরখানির সুবাসে বাড়ি ভরে উঠলো! আম্মা এক বাটি চা দিলো।',
        tone: 'good',
        effects: { happiness: 12, karma: 6 },
      },
      {
        id: 'cut_line_sneaky',
        text: 'চিপা দিয়া লাইনের সামনে ঢুইকা বাকরখানি টান দাও',
        outcomeText: 'পেছনের মুরুব্বিরা গালাগালি দিলো আর তোরে ঘাড় ধইরা পেছনে পাঠাইলো!',
        tone: 'bad',
        effects: { karma: -8, happiness: -8 },
      },
    ],
  },
  {
    id: 'teen_gym_deshi_akada',
    text: 'শরীরে তাকত বাড়াইতে পাড়ার দেশি আখড়ায় গিয়া লোহার ভারী ডাম্বেল তুলতে লাগলি!',
    minAge: 15,
    maxAge: 17,
    weight: 7,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'pump_iron_consistently',
        text: 'ওস্তাদের তদারকিতে নিয়মিত বুক ডন আর ডাম্বেল মারো',
        outcomeText: 'কয়েক মাসেই বাইসেপ ফুললো আর ছাতি চওড়া হইলো! মহল্লার মায়েরা তাকায়!',
        tone: 'good',
        effects: { health: 18, looks: 15, happiness: 16 },
      },
      {
        id: 'drop_dumbbell_foot',
        text: 'ভাব নিতে গিয়া ৫০ কেজির ওজন পায়ের পাতায় ফেলো',
        outcomeText: 'আঙ্গুল ফুলা বেলুন! তিন সপ্তাহ ল্যাংড়াইয়া হাঁটা লাগলো!',
        tone: 'bad',
        effects: { health: -14, happiness: -15 },
      },
    ],
  },
  {
    id: 'teen_eid_chand_raat_mehendi',
    text: 'ঈদের চাঁদ দেখা গেছে! চান্দ রাতে পুরা মহল্লা লাইটিং আর পটকার আওয়াজে কাঁপতাছে!',
    minAge: 13,
    maxAge: 17,
    weight: 9,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'burst_tarabati_rooftop',
        text: 'ছাদে গিয়া কাজিনদের লগে তারাবাতি আর তুবড়ি জ্বালাও',
        outcomeText: 'আলোর রোশনাইয়ে রাতটা রূপকথার মতো কাটলো! ঈদের মহা আনন্দ!',
        tone: 'good',
        effects: { happiness: 24, looks: 6 },
      },
      {
        id: 'stay_up_all_night_adda',
        text: 'গলির মোড়ে বন্ধুদের লগে ফজর পর্যন্ত চা আর আড্ডা দাও',
        outcomeText: 'পরের দিন ঈদের নামাজে ঘুমের চোটে সেজদায় গিয়া কাত হইলি!',
        tone: 'funny',
        effects: { happiness: 14, health: -6 },
      },
    ],
  },
  {
    id: 'teen_college_election_slogan',
    text: 'কলেজের ছাত্র সংসদ নির্বাচনে দুই গ্রুপের টানটান উত্তেজনা! এক নেতা তোরে মিছিলে যাইতে ডাকলো!',
    minAge: 16,
    maxAge: 17,
    weight: 7,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'shout_slogan_front',
        text: 'মাইক হাতে নিয়া জোর গলায় স্লোগান তোল!',
        outcomeText: 'প্রতিপক্ষ গ্রুপ ইট-পাটকেল মারলো! কপালে ঢিল লাইগা হাসপাতাল যাওয়া লাগলো!',
        tone: 'bad',
        effects: { health: -16, happiness: -14, karma: -6 },
      },
      {
        id: 'slip_away_library',
        text: 'রাজনীতি থিকা দূরে থাইকা লাইব্রেরিতে বই পড়তে পালাও',
        outcomeText: 'গ্যাঞ্জাম থিকা বাঁচলি, পড়াশোনায় মনোযোগ বাড়লো!',
        tone: 'good',
        effects: { smarts: 15, health: 4 },
      },
    ],
  },
  {
    id: 'teen_cricket_tournament_sponsor',
    text: 'মহল্লার নাইট ক্রিকেট টুর্নামেন্টের জন্য তোরে চাঁদা তোলার দায়িত্ব দেওয়া হইলো!',
    minAge: 14,
    maxAge: 17,
    weight: 7,
    tone: 'neutral',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'collect_from_local_businessman',
        text: 'নাজিরাবাজারের বিরিয়ানিওয়ালার কাছে গিয়া মিষ্টি মিষ্টি কথা কইয়া স্পন্সর আনো',
        outcomeText: 'বিরিয়ানি চাচা খুশি হইয়া নতুন জার্সি আর ট্রফির জন্য ৫০০০ টাকা দিলো!',
        tone: 'good',
        effects: { money: 30, smarts: 12, happiness: 18 },
      },
      {
        id: 'pocket_some_cash',
        text: 'চাঁদার টাকা থিকা চুপচাপ কিছু নিজের পকেটে রাখো',
        outcomeText: 'হিসাবে গরমিল ধরা পড়লো! ক্লাবের সবাই তোরে বেইমান কইয়া বয়কট করলো!',
        tone: 'bad',
        effects: { karma: -20, happiness: -15, looks: -8 },
      },
    ],
  },
  {
    id: 'teen_smoking_corner_scare',
    text: 'বন্ধুদের পাল্লায় পইড়া নির্জন গলির কোনায় জীবনে প্রথম গোল্ডলিফ সিগারেটে টান দিতাছস! হঠাৎ সামনে বড় ভাই!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'throw_cigarette_drain',
        text: 'মুহূর্তের মধ্যে সিগারেট ড্রেনে ফেলে কাশতে কাশতে সালাম দাও',
        outcomeText: 'বড় ভাই সন্দেহভাজন চোখে তাকায়া কইলো, "মুখ দিয়া ধোঁয়া বাইর হয় ক্যান রে?" কানের নিচে থাপ্পড়!',
        tone: 'bad',
        effects: { health: -8, happiness: -15, looks: -5 },
      },
      {
        id: 'run_like_cheetah',
        text: 'কোনো কথা না শুইনা অন্ধের মতো দৌড়ে পাড়া ছাড়ো',
        outcomeText: 'বড় ভাইয়ের হাত থিকা বাঁচলি, কিন্তু সারা পথ বুকে দম আটকায়া রইলো!',
        tone: 'neutral',
        effects: { health: -4, happiness: -6 },
      },
    ],
  },
  {
    id: 'teen_tailor_eid_fit',
    text: 'ঈদের আগের দিন দর্জির দোকান থিকা পাঞ্জাবি আনলি। ট্রায়াল দিয়া দেখলি এটা পাঞ্জাবি না, এক্কেবারে মশারির নেট!',
    minAge: 14,
    maxAge: 17,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'wear_tight_panjabi',
        text: 'টাইট পাঞ্জাবি পইড়াই বুকে হাওয়া ভইরা ঈদে ঘুরতে বের হও',
        outcomeText: 'বন্ধুরা হাইসা গড়াগড়ি! তোরে "টাইট নবাব" বইলা খেপাইতে লাগলো!',
        tone: 'funny',
        effects: { happiness: 8, looks: -10 },
      },
      {
        id: 'force_tailor_fix',
        text: 'দর্জির দোকানে বইসা রাইত ১২টা পর্যন্ত চিল্লাচিল্লি কইরা অল্টার করাও',
        outcomeText: 'দর্জি মাপ ঠিক কইরা দিলো, ঈদের দিন ফিটফাট নবাব সাজলি!',
        tone: 'good',
        effects: { looks: 12, happiness: 15 },
      },
    ],
  },
  {
    id: 'teen_badminton_foggy_night',
    text: 'কুয়াশাচ্ছন্ন শীতের রাতে গলির রাস্তায় হ্যালোজেন লাইটের নিচে ব্যাডমিন্টন টুর্নামেন্ট! তীব্র স্ম্যাশ ম্যাচ!',
    minAge: 14,
    maxAge: 17,
    weight: 7,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'jump_smash_winner',
        text: 'বাতাসে লাফায়া উঠে বুলেট গতিতে স্ম্যাশ মারো!',
        outcomeText: 'কর্ক সোজা কোর্টের কোণায়! চ্যাম্পিয়ন ট্রফি আর গরমাগরম মালাই চা জুটলো!',
        tone: 'good',
        effects: { health: 12, happiness: 20, looks: 6 },
      },
      {
        id: 'tangle_net_fall',
        text: 'নেটের উপর ঝাপায়া পইড়া পুরো বাঁশ উপড়ে ফেলো',
        outcomeText: 'সবাই হাসলো, খেলার লাইট ভাইঙ্গা জরিমানা গুনতে হইলো!',
        tone: 'bad',
        effects: { health: -6, money: -20, happiness: -10 },
      },
    ],
  },
  {
    id: 'teen_street_fight_bhai',
    text: 'পাশের পাড়ার ছেলেদের লগে মাঠ দখল নিয়া চরম বচসা! হাতাহাতির উপক্রম!',
    minAge: 15,
    maxAge: 17,
    weight: 8,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'fight_with_stick',
        text: 'লাঠি হাতে নিয়া সম্মুখ সমরে ঝাঁপিয়ে পড়ো!',
        outcomeText: 'মাথা ফাটলো, থানা পুলিশের ঝামেলা হইলো! আব্বা থানা থিকা ছাড়ায়া আনলো!',
        tone: 'bad',
        effects: { health: -20, happiness: -22, karma: -18 },
      },
      {
        id: 'call_area_senior_elder',
        text: 'মহল্লার মুরব্বি ডেকে বিষয়টি আপোষে মিটিয়ে নাও',
        outcomeText: 'মুরব্বিরা মাঠের সময় ভাগ কইরা দিলো, শান্তি ফিরলো!',
        tone: 'good',
        effects: { smarts: 14, karma: 12, happiness: 10 },
      },
    ],
  },
  {
    id: 'teen_love_letter_interception',
    text: 'ক্রাশকে লেখা রোমান্টিক প্রেমপত্র খাতার ভিতর থিকা পইড়া গিয়া সোজা হেডমাস্টারের হাতে!',
    minAge: 14,
    maxAge: 16,
    weight: 7,
    tone: 'bad',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'claim_poetry_assignment',
        text: 'মাথা ঠান্ডা রেখে বলো: "স্যার, এটা তো মাইকেল মধুসূদনের অনুকরণে লেখা কবিতা!"',
        outcomeText: 'হেডমাস্টার অবাক হইয়া কড়া চশমার ফাঁকে তাকাইলো আর মুচকি হাসিয়া মাফ করলো!',
        tone: 'good',
        effects: { smarts: 16, happiness: 12 },
      },
      {
        id: 'get_parents_called',
        text: 'ভয়ে কাঁপতে কাঁপতে হাত জোড় করে ক্ষমা চাও',
        outcomeText: 'বাপকে ডেকে অপমান করা হইলো! বাড়ি ফিরে এক মাস পকেট মানি বন্ধ!',
        tone: 'bad',
        effects: { happiness: -20, looks: -6 },
      },
    ],
  },
  {
    id: 'teen_chawk_bazar_eid_shopping',
    text: 'চকবাজার আর ইসলামপুরের পাইকারি কাপড়ের বাজারে আম্মার লগে ভারী শপিং ব্যাগ নিয়া হাঁটা!',
    minAge: 13,
    maxAge: 17,
    weight: 6,
    tone: 'neutral',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'carry_all_bags_dutiful',
        text: 'ভদ্র ছেলের মতো সব ব্যাগ কাঁধে নিয়া আম্মাকে রিকশায় তোলো',
        outcomeText: 'আম্মা খুশি হইয়া তোর জন্য সুন্দর একখান জুতা কিনে দিলো!',
        tone: 'good',
        effects: { karma: 14, happiness: 15, looks: 8 },
      },
      {
        id: 'whine_and_drop_bag',
        text: 'গরমে ঘ্যানঘ্যান করে মাঝপথে বসে পড়ো',
        outcomeText: 'আম্মা মেজাজ হারিয়ে বকা দিলো আর বাসায় ফিরে খাওয়ার পর মিষ্টি দেওয়া বন্ধ করলো!',
        tone: 'bad',
        effects: { happiness: -8, karma: -5 },
      },
    ],
  },
  {
    id: 'game_football_rage',
    text: 'রাইতের বেলা ফুটবল আর ছ্যাঁকা: রাইত জাইগা ফোনে 4-2-4 ফরমেশনে উরাধুরা এটাক দিয়া ফুটবল খেলতাছোস। হঠাত দেখস রাইট উইঙ্গার বল নিয়া জোস কাট-ইন কইরাও ফাঁকা পোস্টে গোল মিস মারছে! জিন্দেগি পুরাই তেজপাতা!',
    minAge: 13,
    maxAge: 25,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'phone_throw_rage',
        text: 'খাইসে রে! চিল্লাইয়া ফোন আছাড় দিমু! এক্কেরে বাপের ট্যাকা ফুড়ুৎ!',
        outcomeText: 'ফোনের ডিসপ্লে ভাইঙ্গা চুরমার! বাপে আইসা কান মলা দিলো আর ফোন বাজেয়াপ্ত করলো!',
        tone: 'bad',
        effects: { money: -20, smarts: -10, happiness: -5 },
      },
      {
        id: 'cool_substitute_mastermind',
        text: 'মাথা ঠান্ডা রাইখা পল্টি নিয়া উইঙ্গার চেঞ্জ করুম, পুরাই মাস্টারমাইন্ড!',
        outcomeText: 'সাবস্টিটিউট নামাইয়া শেষ মিনিটে বাইসাইকেল কিকে গোল! পুরাই কিংবদন্তি ফিলিং!',
        tone: 'good',
        effects: { smarts: 15, happiness: 10 },
      },
    ],
  },
  {
    id: 'teen_first_crush',
    text: 'স্কুলের গেটে ক্রাশ আর মাইঙ্কা চিপা: স্কুল ছুটির পর গেটের সামনে খাড়াইয়া আছোস ক্রাশরে এক নজর দেখবি বইলা। হঠাত দেখস ক্রাশের বড় ভাই, মানে লালবাগের ত্রাস "কালা মকসদ" বাইক নিয়া খাড়াইয়া আছে, চোখে পুরাই লাল বাত্তি!',
    minAge: 13,
    maxAge: 17,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'crush_salam_bhai',
        text: 'বুক ফুলাইয়া সালাম দিমু — "আসসালামু আলাইকুম বড় ভাই, ভাইগ্না কেমন আছে?"',
        outcomeText: 'কালা মকসদ একটু থতমত খাইয়া কয়, "ওয়ালাইকুম সালাম, ভাগ এহন থিকা!" জানে বাঁচলি!',
        tone: 'good',
        effects: { smarts: 10, karma: 5 },
      },
      {
        id: 'crush_usain_bolt_run',
        text: 'কোনো কথা নাই, উসাইন বোল্টের লাহান দৌড় দিয়া চিপা গলিতে গায়েব!',
        outcomeText: 'কালা মকসদ বাইকের হর্ন বাজায়ে হাসলো, ক্রাশের সামনে চরম মান-ইজ্জত গেলো!',
        tone: 'bad',
        effects: { happiness: 5, looks: -10 },
      },
      {
        id: 'crush_swagger_walk',
        text: 'ক্রাশের দিকে তাকাইয়া একটা আলগা ভাব নিয়া বাইকের পাশ দিয়া হাইটা যামু!',
        outcomeText: 'আলগা ভাব নিতে গিয়া বাইকের সাইলেন্সার পাইপে ঠ্যাং লাগাইয়া পুড়লি! ব্যান্ডেজ বানাইতে হইলো!',
        tone: 'bad',
        effects: { looks: 10, health: -15 },
      },
    ],
  },
  {
    id: 'teen_eid_salami',
    text: 'ঈদের সকালে নতুন আতর মাইখা ঈদগাহে নামাজ পইড়া আসলা। পাড়ার মুরুব্বিদের কদমবুসি করতেই পকেটে কচকচা সালামির নোট আসতে লাগলো!',
    minAge: 13,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    requiredFlags: ['religion_muslim'],
    tags: ['islam'],
    choices: [
      {
        id: 'collect_all_salami',
        text: 'খান্দানি সালাম ঠুকে সব চাচার কাছ থেইকা সালামি আদায় কর',
        outcomeText: 'পকেট ভইরা গেল কচকচা নোটে! বন্ধুদের নিয়া চকবাজারের মোড়ে মেলা দেখলা!',
        tone: 'good',
        effects: { money: 1200, happiness: 18 },
      },
      {
        id: 'treat_friends',
        text: 'সালামির টাকা দিয়া দোস্তদের কাচ্চি আর বোরহানি খাওয়া',
        outcomeText: 'বন্ধুমহলে তোমার নাম এক্কেবারে রাজা বাদশার লাহান ছড়াইয়া পড়লো!',
        tone: 'good',
        effects: { happiness: 20, fame: 8, karma: 10 },
      },
    ],
  },
  {
    id: 'teen_janmashtami_procession',
    text: 'পুরান ঢাকার ঐতিহাসিক জন্মাষ্টমীর বিশাল শোভাযাত্রা! শ্রীকৃষ্ণ সাজা পোলাপাইন, রঙিন ব্যানার আর ঢাকের বাদ্যে রাস্তা মুখরিত!',
    minAge: 13,
    maxAge: 17,
    weight: 8,
    tone: 'good',
    category: 'teen',
    source: 'fallback',
    requiredFlags: ['religion_hindu'],
    tags: ['hinduism'],
    choices: [
      {
        id: 'join_flute_band',
        text: 'বাঁশি আর ঢাকের দলের লগে সুর মিলায়া নাচ',
        outcomeText: 'তোর তাল আর উৎসাহ দেইখা শাঁখারীবাজারের বয়োজ্যেষ্ঠরা প্রাণভরে আশির্বাদ করলো!',
        tone: 'good',
        effects: { happiness: 18, fame: 6, karma: 8 },
      },
      {
        id: 'distribute_sweets',
        text: 'শোভাযাত্রার ভক্তদের মাঝে তিলের খাজা আর বাতাসা বিলাও',
        outcomeText: 'মহল্লায় তোমার সুনাম বাড়লো, সবাই কইলো—"পোলাটা বড়ই ধর্মপরায়ণ!"',
        tone: 'good',
        effects: { happiness: 15, karma: 12 },
      },
    ],
  },
];

