import type { LifeEventDef } from '@/lib/engine/types';

export const YOUNG_ADULT_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'ya_first_job_interview',
    text: 'মতিঝিলে ইন্টারভিউ! টাকলা বস চশমার ফাঁক দিয়া কয়, "৫ বছর পর নিজেরে কই দেখস, ভাতিজা?"',
    minAge: 18,
    maxAge: 26,
    weight: 9,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'impress_smart_answer',
        text: 'ভাব নিয়া ক: "৫ বছর পর আপনার এই দামি চেয়ারে আমি বসমু, আর আপনি চা বানাইবেন!"',
        outcomeText: 'টাকলা বসের প্রেসার হাই হইয়া অজ্ঞান! কোম্পানির এমডি তোর সাহস দেইখা তোরে ডাইরেক্ট জিএম বানায়া দিলো!',
        tone: 'good',
        effects: { money: 300, happiness: 25, smarts: 15 },
      },
      {
        id: 'humble_dhakaiya_answer',
        text: 'তেল মাইরা ক: "স্যার, ৫ বছর ধইরা আপনার জুতা পালিশ করুম, খালি চাকরিটা দেন!"',
        outcomeText: 'বস খুশি হইয়া চাকরি দিলো ঠিকই, কিন্তু ডেইলি তোর দিয়া বাথরুম পরিষ্কার করায়! জিন্দেগি পুরাই তেজপাতা!',
        tone: 'bad',
        effects: { money: 150, happiness: -15, smarts: -8 },
      },
      {
        id: 'freeze_stutter',
        text: 'ডরে প্যান্টে হালকা মুইতা দিয়া তোতলাইতে থাক!',
        outcomeText: 'প্যান্টের ভিজা দাগ দেইখা পুরা অফিস হাসতে হাসতে কাইত! গার্ড আইসা ঘাড় ধইরা বাইর কইরা দিলো!',
        tone: 'bad',
        effects: { happiness: -25, looks: -15 },
      },
    ],
  },
  {
    id: 'ya_first_salary_treat',
    text: 'পয়লা বেতন পাইছোস! দোস্তরা শকুনের লাহান ঘাইরা ধরছে: "কিরে ফইন্নি, ট্রিট দিবি না?"',
    minAge: 22,
    maxAge: 28,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'kacchi_bhai_treat',
        text: 'বাপের বেটা সাইজা কাচ্চি ভাইতে নিয়া উরাধুরা খাসির লেগপিস খাওয়া!',
        outcomeText: 'ট্রিট দিয়া পকেট গড়ের মাঠ! মাস পুরাটা টংয়ের বাকরখানি আর চা খায়া কাটাইতে হইলো, তয় ইজ্জত বাঁচলো!',
        tone: 'good',
        effects: { money: -200, happiness: 20, karma: 15 },
      },
      {
        id: 'cha_biscuit_stingy',
        text: 'কিপ্টামি কইরা টংয়ের লাল চা আর পুরান বনরুটি ধরাইয়া ভাগায়া দে!',
        outcomeText: 'দোস্তরা তোরে ধইরা ড্রেনের পানিতে চুবানি দিলো! "হালার কিপ্টা" বইলা পুরা মহল্লায় তোর বদনাম!',
        tone: 'bad',
        effects: { money: -10, happiness: -20, karma: -15 },
      },
    ],
  },
  {
    id: 'ya_friend_debt_ghost',
    text: 'জিগার কা টুকরা দোস্ত কাইন্দা কয়, "মামা, আম্মার অপারেশন, ২০ হাজার ট্যাকা দে, কসম দিমু!"',
    minAge: 23,
    maxAge: 29,
    weight: 8,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'give_loan_friend',
        text: 'দিল দরিয়া বানায়া কষ্টের জমানো ট্যাকা ধার দিয়া দে!',
        outcomeText: 'পরের মাসে দেখস হালায় কক্সবাজারে গার্লফ্রেন্ড নিয়া চিল করতাছে, আর তোরে ব্লক মারছে! তুই পুরাই বাঁশ খাইলি!',
        tone: 'bad',
        effects: { money: -250, happiness: -25, karma: 10 },
      },
      {
        id: 'excuse_tight_budget',
        text: 'কাউন্টার ফাপড় দে: "মামা, আমি তো কিডনি বেইচা আইফোন কিনার প্ল্যানে আছি, তুই কিডনি কিনবি?"',
        outcomeText: 'দোস্ত টাসকি খাইয়া ভাইগা গেলো! তোর ট্যাকা সেইফ, ঘিলু এক্কেরে আইনস্টাইনের লাহান কাম করছে!',
        tone: 'good',
        effects: { smarts: 15, karma: -5 },
      },
    ],
  },
  {
    id: 'ya_wedding_dance_center',
    text: 'বিয়া বাড়িতে ডিজে গান বাজতাছে। সবাই ঠেইল্লা তোরে স্টেজে তুইলা দিলো ড্যান্স দেওয়ার লাইগা!',
    minAge: 18,
    maxAge: 29,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'epic_dhakaiya_dance',
        text: 'উরাধুরা বেলি ড্যান্স দিতে গিয়া প্যান্ট ফাইট্টা এক্কেরে লাল আন্ডারওয়ার বাইর কইরা ফ্যাল!',
        outcomeText: 'পুরা সেন্টারের পাবলিক হাসতে হাসতে বেহুঁশ! বিয়ার ভিডিওতে তুই ভাইরাল, তয় ইজ্জতের পুরাই ফালুদা!',
        tone: 'funny',
        effects: { happiness: 10, looks: -20, fame: 20 },
      },
      {
        id: 'eat_biryani_corner',
        text: 'ড্যান্স বাদ দিয়া খাসির রোস্টের ডেকচির উপ্রে কুত্তার লাহান ঝাঁপায়া পড়!',
        outcomeText: 'রোস্ট খাইতে গিয়া ঝোল পুরা জামায় মাখাইলি! বাপের বকা খাইলি, তয় পেট পুরাই ঠান্ডা!',
        tone: 'good',
        effects: { health: 6, happiness: 15, looks: -5 },
      },
    ],
  },
  {
    id: 'ya_buy_secondhand_bike',
    text: 'বাসে ঝুইলা মেজাজ ফায়ার! জমানো ট্যাকায় একখান খচ্চর মার্কা সেকেন্ডহ্যান্ড পালসার কিনলি!',
    minAge: 23,
    maxAge: 29,
    weight: 7,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'modify_exhaust',
        text: 'সাইলেন্সার খুইলা বিকট আওয়াজ কইরা মহল্লায় ফাপড় নে!',
        outcomeText: 'আওয়াজ শুইনা পাড়ার দশটা কুত্তা তোরে ধাওয়া করলো! কুত্তার কামড় খাইয়া হাসপাতালে তুই ১৪টা ইনজেকশন নিলি!',
        tone: 'bad',
        effects: { money: -50, health: -20, looks: -5 },
      },
      {
        id: 'ride_safe_helmet',
        text: 'মুরুব্বিগো লাহান বড় হেলমেট পইড়া আস্তে আস্তে চালা!',
        outcomeText: 'পাড়ার মাইয়ারা দেইখা কয়, "আংকেল যায়!" রোমান্সের লাল বাত্তি, তয় এক্সিডেন্ট থিকা বাঁচলি!',
        tone: 'funny',
        effects: { happiness: -5, smarts: 10 },
      },
    ],
  },
  {
    id: 'ya_startup_dream_foodcart',
    text: 'দোস্ত কয়, "চাকরি ছাইড়া চল নাজিরাবাজারে কাবাবের ফুডকার্ট দিয়া কোটিপতি হই!"',
    minAge: 24,
    maxAge: 29,
    weight: 8,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'invest_savings_cart',
        text: 'জমানো ট্যাকা ঢাইলা "ভাবীর কাবাব" নামে কার্ট খুইলা ফ্যাল!',
        outcomeText: 'কাবাব খায়া কাস্টমারের উরাধুরা পাতলা পায়খানা! পাবলিক আইসা দোকান ভাইঙ্গা তোরে ন্যাংটা কইরা দৌড়ানি দিলো!',
        tone: 'bad',
        effects: { money: -300, happiness: -25, health: -10 },
      },
      {
        id: 'stick_to_job',
        text: 'ফাপড় বাদ দিয়া কর্পোরেট দাসত্ব কর!',
        outcomeText: 'বস ডেইলি তোর ঘাড়ের উপ্রে বইসা জুতা পালিশ করায়, তয় মাস শেষে ঠিকই ট্যাকা পাস। জিন্দেগি বোরিং!',
        tone: 'neutral',
        effects: { money: 100, happiness: -10 },
      },
    ],
  },
  {
    id: 'ya_dating_dhanmondi_lake',
    text: 'ওয়াইফির লগে ধানমন্ডি লেকে চিপায় বইসা রোমান্স! হঠাত দেখস আম্মার কড়া বান্ধবী ডাইরেক্ট তোদের দিকে আইতাছে!',
    minAge: 18,
    maxAge: 27,
    weight: 8,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'jump_behind_bushes',
        text: 'ওয়াইফিরে ধাক্কা দিয়া লেকের পচা পানিতে ফালাইয়া তুই নিজে ঝোপে লুকা!',
        outcomeText: 'ওয়াইফি লেকের কাদা আর গু-মুত মাইখা উইঠা তোরে স্যান্ডেল দিয়া পিটাইলো! ব্রেকআপ এক্কেরে কনফার্ম!',
        tone: 'bad',
        effects: { happiness: -30, looks: -10, karma: -15 },
      },
      {
        id: 'introduce_bravely',
        text: 'আন্টিরে সালাম দিয়া ক: "খালাম্মা, আমার হবু বউরে দোয়া কইরা দেন!"',
        outcomeText: 'আন্টি খুশি হইয়া আম্মারে কইলো। আম্মা আইসা তোর পিঠে ঝাড়ু ভাইঙ্গা বিয়া কনফার্ম কইরা দিলো!',
        tone: 'good',
        effects: { happiness: 20, smarts: 10, health: -5 },
      },
    ],
  },
  {
    id: 'ya_overtime_boss_fight',
    text: 'শুক্রবার দুপুরে কড়া ঘুমের মইধ্যে বস কল দিয়া কয়, "জলদি অফিসে আয়, কাজ আছে!"',
    minAge: 24,
    maxAge: 29,
    weight: 7,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'attend_overtime',
        text: 'তেল মারার লাইগা ঘুম ছাইড়া অফিসে গিয়া গাধার লাহান খাট!',
        outcomeText: 'বস তোর কাজের ক্রেডিট নিজে নিয়া প্রমোশন পাইলো! তুই দুঃখে বাথরুমে গিয়া কাইন্দা চোখ ফুলাইলি!',
        tone: 'bad',
        effects: { money: 50, smarts: -5, happiness: -15 },
      },
      {
        id: 'fake_illness',
        text: 'ভয়ংকর আওয়াজ কইরা ক: "স্যার, ডাইরিয়ায় বাথরুম ভাসায়া দিছি, আসতে পারুম না!"',
        outcomeText: 'বস ঘিন্না খাইয়া ফোন কাইটা দিলো! তুই আরামে ঘুমাইলি, তয় সোমবারে অফিসে তোর নামে হাগু-রসিকতা শুরু হইলো!',
        tone: 'funny',
        effects: { happiness: 15, karma: -5, fame: 5 },
      },
    ],
  },
  {
    id: 'ya_university_tsc_adda',
    text: 'টিএসসির চিপায় পোলাপাইনের উরাধুরা ভিড়। তোর হাতে একখান গিটার!',
    minAge: 18,
    maxAge: 24,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'sing_guitar_adda',
        text: 'কাকডাকা বেসুরা গলায় জেমসের গান ধইরা দে!',
        outcomeText: 'পাবলিক বিরক্ত হইয়া তোর দিকে পচা সমুচা আর থুতু মারলো! তুই পুরাই ডাস্টবিন হইয়া গেলি!',
        tone: 'bad',
        effects: { happiness: -20, looks: -15 },
      },
      {
        id: 'debate_philosophy',
        text: 'বেনসন ধরাইয়া আলগা আতেল সাইজা কার্ল মার্ক্স নিয়া ফাপড় দে!',
        outcomeText: 'ভাব নিতে গিয়া সিগারেটের আগুনে নিজের ঠোঁট পুড়াইয়া ফালালি! মাইয়ারা হাইসা কুটিকুটি!',
        tone: 'funny',
        effects: { smarts: -5, happiness: -10, health: -5 },
      },
    ],
  },
  {
    id: 'ya_bcs_exam_study_hall',
    text: 'বিসিএস পরীক্ষার আর তিন মাস বাকি। নীলক্ষেতের গাইড বইয়ের তলে তুই চ্যাপ্টা!',
    minAge: 22,
    maxAge: 28,
    weight: 8,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'grind_bcs_14_hours',
        text: 'প্রেম-পিরিত ছাইড়া গাধার লাহান ডেইলি ১৪ ঘণ্টা মুখস্থ কর!',
        outcomeText: 'পড়তে পড়তে চান্দির চুল পইড়া টাক হইয়া গেলি! প্রিলি টিকছোস, কিন্তু এহন আর কেউ তর লগে প্রেম করতে চায় না!',
        tone: 'good',
        effects: { smarts: 25, happiness: -10, looks: -15 },
      },
      {
        id: 'procrastinate_reel',
        text: 'বইয়ের চিপায় মোবাইল রাইখা ফেসবুক রিলসে মাইয়াগো ড্যান্স দ্যাখ!',
        outcomeText: 'পরীক্ষায় ডাব্বা মারলি! আব্বা তোরে ধইরা কাওরান বাজারে বাদাম বেচতে পাঠায়া দিলো!',
        tone: 'bad',
        effects: { smarts: -15, happiness: -25, money: -50 },
      },
    ],
  },
  {
    id: 'ya_matchmaker_proposal_ghotok',
    text: 'ঘটক কাসেম আলী পান চাবাইতে চাবাইতে এক বিশাল বড়লোক কিন্তু খচ্চর চেহারার পাত্রী/পাত্রের ছবি বাইর করলো!',
    minAge: 22,
    maxAge: 29,
    weight: 8,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'agree_see_family',
        text: 'ট্যাকার লোভে রাজি হইয়া এক্কেরে ৩২ দাঁত বাইর কইরা হাস!',
        outcomeText: 'বিয়া হইলো ঠিকই, কিন্তু শ্বশুর হালায় তোরে তার পার্সোনাল ড্রাইভার বানায়া রাখছে! ইজ্জত জিরো!',
        tone: 'bad',
        effects: { money: 500, happiness: -30, looks: -10 },
      },
      {
        id: 'reject_outright_career',
        text: 'ভাব নিয়া ক: "আমি নিজের পায়ে খাড়ামু, এই উটপাখি বিয়া করুম না!"',
        outcomeText: 'আম্মা মেজাজ ফায়ার কইরা তোর চান্দিতে উড়ন্ত স্যান্ডেল মারলো! কিন্তু তোর আত্মসম্মান হালায় বাইচা গেলো!',
        tone: 'neutral',
        effects: { smarts: 15, happiness: -5, health: -5 },
      },
    ],
  },
  {
    id: 'ya_office_politics_appraisal',
    text: 'অ্যাপ্রাইজালের টাইম! তুই কাম করলি আর তোর চামচা কলিগ গিয়া বসের কাছে সব ক্রেডিট নিতাছে!',
    minAge: 23,
    maxAge: 29,
    weight: 8,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'present_data_metrics',
        text: 'কলিগের ফাঁকিবাজির সব স্ক্রিনশট আর প্রমাণ বসের মেইলে ফালায়া দে!',
        outcomeText: 'বস টাসকি খাইলো! কলিগরে ঘাড়ধাক্কা দিয়া বাইর করলো, আর তুই পাইলি ডাবল ইনক্রিমেন্ট! পুরাই গ্যাংস্টার মুভ!',
        tone: 'good',
        effects: { money: 200, happiness: 25, smarts: 20 },
      },
      {
        id: 'threaten_to_resign',
        text: 'মেজাজ গরম কইরা কলিগের প্যান্টের উপ্রে গরম কফি ঢাইলা দে!',
        outcomeText: 'কলিগের পাছা পুইড়া কয়লা! তুই ডাইরেক্ট ফায়ার, লগে পুলিশের কেইস! জেলের ভাত খায়া এহন বডি বানা!',
        tone: 'bad',
        effects: { money: -300, happiness: -40, health: -10 },
      },
    ],
  },
  {
    id: 'ya_bachelor_mess_cooking',
    text: 'মেসের বুয়া ভাইগা গেছে! তোর উপ্রে রান্ধনের প্যারা, তুই হালায় জীবনে পানিও গরম করিস নাই!',
    minAge: 18,
    maxAge: 25,
    weight: 7,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'cook_khichuri_experiment',
        text: 'ডাল-চাল আর আলু মিলায়া জগাখিচুড়ি পাকায়া ফ্যাল!',
        outcomeText: 'পোলাপাইন খায়া ডেইলি ১০ বার বাথরুমে দৌড়ানি শুরু করলো! ডাইরিয়ায় মেস পুরাই আইসিইউ (ICU)!',
        tone: 'bad',
        effects: { smarts: -5, happiness: -20, health: -15 },
      },
      {
        id: 'order_food_waste_rent',
        text: 'ভাড়ার ট্যাকা চুরি কইরা সস্তা বিরিয়ানি অর্ডার দে!',
        outcomeText: 'খাইতে গিয়া দেখস বিরিয়ানির তলে আস্ত একখান মরা তেলাপোকা! ব্লিয়ার্গ! তুই বমি কইরা পুরা ঘর ভাসায়া দিলি!',
        tone: 'funny',
        effects: { money: -50, happiness: -15, health: -10 },
      },
    ],
  },
  {
    id: 'ya_dating_boat_buriganga',
    text: 'ওয়াইফিরে নিয়া বুড়িগঙ্গার পচা কালো পানির উপ্রে নৌকায় রোমান্স করতাছোস!',
    minAge: 18,
    maxAge: 28,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'recite_poetry_lover',
        text: 'রোমান্টিক মুডে তারে কিস করতে গিয়া নৌকার ব্যালেন্স হারা!',
        outcomeText: 'ডাইরেক্ট বুড়িগঙ্গার গু-মুত মাখা পানিতে ডাইভ! উইঠা দেখস তুই আর তোর ওয়াইফি দুইটাই পচা এলিয়েন!',
        tone: 'bad',
        effects: { happiness: -30, looks: -25, health: -15 },
      },
      {
        id: 'drop_phone_in_river',
        text: 'দামি আইফোন বাইর কইরা নৌকার কিনারায় বইসা সেলফির ফুটানি মার!',
        outcomeText: 'আইফোন হাত ফসকা সোজা গু-এর পানিতে গায়ব! ওয়াইফি তোরে ছ্যাঁকা দিয়া অন্য পোলার নৌকায় উইঠা গেলো!',
        tone: 'bad',
        effects: { money: -250, happiness: -35, karma: -10 },
      },
    ],
  },
  {
    id: 'ya_traffic_jam_cng_fare',
    text: 'গুলিস্তানের জ্যামে ৩ ঘণ্টা আটকা! সিএনজিয়ালা চাইত্যা কয়, "মামা আরও ১০০ ট্যাকা না দিলে নামেন!"',
    minAge: 21,
    maxAge: 29,
    weight: 7,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'argue_police_help',
        text: 'কলার ধইরা ফাপড় দে: "চিনস আমারে? কাইট্টা ফালামু!"',
        outcomeText: 'সিএনজিয়ালা তার লোকাল গ্যাং ডাইকা তোরে উলংগ কইরা মাইর দিলো! ইজ্জত পুরাই গুলিস্তানের রাস্তায়!',
        tone: 'bad',
        effects: { health: -20, happiness: -30, looks: -15 },
      },
      {
        id: 'walk_in_pollution',
        text: 'সিএনজি থিকা লাফ দিয়া নর্দমার পানি পাড়াইয়া হাঁটা ধর!',
        outcomeText: 'পচা কাদা ছিইটা তোর সাদা শার্ট পুরাই ডাস্টবিন! অফিসে গিয়া বসের কাছে ছাগলের লাহান ঝাড়ি খাইলি!',
        tone: 'bad',
        effects: { health: -10, happiness: -20, looks: -10 },
      },
    ],
  },
  {
    id: 'ya_freelancing_first_dollar',
    text: 'রাইত জাইগা চোখের তলে কালি ফালাইয়া আমেরিকার ক্লায়েন্টের থিকা প্রথম ৫০০ ডলার পাইছোস!',
    minAge: 18,
    maxAge: 28,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'receive_500_dollar',
        text: 'পুরা গুষ্টির কাছে ট্যাকা পাওয়ার ফুটানি মাইরা দে!',
        outcomeText: 'ফুটানি মারার পর সব খালা-ফুফুরা আইসা লোন চাইলো! ট্যাকা ধার দিয়া তুই এহন রাস্তায় ফকির!',
        tone: 'bad',
        effects: { money: -400, happiness: -20, smarts: -10 },
      },
      {
        id: 'buy_expensive_gadget',
        text: 'ট্যাকা পাইয়াই দামী আরজিবি (RGB) কীবোর্ড কিন্না আন!',
        outcomeText: 'প্রথম দিনেই কীবোর্ডের উপ্রে গরম চা ঢাইলা দিছোস! পুরাই শর্টসার্কিট, ট্যাকা এক্কেরে পানিতে!',
        tone: 'funny',
        effects: { money: -150, happiness: -15, smarts: -5 },
      },
    ],
  },
  {
    id: 'ya_crypto_fomo_loss',
    text: 'দোস্ত ফাপড় দিলো: "DogeElonDhakaiya কয়েন কিন, কাইলকাই কোটিপতি!"',
    minAge: 21,
    maxAge: 28,
    weight: 7,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'panic_sell_bottom',
        text: 'লোভে পইড়া সব ট্যাকা ঢাইলা হোল্ড (Hodl) কইরা বইসা থাক!',
        outcomeText: 'কয়েনের দাম জিরো! স্ক্যাম খাইয়া তুই এহন কিডনি বেচার লাইগা ব্ল্যাক মার্কেটে কাস্টমার খুঁজতাছোস!',
        tone: 'bad',
        effects: { money: -500, happiness: -40, health: -10 },
      },
      {
        id: 'learn_hard_lesson',
        text: 'চান্দি গরম কইরা দোস্তের বাসায় গিয়া রামদা নিয়া খাড়া!',
        outcomeText: 'দোস্ত ডরে মুইতা দিয়া তোর ট্যাকা ফেরত দিয়া দিছে! তুই পুরাই মহল্লার মাফিয়া ডন!',
        tone: 'good',
        effects: { money: 100, happiness: 10, karma: -15 },
      },
    ],
  },
  {
    id: 'ya_father_business_shop',
    text: 'নবাবপুরের হার্ডওয়ার দোকানে আব্বা তোরে গদিতে বসায়া কইলো, "আজ থিকা এই দোকান তোর!"',
    minAge: 22,
    maxAge: 29,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'modernize_shop_pos',
        text: 'দোকানে এসি আর ওয়াইফাই লাগায়া সারাদিন গেম খেল আর ঘুমা!',
        outcomeText: 'তোর ঘুমের চান্সে ম্যানেজার সব মাল চুরি কইরা বেচা দিছে! আব্বা আইসা তোরে ঝাড়ু দিয়া পিটাইলো!',
        tone: 'bad',
        effects: { money: -300, happiness: -20, health: -10 },
      },
      {
        id: 'sit_lazily_smoke',
        text: 'আসল মালিক সাইজা ঘাম ঝরায়া কাস্টমারের লগে চিল্লাচিল্লি কইরা মাল বেচ!',
        outcomeText: 'ঘামে গন্ধ ছুটলেও ক্যাশ পুরাই ফুল! আব্বা খুশি হইয়া তোরে বিয়া করাইয়া দেওয়ার ডিসিশন নিলো!',
        tone: 'good',
        effects: { money: 300, happiness: 20, looks: -5 },
      },
    ],
  },
  {
    id: 'ya_wedding_kabin_bargain',
    text: 'বিয়ার বৈঠকে মাইয়া পার্টি কাবিন চাইতাছে নগদ ২০ লাখ ট্যাকা! তোর বাপের তো স্ট্রোক করার দশা!',
    minAge: 23,
    maxAge: 29,
    weight: 8,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'calm_both_sides',
        text: 'গ্যাঞ্জাম থিকা বাঁচতে কাইন্দা ক: "আমি তো আসলে পুরুষই না, আমার বিয়া লাগবো না!"',
        outcomeText: 'পুরা সেন্টারে পিনপতন নীরবতা! বিয়া তো ভাইঙ্গা গেলোই, পুরা মহল্লায় তুই এহন "হিজড়া" নামে ফেমাস!',
        tone: 'funny',
        effects: { happiness: -40, fame: 50, looks: -20 },
      },
      {
        id: 'storm_out_anger',
        text: 'লজ্জায় মাথা নিচা কইরা ২০ লাখে সিগনেচার মাইরা দে!',
        outcomeText: 'বিয়া হইলো, কিন্তু বউ তোরে চাকরের লাহান খাটায়! তুই এহন জ্যান্ত এটিএম (ATM) মেশিন আর বউয়ের দাস!',
        tone: 'bad',
        effects: { money: -500, happiness: -30, smarts: -15 },
      },
    ],
  },
  {
    id: 'ya_overseas_visa_agency',
    text: 'পল্টনের দালাল ফাপড় দিতাছে: "১০ লাখ ঢাললে কানাডার ভিসা এক্কেরে গ্যারান্টি, মামা!"',
    minAge: 22,
    maxAge: 29,
    weight: 8,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'verify_with_embassy',
        text: 'বিনা চিন্তায় বাপের জমি বেইচা দালালের হাতে ট্যাকা তুইলা দে!',
        outcomeText: 'দালাল ট্যাকা নিয়া লাপাত্তা! তুই এহন কানাডার বদলায় গুলিস্তানে কলা বেচতাছোস!',
        tone: 'bad',
        effects: { money: -500, happiness: -40, smarts: -20 },
      },
      {
        id: 'pay_advance_token',
        text: 'দালালের কলার ধইরা পল্টনের রাস্তায় উরাধুরা মাইর দে!',
        outcomeText: 'দালাল মাফ চাইয়া সবার ট্যাকা ফেরত দিলো! পুরা এলাকায় তুই এহন রবিনহুড, সম্মান এক্কেরে আসমানে!',
        tone: 'good',
        effects: { smarts: 20, fame: 30, karma: 25 },
      },
    ],
  },
  {
    id: 'ya_cox_bazar_trip_gang',
    text: 'শীতের রাইতে দোস্তগো লগে হোন্ডা নিয়া টেকনাফ-কক্সবাজার মেরিন ড্রাইভে ট্যুর!',
    minAge: 21,
    maxAge: 27,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'camp_on_beach_stars',
        text: 'হিরো সাইজা শার্ট খুইলা খালি গায়ে রোদে বাইক চালা!',
        outcomeText: 'রোদ আর বাতাসে পুইড়া তোর চামড়া এক্কেরে লাল বান্দরের পাছা! ৩ দিন বিছানা থিকা উঠতে পারস নাই!',
        tone: 'funny',
        effects: { health: -20, looks: -15, happiness: -10 },
      },
      {
        id: 'speed_race_skid',
        text: 'বিচে সস্তা কাঁকড়া ফ্রাই গিল্যা ফ্যাল!',
        outcomeText: 'কাঁকড়া খাইয়া বাসে উইঠা চরম ডাইরিয়া! বাসের ভিতরেই হাগু কইরা দিছোস, দোস্তরা তোরে বাস থিকা লাথি দিয়া ফালায় দিছে!',
        tone: 'bad',
        effects: { health: -25, happiness: -40, fame: -20 },
      },
    ],
  },
  {
    id: 'ya_first_car_reconditioned',
    text: 'ট্যাকা জমাইয়া একখান লক্কড়ঝক্কড় পুরান প্রিমিও (Premio) গাড়ি কিন্না মহল্লায় ভাব নিতাছোস!',
    minAge: 25,
    maxAge: 29,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'drive_family_to_mawa',
        text: 'গার্লফ্রেন্ডরে তুইলা লং ড্রাইভে যা!',
        outcomeText: 'মাঝ রাস্তায় গাড়ির ইঞ্জিন ধোঁয়া ছাইড়া নষ্ট! গার্লফ্রেন্ডরে দিয়া পিছন থিকা গাড়ি ধাক্কাইলি, ব্রেকআপ কনফার্ম!',
        tone: 'funny',
        effects: { happiness: -25, money: -50, karma: -10 },
      },
      {
        id: 'bumper_dent_rickshaw',
        text: 'ফুটানি মারতে গিয়া লেগুনার লগে ঘষা দিয়া দে!',
        outcomeText: 'লেগুনা ড্রাইভার বাইর হইয়া হুইল রেঞ্জ দিয়া তোর গাড়ির গ্লাস ভাইঙ্গা দিলো! ডরে তুই গাড়ির সিটের নিচে লুকাইলি!',
        tone: 'bad',
        effects: { money: -150, happiness: -20, looks: -10 },
      },
    ],
  },
  {
    id: 'ya_mother_emotional_blackmail',
    text: 'আম্মা কান্দন শুরু করছে: "আমি মরার আগে কি তোর ঘরের নাতি-নাতনির মুখ দেইখা যাইতে পারুম না?"',
    minAge: 24,
    maxAge: 29,
    weight: 7,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'hug_mother_promise',
        text: 'মেজাজ খারাপ কইরা ক: "আইজকাই বিয়া করুম, মাইয়া আনো!"',
        outcomeText: 'আম্মা খুশিতে তোর এক খ্যাত আর দাঁত উঁচা কাজিনরে ধইরা আইন্না বিয়া পড়ায়ে দিলো! পুরা লাইফটাই চ্যাপ্টা হইয়া গেলো!',
        tone: 'bad',
        effects: { happiness: -40, looks: -10, karma: 10 },
      },
      {
        id: 'argue_about_independence',
        text: 'ফাপড় দে: "আমি হিমালয়ে গিয়া সন্ন্যাসী হমু, বিয়া করুম না!"',
        outcomeText: 'আম্মা ঝাড়ু নিয়া এমন পিটানি দিলো যে তুই কান্দতে কান্দতে ম্যাট্রিমনিতে একাউন্ট খুলতে বাধ্য হইলি!',
        tone: 'funny',
        effects: { health: -10, happiness: -15, smarts: -5 },
      },
    ],
  },
  {
    id: 'ya_rooftop_bbq_winter',
    text: 'শীতের রাইতে ছাদে বারবিকিউ পার্টি! পাড়ার সব কুত্তা গোশতের গন্ধে ঘেউ ঘেউ করতাছে!',
    minAge: 21,
    maxAge: 29,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'grill_perfect_kabab',
        text: 'ভাব নিয়া মুরগি পুরা পুড়াইয়া কয়লা বানায়া ফ্যাল!',
        outcomeText: 'উপরে কয়লা কিন্তু ভিতরে কাঁচা রক্ত! পোলাপাইন খাইয়া ডাইরেক্ট হাসপাতালে, তোর নামে পুলিশ কেইস দেওয়ার ফাপড় দিতাছে!',
        tone: 'bad',
        effects: { health: -20, happiness: -30, money: -100 },
      },
      {
        id: 'burn_kabab_black',
        text: 'ভুল কইরা মুরগির পিস ছাদের ময়লা ফ্লোরে ফালায়া দে!',
        outcomeText: 'চুপচাপ ফ্লোর থিকা তুইলা ধুইয়া মশলা মাখায়া দোস্তগো খাওয়াইলি! পোলাপাইন কইলো "সেই স্বাদ মামা!" তুই মনে মনে শয়তানের হাসি হাসলি!',
        tone: 'funny',
        effects: { smarts: 20, happiness: 15, karma: -20 },
      },
    ],
  },
  {
    id: 'ya_bank_loan_credit_card',
    text: 'ব্যাংকের এক আপু সুকণ্ঠী গলায় ফোন দিয়া কয়, "স্যার, ৫ লাখের ক্রেডিট কার্ড নিবেন?"',
    minAge: 23,
    maxAge: 29,
    weight: 7,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'politely_decline_card',
        text: 'ফ্লার্ট কইরা ক: "কার্ড লাগবো না আপু, আপনার নাম্বারটা দেন!"',
        outcomeText: 'আপু তোরে ইচ্ছামতো বকা দিয়া কল কাইটা দিলো! ব্যাংক থিকা তোর নাম্বার ব্ল্যাকলিস্টে ফালাইলো, লুচ্চা হালায়!',
        tone: 'funny',
        effects: { happiness: -10, karma: -5, looks: -10 },
      },
      {
        id: 'max_out_card_shopping',
        text: 'কার্ড নিয়া উরাধুরা আইফোন আর জুতা কিন্না ফুটানি মার!',
        outcomeText: 'মাস শেষে বিল দিতে না পাইরা তুই পলাতক! কালেকশন এজেন্ট আইসা তোর বাপের সামনে তোরে বেইজ্জত কইরা গেলো!',
        tone: 'bad',
        effects: { money: -300, happiness: -40, fame: -20 },
      },
    ],
  },
  {
    id: 'ya_dhaka_metro_rush',
    text: 'সকাল ৯টায় ফার্মগেট মেট্রোতে মানুষের ভিড় দেইখা মনে হইতাছে মাছের বাজার! দরজা খুলতেই ধাক্কাধাক্কি!',
    minAge: 21,
    maxAge: 29,
    weight: 7,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'squeeze_into_metro',
        text: 'চিপা দিয়া ঘুইসা এক মোটা আংকেলের বগলের তলে গিয়া খাড়া!',
        outcomeText: 'আংকেল এমুন একখান পচা ডিমের পাদ দিলো, গন্ধ শুইকা তুই ট্রেনের ভিতরেই অজ্ঞান হইয়া পড়লি!',
        tone: 'funny',
        effects: { health: -15, happiness: -20, smarts: -5 },
      },
      {
        id: 'lose_shoe_in_crowd',
        text: 'পাবলিকের ধাক্কায় ট্রেন থিকা ছিটকায়া ডাইরেক্ট এক ভিক্ষুকের গায়ের উপ্রে পড়!',
        outcomeText: 'তোর প্যান্ট ফাইট্টা একাকার! ভিক্ষুক উল্টা তোর কাছে ক্ষতিপূরণ চাইয়া বসল, ইজ্জত পুরাই লাল বাত্তি!',
        tone: 'bad',
        effects: { looks: -20, money: -20, happiness: -15 },
      },
    ],
  },
  {
    id: 'ya_sakraan_rooftop',
    text: 'সাকরাইনের ছাদে ফাপড় আর কাটাকাটি: পৌষ সংক্রান্তির ভোরে পুরান ঢাকার ছাদ যেন এক মহাযুদ্ধ!',
    minAge: 18,
    maxAge: 29,
    weight: 9,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'sakraan_chokkhu_buijha_katti',
        text: 'নাটাই হাতে নিয়া "চক্ষু বুইঝা কাট্টি" খেলতে গিয়া ছাদ থিকা পা ফসকা!',
        outcomeText: 'ডাইরেক্ট মুরগির খোপের উপ্রে গিয়া পড়লি! গু আর পালক মাইখা তুই পুরাই মুরগি-মানব, পাবলিক হাসতে হাসতে শেষ!',
        tone: 'funny',
        effects: { health: -15, looks: -25, happiness: -10 },
      },
      {
        id: 'sakraan_chudur_budur_dj',
        text: 'চুদুর বুদুর বাদ দিয়া স্পিকারের ফুল ভলিউমে ডিজে বাজায়া ড্যান্স দে!',
        outcomeText: 'পাশের বাড়ির বদরাগী আংকেল পুলিশের ভয় দেখাইয়া স্পিকারের তার কাইটা দিলো! তোর পার্টি পুরাই মাটি!',
        tone: 'bad',
        effects: { happiness: -15, money: -30 },
      },
    ],
  },
  {
    id: 'uni_tongi_commute',
    text: 'টঙ্গী থিকা ঢাকা: জ্যামের মাইঙ্কা চিপা: সকাল আটটায় ভার্সিটিতে ল্যাব ক্লাস, আর তুই বাসে ঝুইলা আছোস!',
    minAge: 18,
    maxAge: 26,
    weight: 8,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'tongi_conductor_fapor',
        text: 'কন্টাক্টরের লগে হাফ পাস নিয়া গ্যাঞ্জাম লাগাইয়া কলার ধর!',
        outcomeText: 'কন্টাক্টর আর হেল্পার মিল্লা তোরে বাস থিকা ঘাড়ধাক্কা দিয়া রাস্তায় ফালায়া দিলো! কাদা মাইখা তুই পুরাই ভিখারি!',
        tone: 'bad',
        effects: { health: -10, looks: -20, happiness: -20 },
      },
      {
        id: 'tongi_headphone_sleep',
        text: 'কানে হেডফোন দিয়া সিটে বইসা হা কইরা ঘুম দে!',
        outcomeText: 'ঘুমের চোটে মুখ দিয়া লালা পইড়া পাশের এক আন্টির শাড়িতে মাখামাখি! আন্টির গাইল শুইনা তোর জান শেষ!',
        tone: 'funny',
        effects: { looks: -15, karma: -10, happiness: -15 },
      },
    ],
  },
  {
    id: 'gf_bkash_salami',
    text: 'ওয়াইফির রাগ আর পকেটে বাতাস: ওয়াইফির (gf) মন মেজাজ পুরাই ফায়ার, সালামি চায়! কিন্তু তোর পকেট পুরাই গড়ের মাঠ!',
    minAge: 18,
    maxAge: 29,
    weight: 8,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'bkash_dhar_salami',
        text: 'বিকাশের ফেক মেসেজ বানাইয়া তারে ফরোয়ার্ড মাইরা দে!',
        outcomeText: 'ওয়াইফি ব্যালেন্স চেক কইরা বাটপারি ধইরা ফেলছে! গাইল দিয়া ডাইরেক্ট ব্রেকআপ মাইরা দিছে, তুই পুরাই ছ্যাঁকা খাওয়া দেবদাস!',
        tone: 'bad',
        effects: { happiness: -40, smarts: -15, looks: -10 },
      },
      {
        id: 'emotional_bangla_kobita',
        text: 'ইমোশনাল ফাপড় দে: "ট্যাকা দিয়া কী হইবো বাবু, আমার কিডনি লেইখা দিলাম তোমারে!"',
        outcomeText: 'ওয়াইফি বিরক্ত হইয়া কইলো, "ফইন্নি কোথাকার, ফুট হালায়!" তোর ইমোশন ডাইরেক্ট ডাস্টবিনে!',
        tone: 'funny',
        effects: { happiness: -20, karma: -5 },
      },
    ],
  },
];