import type { LifeEventDef } from '@/lib/engine/types';

export const YOUNG_ADULT_FALLBACK_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'ya_first_job_interview',
    text: 'মতিঝিলের এক কর্পোরেট অফিসে ইন্টারভিউ! ইন্টারভিউয়ার কড়া চোখে তাকায়া জিগাইলো, "আপনার ৫ বছরের ভবিষ্যৎ প্ল্যান কী?"',
    minAge: 18,
    maxAge: 26,
    weight: 9,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'impress_smart_answer',
        text: 'কনফিডেন্স নিয়া ক: "কোম্পানির গ্রোথ ডাবল করুম আর নিজের পজিশন লিডারশিপে নিমু!"',
        outcomeText: 'ইন্টারভিউয়ার মুগ্ধ হইয়া অফার লেটার ধরাইয়া দিলো! বেতনও মনের মতো!',
        tone: 'good',
        effects: { money: 300, happiness: 25, smarts: 15 },
      },
      {
        id: 'humble_dhakaiya_answer',
        text: 'একটু হেঁসে ক: "স্যার, সৎভাবে কাজ করমু আর দুবেলা কাচ্চি খাওয়ার ট্যাকা কামামু!"',
        outcomeText: 'সবাই হাসলো, তোর সততা দেইখা জুনিয়র এক্সিকিউটিভ পদে জয়েন করাইয়া নিলো।',
        tone: 'good',
        effects: { money: 150, happiness: 15, smarts: 8 },
      },
      {
        id: 'freeze_stutter',
        text: 'ভয়ে ঢোক গিলা তোতলাইয়া ফেল',
        outcomeText: '"উই উইল লেট ইউ নো" বইলা ভাগায়া দিলো। মন খারাপ কইরা রিকশায় বাড়ি ফিরলি।',
        tone: 'bad',
        effects: { happiness: -15, looks: -5 },
      },
    ],
  },
  {
    id: 'ya_first_salary_treat',
    text: 'চাকরির প্রথম মাসের বেতন একাউন্টে ঢুকতেই দোস্তরা চায়ের দোকানে ঘেরাও কইরা স্লোগান দিলো: "ট্রিট দে, ট্রিট দে!"',
    minAge: 22,
    maxAge: 28,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'kacchi_bhai_treat',
        text: 'সব দোস্তররে নিয়া ধানমন্ডি কাচ্চি ভাইয়ে বোরহানি সহ ভরপেট খাওয়া',
        outcomeText: 'দোস্তরা তোরে কাঁধে নিয়া নাচলো! পকেট হালকা হইলো, কিন্তু ইজ্জত বাড়লো ষোলো আনা!',
        tone: 'good',
        effects: { money: -120, happiness: 25, karma: 15 },
      },
      {
        id: 'cha_biscuit_stingy',
        text: 'কঞ্জুসের লাহান খালি লাল চা আর বাকরখানি খাওয়ায়া বিদায় কর',
        outcomeText: 'দোস্তরা কইলো, "হালার ফকিরের ঘরের ফকির!" পিছে গীবত শুরু হইলো।',
        tone: 'bad',
        effects: { money: -10, happiness: -10, karma: -10 },
      },
    ],
  },
  {
    id: 'ya_friend_debt_ghost',
    text: 'ঘনিষ্ঠ দোস্ত কান্নাকাটি কইরা কইলো, "মামা, হাসপাতালে আম্মার অপারেশন, ২০ হাজার ট্যাকা দে, আগামী মাসেই দিয়া দিমু!"',
    minAge: 23,
    maxAge: 29,
    weight: 8,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'give_loan_friend',
        text: 'মানবিকতা দেখায়া কষ্টার্জিত সঞ্চয়ের টাকা ধার দে',
        outcomeText: 'পরের মাসে দোস্তের ফোন বন্ধ! ফেসবুকে ব্লক! হালায় নতুন আইফোন নিয়া কক্সবাজার ঘুরতাছে!',
        tone: 'bad',
        effects: { money: -250, happiness: -25, karma: 10 },
      },
      {
        id: 'excuse_tight_budget',
        text: 'চালাকি কইরা ক: "মামা, আমি নিজেই তো ঋণে ফাইস্যা মাইঙ্কা চিপায় আছি!"',
        outcomeText: 'দোস্ত মন খারাপ কইরা গেল, কিন্তু তোর কষ্টের টাকা পকেটে সুরক্ষিত রইলো।',
        tone: 'neutral',
        effects: { smarts: 12, karma: -5 },
      },
    ],
  },
  {
    id: 'ya_wedding_dance_center',
    text: 'খালাতো বোনের বিয়েতে ডিজে গানের তালে নাচিয়ার ডাক পড়লো। স্টেজে সবাই ভিড় জমাইছে!',
    minAge: 18,
    maxAge: 29,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'epic_dhakaiya_dance',
        text: '"আমি ফাইস্যা গেছি" গানে কোমর দুলাইয়া আগুন লাগায়া নাচ!',
        outcomeText: 'কমিউনিটি সেন্টারের ফ্লোর কাঁপলো! বিয়ের ভিডিওতে তুই সুপারস্টার, বরের বাড়ির এক পাত্রী তোরে পটায়া ফেললো!',
        tone: 'good',
        effects: { happiness: 25, looks: 15 },
      },
      {
        id: 'eat_biryani_corner',
        text: 'নাচানাচি বাদ দিয়া প্লেট ভইরা খাসির কাচ্চি ধ্বংস কর',
        outcomeText: 'তিন প্লেট কাচ্চি সাফ কইরা পেট ফুলিয়ে বাড়ি ফিরলি। শান্তির ঘুম!',
        tone: 'good',
        effects: { health: 6, happiness: 18 },
      },
    ],
  },
  {
    id: 'ya_buy_secondhand_bike',
    text: 'অফিসে বাসে ঝুলতে ঝুলতে বিরক্ত হইয়া জমানো টাকায় একখান সেকেন্ডহ্যান্ড পালসার বাইক কিনলি!',
    minAge: 23,
    maxAge: 29,
    weight: 7,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'modify_exhaust',
        text: 'সাইলেন্সার পাইপ কাইটা বিকট আওয়াজের স্পোর্টস হর্ন লাগা',
        outcomeText: 'মহল্লার মানুষ তোরে গালি দিল, পুলিশের সার্জেন্ট ধরে ২০০ টাকার মামলা ঠুকে দিলো!',
        tone: 'bad',
        effects: { money: -50, karma: -10, looks: -5 },
      },
      {
        id: 'ride_safe_helmet',
        text: 'ভালো হেলমেট পইড়া ভদ্র ছেলের মতো অফিস যাতায়াত কর',
        outcomeText: 'জ্যামের শহরে সময় বাঁচলো, অফিসে টাইমে পৌছাইয়া বসের প্রশংসা পেলি!',
        tone: 'good',
        effects: { happiness: 15, smarts: 8 },
      },
    ],
  },
  {
    id: 'ya_startup_dream_foodcart',
    text: 'চাকরিতে মন বসে না। দোস্ত কইলো, "চল নাজিরাবাজারে একখান প্রিমিয়াম কাবাবের ফুডকার্ট দিয়া ব্যবসা ফাঁদি!"',
    minAge: 24,
    maxAge: 29,
    weight: 8,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'invest_savings_cart',
        text: 'জমানো টাকা ইনভেস্ট কইরা শিক কাবাবের চুলা জ্বালাও',
        outcomeText: 'প্রথম মাসেই ভাইরাল! প্রতিদিন ২০০ শিক কাবাব বিক্রি হইয়া পকেটে কাঁচা টাকার বন্যা!',
        tone: 'good',
        effects: { money: 600, happiness: 25, smarts: 15 },
      },
      {
        id: 'stick_to_job',
        text: 'ঝুঁকি না নিয়া মাস শেষে নিশ্চিত বেতন গোনার পথেই থাক',
        outcomeText: 'নিরাপদ জীবন, কিন্তু ফুডকার্টওয়ালা দোস্তরে নতুন গাড়ি কিনতে দেইখা বুকটা হুহু কইরা উঠলো।',
        tone: 'neutral',
        effects: { money: 100, happiness: -5 },
      },
    ],
  },
  {
    id: 'ya_dating_dhanmondi_lake',
    text: 'প্রেমিকার লগে ধানমন্ডি লেকে রবীন্দ্র সরোবরের পাড়ে বাদাম খাইতে খাইতে বসা। হঠাৎ তোদের দিকে আম্মার বান্ধবী হাইটা আসতেছে!',
    minAge: 18,
    maxAge: 27,
    weight: 8,
    tone: 'funny',
    category: 'teen',
    source: 'fallback',
    choices: [
      {
        id: 'jump_behind_bushes',
        text: 'প্রেমিকার হাত ছাইড়া সোজা ঝোপের পিছনে ডাইভ দে',
        outcomeText: 'বান্ধবী আন্টি তোরে দেখলো না, কিন্তু প্রেমিকা অপমানিত হইয়া তোরে ছ্যাঁকা দিয়া দিলো!',
        tone: 'bad',
        effects: { happiness: -25, looks: -8, karma: -10 },
      },
      {
        id: 'introduce_bravely',
        text: 'বুকের পাটা শক্ত কইরা আন্টিরে সালাম দিয়া প্রেমিকার পরিচয় দে',
        outcomeText: 'আন্টি মিষ্টি হাইসা আম্মারে ফোন দিয়া বিয়ের প্রস্তাব পাঠাইতে কইলো! সাহসের জয়!',
        tone: 'good',
        effects: { happiness: 25, smarts: 12, looks: 10 },
      },
    ],
  },
  {
    id: 'ya_overtime_boss_fight',
    text: 'শুক্রবার ছুটির দিনে বস ফোন দিয়া কইলো, "জরুরি ক্লায়েন্ট প্রেজেন্টেশন আছে, এখনি অফিসে আসেন!"',
    minAge: 24,
    maxAge: 29,
    weight: 7,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'attend_overtime',
        text: 'ঘুমের মায়া ত্যাগ কইরা অফিসে গিয়া রাতদিন এক কইরা কাজ শেষ কর',
        outcomeText: 'বস খুশি হইয়া প্রমোশনের লিস্টে তোর নাম এক নম্বরে রাখলো!',
        tone: 'good',
        effects: { money: 200, smarts: 10, health: -8 },
      },
      {
        id: 'fake_illness',
        text: 'কাশি দিয়া ক: "স্যার, তীব্র ডায়রিয়ায় স্যালাইন খায়া শুইয়া আছি!"',
        outcomeText: 'ছুটি কাটাইলি ঠিকই, কিন্তু সোমবারে অফিসে গিয়া দেখলি বস তোর ওপর খ্যাপা!',
        tone: 'bad',
        effects: { happiness: 10, karma: -5 },
      },
    ],
  },
  {
    id: 'ya_university_tsc_adda',
    text: 'বিশ্ববিদ্যালয়ের ক্লাসের ফাঁকে টিএসসির মোড়ে গরম চা আর ডালপুরি নিয়া জমজমাট আড্ডায় বসলি!',
    minAge: 18,
    maxAge: 24,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'sing_guitar_adda',
        text: 'গিটার হাতে নিয়া বন্ধুদের সাথে ব্যান্ডের গান তোল',
        outcomeText: 'চারপাশের মানুষ ভিড় জমাইলো! এক মায়াবী জুনিয়র তোর ফ্যান হইয়া গেল!',
        tone: 'good',
        effects: { happiness: 22, looks: 12 },
      },
      {
        id: 'debate_philosophy',
        text: 'সিরিয়াস দার্শনিক তত্ত্ব কপচাও',
        outcomeText: 'বন্ধুরা হাইসা কইলো, "হালায় আতেলগিরি থামাবি?" এক কাপ চা ফাউ জুটলো।',
        tone: 'funny',
        effects: { smarts: 10, happiness: 10 },
      },
    ],
  },
  {
    id: 'ya_bcs_exam_study_hall',
    text: 'বিসিএস প্রিলিমিনারি পরীক্ষার আর তিন মাস বাকি। কেন্দ্রীয় লাইব্রেরিতে নীলক্ষেতের গাইড বইয়ের পাহাড়!',
    minAge: 22,
    maxAge: 28,
    weight: 8,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'grind_bcs_14_hours',
        text: 'প্রেম-ভালোবাসা বাদ দিয়া প্রতিদিন ১৪ ঘণ্টা মুখস্থ করো',
        outcomeText: 'প্রিলি পাস! আত্মীয়স্বজনের নজর তোর দিকে, কদর রাতারাতি বেড়ে গেল!',
        tone: 'good',
        effects: { smarts: 20, happiness: 25, health: -8 },
      },
      {
        id: 'procrastinate_reel',
        text: 'পড়ার টেবিলে মোবাইল টিপে ফেসবুক রিলস দেখে সময় নষ্ট করো',
        outcomeText: 'পরীক্ষার হলে সব প্রশ্ন চায়নিজ মনে হইলো! আফসোসে চান্দি গরম!',
        tone: 'bad',
        effects: { smarts: -4, happiness: -18 },
      },
    ],
  },
  {
    id: 'ya_matchmaker_proposal_ghotok',
    text: 'বিখ্যাত ঘটক কাসেম আলী পান চাবাইতে চাবাইতে ড্রয়িংরুমে এক বড়লোক খান্দানি পাত্রী/পাত্রের ছবি মেলিয়া ধরলো!',
    minAge: 22,
    maxAge: 29,
    weight: 8,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'agree_see_family',
        text: 'সাজুগুজু কইরা মিষ্টির প্যাকেট নিয়া পাত্রী/পাত্র দেখতে যাও',
        outcomeText: 'কথাবার্তা জমলো, পরিবারের সবার পছন্দ! বিয়ের বাদ্য বাজার প্রস্তুতি শুরু!',
        tone: 'good',
        effects: { happiness: 20, looks: 10, money: -50 },
      },
      {
        id: 'reject_outright_career',
        text: 'ঘাড় ত্যাড়া কইরা ক: "নিজের পায়ে না দাঁড়াইয়া বিয়ে করুম না!"',
        outcomeText: 'আম্মা কান্নাকাটি শুরু করলো, ঘটক মুখ কালো করে বিদায় নিলো।',
        tone: 'neutral',
        effects: { smarts: 8, karma: -5, happiness: -5 },
      },
    ],
  },
  {
    id: 'ya_office_politics_appraisal',
    text: 'বছরের শেষে পারফর্মেন্স অ্যাপ্রাইজাল! বস তোর কাজরে অবমূল্যায়ন কইরা চাটুকার কলিগরে ক্রেডিট দিতেছে!',
    minAge: 23,
    maxAge: 29,
    weight: 8,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'present_data_metrics',
        text: 'তথ্য ও পরিসংখ্যান সাজিয়ে বসের মুখের উপর প্রমাণ পেশ করো',
        outcomeText: 'বস থতমত খেয়ে ৩০% ইনক্রিমেন্ট আর সিনিয়র টাইটেল দিতে বাধ্য হইলো!',
        tone: 'good',
        effects: { money: 350, happiness: 25, smarts: 14 },
      },
      {
        id: 'threaten_to_resign',
        text: 'টেবিলে পদত্যাগপত্র আছাড় মেরে চিৎকার করো',
        outcomeText: 'চাকরিটাই গেল! নোটিশ পিরিয়ডে কান্দা মন নিয়া বাড়ি ফিরলি!',
        tone: 'bad',
        effects: { money: -200, happiness: -25, health: -6 },
      },
    ],
  },
  {
    id: 'ya_bachelor_mess_cooking',
    text: 'ফার্মগেটের ব্যাচেলর মেসে বুয়া না আসায় তোরে রান্নার দায়িত্ব দেওয়া হইলো। জীবনে ডিমও ভাজিস নাই!',
    minAge: 18,
    maxAge: 25,
    weight: 7,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'cook_khichuri_experiment',
        text: 'ডাল, চাল আর ডিমের একখান আজব খিচুড়ি বানাও',
        outcomeText: 'খিচুড়ি একটু পুড়লো ঠিকই, কিন্তু খিদার চোটে মেসের সবাই চেটেপুটে খাইলো!',
        tone: 'good',
        effects: { smarts: 8, happiness: 12 },
      },
      {
        id: 'order_food_waste_rent',
        text: 'ভাড়ার টাকা ভাইঙ্গা অনলাইনে বিরিয়ানি অর্ডার দাও',
        outcomeText: 'স্বাদে মাখন, কিন্তু মাস শেষে মেস ম্যানেজার বাড়িওয়ালার সাথে বিচার ডাকলো!',
        tone: 'bad',
        effects: { money: -60, happiness: -10 },
      },
    ],
  },
  {
    id: 'ya_dating_boat_buriganga',
    text: 'বিকালে প্রিয় মানুষটিকে নিয়া বুড়িগঙ্গার সদরঘাট থেকে বাদামতলী কাঠের নৌকায় সূর্যাস্ত দেখতে গেলি!',
    minAge: 18,
    maxAge: 28,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'recite_poetry_lover',
        text: 'নদীর হাওয়ায় তার হাত ধরে মিষ্টি প্রেমের কথা বলো',
        outcomeText: 'তার চোখের মায়ায় আলো ঝলমল করলো! প্রেমের সম্পর্ক পূর্ণতা পেল!',
        tone: 'good',
        effects: { happiness: 25, looks: 10 },
      },
      {
        id: 'drop_phone_in_river',
        text: 'সেলফি তুলতে গিয়া নতুন স্মার্টফোন নদীতে ফেলে দাও',
        outcomeText: 'টুপ কইরা ফোন তলিয়ে গেল! রোমান্টিক মুড নষ্ট, সারাটা পথ চোখ ছলছল!',
        tone: 'bad',
        effects: { money: -150, happiness: -22 },
      },
    ],
  },
  {
    id: 'ya_traffic_jam_cng_fare',
    text: 'গুলিস্তানের সিগন্যালে ৩ ঘণ্টা ধরে জ্যামে আটকা! সিএনজি ড্রাইভার কয়, "মামা, আরও ১০০ টাকা না দিলে নামেন!"',
    minAge: 21,
    maxAge: 29,
    weight: 7,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'argue_police_help',
        text: 'ট্রাফিক পুলিশ ডেকে ন্যায্য মিটারে নিয়ে চলো',
        outcomeText: 'পুলিশ ড্রাইভাররে বকা দিলো, তুই সঠিক ভাড়ায় সময়মতো পৌঁছালি!',
        tone: 'good',
        effects: { smarts: 12, happiness: 10 },
      },
      {
        id: 'walk_in_pollution',
        text: 'সিএনজি ছেড়ে ধোঁয়া আর গরমে হেঁটে রওনা দাও',
        outcomeText: 'ঘামে জামা ভিজে একাকার! অফিসে গিয়ে বসের ঝাড়ি জুটলো!',
        tone: 'bad',
        effects: { health: -10, happiness: -14 },
      },
    ],
  },
  {
    id: 'ya_freelancing_first_dollar',
    text: 'রাতের পর রাত জেগে ফ্রিল্যান্সিংয়ে প্রথম আমেরিকান ক্লায়েন্টের ওয়েবসাইট বানিয়ে ডেলিভারি দিলি!',
    minAge: 18,
    maxAge: 28,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'receive_500_dollar',
        text: 'ব্যাংক একাউন্টে প্রথম ৫০০ ডলার কনভার্ট করো',
        outcomeText: 'টাকার নোটিফিকেশন আসতেই চোখে আনন্দাশ্রু! আম্মার হাতে প্রথম কামাইয়ের টাকা তুইলা দিলি!',
        tone: 'good',
        effects: { money: 500, happiness: 25, smarts: 15, karma: 15 },
      },
      {
        id: 'buy_expensive_gadget',
        text: 'টাকা পেতেই লেটেস্ট মেকানিকাল কীবোর্ড আর গেমিং মাউস কিনে ফেলো',
        outcomeText: 'টেবিল সাজলো সুন্দর, কাজ করতে দারুণ লাগতে লাগলো!',
        tone: 'good',
        effects: { money: -100, happiness: 18, smarts: 6 },
      },
    ],
  },
  {
    id: 'ya_crypto_fomo_loss',
    text: 'বন্ধুর কথায় প্রলুব্ধ হইয়া জমানো সব টাকা একখান আজব ক্রিপ্টো কয়েনে ইনভেস্ট করলি!',
    minAge: 21,
    maxAge: 28,
    weight: 7,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'panic_sell_bottom',
        text: 'কয়েন ৯০% পড়ে যেতেই ভয়ে সব বিক্রি করে দাও',
        outcomeText: 'কষ্টের সঞ্চয় উবে গেল! মাথায় হাত দিয়ে ফুটপাতে বসে কান্নাকাটি!',
        tone: 'bad',
        effects: { money: -300, happiness: -25, smarts: 8 },
      },
      {
        id: 'learn_hard_lesson',
        text: 'টাকা যাওয়া মেনে নিয়ে সৎ মেহনতের চাকরিতে মন দাও',
        outcomeText: 'জীবন এক চরম শিক্ষা দিলো। শর্টকাটে বড়লোক হওয়ার ভূত মাথা থেকে নামলো!',
        tone: 'neutral',
        effects: { money: -200, smarts: 18, happiness: -10 },
      },
    ],
  },
  {
    id: 'ya_father_business_shop',
    text: 'নবাবপুরের হার্ডওয়্যারের পুরনো দোকানের ক্যাশে তোরে বসায়া আব্বা কয়, "আজ থিকা তুই এই দোকানের মালিক!"',
    minAge: 22,
    maxAge: 29,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'modernize_shop_pos',
        text: 'পুরনো খাতার বদলে কম্পিউটারে ডিজিটাল হিসাব আর অনলাইন ডেলিভারি চালু করো',
        outcomeText: 'ব্যবসায় লাভ তিনগুণ বাড়লো! আব্বা গর্বে মহল্লায় সবাইকে মিষ্টি খাওয়াইলো!',
        tone: 'good',
        effects: { money: 400, smarts: 16, happiness: 25 },
      },
      {
        id: 'sit_lazily_smoke',
        text: 'দোকান কর্মচারীদের উপর ছাইড়া দিয়া সারাদিন তাস খেলো',
        outcomeText: 'কর্মচারীরা মালামাল চুরি করলো, ক্যাশে বিশাল ঘাটতি পড়ে আব্বার ধমক!',
        tone: 'bad',
        effects: { money: -150, karma: -12, happiness: -16 },
      },
    ],
  },
  {
    id: 'ya_wedding_kabin_bargain',
    text: 'বিয়ে চূড়ান্ত করার বৈঠকে দেনমোহর নিয়া দুই পরিবারের মুরুব্বিদের তুমুল বাকবিতণ্ডা শুরু হইলো!',
    minAge: 23,
    maxAge: 29,
    weight: 8,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'calm_both_sides',
        text: 'মাঝখানে দাঁড়িয়ে বলো: "আমাদের ভালোবাসা আর সংসারটাই আসল, সংখ্যার লড়াই থামান!"',
        outcomeText: 'তোর ব্যক্তিত্বে সবাই মুগ্ধ হইলো, সম্মানজনক দেনমোহরে বিয়ে পাকা!',
        tone: 'good',
        effects: { smarts: 15, karma: 18, happiness: 22 },
      },
      {
        id: 'storm_out_anger',
        text: 'মেজাজ হারিয়ে বৈঠক ছেড়ে বেরিয়ে যাও',
        outcomeText: 'বিয়ে ভেঙে গেল! দুই পরিবারের মাঝে আজীবনের শত্রুতা তৈরি হইলো!',
        tone: 'bad',
        effects: { happiness: -25, looks: -6, karma: -10 },
      },
    ],
  },
  {
    id: 'ya_overseas_visa_agency',
    text: 'পল্টনের এক ট্রাভেল এজেন্সি লোভ দেখাইলো: "১০ লাখ দিলে কানাডার ওয়ার্ক পারমিট ভিসা গ্যারান্টি!"',
    minAge: 22,
    maxAge: 29,
    weight: 8,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'verify_with_embassy',
        text: 'সরাসরি এম্বাসির ওয়েবসাইটে যাচাই করে ভুয়া চক্র ফাঁস করো',
        outcomeText: 'দালাল চক্রের হাত থেকে নিজের ও বন্ধুদের কোটি টাকা বাঁচিয়ে হিরো বনে গেলি!',
        tone: 'good',
        effects: { smarts: 18, karma: 20, happiness: 18 },
      },
      {
        id: 'pay_advance_token',
        text: 'অগ্রিম ৫০ হাজার টাকা টোকেন মানি দিয়ে দাও',
        outcomeText: 'পরের দিন গিয়ে দেখলি এজেন্সির অফিস বন্ধ! দালাল সব টাকা নিয়া ফুড়ুৎ!',
        tone: 'bad',
        effects: { money: -250, happiness: -25 },
      },
    ],
  },
  {
    id: 'ya_cox_bazar_trip_gang',
    text: 'শীতের রাতে পাঁচ দোস্ত মিলে মোটরবাইকে টেকনাফ-কক্সবাজারের মেরিন ড্রাইভে ট্যুরে রওনা দিলি!',
    minAge: 21,
    maxAge: 27,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'camp_on_beach_stars',
        text: 'সৈকতে তাঁবু খাটিয়ে ক্যাম্পফায়ারে গান গেয়ে রাত কাটাও',
        outcomeText: 'সমুদ্রের গর্জন আর তারার মেলা! জীবনের অন্যতম সেরা রোমাঞ্চকর রাত!',
        tone: 'good',
        effects: { happiness: 25, health: 8, looks: 8 },
      },
      {
        id: 'speed_race_skid',
        text: 'বালুর রাস্তায় রেস করতে গিয়ে বাইক নিয়ে আছাড় খাও',
        outcomeText: 'বাইকের হ্যান্ডেল বাঁকা, হাত ছড়ে রক্তাক্ত! ট্যুর নষ্ট!',
        tone: 'bad',
        effects: { health: -14, money: -80, happiness: -16 },
      },
    ],
  },
  {
    id: 'ya_first_car_reconditioned',
    text: 'দীর্ঘ সঞ্চয় দিয়ে জাপানি রিকন্ডিশনড একখানা সাদা সেডান গাড়ি কিনলি! মহল্লায় আলোড়ন!',
    minAge: 25,
    maxAge: 29,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'drive_family_to_mawa',
        text: 'পরিবারের সবাইকে নিয়ে মাওয়া ঘাটে ইলিশ খেতে যাও',
        outcomeText: 'পদ্মা সেতুর ওপর গাড়ি থামিয়ে সবাই সেলফি তুললো! আব্বার চোখে গর্বের জল!',
        tone: 'good',
        effects: { happiness: 25, money: -60, looks: 12 },
      },
      {
        id: 'bumper_dent_rickshaw',
        text: 'পুরান ঢাকার চিপা গলিতে ঢুকিয়ে রিকশার পাদানিতে ঘষা লাগাও',
        outcomeText: 'নতুন গাড়ির বাম্পারে বিশ্রী দাগ! দেখে কলিজায় রক্তক্ষরণ!',
        tone: 'bad',
        effects: { money: -50, happiness: -15 },
      },
    ],
  },
  {
    id: 'ya_mother_emotional_blackmail',
    text: 'আম্মা কপালে হাত দিয়ে কানতে কানতে কইলো, "আমি মরার আগে কি তোর ঘরের নাতি-নাতনির মুখ দেইখা যাইতে পারুম না?"',
    minAge: 24,
    maxAge: 29,
    weight: 7,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'hug_mother_promise',
        text: 'আম্মাকে জড়িয়ে ধরে কও: "আগামী বছরই তোমারে সুসংবাদ দিমু!"',
        outcomeText: 'আম্মার চোখের পানি থামলো, হাসিমুখে তোর প্রিয় ইলিশ মাছ ভাজি করে খাওয়াইলো!',
        tone: 'good',
        effects: { happiness: 18, karma: 12 },
      },
      {
        id: 'argue_about_independence',
        text: 'কড়া গলায় ক: "আমার লাইফ নিয়ে অতিরিক্ত চুদুর বুদুর করবা না!"',
        outcomeText: 'আম্মা তিনদিন না খেয়ে রইলো! পুরো পরিবারে চরম অশান্তি!',
        tone: 'bad',
        effects: { karma: -18, happiness: -20 },
      },
    ],
  },
  {
    id: 'ya_rooftop_bbq_winter',
    text: 'কুয়াশাচ্ছন্ন পৌষের রাতে ছাদে বন্ধুদের নিয়ে শিক কাবাব আর পরোটার ধোঁয়া ওঠা বারবিকিউ পার্টি!',
    minAge: 21,
    maxAge: 29,
    weight: 8,
    tone: 'good',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'grill_perfect_kabab',
        text: 'মশলা মেখে কয়লার আগুনে রসালো মাটন শিক কাবাব তৈরি করো',
        outcomeText: 'স্বাদে অতুলনীয়! সবাই তোরে সেরা শেফ ঘোষণা করলো, আনন্দের সীমা নেই!',
        tone: 'good',
        effects: { happiness: 24, looks: 6, health: 6 },
      },
      {
        id: 'burn_kabab_black',
        text: 'আড্ডায় মশগুল হয়ে সব শিক কয়লা বানিয়ে ফেলো',
        outcomeText: 'সব মাংস পুড়ে ছাই! সবাই মিলে শুকনা পরোটা আর সস খেয়ে হাসাহাসি করলো!',
        tone: 'funny',
        effects: { money: -40, happiness: 8 },
      },
    ],
  },
  {
    id: 'ya_bank_loan_credit_card',
    text: 'ফোনে এক মিষ্টি কণ্ঠের সেলস অফিসার কইলো, "স্যার, আপনার জন্য কোনো জামানত ছাড়াই ৫ লাখের ক্রেডিট কার্ড রেডি!"',
    minAge: 23,
    maxAge: 29,
    weight: 7,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'politely_decline_card',
        text: 'শান্ত সুরে কও: "ধন্যবাদ, আমার ঋণের ফাঁদে পড়ার কোনো ইচ্ছা নেই!"',
        outcomeText: 'অপ্রয়োজনীয় খরচের ফাঁদ এড়ালে। মানসিক শান্তিতে ঘুমালে!',
        tone: 'good',
        effects: { smarts: 14, happiness: 10 },
      },
      {
        id: 'max_out_card_shopping',
        text: 'কার্ড নিয়ে শপিং মলে গিয়ে দামি ব্র্যান্ডের ঘড়ি আর জামা কিনো',
        outcomeText: 'পরের মাসে চড়া সুদের বিল দেখে চোখ কপালে! মাইঙ্কা চিপায় আটকা পড়লি!',
        tone: 'bad',
        effects: { money: -250, happiness: -22 },
      },
    ],
  },
  {
    id: 'ya_dhaka_metro_rush',
    text: 'সকাল ৯টায় ফার্মগেট স্টেশনে মেট্রোরেলের জন্য উপচে পড়া ভিড়! দরজা খুলতেই ধাক্কাধাক্কি শুরু!',
    minAge: 21,
    maxAge: 29,
    weight: 7,
    tone: 'neutral',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'squeeze_into_metro',
        text: 'কৌশলে চিপা দিয়ে ভেতরে ঢুকে হাতল শক্ত করে ধরো',
        outcomeText: 'মাত্র ১২ মিনিটে মতিঝিল পৌঁছে বসের আগেই অফিসে হাজির!',
        tone: 'good',
        effects: { smarts: 10, happiness: 16 },
      },
      {
        id: 'lose_shoe_in_crowd',
        text: 'ধাক্কার চোটে এক পায়ের চামড়ার জুতা প্ল্যাটফর্মে ফেলে ট্রেনে ওঠো',
        outcomeText: 'এক পায়ে জুতা পরে অফিসে গিয়ে চরম হাস্যরসের শিকার হলে!',
        tone: 'funny',
        effects: { looks: -8, happiness: -8, money: -30 },
      },
    ],
  },
  {
    id: 'ya_sakraan_rooftop',
    text: 'সাকরাইনের ছাদে ফাপড় আর কাটাকাটি: পৌষ সংক্রান্তির ভোরে পুরান ঢাকার ছাদ যেন এক মহাযুদ্ধ! আকাশে লাখ লাখ ঘুড়ি, স্পিকারে উরাধুরা গান, আর চারিদিকে হাঁকডাক: "ঐ ভোকাট্টা!" লগে মুরব্বিগো চিল্লাচিল্লি!',
    minAge: 18,
    maxAge: 29,
    weight: 9,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'sakraan_chokkhu_buijha_katti',
        text: 'নাটাই হাতে নিয়া "চক্ষু বুইঝা কাট্টি" খেলায় নামুম, আজকা সবডি প্যাঁচাইয়া ফালায় দিমু!',
        outcomeText: 'লাখ ঘুড়ি কাইটা মহল্লায় পুরাই বাঘের ভাব নিয়া চিল্লালি: "ভোকাট্টা!"',
        tone: 'good',
        effects: { happiness: 18, smarts: 5 },
      },
      {
        id: 'sakraan_chudur_budur_dj',
        text: 'চুদুর বুদুর বাদ দিয়া ছাদের ডেকোরেশন আর সাউন্ড সিস্টেমে গান বাজাইয়া আলগা ডিজে সাজমু!',
        outcomeText: 'ছাদের পোলাপাইন তোরে নিয়া ধুমধাম নাচানাচি করলো! ইজ্জত এক্কেরে আসমানে!',
        tone: 'funny',
        effects: { happiness: 12, looks: 6 },
      },
    ],
  },
  {
    id: 'uni_tongi_commute',
    text: 'টঙ্গী থিকা ঢাকা: জ্যামের মাইঙ্কা চিপা: সকাল আটটায় ভার্সিটিতে ল্যাব ক্লাস, আর তুই পইড়া আছোস টঙ্গীতে! বাসে উইঠা দেখস মানুষ না, পুরাই মুরগির খাঁচা। জ্যামে বইসা চান্দি পুরাই গরম!',
    minAge: 18,
    maxAge: 26,
    weight: 8,
    tone: 'bad',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'tongi_conductor_fapor',
        text: 'কন্টাক্টরের লগে গ্যাঞ্জাম লাগাইয়া ফাপড় দিয়া হাফ পাস দিমু, এক্কেরে বাপের ট্যাকা বাঁচামু!',
        outcomeText: 'কন্টাক্টরের লগে ঝগড়া কইরা হাফ পাস তো দিলি, কিন্তু কন্টাক্টর চিল্লায়া গালাগালি করলো!',
        tone: 'bad',
        effects: { money: 10, health: -5, looks: -5 },
      },
      {
        id: 'tongi_messenger_chilla',
        text: 'চুপচাপ সিটে বইসা রাইয়ান আর আরাফাতের লগে প্রজেক্টের প্যারা নিয়া মেসেঞ্জারে চিল্লামিল্লি করুম।',
        outcomeText: 'প্রজেক্টের প্যারা নিয়া চিল্লাইতে চিল্লাইতে মাথায় আগুন ধইরা গেল!',
        tone: 'neutral',
        effects: { smarts: 10, health: -5 },
      },
      {
        id: 'tongi_headphone_sleep',
        text: 'কানে হেডফোন দিয়া এক ঘুম দিমু, ক্লাস গোল্লায় যাক, জিন্দেগি চিল!',
        outcomeText: 'বাসের সিটে মাথা ঝুলাইয়া ঘুমাইয়া মহা তৃপ্তি পাইলি, স্যার ল্যাবে এবসেন্ট বসায় দিলো!',
        tone: 'funny',
        effects: { happiness: 15, smarts: -15 },
      },
    ],
  },
  {
    id: 'gf_bkash_salami',
    text: 'ওয়াইফির রাগ আর পকেটে বাতাস: ওয়াইফির (gf) মন মেজাজ পুরাই লাল বাত্তি, কিন্তু তোর পকেট পুরাই গড়ের মাঠ, এক্কেরে ফকিরি হালত! এহন চিপা থিকা কেমনে বাইর হইবি?',
    minAge: 18,
    maxAge: 29,
    weight: 8,
    tone: 'funny',
    category: 'young-adult',
    source: 'fallback',
    choices: [
      {
        id: 'bkash_dhar_salami',
        text: 'দোস্তগো কাছ থিকা ট্যাকা ধার কইরা বিকাশে সালামি পাঠাইয়া পুরাই রোমিও সাজমু!',
        outcomeText: 'বিকাশ যাইতেই ওয়াইফির মুখে চান্দের হাসি! তুই রোমিও হইলি কিন্তু দোস্তরা ধইরা মারলো!',
        tone: 'good',
        effects: { happiness: 20, money: -15, karma: 10 },
      },
      {
        id: 'emotional_bangla_kobita',
        text: 'কোনো ট্যাকা পয়সার সিন নাই, নিজের ব্রেন খাটাইয়া একখান সেই লেভেলের ইমোশনাল বাংলা কবিতা লেইখা পাঠায় দিমু!',
        outcomeText: 'তোর খাঁটি আবেগী কবিতা পইড়া ওয়াইফি গইলা পানি হইয়া গেল! বিনা খরচায় রাজত্ব!',
        tone: 'good',
        effects: { smarts: 15, looks: 10 },
      },
    ],
  },
];

