import type { LifeEventDef } from '@/lib/engine/types';

/**
 * Adult pool (ages 26–65, covers adult + middle-aged arcs): career
 * advancement and the business track, marriage/kids/divorce, home and car
 * purchases, market swings, the crime ladder, and health/mental-health
 * beats. Sensitive-content policy per DESIGN.md §11 — no graphic gore,
 * supportive mental-health framing only.
 */
export const ADULT_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'ad_office_review',
    text: 'Annual review season rolls around again, with its strange little ritual of mutual awkwardness.',
    minAge: 26,
    maxAge: 40,
    weight: 75,
    tone: 'neutral',
    category: 'adult',
    tags: ['career'],
    requiredFlags: ['job_office'],
    choices: [
      {
        id: 'ad_review_ask',
        text: 'Ask point-blank for a raise and more responsibility',
        effects: { money: 14, happiness: 3, addFlag: 'perf_high' },
        outcomeText: 'The manager hesitates, then nods. The raise lands with the next paycheck.',
        tone: 'good',
      },
      {
        id: 'ad_review_steady',
        text: 'Take the standard "meets expectations" and leave',
        effects: { happiness: 1, addFlag: 'perf_low' },
        outcomeText: 'Safe, quiet, and forever slightly resentful of the word "satisfactory".',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_tech_contract',
    text: 'A recruiter slides into your inbox with a remote tech role that pays in "exciting".',
    minAge: 25,
    maxAge: 45,
    weight: 70,
    tone: 'neutral',
    category: 'adult',
    tags: ['career'],
    requiredFlags: ['major_stem'],
    choices: [
      {
        id: 'ad_tech_take',
        text: 'Take the role and the stock options',
        effects: { money: 16, smarts: 5, happiness: 2, addFlag: 'job_tech' },
        outcomeText: 'You now write small programs that quietly improve a very large website.',
        tone: 'good',
      },
      {
        id: 'ad_tech_stay',
        text: 'Stay put; the current job is comfy',
        effects: { happiness: 3 },
        outcomeText: 'The recruiter sends exactly one more email, then gives up gracefully.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_medical_residency',
    text: 'The hospital is asking about your next rotation. Sleep becomes a rumour.',
    minAge: 26,
    maxAge: 40,
    weight: 55,
    tone: 'neutral',
    category: 'adult',
    tags: ['career', 'health'],
    requiredFlags: ['major_medicine'],
    choices: [
      {
        id: 'ad_medical_grind',
        text: 'Commit to the long hours',
        effects: { money: 15, smarts: 8, health: -8 },
        outcomeText: 'You help real people and forget what weekends are.',
        tone: 'good',
      },
      {
        id: 'ad_medical_balance',
        text: 'Push for humane hours and lateral toward clinics',
        effects: { health: 4, happiness: 5, money: 6 },
        outcomeText: 'Slower path, saner path. The patients still get excellent care.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ad_legal_partner',
    text: 'The partners at your law firm raise the subject of "your future here".',
    minAge: 30,
    maxAge: 50,
    weight: 50,
    tone: 'neutral',
    category: 'adult',
    tags: ['career'],
    requiredFlags: ['major_law'],
    choices: [
      {
        id: 'ad_legal_accept',
        text: 'Grind toward partnership',
        effects: { money: 20, happiness: -4, health: -3 },
        outcomeText: 'Your name goes on the letterhead. Your black bag has, regrettably, stamps too.',
        tone: 'good',
      },
      {
        id: 'ad_legal_leave',
        text: 'Leave the ladder for a nonprofit practice',
        effects: { happiness: 8, money: -6, karma: 5 },
        outcomeText: 'Smaller cases, bigger meaning. The partners send a polite card.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ad_art_success',
    text: 'A curator rings about your portfolio. It turns out someone has been watching your work.',
    minAge: 26,
    maxAge: 50,
    weight: 45,
    tone: 'good',
    category: 'adult',
    tags: ['career', 'fame'],
    requiredFlags: ['major_arts', 'hobby_art'],
    choices: [
      {
        id: 'ad_art_gallery',
        text: 'Show in the gallery',
        effects: { fame: 6, money: 12, happiness: 6, addFlag: 'job_art' },
        outcomeText: 'Two pieces sell. Your mother cries. You frame the awkward review too.',
        tone: 'good',
      },
      {
        id: 'ad_art_keep',
        text: 'Decline and keep making work you like',
        effects: { happiness: 8, karma: 1 },
        outcomeText: 'The work stays honest, and honestly, that was never going to be sold.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_finance_grade',
    text: 'The trading floor is having a good week and is in the mood to celebrate loudly.',
    minAge: 26,
    maxAge: 45,
    weight: 50,
    tone: 'neutral',
    category: 'adult',
    tags: ['career', 'finance'],
    requiredFlags: ['major_business'],
    choices: [
      {
        id: 'ad_finance_bonus',
        text: 'Take the bonus and a bigger book of clients',
        effects: { money: 22, health: -4, happiness: 2, addFlag: 'job_finance' },
        outcomeText: 'The bonus is real and the hours are longer than the peace of mind.',
        tone: 'good',
      },
      {
        id: 'ad_finance_lateral',
        text: 'Move to a calmer personal-finance desk',
        effects: { health: 5, happiness: 4, money: 8 },
        outcomeText: 'You now explain compound interest kindly to nervous retirees.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ad_job_fired_shock',
    text: 'A Tuesday meeting, a folder, and HR with a soft voice. You are being let go.',
    minAge: 26,
    maxAge: 55,
    weight: 50,
    tone: 'bad',
    category: 'adult',
    tags: ['career'],
    antiFlags: ['retired', 'job_business'],
    choices: [
      {
        id: 'ad_fired_search',
        text: 'Update the résumé and network like it is a sport',
        effects: { smarts: 4, money: -4, happiness: 3, addFlag: 'perf_high' },
        outcomeText: 'Eight weeks later a better offer lands. The folder was only the beginning.',
        tone: 'good',
      },
      {
        id: 'ad_fired_sulk',
        text: 'Take a long sulk and burn through savings',
        effects: { money: -10, happiness: -5, health: -2 },
        outcomeText: 'The sulk is thorough. The savings notice is not.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_start_business',
    text: 'You have been sketching a small business idea on the back of napkins for a year.',
    minAge: 26,
    maxAge: 50,
    weight: 55,
    tone: 'neutral',
    category: 'adult',
    tags: ['career', 'finance', 'risk'],
    choices: [
      {
        id: 'ad_business_launch',
        text: 'Launch it',
        effects: { money: -12, happiness: 6, addFlag: 'job_business' },
        outcomeText: 'Your sign goes up. Eleven whole customers notice in week one.',
        tone: 'good',
      },
      {
        id: 'ad_business_napkin',
        text: 'Keep it on the napkin',
        effects: { happiness: -1, money: 3 },
        outcomeText: 'The napkin is now laminated. It counts as commitment.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ad_business_scale',
    text: 'The little business outgrew your kitchen table. The rent on a real space is being quoted.',
    minAge: 28,
    maxAge: 55,
    weight: 45,
    tone: 'neutral',
    category: 'adult',
    tags: ['career', 'finance'],
    requiredFlags: ['job_business'],
    choices: [
      {
        id: 'ad_scale_grow',
        text: 'Take on the shop space and a small team',
        effects: { money: 18, happiness: 4, health: -3 },
        outcomeText: 'You now have an actual door with your name etched into the glass.',
        tone: 'good',
      },
      {
        id: 'ad_scale_sell',
        text: 'Sell the business while it is healthy',
        effects: { money: 25, happiness: 2, removeFlag: 'job_business' },
        outcomeText: 'The cheque lands. Someone else inherits the 6am deliveries.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_military_promotion',
    text: 'The barracks want a sergeant with steady hands; three people put your name forward.',
    minAge: 26,
    maxAge: 45,
    weight: 45,
    tone: 'neutral',
    category: 'adult',
    tags: ['career'],
    requiredFlags: ['job_military'],
    choices: [
      {
        id: 'ad_military_step',
        text: 'Take the stripes and the extra drill',
        effects: { money: 10, health: 3, happiness: 3 },
        outcomeText: 'The rank clicks on. The coffee sense dulls, peacefully.',
        tone: 'good',
      },
      {
        id: 'ad_military_retire',
        text: 'Wind down and plan an exit',
        effects: { happiness: 5, money: -3, addFlag: 'retired' },
        outcomeText: 'You map out the after-life: workshops, fishing, sleeping in.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_entertainer_break',
    text: 'Your channel goes viral for a week. Strangers start recognising your voice in public.',
    minAge: 26,
    maxAge: 50,
    weight: 45,
    tone: 'good',
    category: 'adult',
    tags: ['fame', 'career'],
    requiredFlags: ['job_entertainer'],
    choices: [
      {
        id: 'ad_ent_ride',
        text: 'Ride the wave with daily uploads',
        effects: { fame: 8, money: 12, happiness: 4 },
        outcomeText: 'The algorithm is a jealous god, but this week it favours you.',
        tone: 'good',
      },
      {
        id: 'ad_ent_grounded',
        text: 'Keep the regular life and post rarely',
        effects: { happiness: 7, fame: 1 },
        outcomeText: 'The wave rolls past without you. You prefer the quiet spray.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_politics_run',
    text: 'A ward council seat is open and a neighbour swears you would "win it easily".',
    minAge: 28,
    maxAge: 60,
    weight: 35,
    tone: 'neutral',
    category: 'adult',
    tags: ['career', 'fame'],
    choices: [
      {
        id: 'ad_politics_campaign',
        text: 'Run for the seat',
        effects: { fame: 6, money: -5, happiness: 3, addFlag: 'job_politics' },
        outcomeText: 'You win by 112 votes and inherit the world of committee minutes.',
        tone: 'good',
      },
      {
        id: 'ad_politics_help',
        text: 'Campaign for the other decent candidate instead',
        effects: { karma: 4, happiness: 2 },
        outcomeText: 'Your yard sign counts. Your title stays humble.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_sports_comeback',
    text: 'A recreational league wants an over-30 player with "humble attitudes and good knees".',
    minAge: 28,
    maxAge: 55,
    weight: 45,
    tone: 'neutral',
    category: 'adult',
    tags: ['sports', 'health'],
    requiredFlags: ['hobby_sport'],
    choices: [
      {
        id: 'ad_sports_play',
        text: 'Suit up for the season',
        effects: { health: 5, happiness: 5 },
        outcomeText: 'You land one glorious goal and re-injure an old knee. Worth it.',
        tone: 'good',
      },
      {
        id: 'ad_sports_coach',
        text: 'Coach the kids instead',
        effects: { happiness: 6, smarts: 2, karma: 2 },
        outcomeText: 'Your whistle is respected. Your knees remain grateful.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ad_marriage_proposal',
    text: 'The person you keep choosing, year after year, is smiling at you with a question in their eyes.',
    minAge: 22,
    maxAge: 50,
    weight: 75,
    tone: 'good',
    category: 'adult',
    tags: ['romance', 'family'],
    moment: 'wedding',
    requiredFlags: ['has_partner'],
    choices: [
      {
        id: 'ad_marry_yes',
        text: 'Say yes and throw a small, happy wedding',
        effects: { happiness: 15, money: -8, addFlag: 'has_spouse' },
        outcomeText: 'The rings clink, the family cries, the cake is genuinely excellent.',
        tone: 'good',
      },
      {
        id: 'ad_marry_soon',
        text: 'Say "soon" and mean it',
        effects: { happiness: 3 },
        outcomeText: 'Your person nods, satisfied. "Soon" has a deadline, unspoken.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_marital_strain',
    text: 'You and your spouse are orbiting different hobbies and the same silent stretch of sofa.',
    minAge: 26,
    maxAge: 60,
    weight: 55,
    tone: 'bad',
    category: 'adult',
    tags: ['romance', 'family'],
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'ad_strain_talk',
        text: 'Schedule a real talk over takeout',
        effects: { happiness: 6, addFlag: 'has_partner' },
        outcomeText: 'The talk is clumsy and kind. The sofa feels shared again.',
        tone: 'good',
      },
      {
        id: 'ad_strain_numb',
        text: 'Let it lie and focus on work',
        effects: { money: 6, happiness: -8 },
        outcomeText: 'The work gets better. The silence around it gets heavier.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_divorce_unravel',
    text: 'The partnership has been thin for a while, and a small fight escalates into a very large one.',
    minAge: 28,
    maxAge: 60,
    weight: 40,
    tone: 'bad',
    category: 'adult',
    tags: ['romance', 'family'],
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'ad_divorce_work',
        text: 'Insist on counselling before any decision',
        effects: { happiness: -3, money: -5, smarts: 3 },
        outcomeText: 'The counselling is hard. Sometimes it saves things; sometimes it ends them kindly.',
        tone: 'neutral',
      },
      {
        id: 'ad_divorce_split',
        text: 'Separate amicably and split the books fairly',
        effects: { happiness: -6, money: -10, addFlag: 'divorced', removeFlag: 'has_spouse' },
        outcomeText: 'Two new addresses, one shared set of friends, and a fair split of the cookbooks.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_baby_news',
    text: 'The doctor confirms it: a small, loud future is on the way and will arrive in nine months.',
    minAge: 22,
    maxAge: 45,
    weight: 70,
    tone: 'good',
    category: 'adult',
    tags: ['family', 'milestone'],
    moment: 'birth',
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'ad_baby_excited',
        text: 'Prepare the nursery and the argument about the middle name',
        effects: { happiness: 15, money: -8, addFlag: 'has_child' },
        outcomeText: 'Tiny socks are folded into tiny towers. You are already hopeless.',
        tone: 'good',
      },
      {
        id: 'ad_baby_later',
        text: 'Savour the calm while it lasts',
        effects: { happiness: 6, smarts: 2, addFlag: 'has_child' },
        outcomeText: 'The baby arrives anyway, along with a small mountain of advice.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_adoption_open',
    text: 'A letter arrives from an agency about fostering toward adoption. It is signed by a social worker, not a machine.',
    minAge: 28,
    maxAge: 50,
    weight: 40,
    tone: 'neutral',
    category: 'adult',
    tags: ['family'],
    choices: [
      {
        id: 'ad_adopt_begin',
        text: 'Begin the quiet, long journey',
        effects: { happiness: 8, money: -6, karma: 4, addFlag: 'has_child' },
        outcomeText: 'The paperwork is honest and enormous. Somewhere a child gains a home.',
        tone: 'good',
      },
      {
        id: 'ad_adopt_notyet',
        text: 'Keep the letter and revisit the idea later',
        effects: { happiness: -1 },
        outcomeText: 'The letter lives in a drawer, waiting patiently.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_empty_nest',
    text: 'The college box is in the hallway. Your kid leaves in the morning, carrying most of your accent.',
    minAge: 40,
    maxAge: 65,
    weight: 55,
    tone: 'neutral',
    category: 'adult',
    tags: ['family'],
    requiredFlags: ['has_child'],
    choices: [
      {
        id: 'ad_nest_new',
        text: 'Refit the spare room as a studio',
        effects: { happiness: 7, smarts: 4 },
        outcomeText: 'The room becomes yours again, briefly, before it becomes a guest room forever.',
        tone: 'good',
      },
      {
        id: 'ad_nest_miss',
        text: 'Call them every evening, "just to check"',
        effects: { happiness: 3 },
        outcomeText: 'They answer, mostly. The calls become shorter and sweeter by inches.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_first_house',
    text: 'The bank, the builder, and your own optimism finally agree on a shape called "your home".',
    minAge: 24,
    maxAge: 55,
    weight: 65,
    tone: 'good',
    category: 'adult',
    tags: ['finance', 'milestone'],
    moment: 'house',
    choices: [
      {
        id: 'ad_house_buy',
        text: 'Put down the deposit and take the keys',
        effects: { money: -15, happiness: 12, addFlag: 'has_house' },
        outcomeText: 'The key turns and the empty room echoes, gloriously, yours.',
        tone: 'good',
      },
      {
        id: 'ad_house_keep',
        text: 'Keep renting and bank the cash',
        effects: { money: 10, happiness: 2 },
        outcomeText: 'The landlord gets a card twice a year. You get flexibility and a tidy balance.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_car_decisions',
    text: 'Your commute now requires either a new car or a minor fitness journey.',
    minAge: 26,
    maxAge: 50,
    weight: 55,
    tone: 'neutral',
    category: 'adult',
    tags: ['finance', 'daily-life'],
    choices: [
      {
        id: 'ad_car_used',
        text: 'Buy a sensible used car',
        effects: { money: -8, happiness: 4, addFlag: 'has_car' },
        outcomeText: 'It hums in traffic and is exactly as exciting as a well-chosen pot.',
        tone: 'neutral',
      },
      {
        id: 'ad_car_cycle',
        text: 'Commit to the bicycle and the bus',
        effects: { health: 6, money: 4 },
        outcomeText: 'Your legs become quietly formidable. Your raincoat budget, less so.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ad_market_swing',
    text: 'The news anchor announces a dip with the voice of a weather report.',
    minAge: 30,
    maxAge: 65,
    weight: 55,
    tone: 'bad',
    category: 'adult',
    tags: ['finance'],
    choices: [
      {
        id: 'ad_market_hold',
        text: 'Hold everything and stay off the app',
        effects: { smarts: 4, happiness: 3 },
        outcomeText: 'A quarter later it recovers. Patience is written quietly into your ledger.',
        tone: 'good',
      },
      {
        id: 'ad_market_panic',
        text: 'Sell everything at the bottom in a panic',
        effects: { money: -15, happiness: -6, addFlag: 'has_debt' },
        outcomeText: 'You bought high, sold low, and bought the T-shirt of experience.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_market_boom',
    text: 'A friendly chart of your holdings has decided to only go up this month.',
    minAge: 30,
    maxAge: 65,
    weight: 45,
    tone: 'good',
    category: 'adult',
    tags: ['finance'],
    choices: [
      {
        id: 'ad_boom_cash',
        text: 'Take some profit and keep the record',
        effects: { money: 15, happiness: 4 },
        outcomeText: 'You sell a slice at the top. Not the whole slice. Just enough.',
        tone: 'good',
      },
      {
        id: 'ad_boom_hold',
        text: 'Let it ride, convinced it is your destiny',
        effects: { money: 8, addFlag: 'has_investment' },
        outcomeText: 'The muscle memory of the chart continues. Destiny remains a strong word.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_inheritance_odd',
    text: 'A far-away relative files a will, and you are in it. So is a carved wooden duck.',
    minAge: 30,
    maxAge: 70,
    weight: 35,
    tone: 'funny',
    category: 'adult',
    tags: ['finance', 'family'],
    choices: [
      {
        id: 'ad_inherit_accept',
        text: 'Accept both the money and the duck',
        effects: { money: 14, happiness: 3 },
        outcomeText: 'The duck now guards your bookshelf with a dignified expression.',
        tone: 'funny',
      },
      {
        id: 'ad_inherit_pass',
        text: 'Pass your share to the cleaner cause they named',
        effects: { karma: 6, happiness: 4 },
        outcomeText: 'A small plaque somewhere thanks you, sort of, for the clock.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ad_jury_duty',
    text: 'A postcard summons you to a courtroom three Tuesdays from now. Lunch included.',
    minAge: 21,
    maxAge: 65,
    weight: 40,
    tone: 'funny',
    category: 'adult',
    tags: ['daily-life', 'community'],
    choices: [
      {
        id: 'ad_jury_serve',
        text: 'Serve with solemn importance',
        effects: { smarts: 4, karma: 2, happiness: 2 },
        outcomeText: 'You deliver a verdict with hand gestures. The judge tolerates you.',
        tone: 'funny',
      },
      {
        id: 'ad_jury_excuse',
        text: 'Angle for the "hardship" exemption',
        effects: { happiness: 1, money: 1 },
        outcomeText: 'The clerk narrows their eyes. You are dismissed anyway. Win?',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ad_midlife_hobby',
    text: 'A sudden urge to make things again grips you somewhere between two meetings.',
    minAge: 35,
    maxAge: 60,
    weight: 55,
    tone: 'neutral',
    category: 'adult',
    tags: ['hobby', 'health'],
    choices: [
      {
        id: 'ad_hobby_music',
        text: 'Dust off the old instrument and take lessons',
        effects: { happiness: 8, smarts: 3, addFlag: 'hobby_music' },
        outcomeText: 'Your neighbours now host the world\'s quietest rehearsal studio.',
        tone: 'good',
      },
      {
        id: 'ad_hobby_art',
        text: 'Sign up for a pottery class',
        effects: { happiness: 9, addFlag: 'hobby_art' },
        outcomeText: 'Every mug you make leans. Every mug is loved.',
        tone: 'good',
      },
      {
        id: 'ad_hobby_sulk',
        text: 'Ignore the urge and buy a very expensive watch',
        effects: { money: -8, happiness: 2 },
        outcomeText: 'The watch is lovely. It does not, notably, make anything.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ad_mental_fog',
    text: 'For a few weeks the world feels as if it is behind glass. Everything weighs a little more.',
    minAge: 26,
    maxAge: 70,
    weight: 45,
    tone: 'bad',
    category: 'adult',
    tags: ['health', 'mental-health'],
    choices: [
      {
        id: 'ad_fog_therapy',
        text: 'Book sessions with a counsellor',
        effects: { health: 6, happiness: 6, addFlag: 'went_to_therapy' },
        outcomeText: 'Slow sessions, small tools, and one day the glass thins.',
        tone: 'good',
      },
      {
        id: 'ad_fog_speaking',
        text: 'Tell a close friend plainly and keep walking together',
        effects: { health: 3, happiness: 5 },
        outcomeText: 'Carried lightly by someone who listens. The week softens.',
        tone: 'good',
      },
      {
        id: 'ad_fog_bottle',
        text: 'Pretend it is just tiredness and push on',
        effects: { health: -5, happiness: -6, addFlag: 'mental_low' },
        outcomeText: 'Pushing on alone is rarely the road back.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_quit_bad_habit',
    text: 'Your doctor, having failed with softer hints, writes "suggest strongly" in block capitals.',
    minAge: 30,
    maxAge: 70,
    weight: 50,
    tone: 'neutral',
    category: 'adult',
    tags: ['health'],
    choices: [
      {
        id: 'ad_quit_cold',
        text: 'Quit cold turkey and smugly announce it',
        effects: { health: 9, happiness: -2, addFlag: 'quit_bad_habit' },
        outcomeText: 'Three hard weeks, then a quiet, permanent victory.',
        tone: 'good',
      },
      {
        id: 'ad_quit_taper',
        text: 'Taper with patches, apps, and counting',
        effects: { health: 8, happiness: 1, addFlag: 'quit_bad_habit' },
        outcomeText: 'A streak counter climbs. So do you, away from it.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ad_health_scare',
    text: 'A routine scan comes back with a "monitor this" note that steals two nights of sleep.',
    minAge: 40,
    maxAge: 75,
    weight: 45,
    tone: 'bad',
    category: 'adult',
    tags: ['health'],
    choices: [
      {
        id: 'ad_scare_follow',
        text: 'Follow the appointments and the good advice',
        effects: { health: 7, happiness: 2, addFlag: 'ill_recovered' },
        outcomeText: 'The follow-up comes back clear. You eat breakfast very happily after.',
        tone: 'good',
      },
      {
        id: 'ad_scare_delay',
        text: 'Shove the letter in a drawer',
        effects: { health: -5, happiness: -3 },
        outcomeText: 'The drawer grows heavier. Health waits for no one, politely decided.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_sabbatical_sign',
    text: 'Your savings could stretch to six months of "not much". The thought is loud.',
    minAge: 40,
    maxAge: 60,
    weight: 40,
    tone: 'neutral',
    category: 'adult',
    tags: ['career', 'lifestyle'],
    choices: [
      {
        id: 'ad_sabbatical_go',
        text: 'Take the sabbatical and go slow',
        effects: { happiness: 12, money: -8, smarts: 4 },
        outcomeText: 'You return with calmer eyes and one perfected breakfast.',
        tone: 'good',
      },
      {
        id: 'ad_sabbatical_skip',
        text: 'Cash out the plan into a sensible holiday',
        effects: { happiness: 7, money: -3 },
        outcomeText: 'Two weeks, not six months. Enough to feel the shift of gears.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_city_to_country',
    text: 'The countryside house near your old aunt grows a lawn and a very persuasive price tag.',
    minAge: 35,
    maxAge: 65,
    weight: 40,
    tone: 'neutral',
    category: 'adult',
    tags: ['lifestyle', 'family'],
    choices: [
      {
        id: 'ad_country_move',
        text: 'Move for the quiet and the birds',
        effects: { happiness: 8, health: 3, money: -5, addFlag: 'moved_away' },
        outcomeText: 'The train into meetings is long; the birdsong is longer.',
        tone: 'good',
      },
      {
        id: 'ad_city_stay',
        text: 'Stay put; the ferry of friends matters more',
        effects: { happiness: 4 },
        outcomeText: 'The city keeps you, and you keep your walkable coffee shop.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_crime_numbers_dodge',
    text: 'Your old friend at the warehouse asks you to quietly make the inventory numbers... friendlier.',
    minAge: 26,
    maxAge: 60,
    weight: 30,
    tone: 'bad',
    category: 'adult',
    tags: ['crime-abstracted'],
    choices: [
      {
        id: 'ad_crime_refuse',
        text: 'Refuse flat and keep your ledger clean',
        effects: { karma: 5, happiness: 1, smarts: 2 },
        outcomeText: 'The numbers stay honest. Your friendship gets a quiet temperature.',
        tone: 'good',
      },
      {
        id: 'ad_crime_help',
        text: 'Help once, "as a favour"',
        effects: { money: 10, happiness: -4, addFlag: 'criminal_record' },
        outcomeText: 'It is never once. The favour walks into an audit and the audit walks into your life.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_crime_arrested',
    text: 'The borrowed favour comes home to roost: an interview room, a folder, and a lawyer who is very calm.',
    minAge: 26,
    maxAge: 70,
    weight: 20,
    tone: 'bad',
    category: 'adult',
    tags: ['crime-abstracted', 'milestone'],
    moment: 'handcuffs',
    requiredFlags: ['criminal_record'],
    choices: [
      {
        id: 'ad_arrest_cooperate',
        text: 'Cooperate fully and pay your dues',
        effects: { health: -8, happiness: -8, money: -12, fame: -3, addFlag: 'gone_straight' },
        outcomeText: 'The record stays, the lesson lands, and the road back begins slowly.',
        tone: 'bad',
      },
      {
        id: 'ad_arrest_fight',
        text: 'Hire a costly lawyer and fight everything',
        effects: { money: -20, happiness: -4, smarts: 2 },
        outcomeText: 'You win on a technicality. The real price was never the fine.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_debt_snowball',
    text: 'Several crisp statements arrive with the clear message that the numbers have gone on holiday.',
    minAge: 26,
    maxAge: 65,
    weight: 40,
    tone: 'bad',
    category: 'adult',
    tags: ['finance'],
    choices: [
      {
        id: 'ad_debt_plan',
        text: 'Cut everything and snowball the payments',
        effects: { money: -8, health: 2, happiness: -3 },
        outcomeText: 'Month by month the smallest debt dies, then the next. The light is ahead.',
        tone: 'good',
      },
      {
        id: 'ad_debt_refinance',
        text: 'Roll it all into one tidy, larger loan',
        effects: { money: -6, addFlag: 'has_debt' },
        outcomeText: 'One number now. A larger number, but just the one. Your call.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_business_sued',
    text: 'A rival firm drops a letter on your doorstep about the trademark of a very common word.',
    minAge: 30,
    maxAge: 60,
    weight: 25,
    tone: 'bad',
    category: 'adult',
    tags: ['career', 'finance'],
    requiredFlags: ['job_business'],
    choices: [
      {
        id: 'ad_sued_settle',
        text: 'Settle quietly out of court',
        effects: { money: -14, happiness: -3 },
        outcomeText: 'The cheque is painful; the word "cloud" is now legally shared.',
        tone: 'bad',
      },
      {
        id: 'ad_sued_fight',
        text: 'Fight it with receipts and a good barrister',
        effects: { money: -10, smarts: 3, happiness: -1, addFlag: 'sued' },
        outcomeText: 'You win on the paperwork. The word stays yours, draped in legal costs.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_reconnect_parent',
    text: 'A family anniversary lands and, on a whim, you dial the number you have dialled less.',
    minAge: 30,
    maxAge: 70,
    weight: 55,
    tone: 'good',
    category: 'adult',
    tags: ['family', 'milestone'],
    moment: 'heart',
    choices: [
      {
        id: 'ad_reconnect_call',
        text: 'Make the call and keep it short and warm',
        effects: { happiness: 10, karma: 3 },
        outcomeText: 'Forty minutes later neither of you has hung up. The bridge is narrower.',
        tone: 'good',
      },
      {
        id: 'ad_reconnect_card',
        text: 'Send a card instead, with a note',
        effects: { happiness: 5, karma: 2 },
        outcomeText: 'The card returns to the fridge, which is a kind of response.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_social_star',
    text: 'Your dinner parties have acquired a reputation. People angle for invitations.',
    minAge: 30,
    maxAge: 70,
    weight: 45,
    tone: 'good',
    category: 'adult',
    tags: ['social', 'lifestyle'],
    choices: [
      {
        id: 'ad_social_host',
        text: 'Host the big monthly gathering',
        effects: { happiness: 8, fame: 2, addFlag: 'social_star' },
        outcomeText: 'The kitchen is chaos and the laughter is real. The reputation grows.',
        tone: 'good',
      },
      {
        id: 'ad_social_cozy',
        text: 'Keep it to two close friends and a good box of tea',
        effects: { happiness: 6 },
        outcomeText: 'Small, warm, and unfailingly good. The legend remains, quiet.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_mentor_junior',
    text: 'A new junior at work keeps hovering near your desk with hopeful questions.',
    minAge: 30,
    maxAge: 65,
    weight: 50,
    tone: 'good',
    category: 'adult',
    tags: ['career', 'community'],
    choices: [
      {
        id: 'ad_mentor_yes',
        text: 'Take them under your wing properly',
        effects: { karma: 4, happiness: 6, smarts: 2 },
        outcomeText: 'A year later they run the project you sketched for them. Delightful.',
        tone: 'good',
      },
      {
        id: 'ad_mentor_distract',
        text: 'Point at a manual and make a lovely escape',
        effects: { happiness: -1 },
        outcomeText: 'The manual is dense. They find someone kinder, eventually.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_second_child',
    text: 'The tiny shoes have a repeat order in progress. The doctor holds up two fingers.',
    minAge: 26,
    maxAge: 46,
    weight: 45,
    tone: 'good',
    category: 'adult',
    tags: ['family', 'milestone'],
    moment: 'birth',
    requiredFlags: ['has_child', 'has_spouse'],
    choices: [
      {
        id: 'ad_second_jump',
        text: 'Embrace the extra chaos',
        effects: { happiness: 12, money: -10 },
        outcomeText: 'Two small humans now negotiate for your attention. You lose, joyfully.',
        tone: 'good',
      },
      {
        id: 'ad_second_steady',
        text: 'Keep the routine ruthlessly',
        effects: { happiness: 8, smarts: 2 },
        outcomeText: 'The schedule is a fortress. The baby shrugs and naps through it.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_exec_ladder',
    text: 'A director role is open and your name has reached the shortlist on its own momentum.',
    minAge: 32,
    maxAge: 55,
    weight: 45,
    tone: 'neutral',
    category: 'adult',
    tags: ['career'],
    requiredFlags: ['job_office'],
    choices: [
      {
        id: 'exec_apply',
        text: 'Apply with your track record worn on your sleeve',
        effects: { money: 20, fame: 3, health: -3, happiness: 2 },
        outcomeText: 'The new office has a view. The view has meetings. Mostly meetings.',
        tone: 'good',
      },
      {
        id: 'exec_lateral',
        text: 'Pass and add "more depth over rank" to your legend',
        effects: { happiness: 4 },
        outcomeText: 'Your legend now includes lunches nobody interrupts.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_tax_season',
    text: 'Tax season arrives and the receipts you saved in a drawer now form a demanding relationship.',
    minAge: 26,
    maxAge: 70,
    weight: 50,
    tone: 'funny',
    category: 'adult',
    tags: ['finance', 'daily-life'],
    requiredFlags: ['job_business', 'side_hustle'],
    choices: [
      {
        id: 'tax_organised',
        text: 'Sort everything into a heroic spreadsheet',
        effects: { money: 8, smarts: 3 },
        outcomeText: 'The deduction is found, the state is satisfied, and the drawer weeps.',
        tone: 'good',
      },
      {
        id: 'tax_chaos',
        text: 'Shove it in a folder labelled "eventually"',
        effects: { money: -8, happiness: -2 },
        outcomeText: 'The envelope finds you. An accountant finds the envelope. A calm follows.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ad_neighbour_hedge',
    text: 'The hedge between you and the neighbours has opinions on both sides about its height.',
    minAge: 26,
    maxAge: 70,
    weight: 45,
    tone: 'funny',
    category: 'adult',
    tags: ['community', 'daily-life'],
    choices: [
      {
        id: 'hedge_gather',
        text: 'Gather the street for a hedge summit',
        effects: { happiness: 5, karma: 4 },
        outcomeText: 'The hedge is trimmed to a diplomatic half-height and friendship prevails.',
        tone: 'good',
      },
      {
        id: 'hedge_clip',
        text: 'Clip your side and call it a day',
        effects: { happiness: 1, karma: -1 },
        outcomeText: 'The mutual hedge grows faster on one side now. Winter solves it.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ad_sunday_runs',
    text: 'A dull Sunday looks like a good day to start moving, if only the sofa would release you.',
    minAge: 26,
    maxAge: 60,
    weight: 50,
    tone: 'neutral',
    category: 'adult',
    tags: ['health', 'activity'],
    choices: [
      {
        id: 'sunday_run_start',
        text: 'Start a gentle run-walk routine',
        effects: { health: 7, happiness: 4 },
        outcomeText: 'By month three, the Sunday run has a name and a playlist.',
        tone: 'good',
      },
      {
        id: 'sunday_walk',
        text: 'Walk to the good bakery and back',
        effects: { happiness: 5, health: 2 },
        outcomeText: 'A bakery route is technically cardio. You say so aloud.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ad_hobby_writing',
    text: 'A story has been rattling in your skull and a blank document is looking at you expectantly.',
    minAge: 28,
    maxAge: 70,
    weight: 45,
    tone: 'neutral',
    category: 'adult',
    tags: ['hobby'],
    choices: [
      {
        id: 'writing_draft',
        text: 'Write the first chapter badly, on purpose',
        effects: { happiness: 7, smarts: 3 },
        outcomeText: 'The chapter exists. The rattling quiets, temporarily.',
        tone: 'good',
      },
      {
        id: 'writing_note',
        text: 'Scribble three lines in a notebook instead',
        effects: { happiness: 3 },
        outcomeText: 'Three good lines. The notebook version is alive.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_community_cleanup',
    text: 'The park needs a cleanup day and the flyer has a clipart shovel that is deeply motivating.',
    minAge: 26,
    maxAge: 70,
    weight: 45,
    tone: 'good',
    category: 'adult',
    tags: ['community', 'activity'],
    choices: [
      {
        id: 'cleanup_join',
        text: 'Join and spend the morning hauling bags',
        effects: { health: 2, happiness: 6, karma: 5 },
        outcomeText: 'The park glows. The clipart shovel deserved every commendation.',
        tone: 'good',
      },
      {
        id: 'cleanup_treats',
        text: 'Show up with the refreshments instead',
        effects: { karma: 3, happiness: 4 },
        outcomeText: 'Hydration leadership. The volunteers line up in gratitude.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ad_phone_app_garden',
    text: 'A phone app is convinced it can teach you to identify every plant on your street.',
    minAge: 28,
    maxAge: 75,
    weight: 40,
    tone: 'funny',
    category: 'adult',
    tags: ['hobby', 'smarts'],
    choices: [
      {
        id: 'gardenapp_nature',
        text: 'Become the neighbourhood plant expert',
        effects: { smarts: 4, happiness: 4 },
        outcomeText: 'Your facts are 80% correct and delivered with total authority.',
        tone: 'funny',
      },
      {
        id: 'gardenapp_photo',
        text: 'Photograph one suspicious leaf for a week',
        effects: { happiness: 3 },
        outcomeText: 'The leaf is conclusively a leaf, per the app.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ad_teach_workshop',
    text: 'The local night school asks if you could teach a workshop in your very specific area.',
    minAge: 30,
    maxAge: 70,
    weight: 45,
    tone: 'good',
    category: 'adult',
    tags: ['education', 'community'],
    choices: [
      {
        id: 'workshop_teach',
        text: 'Prepare the workshop and deliver it',
        effects: { smarts: 3, happiness: 6, karma: 4 },
        outcomeText: 'Eleven students master your subject. One of them thanks you by name.',
        tone: 'good',
      },
      {
        id: 'workshop_mentor',
        text: 'Suggest a better candidate and back them fully',
        effects: { karma: 5, happiness: 2 },
        outcomeText: 'The workshop thrives and the credit flows somewhere warm.',
        tone: 'neutral',
      },
    ],
  },
];