import type { LifeEventDef } from '@/lib/engine/types';

export const CHILDHOOD_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'toddler_first_words',
    text: 'You are buzzing around the living room when your first real word slips out.',
    minAge: 1,
    maxAge: 2,
    weight: 90,
    tone: 'good',
    category: 'childhood',
    moment: 'confetti',
    tags: ['milestone'],
    choices: [
      {
        id: 'first_words_ma',
        text: 'Grin and say "Ma! Ma!"',
        effects: { happiness: 12, health: 2 },
        outcomeText: 'Someone scoops you up and you feel like the most clever person in the world.',
        tone: 'good',
      },
      {
        id: 'first_words_no',
        text: 'Say "No!" at the exact wrong moment',
        effects: { happiness: 5, smarts: 3 },
        outcomeText: 'Everyone laughs, and you file that power away for future use.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'toddler_tantrum',
    text: 'The cookie jar is on the top shelf. The whole universe is unfair right now.',
    minAge: 2,
    maxAge: 4,
    weight: 85,
    tone: 'bad',
    category: 'childhood',
    tags: ['milestone'],
    choices: [
      {
        id: 'tantrum_floor',
        text: 'Go limp and wail like a tiny siren',
        effects: { happiness: 5, smarts: -2 },
        outcomeText: 'It works for a while, then you nearly get put in the kitchen chair of shame.',
        tone: 'funny',
      },
      {
        id: 'tantrum_breathe',
        text: 'Take a big breath and point at what you want',
        effects: { smarts: 4, happiness: 3 },
        outcomeText: 'The grown-ups act like you just solved a maze. Fine, you will take it.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_pet_wish',
    text: 'You have decided: the family needs a hamster. There is no other option.',
    minAge: 4,
    maxAge: 7,
    weight: 60,
    tone: 'neutral',
    category: 'childhood',
    tags: ['family'],
    choices: [
      {
        id: 'pet_beg',
        text: 'Ask every single day until someone caves',
        effects: { happiness: 8, smarts: -2 },
        outcomeText: 'Your campaign has officially begun. Notes are being left on the fridge.',
        tone: 'funny',
      },
      {
        id: 'pet_promise',
        text: 'Stay calm and swear you will clean the cage',
        effects: { smarts: 3, happiness: 2, addFlag: 'pet_plea' },
        outcomeText: 'The grown-ups exchange a look. The words "we will see" hang in the air.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_first_friend',
    text: 'A kid at the park holds out half of their biscuit to you.',
    minAge: 5,
    maxAge: 9,
    weight: 75,
    tone: 'good',
    category: 'childhood',
    tags: ['friendship'],
    choices: [
      {
        id: 'friend_share',
        text: 'Break your biscuit in half and trade',
        effects: { happiness: 12, karma: 10 },
        outcomeText: 'From half a biscuit, a friendship is born.',
        tone: 'good',
      },
      {
        id: 'friend_keep',
        text: 'Nibble yours and pretend not to notice',
        effects: { happiness: -5 },
        outcomeText: 'You keep your biscuit. It tastes slightly less good.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_bully',
    text: 'The loud kid on the swings is demanding your snack money.',
    minAge: 7,
    maxAge: 12,
    weight: 65,
    tone: 'bad',
    category: 'childhood',
    choices: [
      {
        id: 'bully_give',
        text: 'Hand it over to avoid a scene',
        effects: { happiness: -8, money: -5 },
        outcomeText: 'The money is gone and the injustice follows you home.',
        tone: 'bad',
      },
      {
        id: 'bully_tell',
        text: 'March straight to a grown-up and tell them',
        effects: { happiness: 5, karma: 8 },
        outcomeText: 'The bully gets the talking-to. You feel the shift in the air.',
        tone: 'good',
      },
      {
        id: 'bully_stand',
        text: 'Stand your ground and puff up',
        effects: { health: -5, happiness: 10 },
        outcomeText: 'A scuffle, a scuffle. But you are standing, and that is what you will remember.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'child_lost_tooth',
    text: 'A tooth came out during dinner soup. Everyone cheered like you won a prize.',
    minAge: 5,
    maxAge: 8,
    weight: 95,
    tone: 'good',
    category: 'childhood',
    moment: 'sparkles',
    tags: ['milestone'],
    choices: [
      {
        id: 'tooth_pillow',
        text: 'Tuck it under the pillow and wait',
        effects: { happiness: 10, money: 12 },
        outcomeText: 'The night-time coin fairy leaves a surprising fortune under the pillow.',
        tone: 'good',
      },
      {
        id: 'tooth_cook',
        text: 'Try to glue it back into your mouth',
        effects: { smarts: -3, happiness: 6 },
        outcomeText: 'It does not work. But a new tooth is growing anyway, so who is the real winner?',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_library_card',
    text: 'The library lady hands you a card with your very own name on it.',
    minAge: 8,
    maxAge: 12,
    weight: 60,
    tone: 'good',
    category: 'childhood',
    tags: ['education'],
    choices: [
      {
        id: 'library_card_take',
        text: 'Borrow the biggest book you can carry',
        effects: { smarts: 9, happiness: 4 },
        outcomeText: 'You stagger home with a book twice your width. Worth it.',
        tone: 'good',
      },
      {
        id: 'library_card_picture',
        text: 'Just admire the card like a passport',
        effects: { happiness: 5 },
        outcomeText: 'It sits proudly in your pocket for a week before you remember what it is for.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_class_pet',
    text: 'The class rabbit has escaped its pen and is making a break for the door.',
    minAge: 6,
    maxAge: 10,
    weight: 55,
    tone: 'funny',
    category: 'childhood',
    choices: [
      {
        id: 'classpet_catch',
        text: 'Dive to block the escape route',
        effects: { happiness: 8, health: -2 },
        outcomeText: 'You tumble, you grab, you win. The rabbit glares at you.',
        tone: 'funny',
      },
      {
        id: 'classpet_bribe',
        text: 'Offer a leaf from your lunch as a peace offering',
        effects: { smarts: 2, happiness: 4 },
        outcomeText: 'The rabbit pauses for the leaf and is gently captured. Diplomacy wins the day.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_marbles',
    text: 'Aleem da shows off a pouch full of shiny marbles at recess.',
    minAge: 7,
    maxAge: 11,
    weight: 50,
    tone: 'neutral',
    category: 'childhood',
    choices: [
      {
        id: 'marbles_play',
        text: 'Challenge him to a round for keeps',
        effects: { money: 15, smarts: 3 },
        outcomeText: 'You walk away richer by three marbles and one very confused opponent.',
        tone: 'good',
      },
      {
        id: 'marbles_watch',
        text: 'Just watch the technique carefully',
        effects: { smarts: 5 },
        outcomeText: 'You study the flick of the thumb like a scholar. One day, those marbles are yours.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_health_kick',
    text: 'The after-school running club is forming. Coach looks at you expectantly.',
    minAge: 8,
    maxAge: 12,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['health'],
    choices: [
      {
        id: 'health_kick_join',
        text: 'Join and huff around the track',
        effects: { health: 8, happiness: 5 },
        outcomeText: 'You are slower than the gate, but faster than last week. Progress!',
        tone: 'good',
      },
      {
        id: 'health_kick_sit',
        text: 'Stay and draw in the shade',
        effects: { smarts: 4 },
        outcomeText: 'The runners puff past while you sketch. Different race, same track.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_got_pet',
    text: 'After all that patient asking, a tiny grey hamster now rules the living room.',
    minAge: 5,
    maxAge: 12,
    weight: 40,
    tone: 'good',
    category: 'childhood',
    tags: ['family', 'pet'],
    requiredFlags: ['pet_plea'],
    choices: [
      {
        id: 'gotpet_name',
        text: 'Name it Crumbs and swear loyalty forever',
        effects: { happiness: 14, karma: 5 },
        outcomeText: 'Crumbs immediately escapes under the sofa. Loyalty remains unwavering.',
        tone: 'funny',
      },
      {
        id: 'gotpet_cage',
        text: 'Build an elaborate obstacle-course cage',
        effects: { smarts: 6, happiness: 6 },
        outcomeText: 'Crumbs ignores every tunnel but sits in the food bowl. Engineering is its own reward.',
        tone: 'neutral',
      },
    ],
  },
];