import type { LifeEventDef } from '@/lib/engine/types';

export const CHILDHOOD_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'toddler_first_words',
    text: 'You are buzzing around the living room when your first real word slips out.',
    minAge: 1,
    maxAge: 2,
    weight: 90,
    tone: 'good',
    category: 'childhood',
    moment: 'confetti',
    tags: ['milestone'],
    choices: [
      {
        id: 'first_words_ma',
        text: 'Grin and say "Ma! Ma!"',
        effects: { happiness: 12, health: 2 },
        outcomeText: 'Someone scoops you up and you feel like the most clever person in the world.',
        tone: 'good',
      },
      {
        id: 'first_words_no',
        text: 'Say "No!" at the exact wrong moment',
        effects: { happiness: 5, smarts: 3 },
        outcomeText: 'Everyone laughs, and you file that power away for future use.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'toddler_tantrum',
    text: 'The cookie jar is on the top shelf. The whole universe is unfair right now.',
    minAge: 2,
    maxAge: 4,
    weight: 85,
    tone: 'bad',
    category: 'childhood',
    tags: ['milestone'],
    choices: [
      {
        id: 'tantrum_floor',
        text: 'Go limp and wail like a tiny siren',
        effects: { happiness: 5, smarts: -2 },
        outcomeText: 'It works for a while, then you nearly get put in the kitchen chair of shame.',
        tone: 'funny',
      },
      {
        id: 'tantrum_breathe',
        text: 'Take a big breath and point at what you want',
        effects: { smarts: 4, happiness: 3 },
        outcomeText: 'The grown-ups act like you just solved a maze. Fine, you will take it.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_pet_wish',
    text: 'You have decided: the family needs a hamster. There is no other option.',
    minAge: 4,
    maxAge: 7,
    weight: 60,
    tone: 'neutral',
    category: 'childhood',
    tags: ['family'],
    choices: [
      {
        id: 'pet_beg',
        text: 'Ask every single day until someone caves',
        effects: { happiness: 8, smarts: -2 },
        outcomeText: 'Your campaign has officially begun. Notes are being left on the fridge.',
        tone: 'funny',
      },
      {
        id: 'pet_promise',
        text: 'Stay calm and swear you will clean the cage',
        effects: { smarts: 3, happiness: 2, addFlag: 'pet_plea' },
        outcomeText: 'The grown-ups exchange a look. The words "we will see" hang in the air.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_first_friend',
    text: 'A kid at the park holds out half of their biscuit to you.',
    minAge: 5,
    maxAge: 9,
    weight: 75,
    tone: 'good',
    category: 'childhood',
    tags: ['friendship'],
    choices: [
      {
        id: 'friend_share',
        text: 'Break your biscuit in half and trade',
        effects: { happiness: 12, karma: 10 },
        outcomeText: 'From half a biscuit, a friendship is born.',
        tone: 'good',
      },
      {
        id: 'friend_keep',
        text: 'Nibble yours and pretend not to notice',
        effects: { happiness: -5 },
        outcomeText: 'You keep your biscuit. It tastes slightly less good.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_bully',
    text: 'The loud kid on the swings is demanding your snack money.',
    minAge: 7,
    maxAge: 12,
    weight: 65,
    tone: 'bad',
    category: 'childhood',
    choices: [
      {
        id: 'bully_give',
        text: 'Hand it over to avoid a scene',
        effects: { happiness: -8, money: -5 },
        outcomeText: 'The money is gone and the injustice follows you home.',
        tone: 'bad',
      },
      {
        id: 'bully_tell',
        text: 'March straight to a grown-up and tell them',
        effects: { happiness: 5, karma: 8 },
        outcomeText: 'The bully gets the talking-to. You feel the shift in the air.',
        tone: 'good',
      },
      {
        id: 'bully_stand',
        text: 'Stand your ground and puff up',
        effects: { health: -5, happiness: 10 },
        outcomeText: 'A scuffle, a scuffle. But you are standing, and that is what you will remember.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'child_lost_tooth',
    text: 'A tooth came out during dinner soup. Everyone cheered like you won a prize.',
    minAge: 5,
    maxAge: 8,
    weight: 95,
    tone: 'good',
    category: 'childhood',
    moment: 'sparkles',
    tags: ['milestone'],
    choices: [
      {
        id: 'tooth_pillow',
        text: 'Tuck it under the pillow and wait',
        effects: { happiness: 10, money: 12 },
        outcomeText: 'The night-time coin fairy leaves a surprising fortune under the pillow.',
        tone: 'good',
      },
      {
        id: 'tooth_cook',
        text: 'Try to glue it back into your mouth',
        effects: { smarts: -3, happiness: 6 },
        outcomeText: 'It does not work. But a new tooth is growing anyway, so who is the real winner?',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_library_card',
    text: 'The library lady hands you a card with your very own name on it.',
    minAge: 8,
    maxAge: 12,
    weight: 60,
    tone: 'good',
    category: 'childhood',
    tags: ['education'],
    choices: [
      {
        id: 'library_card_take',
        text: 'Borrow the biggest book you can carry',
        effects: { smarts: 9, happiness: 4 },
        outcomeText: 'You stagger home with a book twice your width. Worth it.',
        tone: 'good',
      },
      {
        id: 'library_card_picture',
        text: 'Just admire the card like a passport',
        effects: { happiness: 5 },
        outcomeText: 'It sits proudly in your pocket for a week before you remember what it is for.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_class_pet',
    text: 'The class rabbit has escaped its pen and is making a break for the door.',
    minAge: 6,
    maxAge: 10,
    weight: 55,
    tone: 'funny',
    category: 'childhood',
    choices: [
      {
        id: 'classpet_catch',
        text: 'Dive to block the escape route',
        effects: { happiness: 8, health: -2 },
        outcomeText: 'You tumble, you grab, you win. The rabbit glares at you.',
        tone: 'funny',
      },
      {
        id: 'classpet_bribe',
        text: 'Offer a leaf from your lunch as a peace offering',
        effects: { smarts: 2, happiness: 4 },
        outcomeText: 'The rabbit pauses for the leaf and is gently captured. Diplomacy wins the day.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_marbles',
    text: 'Aleem da shows off a pouch full of shiny marbles at recess.',
    minAge: 7,
    maxAge: 11,
    weight: 50,
    tone: 'neutral',
    category: 'childhood',
    choices: [
      {
        id: 'marbles_play',
        text: 'Challenge him to a round for keeps',
        effects: { money: 15, smarts: 3 },
        outcomeText: 'You walk away richer by three marbles and one very confused opponent.',
        tone: 'good',
      },
      {
        id: 'marbles_watch',
        text: 'Just watch the technique carefully',
        effects: { smarts: 5 },
        outcomeText: 'You study the flick of the thumb like a scholar. One day, those marbles are yours.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_health_kick',
    text: 'The after-school running club is forming. Coach looks at you expectantly.',
    minAge: 8,
    maxAge: 12,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['health'],
    choices: [
      {
        id: 'health_kick_join',
        text: 'Join and huff around the track',
        effects: { health: 8, happiness: 5 },
        outcomeText: 'You are slower than the gate, but faster than last week. Progress!',
        tone: 'good',
      },
      {
        id: 'health_kick_sit',
        text: 'Stay and draw in the shade',
        effects: { smarts: 4 },
        outcomeText: 'The runners puff past while you sketch. Different race, same track.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_got_pet',
    text: 'After all that patient asking, a tiny grey hamster now rules the living room.',
    minAge: 5,
    maxAge: 12,
    weight: 40,
    tone: 'good',
    category: 'childhood',
    tags: ['family', 'pet'],
    requiredFlags: ['pet_plea'],
    choices: [
      {
        id: 'gotpet_name',
        text: 'Name it Crumbs and swear loyalty forever',
        effects: { happiness: 14, karma: 5 },
        outcomeText: 'Crumbs immediately escapes under the sofa. Loyalty remains unwavering.',
        tone: 'funny',
      },
      {
        id: 'gotpet_cage',
        text: 'Build an elaborate obstacle-course cage',
        effects: { smarts: 6, happiness: 6 },
        outcomeText: 'Crumbs ignores every tunnel but sits in the food bowl. Engineering is its own reward.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_giant_puddle',
    text: 'Rain built a lake across the path and you have been consulted on its majesty.',
    minAge: 2,
    maxAge: 7,
    weight: 50,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'puddle_stomp',
        text: 'Stomp through it with total commitment',
        effects: { happiness: 10, money: -2, health: -1 },
        outcomeText: 'Every splash is a victory. Your socks file a protest.',
        tone: 'funny',
      },
      {
        id: 'puddle_measure',
        text: 'Measure the depth with a stick, scientifically',
        effects: { smarts: 4, happiness: 3 },
        outcomeText: 'The data is conclusive: it is very deep, about 1 stick plus a bit.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_kite_war',
    text: 'Someone\'s kite has looped yours mid-air in a classic sky duel.',
    minAge: 6,
    maxAge: 11,
    weight: 45,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune', 'friendship'],
    choices: [
      {
        id: 'kite_duel',
        text: 'Jig the line and try to cut the thief',
        effects: { happiness: 8, smarts: 2 },
        outcomeText: 'The two kites dance, tangle, and finally crash-land side by side.',
        tone: 'funny',
      },
      {
        id: 'kite_share',
        text: 'Tie the lines together and make one giant kite',
        effects: { smarts: 4, happiness: 6 },
        outcomeText: 'Physics argues, friendship wins, and the giant kite lumbers gloriously.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_sports_day',
    text: 'Sports day has everyone in frantic bibs. The egg-and-spoon awaits its champion.',
    minAge: 7,
    maxAge: 12,
    weight: 45,
    tone: 'neutral',
    category: 'childhood',
    tags: ['sports'],
    choices: [
      {
        id: 'sportsday_run',
        text: 'Run the sprint with maximum seriousness',
        effects: { health: 3, happiness: 5, looks: 2 },
        outcomeText: 'You come third and celebrate like a podium finish. Correct behaviour.',
        tone: 'good',
      },
      {
        id: 'sportsday_egg',
        text: 'Focus the whole day on the egg-and-spoon',
        effects: { smarts: 3, happiness: 4 },
        outcomeText: 'The egg survives. You collect the ribbon and the marble of glory.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_scary_show',
    text: 'You watched a show that was slightly too grown-up and the closet now watches you back.',
    minAge: 3,
    maxAge: 8,
    weight: 40,
    tone: 'bad',
    category: 'childhood',
    tags: ['fortune', 'family'],
    choices: [
      {
        id: 'scary_lamp',
        text: 'Insist the lamp stays on all night',
        effects: { happiness: 5, health: 2 },
        outcomeText: 'The lamp wins the argument. So does sleep. Everyone wins except the monster.',
        tone: 'neutral',
      },
      {
        id: 'scary_hum',
        text: 'Hum a brave song until you fall asleep',
        effects: { happiness: 4, karma: 2 },
        outcomeText: 'The song becomes your family\'s private anthem for brave nights.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'toddler_baby_dance',
    text: 'A song comes on and your body decides, independently, to compose a dance.',
    minAge: 0,
    maxAge: 3,
    weight: 75,
    tone: 'good',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'babydance_full',
        text: 'Commit to the full choreography, hips included',
        effects: { happiness: 10, health: 1 },
        outcomeText: 'The audience (two adults and a lamp) gives you a standing ovation.',
        tone: 'good',
      },
      {
        id: 'babydance_shy',
        text: 'Sway politely, one foot only',
        effects: { happiness: 4 },
        outcomeText: 'A restrained, dignified performance. The lamp still claps.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'toddler_mud_cake',
    text: 'The garden mud is at peak quality and a birthday cake clearly must be made.',
    minAge: 2,
    maxAge: 5,
    weight: 55,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'mudcake_chef',
        text: 'Fire the whole kitchen: mud, leaves, glitter',
        effects: { happiness: 8, karma: 2 },
        outcomeText: 'The cake is a masterpiece of questionable ingredients.',
        tone: 'funny',
      },
      {
        id: 'mudcake_science',
        text: 'Test which mud holds a perfect pinch',
        effects: { smarts: 4 },
        outcomeText: 'Your soil research earns you two commendations and one hosed-down outfit.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_dino_museum',
    text: 'The museum has a dinosaur skeleton so tall it has its own room and audience.',
    minAge: 4,
    maxAge: 10,
    weight: 50,
    tone: 'good',
    category: 'childhood',
    tags: ['education'],
    choices: [
      {
        id: 'dino_stare',
        text: 'Stare up at it for a very long time',
        effects: { happiness: 6, smarts: 3 },
        outcomeText: 'The skeleton stares back, geologically. A mutual respect.',
        tone: 'good',
      },
      {
        id: 'dino_dictate',
        text: 'Give the whole class a confident lecture on it',
        effects: { smarts: 4, fame: 2 },
        outcomeText: 'Half the facts are yours; half are freshly invented. All are delivered.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_braids',
    text: 'For picture day, someone is attempting a hairstyle that requires far more patience than exists.',
    minAge: 5,
    maxAge: 10,
    weight: 45,
    tone: 'neutral',
    category: 'childhood',
    tags: ['looks'],
    choices: [
      {
        id: 'braids_hold',
        text: 'Hold still and let it happen',
        effects: { looks: 4, happiness: 2 },
        outcomeText: 'The braids are uneven and the photos are charming. Both true.',
        tone: 'good',
      },
      {
        id: 'braids_pull',
        text: 'Fidget through the whole ordeal',
        effects: { looks: -2, happiness: 3 },
        outcomeText: 'The final look is best described as "won the fight with the mirror".',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_coin_under_cushion',
    text: 'Your hand, exploring a sofa cushion, encounters a coin that nobody has claimed.',
    minAge: 4,
    maxAge: 9,
    weight: 45,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'cushion_coin_keep',
        text: 'Claim it loudly as treasure',
        effects: { money: 4, happiness: 4 },
        outcomeText: 'A rare, legitimate windfall. You spend it with extreme ceremony.',
        tone: 'funny',
      },
      {
        id: 'cushion_coin_ask',
        text: 'Hand it over to the cushion\'s owner',
        effects: { karma: 5, happiness: 2 },
        outcomeText: 'You are declared "the honest one" in the kitchen. A title is born.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_sick_day_tv',
    text: 'A fever excuses you from school for a day and grants access to the daytime TV the adults hide.',
    minAge: 4,
    maxAge: 10,
    weight: 45,
    tone: 'neutral',
    category: 'childhood',
    tags: ['health'],
    choices: [
      {
        id: 'sickday_rest',
        text: 'Sip warm drinks and sleep it off',
        effects: { health: 6, happiness: 2 },
        outcomeText: 'By evening the fever has retreated and the soup has won.',
        tone: 'good',
      },
      {
        id: 'sickday_marathon',
        text: 'Binge every show the grown-ups usually forbid',
        effects: { happiness: 8, health: -3 },
        outcomeText: 'Magnificent television. The cough returns promptly to complain.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_marker_hands',
    text: 'Someone left washable markers in reach and your hands are currently two glorious colours.',
    minAge: 2,
    maxAge: 6,
    weight: 45,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'markers_masterpiece',
        text: 'Turn the whole arm into a masterpiece',
        effects: { happiness: 8, smarts: 2 },
        outcomeText: 'The arm is declared "permanent museum art" until the bath.',
        tone: 'funny',
      },
      {
        id: 'markers_one_colour',
        text: 'Pick one colour and go deep with it',
        effects: { happiness: 5, smarts: 1 },
        outcomeText: 'A single confident shade, applied with scholarly seriousness.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_treehouse',
    text: 'A tree in the garden has a platform being built, and your opinion has been formally requested.',
    minAge: 7,
    maxAge: 12,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['family', 'home'],
    choices: [
      {
        id: 'treehouse_design',
        text: 'Help design it, with a flag and a rope ladder',
        effects: { smarts: 5, happiness: 6 },
        outcomeText: 'The flag goes up Thursday. The rope ladder is used strictly by cats.',
        tone: 'good',
      },
      {
        id: 'treehouse_observer',
        text: 'Supervise the build from the kitchen window',
        effects: { happiness: 4, smarts: 2 },
        outcomeText: 'A supervisor with a good biscuit budget. Engineering proceeds.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_speed_corners',
    text: 'The school corridor has a hairpin bend and a reputation: the fastest walkers take it at speed.',
    minAge: 6,
    maxAge: 11,
    weight: 45,
    tone: 'funny',
    category: 'childhood',
    tags: ['school'],
    choices: [
      {
        id: 'speedcorner_lean',
        text: 'Lean into it like a racing driver',
        effects: { happiness: 7, health: -1 },
        outcomeText: 'A clean line, a near-miss with a plant pot, absolute glory.',
        tone: 'funny',
      },
      {
        id: 'speedcorner_watch',
        text: 'Watch the champions and take notes',
        effects: { smarts: 3 },
        outcomeText: 'You study the technique. Someday, the bend will be yours.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_old_photo',
    text: 'Your parents pull out a photo album and the room goes quiet with the past.',
    minAge: 6,
    maxAge: 12,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['family'],
    choices: [
      {
        id: 'oldphoto_ask',
        text: 'Ask about every single photo',
        effects: { smarts: 3, happiness: 6, karma: 2 },
        outcomeText: 'Two hours of stories. The album is now your mental furniture.',
        tone: 'good',
      },
      {
        id: 'oldphoto_copy',
        text: 'Copy your favourite photo to keep in your room',
        effects: { happiness: 5 },
        outcomeText: 'A small frame, a small face, a great inheritance.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_science_question',
    text: 'A question explodes in your head: why is the sky that colour and who decided.',
    minAge: 5,
    maxAge: 10,
    weight: 45,
    tone: 'neutral',
    category: 'childhood',
    tags: ['education'],
    choices: [
      {
        id: 'why_ask',
        text: 'Ask every adult you know until one answers',
        effects: { smarts: 6, karma: 1 },
        outcomeText: 'The answers differ, but the last one finally makes sense. You file it away.',
        tone: 'good',
      },
      {
        id: 'why_invent',
        text: 'Invent a satisfying answer of your own',
        effects: { smarts: 4, happiness: 2 },
        outcomeText: 'Your theory is elegant and totally unsupported. It will be corrected. Gently.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_paper_boat',
    text: 'A folded paper boat sails down the rain gutter and all of physics stands briefly on your side.',
    minAge: 4,
    maxAge: 9,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'paperboat_chase',
        text: 'Chase it to the drain and back again',
        effects: { happiness: 7, health: -1 },
        outcomeText: 'Wet socks, a rescued boat, a legendary voyage.',
        tone: 'funny',
      },
      {
        id: 'paperboat_fleet',
        text: 'Fold three more and launch an armada',
        effects: { smarts: 4, happiness: 4 },
        outcomeText: 'The fleet crosses the puddle. One is lost at sea. Ceremony held.',
        tone: 'neutral',
      },
    ],
  },
];