import type { LifeEventDef } from '@/lib/engine/types';

export const CHILDHOOD_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'toddler_first_words',
    text: 'তুই ড্রয়িংরুমে হামাগুড়ি দিয়া ঘুইরা বেড়াসতাছোস, আর হঠাৎ তোর মুখ দিয়া মেইন ডায়লগ বাইর হইয়া গেলো!',
    minAge: 1,
    maxAge: 2,
    weight: 90,
    tone: 'good',
    category: 'childhood',
    moment: 'confetti',
    tags: ['milestone'],
    choices: [
      {
        id: 'first_words_ma',
        text: 'দাঁত কেল্লায়া ক: "মা! মা!"',
        effects: { happiness: 12, health: 2 },
        outcomeText: 'আম্মা তোরে কোলে তুইলা এমন চটকানি দিলো, তোর মনে হইলো তুই এই দুনিয়ার সবচেয়ে চালাক বান্দর!',
        tone: 'good',
      },
      {
        id: 'first_words_no',
        text: 'সবাইরে থমকায়া দিয়া ক: "না! দিমু না!"',
        effects: { happiness: 5, smarts: 3 },
        outcomeText: 'সবাই হাসতে হাসতে কাইত! তুই বুঝলি যে এই "না" বলার পাওয়ার দিয়া ফিউচারে সবার বারোটা বাজানো যাইবো।',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'toddler_tantrum',
    text: 'কোৌটার বিস্কুট রাখছে উঁচুতে! তোর এহন মনে হইতাছে পুরা মহাবিশ্ব তোর লগে বাটপারি করতাছে!',
    minAge: 2,
    maxAge: 4,
    weight: 85,
    tone: 'bad',
    category: 'childhood',
    tags: ['milestone'],
    choices: [
      {
        id: 'tantrum_floor',
        text: 'ফ্লোরে শুইয়া ফাইট্টা যাওয়া মাইকের লাহান হোগুড়া কান্দন শুরু কর!',
        effects: { happiness: 5, smarts: -2 },
        outcomeText: 'কান্দন দেইখা কিছু সময় ডরের চোটে বিস্কুট দিলেও, পরে তোরে দিয়া ঘরের সব থালা-বাসন ধোয়াইছে!',
        tone: 'funny',
      },
      {
        id: 'tantrum_breathe',
        text: 'দীর্ঘ শ্বাস ফালায়া বিস্কুটের দিকে আঙ্গুল তুইলা ধমক দে!',
        effects: { smarts: 4, happiness: 3 },
        outcomeText: 'বড়রা ভাবলো তুই আইনস্টাইনের হালাতো ভাই! তোরে বিস্কুট দিয়া দিল, বাটপারির প্রথম জয়!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_pet_wish',
    text: 'তোর ব্রেনে পোকা ঢুকছে: ফ্যামিলিতে একখান ইঁদুর মার্কা হ্যামস্টার আনাই লাগবো, নাইলে তুই জীবন ফালায়া দিবি!',
    minAge: 4,
    maxAge: 7,
    weight: 60,
    tone: 'neutral',
    category: 'childhood',
    tags: ['family'],
    choices: [
      {
        id: 'pet_beg',
        text: 'প্রতিদিন কুত্তার লাহান গ্যানগ্যান কইরা মাথা খাইয়া ফ্যাল!',
        effects: { happiness: 8, smarts: -2 },
        outcomeText: 'তোর জ্বালায় ফ্রিজের গায়ে চিপা কাগজের নোট লাগায়া রাখছে, "এই বান্দরের বাচ্চা শান্ত কর!"',
        tone: 'funny',
      },
      {
        id: 'pet_promise',
        text: 'কসম কাইটা ক: "আমি নিজে ওর গু-মুত সাফ করুম!"',
        effects: { smarts: 3, happiness: 2, addFlag: 'pet_plea' },
        outcomeText: 'বড়রা মুখ বাঁকা কইরা তাকাইলো। বাতাসে খালি ভাসতাছে "দেখা যাইবো সুম্মা"! ফাপড় নিতাছোস খালি!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_first_friend',
    text: 'পার্কে খাড়াইয়া এক ফইন্নি পোলা তার আধা খাওয়া বিস্কুট তোর দিকে বাড়াইয়া দিল!',
    minAge: 5,
    maxAge: 9,
    weight: 75,
    tone: 'good',
    category: 'childhood',
    tags: ['friendship'],
    choices: [
      {
        id: 'friend_share',
        text: 'নিজের বিস্কুট ভাইঙ্গা তার লগে এক্সচেঞ্জ কর!',
        effects: { happiness: 12, karma: 10 },
        outcomeText: 'আধা খাওয়া বিস্কুট দিয়া লাইফের পয়লা দোস্ত পাইলি! তোরা দুইজনে মিক্সড বিস্কুট খায়া দিল খুশ!',
        tone: 'good',
      },
      {
        id: 'friend_keep',
        text: 'নিজের বিস্কুট চাবাইয়া খাইয়া তার দিকে তাকিয়ে ভেংচি কাটো!',
        effects: { happiness: -5 },
        outcomeText: 'তুই তোর বিস্কুট রাখলি, কিন্তু পোলার অভিশাপে বিস্কুটটা তোর গলায় আটকাইয়া যাওয়ার দশা!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_bully',
    text: 'দোলনার কাছে পাড়ার এক মাস্তান পোলা আইসা তোর টিফিনের ট্যাকা চাঁদা চাইছে!',
    minAge: 7,
    maxAge: 12,
    weight: 65,
    tone: 'bad',
    category: 'childhood',
    choices: [
      {
        id: 'bully_give',
        text: 'ডরে প্যান্টে মুইতা দিয়া ট্যাকা তুইল্যা দে!',
        outcomeText: 'ট্যাকা গেল গিয়া, আর মাস্তান পোলা তোরে সারাজীবনের মতো "ভিখারি" বানায়া রাখলো!',
        tone: 'bad',
         effects: { happiness: -5, money: -10, karma: -2},
      },
      {
        id: 'bully_tell',
        text: 'দৌড়াইয়া গিয়া স্যারের কাছে নালিশ ঠুকে দে!',
        outcomeText: 'স্যার আইসা মাস্তান পোলার কান এমুন মলা দিলো, হালা কাইন্দা দিলের শান্তি দিল!',
        tone: 'good',
        effects: { happiness: 5, karma: 3 },
      },
      {
        id: 'bully_stand',
        text: 'বুক ফুলাইয়া ফাপড় নে: "চিনস আমারে?"',
        outcomeText: 'মাস্তান পোলা এক থাপ্পড়ে তোর নাক ফাটায়া দিলো! তুই রক্ত মুছতে মুছতে বাড়ি গেলি!',
        tone: 'bad',
        effects: { happiness: -5, health: -3, karma: -1 },
      },
    ],
  },
  {
    id: 'child_lost_tooth',
    text: 'রাতের বেলা খাসির মাংস খাইতে গিয়া তোর একটা আস্ত দাঁত খুইসা পইড়্যা গেছে! সবাই ফালতাছে!',
    minAge: 5,
    maxAge: 8,
    weight: 95,
    tone: 'good',
    category: 'childhood',
    moment: 'sparkles',
    tags: ['milestone'],
    choices: [
      {
        id: 'tooth_pillow',
        text: 'দাঁত বালিশের তলে রাইখা ঘুমায় যা!',
        effects: { happiness: 10, money: 12 },
        outcomeText: 'সকালে উইঠা দেখস টিনের ফেয়ারি আইসা ৫০ ট্যাকা রাইখা গেছে! বাপের পকেট খালি!',
        tone: 'good',
      },
      {
        id: 'tooth_cook',
        text: 'আঠা দিয়া দাঁত আবার পাড়ার মইধ্যে লাগানোর ট্রাই কর!',
        effects: { smarts: -3, happiness: 6 },
        outcomeText: 'কাম কাজ হয় নাই, উল্টা আঠা জাইম্মা তোর মুখ জিপার দিয়া আটকানোর লাহান হইয়া গেছে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_library_card',
    text: 'লাইব্রেরির আন্টি তোরে একখানা কার্ড ধরাইয়া দিছে, যেটার উপ্রে তোর আঁকাবাঁকা নামে লেখা!',
    minAge: 8,
    maxAge: 12,
    weight: 60,
    tone: 'good',
    category: 'childhood',
    tags: ['education'],
    choices: [
      {
        id: 'library_card_take',
        text: 'ডাইনোসরের ওপর একটা বিশাল মোটা বই কান্ধে নিয়া আয়!',
        effects: { smarts: 9, happiness: 4 },
        outcomeText: 'বইয়ের ওজনে তোর পিঠ বাঁকা হইয়া গেছে! তুই এহন জ্যান্ত কুঁজো বুইড়া!',
        tone: 'good',
      },
      {
        id: 'library_card_picture',
        text: 'পাসপোর্টের লাহান পকেটে রাইখা ভাব মার!',
        effects: { happiness: 5 },
        outcomeText: 'পকেটে রাইখা পইচা গেছে, তুই ভুলেই গেছস এইটা দিয়া বই আনন লাগে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_class_pet',
    text: 'স্কুলের ক্লাসের খরগোশডা জেলখানা (খাঁচা) ফাইট্টা বারিঙ্গার রোডে দৌড় মারছে!',
    minAge: 6,
    maxAge: 10,
    weight: 55,
    tone: 'funny',
    category: 'childhood',
    choices: [
      {
        id: 'classpet_catch',
        text: 'সুপারম্যান সাইজা খরগোশের উপ্রে ডাইভ দে!',
        effects: { happiness: 8, health: -2 },
        outcomeText: 'খরগোশ ধরছস ঠিকই, কিন্তু খরগোশ তোর ঠোঁটে এমুন এক কামড় দিছে, তুই কাইন্দা দিছস!',
        tone: 'funny',
      },
      {
        id: 'classpet_bribe',
        text: 'টিফিনের পচা মলাণ রুটি দিয়া লোভ দেখা!',
        outcomeText: 'রুটি দেইখা খরগোশ নিজেই ধরা দিছে! কূটনীতি কামে দিছে হালায়!',
        tone: 'good',
        effects: { happiness: 5, smarts: 3 },
      },
    ],
  },
  {
    id: 'child_marbles',
    text: 'আলেম দা টিফিনের টাইমে পকেট থিকা চকচকা মার্বেল বাইর কইরা ফুটানি মারতাছে!',
    minAge: 7,
    maxAge: 11,
    weight: 50,
    tone: 'neutral',
    category: 'childhood',
    choices: [
      {
        id: 'marbles_play',
        text: 'চ্যালেঞ্জ দিয়া মার্বেল মারার খেলা শুরু কর!',
        effects: { money: 15, smarts: 3 },
        outcomeText: 'আলেম দার সব মার্বেল জিতা নিলি! হালায় কাইন্দা দিয়া বাড়ি দৌড় দিছে, তুই মহল্লার মার্বেল ডন!',
        tone: 'good',
      },
      {
        id: 'marbles_watch',
        text: 'চোখ বড় বড় কইরা আতেলের লাহান টেকনিক শিখ!',
        effects: { smarts: 5 },
        outcomeText: 'টেকনিক শিখছস, বাট পরের দিন তোর নিজের মার্বেলগুলাই ড্রেনে পইড়া গেছে!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_health_kick',
    text: 'স্কুলের কোচ আইসা তোরে দৌড় প্রতিযোগিতা নামায়া দিছে। তোর ভুঁড়ি দেইখা সবাই হাসে!',
    minAge: 8,
    maxAge: 12,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['health'],
    choices: [
      {
        id: 'health_kick_join',
        text: 'হাঁপাইতে হাঁপাইতে ট্র্যাকের চারপাশ ঘুরে আয়!',
        effects: { health: 8, happiness: 5 },
        outcomeText: 'ঘামে জাবিজাবি হইয়া শেষ পর্যন্ত ফিনিশিং লাইনে পৌঁছাইলি। কুকুরও তোর পিছে দৌড়াইছে!',
        tone: 'good',
      },
      {
        id: 'health_kick_sit',
        text: 'দৌড় বাদ দিয়া গাছের ছায়ায় বইসা ছবি আঁক!',
        effects: { smarts: 4 },
        outcomeText: 'পোলাপাইন যখন দৌড়ায়া হাপায়, তুই তখন মগজ খাটাইয়া কোচের একটা ফানি কার্টুন আঁইকা ফেললি!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_got_pet',
    text: 'রক্ত পানি করা কান্দাকান্দির পর অবশেষে বাসায় একখান হ্যামস্টার আইছে!',
    minAge: 5,
    maxAge: 12,
    weight: 40,
    tone: 'good',
    category: 'childhood',
    tags: ['family', 'pet'],
    requiredFlags: ['pet_plea'],
    choices: [
      {
        id: 'gotpet_name',
        text: 'নাম রাখলি "ক্রাম্বস" আর জিন্দেগির কসম কাটলি!',
        effects: { happiness: 14, karma: 5 },
        outcomeText: 'ক্রাম্বস সোফারে কাইটা তক্তা বানায়া দিছে! তোর কসম খাতার খাতাতেই রইয়া গেলো!',
        tone: 'funny',
      },
      {
        id: 'gotpet_cage',
        text: 'তার কাটাইয়া বিশাল অবস্টাকল কোর্স বানা!',
        effects: { smarts: 6, happiness: 6 },
        outcomeText: 'ইঞ্জিনিয়ারিং কইরা খাঁচা বান্দস, কিন্তু হ্যামস্টার সব টপקাইয়া সোজা গিয়ে তোর জুতার মইধ্যে হাগু কইরা দিছে!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_giant_puddle',
    text: 'বৃষ্টির পানিতে রাস্তা পুরা সাগরের রূপ নিছে! তুই এহন বিশেষজ্ঞ মারেক লেন্স!',
    minAge: 2,
    maxAge: 7,
    weight: 50,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'puddle_stomp',
        text: 'পচা কাদার সাগরে উরাধুরা ডাইভ মার!',
        effects: { happiness: 10, money: -2, health: -1 },
        outcomeText: 'কাদা মাখামাখি হইয়া তুই যখন উঠলি, মাইনষে ভাবলো তুই ড্রেনের ড্রাকুলা! মোজার বারোটা বাজছে!',
        tone: 'funny',
      },
      {
        id: 'puddle_measure',
        text: 'সৈনিক সাইজা লাঠি দিয়া গভীরতা মাপ!',
        effects: { smarts: 4, happiness: 3 },
        outcomeText: 'ডেটা পাইলি: গভীরতা এক লাঠি সমান! তুই খুশি হইয়া ওই লাঠিটাই চাবাইতে শুরু করলি!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_kite_war',
    text: 'ছাদে ঘুড়ি ওড়াইতে গিয়া তোর সুতা আরেক ফাজিলের ঘুড়ির লগে প্যাঁচ খাইয়া গেছে!',
    minAge: 6,
    maxAge: 11,
    weight: 45,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune', 'friendship'],
    choices: [
      {
        id: 'kite_duel',
        text: 'জোরে হ্যাঁচকা টান মাইরা হালার ঘুড়ি কাইট্যা দে!',
        effects: { happiness: 8, smarts: 2 },
        outcomeText: 'ভোকাট্টা চিল্লাইয়া তুই যখন নাচতাছোস, তোর নিজের সুতাও কাইটা গিয়া পাশের বাসার আন্টির চুলে পেঁচায়া গেলো!',
        tone: 'funny',
      },
      {
        id: 'kite_share',
        text: 'দুইটা সুতা বাইন্ধা এক মহা-ঘুড়ি বানা!',
        effects: { smarts: 4, happiness: 6 },
        outcomeText: 'ফিজিক্সের গুষ্টি কিলাইয়া সেই ঘুড়ি আকাশে উইড়া সোজা গিয়া ট্রান্সফরমার লাইনে পইড়া শর্টসার্কিট!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_sports_day',
    text: 'স্পোর্টস ডে! চামচে ডিম রাইয়া দৌড়ানোর লাইগা তুই এহন রেডি!',
    minAge: 7,
    maxAge: 12,
    weight: 45,
    tone: 'neutral',
    category: 'childhood',
    tags: ['sports'],
    choices: [
      {
        id: 'sportsday_run',
        text: 'অলিম্পিকের স্প্রিন্টারের লাহান দৌড় দে!',
        effects: { health: 3, happiness: 5, looks: 2 },
        outcomeText: 'দৌড়াইতে গিয়া তুই এমন আছাড় খাস যে তুই ৩য় হইছোস, তয় তোর হাঁটু ছিলা রক্তারক্তি!',
        tone: 'good',
      },
      {
        id: 'sportsday_egg',
        text: 'ডিম বাচাইয়া রোবটের লাহান হাঁটা শুরু কর!',
        effects: { smarts: 3, happiness: 4 },
        outcomeText: 'ডিম বাঁচছে ঠিকই, কিন্তু তুই সবার লাস্টে ফিনিশ করছোস! সবাই তোরে দেইখা হাততালি দিছে!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_scary_show',
    text: 'রাতদুপুরে একটু বড়দের হরর মুভি দেখছোস, এহন ঘরের অন্ধকার আলমারি তোর দিকে তাকায়া হাসতাছে!',
    minAge: 3,
    maxAge: 8,
    weight: 40,
    tone: 'bad',
    category: 'childhood',
    tags: ['fortune', 'family'],
    choices: [
      {
        id: 'scary_lamp',
        text: 'ভয়ে চান্দি গরম হইয়া সারারাত লাইট জ্বেলে রাখ!',
        effects: { happiness: 5, health: 2 },
        outcomeText: 'সকালে কারেন্টের বিল দেইখা আব্বু এমন এক চড় দিলো যে হরর মুভির ভূত মাথা থিকা ভাইগ্যা গেলো!',
        tone: 'neutral',
      },
      {
        id: 'scary_hum',
        text: 'বুক ফাপড় নিয়া বিচ্ছিরি গলায় গান গাইতে গাইতে ঘুমাও!',
        effects: { happiness: 4, karma: 2 },
        outcomeText: 'তोर বেসুরা গানে ভূত ডরে পলায়ছে! তুই ফ্যামিলির একমাত্র বাহাদুর ভিরু!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'toddler_baby_dance',
    text: 'টিভিতে গান বাজতেই তোর কোমর আর হিপস নিজে নিজেই ড্যান্স ফর্মে চইলা গেছে!',
    minAge: 0,
    maxAge: 3,
    weight: 75,
    tone: 'good',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'babydance_full',
        text: 'মেশিন গান ফায়ার করার লাহান উরাধুরা বেলি ড্যান্স দে!',
        effects: { happiness: 10, health: 1 },
        outcomeText: 'তোর এই আজব কোমর দোলানি দেইখা টেবিলে রাখা চায়ের কাপ ভাইঙ্গা পইড়া গেছে!',
        tone: 'good',
      },
      {
        id: 'babydance_shy',
        text: 'লজ্জায় লাল হইয়া খালি এক পাও নাড়া!',
        effects: { happiness: 4 },
        outcomeText: 'ভদ্র পোলাপাইনের লাহান স্টাইল মারছোস, কিন্তু তোর ডায়াপার ভিজে ভারি হইয়া গেছিল!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'toddler_mud_cake',
    text: 'বাগানের পচা কাদা দেইখা তোর মনে মাস্টারশেফ জাগছে। এহন একটা মাটির কেক বানাইবি!',
    minAge: 2,
    maxAge: 5,
    weight: 55,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'mudcake_chef',
        text: 'কাদা, পোকা, পাতা মিলায়া এক জগাখিচুড়ি কেক বানা!',
        effects: { happiness: 8, karma: 2 },
        outcomeText: 'কেক বানায়া তুই নিজেই ওইটা খাইবার গেছোস! পেট খারাপ হইয়া তুই সারাদিন বাথরুমে!',
        tone: 'funny',
      },
      {
        id: 'mudcake_science',
        text: 'আটকে যাওয়া কাদা দিয়া পারফেক্ট সাইজ কেক বানা!',
        effects: { smarts: 4 },
        outcomeText: 'তোর মাটি বিজ্ঞান দেইখা আম্মা তোরে দিয়া ড্রেন পরিষ্কার করাইছে!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_dino_museum',
    text: 'মিউজিয়মে বিশাল একখান ডাইনোসরের কঙ্কাল দেইখা তোর চোখ কপালে উইঠা গেছে!',
    minAge: 4,
    maxAge: 10,
    weight: 50,
    tone: 'good',
    category: 'childhood',
    tags: ['education'],
    choices: [
      {
        id: 'dino_stare',
        text: 'মুখ হা কইরা আতেলের লাহান অপলক তাকিয়ে থাক!',
        effects: { happiness: 6, smarts: 3 },
        outcomeText: 'তোর লালা পইড়া মিউজিয়মের ফ্লোর ভেজা! গার্ড আইসা তোরে ধমক দিয়া সরায়ে দিলো!',
        tone: 'good',
      },
      {
        id: 'dino_dictate',
        text: 'বুক ফুলাইয়া প্রফেসর সাইজা সবাইকে ভুয়া লেকচার দে!',
        effects: { smarts: 4, fame: 2 },
        outcomeText: 'তুই হাড্ডি নিয়া এমন সব আজগুবি তথ্য দিছস, মাইনষে তোরে ডাইনোসরের বংশধর মনে করছে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_braids',
    text: 'স্কুলের পিকচার ডে! আম্মা তোর চুলে এমন এক স্টাইল করতাছে যেটার ব্যথায় তোর চোখ উপরে উইঠা যাইতাছে!',
    minAge: 5,
    maxAge: 10,
    weight: 45,
    tone: 'neutral',
    category: 'childhood',
    tags: ['looks'],
    choices: [
      {
        id: 'braids_hold',
        text: 'দাঁত বাইর কইরা ডরে ডরে চূপচাপ বইসা থাক!',
        effects: { looks: 4, happiness: 2 },
        outcomeText: 'ছবিতে তোরে দেইখা মনে হইতাছে কারেন্ট খাইয়া তোর চুল খাড়া হইয়া গেছে!',
        tone: 'good',
      },
      {
        id: 'braids_pull',
        text: 'চুলটুল কাইটা ফ্যালায় দিয়া পলায় যাওয়ার ট্রাই কর!',
        effects: { looks: -2, happiness: 3 },
        outcomeText: 'পলাইতে গিয়া আম্মার জুতার বাড়ি খাস নাই ঠিকই, বাট ছবির দিন তোরে পেঁচার লাহান দেখা গেছে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_coin_under_cushion',
    text: 'সোফার কুশনের চিপায় হাত ঢুকাইতেই কিসের যেন একটা গোল চকচকা কয়েন পাইলি!',
    minAge: 4,
    maxAge: 9,
    weight: 45,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'cushion_coin_keep',
        text: 'লুঙ্গির চিপায় ট্যাকা লুকায়া রাজা সাজ!',
        effects: { money: 4, happiness: 4 },
        outcomeText: 'বাপের হারানো কয়েন তুই মাইরা দিছস! ওই ট্যাকা দিয়া আইসক্রিম খায়া তুই এহন অপরাধী!',
        tone: 'funny',
      },
      {
        id: 'cushion_coin_ask',
        text: 'সৎ পোলার লাহান কয়েন গিয়া বড়দের ফেরত দে!',
        effects: { karma: 5, happiness: 2 },
        outcomeText: 'সবাই তোরে "সৎ বালক" সার্টিফিকেট দিছে। মনটা ভইরা গেছে, যদিও আইসক্রিম মিস!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_sick_day_tv',
    text: 'জ্বর উঠছে দেইখা স্কুলে যাওয়া লাগেনি! এহন সারাদিন কার্টুন দেখার সুবর্ণ সুযোগ!',
    minAge: 4,
    maxAge: 10,
    weight: 45,
    tone: 'neutral',
    category: 'childhood',
    tags: ['health'],
    choices: [
      {
        id: 'sickday_rest',
        text: 'আম্মার হাতের তিতা তেঁতুল পানি খাইয়া ঘুম দে!',
        effects: { health: 6, happiness: 2 },
        outcomeText: 'তিতা খাইয়া জ্বর তো কমছেই না, উল্টা তোর বমি আইসা আম্মার শাড়ি নষ্ট!',
        tone: 'good',
      },
      {
        id: 'sickday_marathon',
        text: 'চোখ লাল কইরা সারারাত কার্টুন দেখ!',
        effects: { happiness: 8, health: -3 },
        outcomeText: 'কার্টুন দেখতে দেখতে তোর চোখ নষ্ট! পরদিন ডাক্তার আইসা কড়া ইনজেকশন দিয়া গেছে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_marker_hands',
    text: 'হাতে পার্মানেন্ট মার্কার পাইয়া তুই নিজের হাত-পায়ে ভিনদেশী ভিনগ্রহের ট্যাটু আঁইকা ফেলছোস!',
    minAge: 2,
    maxAge: 6,
    weight: 45,
    tone: 'funny',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'markers_masterpiece',
        text: 'গ্যাংস্টার সাইজা পুরা হাত ড্রয়িং বানিয়ে ফেল!',
        effects: { happiness: 8, smarts: 2 },
        outcomeText: 'আম্মা কেরোসিন দিয়া তোর চামড়া তুইল্যা ওই কালার তুলছে! জ্বালায় তুই কাইন্দা একাকার!',
        tone: 'funny',
      },
      {
        id: 'markers_one_colour',
        text: 'মুখে আর নাকে লাল মার্কার ঘইষা ভুত সাজ!',
        effects: { happiness: 5, smarts: 1 },
        outcomeText: 'আয়নায় নিজের চেহারা দেইখা তুই নিজেই ডরাইয়া পইড়া গেছোস!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_treehouse',
    text: 'গাছের ডালে একটা মাচা বানানোর প্ল্যান চলতাছে, আর তোরে বানাইছে চিফ আর্কিটেক্ট!',
    minAge: 7,
    maxAge: 12,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['family', 'home'],
    choices: [
      {
        id: 'treehouse_design',
        text: 'ঝাড়ুর কাঠি আর পলিথিন দিয়া ঘাসফড়িং বাসা বানা!',
        effects: { smarts: 5, happiness: 6 },
        outcomeText: 'বাতাস আইসা তোর মাচা এক ফু দিয়ে উড়াইয়া নিয়া গেছে! তুই ছাদ থিকা পইড়া কাইত!',
        tone: 'good',
      },
      {
        id: 'treehouse_observer',
        text: 'কাজ না কইরা নিচ থেকে বস সাইজা হুকুম দে!',
        effects: { happiness: 4, smarts: 2 },
        outcomeText: 'পোলারা তোরে কাজ না করার অপরাধে গাছে টাইন্যা উইঠা পিঁপড়ার বাসায় বইসা রাখছে!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_speed_corners',
    text: 'স্কুলের লম্বা করিডোরের কোনায় স্পিড টেস্টের ধান্দা! ফাস্ট ওয়াকার হওয়ার সুবর্ণ সুযোগ!',
    minAge: 6,
    maxAge: 11,
    weight: 45,
    tone: 'funny',
    category: 'childhood',
    tags: ['school'],
    choices: [
      {
        id: 'speedcorner_lean',
        text: 'মহাকাশচারী সাইজা কর্নার দিয়ে স্পিডে ঘুইরা যা!',
        effects: { happiness: 7, health: -1 },
        outcomeText: 'ঘুরতে গিয়া প্রিন্সিপাল স্যারের চামড়ার জুতার উপর ডাইরেক্ট স্লাইড! স্যার তোরে কান ধইরা বাইর করলো!',
        tone: 'funny',
      },
      {
        id: 'speedcorner_watch',
        text: 'ডরে কোণায় খাড়ায়া পোলাপাইনের আছাড় খাওয়া দ্যাখ!',
        effects: { smarts: 3 },
        outcomeText: 'পোলাপাইনের আছাড় খাওয়া দেখতে দেখতে তুই নিজেই পিছলা খাইয়া পইড়া গেলি!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_old_photo',
    text: 'আম্মা পুরান ছবি বাইর করছে, যেটায় তোর ন্যাংটা বেলার বিশ্রী ছবি দেইখা তোর লজ্জা লাগতাছে!',
    minAge: 6,
    maxAge: 12,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['family'],
    choices: [
      {
        id: 'oldphoto_ask',
        text: 'জিজ্ঞাস কর: "এইড কি আমার কাটা নুনু?"',
        outcomeText: 'তোর এই বেহুদা প্রশ্নে মেহমানরা সব হা হইয়া গেছে! আম্মা তোরে জুতা নিয়া দৌড়ানি দিছে!',
        tone: 'good',
        effects: { happiness: -5, karma: -2 },        
      },
      {
        id: 'oldphoto_copy',
        text: 'লুকাইয়া ছবিডা কাইটা পকেটে লুকাইয়া ফ্যাল!',
        effects: { happiness: 5 },
        outcomeText: 'ছবি লুকাইতে গিয়া তোর হাত কাডা! রক্ত বাইর হইছে, আর ছবিডা পইড়া নষ্ট!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_science_question',
    text: 'তোর ব্রেনে হঠাৎ এক আজব কোয়েশ্চেন ফায়ার হইছে: "আসমান এত নীল ক্যান, কেউ কি ওইটাতে রং মারছে?"',
    minAge: 5,
    maxAge: 10,
    weight: 45,
    tone: 'neutral',
    category: 'childhood',
    tags: ['education'],
    choices: [
      {
        id: 'why_ask',
        text: 'পাড়ার সব মুরুব্বির মাথা খাস এই আজব কোয়েশ্চেন কইয়া!',
        effects: { smarts: 6, karma: 1 },
        outcomeText: 'মুরুব্বিরা বিরক্ত হইয়া কইলো, "আকাশে পরীরা নীল রং ঢালে!" তুই হালায় ভুয়া জ্ঞান নিয়া বইসা থাকলি!',
        tone: 'good',
      },
      {
        id: 'why_invent',
        text: 'নিজে নিজে থিওরি বানা: "আকাশ আসলে একটা বিশাল নীল জামাকাপড়!"',
        effects: { smarts: 4, happiness: 2 },
        outcomeText: 'তোর ফিজিক্সের এই লজিক শুইনা সায়েন্সের স্যার তোরে দিয়া ক্লাসরুম ঝাড়ু দেওয়াইছে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_paper_boat',
    text: 'বৃষ্টির পানিতে খাতার পাতা ছিঁড়া নৌকা বানাইয়া ড্রেনের স্রোতে ভাসাইছোস!',
    minAge: 4,
    maxAge: 9,
    weight: 45,
    tone: 'good',
    category: 'childhood',
    tags: ['fortune'],
    choices: [
      {
        id: 'paperboat_chase',
        text: 'নৌকার পিছে পিছে পাগল কুকুরের লাহান দৌড়!',
        outcomeText: 'নৌকা বাইচা গেছে, কিন্তু তুই পচা নর্দমার পানিতে পইড়া আস্ত শুঁটকি মাছ হইয়া বাড়ি ফিরছোস!',
        tone: 'funny',
        effects: { happiness: 5, health: -3, looks: -2 },        
      },
      {
        id: 'paperboat_fleet',
        text: 'পুরান পড়ার খাতা ছিঁড়া পুরা এক নৌবহর বানায়া ফ্যাল!',
        effects: { smarts: 4, happiness: 4 },
        outcomeText: 'নৌকাগুলো ড্রেনে গিয়া জ্যাম লাইগা কৃত্রিম বন্যা বানাইয়া দিছে! এলাকায় তোরে নিয়ে নালিশ!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_mango_orchard',
    text: 'বড় বাড়ির আম গাছে কাঁচা আম ঝুইলা আছে! তোর জিহ্বায় লালা আইসা গেছে!',
    minAge: 6,
    maxAge: 11,
    weight: 80,
    tone: 'funny',
    category: 'childhood',
    tags: ['adventure'],
    choices: [
      {
        id: 'mango_pluck',
        text: 'ইট মাইরা আম নামানোর ট্রাই কর!',
        effects: { happiness: 10, health: -2, karma: -2 },
        outcomeText: 'ইট ঘুইরা মালিকের গাড়ির গ্লাস ভাইঙ্গা দিছে! মালিক লাঠি নিয়া তোরে এমন দৌড়ানি দিছে, তোর জুতা হারায়া গেছে!',
        tone: 'good',
      },
      {
        id: 'mango_watchman',
        text: 'মালি বা গার্ডের চিল্লানি শুইনা ভোঁ দৌড় দে!',
        outcomeText: 'দৌড়াইতে গিয়া তুই ডাইরেক্ট একটা পাঁঠা ছাগলের উপ্রে পড়ছোস! ছাগল তোরে গুতা দিয়া গাছে উঠাইয়া দিছে!',
        tone: 'neutral',
        effects: { happiness: 5, health: -5, karma: -1 },        
      },
    ],
  },
  {
    id: 'child_monsoon_football',
    text: 'ঝুম বৃষ্টি! ড্রেন উথলাইয়া মাঠে এক হাঁটু কাদা! পোলাপাইন খালি গায়ে ফুটবল নিয়া নামছে!',
    minAge: 7,
    maxAge: 12,
    weight: 85,
    tone: 'good',
    category: 'childhood',
    tags: ['sports'],
    choices: [
      {
        id: 'monsoon_score',
        text: 'কাদার মইধ্যে স্লাইড মাইরা গোল দেওয়ার ফাপড় নে!',
        effects: { health: 4, happiness: 12, looks: -2 },
        outcomeText: 'গোল তো দিছোস, কিন্তু তোর মুখ পুরা গোবর আর কাদায় মাখামাখি! আম্মা তোরে গেটের বাইরে hose pipe দিয়া ধুইছে!',
        tone: 'good',
      },
      {
        id: 'monsoon_porch',
        text: 'ভিজার ডরে বারান্দায় খাড়াইয়া চিল্লাইয়া চিল্লাইয়া গাইল দে!',
        effects: { happiness: 5, health: 2 },
        outcomeText: 'তুই বারান্দায় শুষ্ক রইলি, কিন্তু পোলারা তোরে ধইরা জোর কইরা কাদায় ফালায়া দিলো! সব সুখ শেষ!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_eid_salami',
    text: 'ঈদের দিনে মুরুব্বিরা তোরে কড়কড়া সালামি দিতাছে! তোর পকেট এহন ট্যাকার বস্তা!',
    minAge: 5,
    maxAge: 11,
    weight: 80,
    tone: 'good',
    category: 'childhood',
    tags: ['wealth'],
    choices: [
      {
        id: 'salami_piggybank',
        text: 'মাটির ব্যাংকে ট্যাকা জমাইয়া জমিদার সাজ!',
        effects: { money: 15, smarts: 4, happiness: 6 },
        outcomeText: 'ট্যাকা জমাইছোস ঠিকই, কিন্তু বড় ভাই ব্যাংক ভাইঙ্গা সব ট্যাকা দিয়া সিগারেট কিনছে!',
        tone: 'good',
      },
      {
        id: 'salami_icecream',
        text: 'ট্যাকা পাইয়াই আইসক্রিমওয়ালার পিছে স্প্রিন্ট মার!',
        effects: { happiness: 12, health: -1, money: 5 },
        outcomeText: 'সব সালামির ট্যাকা দিয়া কুলফি খাইয়া রাইতে তোর পাতলা পায়খানা! সালামির গুষ্টি কিলাইয়া দিলি!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_kite_chase',
    text: 'আকাশ থিকা একটা কাটার ঘুড়ি তোর ছাদের দিকে পইড়া আসতাছে!',
    minAge: 8,
    maxAge: 12,
    weight: 75,
    tone: 'neutral',
    category: 'childhood',
    tags: ['adventure'],
    choices: [
      {
        id: 'kite_bamboo_pole',
        text: 'বাঁশ হাতে নিয়া ছাদ থিকা ঝুঁইকা ঘুড়ি ধরতে যা!',
        outcomeText: 'ঝুঁকতে গিয়া তুই নিজে ছাদ থিকা পইড়া যাওয়ার উপক্রম! পাশের বাসার আন্টি তোরে জামার কলার ধইরা বাঁচাইছে!',
        tone: 'good',
        effects: { happiness: 5, health: -3, karma: 2},
      },
      {
        id: 'kite_letgo',
        text: 'ভাব নিয়া চিল্লাইয়া ওঠ: "আমার এইডা লাগতানা!"',
        outcomeText: 'ঘুড়ি গিয়া পাশের বাসার ঝালমুড়িওয়ালার মাথার উপre পড়লো! মাখামাখি অবস্থা!',
        tone: 'neutral',
        effects: { happiness: 5, health: -2, karma: -1},
      },
    ],
  },
  {
    id: 'child_secret_comic',
    text: 'ম্যাথ খাতার চিপায় চটি বা কমিকস লুকাইয়া পড়ার মাস্টারপিস প্র্যাকটিস করতাছোস!',
    minAge: 8,
    maxAge: 12,
    weight: 70,
    tone: 'funny',
    category: 'childhood',
    tags: ['education'],
    choices: [
      {
        id: 'comic_stealth',
        text: 'স্টিলথ মোডে বই পইড়া হ্যাকার সাইজা থাক!',
        effects: { smarts: 4, happiness: 8 },
        outcomeText: 'ধরা পড়স নাই, তুই এহন ক্লাসের আন্ডারগ্রাউন্ড কমিক কিং!',
        tone: 'good',
      },
      {
        id: 'comic_snickered',
        text: 'কমিকস পইড়া শব্দ কইরা খ্যাঁকখ্যাঁক কইরা হাস!',
        effects: { happiness: -4, karma: 2 },
        outcomeText: 'স্যার আইসা খাতা খুইলা দেখলো তুই ম্যাথের জায়গায় স্পাইডারম্যান পড়তাছোস! খাতা জব্দ, বাড়ি গিয়া মাইর!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'child_stray_cat',
    text: 'রান্নাঘরের দরজায় এক চিপচিপে বিলাই মিউ মিউ করতাছে। তোর মনে দয়া উথলাইয়া উঠছে!',
    minAge: 4,
    maxAge: 11,
    weight: 75,
    tone: 'good',
    category: 'childhood',
    tags: ['pets'],
    choices: [
      {
        id: 'stray_feed_fish',
        text: 'আম্মার মাছ ভাজার ইলিশ মাছ লুকাইয়া বিলাইরে দে!',
        effects: { karma: 8, happiness: 10 },
        outcomeText: 'বিলাই মাছ খায়া পলায়ছে, আর আম্মা আইসা ইলিশ মাছ চুরির অপরাধে তোরে ডাইরেক্ট খাটের কোণায় টাইট দিছে!',
        tone: 'good',
      },
      {
        id: 'stray_shoo_gently',
        text: 'ডায়নোসরের লাহান ভংচং কইরা বিলাই তাড়!',
        effects: { smarts: 2, happiness: -1 },
        outcomeText: 'বিলাই তোরে উল্টা তেড়ে আইসা কামড় দিছে! তোর হাতে ব্যান্ডেজ বানাইতে হইছে!',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'child_chashi_chalk',
    text: 'হাতে চক পাইয়া তুই উঠানের মইধ্যে কুচ্ছিত নকশা আর ভুতুড়ে ম্যাপ আঁকতে শুরু করছোস!',
    minAge: 5,
    maxAge: 10,
    weight: 70,
    tone: 'good',
    category: 'childhood',
    tags: ['creativity'],
    choices: [
      {
        id: 'chalk_tournament',
        text: 'সাজেস্ট কর যে এইডা একটা ভিনগ্রহের রানওয়ে!',
        effects: { happiness: 10, health: 3 },
        outcomeText: 'পোলাপাইন আইসা ওইটার উপর দিয়া দৌড় মারতে গিয়া পইড়া পা ভাঙছে! তোরে নিয়া বিচার বসছে!',
        tone: 'good',
      },
      {
        id: 'chalk_art',
        text: 'আতেল সাইজা বিশাল আর্ট বানানোর ফাপড় নে!',
        effects: { smarts: 5, happiness: 7 },
        outcomeText: 'বৃষ্টি আইসা তোর সব আর্ট ধুইয়া ড্রেনে ফালায়া দিছে! প্রকৃতির কাছে তোর আর্ট ফেল!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'child_power_cut_stories',
    text: 'কারেন্ট ফুড়ুৎ! মোমের আলোয় সবাই গোল হইয়া বইসা ভূতের গল্প ফাদছে!',
    minAge: 6,
    maxAge: 12,
    weight: 75,
    tone: 'funny',
    category: 'childhood',
    tags: ['family'],
    choices: [
      {
        id: 'ghost_scare',
        text: 'পেত্নীর গল্প কইয়া এমন চিল্লাইয়া ওঠ, সবডি ডরে লাফায়!',
        effects: { happiness: 10, fame: 3 },
        outcomeText: 'সবাই ডরছে ঠিকই, কিন্তু ডরের চোটে কাজিন তোর গায়ে চা ঢাইলা দিছে! চামড়া পুইড়া লাল!',
        tone: 'good',
      },
      {
        id: 'shadow_puppets',
        text: 'হাতের ছায়া দিয়া দেয়ালে কুত্তা-বিড়াল বানাস!',
        effects: { smarts: 4, happiness: 8 },
        outcomeText: 'ছায়ার খেলা দেখতে দেখতে কারেন্ট আইসা গেছে, তোর ম্যাজিক শেষ!',
        tone: 'good',
      },
    ],
  },
];