import type { LifeEventDef } from '@/lib/engine/types';

export const SENIOR_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'se_retirement_day',
    text: 'অফিসের ডেস্কে লাস্ট দিন! তোর চামচা কলিগরা একখান সস্তা কেক আইন্না বিদায় দিতাছে, আর মনে মনে কয় "বুড়া হালায় কবে যাইবো!"',
    minAge: 60,
    maxAge: 75,
    weight: 95,
    tone: 'good',
    category: 'senior',
    tags: ['career', 'milestone'],
    choices: [
      {
        id: 'se_retire_soft',
        text: 'নবাবের লাহান রিটায়ার কইরা ঘরে গিয়া লুঙ্গি পইড়া চিল মার!',
        effects: { happiness: 8, health: 3, addFlag: 'retired' },
        outcomeText: 'ঘরে বইসা চিল মারতে গিয়া বউয়ের ঝাড়ুর বাড়ি খাইলি! বউ কয়, "সারাদিন ঘরে পইড়া না থাইকা বাজারে যা হালায়!"',
        tone: 'bad',
      },
      {
        id: 'se_retire_consult',
        text: 'লোভে পইড়া আবার কন্ট্রাক্টে চাকরি করার ফাপড় নে!',
        effects: { money: 6, happiness: 4, smarts: 2 },
        outcomeText: 'নতুন বসের আন্ডারে তুই এহন পুরাই গাধা! তোর বয়সের পোলাপাইন তোরে দিয়া চা আনায়, ইজ্জতের পুরাই ফালুদা!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_grandkids_barrage',
    text: 'গরমের ছুটিতে তোর নাতি-নাতনিরা আইসা পুরা বাড়ি মাথায় তুলছে! তাগো চিল্লানিতে তোর কানের মেশিন ফাইট্টা যাওয়ার দশা!',
    minAge: 60,
    maxAge: 85,
    weight: 80,
    tone: 'bad',
    category: 'senior',
    tags: ['family'],
    requiredFlags: ['has_child'],
    choices: [
      {
        id: 'se_grand_expeditions',
        text: 'পার্কে নিয়া গিয়া পিচ্চিগো আইসক্রিম খাওয়া আর ফাপড় নে!',
        effects: { happiness: 12, health: -2 },
        outcomeText: 'আইসক্রিম খাইতে গিয়া তোর নিজেরই দাঁত শিরশির কইরা উঠলো! আর পিচ্চিরা তোর পকেটের সব ট্যাকা খসায়া তোরে ফকির বানায়া দিলো!',
        tone: 'funny',
      },
      {
        id: 'se_grand_fisherman',
        text: 'ঘরে বইসা পিচ্চিগো তোর আমলের গাজাখুরি গল্প শুনা!',
        effects: { happiness: 8, smarts: 3 },
        outcomeText: 'তোর গল্প শুইনা পিচ্চিরা বোরিং খাইয়া তোর মুখেই খেলনা ফিক্কা মারলো! তোর নাক দিয়া রক্ত বাইর হইয়া একাকার!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_spouse_care',
    text: 'তোর বুড়ির/বুড়ার হাড্ডি নড়বড়ে, এহন তোরেই নার্স সাইজা গু-মুত সাফ করা লাগতাছে! রোমান্স এহন ডাইরেক্ট ডায়াপারে!',
    minAge: 65,
    maxAge: 90,
    weight: 55,
    tone: 'neutral',
    category: 'senior',
    tags: ['family', 'health'],
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'se_care_patient',
        text: 'দাঁত কামড়াইয়া নিজের হাতে বুড়ির ডায়াপার চেঞ্জ কর!',
        effects: { happiness: 6, health: -4, karma: 6 },
        outcomeText: 'ডায়াপার খুলতেই এমুন একখান গন্ধ বাইর হইলো, তুই বমি কইরা পুরা বিছানা ভাসায়া দিলি! রোমান্স পুরাই ডাস্টবিনে!',
        tone: 'bad',
      },
      {
        id: 'se_care_share',
        text: 'ট্যাকা খরচ কইরা একখান ইয়াং নার্স রাখ বাসায়!',
        effects: { health: 3, happiness: 3, money: -6 },
        outcomeText: 'ইয়াং নার্স দেইখা তোর নিজেরই নুনু খাড়া হইয়া যাওয়ার দশা! বুড়ি এইটা টের পাইয়া তোরে লাঠি দিয়া এমুন পিটাইলো, তুই নিজেই এহন রোগী!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_downsize_choice',
    text: 'বাড়ি বড়, কিন্তু পোলাপাইন সব বিদেশে! দালালে ফাপড় দিতাছে বাড়ি বেইচা ছোট ফ্লাটে উঠতে, নাইলে মইরা পইড়া থাকলে কেউ টের পাইবো না!',
    minAge: 65,
    maxAge: 85,
    weight: 65,
    tone: 'neutral',
    category: 'senior',
    tags: ['lifestyle', 'finance'],
    choices: [
      {
        id: 'se_downsize_flat',
        text: 'পুরান বাড়ি বেইচা ডাইরেক্ট একখান লিফটওয়ালা ফ্লাটে গিয়া উঠ!',
        effects: { happiness: 8, money: 8, health: 3 },
        outcomeText: 'ফ্লাটে উঠছোস ঠিকই, কিন্তু লিফট নষ্ট থাকায় তোর ১০ তলা হাইটা উঠতে গিয়া হার্ট অ্যাটাক করার দশা! হাঁটু ফাইট্টা চৌচির!',
        tone: 'bad',
      },
      {
        id: 'se_downsize_stay',
        text: 'গুন্ডা সাইজা ক: "মরলেও বাপের ভিটায় মরুম, হালায়!"',
        effects: { happiness: 5, money: -4 },
        outcomeText: 'বাপের ভিটায় একা থাকতে গিয়া রাইতে চোর আইসা তোর লুঙ্গি খুইলা সব ট্যাকা নিয়া গেছে! তুই এহন ন্যাংটা বুইড়া!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_pension_plan',
    text: 'পেনশনের ট্যাকা আইছে! এহন ডিসিশন ল, একলগে তুইলা থাইল্যান্ড যাবি নাকি মাসে মাসে মাইপা খাবি?',
    minAge: 65,
    maxAge: 80,
    weight: 60,
    tone: 'neutral',
    category: 'senior',
    tags: ['finance'],
    choices: [
      {
        id: 'se_pension_steady',
        text: 'ভদ্র বুইড়া সাইজা মাসে মাসে ট্যাকা নিয়া দাইল-ভাত খা!',
        effects: { money: 10, happiness: 2 },
        outcomeText: 'মাসে মাসে ট্যাকা নিস ঠিকই, কিন্তু তোর পোলারা সব ট্যাকা মাইরা নিয়া যায়! তুই এহন জ্যান্ত এটিএম (ATM) মেশিন!',
        tone: 'bad',
      },
      {
        id: 'se_pension_lump',
        text: 'একলগে সব ট্যাকা তুইলা থাইল্যান্ডের পাতায়ায় মাসাজ নিতে যা!',
        effects: { money: 12, happiness: 8, health: -2 },
        outcomeText: 'পাতায়ায় গিয়া লেডি-বয় (Ladyboy) দেইখা তোর হার্ট ফেল করার দশা! ট্যাকা সব উড়াইয়া দেশে আইসা এহন তুই ভিক্কা কর!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_bucket_last_page',
    text: 'মরার আগে তোর বাকেট লিস্টের লাস্ট পেজ বাকি! উরাধুরা কিছু করার শখ জাগছে তোর!',
    minAge: 66,
    maxAge: 85,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['travel'],
    choices: [
      {
        id: 'se_bucket_go',
        text: 'ব্লাড প্রেসারের গুষ্টি কিলাইয়া দার্জিলিং ট্যুরে বাইর হ!',
        effects: { happiness: 10, money: -6 },
        outcomeText: 'দার্জিলিং গিয়া ঠান্ডায় তোর অণ্ডকোষ জইমা এক্কেরে বরফ! বাথরুমে মুততে গিয়া দেখস নুনু খুঁজাই পাচ্ছোস না! ট্যুর পুরাই বাঁশ!',
        tone: 'funny',
      },
      {
        id: 'se_bucket_photobook',
        text: 'ডরে মুইতা দিয়া ঘরে বইসা ইউটিউবে ট্রাভেল ভ্লগ দ্যাখ!',
        effects: { happiness: 7 },
        outcomeText: 'ভ্লগ দেখতে দেখতে তুই ঘুমাইয়া গেলি! ঘুমের মইধ্যে বিছানায় মুইতা দিয়া পুরা বাকেট লিস্টের বারোটা বাজাইয়া দিছোস!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_health_knees',
    text: 'হাঁটুর বাতে তুই এহন লেংড়া ঘোড়া! কমোডে বইতে গেলে এমুন চিল্লান বাইর হয়, পাশের ফ্ল্যাটের মাইনষে ভাবে তুই জবেহ হইতাছোস!',
    minAge: 70,
    maxAge: 95,
    weight: 60,
    tone: 'bad',
    category: 'senior',
    tags: ['health'],
    choices: [
      {
        id: 'se_knees_move',
        text: 'পাকনামি কইরা ইউটিউব দেইখা ইয়োগা (Yoga) করার ট্রাই কর!',
        effects: { health: 6, happiness: 4 },
        outcomeText: 'পাছা উঁচা কইরা ইয়োগা করতে গিয়া তোর হিপ জয়েন্ট খুইলা গেছে! এহন তুই বাঁকা হইয়া হাঁটতাছোস, পুরাই পঙ্গু!',
        tone: 'funny',
      },
      {
        id: 'se_knees_grump',
        text: 'ব্যথায় মেজাজ ফায়ার কইরা ঘরের সবগুলারে ইচ্ছামতো গাইল পার!',
        effects: { health: -4, happiness: -3 },
        outcomeText: 'তোর গাইল শুইনা তোর পোলা তোরে বাথরুমে আটকায়া রাখছে পুরা দিন! গু-মুতের গন্ধে তোর জান শেষ!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_reconnect_old_friends',
    text: '৬০ বছর আগের ক্লাসমেট নক দিছে! যেই হালায় স্কুলে তোর ক্রাশরে ভাগাইয়া নিসিলো, হেই আইজকা রিইউনিয়নের ফাপড় দিতাছে!',
    minAge: 70,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['friendship'],
    choices: [
      {
        id: 'se_friends_reunion',
        text: 'রিইউনিয়নে গিয়া ফাপড়বাজি কইরা পুরান ঝাল মিটা!',
        effects: { happiness: 12, smarts: 3 },
        outcomeText: 'গিয়া দেখস হেই হালায় এহন কোটিপতি আর তুই হালায় ফইন্নি! অপমানে তোর প্রেশার হাই হইয়া তুই ডাইরেক্ট বেহুঁশ!',
        tone: 'bad',
      },
      {
        id: 'se_friends_letters',
        text: 'ইগনোর মাইরা আলগা ভাব নিয়া ফেসবুকে ব্লক মাইরা দে!',
        effects: { happiness: 8 },
        outcomeText: 'ব্লক মারছোস ঠিকই, কিন্তু পরে হুনলি হেই হালায় সব দোস্তগো লাখ ট্যাকা কইরা গিফট দিছে! আফসোসে তুই নিজের চুল নিজে ছিঁড়তাছোস!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_legacy_notebook',
    text: 'তোর নাতি জিগায় তুই লাইফে কী বাল ফালাইছোস? এহন আত্মজীবনী লেখার টাইম, চাপাবাজির লিমিট ক্রস করার সুবর্ণ সুযোগ!',
    minAge: 70,
    maxAge: 95,
    weight: 65,
    tone: 'good',
    category: 'senior',
    tags: ['legacy'],
    choices: [
      {
        id: 'se_legacy_write',
        text: 'খাতা খুইলা ৭১ সালের ভুয়া বীরত্বের গল্প লেইখা ফাপড় নে!',
        effects: { happiness: 9, smarts: 4, karma: 3 },
        outcomeText: 'গল্প পইড়া তোর নাতি জিগায়, "দাদু, তুমি তো তখন মাত্র ৫ বছরের আছিলা, বন্দুক ধরলা কেমনে?" বাটপারি ধইরা তোরে পুরাই রোস্ট কইরা দিলো!',
        tone: 'funny',
      },
      {
        id: 'se_legacy_recite',
        text: 'মোবাইলে ভয়েস রেকর্ড কইরা জ্ঞান দেওয়ার ট্রাই কর!',
        effects: { happiness: 7, karma: 2 },
        outcomeText: 'রেকর্ড করার টাইমে তোর এমুন কড়া একখান পাদ বাইর হইলো যে রেকর্ড পুরাই নষ্ট! নাতিরা ওইটা শুইনা হাসতে হাসতে বেহুঁশ!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_garden_society',
    text: 'মহল্লার ছাদ বাগানের সভাপতি বানাইছে তোরে, কিন্তু তুই হালায় জীবনে একটা ঘাসও কাটছ নাই!',
    minAge: 70,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['community', 'health'],
    choices: [
      {
        id: 'se_garden_own',
        text: 'হাতে কোদাল নিয়া মাটি খুঁইড়া টমেটো চাষের ভাব ল!',
        effects: { happiness: 9, health: 4, karma: 2 },
        outcomeText: 'কোদাল মারতে গিয়া তুই ছাদের পানির পাইপ ফাটাইয়া দিছোস! পুরা বিল্ডিংয়ের মাইনষে তোরে গাইল দিয়া সভাপতি থিকা লাথি মাইরা নামাইলো!',
        tone: 'bad',
      },
      {
        id: 'se_garden_advise',
        text: 'চেয়ারে বইসা ইয়াং পোলাপাইনরে ফাউ ফাউ এডভাইস দে!',
        effects: { happiness: 5, smarts: 1 },
        outcomeText: 'তোর ফাউ এডভাইস শুইনা পোলাপাইন তোর গাছে ডাইরেক্ট মুইতা দিছে! গাছও মরছে, তোর ইজ্জতও মরছে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_companion_cat',
    text: 'একা লাইফে একখান বদমেজাজি বিলাই পালার ফাপড় নিছোস! বিলাই তোরে দেইখা এমুন চাউনি দিতাছে, মনে হয় তুই ওর চাকর!',
    minAge: 70,
    maxAge: 95,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['pet', 'companion'],
    choices: [
      {
        id: 'se_cat_adopt',
        text: 'বিলাইরে আদর করতে গিয়া কোলে তুইলা নে!',
        effects: { happiness: 10, health: 2 },
        outcomeText: 'বিলাই তোর মুখে এমুন এক খামচি দিলো, তুই আজীবন টাইগার-মুখা হইয়া গেলি! এহন তুই বিলাইয়ের ডরে খাটের তলে ঘুমাস!',
        tone: 'bad',
      },
      {
        id: 'se_cat_visit',
        text: 'ডরে বিলাই না পাইলা রাস্তায় কুত্তারে পাউরুটি খাওয়া!',
        effects: { happiness: 5, karma: 2 },
        outcomeText: 'পাউরুটি খায়া কুত্তা তোর প্যান্টের উপ্রে ডাইরেক্ট মুইতা দিলো! তুই পুরাই স্ট্রিট-ডগ টয়লেট!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_reading_circle',
    text: 'লাইব্রেরিতে বুইড়াগো আড্ডায় ডাক পড়ছে, সবডি মিল্লা পরকীয়ার উপন্যাস পইড়া যৌবন মনে করতাছে!',
    minAge: 70,
    maxAge: 95,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['hobby', 'social'],
    choices: [
      {
        id: 'se_reading_join',
        text: 'আড্ডায় গিয়া রোমান্টিক ডায়লগ মাইরা ভাব নে!',
        effects: { happiness: 8, smarts: 4 },
        outcomeText: 'রোমান্টিক কথা বলতে গিয়া তোর ফলস দাঁত খুইলা সামনের আন্টির চায়ের কাপে পড়লো! আন্টি বমি কইরা পুরা লাইব্রেরি ভাসাইলো!',
        tone: 'funny',
      },
      {
        id: 'se_reading_lead',
        text: 'সবারে লুকাইয়া চটি বই পড়ার অফার দে!',
        effects: { happiness: 7, smarts: 5, karma: 2 },
        outcomeText: 'চটি বই বাইর করতেই লাইব্রেরিয়ান ধইরা ফালাইলো! "লুচ্চা বুইড়া" কইয়া তোরে ঘাড়ধাক্কা দিয়া রাস্তায় বাইর কইরা দিলো!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_sage_advice',
    text: 'তোর এক ইয়াং কলিগ ফোন দিয়া তোর ফালতু এডভাইস চাইতাছে! তুই এহন সক্রেটিস সাজার চান্স পাইছোস!',
    minAge: 68,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['community', 'mentor'],
    choices: [
      {
        id: 'se_sage_speak',
        text: 'আতেল সাইজা লম্বা একখান গাজাখুরি ফিলোসফি ঝাইড়া দে!',
        effects: { happiness: 7, karma: 4 },
        outcomeText: 'তোর এডভাইস শুইনা হেই পোলা ব্যবসায় ডাব্বা মারছে! এহন তোরে খুঁজতাছে রামদা নিয়া কোপানোর লাইগা!',
        tone: 'bad',
      },
      {
        id: 'se_sage_listen',
        text: 'পকপক না শুইনা ফোন রাইখা দিয়া বিড়ি ধরাইয়া চিল মার!',
        effects: { happiness: 6, karma: 3 },
        outcomeText: 'পোলা ভাইবা নিছে তুই অনেক জ্ঞানী তাই চুপ আছিলি! মাগনা ইজ্জত কামাইলি হালায়, পুরাই কপাল তোর!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_comfort_visit',
    text: 'পাশের ফ্লাটের মুরুব্বি হাসপাতালে, তুই হালায় দেখতে যাবি নাকি তার মরার ওয়েট করবি?',
    minAge: 70,
    maxAge: 95,
    weight: 45,
    tone: 'neutral',
    category: 'senior',
    tags: ['health', 'community'],
    choices: [
      {
        id: 'se_visit_presence',
        text: 'হাসপাতালে গিয়া আপেল হাতে নিয়া কান্দনের ভান কর!',
        effects: { happiness: 7, karma: 5 },
        outcomeText: 'মুরুব্বি তো মরেই নাই, উল্টা তোর আপেল খায়া তোরে গাইল দিলো! "কঞ্জুস হালায়, আঙুর আনতে পারস নাই?"',
        tone: 'funny',
      },
      {
        id: 'se_visit_card',
        text: 'ট্যাকা বাঁচাইতে না গিয়া হোয়াটসএপে "গেট ওয়েল সুন" মেসেজ দে!',
        effects: { happiness: 3, karma: 2 },
        outcomeText: 'মুরুব্বির পোলা মেসেজ দেইখা রাগ কইরা তোরে ব্লক মারছে! তুই মহল্লায় পুরাই বেইজ্জত!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_widowhood_kind',
    text: 'তোর সারা জীবনের প্যারা, তোর বউ/স্বামী অবশেষে পটল তুলছে। ঘর এহন শ্মশানঘাট, কিন্তু তোর মনে হালকা মুক্তির বাতাস!',
    minAge: 65,
    maxAge: 100,
    weight: 40,
    tone: 'bad',
    category: 'senior',
    tags: ['family', 'grief'],
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'se_widow_grief',
        text: 'মানুষের সামনে গিয়া হাউমাউ কইরা মাইক ফাটায়া কান্দ!',
        effects: { happiness: -6, health: -3, smarts: 3 },
        outcomeText: 'কান্দতে গিয়া তোর ফলস দাঁত খুইলা লাশের উপ্রে পইড়া গেলো! পোলাপাইন আইসা তোরে সান্ত্বনার বদলে দাঁত তুইলা দিলো! চরম সিন!',
        tone: 'funny',
      },
      {
        id: 'se_widow_memory',
        text: 'নতুন কইরা ব্যাচেলর লাইফ শুরু করার প্ল্যান কর মনে মনে!',
        effects: { happiness: 4, karma: 3, addFlag: 'widowed', removeFlag: 'has_spouse' },
        outcomeText: 'নতুন বিয়া করবি ভাইবা খুশি হইছিলি, কিন্তু তোর কোমরে এহন আর জোর নাই! ভায়াগ্রা খায়া তুই ডাইরেক্ট হাসপাতালে!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_memory_project',
    text: 'মরার আগে ফ্যামিলি তোর ইন্টারভিউ নিতে আইছে, মেইনলি সম্পত্তির খোঁজ নিতে!',
    minAge: 72,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['family', 'legacy'],
    choices: [
      {
        id: 'se_memory_join',
        text: 'ক্যামেরার সামনে বইসা জমিদারের লাহান চাপাবাজি শুরু কর!',
        effects: { happiness: 9, karma: 4 },
        outcomeText: 'তুই কইলি তোর সুইস ব্যাংকে ট্যাকা আছে! পোলাপাইন খুশিতে তোরে মাথায় তুইলা নাচলো, তুই মইরা গেলে হালাগো বাঁশ কনফার্ম!',
        tone: 'funny',
      },
      {
        id: 'se_memory_count',
        text: 'ইন্টারভিউ না দিয়া পুরান মাইয়াগো ছবি বাইর কইরা নস্টালজিক হ!',
        effects: { happiness: 7, smarts: 3 },
        outcomeText: 'তোর মাইয়া আইসা দেখলো তুই পুরান এক্স-এর ছবি দেখতাছোস! তোরে থাপ্পড় দিয়া ছবিগুলা ছিঁড়া চুলায় ফালায়া দিলো!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_bridge_club',
    text: 'তাসের আড্ডায় বুইড়ারা বিস্কুট আর ১০ ট্যাকার বাজি নিয়া কুরুক্ষেত্র লাগাইছে!',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['social', 'hobby'],
    choices: [
      {
        id: 'bridge_learn',
        text: 'তাসের আড্ডায় ঢুইকা বাটপারি কইরা জেতার ট্রাই কর!',
        effects: { smarts: 5, happiness: 5 },
        outcomeText: 'তোর তাস চুরি ধরা পইড়া গেছে! বুইড়ারা মিল্লা তোরে লাঠি দিয়া এমুন পিটাইলো, তোর কোমরের হাড্ডি বাঁকা হইয়া গেছে!',
        tone: 'bad',
      },
      {
        id: 'bridge_watch',
        text: 'খেইলা বাঁশ না খায়া রেফারি সাইজা ফ্রি বিস্কুট গিল!',
        effects: { happiness: 3, karma: 3 },
        outcomeText: 'মাগনা বিস্কুট খাইতে গিয়া তোর গলায় আটকায়া গেলো! শ্বাস বন্ধ হইয়া তুই এমুন চোখ উল্টাইলি, সবাই ভাবলো তুই পটল তুলছোস!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_technology_class',
    text: 'স্মার্টফোন চালাইতে গিয়া পর্ন সাইটের লিংক ফ্যামিলি গ্রুপে শেয়ার কইরা দিছোস! এহন বাঁচার লাইগা টেকনোলজি ক্লাসে ভর্তি হইছোস!',
    minAge: 70,
    maxAge: 100,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['education', 'social'],
    choices: [
      {
        id: 'techclass_stay',
        text: 'ক্লাসে বইসা ভালো পোলার লাহান ফেসবুক চালানো শিখ!',
        effects: { smarts: 7, happiness: 4 },
        outcomeText: 'ফেসবুক চালানো শিখছোস ঠিকই, কিন্তু এহন তুই সারাদিন টিকটকে ইয়াং মাইয়াগো ড্যান্স দেইখা লালা ফালাস! লুচ্চা বুইড়া!',
        tone: 'funny',
      },
      {
        id: 'techclass_note',
        text: 'ক্লাসে না বুইঝাই টিচাররে আলগা এডভাইস দেওয়া শুরু কর!',
        effects: { happiness: 4, karma: 4 },
        outcomeText: 'টিচার মেজাজ ফায়ার কইরা তোরে ক্লাস থিকা বাইর কইরা দিছে! তুই এহনও বাটন ফোনে হ্যালো হ্যালো করস!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_genealogy_trip',
    text: 'তোর দাদার বাপে নাকি জমিদার আছিলো! খোঁজ নিতে গ্রামে যাবি নাকি ঘরে বইসা ফাপড় দিবি?',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['legacy', 'family', 'travel'],
    choices: [
      {
        id: 'genealogy_visit',
        text: 'লুঙ্গি পইড়া গ্রামে গিয়া জমিদারের লাহান ভাব নিতে যা!',
        effects: { happiness: 7, smarts: 3, money: -5 },
        outcomeText: 'গ্রামে গিয়া শুনলি তোর দাদার বাপ জমিদার না, জমিদারের কুত্তা পালতো! পুরাই বেইজ্জতি, গ্রামের মাইনষে তোরে নিয়া হাসাহাসি করলো!',
        tone: 'funny',
      },
      {
        id: 'genealogy_chart',
        text: 'গ্রামে না গিয়া ঘরে বইসাই ভুয়া ফ্যামিলি ট্রি বানায়া ফাপড় নে!',
        effects: { smarts: 5, happiness: 3 },
        outcomeText: 'তোর ফ্যামিলি ট্রি দেইখা পোলাপাইন জিগায়, "দাদু, আমাগো গুষ্টিতে কি সব ছাগল আছিলো?" তুই রাগে কাগজ ছিঁইড়া ফালায়া দিলি!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_letters_to_future',
    text: '১০০ বছর পরের নাতি-পুতিগো লাইগা চিঠি লেখার ফাপড়! তুই এহন ভবিষ্যৎ দ্রষ্টা!',
    minAge: 70,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['legacy'],
    choices: [
      {
        id: 'letters_write',
        text: 'চিঠিতে লেইখা দে: "আমার জমানো ট্যাকা বাথরুমের ফ্লোরের নিচে!"',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'তোর চিঠি পইড়া ফ্যামিলির সবাই বাথরুম ভাইঙ্গা খুঁড়াখুঁড়ি শুরু করলো! ট্যাকা তো নাইই, এহন তুই হাগু করবি কই হালায়?',
        tone: 'funny',
      },
      {
        id: 'letters_tape',
        text: 'ক্যাসেট রেকর্ডারে গাইল দিয়া রেকর্ড কইরা থুইয়া যা!',
        effects: { happiness: 6, karma: 2 },
        outcomeText: 'তোর রেকর্ড শুইনা নাতি-পুতিরা ভাবলো তুই পাগল আছিলি! তোর রেকর্ড এহন টিকটকে ফানি সাউন্ড হিসেবে ভাইরাল!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_reminiscence_table',
    text: 'বৃদ্ধাশ্রমে পুরান জিনিস নিয়া ফাপড়বাজির আড্ডা! সবাই আইছে চাপাবাজি করতে!',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['community'],
    choices: [
      {
        id: 'reminiscence_share',
        text: 'তোর পুরান আন্ডারওয়ার দেখাইয়া ক: "এইডা পইড়াই আমি মুক্তিযুদ্ধে গেছিলাম!"',
        outcomeText: 'তোর আন্ডারওয়ারের গন্ধে পুরা আড্ডা ভাইঙ্গা সবাই বমি কইরা দিলো! তোরে ধইরা বৃদ্ধাশ্রম থিকা বাইর কইরা দিলো!',
        tone: 'bad',
        effects: { happiness: -5, karma: 2 },
      },
      {
        id: 'reminiscence_listen',
        text: 'চাপাবাজি না শুইনা কোণায় বইসা নাক ডাইকা ঘুম দে!',
        effects: { happiness: 5, smarts: 3 },
        outcomeText: 'ঘুমের মইধ্যে তুই এমুন পাদ দিলি, পাশের এক বুইড়া হার্ট অ্যাটাক কইরা পটল তুললো! তুই এহন খুনি হালায়!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_morning_walk',
    text: 'রমনা পার্কে ডায়াবেটিস কমানোর লাইগা দৌড়ানি! লগে আন্টিগো দেইখা তোর চোখ ট্যারা!',
    minAge: 66,
    maxAge: 100,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['health'],
    choices: [
      {
        id: 'morningwalk_soon',
        text: 'আন্টিগো সামনে হিরো সাইজা স্পিডে দৌড় দে!',
        effects: { health: 7, happiness: 5 },
        outcomeText: 'দৌড়াইতে গিয়া তুই কুকুরের গু-এ পাড়া দিয়া এমুন আছাড় খাইলি, তোর ফলস দাঁত উইড়া গিয়া আন্টির গায়ে পড়লো! ইজ্জত পুরাই জিরো!',
        tone: 'funny',
      },
      {
        id: 'morningwalk_garden',
        text: 'দৌড়ানি বাদ দিয়া বেঞ্চে বইসা বিড়ি ফুঁক!',
        effects: { health: -10, happiness: 4 },
        outcomeText: 'বিড়ি খাইতে গিয়া তোর কাশির চোটে ফুসফুস বাইর হইয়া যাওয়ার দশা! এহন হাসপাতালে বইসা অক্সিজেন টান হালায়!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_grandchild_bedtime_stories',
    text: 'নাতিরে ঘুম পাড়ানির লাইগা রূপকথার ফাপড়! তুই এহন গল্পকার!',
    minAge: 55,
    maxAge: 95,
    weight: 80,
    tone: 'good',
    category: 'senior',
    tags: ['family'],
    choices: [
      {
        id: 'story_theatrical_voices',
        text: 'ভুতের আওয়াজ কইরা পিচ্চিরে ডর দেখানোর ট্রাই কর!',
        effects: { happiness: 16, karma: 10, smarts: 4 },
        outcomeText: 'তোর ভুতের আওয়াজ শুইনা পিচ্চি ডরে তোর কোলেই মুইতা দিলো! এহন তুই মুত-মাখা দাদু, রাইত ভইরা লুঙ্গি ধো!',
        tone: 'funny',
      },
      {
        id: 'story_ancestral_history',
        text: 'নিজের লাইফের চাপাবাজির স্টোরি শুনা!',
        effects: { karma: 12, smarts: 6, happiness: 10 },
        outcomeText: 'তোর বোরিং গল্প শুইনা পিচ্চি ঘুমাইলো ঠিকই, কিন্তু তুই নিজেই গল্প বলতে বলতে নাক ডাইকা ঘুমায়া গেলি! সকালে উইঠা দেখস পিচ্চি তোর মুখে মার্কার দিয়া গোঁফ আইকা দিছে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_morning_park_laughter_club',
    text: 'পার্কে গিয়া পাগলের লাহান হাত তুইলা হাসির প্র্যাকটিস! পুরাই সার্কাস চলতাছে!',
    minAge: 55,
    maxAge: 100,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['health', 'community'],
    choices: [
      {
        id: 'laugh_belly_hearty',
        text: 'বুক ফুলাইয়া হা হা হা কইরা জানোয়ারের লাহান হাস!',
        effects: { health: 10, happiness: 16, looks: 4 },
        outcomeText: 'অতিরিক্ত হাসতে গিয়া তোর লুঙ্গির গিট খুইলা ডাইরেক্ট নিচে পইড়া গেলো! পার্কের আন্টিরা তোর মালসামানা দেইখা চিল্লান দিয়া ভাইগা গেলো!',
        tone: 'bad',
      },
      {
        id: 'laugh_brisk_lap',
        text: 'হাসি বাদ দিয়া ছড়ি ধইরা লেংড়াইয়া লেংড়াইয়া হাঁট!',
        effects: { health: 8, happiness: 8 },
        outcomeText: 'হাঁটতে গিয়া তুই এক্কেরে ড্রেনে ডাইভ দিলি! ড্রেনের পচা কাদা মাইখা তুই এহন পার্কের নতুন ভূত!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_memoir_handwritten_journal',
    text: 'আত্মজীবনী লেইখা দুনিয়ারে তুই জ্ঞান দিবি! মনে করতাছোস তুই নেলসন ম্যান্ডেলা!',
    minAge: 60,
    maxAge: 105,
    weight: 70,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle', 'smarts'],
    choices: [
      {
        id: 'memoir_write_daily',
        text: 'কলম ধইরা নিজের সব বাটপারি আর পরকীয়ার কথা লেইখা ফ্যাল!',
        effects: { smarts: 8, happiness: 14, karma: 8 },
        outcomeText: 'তোর বই পইড়া তোর বউ তোরে এমুন ঝাড়ুপেটা করলো, তুই বাড়ি থিকা ডাইরেক্ট বাইর! এহন রাস্তায় বইসা বই বেচ হালায়!',
        tone: 'bad',
      },
      {
        id: 'memoir_audio_record',
        text: 'ক্যাসেট রেকর্ডারে গাইল দিয়া রেকর্ড কর!',
        effects: { fame: 6, happiness: 12, karma: 10 },
        outcomeText: 'রেকর্ড শুইনা ফ্যামিলির সবাই তোরে মানসিক হাসপাতালে ভর্তি কইরা দিছে! তুই এহন পাগলাগারদে বইসা হাওয়া খা!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_vintage_radio_repair',
    text: 'বাপের আমলের পুরান রেডিও বাইর কইরা মেকানিক সাজতে গেছোস! রেডিও হালায় ঘ্যাঁড় ঘ্যাঁড় করতাছে!',
    minAge: 52,
    maxAge: 95,
    weight: 65,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'radio_solder_antenna',
        text: 'তার জোড়া লাগাইতে গিয়া কারেন্টের ডাইরেক্ট শট খা!',
        effects: { smarts: -10, happiness: -20 },
        outcomeText: 'এমুন শট খাইলি যে তোর চান্দির চুল খাড়া হইয়া আইনস্টাইন হইয়া গেলো! ডরে তুই প্যান্টে মুইতা দিছোস, পুরা ঘর মুতের গন্ধে ভরে গেছে!',
        tone: 'bad',
      },
      {
        id: 'radio_listen_balcony',
        text: 'রেডিওতে থাপ্পড় মাইরা চালু করার ট্রাই কর!',
        effects: { happiness: 10, health: -5 },
        outcomeText: 'রেডিও চালু হইলো ঠিকই, কিন্তু ফুল ভলিউমে হারবাল ওষুধের সেক্স-পাওয়ার বড়ির এডভার্টাইজ বাজানো শুরু করলো! মেহমানদের সামনে তোর ইজ্জত পাংচার!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_golden_wedding_jubilee',
    text: 'বিয়ার ৫০ বছর! বুড়ি এহনও তোরে গাইল পাড়ে, আর তুই হালায় রোমান্স খুঁজতাছোস!',
    minAge: 68,
    maxAge: 105,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['romance', 'family'],
    choices: [
      {
        id: 'jubilee_garland_exchange',
        text: 'বুড়িরে গোলাপ ফুল দিয়া ফিল্মি স্টাইলে প্রপোজ কর!',
        effects: { happiness: 25, karma: 18, fame: 10 },
        outcomeText: 'বুড়ি গোলাপের কাঁটায় খোঁচা খায়া মেজাজ ফায়ার! তোর মুখে এমুন এক থাপ্পড় দিলো, তোর ফলস দাঁত খুইলা ড্রেনে পইড়া গেলো!',
        tone: 'bad',
      },
      {
        id: 'jubilee_endow_school',
        text: 'খুশিতে ফ্যামিলিরে পার্টি দিয়া সব ট্যাকা উড়া!',
        effects: { karma: 25, fame: 12, money: -150, happiness: 20 },
        outcomeText: 'পার্টি দিতে গিয়া তুই ফকির হইয়া গেলি! এহন তুই আর তোর বুড়ি রাস্তায় বইসা হারমোনিয়াম বাজায়া গান গা!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_chess_under_banyan',
    text: 'বটতলায় বইসা আরেক বুইড়ার লগে দাবা খেলার ফাপড়! তুই এহন গ্যারি কাসপারভ!',
    minAge: 55,
    maxAge: 100,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle', 'smarts'],
    choices: [
      {
        id: 'chess_queen_sacrifice',
        text: 'চাপাবাজি কইরা চাল দে আর অপোনেন্টের গুটি চুরি কর!',
        effects: { smarts: -15, happiness: -20, fame: -10 },
        outcomeText: 'চুরি ধইরা ফালাইছে! বুইড়া হালায় দাবার বোর্ড তুইলা তোর মাথায় এমুন বাড়ি মারলো, তুই এহন ডাইরেক্ট হাসপাতালে বেহুঁশ!',
        tone: 'bad',
      },
      {
        id: 'chess_draw_chai',
        text: 'হার নিশ্চিত দেইখা চা খাওয়ার নাম কইরা ম্যাচ ড্র কর!',
        effects: { happiness: 10, karma: -5 },
        outcomeText: 'চা খাইতে গিয়া তোর গলায় বিস্কুট আটকাইয়া তুই এমুন বিষম খাইলি, পাবলিক ভাবলো তোর মৃগী রোগ উঠছে! ইজ্জতের পুরাই ফালুদা!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_community_wisdom_arbitrator',
    text: 'মহল্লার গ্যাঞ্জামে তোরে বিচারক বানাইছে, দুই পার্টির থিকা ঘুষ খাওয়ার সুবর্ণ সুযোগ!',
    minAge: 60,
    maxAge: 100,
    weight: 70,
    tone: 'good',
    category: 'senior',
    tags: ['community', 'karma'],
    choices: [
      {
        id: 'arbitrate_just_solution',
        text: 'টেবিলে থাপ্পড় মাইরা কড়া একখান জাজমেন্ট ফালায়া দে!',
        effects: { karma: -20, fame: -15, smarts: -10, happiness: -25 },
        outcomeText: 'তোর থাপ্পড়ে টেবিল ভাইঙ্গা গেলো আর তুই নিজেই উল্টায়া পড়লি! পোলাপাইন বিচার বাদ দিয়া তোরে নিয়া হাসতে হাসতে কাইত!',
        tone: 'funny',
      },
      {
        id: 'arbitrate_tea_hospitality',
        text: 'এক পার্টির থিকা চুপিচুপি মিষ্টির প্যাকেট ঘুষ খা!',
        effects: { karma: -30, happiness: -20, money: 50 },
        outcomeText: 'ঘুষ খাওয়ার ভিডিও ফেসবুকে ভাইরাল! তুই এহন মহল্লার "ঘুষখোর বুইড়া"! পোলাপাইন তোরে দেখলে থুতু মারে!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_birdwatching_sanctuary',
    text: 'দূরবীন দিয়া পাখি দেখার নাম কইরা তুই হালায় পাশের বাড়ির আন্টিরে ছাদে কাপড় শুকাতে দেখতাছোস! লুচ্চা বুইড়া!',
    minAge: 52,
    maxAge: 105,
    weight: 70,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'bird_spot_rare_kingfisher',
        text: 'দূরবীন ঘুরাইয়া আন্টির দিকে ফোকাস কর!',
        effects: { happiness: -25, smarts: -15, health: -20 },
        outcomeText: 'আন্টির জামাই তোরে দেইখা ফালাইছে! ছাদে আইসা তোর দূরবীন ভাইঙ্গা তোর পাছায় এমুন লাথি মারলো, তুই ডাইরেক্ট রাস্তার ডাস্টবিনে!',
        tone: 'bad',
      },
      {
        id: 'bird_teach_grandchild',
        text: 'ভালো মানুষ সাইজা নাতিরে দূরবীন দিয়া কাক দেখা!',
        effects: { karma: 10, happiness: -10 },
        outcomeText: 'নাতি দূরবীন দিয়া দেখলো এক কুত্তা রাস্তার মোড়ে হাগু করতাছে! তোর বার্ডওয়াচিং পুরাই গু-ওয়াচিংয়ে পরিণত হইলো!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_family_recipe_compendium',
    text: 'তোর বিখ্যাত কাচ্চির রেসিপি নিয়া পোলাপাইন পাগল! এহন রেসিপি শিখানোর টাইম!',
    minAge: 55,
    maxAge: 95,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['family'],
    choices: [
      {
        id: 'recipe_hands_on_masterclass',
        text: 'ভাব নিয়া রান্নাঘরে গিয়া নিজেই কাচ্চি রান্ধার ট্রাই কর!',
        effects: { happiness: -30, karma: -20, looks: -15 },
        outcomeText: 'লবণ দিতে গিয়া তুই পুরা এক ডিব্বা লবণ ঢাইলা দিছোস! কাচ্চি খায়া ফ্যামিলির সবার ডাইরিয়া, তোরে এহন কেউ ঘরে ঢুকতে দেয় না!',
        tone: 'bad',
      },
      {
        id: 'recipe_calligraphy_booklet',
        text: 'ভুয়া রেসিপি লেইখা পোলাপাইনরে ফাপড় দে!',
        effects: { smarts: -10, happiness: 15, karma: -15 },
        outcomeText: 'তোর ভুয়া রেসিপিতে কাচ্চি রান্ধতে গিয়া পুরা রান্নাঘরে আগুন ধইরা গেলো! ফায়ার সার্ভিস আইসা আগুন নিভাইলো, আর তুই ডরে বাথরুমে লুকায়া আছোস!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_heritage_village_visit',
    text: 'গ্রামে গিয়া জমিদারের লাহান ভাব নিতে গেছোস! গিয়া দেখস তোর বাপের ভিটায় এহন কুত্তায় মুতে!',
    minAge: 55,
    maxAge: 105,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle', 'family'],
    choices: [
      {
        id: 'village_dip_feet_water',
        text: 'পুকুরে পা চুবাইয়া নস্টালজিক হওয়ার ভাব ল!',
        effects: { health: -15, happiness: -20, karma: -10 },
        outcomeText: 'পুকুরে পা দিতেই এক বিশাল জোক তোর আঙ্গুলে এমুন কামড় দিলো, তুই চিল্লায়া পুরা গ্রাম মাথায় তুললি! রক্তারক্তি অবস্থা!',
        tone: 'bad',
      },
      {
        id: 'village_gift_primary_school',
        text: 'গ্রামে গিয়া দানবীর সাইজা স্কুলে ট্যাকা দে!',
        effects: { karma: 20, happiness: -25, fame: 8, money: -500 },
        outcomeText: 'ট্যাকা দেওয়ার পর শুনলি স্কুলের হেডমাস্টার ওই ট্যাকা দিয়া নিজের মাইয়ার বিয়া দিয়া দিছে! তুই পুরাই স্ক্যাম খাইলি, হালায় বোকাচোদা!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_cataract_vision_restoration',
    text: 'চোখের ছানি কাটার পর দুনিয়া এহন ফোরকে (4K)! তুই এহন নতুন কইরা দুনিয়া দেখতাছোস!',
    minAge: 62,
    maxAge: 105,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['health'],
    choices: [
      {
        id: 'cataract_laser_surgery',
        text: 'খুশিতে আয়নার সামনে গিয়া নিজের চেহারা দ্যাখ!',
        effects: { health: 12, happiness: -30, money: -8, looks: -20 },
        outcomeText: 'নিজের চেহারা দেইখা তুই নিজেই ডরাইয়া গেলি! "হায়রে, আমি তো জ্যান্ত মমি!" ডরে তুই আবার চোখ বন্ধ কইরা ফালাইলি!',
        tone: 'funny',
      },
      {
        id: 'cataract_read_new_books',
        text: 'বই পড়ার নাম কইরা লুকাইয়া চটি বই পড়া শুরু কর!',
        effects: { smarts: -10, happiness: -20 },
        outcomeText: 'বই পড়তে গিয়া বউ তোরে ধইরা ফালাইলো! "লুচ্চা বুইড়া" বইলা এমুন ঝাড়ুপেটা করলো, তোর চোখের চশমা ভাইঙ্গা আবার ছানি পইড়া গেলো!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_philanthropic_endowment',
    text: 'মরার আগে পাপ মোচনের লাইগা ট্যাকা দান করার ধান্দা! তুই এহন হাজি সাব সাজতে চাস!',
    minAge: 65,
    maxAge: 110,
    weight: 70,
    tone: 'good',
    category: 'senior',
    tags: ['wealth', 'karma'],
    choices: [
      {
        id: 'endow_free_clinic',
        text: 'হাসপাতাল বানানোর লাইগা ট্যাকা দিয়া বিশাল সাইনবোর্ড লাগা!',
        effects: { karma: -10, fame: -20, money: -250, happiness: -30 },
        outcomeText: 'সাইনবোর্ডে তোর নামের জায়গায় ভুল কইরা লেইখা দিছে "কঞ্জুস মকসদ মেমোরিয়াল ক্লিনিক"! পাবলিক তোরে নিয়া হাসতাছে, ট্যাকাও গেলো, ইজ্জতও গেলো!',
        tone: 'bad',
      },
      {
        id: 'endow_modest_trust',
        text: 'ট্রাস্ট বানায়া ফ্যামিলির ট্যাকা ফাঁকি দেওয়ার প্ল্যান কর!',
        effects: { karma: -30, money: -100, happiness: -40 },
        outcomeText: 'তোর পোলারা তোর চালাকি ধইরা তোরে এমুন মাইর দিলো, তুই এহন নিজেই ওই ক্লিনিকের পয়লা রোগী হইয়া বেডে শুইয়া আছোস!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_centenarian_birthday_feast',
    text: '১০০ বছর বাইচা আছোস! যমদূত তোরে ভুইলা গেছে হালায়! তোর চেহারা এহন পুরাই শুঁটকি মাছের লাহান!',
    minAge: 95,
    maxAge: 120,
    weight: 85,
    tone: 'good',
    category: 'senior',
    tags: ['family', 'fame'],
    choices: [
      {
        id: 'centenary_bless_posterity',
        text: '১০০টা মোমবাতি ফুঁ দিয়া নিভানোর ফাপড় নে!',
        effects: { happiness: -20, karma: -10, health: -30 },
        outcomeText: 'ফুঁ দিতে গিয়া তোর ফলস দাঁত উইড়া গিয়া কেকের মইধ্যে গাঁইথা গেলো! আর তুই অক্সিজেনের অভাবে ডাইরেক্ট বেহুঁশ! বার্থডে পার্টি এহন কুলখানি!',
        tone: 'funny',
      },
      {
        id: 'centenary_share_secret',
        text: 'সাংবাদিকরে লম্বা আয়ুর ফাপড়বাজি টিপস দে!',
        effects: { happiness: 24, fame: -20, looks: -15 },
        outcomeText: 'টিপস দিতে গিয়া তুই কইয়া ফালালি, "আমি ডেইলি আধা বোতল বাংলা মদ খাই!" তোর ইজ্জতের ফালুদা, ফ্যামিলি তোরে ঘর থিকা বাইর কইরা দিলো!',
        tone: 'bad',
      },
    ],
  },
];