import type { LifeEventDef } from '@/lib/engine/types';

/**
 * Senior pool (ages 66+): retirement, grandchildren, health with dignity,
 * legacy and memory, and the passing of loved ones handled with reverence.
 * Sensitive-content policy per DESIGN.md §11 — bereavement is selectable and
 * supportive, never presented as an option to self-harm.
 */
export const SENIOR_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'se_retirement_day',
    text: 'The last day of work arrives and the staff lounge has a cake with your name across it.',
    minAge: 60,
    maxAge: 75,
    weight: 95,
    tone: 'good',
    category: 'senior',
    tags: ['career', 'milestone'],
    choices: [
      {
        id: 'se_retire_soft',
        text: 'Retire softly and hand over your notebooks',
        effects: { happiness: 8, health: 3, addFlag: 'retired' },
        outcomeText: 'The cake is gone by Thursday. The mornings stretch out, gladly.',
        tone: 'good',
      },
      {
        id: 'se_retire_consult',
        text: 'Retire, but offer to consult two days a week',
        effects: { money: 6, happiness: 4, smarts: 2 },
        outcomeText: 'You keep a toe in the river without drowning in it.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_grandkids_barrage',
    text: 'Grandchildren arrive for the summer with a pile of questions and very loud opinions.',
    minAge: 60,
    maxAge: 85,
    weight: 80,
    tone: 'good',
    category: 'senior',
    tags: ['family'],
    requiredFlags: ['has_child'],
    choices: [
      {
        id: 'se_grand_expeditions',
        text: 'Plan daily expeditions, park and ice cream',
        effects: { happiness: 12, health: -2 },
        outcomeText: 'By August you are their favourite storyteller and the ice cream shop knows you.',
        tone: 'good',
      },
      {
        id: 'se_grand_fisherman',
        text: 'Teach them the quiet crafts instead',
        effects: { happiness: 8, smarts: 3 },
        outcomeText: 'Whittling, kites, and card tricks. The quiet projects hold loud memories.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_spouse_care',
    text: 'Your spouse\'s steps have slowed, and the world rearranges itself around their needs.',
    minAge: 65,
    maxAge: 90,
    weight: 55,
    tone: 'neutral',
    category: 'senior',
    tags: ['family', 'health'],
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'se_care_patient',
        text: 'Take on the care with patience and help',
        effects: { happiness: 6, health: -4, karma: 6 },
        outcomeText: 'Small rituals anchor the days. You are both still laughing at your old jokes.',
        tone: 'good',
      },
      {
        id: 'se_care_share',
        text: 'Arrange carers early and guard your own health',
        effects: { health: 3, happiness: 3, money: -6 },
        outcomeText: 'Professionals help, and you both keep more of your evenings.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_downsize_choice',
    text: 'The big house echoes for two. The agent puts a sensible number on the lawn.',
    minAge: 65,
    maxAge: 85,
    weight: 65,
    tone: 'neutral',
    category: 'senior',
    tags: ['lifestyle', 'finance'],
    choices: [
      {
        id: 'se_downsize_flat',
        text: 'Move to the sunny flat by the park',
        effects: { happiness: 8, money: 8, health: 3 },
        outcomeText: 'One lift, no staircase, and a bench that knows your name. Lighter.',
        tone: 'good',
      },
      {
        id: 'se_downsize_stay',
        text: 'Stay put amid the familiar walls',
        effects: { happiness: 5, money: -4 },
        outcomeText: 'The rooms keep their ghosts and their warmth. The stairs get opinions.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_pension_plan',
    text: 'The pension paperwork arrives and asks for the traditional heroic decision.',
    minAge: 65,
    maxAge: 80,
    weight: 60,
    tone: 'neutral',
    category: 'senior',
    tags: ['finance'],
    choices: [
      {
        id: 'se_pension_steady',
        text: 'Take the guaranteed monthly amount',
        effects: { money: 10, happiness: 2 },
        outcomeText: 'Steady as tides. The small numbers add up to a warm, predictable year.',
        tone: 'good',
      },
      {
        id: 'se_pension_lump',
        text: 'Take the lump sum for one grand trip',
        effects: { money: 12, happiness: 8, health: -2 },
        outcomeText: 'One enormous holiday, framed photos, and a quieter ledger after.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_bucket_last_page',
    text: 'Your notebook of "someday" trips still has one untouched page.',
    minAge: 66,
    maxAge: 85,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['travel'],
    choices: [
      {
        id: 'se_bucket_go',
        text: 'Book the train ride you always postponed',
        effects: { happiness: 10, money: -6 },
        outcomeText: 'The window seat, the rattle, the new town. The page gets ceremonially crossed off.',
        tone: 'good',
      },
      {
        id: 'se_bucket_photobook',
        text: 'Rebuild the trip from old photos instead',
        effects: { happiness: 7 },
        outcomeText: 'The scrapbook version is somehow just as good, and dust-free.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_health_knees',
    text: 'Your joints file a formal complaint about stairs, cold days, and morning in general.',
    minAge: 70,
    maxAge: 95,
    weight: 60,
    tone: 'bad',
    category: 'senior',
    tags: ['health'],
    choices: [
      {
        id: 'se_knees_move',
        text: 'Join the chair-yoga group at the hall',
        effects: { health: 6, happiness: 4 },
        outcomeText: 'Slow, gentle, and oddly joyful. The knees register the improvement.',
        tone: 'good',
      },
      {
        id: 'se_knees_grump',
        text: 'Blame the weather and move less',
        effects: { health: -4, happiness: -3 },
        outcomeText: 'The armchair collects you. The joints collect their grievances.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_reconnect_old_friends',
    text: 'A classmate from decades ago emails a list of everyone, and where they ended up.',
    minAge: 70,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['friendship'],
    choices: [
      {
        id: 'se_friends_reunion',
        text: 'Go to the reunion and swap fifty years of stories',
        effects: { happiness: 12, smarts: 3 },
        outcomeText: 'You laugh at the same jokes and add new ones. Time folds pleasantly.',
        tone: 'good',
      },
      {
        id: 'se_friends_letters',
        text: 'Renew a long-dormant pen-friendship instead',
        effects: { happiness: 8 },
        outcomeText: 'Two letters a year, handwritten, unfashionable, and priceless.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_legacy_notebook',
    text: 'Your grandchild asks what you \'used to do all day\' and you realise an answer would be nice.',
    minAge: 70,
    maxAge: 95,
    weight: 65,
    tone: 'good',
    category: 'senior',
    tags: ['legacy'],
    choices: [
      {
        id: 'se_legacy_write',
        text: 'Write the small memoir, one memory at a time',
        effects: { happiness: 9, smarts: 4, karma: 3 },
        outcomeText: 'Seventy short chapters. The grandchild reads them twice.',
        tone: 'good',
      },
      {
        id: 'se_legacy_recite',
        text: 'Record your stories on voice notes instead',
        effects: { happiness: 7, karma: 2 },
        outcomeText: 'Your voice, your pauses, your laugh at the punchlines. All saved.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_garden_society',
    text: 'The community garden elected you to the watering rota purely on reputation.',
    minAge: 70,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['community', 'health'],
    choices: [
      {
        id: 'se_garden_own',
        text: 'Take the corner plot and grow tomatoes',
        effects: { happiness: 9, health: 4, karma: 2 },
        outcomeText: 'A dozen jars of sauce later, your shelves carry your summer.',
        tone: 'good',
      },
      {
        id: 'se_garden_advise',
        text: 'Advise loudly from a comfortable chair',
        effects: { happiness: 5, smarts: 1 },
        outcomeText: 'Your opinions are accepted with affectionate eye-rolls.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_companion_cat',
    text: 'The shelter introduces a dignified senior cat who has learned to approve of you.',
    minAge: 70,
    maxAge: 95,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['pet', 'companion'],
    choices: [
      {
        id: 'se_cat_adopt',
        text: 'Adopt the cat and share the armchair',
        effects: { happiness: 10, health: 2 },
        outcomeText: 'The cat supervises breakfasts, naps, and your entire day. Authority happily ceded.',
        tone: 'good',
      },
      {
        id: 'se_cat_visit',
        text: 'Visit the cat weekly at the shelter instead',
        effects: { happiness: 5, karma: 2 },
        outcomeText: 'You are the favourite visitor. The cat says so, with its eyes.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_reading_circle',
    text: 'The library starts an evening circle and someone puts your name forward, kindly.',
    minAge: 70,
    maxAge: 95,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['hobby', 'social'],
    choices: [
      {
        id: 'se_reading_join',
        text: 'Join and bring your strong opinions',
        effects: { happiness: 8, smarts: 4 },
        outcomeText: 'You defend a minor character fiercely. Everyone warms to you.',
        tone: 'good',
      },
      {
        id: 'se_reading_lead',
        text: 'Offer to lead the next month\'s pick',
        effects: { happiness: 7, smarts: 5, karma: 2 },
        outcomeText: 'Your chosen book divides the room. Perfect discussion material.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_sage_advice',
    text: 'A young colleague, now middle-aged, phones for a no-frills opinion on a big choice.',
    minAge: 68,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['community', 'mentor'],
    choices: [
      {
        id: 'se_sage_speak',
        text: 'Give the honest, kind, complicated answer',
        effects: { happiness: 7, karma: 4 },
        outcomeText: 'They write it down. A year later they quote it back to you, exactly.',
        tone: 'good',
      },
      {
        id: 'se_sage_listen',
        text: 'Mostly listen, which is what they needed',
        effects: { happiness: 6, karma: 3 },
        outcomeText: 'A long silence, then: "Thank you. That helped."',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_comfort_visit',
    text: 'Your old neighbour is back in hospital, and the family asks if you might drop by.',
    minAge: 70,
    maxAge: 95,
    weight: 45,
    tone: 'neutral',
    category: 'senior',
    tags: ['health', 'community'],
    choices: [
      {
        id: 'se_visit_presence',
        text: 'Go, sit, and tell old stories',
        effects: { happiness: 7, karma: 5 },
        outcomeText: 'The stories work better than any gift. The nurse smiles at both of you.',
        tone: 'good',
      },
      {
        id: 'se_visit_card',
        text: 'Send a card with a pressed flower',
        effects: { happiness: 3, karma: 2 },
        outcomeText: 'The flower finds its way to the bedside table.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_widowhood_kind',
    text: 'Losing your spouse leaves an ordinary Tuesday suddenly enormous. The house is too quiet.',
    minAge: 65,
    maxAge: 100,
    weight: 40,
    tone: 'bad',
    category: 'senior',
    tags: ['family', 'grief'],
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'se_widow_grief',
        text: 'Let the grief move through you slowly, with help',
        effects: { happiness: -6, health: -3, smarts: 3 },
        outcomeText: 'Support groups and slow walks help. The grief stays, but gentler.',
        tone: 'bad',
      },
      {
        id: 'se_widow_memory',
        text: 'Plant a tree and keep their chair',
        effects: { happiness: 4, karma: 3, addFlag: 'widowed', removeFlag: 'has_spouse' },
        outcomeText: 'The tree grows. The chair stays. The two of them argue no more.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_memory_project',
    text: 'The family starts a project to gather voices and faces before stories blur.',
    minAge: 72,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['family', 'legacy'],
    choices: [
      {
        id: 'se_memory_join',
        text: 'Sit for the interviews and the photo album',
        effects: { happiness: 9, karma: 4 },
        outcomeText: 'The album has your laugh on every page. Future generations will know it.',
        tone: 'good',
      },
      {
        id: 'se_memory_count',
        text: 'Help sort the shoeboxes of photographs',
        effects: { happiness: 7, smarts: 3 },
        outcomeText: 'You label the faces the younger ones had no hope of placing.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_bridge_club',
    text: 'The community hall runs a bridge evening where the stakes are biscuits and the trash talk is legendary.',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['social', 'hobby'],
    choices: [
      {
        id: 'bridge_learn',
        text: 'Learn the game properly',
        effects: { smarts: 5, happiness: 5 },
        outcomeText: 'A year later, you are the feared biscuit champion of table three.',
        tone: 'good',
      },
      {
        id: 'bridge_watch',
        text: 'Watch and referee the great arguments',
        effects: { happiness: 3, karma: 3 },
        outcomeText: 'Your ruling on the biscuits is final and universally respected.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_technology_class',
    text: 'The library offers a "great-grandchildren-proof" technology class and everyone wants your seat.',
    minAge: 70,
    maxAge: 100,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['education', 'social'],
    choices: [
      {
        id: 'techclass_stay',
        text: 'Take the class to the end, slow as syrup',
        effects: { smarts: 7, happiness: 4 },
        outcomeText: 'You can now video-call, mute, and unmute, in any weather.',
        tone: 'good',
      },
      {
        id: 'techclass_note',
        text: 'Take precise handwritten notes for the others',
        effects: { happiness: 4, karma: 4 },
        outcomeText: 'Your notes in the margin are now class lore.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_genealogy_trip',
    text: 'A family tree website shows a branch that leads somewhere interesting, and tickets are cheap.',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['legacy', 'family', 'travel'],
    choices: [
      {
        id: 'genealogy_visit',
        text: 'Visit the town and find the old records',
        effects: { happiness: 7, smarts: 3, money: -5 },
        outcomeText: 'The records confirm the family rumour and the town is lovely.',
        tone: 'good',
      },
      {
        id: 'genealogy_chart',
        text: 'Build the full chart at the kitchen table',
        effects: { smarts: 5, happiness: 3 },
        outcomeText: 'Forty names now have faces and stories. The chart gets framed.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_letters_to_future',
    text: 'Your hundred-year-old self has been requested for letters, addressed with tenderness and humour.',
    minAge: 70,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['legacy'],
    choices: [
      {
        id: 'letters_write',
        text: 'Write a letter for each grandchild\'s next birthday',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'The letters wait in a shoebox, sealed, and hugely loved.',
        tone: 'good',
      },
      {
        id: 'letters_tape',
        text: 'Record a short message instead',
        effects: { happiness: 6, karma: 2 },
        outcomeText: 'Your voice, saved. Decades from now it will still make them smile.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_reminiscence_table',
    text: 'The care home next door starts a memory circle and invites regulars to bring one object each.',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['community'],
    choices: [
      {
        id: 'reminiscence_share',
        text: 'Bring one object and tell its story',
        effects: { happiness: 7, karma: 4 },
        outcomeText: 'The room goes quiet, then warm. You are invited back every month.',
        tone: 'good',
      },
      {
        id: 'reminiscence_listen',
        text: 'Come and listen to the others',
        effects: { happiness: 5, smarts: 3 },
        outcomeText: 'Some afternoons, listening is the whole gift.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_morning_walk',
    text: 'A gentle morning walk now has the discipline of a habit and the prize of a very good bench.',
    minAge: 66,
    maxAge: 100,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['health'],
    choices: [
      {
        id: 'morningwalk_soon',
        text: 'Make the walk the day\'s first appointment',
        effects: { health: 7, happiness: 5 },
        outcomeText: 'The bench, the birds, the routine. The day starts right.',
        tone: 'good',
      },
      {
        id: 'morningwalk_garden',
        text: 'Trade the walk for ten minutes in the garden',
        effects: { health: 4, happiness: 4 },
        outcomeText: 'The garden also counts, and says so proudly.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_grandchild_bedtime_stories',
    text: 'Your grandchildren climb into bed, pleading for {tales of mythical river spirits and trickster foxes|stories of your mischievous childhood pranks}.',
    minAge: 55,
    maxAge: 95,
    weight: 80,
    tone: 'good',
    category: 'senior',
    tags: ['family'],
    choices: [
      {
        id: 'story_theatrical_voices',
        text: 'Narrate with dramatic character voices, spooky whispers, and sound effects',
        effects: { happiness: 16, karma: 10, smarts: 4 },
        outcomeText: 'Their wide-eyed wonder and giggles made your heart swell with boundless joy.',
        tone: 'good',
      },
      {
        id: 'story_ancestral_history',
        text: 'Tell the true historical courage of how your grandparents built their home',
        effects: { karma: 12, smarts: 6, happiness: 10 },
        outcomeText: 'They listened with solemn respect, treasuring their family roots.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_morning_park_laughter_club',
    text: 'At sunrise in the municipal botanical park, a lively circle of seniors invites you to join {the rhythmic clapping laughter club|morning deep pranayama breathing}.',
    minAge: 55,
    maxAge: 100,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['health', 'community'],
    choices: [
      {
        id: 'laugh_belly_hearty',
        text: 'Throw head back and unleash uncontrollable hearty belly laughter with the crowd',
        effects: { health: 10, happiness: 16, looks: 4 },
        outcomeText: 'Endorphins flooded your veins! You walked home with a spring in your step.',
        tone: 'good',
      },
      {
        id: 'laugh_brisk_lap',
        text: 'Complete two brisk walking laps around the lotus pond with your walking cane',
        effects: { health: 8, happiness: 8 },
        outcomeText: 'Fresh morning air filled your lungs. The body feels nimble and primed.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_memoir_handwritten_journal',
    text: 'With quiet afternoons to spare, you acquire a fountain pen to write {your life memoirs|a compendium of life advice for your descendants}.',
    minAge: 60,
    maxAge: 105,
    weight: 70,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle', 'smarts'],
    choices: [
      {
        id: 'memoir_write_daily',
        text: 'Write two pages every afternoon recounting love, struggle, and hard-earned wisdom',
        effects: { smarts: 8, happiness: 14, karma: 8 },
        outcomeText: 'Completed a poignant manuscript that family members wept over and bound into print.',
        tone: 'good',
      },
      {
        id: 'memoir_audio_record',
        text: 'Record spoken stories on your smartphone for grandchildren to listen to anytime',
        effects: { fame: 6, happiness: 12, karma: 10 },
        outcomeText: 'Your warm voice and laughter preserved forever across generations.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_vintage_radio_repair',
    text: 'You discover an old wooden tube radio in the attic, crackling softly with {nostalgic classical music|vintage live cricket broadcast static}.',
    minAge: 52,
    maxAge: 95,
    weight: 65,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'radio_solder_antenna',
        text: 'Solder the aerial wire with a delicate hand until rich, warm analog sound flows',
        effects: { smarts: 6, happiness: 12 },
        outcomeText: 'Mellow melodies filled the room, transporting you straight back to the golden era.',
        tone: 'good',
      },
      {
        id: 'radio_listen_balcony',
        text: 'Place it on the veranda table while sipping afternoon cardamom tea',
        effects: { happiness: 10, health: 3 },
        outcomeText: 'Peaceful breeze, melodious strings, and memories drifting by like clouds.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_golden_wedding_jubilee',
    text: 'You and your partner celebrate a miraculous fifty years of marriage! Four generations gather for {a golden jubilee gala|a blessed family prayer feast}.',
    minAge: 68,
    maxAge: 105,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['romance', 'family'],
    choices: [
      {
        id: 'jubilee_garland_exchange',
        text: 'Re-exchange fragrant jasmine garlands, holding hands as cameras flash',
        effects: { happiness: 25, karma: 18, fame: 10 },
        outcomeText: 'Half a century of unconditional loyalty, shared laughter, and unwavering love.',
        tone: 'good',
      },
      {
        id: 'jubilee_endow_school',
        text: 'Sponsor a full university scholarship fund in your partner honor',
        effects: { karma: 25, fame: 12, money: -15, happiness: 20 },
        outcomeText: 'A legacy of compassion that outlives lifetimes. Deep, profound fulfillment.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_chess_under_banyan',
    text: 'Every afternoon under the spreading banyan tree, an old friend sets up a wooden chess board for {an intense tactical showdown|a battle of veteran minds}.',
    minAge: 55,
    maxAge: 100,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle', 'smarts'],
    choices: [
      {
        id: 'chess_queen_sacrifice',
        text: 'Execute a brilliant queen sacrifice leading to an inevitable checkmate',
        effects: { smarts: 10, happiness: 14, fame: 4 },
        outcomeText: 'Onlookers gasped in awe! Your rival tipped their king with a broad respectful grin.',
        tone: 'good',
      },
      {
        id: 'chess_draw_chai',
        text: 'Offer a friendly stalemate draw and split a pot of spiced street tea',
        effects: { happiness: 10, karma: 6 },
        outcomeText: 'Forty years of rivalry turned into forty years of unbreakable brotherhood.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_community_wisdom_arbitrator',
    text: 'A neighborhood dispute over property boundaries is brought to your veranda by neighbors seeking {your fair elder arbitration|your impartial moral guidance}.',
    minAge: 60,
    maxAge: 100,
    weight: 70,
    tone: 'good',
    category: 'senior',
    tags: ['community', 'karma'],
    choices: [
      {
        id: 'arbitrate_just_solution',
        text: 'Listen patiently to both sides and propose an equitable compromise rooted in fairness',
        effects: { karma: 20, fame: 12, smarts: 8, happiness: 10 },
        outcomeText: 'Both parties shook hands, shared sweets, and praised your Solomon-like wisdom.',
        tone: 'good',
      },
      {
        id: 'arbitrate_tea_hospitality',
        text: 'Serve sweet refreshments first and remind them of three decades of friendly neighborliness',
        effects: { karma: 16, happiness: 10 },
        outcomeText: 'Hot tea cooled fiery tempers. Reconciliation followed naturally.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_birdwatching_sanctuary',
    text: 'Migratory winter birds arrive by the lakeside. You set up binoculars and {a clay birdbath filled with sunflower seeds|a botanical observation notebook}.',
    minAge: 52,
    maxAge: 105,
    weight: 70,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'bird_spot_rare_kingfisher',
        text: 'Spot a rare iridescent blue kingfisher diving for minnows at sunrise',
        effects: { happiness: 14, smarts: 5, health: 3 },
        outcomeText: 'A flash of brilliant turquoise and ruby. Nature breathtaking splendor up close.',
        tone: 'good',
      },
      {
        id: 'bird_teach_grandchild',
        text: 'Teach your young grandchild how to identify local bird calls by ear',
        effects: { karma: 10, happiness: 12 },
        outcomeText: 'Their faces lit up with joy every time a robin chirped in response.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_family_recipe_compendium',
    text: 'Your adult children and nieces beg you to document {the secret spice proportions of your famous biryani|your traditional grandmother sweetmeats}.',
    minAge: 55,
    maxAge: 95,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['family'],
    choices: [
      {
        id: 'recipe_hands_on_masterclass',
        text: 'Gather the whole family in the kitchen for a lively weekend cooking masterclass',
        effects: { happiness: 18, karma: 12, looks: 2 },
        outcomeText: 'Aprons, laughter, and generational culinary magic passed down in full glory.',
        tone: 'good',
      },
      {
        id: 'recipe_calligraphy_booklet',
        text: 'Inscribe the recipes in an ornate leather notebook with handwritten historical notes',
        effects: { smarts: 6, happiness: 12, karma: 8 },
        outcomeText: 'The family prized possession, passed down with reverence.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_heritage_village_visit',
    text: 'You travel back to your rural ancestral village, walking down the red-dirt lane toward {the ancient family pond|the majestic grandfather banyan tree}.',
    minAge: 55,
    maxAge: 105,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['lifestyle', 'family'],
    choices: [
      {
        id: 'village_dip_feet_water',
        text: 'Sit on the old stone steps and dip your feet into the cool, crystal water',
        effects: { health: 6, happiness: 16, karma: 8 },
        outcomeText: 'Decades of memories washed over you with serene clarity. Home at last.',
        tone: 'good',
      },
      {
        id: 'village_gift_primary_school',
        text: 'Visit the local village school to donate brand new library desks and books',
        effects: { karma: 20, happiness: 16, fame: 8, money: -6 },
        outcomeText: 'Rapturous cheers from school children whose futures you blessed.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_cataract_vision_restoration',
    text: 'A safe, modern laser procedure promises to clear clouding cataracts and restore {crisp 20/20 daylight vision|vivid colors of the outside world}.',
    minAge: 62,
    maxAge: 105,
    weight: 75,
    tone: 'good',
    category: 'senior',
    tags: ['health'],
    choices: [
      {
        id: 'cataract_laser_surgery',
        text: 'Undergo the quick outpatient laser lens replacement procedure',
        effects: { health: 12, happiness: 18, money: -8, looks: 4 },
        outcomeText: 'Bandages removed: the world exploded in vibrant, crystalline colors! You wept with joy.',
        tone: 'good',
      },
      {
        id: 'cataract_read_new_books',
        text: 'Celebrate by reading your favorite classic novels without needing magnifying glasses',
        effects: { smarts: 6, happiness: 14 },
        outcomeText: 'Poring over delicate print with ease. A renewed lease on mental vitality.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_philanthropic_endowment',
    text: 'Looking over your lifetime assets, you decide to establish {a permanent medical clinic fund for elderly citizens|a science research endowment}.',
    minAge: 65,
    maxAge: 110,
    weight: 70,
    tone: 'good',
    category: 'senior',
    tags: ['wealth', 'karma'],
    choices: [
      {
        id: 'endow_free_clinic',
        text: 'Fund the construction of a free community diabetic and cardiac care center',
        effects: { karma: 30, fame: 20, money: -25, happiness: 20 },
        outcomeText: 'Thousands of underprivileged elders receive compassionate healing every year in your name.',
        tone: 'good',
      },
      {
        id: 'endow_modest_trust',
        text: 'Set up an educational micro-trust administered by trusted family trustees',
        effects: { karma: 18, money: -10, happiness: 14 },
        outcomeText: 'Generations of scholars will earn college degrees thanks to your foresight.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_centenarian_birthday_feast',
    text: 'Reaching the milestone age of one hundred, your family gathers hundreds of relatives for {a historic centenarian gala|a grand civic celebration attended by the city mayor}.',
    minAge: 95,
    maxAge: 120,
    weight: 85,
    tone: 'good',
    category: 'senior',
    tags: ['family', 'fame'],
    choices: [
      {
        id: 'centenary_bless_posterity',
        text: 'Blow out one hundred golden candles and gently place hands on each child head in blessing',
        effects: { happiness: 30, karma: 25, fame: 20 },
        outcomeText: 'A living legend! The mayor presented a ceremonial medal honoring your century of grace.',
        tone: 'good',
      },
      {
        id: 'centenary_share_secret',
        text: 'Wink and tell the television reporters that the real secret to longevity is laughing often',
        effects: { happiness: 24, fame: 18, looks: 6 },
        outcomeText: 'Your witty one-liner went viral nationwide, charming millions of hearts.',
        tone: 'good',
      },
    ],
  },
];