import type { LifeEventDef } from '@/lib/engine/types';

/**
 * Senior pool (ages 66+): retirement, grandchildren, health with dignity,
 * legacy and memory, and the passing of loved ones handled with reverence.
 * Sensitive-content policy per DESIGN.md §11 — bereavement is selectable and
 * supportive, never presented as an option to self-harm.
 */
export const SENIOR_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'se_retirement_day',
    text: 'The last day of work arrives and the staff lounge has a cake with your name across it.',
    minAge: 60,
    maxAge: 75,
    weight: 95,
    tone: 'good',
    category: 'senior',
    tags: ['career', 'milestone'],
    choices: [
      {
        id: 'se_retire_soft',
        text: 'Retire softly and hand over your notebooks',
        effects: { happiness: 8, health: 3, addFlag: 'retired' },
        outcomeText: 'The cake is gone by Thursday. The mornings stretch out, gladly.',
        tone: 'good',
      },
      {
        id: 'se_retire_consult',
        text: 'Retire, but offer to consult two days a week',
        effects: { money: 6, happiness: 4, smarts: 2 },
        outcomeText: 'You keep a toe in the river without drowning in it.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_grandkids_barrage',
    text: 'Grandchildren arrive for the summer with a pile of questions and very loud opinions.',
    minAge: 60,
    maxAge: 85,
    weight: 80,
    tone: 'good',
    category: 'senior',
    tags: ['family'],
    requiredFlags: ['has_child'],
    choices: [
      {
        id: 'se_grand_expeditions',
        text: 'Plan daily expeditions, park and ice cream',
        effects: { happiness: 12, health: -2 },
        outcomeText: 'By August you are their favourite storyteller and the ice cream shop knows you.',
        tone: 'good',
      },
      {
        id: 'se_grand_fisherman',
        text: 'Teach them the quiet crafts instead',
        effects: { happiness: 8, smarts: 3 },
        outcomeText: 'Whittling, kites, and card tricks. The quiet projects hold loud memories.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'se_spouse_care',
    text: 'Your spouse\'s steps have slowed, and the world rearranges itself around their needs.',
    minAge: 65,
    maxAge: 90,
    weight: 55,
    tone: 'neutral',
    category: 'senior',
    tags: ['family', 'health'],
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'se_care_patient',
        text: 'Take on the care with patience and help',
        effects: { happiness: 6, health: -4, karma: 6 },
        outcomeText: 'Small rituals anchor the days. You are both still laughing at your old jokes.',
        tone: 'good',
      },
      {
        id: 'se_care_share',
        text: 'Arrange carers early and guard your own health',
        effects: { health: 3, happiness: 3, money: -6 },
        outcomeText: 'Professionals help, and you both keep more of your evenings.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_downsize_choice',
    text: 'The big house echoes for two. The agent puts a sensible number on the lawn.',
    minAge: 65,
    maxAge: 85,
    weight: 65,
    tone: 'neutral',
    category: 'senior',
    tags: ['lifestyle', 'finance'],
    choices: [
      {
        id: 'se_downsize_flat',
        text: 'Move to the sunny flat by the park',
        effects: { happiness: 8, money: 8, health: 3 },
        outcomeText: 'One lift, no staircase, and a bench that knows your name. Lighter.',
        tone: 'good',
      },
      {
        id: 'se_downsize_stay',
        text: 'Stay put amid the familiar walls',
        effects: { happiness: 5, money: -4 },
        outcomeText: 'The rooms keep their ghosts and their warmth. The stairs get opinions.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_pension_plan',
    text: 'The pension paperwork arrives and asks for the traditional heroic decision.',
    minAge: 65,
    maxAge: 80,
    weight: 60,
    tone: 'neutral',
    category: 'senior',
    tags: ['finance'],
    choices: [
      {
        id: 'se_pension_steady',
        text: 'Take the guaranteed monthly amount',
        effects: { money: 10, happiness: 2 },
        outcomeText: 'Steady as tides. The small numbers add up to a warm, predictable year.',
        tone: 'good',
      },
      {
        id: 'se_pension_lump',
        text: 'Take the lump sum for one grand trip',
        effects: { money: 12, happiness: 8, health: -2 },
        outcomeText: 'One enormous holiday, framed photos, and a quieter ledger after.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_bucket_last_page',
    text: 'Your notebook of "someday" trips still has one untouched page.',
    minAge: 66,
    maxAge: 85,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['travel'],
    choices: [
      {
        id: 'se_bucket_go',
        text: 'Book the train ride you always postponed',
        effects: { happiness: 10, money: -6 },
        outcomeText: 'The window seat, the rattle, the new town. The page gets ceremonially crossed off.',
        tone: 'good',
      },
      {
        id: 'se_bucket_photobook',
        text: 'Rebuild the trip from old photos instead',
        effects: { happiness: 7 },
        outcomeText: 'The scrapbook version is somehow just as good, and dust-free.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_health_knees',
    text: 'Your joints file a formal complaint about stairs, cold days, and morning in general.',
    minAge: 70,
    maxAge: 95,
    weight: 60,
    tone: 'bad',
    category: 'senior',
    tags: ['health'],
    choices: [
      {
        id: 'se_knees_move',
        text: 'Join the chair-yoga group at the hall',
        effects: { health: 6, happiness: 4 },
        outcomeText: 'Slow, gentle, and oddly joyful. The knees register the improvement.',
        tone: 'good',
      },
      {
        id: 'se_knees_grump',
        text: 'Blame the weather and move less',
        effects: { health: -4, happiness: -3 },
        outcomeText: 'The armchair collects you. The joints collect their grievances.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'se_reconnect_old_friends',
    text: 'A classmate from decades ago emails a list of everyone, and where they ended up.',
    minAge: 70,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['friendship'],
    choices: [
      {
        id: 'se_friends_reunion',
        text: 'Go to the reunion and swap fifty years of stories',
        effects: { happiness: 12, smarts: 3 },
        outcomeText: 'You laugh at the same jokes and add new ones. Time folds pleasantly.',
        tone: 'good',
      },
      {
        id: 'se_friends_letters',
        text: 'Renew a long-dormant pen-friendship instead',
        effects: { happiness: 8 },
        outcomeText: 'Two letters a year, handwritten, unfashionable, and priceless.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_legacy_notebook',
    text: 'Your grandchild asks what you \'used to do all day\' and you realise an answer would be nice.',
    minAge: 70,
    maxAge: 95,
    weight: 65,
    tone: 'good',
    category: 'senior',
    tags: ['legacy'],
    choices: [
      {
        id: 'se_legacy_write',
        text: 'Write the small memoir, one memory at a time',
        effects: { happiness: 9, smarts: 4, karma: 3 },
        outcomeText: 'Seventy short chapters. The grandchild reads them twice.',
        tone: 'good',
      },
      {
        id: 'se_legacy_recite',
        text: 'Record your stories on voice notes instead',
        effects: { happiness: 7, karma: 2 },
        outcomeText: 'Your voice, your pauses, your laugh at the punchlines. All saved.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_garden_society',
    text: 'The community garden elected you to the watering rota purely on reputation.',
    minAge: 70,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['community', 'health'],
    choices: [
      {
        id: 'se_garden_own',
        text: 'Take the corner plot and grow tomatoes',
        effects: { happiness: 9, health: 4, karma: 2 },
        outcomeText: 'A dozen jars of sauce later, your shelves carry your summer.',
        tone: 'good',
      },
      {
        id: 'se_garden_advise',
        text: 'Advise loudly from a comfortable chair',
        effects: { happiness: 5, smarts: 1 },
        outcomeText: 'Your opinions are accepted with affectionate eye-rolls.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'se_companion_cat',
    text: 'The shelter introduces a dignified senior cat who has learned to approve of you.',
    minAge: 70,
    maxAge: 95,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['pet', 'companion'],
    choices: [
      {
        id: 'se_cat_adopt',
        text: 'Adopt the cat and share the armchair',
        effects: { happiness: 10, health: 2 },
        outcomeText: 'The cat supervises breakfasts, naps, and your entire day. Authority happily ceded.',
        tone: 'good',
      },
      {
        id: 'se_cat_visit',
        text: 'Visit the cat weekly at the shelter instead',
        effects: { happiness: 5, karma: 2 },
        outcomeText: 'You are the favourite visitor. The cat says so, with its eyes.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_reading_circle',
    text: 'The library starts an evening circle and someone puts your name forward, kindly.',
    minAge: 70,
    maxAge: 95,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['hobby', 'social'],
    choices: [
      {
        id: 'se_reading_join',
        text: 'Join and bring your strong opinions',
        effects: { happiness: 8, smarts: 4 },
        outcomeText: 'You defend a minor character fiercely. Everyone warms to you.',
        tone: 'good',
      },
      {
        id: 'se_reading_lead',
        text: 'Offer to lead the next month\'s pick',
        effects: { happiness: 7, smarts: 5, karma: 2 },
        outcomeText: 'Your chosen book divides the room. Perfect discussion material.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_sage_advice',
    text: 'A young colleague, now middle-aged, phones for a no-frills opinion on a big choice.',
    minAge: 68,
    maxAge: 95,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['community', 'mentor'],
    choices: [
      {
        id: 'se_sage_speak',
        text: 'Give the honest, kind, complicated answer',
        effects: { happiness: 7, karma: 4 },
        outcomeText: 'They write it down. A year later they quote it back to you, exactly.',
        tone: 'good',
      },
      {
        id: 'se_sage_listen',
        text: 'Mostly listen, which is what they needed',
        effects: { happiness: 6, karma: 3 },
        outcomeText: 'A long silence, then: "Thank you. That helped."',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_comfort_visit',
    text: 'Your old neighbour is back in hospital, and the family asks if you might drop by.',
    minAge: 70,
    maxAge: 95,
    weight: 45,
    tone: 'neutral',
    category: 'senior',
    tags: ['health', 'community'],
    choices: [
      {
        id: 'se_visit_presence',
        text: 'Go, sit, and tell old stories',
        effects: { happiness: 7, karma: 5 },
        outcomeText: 'The stories work better than any gift. The nurse smiles at both of you.',
        tone: 'good',
      },
      {
        id: 'se_visit_card',
        text: 'Send a card with a pressed flower',
        effects: { happiness: 3, karma: 2 },
        outcomeText: 'The flower finds its way to the bedside table.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_widowhood_kind',
    text: 'Losing your spouse leaves an ordinary Tuesday suddenly enormous. The house is too quiet.',
    minAge: 65,
    maxAge: 100,
    weight: 40,
    tone: 'bad',
    category: 'senior',
    tags: ['family', 'grief'],
    requiredFlags: ['has_spouse'],
    choices: [
      {
        id: 'se_widow_grief',
        text: 'Let the grief move through you slowly, with help',
        effects: { happiness: -6, health: -3, smarts: 3 },
        outcomeText: 'Support groups and slow walks help. The grief stays, but gentler.',
        tone: 'bad',
      },
      {
        id: 'se_widow_memory',
        text: 'Plant a tree and keep their chair',
        effects: { happiness: 4, karma: 3, addFlag: 'widowed', removeFlag: 'has_spouse' },
        outcomeText: 'The tree grows. The chair stays. The two of them argue no more.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_memory_project',
    text: 'The family starts a project to gather voices and faces before stories blur.',
    minAge: 72,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['family', 'legacy'],
    choices: [
      {
        id: 'se_memory_join',
        text: 'Sit for the interviews and the photo album',
        effects: { happiness: 9, karma: 4 },
        outcomeText: 'The album has your laugh on every page. Future generations will know it.',
        tone: 'good',
      },
      {
        id: 'se_memory_count',
        text: 'Help sort the shoeboxes of photographs',
        effects: { happiness: 7, smarts: 3 },
        outcomeText: 'You label the faces the younger ones had no hope of placing.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_bridge_club',
    text: 'The community hall runs a bridge evening where the stakes are biscuits and the trash talk is legendary.',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['social', 'hobby'],
    choices: [
      {
        id: 'bridge_learn',
        text: 'Learn the game properly',
        effects: { smarts: 5, happiness: 5 },
        outcomeText: 'A year later, you are the feared biscuit champion of table three.',
        tone: 'good',
      },
      {
        id: 'bridge_watch',
        text: 'Watch and referee the great arguments',
        effects: { happiness: 3, karma: 3 },
        outcomeText: 'Your ruling on the biscuits is final and universally respected.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_technology_class',
    text: 'The library offers a "great-grandchildren-proof" technology class and everyone wants your seat.',
    minAge: 70,
    maxAge: 100,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['education', 'social'],
    choices: [
      {
        id: 'techclass_stay',
        text: 'Take the class to the end, slow as syrup',
        effects: { smarts: 7, happiness: 4 },
        outcomeText: 'You can now video-call, mute, and unmute, in any weather.',
        tone: 'good',
      },
      {
        id: 'techclass_note',
        text: 'Take precise handwritten notes for the others',
        effects: { happiness: 4, karma: 4 },
        outcomeText: 'Your notes in the margin are now class lore.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_genealogy_trip',
    text: 'A family tree website shows a branch that leads somewhere interesting, and tickets are cheap.',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['legacy', 'family', 'travel'],
    choices: [
      {
        id: 'genealogy_visit',
        text: 'Visit the town and find the old records',
        effects: { happiness: 7, smarts: 3, money: -5 },
        outcomeText: 'The records confirm the family rumour and the town is lovely.',
        tone: 'good',
      },
      {
        id: 'genealogy_chart',
        text: 'Build the full chart at the kitchen table',
        effects: { smarts: 5, happiness: 3 },
        outcomeText: 'Forty names now have faces and stories. The chart gets framed.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_letters_to_future',
    text: 'Your hundred-year-old self has been requested for letters, addressed with tenderness and humour.',
    minAge: 70,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['legacy'],
    choices: [
      {
        id: 'letters_write',
        text: 'Write a letter for each grandchild\'s next birthday',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'The letters wait in a shoebox, sealed, and hugely loved.',
        tone: 'good',
      },
      {
        id: 'letters_tape',
        text: 'Record a short message instead',
        effects: { happiness: 6, karma: 2 },
        outcomeText: 'Your voice, saved. Decades from now it will still make them smile.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_reminiscence_table',
    text: 'The care home next door starts a memory circle and invites regulars to bring one object each.',
    minAge: 68,
    maxAge: 100,
    weight: 50,
    tone: 'good',
    category: 'senior',
    tags: ['community'],
    choices: [
      {
        id: 'reminiscence_share',
        text: 'Bring one object and tell its story',
        effects: { happiness: 7, karma: 4 },
        outcomeText: 'The room goes quiet, then warm. You are invited back every month.',
        tone: 'good',
      },
      {
        id: 'reminiscence_listen',
        text: 'Come and listen to the others',
        effects: { happiness: 5, smarts: 3 },
        outcomeText: 'Some afternoons, listening is the whole gift.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'se_morning_walk',
    text: 'A gentle morning walk now has the discipline of a habit and the prize of a very good bench.',
    minAge: 66,
    maxAge: 100,
    weight: 55,
    tone: 'good',
    category: 'senior',
    tags: ['health'],
    choices: [
      {
        id: 'morningwalk_soon',
        text: 'Make the walk the day\'s first appointment',
        effects: { health: 7, happiness: 5 },
        outcomeText: 'The bench, the birds, the routine. The day starts right.',
        tone: 'good',
      },
      {
        id: 'morningwalk_garden',
        text: 'Trade the walk for ten minutes in the garden',
        effects: { health: 4, happiness: 4 },
        outcomeText: 'The garden also counts, and says so proudly.',
        tone: 'neutral',
      },
    ],
  },
];