import type { LifeEventDef } from '@/lib/engine/types';

export const TEEN_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'teen_acne',
    text: 'One morning you look in the mirror and meet a very unwelcome red visitor.',
    minAge: 13,
    maxAge: 17,
    weight: 90,
    tone: 'bad',
    category: 'teen',
    tags: ['looks'],
    choices: [
      {
        id: 'acne_disguise',
        text: 'Wear a hat and stare at your shoes all day',
        effects: { looks: 2 },
        outcomeText: 'The hat does not fool anyone, but it made you feel in control.',
        tone: 'neutral',
      },
      {
        id: 'acne_toothpaste',
        text: 'Try the internet remedy involving toothpaste',
        effects: { health: -1, happiness: 3 },
        outcomeText: 'It does nothing except make your face smell of mint. Science pending.',
        tone: 'funny',
      },
      {
        id: 'acne_ownit',
        text: 'Shrug and carry on like it is not there',
        effects: { happiness: 6, smarts: 2 },
        outcomeText: 'Turns out nobody was counting your spots except you.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_crush',
    text: 'The art-club captain smiled at you between classes. You have not recovered.',
    minAge: 13,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'crush_smile',
        text: 'Smile back, then pretend to check your shoe',
        effects: { happiness: 12, looks: 2 },
        outcomeText: 'A six-second moment that you will relive for a week.',
        tone: 'good',
      },
      {
        id: 'crush_wave',
        text: 'Wave with your whole arm and own it',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'Openly friendly, honestly friendly. The wave does its work.',
        tone: 'neutral',
      },
      {
        id: 'crush_lookaway',
        text: 'Stare fixedly at the fire alarm',
        effects: { smarts: -1, happiness: -3 },
        outcomeText: 'The fire alarm was very interesting, actually. You know nothing else.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_party',
    text: 'A school dance is happening on Friday. The entire cafeteria is debating attendance.',
    minAge: 14,
    maxAge: 18,
    weight: 70,
    tone: 'neutral',
    category: 'teen',
    choices: [
      {
        id: 'party_go',
        text: 'Go and meet everyone near the snacks',
        effects: { happiness: 12, looks: 3, health: -3 },
        outcomeText: 'The music is too loud and the snacks run out, but you were there.',
        tone: 'good',
      },
      {
        id: 'party_study',
        text: 'Skip it and get ahead on homework',
        effects: { smarts: 8, happiness: -4 },
        outcomeText: 'The chapter gets read. FOMO flashes once, then fades.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_test',
    text: 'A history exam looms. Half the class is panicking, the other half is lying.',
    minAge: 13,
    maxAge: 17,
    weight: 85,
    tone: 'neutral',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'test_study',
        text: 'Make a study sheet and grind through it',
        effects: { smarts: 6, happiness: -2 },
        outcomeText: 'Boring, but on exam day the answers sit right where you put them.',
        tone: 'good',
      },
      {
        id: 'test_group',
        text: 'Study in a loud group with snacks',
        effects: { smarts: 5, happiness: 3 },
        outcomeText: 'Forty percent real studying, sixty percent biscuit diplomacy. It works.',
        tone: 'neutral',
      },
      {
        id: 'test_wing',
        text: 'Wing it on vibes alone',
        effects: { smarts: -3, happiness: 4 },
        outcomeText: 'You write with confidence about an empire that may not exist. Grade pending.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_part_time',
    text: 'The community center is hiring someone to organize the sports equipment room.',
    minAge: 15,
    maxAge: 18,
    weight: 55,
    tone: 'neutral',
    category: 'teen',
    tags: ['work'],
    choices: [
      {
        id: 'parttime_accept',
        text: 'Take the job and earn real money',
        effects: { money: 50, smarts: 3, addFlag: 'parttime_accept' },
        outcomeText: 'You are paid actual coins for arranging balls in order. The economy has noticed you.',
        tone: 'good',
      },
      {
        id: 'parttime_decline',
        text: 'Decline and guard your weekends',
        effects: { happiness: 5 },
        outcomeText: 'The weekends are yours. The ball room waits for another hero.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_sports_tryout',
    text: 'The school team is holding tryouts and you half-signed up before you could stop yourself.',
    minAge: 13,
    maxAge: 18,
    weight: 60,
    tone: 'good',
    category: 'teen',
    tags: ['health', 'sport'],
    choices: [
      {
        id: 'tryout_train',
        text: 'Train hard all week and go all in',
        effects: { health: 8, happiness: 5 },
        outcomeText: 'Every bruise is proof. You make the roster by exactly one spot.',
        tone: 'good',
      },
      {
        id: 'tryout_show',
        text: 'Show up, give one honest try, accept the result',
        effects: { health: 2, smarts: 3 },
        outcomeText: 'You do not make it, but you learn you survive a public miss.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_curfew',
    text: 'You are home fourteen minutes late and the porch light is on like a searchlight.',
    minAge: 14,
    maxAge: 17,
    weight: 50,
    tone: 'bad',
    category: 'teen',
    choices: [
      {
        id: 'curfew_sneak',
        text: 'Slip in through the back window',
        effects: { smarts: 3, karma: -8 },
        outcomeText: 'You land cleanly, only to find the kitchen light on and a "we need to talk" brewing.',
        tone: 'funny',
      },
      {
        id: 'curfew_honest',
        text: 'Walk in, apologize, take the lecture',
        effects: { karma: 8, happiness: -4 },
        outcomeText: 'The lecture is long, but the trust account stays full.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_science_fair',
    text: 'The science fair is looking for volunteers. Everyone has a power of two thoughts about it.',
    minAge: 12,
    maxAge: 17,
    weight: 40,
    tone: 'good',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'science_fair_volcano',
        text: 'Build a baking-soda volcano and own the floor',
        effects: { smarts: 6, happiness: 8 },
        outcomeText: 'The volcano erupts a little too well and the janitor is called. Glorious.',
        tone: 'funny',
      },
      {
        id: 'science_fair_help',
        text: 'Help two nervous teams set up their boards',
        effects: { karma: 8, smarts: 2 },
        outcomeText: 'Three projects show up polished, and yours is the glue that held them.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_first_wage',
    text: 'Your first paycheck lands in your hand. It is smaller than you dreamed and taller than it looks.',
    minAge: 15,
    maxAge: 18,
    weight: 45,
    tone: 'good',
    category: 'teen',
    moment: 'money',
    tags: ['work', 'money'],
    requiredFlags: ['parttime_accept'],
    choices: [
      {
        id: 'wage_save',
        text: 'Stash it in a savings tin with great ceremony',
        effects: { smarts: 3, money: 10 },
        outcomeText: 'The tin feels heavier in the best way. First coin, first fort.',
        tone: 'good',
      },
      {
        id: 'wage_spend',
        text: 'Spend it all on snacks for the friend group',
        effects: { happiness: 10, karma: 6 },
        outcomeText: 'One glorious afternoon, then pockets full of crumbs and fond memory.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_mock_exam_shock',
    text: 'The mock exam results board goes up with the cheerful announcement that yellow means "revise more".',
    minAge: 13,
    maxAge: 17,
    weight: 60,
    tone: 'bad',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'mock_panic_revise',
        text: 'Build a revision timetable and actually follow it',
        effects: { smarts: 6, happiness: -1 },
        outcomeText: 'The real exams arrive and the yellow shrinks to a polite amber.',
        tone: 'good',
      },
      {
        id: 'mock_panic_bash',
        text: 'Cram wildly the night before each paper',
        effects: { smarts: -4, health: -2, happiness: -2 },
        outcomeText: 'The yellow stays. So does the cramming. Some cycles are hard to break.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'teen_talent_show',
    text: 'The school talent show has a slot open and the crowd\'s expectations are already enormous.',
    minAge: 13,
    maxAge: 17,
    weight: 45,
    tone: 'good',
    category: 'teen',
    tags: ['fame', 'hobby'],
    choices: [
      {
        id: 'talent_perform',
        text: 'Perform, badly but bravely',
        effects: { fame: 4, happiness: 8, looks: 2 },
        outcomeText: 'The applause is real, the blush is realer, and everyone knows your name now.',
        tone: 'good',
      },
      {
        id: 'talent_backstage',
        text: 'Run sound and lights instead',
        effects: { smarts: 3, karma: 3 },
        outcomeText: 'The show runs perfectly from your boards. Nobody notices. That is the job.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_group_photo',
    text: 'The year photo is being taken and the photographer has an elaborate idea involving stepping.',
    minAge: 13,
    maxAge: 18,
    weight: 45,
    tone: 'funny',
    category: 'teen',
    tags: ['school'],
    choices: [
      {
        id: 'groupphoto_fun',
        text: 'Do the peace sign, fully committing',
        effects: { happiness: 6, looks: 1 },
        outcomeText: 'Your peace sign is now in the yearbook forever, above a quiet smirk.',
        tone: 'funny',
      },
      {
        id: 'groupphoto_serious',
        text: 'Stand solemnly, like a small diplomat',
        effects: { happiness: 3, fame: 1 },
        outcomeText: 'The diplomat expression will be gleefully memed by your friends.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_dorm_bet',
    text: 'Your friend bets you a week of chores that you cannot learn to whistle with two fingers by Friday.',
    minAge: 14,
    maxAge: 18,
    weight: 40,
    tone: 'funny',
    category: 'teen',
    tags: ['friendship', 'daily-life'],
    choices: [
      {
        id: 'dormbet_practice',
        text: 'Grind it out in the bathroom mirror',
        effects: { smarts: 3, happiness: 4 },
        outcomeText: 'Thursday night: a thin whistle. Friday: a victory blast that echoes down the hall.',
        tone: 'good',
      },
      {
        id: 'dormbet_chores',
        text: 'Accept the chores and level up as a laundromat philosopher',
        effects: { karma: 3, happiness: 1 },
        outcomeText: 'A week of folding. The friend\'s fingers are now, allegedly, insured.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_fast_track',
    text: 'A fast-track study group opens for the keen, the curious, and the terminally early-risers.',
    minAge: 13,
    maxAge: 16,
    weight: 50,
    tone: 'neutral',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'fasttrack_join',
        text: 'Join and ride the friendly pressure',
        effects: { smarts: 8, happiness: -1 },
        outcomeText: 'Your grades climb and your jokes get, statistically, denser.',
        tone: 'good',
      },
      {
        id: 'fasttrack_skip',
        text: 'Skip it and keep your afternoons',
        effects: { happiness: 4 },
        outcomeText: 'The group emails you. You cheer them on from the sunshine.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_sleepover',
    text: 'A sleepover at your place, where the official schedule shows "snacks", and the unofficially shows chaos.',
    minAge: 12,
    maxAge: 16,
    weight: 50,
    tone: 'good',
    category: 'teen',
    tags: ['friendship'],
    choices: [
      {
        id: 'sleepover_epic',
        text: 'Plan the full epic night of games and films',
        effects: { happiness: 8, karma: 3 },
        outcomeText: 'The morning after is a battlefield of sleeping bags and loyalty.',
        tone: 'good',
      },
      {
        id: 'sleepover_quiet',
        text: 'Keep it to two friends and one documentary',
        effects: { happiness: 4, smarts: 2 },
        outcomeText: 'Calm, warm, and with unbroken snack protocol.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_phone_dare',
    text: 'A group chat declares that someone must call their crush. Everyone except you has a plan.',
    minAge: 14,
    maxAge: 17,
    weight: 45,
    tone: 'funny',
    category: 'teen',
    tags: ['friendship', 'romance'],
    choices: [
      {
        id: 'phonedare_call',
        text: 'Do the call, voice crack and all',
        effects: { happiness: 7, looks: 2 },
        outcomeText: 'It is awkward, brief, and somehow wins the day. Legend status achieved.',
        tone: 'funny',
      },
      {
        id: 'phonedare_text',
        text: 'Send a funny message instead and blame signal',
        effects: { smarts: 3, karma: 1 },
        outcomeText: 'The excuse is transparent and everyone pretends to believe it.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_penpal',
    text: 'Your English teacher suggests a pen-pal exchange with a school in another country.',
    minAge: 13,
    maxAge: 16,
    weight: 45,
    tone: 'neutral',
    category: 'teen',
    tags: ['education', 'friendship'],
    choices: [
      {
        id: 'penpal_write',
        text: 'Write a proper first letter',
        effects: { smarts: 4, happiness: 4 },
        outcomeText: 'The reply arrives in six weeks and tastes of somewhere else entirely.',
        tone: 'good',
      },
      {
        id: 'penpal_card',
        text: 'Send a postcard with a very tidy doodle',
        effects: { happiness: 2, karma: 2 },
        outcomeText: 'The doodle is discussed warmly on the other side of the world.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_show_and_tell',
    text: 'Show-and-tell is on and the spotlight is terrifyingly square.',
    minAge: 11,
    maxAge: 14,
    weight: 45,
    tone: 'neutral',
    category: 'teen',
    tags: ['school', 'fame'],
    choices: [
      {
        id: 'showtell_object',
        text: 'Bring a genuinely weird object and own the story',
        effects: { fame: 3, happiness: 6, smarts: 1 },
        outcomeText: 'The class votes it the most memorable. You are briefly royalty.',
        tone: 'good',
      },
      {
        id: 'showtell_coin',
        text: 'Bring a coin and wing the story',
        effects: { happiness: -1, smarts: 1 },
        outcomeText: 'The coin story folds after forty seconds. The applause is kind.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_cycling_team',
    text: 'The neighbourhood cycling club is looking for junior riders for the summer series.',
    minAge: 14,
    maxAge: 17,
    weight: 45,
    tone: 'neutral',
    category: 'teen',
    tags: ['sports', 'health'],
    choices: [
      {
        id: 'cycling_join',
        text: 'Join and earn your very real jersey',
        effects: { health: 7, happiness: 4 },
        outcomeText: 'By August your calves are philosophical works of art.',
        tone: 'good',
      },
      {
        id: 'cycling_pump',
        text: 'Become the trackside pump-and-tire whisperer',
        effects: { smarts: 2, karma: 3 },
        outcomeText: 'Every rider owes a fraction of their podium to your valve skills.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_school_play',
    text: 'The school play has a juicy minor role and auditions are unusually unmocked.',
    minAge: 13,
    maxAge: 17,
    weight: 45,
    tone: 'neutral',
    category: 'teen',
    tags: ['fame', 'hobby'],
    choices: [
      {
        id: 'play_audition',
        text: 'Audition and go for it',
        effects: { fame: 4, happiness: 7 },
        outcomeText: 'You get the part, memorise everything, and forget everything on opening night. Almost.',
        tone: 'good',
      },
      {
        id: 'play_lightboard',
        text: 'Run the lightboard instead',
        effects: { smarts: 3, karma: 2 },
        outcomeText: 'You control the spotlight, which is its own kind of power.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_homework_storm',
    text: 'Four subjects have decided today is the day to strike simultaneously.',
    minAge: 13,
    maxAge: 17,
    weight: 50,
    tone: 'bad',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'homework_march',
        text: 'Systematically march through the pile',
        effects: { smarts: 5, happiness: -2, health: -2 },
        outcomeText: 'By midnight it is done. The desk looks relieved.',
        tone: 'good',
      },
      {
        id: 'homework_selection',
        text: 'Do the best two and brave the other two',
        effects: { smarts: 1, happiness: 2 },
        outcomeText: 'The strategy is bold. The teachers notice, in their own gentle ways.',
        tone: 'bad',
      },
    ],
  },
];