import type { LifeEventDef } from '@/lib/engine/types';

export const TEEN_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'teen_acne',
    text: 'সকালে আয়নার সামনে গিয়া দেখস তোর নাকের ডগায় বিশাল একখান পিনিক দেওয়া ব্রন! পুরাই লাল বাত্তি!',
    minAge: 13,
    maxAge: 17,
    weight: 90,
    tone: 'bad',
    category: 'teen',
    tags: ['looks'],
    choices: [
      {
        id: 'acne_disguise',
        text: 'আব্বুর পুরান ক্যাপ পইড়া মুখ লুকাইয়া স্কুলে যা!',
        effects: { looks: 2, happiness: -10 },
        outcomeText: 'ক্যাপ পইড়া ভাব নিতে গিয়া তুই ড্রেনে পইড়া গেলি! এহন তোর পুরা মুখেই ড্রেনের কাদা, ব্রন আর কেউ দেখবো না হালায়!',
        tone: 'funny',
      },
      {
        id: 'acne_toothpaste',
        text: 'ইউটিউব দেইখা ব্রনের উপ্রে টুথপেস্ট আর চুন ঘইষা দে!',
        effects: { health: -15, happiness: -20, looks: -25 },
        outcomeText: 'চুন আর পেস্টের রিঅ্যাকশনে তোর ব্রন ফাইট্টা পুঁজ বাইর হইয়া পুরা মুখ ভাইসা গেলো! তুই এহন জ্যান্ত পুঁজ-মামা!',
        tone: 'bad',
      },
      {
        id: 'acne_ownit',
        text: 'ব্রনের গুষ্টি কিলাইয়া বুক ফুলাইয়া মাইয়াগো সামনে যা!',
        effects: { happiness: 10, smarts: 5, fame: -10 },
        outcomeText: 'মাইয়ারা তোর ব্রন দেইখা বমি কইরা দিলো! তয় তুই হালায় কনফিডেন্সের বাপ, তোর কোন বাল ছেঁড়া গেলো না!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_crush',
    text: 'ক্লাসের সবচেয়ে কড়া মাইয়াটা তোর দিকে তাকাইয়া এমুন একখান হাসি দিছে, তোর প্যান্টের চেইন নিজে নিজেই খুইলা যাওয়ার দশা!',
    minAge: 13,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'crush_smile',
        text: 'দাঁত বাইর কইরা বান্দরের লাহান একখান হাসি ফিরায়া দে!',
        effects: { happiness: -15, looks: -20 },
        outcomeText: 'তোর দাঁতের ফাঁকে লাইগা থাকা পালং শাক দেইখা মাইয়া থুতু দিয়া চইলা গেলো! তুই পুরাই ফইন্নি রোমিও!',
        tone: 'bad',
      },
      {
        id: 'crush_wave',
        text: 'শাহরুখ খান সাইজা হাত নাড়াইয়া ফ্লাইং কিস দে!',
        effects: { happiness: -25, fame: 20, health: -15 },
        outcomeText: 'ফ্লাইং কিস দিতে গিয়া তুই পিছলা খায়া স্যারের গায়ের উপ্রে পড়লি! স্যার তোরে ডাইরেক্ট টিসি (TC) দিয়া বাইর কইরা দিলো!',
        tone: 'bad',
      },
      {
        id: 'crush_lookaway',
        text: 'ডরে মুইতা দিয়া অন্যদিকে ঘুইরা নাকের সর্দি টান দে!',
        effects: { smarts: -5, happiness: -10, looks: -10 },
        outcomeText: 'সর্দি টানতে গিয়া তোর নাক দিয়া একতাল কাঁচা সর্দি বাইর হইয়া ঠোঁটে পড়লো! মাইয়া দেইখা বেহুঁশ, তুই হালায় আজীবন সিঙ্গেল!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_party',
    text: 'স্কুলে ফাটাফাটি পার্টি! পুরা ক্লাসের পোলাপাইন যাইতেছে, আর তুই চিপায় বইসা নখ কামড়াইতাছোস!',
    minAge: 14,
    maxAge: 18,
    weight: 70,
    tone: 'neutral',
    category: 'teen',
    choices: [
      {
        id: 'party_go',
        text: 'বাপের পকেট মাইরা নতুন শার্ট কিন্না পার্টিতে যা!',
        effects: { happiness: -20, looks: -10, health: -15 },
        outcomeText: 'পার্টিতে গিয়া সস্তা বিরিয়ানি খায়া তোর এমুন ডাইরিয়া হইলো, তুই ড্যান্স ফ্লোরেই হাগু কইরা দিলি! পুরা পার্টি ভন্ডুল!',
        tone: 'bad',
      },
      {
        id: 'party_study',
        text: 'পার্টির গুষ্টি কিলাইয়া ঘরে বইসা আতেল সাইজা অঙ্ক কর!',
        effects: { smarts: 15, happiness: -25, fame: -20 },
        outcomeText: 'অঙ্ক করলি ঠিকই, কিন্তু পরের দিন পোলাপাইন তোরে "আতেল-হিজড়া" বইলা পুরা স্কুল ঘুরাইলো! তোর ইজ্জত জিরো!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_test',
    text: 'কাইলকা ইতিহাসের বিশাল এক্সাম! পোলাপাইন ডরে কান্দতাছে, আর তুই হালায় মুভি দেখতাছোস!',
    minAge: 13,
    maxAge: 17,
    weight: 85,
    tone: 'neutral',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'test_study',
        text: 'রাইত জাইগা বইয়ের পাতা ছিঁড়া মুখস্থ কর!',
        effects: { smarts: 10, happiness: -15, health: -10 },
        outcomeText: 'মুখস্থ করছোস ঠিকই, কিন্তু পরীক্ষার হলে গিয়া ঘুমের চোটে তুই খাতার উপ্রেই লালা ফালাইয়া ঘুমাইয়া গেলি! আন্ডা পাইছোস হালায়!',
        tone: 'bad',
      },
      {
        id: 'test_group',
        text: 'দোস্তগো বাসায় গিয়া গ্রুপ স্টাডির ফাপড় নে!',
        effects: { smarts: -10, happiness: 20, fame: 10 },
        outcomeText: 'পড়াশোনা বাদ দিয়া তোরা সারারাত লুডু খেলছোস আর বিড়ি টানছোস! সকালে সবাই মিল্লা ডাব্বা মারছোস, তয় চিল তো হইছে!',
        tone: 'funny',
      },
      {
        id: 'test_wing',
        text: 'বই না খুইলা ডাইরেক্ট পরীক্ষার হলে গিয়া চাপাবাজি কর!',
        effects: { smarts: -25, happiness: -10, karma: -15 },
        outcomeText: 'নবাব সিরাজউদ্দৌলার জায়গায় তুই জেমসের গানের লিরিক্স লেইখা দিছোস! স্যার তোর বাপরে ডাইকা আইন্না তোরে ন্যাংটা কইরা পিটাইছে!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'teen_part_time',
    text: 'এলাকার ক্লাবে বল কুড়ানোর চাকরির অফার আইছে! মাসে ৫০০ ট্যাকা বেতন!',
    minAge: 15,
    maxAge: 18,
    weight: 55,
    tone: 'neutral',
    category: 'teen',
    tags: ['work'],
    choices: [
      {
        id: 'parttime_accept',
        text: 'লজ্জা ছাইড়া ৫০০ ট্যাকার লাইগা চাকরিতে ঢুইকা যা!',
        effects: { money: 50, smarts: 5, addFlag: 'parttime_accept', fame: -15 },
        outcomeText: 'বল কুড়াইতে গিয়া তুই ড্রেনের পচা পানিতে এমুন আছাড় খাইলি, তোর গায় গু-মুত মাখামাখি! তুই এহন ক্লাবের "গু-বয়"!',
        tone: 'bad',
      },
      {
        id: 'parttime_decline',
        text: 'ফাপড় নিয়া ক: "বাপের ট্যাকা থাকতে ফইন্নির চাকরি করুম না!"',
        effects: { happiness: 10, money: -20 },
        outcomeText: 'বাপ শুইনা তোরে ঘাড়ধাক্কা দিয়া বাইর কইরা দিছে! তুই এহন রাস্তায় বইসা বাদাম বেচ হালায়!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_sports_tryout',
    text: 'স্কুলের ক্রিকেট টিমে ট্রায়াল চলতাছে! তুই হালায় ব্যাট ধরতে পারস না, তাও নাম দিয়া দিছোস!',
    minAge: 13,
    maxAge: 18,
    weight: 60,
    tone: 'good',
    category: 'teen',
    tags: ['health', 'sport'],
    choices: [
      {
        id: 'tryout_train',
        text: 'সাকিব আল হাসান সাইজা উরাধুরা প্র্যাকটিস শুরু কর!',
        effects: { health: -15, happiness: -20, fame: -10 },
        outcomeText: 'প্র্যাকটিস করতে গিয়া তুই নিজের আন্ডারওয়ার ছিঁড়া ফালাইছোস! পুরা মাঠের সামনে তোর পাছা ওপেন, তুই ডাইরেক্ট ভাইরাল!',
        tone: 'bad',
      },
      {
        id: 'tryout_show',
        text: 'খালি হাতে মাঠে গিয়া ফাপড়বাজি কর!',
        effects: { health: -20, smarts: -10 },
        outcomeText: 'প্রথম বলেই বল ডাইরেক্ট গিয়া তোর অন্ডকোষে হিট! তুই ব্যথায় কোঁকাইয়া অজ্ঞান, এহন হাসপাতালে ভর্তি হ হালায়!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'teen_curfew',
    text: 'রাইত ১০টায় বাসায় ফিরছোস! বাপে দরজায় লাঠি নিয়া খাড়ায়া আছে, তোর জান শেষ!',
    minAge: 14,
    maxAge: 17,
    weight: 50,
    tone: 'bad',
    category: 'teen',
    choices: [
      {
        id: 'curfew_sneak',
        text: 'চোরের লাহান পিছনের জানলা দিয়া রুমে ঢোকার ট্রাই কর!',
        effects: { smarts: -15, karma: -20, health: -15 },
        outcomeText: 'জানলা দিয়া ঢুকতে গিয়া তুই বাথরুমের কমোডের উপ্রে পড়লি! পুরাই গু-মাখা ভূত হইয়া গেলি, বাপে দেইখা ডরে অজ্ঞান!',
        tone: 'funny',
      },
      {
        id: 'curfew_honest',
        text: 'বুকের পাটা ফুলাইয়া বাপের সামনে গিয়া খাড়া!',
        effects: { karma: 10, happiness: -30, health: -25 },
        outcomeText: 'বাপে কোনো কথা না বইলা তোর পাছায় এমুন একখান লাথি দিলো, তুই উইড়া গিয়া ড্রেনে পড়লি! রাইত পুরাটা ড্রেনেই কাটলো!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'teen_science_fair',
    text: 'বিজ্ঞান মেলায় প্রজেক্ট জমা দিতে হইবো! তুই হালায় আলু দিয়া কারেন্ট বানানোর ফাপড় নিছোস!',
    minAge: 12,
    maxAge: 17,
    weight: 40,
    tone: 'good',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'science_fair_volcano',
        text: 'বেকিং সোডা আর ভিনেগার দিয়া ভলকানো বানায়া ফুটানি মার!',
        effects: { smarts: -10, happiness: -20, looks: -15 },
        outcomeText: 'ভলকানো ব্লাস্ট হইয়া ডাইরেক্ট প্রিন্সিপালের মুখে পইড়া তার চশমা ভাইঙ্গা গেলো! তোরে ধইরা স্কুল থিকা লাথি দিয়া বাইর করছে!',
        tone: 'bad',
      },
      {
        id: 'science_fair_help',
        text: 'নিজের প্রজেক্ট বাদ দিয়া মাইয়াগো প্রজেক্টে হেল্প করতে যা!',
        effects: { karma: -15, smarts: -20, fame: -25 },
        outcomeText: 'মাইয়ারা তোরে দিয়া তাগো ব্যাগ আর ছাতা বওয়াইলো! কাম শেষ হইলে তোরে চিনতেই পারলো না! তুই পুরাই ফইন্নি চাকর!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_first_wage',
    text: 'পয়লা ইনকামের ৫০০ ট্যাকা পকেটে! তোর এহন মনে হইতাছে তুই বিল গেটসের হালাতো ভাই!',
    minAge: 15,
    maxAge: 18,
    weight: 45,
    tone: 'good',
    category: 'teen',
    moment: 'money',
    tags: ['work', 'money'],
    requiredFlags: ['parttime_accept'],
    choices: [
      {
        id: 'wage_save',
        text: 'কিপ্টার লাহান ট্যাকা মাটির ব্যাংকে লুকাইয়া রাখ!',
        effects: { smarts: 15, money: 50, happiness: -10 },
        outcomeText: 'মাটির ব্যাংক ভাইঙ্গা দেখস তোর ছোট ভাই সব ট্যাকা চুরি কইরা ফ্রি-ফায়ারে ডাইমন্ড কিন্না ফেলছে! তুই এহন কাইন্দা নদী বানায়া ফ্যাল!',
        tone: 'funny',
      },
      {
        id: 'wage_spend',
        text: 'সব ট্যাকা উড়াইয়া দোস্তগো কাচ্চি খাওয়া!',
        effects: { happiness: 20, karma: 10, money: -50 },
        outcomeText: 'খাওয়া শেষ কইরা দেখস বিল আইছে ১৫০০ ট্যাকা! বাকি ট্যাকা না দিতে পাইরা তোরা সবাই হোটেলের বাথরুম ধুইছোস রাইত ১২টা পর্যন্ত!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'teen_mock_exam_shock',
    text: 'টেস্ট পরীক্ষার রেজাল্ট দিছে! তুই হালায় ৪ সাবজেক্টে ডাব্বা মাইরা লাল বাত্তি জ্বালাইয়া দিছোস!',
    minAge: 13,
    maxAge: 17,
    weight: 60,
    tone: 'bad',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'mock_panic_revise',
        text: 'ডরে মুইতা দিয়া রাইত-দিন এক কইরা পড়া শুরু কর!',
        effects: { smarts: 20, happiness: -30, looks: -15 },
        outcomeText: 'পড়তে পড়তে তোর চোখ গর্তে ঢুইকা তুই জম্বি হইয়া গেলি! পাস করছোস ঠিকই, কিন্তু তোরে দেইখা মহল্লার কুত্তাও ভয় পায়!',
        tone: 'funny',
      },
      {
        id: 'mock_panic_bash',
        text: 'পড়াশোনার গুষ্টি কিলাইয়া পরীক্ষার আগের রাইতে ফাপড় নে!',
        effects: { smarts: -30, health: -20, happiness: -25 },
        outcomeText: 'ফাইনাল পরীক্ষায় তুই এমুন ডাব্বা মারছোস যে স্যার তোর খাতায় শুয়োরের ছবি আইকা দিছে! বাপে তোরে গ্যারেজে কামে দিয়া দিছে!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'teen_talent_show',
    text: 'স্কুলে ট্যালেন্ট শো! সবাই নাচ-গান করতাছে, আর তুই হালায় স্টেজে উইঠা কী বাল ফালাবি ভাবতাছোস!',
    minAge: 13,
    maxAge: 17,
    weight: 45,
    tone: 'good',
    category: 'teen',
    tags: ['fame', 'hobby'],
    choices: [
      {
        id: 'talent_perform',
        text: 'মাইক ধইরা বেসুরা গলায় জেমসের গান চিল্লায়া গা!',
        effects: { fame: -25, happiness: -30, looks: -20 },
        outcomeText: 'তোর গলার আওয়াজ শুইনা পিছনের পাবলিক তোর দিকে পচা ডিম আর জুতা ফিক্কা মারছে! তুই ডাইরেক্ট ডাস্টবিন হইয়া স্টেজ থিকা নামলি!',
        tone: 'bad',
      },
      {
        id: 'talent_backstage',
        text: 'ডরে স্টেজে না উইঠা পিছনে গিয়া লাইটম্যানের কাম কর!',
        effects: { smarts: 5, karma: -10, fame: -15 },
        outcomeText: 'লাইট ঠিক করতে গিয়া তুই এমুন কারেন্টের শট খাইলি, তোর প্যান্টের চেইন খুইলা গেলো! ন্যাংটা হইয়া তুই অজ্ঞান, পুরাই লেজেন্ড!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_group_photo',
    text: 'ক্লাসের গ্রুপ ছবি তোলা হইতাছে! তুই পিছনের লাইনে খাড়াইয়া ফাপড় নিতাছোস!',
    minAge: 13,
    maxAge: 18,
    weight: 45,
    tone: 'funny',
    category: 'teen',
    tags: ['school'],
    choices: [
      {
        id: 'groupphoto_fun',
        text: 'দাঁত বাইর কইরা ভি-সাইন (V-Sign) দিয়া বান্দর সাজ!',
        effects: { happiness: -15, looks: -25, fame: 20 },
        outcomeText: 'ছবি বাইর হওয়ার পর দেখস তোর নাকের বিশাল একখান সর্দি ছবির মইধ্যে হাইলাইট হইতাছে! পুরা স্কুল তোরে "সর্দি-মামা" ডাকে!',
        tone: 'bad',
      },
      {
        id: 'groupphoto_serious',
        text: 'হিরো সাইজা সিরিয়াস লুক দিয়া খাড়া!',
        effects: { happiness: -10, fame: -15 },
        outcomeText: 'তোর সিরিয়াস লুক দেইখা পোলাপাইন তোরে কোষ্ঠকাঠিন্যের রোগী বানায়া টিকটকে মিম বানাইছে! তুই পুরাই রোস্টেড!',
        tone: 'funny',
      },
    ],
  },
];