import type { LifeEventDef } from '@/lib/engine/types';

export const TEEN_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'teen_acne',
    text: 'One morning you look in the mirror and meet a very unwelcome red visitor.',
    minAge: 13,
    maxAge: 17,
    weight: 90,
    tone: 'bad',
    category: 'teen',
    tags: ['looks'],
    choices: [
      {
        id: 'acne_disguise',
        text: 'Wear a hat and stare at your shoes all day',
        effects: { looks: 2 },
        outcomeText: 'The hat does not fool anyone, but it made you feel in control.',
        tone: 'neutral',
      },
      {
        id: 'acne_toothpaste',
        text: 'Try the internet remedy involving toothpaste',
        effects: { health: -1, happiness: 3 },
        outcomeText: 'It does nothing except make your face smell of mint. Science pending.',
        tone: 'funny',
      },
      {
        id: 'acne_ownit',
        text: 'Shrug and carry on like it is not there',
        effects: { happiness: 6, smarts: 2 },
        outcomeText: 'Turns out nobody was counting your spots except you.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_crush',
    text: 'The art-club captain smiled at you between classes. You have not recovered.',
    minAge: 13,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'crush_smile',
        text: 'Smile back, then pretend to check your shoe',
        effects: { happiness: 12, looks: 2 },
        outcomeText: 'A six-second moment that you will relive for a week.',
        tone: 'good',
      },
      {
        id: 'crush_wave',
        text: 'Wave with your whole arm and own it',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'Openly friendly, honestly friendly. The wave does its work.',
        tone: 'neutral',
      },
      {
        id: 'crush_lookaway',
        text: 'Stare fixedly at the fire alarm',
        effects: { smarts: -1, happiness: -3 },
        outcomeText: 'The fire alarm was very interesting, actually. You know nothing else.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_party',
    text: 'A school dance is happening on Friday. The entire cafeteria is debating attendance.',
    minAge: 14,
    maxAge: 18,
    weight: 70,
    tone: 'neutral',
    category: 'teen',
    choices: [
      {
        id: 'party_go',
        text: 'Go and meet everyone near the snacks',
        effects: { happiness: 12, looks: 3, health: -3 },
        outcomeText: 'The music is too loud and the snacks run out, but you were there.',
        tone: 'good',
      },
      {
        id: 'party_study',
        text: 'Skip it and get ahead on homework',
        effects: { smarts: 8, happiness: -4 },
        outcomeText: 'The chapter gets read. FOMO flashes once, then fades.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_test',
    text: 'A history exam looms. Half the class is panicking, the other half is lying.',
    minAge: 13,
    maxAge: 17,
    weight: 85,
    tone: 'neutral',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'test_study',
        text: 'Make a study sheet and grind through it',
        effects: { smarts: 6, happiness: -2 },
        outcomeText: 'Boring, but on exam day the answers sit right where you put them.',
        tone: 'good',
      },
      {
        id: 'test_group',
        text: 'Study in a loud group with snacks',
        effects: { smarts: 5, happiness: 3 },
        outcomeText: 'Forty percent real studying, sixty percent biscuit diplomacy. It works.',
        tone: 'neutral',
      },
      {
        id: 'test_wing',
        text: 'Wing it on vibes alone',
        effects: { smarts: -3, happiness: 4 },
        outcomeText: 'You write with confidence about an empire that may not exist. Grade pending.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_part_time',
    text: 'The community center is hiring someone to organize the sports equipment room.',
    minAge: 15,
    maxAge: 18,
    weight: 55,
    tone: 'neutral',
    category: 'teen',
    tags: ['work'],
    choices: [
      {
        id: 'parttime_accept',
        text: 'Take the job and earn real money',
        effects: { money: 50, smarts: 3, addFlag: 'parttime_accept' },
        outcomeText: 'You are paid actual coins for arranging balls in order. The economy has noticed you.',
        tone: 'good',
      },
      {
        id: 'parttime_decline',
        text: 'Decline and guard your weekends',
        effects: { happiness: 5 },
        outcomeText: 'The weekends are yours. The ball room waits for another hero.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_sports_tryout',
    text: 'The school team is holding tryouts and you half-signed up before you could stop yourself.',
    minAge: 13,
    maxAge: 18,
    weight: 60,
    tone: 'good',
    category: 'teen',
    tags: ['health', 'sport'],
    choices: [
      {
        id: 'tryout_train',
        text: 'Train hard all week and go all in',
        effects: { health: 8, happiness: 5 },
        outcomeText: 'Every bruise is proof. You make the roster by exactly one spot.',
        tone: 'good',
      },
      {
        id: 'tryout_show',
        text: 'Show up, give one honest try, accept the result',
        effects: { health: 2, smarts: 3 },
        outcomeText: 'You do not make it, but you learn you survive a public miss.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_curfew',
    text: 'You are home fourteen minutes late and the porch light is on like a searchlight.',
    minAge: 14,
    maxAge: 17,
    weight: 50,
    tone: 'bad',
    category: 'teen',
    choices: [
      {
        id: 'curfew_sneak',
        text: 'Slip in through the back window',
        effects: { smarts: 3, karma: -8 },
        outcomeText: 'You land cleanly, only to find the kitchen light on and a "we need to talk" brewing.',
        tone: 'funny',
      },
      {
        id: 'curfew_honest',
        text: 'Walk in, apologize, take the lecture',
        effects: { karma: 8, happiness: -4 },
        outcomeText: 'The lecture is long, but the trust account stays full.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_science_fair',
    text: 'The science fair is looking for volunteers. Everyone has a power of two thoughts about it.',
    minAge: 12,
    maxAge: 17,
    weight: 40,
    tone: 'good',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'science_fair_volcano',
        text: 'Build a baking-soda volcano and own the floor',
        effects: { smarts: 6, happiness: 8 },
        outcomeText: 'The volcano erupts a little too well and the janitor is called. Glorious.',
        tone: 'funny',
      },
      {
        id: 'science_fair_help',
        text: 'Help two nervous teams set up their boards',
        effects: { karma: 8, smarts: 2 },
        outcomeText: 'Three projects show up polished, and yours is the glue that held them.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_first_wage',
    text: 'Your first paycheck lands in your hand. It is smaller than you dreamed and taller than it looks.',
    minAge: 15,
    maxAge: 18,
    weight: 45,
    tone: 'good',
    category: 'teen',
    moment: 'money',
    tags: ['work', 'money'],
    requiredFlags: ['parttime_accept'],
    choices: [
      {
        id: 'wage_save',
        text: 'Stash it in a savings tin with great ceremony',
        effects: { smarts: 3, money: 10 },
        outcomeText: 'The tin feels heavier in the best way. First coin, first fort.',
        tone: 'good',
      },
      {
        id: 'wage_spend',
        text: 'Spend it all on snacks for the friend group',
        effects: { happiness: 10, karma: 6 },
        outcomeText: 'One glorious afternoon, then pockets full of crumbs and fond memory.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_mock_exam_shock',
    text: 'The mock exam results board goes up with the cheerful announcement that yellow means "revise more".',
    minAge: 13,
    maxAge: 17,
    weight: 60,
    tone: 'bad',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'mock_panic_revise',
        text: 'Build a revision timetable and actually follow it',
        effects: { smarts: 6, happiness: -1 },
        outcomeText: 'The real exams arrive and the yellow shrinks to a polite amber.',
        tone: 'good',
      },
      {
        id: 'mock_panic_bash',
        text: 'Cram wildly the night before each paper',
        effects: { smarts: -4, health: -2, happiness: -2 },
        outcomeText: 'The yellow stays. So does the cramming. Some cycles are hard to break.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'teen_talent_show',
    text: 'The school talent show has a slot open and the crowd\'s expectations are already enormous.',
    minAge: 13,
    maxAge: 17,
    weight: 45,
    tone: 'good',
    category: 'teen',
    tags: ['fame', 'hobby'],
    choices: [
      {
        id: 'talent_perform',
        text: 'Perform, badly but bravely',
        effects: { fame: 4, happiness: 8, looks: 2 },
        outcomeText: 'The applause is real, the blush is realer, and everyone knows your name now.',
        tone: 'good',
      },
      {
        id: 'talent_backstage',
        text: 'Run sound and lights instead',
        effects: { smarts: 3, karma: 3 },
        outcomeText: 'The show runs perfectly from your boards. Nobody notices. That is the job.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_group_photo',
    text: 'The year photo is being taken and the photographer has an elaborate idea involving stepping.',
    minAge: 13,
    maxAge: 18,
    weight: 45,
    tone: 'funny',
    category: 'teen',
    tags: ['school'],
    choices: [
      {
        id: 'groupphoto_fun',
        text: 'Do the peace sign, fully committing',
        effects: { happiness: 6, looks: 1 },
        outcomeText: 'Your peace sign is now in the yearbook forever, above a quiet smirk.',
        tone: 'funny',
      },
      {
        id: 'groupphoto_serious',
        text: 'Stand solemnly, like a small diplomat',
        effects: { happiness: 3, fame: 1 },
        outcomeText: 'The diplomat expression will be gleefully memed by your friends.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_dorm_bet',
    text: 'Your friend bets you a week of chores that you cannot learn to whistle with two fingers by Friday.',
    minAge: 14,
    maxAge: 18,
    weight: 40,
    tone: 'funny',
    category: 'teen',
    tags: ['friendship', 'daily-life'],
    choices: [
      {
        id: 'dormbet_practice',
        text: 'Grind it out in the bathroom mirror',
        effects: { smarts: 3, happiness: 4 },
        outcomeText: 'Thursday night: a thin whistle. Friday: a victory blast that echoes down the hall.',
        tone: 'good',
      },
      {
        id: 'dormbet_chores',
        text: 'Accept the chores and level up as a laundromat philosopher',
        effects: { karma: 3, happiness: 1 },
        outcomeText: 'A week of folding. The friend\'s fingers are now, allegedly, insured.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_fast_track',
    text: 'A fast-track study group opens for the keen, the curious, and the terminally early-risers.',
    minAge: 13,
    maxAge: 16,
    weight: 50,
    tone: 'neutral',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'fasttrack_join',
        text: 'Join and ride the friendly pressure',
        effects: { smarts: 8, happiness: -1 },
        outcomeText: 'Your grades climb and your jokes get, statistically, denser.',
        tone: 'good',
      },
      {
        id: 'fasttrack_skip',
        text: 'Skip it and keep your afternoons',
        effects: { happiness: 4 },
        outcomeText: 'The group emails you. You cheer them on from the sunshine.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_sleepover',
    text: 'A sleepover at your place, where the official schedule shows "snacks", and the unofficially shows chaos.',
    minAge: 12,
    maxAge: 16,
    weight: 50,
    tone: 'good',
    category: 'teen',
    tags: ['friendship'],
    choices: [
      {
        id: 'sleepover_epic',
        text: 'Plan the full epic night of games and films',
        effects: { happiness: 8, karma: 3 },
        outcomeText: 'The morning after is a battlefield of sleeping bags and loyalty.',
        tone: 'good',
      },
      {
        id: 'sleepover_quiet',
        text: 'Keep it to two friends and one documentary',
        effects: { happiness: 4, smarts: 2 },
        outcomeText: 'Calm, warm, and with unbroken snack protocol.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_phone_dare',
    text: 'A group chat declares that someone must call their crush. Everyone except you has a plan.',
    minAge: 14,
    maxAge: 17,
    weight: 45,
    tone: 'funny',
    category: 'teen',
    tags: ['friendship', 'romance'],
    choices: [
      {
        id: 'phonedare_call',
        text: 'Do the call, voice crack and all',
        effects: { happiness: 7, looks: 2 },
        outcomeText: 'It is awkward, brief, and somehow wins the day. Legend status achieved.',
        tone: 'funny',
      },
      {
        id: 'phonedare_text',
        text: 'Send a funny message instead and blame signal',
        effects: { smarts: 3, karma: 1 },
        outcomeText: 'The excuse is transparent and everyone pretends to believe it.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_penpal',
    text: 'Your English teacher suggests a pen-pal exchange with a school in another country.',
    minAge: 13,
    maxAge: 16,
    weight: 45,
    tone: 'neutral',
    category: 'teen',
    tags: ['education', 'friendship'],
    choices: [
      {
        id: 'penpal_write',
        text: 'Write a proper first letter',
        effects: { smarts: 4, happiness: 4 },
        outcomeText: 'The reply arrives in six weeks and tastes of somewhere else entirely.',
        tone: 'good',
      },
      {
        id: 'penpal_card',
        text: 'Send a postcard with a very tidy doodle',
        effects: { happiness: 2, karma: 2 },
        outcomeText: 'The doodle is discussed warmly on the other side of the world.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_show_and_tell',
    text: 'Show-and-tell is on and the spotlight is terrifyingly square.',
    minAge: 11,
    maxAge: 14,
    weight: 45,
    tone: 'neutral',
    category: 'teen',
    tags: ['school', 'fame'],
    choices: [
      {
        id: 'showtell_object',
        text: 'Bring a genuinely weird object and own the story',
        effects: { fame: 3, happiness: 6, smarts: 1 },
        outcomeText: 'The class votes it the most memorable. You are briefly royalty.',
        tone: 'good',
      },
      {
        id: 'showtell_coin',
        text: 'Bring a coin and wing the story',
        effects: { happiness: -1, smarts: 1 },
        outcomeText: 'The coin story folds after forty seconds. The applause is kind.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_cycling_team',
    text: 'The neighbourhood cycling club is looking for junior riders for the summer series.',
    minAge: 14,
    maxAge: 17,
    weight: 45,
    tone: 'neutral',
    category: 'teen',
    tags: ['sports', 'health'],
    choices: [
      {
        id: 'cycling_join',
        text: 'Join and earn your very real jersey',
        effects: { health: 7, happiness: 4 },
        outcomeText: 'By August your calves are philosophical works of art.',
        tone: 'good',
      },
      {
        id: 'cycling_pump',
        text: 'Become the trackside pump-and-tire whisperer',
        effects: { smarts: 2, karma: 3 },
        outcomeText: 'Every rider owes a fraction of their podium to your valve skills.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_school_play',
    text: 'The school play has a juicy minor role and auditions are unusually unmocked.',
    minAge: 13,
    maxAge: 17,
    weight: 45,
    tone: 'neutral',
    category: 'teen',
    tags: ['fame', 'hobby'],
    choices: [
      {
        id: 'play_audition',
        text: 'Audition and go for it',
        effects: { fame: 4, happiness: 7 },
        outcomeText: 'You get the part, memorise everything, and forget everything on opening night. Almost.',
        tone: 'good',
      },
      {
        id: 'play_lightboard',
        text: 'Run the lightboard instead',
        effects: { smarts: 3, karma: 2 },
        outcomeText: 'You control the spotlight, which is its own kind of power.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_homework_storm',
    text: 'Four subjects have decided today is the day to strike simultaneously.',
    minAge: 13,
    maxAge: 17,
    weight: 50,
    tone: 'bad',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'homework_march',
        text: 'Systematically march through the pile',
        effects: { smarts: 5, happiness: -2, health: -2 },
        outcomeText: 'By midnight it is done. The desk looks relieved.',
        tone: 'good',
      },
      {
        id: 'homework_selection',
        text: 'Do the best two and brave the other two',
        effects: { smarts: 1, happiness: 2 },
        outcomeText: 'The strategy is bold. The teachers notice, in their own gentle ways.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'teen_secret_note',
    text: 'A neatly folded origami note slips out of your {physics notebook|pencil pouch|locker}. Inside is a handwritten poem about your {smile|laugh|eyes}.',
    minAge: 13,
    maxAge: 17,
    weight: 85,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'note_investigate',
        text: 'Quietly cross-reference the handwriting across the classroom',
        effects: { smarts: 4, happiness: 10 },
        outcomeText: 'You catch someone blushing three desks over. Hearts race.',
        tone: 'good',
      },
      {
        id: 'note_treasured',
        text: 'Tuck it into your private diary as a cherished keepsake',
        effects: { happiness: 8, looks: 2 },
        outcomeText: 'A sweet mystery that brightens the rest of your school term.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_school_dance',
    text: 'The annual school cultural night is this Friday. The cafeteria is buzzing with talk of {who is going with whom|extravagant invites|homemade corsages}.',
    minAge: 14,
    maxAge: 17,
    weight: 85,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'dance_ask_crush',
        text: 'Gather your courage and ask your crush during lunch',
        effects: { happiness: 14, looks: 3, fame: 4 },
        outcomeText: 'They gasped, smiled warmly, and accepted. High fives all around!',
        tone: 'good',
      },
      {
        id: 'dance_friend_crew',
        text: 'Go with a tight-knit squad and dance foolishly together',
        effects: { happiness: 10, karma: 4 },
        outcomeText: 'No romantic pressure, just pure energetic laughter under the disco lights.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_shared_earphones',
    text: 'On the school bus ride home, your crush notices your playlist and offers to {share an earphone|swap favorite tracks}.',
    minAge: 13,
    maxAge: 17,
    weight: 80,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'earphone_indie_track',
        text: 'Play your obscure favorite indie acoustic song',
        effects: { happiness: 10, smarts: 3, looks: 2 },
        outcomeText: 'They close their eyes and hum along. An instant connection.',
        tone: 'good',
      },
      {
        id: 'earphone_pop_banger',
        text: 'Blast an upbeat pop anthem and sing along loudly',
        effects: { happiness: 8, fame: 2 },
        outcomeText: 'The whole back row of the bus joins the chorus.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_monsoon_umbrella',
    text: 'A torrential cloudburst traps students under the school gates. Your crush is standing alone without {an umbrella|a raincoat}.',
    minAge: 13,
    maxAge: 17,
    weight: 80,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'umbrella_share',
        text: 'Open your wide black umbrella and offer to walk them to the rickshaw',
        effects: { happiness: 15, karma: 6, looks: 3 },
        outcomeText: 'Walking shoulder-to-shoulder through the rain feels cinematic.',
        tone: 'good',
      },
      {
        id: 'umbrella_lend',
        text: 'Hand over your umbrella and brave the rain in a heroic sprint',
        effects: { health: -1, happiness: 10, karma: 8 },
        outcomeText: 'Soaked to the bone, but your legendary gallantry is the talk of the hallway.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_tuition_coaching',
    text: 'Your parents enroll you in a notoriously strict {math coaching center|physics tuition class} with fifty other stressed teenagers.',
    minAge: 14,
    maxAge: 17,
    weight: 75,
    tone: 'neutral',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'tuition_front_row',
        text: 'Sit in the front row and take obsessive notes',
        effects: { smarts: 8, happiness: -4 },
        outcomeText: 'Your test scores soar, even if your social life took a hit.',
        tone: 'good',
      },
      {
        id: 'tuition_back_bench',
        text: 'Sit at the back bench cracking whispers with new friends',
        effects: { happiness: 8, smarts: 1 },
        outcomeText: 'You barely learned calculus, but you made lifelong comrades.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_bunk_fuchka',
    text: 'During a dull free period, your friends suggest slipping out past the gatekeeper for {spicy fuchka and chotpoti|street samosas and hot tea}.',
    minAge: 14,
    maxAge: 17,
    weight: 75,
    tone: 'funny',
    category: 'teen',
    tags: ['adventure'],
    choices: [
      {
        id: 'bunk_feast',
        text: 'Climb the low brick wall and indulge in extra tamarind sauce',
        effects: { happiness: 12, health: -1, karma: -3 },
        outcomeText: 'Crispy, tangy perfection. You sneaked back in without raising alarms.',
        tone: 'good',
      },
      {
        id: 'bunk_prefect_duty',
        text: 'Refuse the escape and warn them the disciplinary teacher is patrolling',
        effects: { smarts: 4, karma: 4 },
        outcomeText: 'The gang got caught outside ten minutes later. Your record stays clean.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_voice_crack',
    text: 'During an important English presentation, your voice suddenly {cracks like a squeaking saxophone|drops two octaves unexpectedly}.',
    minAge: 13,
    maxAge: 16,
    weight: 70,
    tone: 'funny',
    category: 'teen',
    tags: ['social'],
    choices: [
      {
        id: 'voice_laugh_it_off',
        text: 'Bow dramatically and announce the pitch was intentional',
        effects: { fame: 5, happiness: 6, smarts: 2 },
        outcomeText: 'The class erupted in genuine cheers. Awkwardness conquered!',
        tone: 'good',
      },
      {
        id: 'voice_drink_water',
        text: 'Cough into your fist, take a sip of water, and press forward',
        effects: { smarts: 3, happiness: 1 },
        outcomeText: 'You soldiered through like a dignified professional.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_guitar_phase',
    text: 'Inspired by rock bands, you convince your uncle to lend you an old acoustic guitar with {rusty nylon strings|a faded wooden finish}.',
    minAge: 13,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['creativity'],
    choices: [
      {
        id: 'guitar_practice_fingers',
        text: 'Practice chord transitions until your fingertips develop tough calluses',
        effects: { smarts: 5, looks: 4, happiness: 8 },
        outcomeText: 'You mastered the intro to a classic ballad! Friends are genuinely impressed.',
        tone: 'good',
      },
      {
        id: 'guitar_rooftop_jam',
        text: 'Host an evening rooftop jam session with neighborhood peers',
        effects: { fame: 6, happiness: 10 },
        outcomeText: 'Passersby stopped to listen as twilight set over the neighborhood.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_first_tutoring_job',
    text: 'A neighbor asks if you can tutor their {hyperactive 4th grader|rebellious younger cousin} in general science for extra pocket money.',
    minAge: 15,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['wealth'],
    choices: [
      {
        id: 'tutor_patient_teacher',
        text: 'Design fun illustrated diagrams and reward good answers with candy',
        effects: { money: 35, smarts: 5, karma: 5, happiness: 6 },
        outcomeText: 'The kid passed their exam with flying colors! The parents tipped you generously.',
        tone: 'good',
      },
      {
        id: 'tutor_give_up',
        text: 'Give up when the kid draws cartoons all over your lesson notes',
        effects: { money: 10, happiness: -3 },
        outcomeText: 'Teaching is not for the faint of heart. You respectfully bowed out.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_science_fair_disaster',
    text: 'At the inter-school science fair, your {papier-mâché volcano|electromagnetic motor|hydraulic bridge} begins making ominous hissing noises.',
    minAge: 14,
    maxAge: 17,
    weight: 70,
    tone: 'funny',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'science_improvise',
        text: 'Proudly claim the excessive foam is a demonstration of rapid carbonation',
        effects: { smarts: 6, fame: 5, happiness: 6 },
        outcomeText: 'The judges awarded you the Innovation Prize for thinking on your feet!',
        tone: 'good',
      },
      {
        id: 'science_evacuate',
        text: 'Yell for everyone to take cover and pull the plug',
        effects: { happiness: 4, karma: 2 },
        outcomeText: 'Red food dye splashed across the banner, but no one was injured.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_debate_podium',
    text: 'You are selected as the final speaker for the school debate team against your fiercest {crosstown rivals|championship opponents}.',
    minAge: 14,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'debate_rebuttal',
        text: 'Deliver a razor-sharp, statistics-backed closing argument',
        effects: { smarts: 8, fame: 8, happiness: 10 },
        outcomeText: 'The auditorium erupted into standing applause. Trophy secured!',
        tone: 'good',
      },
      {
        id: 'debate_emotional_plea',
        text: 'Appeal to raw human empathy with poetic storytelling',
        effects: { karma: 6, smarts: 4, happiness: 6 },
        outcomeText: 'Even the opposing adjudicator wiped away a small tear.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_haircut_experiment',
    text: 'Tired of your standard school haircut, you show the local barber a picture of a {Korean pop star|trendy European footballer}.',
    minAge: 14,
    maxAge: 17,
    weight: 75,
    tone: 'funny',
    category: 'teen',
    tags: ['looks'],
    choices: [
      {
        id: 'haircut_slay',
        text: 'Style the fresh fade with pomade and walk into class with swagger',
        effects: { looks: 8, happiness: 8 },
        outcomeText: 'Compliments flood in from hallway lockers to the bus stop.',
        tone: 'good',
      },
      {
        id: 'haircut_botched',
        text: 'Realize he gave you a bowl cut and live under a hoodie for three weeks',
        effects: { looks: -6, happiness: -5 },
        outcomeText: 'Hair grows back. The jokes, however, will linger for a semester.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_rooftop_cricket',
    text: 'A fierce afternoon rooftop tape-ball cricket match is tied on the last ball. You are on {strike with three runs needed|bowling the final over}.',
    minAge: 13,
    maxAge: 17,
    weight: 80,
    tone: 'good',
    category: 'teen',
    tags: ['sports'],
    choices: [
      {
        id: 'cricket_loft_six',
        text: 'Swing hard for the fences over the water tank',
        effects: { health: 3, happiness: 12, fame: 6 },
        outcomeText: 'A towering maximum! The ball is lost forever, but the legend lives.',
        tone: 'good',
      },
      {
        id: 'cricket_safe_single',
        text: 'Dab the ball softly for a quick scampering single',
        effects: { smarts: 3, health: 2, happiness: 5 },
        outcomeText: 'A disciplined tie. Both sides share sweet lemon squash in harmony.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_gaming_allnighter',
    text: 'Your friends launch a multiplayer squad tournament on the night before a {school holiday|routine history quiz}.',
    minAge: 13,
    maxAge: 17,
    weight: 70,
    tone: 'funny',
    category: 'teen',
    tags: ['social'],
    choices: [
      {
        id: 'gaming_victory_royale',
        text: 'Play until 4 AM fueled by potato chips and pure adrenaline',
        effects: { happiness: 10, health: -4, smarts: -2 },
        outcomeText: 'Three back-to-back championship wins. You slept through half of Saturday.',
        tone: 'funny',
      },
      {
        id: 'gaming_responsible_logoff',
        text: 'Log off at midnight after one solid victory',
        effects: { health: 2, smarts: 2, happiness: 4 },
        outcomeText: 'A balanced evening with eight hours of glorious restorative sleep.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_library_whispers',
    text: 'While studying for finals in the quiet corner of the city library, someone slides you a {chilled chocolate milk|sweet mango juice box} with a smiley face drawn on it.',
    minAge: 14,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'library_note_back',
        text: 'Slide back a thank-you doodle on a yellow sticky note',
        effects: { happiness: 12, looks: 2 },
        outcomeText: 'You exchange quiet smiles across the wooden bookshelves all afternoon.',
        tone: 'good',
      },
      {
        id: 'library_drink_sip',
        text: 'Take a grateful sip and offer half your biscuits in return',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'A silent pact of shared study snacks is forged.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_bicycle_upgrade',
    text: 'You save up pocket money to customize your bicycle with {neon rim lights|a bell and leather grips|new speed gears}.',
    minAge: 13,
    maxAge: 16,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'bike_race_hill',
        text: 'Race down the steep neighborhood flyover ramp',
        effects: { health: 4, happiness: 10, fame: 2 },
        outcomeText: 'Wind in your hair, rubber gripping tarmac. Pure exhilaration!',
        tone: 'good',
      },
      {
        id: 'bike_neighborhood_cruise',
        text: 'Leisurely cruise past friends hanging out by the corner store',
        effects: { looks: 4, happiness: 6 },
        outcomeText: 'The shiny new components turn plenty of appreciative heads.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_art_competition',
    text: 'The regional youth council announces an art competition themed around {Dhaka at twilight|dreams of the future|heritage and monsoon}.',
    minAge: 14,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['creativity'],
    choices: [
      {
        id: 'art_acrylic_canvas',
        text: 'Paint a vivid, colorful canvas of rain-washed city streets',
        effects: { smarts: 6, fame: 8, happiness: 10 },
        outcomeText: 'Your painting was selected for exhibition in the main gallery hall!',
        tone: 'good',
      },
      {
        id: 'art_charcoal_sketch',
        text: 'Create a moody, detailed monochrome sketch of old brick alleys',
        effects: { smarts: 5, happiness: 6 },
        outcomeText: 'The art teacher praised your mastery of shadows and contrast.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_street_food_dare',
    text: 'Friends dare you to eat a fuchka loaded with three times the usual amount of {fiery green chilies|crushed naga morich}.',
    minAge: 13,
    maxAge: 17,
    weight: 75,
    tone: 'funny',
    category: 'teen',
    tags: ['social'],
    choices: [
      {
        id: 'food_swallow_brave',
        text: 'Swallow it whole without blinking or tearing up',
        effects: { health: -3, fame: 8, happiness: 8 },
        outcomeText: 'Your mouth felt like molten magma, but you earned unbreakable bragging rights.',
        tone: 'funny',
      },
      {
        id: 'food_sip_water',
        text: 'Chicken out and order sweet doi (yogurt) instead',
        effects: { health: 2, happiness: 4 },
        outcomeText: 'Cool, creamy sweetness saved your stomach from utter ruin.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_first_concert',
    text: 'A popular local indie band is playing a free open-air concert at the {university amphitheater|lakeside park}.',
    minAge: 15,
    maxAge: 17,
    weight: 80,
    tone: 'good',
    category: 'teen',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'concert_front_crowd',
        text: 'Push to the front rail and sing your lungs out',
        effects: { happiness: 15, looks: 2, health: -1 },
        outcomeText: 'Electrifying bass, screaming guitar riffs, and memories to last forever.',
        tone: 'good',
      },
      {
        id: 'concert_grassy_hill',
        text: 'Sit on the grassy embankment enjoying the twilight breeze',
        effects: { happiness: 10, health: 2 },
        outcomeText: 'Melodic tunes drifting across the water made for a tranquil evening.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_fashion_rebellion',
    text: 'You wear a bold vintage jacket found at {a thrift bazaar|your father old trunk} to school on free-dress day.',
    minAge: 14,
    maxAge: 17,
    weight: 70,
    tone: 'neutral',
    category: 'teen',
    tags: ['looks'],
    choices: [
      {
        id: 'fashion_own_vintage',
        text: 'Rock the look with oversized sunglasses and complete confidence',
        effects: { looks: 6, fame: 6, happiness: 8 },
        outcomeText: 'People asked what retro brand it was. You set an accidental trend.',
        tone: 'good',
      },
      {
        id: 'fashion_modest',
        text: 'Take it off and keep it folded in your backpack',
        effects: { happiness: -1 },
        outcomeText: 'Blended right back into the familiar crowd of blue jeans and polo shirts.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_stray_puppy_rescue',
    text: 'You find a shivering stray puppy sheltering from monsoon gutters under a {vegetable cart|tea stall bench}.',
    minAge: 13,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['pets'],
    choices: [
      {
        id: 'puppy_vet_clean',
        text: 'Dry it with your gym towel and find a welcoming adoption home',
        effects: { karma: 12, happiness: 12 },
        outcomeText: 'A kind neighbor adopted the pup. You get greeted with tail wags daily.',
        tone: 'good',
      },
      {
        id: 'puppy_feed_biscuits',
        text: 'Buy a packet of milk biscuits and leave a dry cardboard box',
        effects: { karma: 6, happiness: 6 },
        outcomeText: 'The puppy ate eagerly and curled up warmly out of the rain.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_math_olympiad',
    text: 'The principal selects you to represent the school at the national {Mathematics Olympiad|Informatics Contest}.',
    minAge: 14,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'olympiad_solve_proof',
        text: 'Crack an elegant prime number theorem problem in the final round',
        effects: { smarts: 10, fame: 8, happiness: 10 },
        outcomeText: 'National runner-up medal! Your picture was posted on the school noticeboard.',
        tone: 'good',
      },
      {
        id: 'olympiad_enjoy_free_snacks',
        text: 'Do your best and demolish the buffet of free samosas and sweets',
        effects: { smarts: 4, happiness: 8 },
        outcomeText: 'A respectable certificate and a deeply satisfied appetite.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_rumor_mill',
    text: 'A silly playground rumor spreads claiming that you have a secret crush on the {head prefect|class president}.',
    minAge: 13,
    maxAge: 16,
    weight: 75,
    tone: 'funny',
    category: 'teen',
    tags: ['social'],
    choices: [
      {
        id: 'rumor_play_along',
        text: 'Dramatically wink whenever their name is mentioned',
        effects: { fame: 6, happiness: 6, looks: 2 },
        outcomeText: 'The mystery only grew more hilarious. Everyone was kept guessing.',
        tone: 'funny',
      },
      {
        id: 'rumor_debunk',
        text: 'Firmly declare it total fiction with an eye roll',
        effects: { karma: 2, happiness: 2 },
        outcomeText: 'The gossip fizzled out within two days as new drama took over.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_rooftop_gardening',
    text: 'Your grandmother asks for help planting {red chili bushes|fragrant jasmine shrubs|potted tomatoes} on the rooftop terrace.',
    minAge: 13,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['family'],
    choices: [
      {
        id: 'garden_fertile_soil',
        text: 'Mix the compost, haul the clay pots, and arrange a green sanctuary',
        effects: { karma: 8, happiness: 8, health: 3 },
        outcomeText: 'Fresh white jasmine blooms perfume the evening breeze. Grandma smiles fondly.',
        tone: 'good',
      },
      {
        id: 'garden_watering_quick',
        text: 'Water the pots briskly and enjoy grandmother hot sweet tea',
        effects: { happiness: 6, karma: 4 },
        outcomeText: 'A cozy family chat with stories of old Dhaka.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_study_group_crush',
    text: 'Your crush invites you to a weekend study group to prepare for upcoming {board exams|mid-terms} at a local café.',
    minAge: 15,
    maxAge: 17,
    weight: 80,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'study_teach_concept',
        text: 'Patiently explain a tricky chemistry formula using funny analogies',
        effects: { smarts: 6, happiness: 12, looks: 3 },
        outcomeText: 'Their face lit up with understanding: "You explained that better than our teacher!"',
        tone: 'good',
      },
      {
        id: 'study_order_pastries',
        text: 'Treat the table to chocolate chip cookies to keep morale high',
        effects: { money: -5, happiness: 10, karma: 4 },
        outcomeText: 'The study session turned into two hours of warm, effortless bonding.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_sports_day_sprint',
    text: 'The 100-meter sprint on Annual Sports Day is called. You are lined up against the {fastest runner in your grade|defending champion}.',
    minAge: 13,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['sports'],
    choices: [
      {
        id: 'sprint_dive_finish',
        text: 'Explode off the blocks and dip your shoulder at the ribbon',
        effects: { health: 6, fame: 8, happiness: 10 },
        outcomeText: 'First place by a chest-width! The entire house bleachers erupted in chants.',
        tone: 'good',
      },
      {
        id: 'sprint_solid_run',
        text: 'Maintain clean form and secure a podium finish',
        effects: { health: 4, happiness: 6 },
        outcomeText: 'Bronze medal proudly hung around your neck before the parade.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_bus_rickshaw_race',
    text: 'Running late for morning assembly, your rickshaw puller offers a shortcut through {a bustling fish market|narrow cobblestone alleyways}.',
    minAge: 13,
    maxAge: 17,
    weight: 70,
    tone: 'funny',
    category: 'teen',
    tags: ['adventure'],
    choices: [
      {
        id: 'rickshaw_go_fast',
        text: 'Cheer him on and hold tight to the wooden armrest',
        effects: { happiness: 8, looks: -1 },
        outcomeText: 'Slalomed through parked scooters and slipped into the gate just as the bell rang!',
        tone: 'good',
      },
      {
        id: 'rickshaw_play_safe',
        text: 'Ask him to take the main road calmly and accept a tardy mark',
        effects: { karma: 2, happiness: 1 },
        outcomeText: 'You had to stand outside for five minutes, but you arrived safely.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_poetry_slam',
    text: 'The literary club hosts an evening open-mic poetry slam under the {campus banyan tree|school auditorium lamps}.',
    minAge: 14,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['creativity'],
    choices: [
      {
        id: 'poetry_recite_passionate',
        text: 'Recite a heartfelt rhythm piece about adolescent dreams and late-night skies',
        effects: { smarts: 6, fame: 6, happiness: 10 },
        outcomeText: 'Snaps and applause echoed under the leaves. Several peers asked for a copy.',
        tone: 'good',
      },
      {
        id: 'poetry_listen_applaud',
        text: 'Sit quietly in the audience sipping warm cardamom chai',
        effects: { smarts: 3, happiness: 6 },
        outcomeText: 'A tranquil evening soaking in the creative spirit of youth.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_lost_wallet_dilemma',
    text: 'On a park bench, you spot an abandoned leather wallet containing {several hundred taka and an ID card|cash and family photos}.',
    minAge: 13,
    maxAge: 17,
    weight: 70,
    tone: 'neutral',
    category: 'teen',
    tags: ['karma'],
    choices: [
      {
        id: 'wallet_return_owner',
        text: 'Track down the owner using the student card and return it intact',
        effects: { karma: 15, happiness: 10, fame: 4 },
        outcomeText: 'The relieved university student bought you sweets and thanked you profusely.',
        tone: 'good',
      },
      {
        id: 'wallet_finder_fee',
        text: 'Take a small finders fee before turning it in to the guards',
        effects: { money: 20, karma: -8 },
        outcomeText: 'Extra cash in your pocket, but a little thorn in your conscience.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_kite_festival',
    text: 'The traditional Shakrain winter kite festival fills the sky with thousands of {fighting kites and glowing lanterns|soaring dragons and fireworks}.',
    minAge: 13,
    maxAge: 17,
    weight: 80,
    tone: 'good',
    category: 'teen',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'shakrain_kite_duel',
        text: 'Engage in an intense aerial dogfight using glass-coated manja line',
        effects: { health: 2, fame: 6, happiness: 12 },
        outcomeText: 'Bho-khatta! You severed three competitor lines and claimed rooftop glory.',
        tone: 'good',
      },
      {
        id: 'shakrain_fire_spinning',
        text: 'Watch the skilled older kids breathe fire and dance to folk beats',
        effects: { happiness: 10, fame: 2 },
        outcomeText: 'A winter spectacle of lights, bass, and winter sweets on the rooftop.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_coding_project',
    text: 'You decide to teach yourself programming by building a {text-based life sim game|retro arcade clone} on an old desktop.',
    minAge: 14,
    maxAge: 17,
    weight: 75,
    tone: 'good',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'code_publish_online',
        text: 'Fix the bugs, polish the UI, and upload it to an online indie forum',
        effects: { smarts: 10, fame: 6, happiness: 10 },
        outcomeText: 'Comments praised your clever dialogue and clean logic. A coder is born!',
        tone: 'good',
      },
      {
        id: 'code_share_friends',
        text: 'Send the link to your school group chat for playtesting',
        effects: { smarts: 6, happiness: 8 },
        outcomeText: 'Friends spent the entire weekend trying to get the highest score.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_school_play_audition',
    text: 'Auditions open for the annual adaptation of a {historical tragedy|romantic comedy}. A lead role is up for grabs.',
    minAge: 14,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['creativity'],
    choices: [
      {
        id: 'play_dramatic_monologue',
        text: 'Give a thunderous, tearful monologue with stage presence',
        effects: { looks: 4, fame: 8, happiness: 10 },
        outcomeText: 'The drama teacher cast you as the protagonist on the spot!',
        tone: 'good',
      },
      {
        id: 'play_comic_relief',
        text: 'Audition for the witty sidekick with slapstick timing',
        effects: { happiness: 10, fame: 5 },
        outcomeText: 'You stole the show in rehearsals with hilarious ad-libs.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_sibling_advice',
    text: 'Your younger sibling comes to you in tears because {kids at school made fun of their shoes|they failed a spelling quiz}.',
    minAge: 13,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['family'],
    choices: [
      {
        id: 'sibling_comfort_snack',
        text: 'Listen patiently, share your favorite chocolate bar, and teach them a witty comeback',
        effects: { karma: 10, happiness: 8 },
        outcomeText: 'Tears turned into giggles. Your bond grew immensely stronger.',
        tone: 'good',
      },
      {
        id: 'sibling_study_together',
        text: 'Help them practice spelling until they get every word right',
        effects: { smarts: 3, karma: 8 },
        outcomeText: 'They scored top marks the next day and thanked you with a handwritten drawing.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_bazaar_bargain',
    text: 'Sent to the neighborhood bazaar alone, you must negotiate the price of {fresh seasonal fish|sweet winter cauliflower}.',
    minAge: 14,
    maxAge: 17,
    weight: 70,
    tone: 'funny',
    category: 'teen',
    tags: ['wealth'],
    choices: [
      {
        id: 'bazaar_firm_haggler',
        text: 'Employ the classic technique of pretending to walk away slowly',
        effects: { smarts: 6, money: 10, happiness: 6 },
        outcomeText: 'The vendor called you back and shaved twenty taka off the bill! A certified bargainer.',
        tone: 'good',
      },
      {
        id: 'bazaar_pay_full',
        text: 'Pay the asking price with a polite smile',
        effects: { karma: 3, happiness: 2 },
        outcomeText: 'The fishmonger threw in extra fresh coriander leaves as a friendly bonus.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_street_photography',
    text: 'Borrowing a camera, you spend Sunday morning capturing {candid portraits of old rickshaw wallahs|reflections in puddles along the river}.',
    minAge: 15,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['creativity'],
    choices: [
      {
        id: 'photo_print_gift',
        text: 'Print the portraits and gift them back to the subjects',
        effects: { karma: 12, happiness: 12, looks: 2 },
        outcomeText: 'The broad, wrinkly smiles in their hands made your heart soar.',
        tone: 'good',
      },
      {
        id: 'photo_social_post',
        text: 'Share the high-contrast black-and-white series online',
        effects: { fame: 8, happiness: 8 },
        outcomeText: 'The post went mini-viral in photography circles.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'teen_exam_superstition',
    text: 'On the morning of the big final exam, an aunt offers you {a hardboiled egg for good luck|a sweet spoonful of curd} before leaving.',
    minAge: 13,
    maxAge: 17,
    weight: 65,
    tone: 'funny',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'exam_eat_curd',
        text: 'Eat the curd respectfully and touch her feet for blessings',
        effects: { karma: 5, happiness: 6, smarts: 2 },
        outcomeText: 'Confidence surged through you as you opened the exam booklet.',
        tone: 'good',
      },
      {
        id: 'exam_decline_egg',
        text: 'Firmly refuse the egg: "No eggs, or I will score a big round zero!"',
        effects: { happiness: 4 },
        outcomeText: 'Everyone laughed at the superstition. You took the exam with a calm mind.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_first_crush_confession',
    text: 'On the last day of high school, you find yourself alone with your crush on the {breezy school rooftop|staircase after the farewell party}.',
    minAge: 16,
    maxAge: 17,
    weight: 85,
    tone: 'good',
    category: 'teen',
    tags: ['romance'],
    choices: [
      {
        id: 'confess_honest_feelings',
        text: 'Confess that you have liked them since the very first day of class',
        effects: { happiness: 16, looks: 4, karma: 4 },
        outcomeText: 'They held their breath, blushed deeply, and confessed they felt the exact same way!',
        tone: 'good',
      },
      {
        id: 'confess_stay_friends',
        text: 'Wish them the best for college and promise to stay in touch',
        effects: { happiness: 8, smarts: 4 },
        outcomeText: 'A bittersweet hug and phone numbers exchanged as sunset painted the sky.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'teen_street_cricket_sixer',
    text: 'During an intense alleyway tape-tennis cricket match, your powerhouse shot shatters {the neighborhood grocer shop window|a neighbor balcony flowerpot}.',
    minAge: 13,
    maxAge: 17,
    weight: 75,
    tone: 'funny',
    category: 'teen',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'cricket_own_up',
        text: 'Walk up sincerely, apologize, and promise to sweep the shards',
        effects: { karma: 8, happiness: 4, money: -3 },
        outcomeText: 'The elder admired your honesty: "Good shot though, young bowler had no chance!"',
        tone: 'good',
      },
      {
        id: 'cricket_sprint_away',
        text: 'Signal the team with urgent hand gestures and sprint into the nearest alley',
        effects: { health: 4, karma: -4, happiness: 5 },
        outcomeText: 'You escaped cleanly, but your legendary match remains postponed indefinitely.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'teen_science_fair_volcano',
    text: 'At the inter-school science fair, your {baking soda vinegar volcano|solar-powered water purifier} draws an unexpectedly huge audience.',
    minAge: 14,
    maxAge: 17,
    weight: 70,
    tone: 'good',
    category: 'teen',
    tags: ['education'],
    choices: [
      {
        id: 'fair_demonstrate_live',
        text: 'Give a charismatic live demonstration explaining the chemical reaction',
        effects: { smarts: 8, fame: 8, happiness: 10 },
        outcomeText: 'The judges awarded your team first prize ribbon amid enthusiastic applause!',
        tone: 'good',
      },
      {
        id: 'fair_humble_handout',
        text: 'Distribute neat handwritten diagrams and explain the environmental benefits',
        effects: { smarts: 6, karma: 6, happiness: 6 },
        outcomeText: 'Teachers complimented your thorough research and presentation etiquette.',
        tone: 'good',
      },
    ],
  },
];