import type { LifeEventDef } from '@/lib/engine/types';

/**
 * Universal pool (all ages). Several events span 0–120 so that every age,
 * whatever its flags, always has eligible events — this is the guarantee the
 * Gate 5 eligibility test asserts. Tone-tagged for the stinger system.
 */
export const UNIVERSAL_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'un_surprise_gift',
    text: 'হঠাত কইরা একখান গিফট আইলো—একটা কলম, বা টংয়ের চিপস। কেউ একজন তোর কথা ভাবছে মামা!',
    minAge: 0,
    maxAge: 120,
    weight: 60,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_gift_savor',
        text: 'এক্কেরে লগে লগে ইউজ করুম!',
        effects: { happiness: 6 },
        outcomeText: 'কলম পকেটে, আর চিপস পেটে। দিল খুশ!',
        tone: 'good',
      },
      {
        id: 'un_gift_pass',
        text: 'রাইখা দিমু, মাইঙ্কা চিপার দিনের লাইগা।',
        effects: { happiness: 3, smarts: 1 },
        outcomeText: 'ঠিকই বিপদের দিনে গিফটডা কামে দিলো, পুরাই জোস।',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_dog_moment',
    text: 'রাস্তার এক ত্যাড়া কুত্তা তোর সামনে আইসা এমন ভাব লইলো, মনে হয় এলাকার চেয়ারম্যান!',
    minAge: 0,
    maxAge: 120,
    weight: 60,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_dog_pet',
        text: 'খাড়াইয়া তারে পুরা ভিআইপি সম্মান দিমু।',
        effects: { happiness: 8 },
        outcomeText: 'কুত্তা খুশি, তোরও মনে হইলো মুরব্বির দোয়া পাইলি।',
        tone: 'good',
      },
      {
        id: 'un_dog_walk',
        text: 'একটু হাইসা সাইড কাইটা হাঁটা দিমু।',
        effects: { happiness: 3, health: 1 },
        outcomeText: 'কুত্তার লগে প্রফেশনাল খাতির, স্ট্যাটাসও বজায় থাকলো।',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_street_festival',
    text: 'রাস্তায় এক্কেরে মেলা বইসা গেছে, ফুচকা আর চটপটির দোকানের তো অভাব নাই!',
    minAge: 0,
    maxAge: 120,
    weight: 55,
    tone: 'good',
    category: 'universal',
    tags: ['community'],
    choices: [
      {
        id: 'un_fest_party',
        text: 'ভিড়ের মইধ্যে ঢুইকা উরাধুরা খামু।',
        effects: { happiness: 10, money: -4, health: -1 },
        outcomeText: 'তিন পদের ভাজাভুজি খাইয়া পেট পুরাই টাইট, কিন্তু জোস একটা দিন!',
        tone: 'good',
      },
      {
        id: 'un_fest_watch',
        text: 'চিপায় বইসা একটা ঝালমুড়ি খামু আর তামাশা দেখুম।',
        effects: { happiness: 5 },
        outcomeText: 'ফাপড়বাজি ছাড়া তামাশা দেখার মজাই আলাদা।',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_lost_and_found',
    text: 'গত মাসে হারাইয়া যাওয়া জিনিসডা হঠাত প্যান্টের চিপা পকেটে পাওয়া গেলো!',
    minAge: 4,
    maxAge: 120,
    weight: 50,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_lost_recover',
        text: 'এক্কেরে চান্দে উইঠা চিল্লাইয়া সেলিব্রেট করুম।',
        effects: { happiness: 6 },
        outcomeText: 'জিনিস ছোট, কিন্তু পাওয়ার ফিলিং পুরাই ওয়ার্ল্ড কাপ জেতার লাহান!',
        tone: 'good',
      },
      {
        id: 'un_lost_donate',
        text: 'যে গরিবের বেশি দরকার তারে দান কইরা দিমু।',
        effects: { karma: 4, happiness: 4 },
        outcomeText: 'তোর হারানো জিনিস দিয়া আরেকজনের লাইফে ঈদ আইসা গেলো।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_rainy_phone',
    text: 'আচমকা আসমান ফাইট্টা বৃষ্টি! রাস্তার সবার হাতে থাকা দামি ফোনগুলা এহন পুরাই কলিজার টুকরা!',
    minAge: 0,
    maxAge: 120,
    weight: 55,
    tone: 'funny',
    category: 'universal',
    tags: ['daily-life'],
    choices: [
      {
        id: 'un_rain_dance',
        text: 'ফোনের মায়া ছাইড়া পুরাই বৃষ্টিতে ভিজুম।',
        effects: { happiness: 9, health: -2 },
        outcomeText: 'জুতা-মোজা সব কাদা, কিন্তু হাসিডা আছিল পুরাই আগুন!',
        tone: 'good',
      },
      {
        id: 'un_rain_shelter',
        text: 'দৌড়াইয়া টংয়ের চালের নিচে গিয়া লুকামু।',
        effects: { happiness: 2, smarts: 2 },
        outcomeText: 'টংয়ের চাল দিয়া পানি পড়ে, তাও ভালো ফোনডা তো বাঁচলো!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'un_letter_unexpected',
    text: 'পোস্টম্যান আইসা একখান চিঠির খাম দিয়া গেলো, এক্কেরে হাতের লেখায়!',
    minAge: 6,
    maxAge: 120,
    weight: 50,
    tone: 'neutral',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_letter_reply',
        text: 'কলম বাইর কইরা সাথে সাথেই উরাধুরা রিপ্লাই দিমু।',
        effects: { happiness: 7, karma: 3 },
        outcomeText: 'তুই আর তোর দোস্ত পুরাই জমিদার আমলের চিঠি-চিঠি খেলতাছোস।',
        tone: 'good',
      },
      {
        id: 'un_letter_keep',
        text: 'যত্ন কইরা ড্রয়ারের মাইঙ্কা চিপায় তুইলা রাখুম।',
        effects: { happiness: 4 },
        outcomeText: 'ড্রয়ারের মান বাইড়া গেলো, চিঠিডাও সেইফ থাকলো।',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_coins_trouser',
    text: 'শীতের জ্যাকেটের পকেটে হাত দিয়া দেখস পুরাই গুপ্তধন! পুরান কিছু ট্যাকা!',
    minAge: 8,
    maxAge: 120,
    weight: 50,
    tone: 'good',
    category: 'universal',
    tags: ['money'],
    choices: [
      {
        id: 'un_coins_keep',
        text: 'যা পাইছি সব দিয়া ফাটাফাটি খাওয়া দিমু।',
        effects: { money: 3, happiness: 5 },
        outcomeText: 'মাগনা পাওয়া ট্যাকা, ফুড়ুৎ কইরা উড়ায়া দিয়া পুরাই চিল!',
        tone: 'funny',
      },
      {
        id: 'un_coins_donate',
        text: 'মসজিদের বক্সে ফালায় দিমু।',
        effects: { karma: 3, happiness: 3 },
        outcomeText: 'ট্যাকা গেলো বক্সে, আর তোর আমলনামায় যোগ হইলো নেকি।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_powercut_candles',
    text: 'ঠিক রাইতের বেলা পুরা এলাকায় কারেন্ট ফুড়ুৎ! ঘরে খালি দুইটা মোমবাতি, মেজাজ পুরাই ফায়ার!',
    minAge: 2,
    maxAge: 120,
    weight: 45,
    tone: 'funny',
    category: 'universal',
    tags: ['daily-life'],
    choices: [
      {
        id: 'un_power_stories',
        text: 'মোমবাতি জ্বালায়া দেয়ালে হাতের ছায়া দিয়া ফাপড়বাজি করুম।',
        effects: { happiness: 7, smarts: 2 },
        outcomeText: 'লোডশেডিংয়ের রাইত পুরাই সিনেমার লাহান হিট হইয়া গেলো!',
        tone: 'good',
      },
      {
        id: 'un_power_early',
        text: 'ঘুমের ভান ধইরা সোজা বিছানায় কাইত!',
        effects: { health: 4, happiness: 2 },
        outcomeText: 'রাইত দুইটায় কারেন্ট আইছে, তুই ততক্ষণে স্বপ্নে ডিগবাজি দিতাছোস।',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_concert_pass',
    text: 'দোস্ত একটা কনসার্টের টিকিট ধরাইয়া দিয়া কয়, "মামা আমি যাইতে পারুম না, তুই যা।"',
    minAge: 10,
    maxAge: 120,
    weight: 40,
    tone: 'good',
    category: 'universal',
    tags: ['culture'],
    choices: [
      {
        id: 'un_concert_go',
        text: 'এক্কেরে সামনে খাড়ায়া বেসুরা গলায় গান গামু।',
        effects: { happiness: 8 },
        outcomeText: 'তোর চিল্লানিতে কনসার্ট হিট, পরের দিন গলা পুরাই জ্যাম!',
        tone: 'good',
      },
      {
        id: 'un_concert_gift',
        text: 'মহল্লার অন্য এক ছ্যাঁকা খাওয়া ভাইরে দিয়া দিমু।',
        effects: { karma: 4, happiness: 3 },
        outcomeText: 'ভাই খুশিতে গদগদ, তোর সম্মান পুরাই আসমানে।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_bus_kindness',
    text: 'লোকাল বাসে উঠছোস, ভাড়া দিতে গিয়া দেখস আরেকজন তোর ভাড়া দিয়া দিছে!',
    minAge: 0,
    maxAge: 120,
    weight: 50,
    tone: 'good',
    category: 'universal',
    tags: ['community'],
    choices: [
      {
        id: 'un_bus_thank',
        text: 'উস্তাদরে এক্কেরে দিল থিকা শুকরিয়া কমু।',
        effects: { happiness: 5, karma: 2 },
        outcomeText: 'অচেনা মাইনষের খাতির, দিল পুরাই ঠান্ডা কইরা দিলো।',
        tone: 'good',
      },
      {
        id: 'un_bus_forward',
        text: 'পরের স্টপেজে উইঠা আরেকজনের ভাড়া আমি দিয়া দিমু।',
        effects: { happiness: 6, karma: 4 },
        outcomeText: 'তুইও পুরাই দানবীর হাতেম তাই সাজলি, চেইন রিঅ্যাকশন!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_meteor_shower',
    text: 'মহল্লায় খবর রটছে, আইজকা রাইতে নাকি আসমান থিকা তারা খইসা পড়বো!',
    minAge: 5,
    maxAge: 120,
    weight: 40,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_meteor_stay',
        text: 'ছাদে কাঁথা বিছাইয়া আসমানের দিকে চাইয়া থাকুম।',
        effects: { happiness: 9, health: -1 },
        outcomeText: 'দুই মিনিটে তিনটা তারা দেখলি, পুরাই পয়সা উসুল!',
        tone: 'good',
      },
      {
        id: 'un_meteor_sleep',
        text: 'নাক ডাইকা ঘুমামু, কাইলকা পেপারে দেখলেই হইবো।',
        effects: { health: 3, smarts: 1 },
        outcomeText: 'পেপারের ছবি দেইখাই খুশি, আর তোর ঘুমও পুরাই ১০০তে ১০০।',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_overheard_praise',
    text: 'আড়ালে খাড়াইয়া শুনলি কেউ একজন তোর নামে পুরাই মধু ঢালতাছে, বদনাম না!',
    minAge: 0,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_praise_absorb',
        text: 'ভাব লমু আমি পুরাই ফেরেশতা, কথাডা বিশ্বাস করুম।',
        effects: { happiness: 7 },
        outcomeText: 'পরের এক সপ্তাহ তোর পা আর মাটিতে পড়বো না!',
        tone: 'good',
      },
      {
        id: 'un_praise_repay',
        text: 'তার লগে দেখা হইলে আমিও তার পাম দিমু।',
        effects: { happiness: 5, karma: 3 },
        outcomeText: 'তেল আর পামের চোটে পুরা এলাকা পিছলা হইয়া গেলো।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_cloud_sky',
    text: 'আসমানের মেঘগুলা আইজকা পুরাই পাগল হইছে, একেকটা একেক ডিজাইনের!',
    minAge: 0,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_cloud_point',
        text: 'রাস্তার মাইনষেরে ডাইকা মেঘের ডিজাইন দেখামু।',
        effects: { happiness: 5 },
        outcomeText: 'তুই দেখস বাঘ, হ্যায় দেখে হাতি! ফাপড়বাজির শেষ নাই।',
        tone: 'funny',
      },
      {
        id: 'un_cloud_walk',
        text: 'আসমানের দিকে তাকায়া তাকায়া হাঁটুম।',
        effects: { happiness: 4, health: 1 },
        outcomeText: 'হাঁটতে গিয়া হোঁচট খাইতে খাইতে বাঁচলি, তাও মেঘ দেখা মিস নাই।',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_stranger_help',
    text: 'রাস্তায় একজন অচেনা মানুষ আচমকা তোর ভারী ব্যাগটা ধইরা দিলো, কোনো ফাপড় ছাড়াই!',
    minAge: 0,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['community'],
    choices: [
      {
        id: 'un_help_thank',
        text: 'এক্কেরে স্যালুট দিয়া থ্যাংকস কমু।',
        effects: { happiness: 5, karma: 1 },
        outcomeText: 'লোকটা একটা মুচকি হাসি দিলো, তোর দিনটা পুরাই জোস হইয়া গেলো।',
        tone: 'good',
      },
      {
        id: 'un_help_note',
        text: 'জিনিসটা মাথায় রাখুম, পরে আমিও কাউরে হেল্প করুম।',
        effects: { happiness: 6, karma: 3 },
        outcomeText: 'মহল্লায় তুইও একজন হিরো হওয়ার লাইনে চইলা গেলি।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_sunrise_kinetic',
    text: 'ভুল কইরা ভোরে ঘুম ভাইঙ্গা গেছে, আর দেখস আসমান পুরাই লাল আগুন! সূর্য উঠতাছে!',
    minAge: 9,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'sunrise_watch',
        text: 'খাড়াইয়া পুরা সূর্য ওঠা দেখুম।',
        effects: { happiness: 6 },
        outcomeText: 'আসমানের কালার দেইখা মনে হইলো ঘুম ভাঙ্গাটা পুরাই উসুল!',
        tone: 'good',
      },
      {
        id: 'sunrise_proceed',
        text: 'সূর্যরে একটা সালাম দিয়া নিজের কামে দৌড় দিমু।',
        effects: { happiness: 2, smarts: 1 },
        outcomeText: 'তুই এক মিনিটের লাইগা দেখলি, কিন্তু ফিলডা সারাদিন থাকলো।',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_icecream_negotiation',
    text: 'সামনে আইসক্রিমের গাড়ি! এহন কোন ফ্লেভার আর কোন কোন নিবি, সেইডা নিয়া পুরাই মাইঙ্কা চিপা!',
    minAge: 3,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'icecream_classic',
        text: 'রেগুলার কোন, রেগুলার ফ্লেভার, নো রিস্ক!',
        effects: { happiness: 6, health: -1 },
        outcomeText: 'এক্কেরে পারফেক্ট আইসক্রিম, পারফেক্ট পাঁচ মিনিট।',
        tone: 'good',
      },
      {
        id: 'icecream_wild',
        text: 'মেন্যুর সবচেয়ে উল্টাপাল্টা ফ্লেভার মিক্স কইরা খামু!',
        effects: { happiness: 8, health: -2 },
        outcomeText: 'খাইতে গিয়া বুঝলি তুই পুরাই জিনিয়াস, নাকি পাগল!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'un_forgotten_umbrella',
    text: 'যেই মুহূর্তে বুঝলি তোর লগে ছাতা নাই, ঠিক সেই মুহূর্তেই আসমান ভাইঙ্গা বৃষ্টি নামলো!',
    minAge: 0,
    maxAge: 120,
    weight: 45,
    tone: 'funny',
    category: 'universal',
    tags: ['daily-life'],
    choices: [
      {
        id: 'umbrella_brave',
        text: 'হিরোর লাহান ভিজতে ভিজতে যামু।',
        effects: { health: -3, happiness: 5 },
        outcomeText: 'পুরাই কাকভেজা হইলি, কিন্তু এটিচিউড আছিল পুরাই বস লেভেলের!',
        tone: 'funny',
      },
      {
        id: 'umbrella_recover',
        text: 'দৌড়াইয়া পিছে গিয়া ছাতা নিয়া আমু।',
        effects: { smarts: 2, happiness: 3, health: 1 },
        outcomeText: 'ছাতা ঠিকই পাইলি, কিন্তু ততক্ষণে তোর ইজ্জত আর শার্ট দুইটাই ভিজা।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_coat_pocket_note',
    text: 'শীতের জ্যাকেট বাইর করছোস, আর পকেট থিকা গত বছরের হাবিজাবি বাইর হইতাছে!',
    minAge: 2,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'pocket_keep',
        text: 'সবগুলা বাইর কইরা টেবিলে সাজাইয়া রাখুম।',
        effects: { happiness: 5 },
        outcomeText: 'পুরান রশিদ, কয়েন... মনে হইতাছে গত শীতের মিউজিয়াম খুলছোস!',
        tone: 'funny',
      },
      {
        id: 'pocket_note_send',
        text: 'জোস একটা জিনিস দোস্তরে মেসেজ কইরা পাঠামু।',
        effects: { happiness: 4, karma: 3 },
        outcomeText: 'দোস্ত তো ছবি দেইখা হাসতে হাসতে বেহুঁশ, তোরও দিল খুশ।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_solar_eclipse_gathering',
    text: 'দিনের বেলা আসমান কালা হইয়া সূর্যগ্রহণ শুরু! মহল্লার পোলাপান সব এক্সরে ফিল্ম নিয়া হাজির।',
    minAge: 5,
    maxAge: 120,
    weight: 60,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'eclipse_view_crescent',
        text: 'ফিল্ম দিয়া আসমানের দিকে চাইয়া থাকুম।',
        effects: { smarts: 6, happiness: 10, fame: 2 },
        outcomeText: 'কাক-পক্ষী সব চুপ, তুই পুরাই সাইন্টিস্টের লাহান ফিল নিলি!',
        tone: 'good',
      },
      {
        id: 'eclipse_share_glasses',
        text: 'নিজের ফিল্মটা পিচ্চি পোলাপানগো দেখতে দিমু।',
        effects: { karma: 10, happiness: 8 },
        outcomeText: 'পোলাপান খুশি, তুইও মুরব্বিগো থিকা পুরাই সাবাশি পাইলি।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_street_vendor_flute',
    text: 'রাস্তায় এক বাঁশিওয়ালা পুরাই কলিজা কাঁপানো সুরে বাঁশি বাজাইয়া হাইটা যাইতাছে।',
    minAge: 3,
    maxAge: 120,
    weight: 65,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'flute_buy_bamboo',
        text: 'ট্যাকা দিয়া একটা বাঁশি কিন্না ওস্তাদের থিকা দুইটা টিপস লমু।',
        effects: { money: -2, happiness: 12, smarts: 4 },
        outcomeText: 'ঘরে বইসা প্যাঁ-পোঁ বাজাইলি, তাও মনটা পুরাই শান্তিতে ভরলো।',
        tone: 'good',
      },
      {
        id: 'flute_listen_appreciate',
        text: 'খাড়াইয়া খাড়াইয়া ফ্রি-তে সুর শুনুম যতক্ষণ না ব্যাটা যায়।',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'রাস্তায় খাড়াইয়া পুরাই ফকিন্নির লাহান শান্তি পাইলি।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_migratory_butterfly_swarm',
    text: 'মহল্লার বাগানে হঠাত কোইত্থিকা লাখ লাখ রঙিন প্রজাপতি আইসা ছাইয়া গেছে!',
    minAge: 2,
    maxAge: 120,
    weight: 65,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'butterfly_stand_still',
        text: 'মূর্তির লাহান খাড়ায়া থাকুম যাতে হাতে আইসা বসে।',
        effects: { happiness: 14, looks: 4, karma: 6 },
        outcomeText: 'হাতে একটা বইসাও গেলো, তুই পুরাই ডিজনির প্রিন্সেস/প্রিন্স ফিল নিলি!',
        tone: 'good',
      },
      {
        id: 'butterfly_snap_photo',
        text: 'মোবাইল বাইর কইরা পুরাই প্রফেশনাল ফটোগ্রাফার সাজমু।',
        effects: { smarts: 4, happiness: 8, fame: 4 },
        outcomeText: 'ছবি ফেস বুকে ছাড়ার পর লাইকের বন্যায় তুই পুরাই ভাইরাল!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_rainbow_after_storm',
    text: 'তুফান থামার পর আসমানে এক্কেরে জোড়া রংধনু উইঠা পুরাই চান্দি ফাটা একটা ভিউ!',
    minAge: 1,
    maxAge: 120,
    weight: 70,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'rainbow_rooftop_marvel',
        text: 'ছাদে দৌড় দিয়া গিয়া রংধনু দেখুম।',
        effects: { happiness: 16, health: 3 },
        outcomeText: 'সাত রঙের বাহার দেইখা তোর চোখ পুরাই টেরচা হইয়া গেলো খুশিতে!',
        tone: 'good',
      },
      {
        id: 'rainbow_call_family',
        text: 'চিল্লায়া বাসার সবারে ডাইকা দেখামু।',
        effects: { happiness: 12, karma: 6 },
        outcomeText: 'পুরা ফ্যামিলি একলগে খাড়ায়া দেখলো, এক্কেরে হ্যাপি ফ্যামিলি প্যাকেজ!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_found_vintage_coin',
    text: 'পুরান আলমারির চিপা থিকা সাফা করতে গিয়া এক্কেরে বাপ-দাদার আমলের পুরান কয়েন পাইলি!',
    minAge: 6,
    maxAge: 120,
    weight: 60,
    tone: 'good',
    category: 'universal',
    tags: ['wealth', 'smarts'],
    choices: [
      {
        id: 'coin_research_archives',
        text: 'ঘইষা-মাজা কইরা গুগলে সার্চ দিমু এইডার দাম কত!',
        effects: { smarts: 8, happiness: 8, money: 4 },
        outcomeText: 'দেখলি এইডা পুরাই এন্টিক পিস, তুই মনে মনে কোটিপতি!',
        tone: 'good',
      },
      {
        id: 'coin_lucky_pocket',
        text: 'পকেটে রাইখা দিমু লাকি কয়েন হিসাবে।',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'পকেটে হাত দিলেই একটা জোস ভাব আয়, তুই পুরাই নবাবের হালাতো ভাই।',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_neighborhood_kite_festival',
    text: 'সাকরাইনের দিন আসমানে পুরাই ঘুড়ির মেলা, চারিদিকে খালি হাঁকডাক: "ঐ ভোকাট্টা!"',
    minAge: 6,
    maxAge: 120,
    weight: 70,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'kite_pilot_duels',
        text: 'নাটাই হাতে নিয়া ছাদের কোনায় খাড়ায়া ঘুড়ি কাটাকাটিতে নামুম!',
        effects: { happiness: 16, fame: 6, smarts: 4 },
        outcomeText: 'তিনজনের ঘুড়ি কাইটা তুই পুরাই ছাদের হিরো, চিল্লায়া গলা ফাটাইলি!',
        tone: 'good',
      },
      {
        id: 'kite_spiced_chana',
        text: 'মুরব্বিগো লগে বইসা কাচ্চি আর বোরহানি খামু।',
        effects: { happiness: 10, health: 2 },
        outcomeText: 'ঘুড়ির থিকা তোর নজর কাচ্চির হাড্ডিতে বেশি, পেট পুরাই টাইট!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_shooting_star_wish',
    text: 'রাইতে আসমানের দিকে চাইয়া আছোস, হঠাত দেখস একটা তারা খইসা পড়লো এক্কেরে রকেটের লাহান!',
    minAge: 4,
    maxAge: 120,
    weight: 65,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'star_whisper_wish',
        text: 'চোখ বন্ধ কইরা ফাটাফাটি একটা উইশ কইরা দিমু।',
        effects: { happiness: 14, karma: 8 },
        outcomeText: 'দিল পুরাই ঠান্ডা, মনে হইলো কালকেই কোটিপতি হইয়া যাবি!',
        tone: 'good',
      },
      {
        id: 'star_astronomy_chart',
        text: 'সাইন্টিস্টের লাহান হিসাব করুম এইডা কোন গ্রহের টুকরা!',
        effects: { smarts: 6, happiness: 8 },
        outcomeText: 'মগজের ঘিলু একটু বাড়লো, কিন্তু রোমান্স পুরাই ফুড়ুৎ!',
        tone: 'good',
      },
    ],
  },
];