import type { LifeEventDef } from '@/lib/engine/types';

/**
 * Universal pool (all ages). Several events span 0–120 so that every age,
 * whatever its flags, always has eligible events — this is the guarantee the
 * Gate 5 eligibility test asserts. Tone-tagged for the stinger system.
 */
export const UNIVERSAL_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'un_surprise_gift',
    text: 'A small, unexpected gift arrives — a bookmark, a snack, a good pen. Someone thought of you.',
    minAge: 0,
    maxAge: 120,
    weight: 60,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_gift_savor',
        text: 'Savour it and use it today',
        effects: { happiness: 6 },
        outcomeText: 'The pen is in your pocket by noon. The bookmark lives in the current chapter.',
        tone: 'good',
      },
      {
        id: 'un_gift_pass',
        text: 'Save it for a rainy day',
        effects: { happiness: 3, smarts: 1 },
        outcomeText: 'The rainy day arrives and the gift arrives with it, exactly as planned.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_dog_moment',
    text: 'A very confident dog crosses your path and demands, with eyes, a moment of your day.',
    minAge: 0,
    maxAge: 120,
    weight: 60,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_dog_pet',
        text: 'Stop to give it the full royal attention',
        effects: { happiness: 8 },
        outcomeText: 'The dog is satisfied and leaves. You feel broadly approved of.',
        tone: 'good',
      },
      {
        id: 'un_dog_walk',
        text: 'Greet it politely and keep walking',
        effects: { happiness: 3, health: 1 },
        outcomeText: 'A nod between equals. Professional, dignified, still nice.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_street_festival',
    text: 'The street has closed itself off for a festival, with bunting and a suspicious number of food carts.',
    minAge: 0,
    maxAge: 120,
    weight: 55,
    tone: 'good',
    category: 'universal',
    tags: ['community'],
    choices: [
      {
        id: 'un_fest_party',
        text: 'Join the crowd and try everything',
        effects: { happiness: 10, money: -4, health: -1 },
        outcomeText: 'Three kinds of fried batter and one spare-dance later, a great Tuesday.',
        tone: 'good',
      },
      {
        id: 'un_fest_watch',
        text: 'Watch from a bench with a tiny treat',
        effects: { happiness: 5 },
        outcomeText: 'Sometimes the best view of the parade is from the quiet side.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_lost_and_found',
    text: 'The thing you lost last month turns up in the most ordinary pocket.',
    minAge: 4,
    maxAge: 120,
    weight: 50,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_lost_recover',
        text: 'Reclaim it with real ceremony',
        effects: { happiness: 6 },
        outcomeText: 'The thing itself is small. The reunion, however, is epic.',
        tone: 'good',
      },
      {
        id: 'un_lost_donate',
        text: 'Pass it along to someone who needs it more',
        effects: { karma: 4, happiness: 4 },
        outcomeText: 'The lost thing starts a second life elsewhere.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_rainy_phone',
    text: 'Rain arrives sideways and every phone in the street is suddenly a precious artifact.',
    minAge: 0,
    maxAge: 120,
    weight: 55,
    tone: 'funny',
    category: 'universal',
    tags: ['daily-life'],
    choices: [
      {
        id: 'un_rain_dance',
        text: 'Give up and enjoy the downpour',
        effects: { happiness: 9, health: -2 },
        outcomeText: 'Socks are ruined. The laugh is unforgettable.',
        tone: 'good',
      },
      {
        id: 'un_rain_shelter',
        text: 'Huddle under the awning and wait it out',
        effects: { happiness: 2, smarts: 2 },
        outcomeText: 'You learn which awning leaks. Valuable municipal knowledge.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'un_letter_unexpected',
    text: 'An actual letter arrives, by actual post, in actual handwriting.',
    minAge: 6,
    maxAge: 120,
    weight: 50,
    tone: 'neutral',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_letter_reply',
        text: 'Reply by hand the same week',
        effects: { happiness: 7, karma: 3 },
        outcomeText: 'The reply is slow and delicious. Two pen-pals, officially.',
        tone: 'good',
      },
      {
        id: 'un_letter_keep',
        text: 'Keep it in the drawer of good things',
        effects: { happiness: 4 },
        outcomeText: 'Good drawer energy. The letter lives a long, warm life.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_coins_trouser',
    text: 'A winter coat presents a forgotten fund in its deepest pocket.',
    minAge: 8,
    maxAge: 120,
    weight: 50,
    tone: 'good',
    category: 'universal',
    tags: ['money'],
    choices: [
      {
        id: 'un_coins_keep',
        text: 'Treat yourself to something silly',
        effects: { money: 3, happiness: 5 },
        outcomeText: 'The most profitable pocket in your life, spent in seconds.',
        tone: 'funny',
      },
      {
        id: 'un_coins_donate',
        text: 'Drop it in the nearest collection tin',
        effects: { karma: 3, happiness: 3 },
        outcomeText: 'The tin thanks you silently. The coins do their small good.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_powercut_candles',
    text: 'The whole block goes dark at exactly the wrong hour, with candles available and morale uncertain.',
    minAge: 2,
    maxAge: 120,
    weight: 45,
    tone: 'funny',
    category: 'universal',
    tags: ['daily-life'],
    choices: [
      {
        id: 'un_power_stories',
        text: 'Start a flashlight-puppet show',
        effects: { happiness: 7, smarts: 2 },
        outcomeText: 'The outage becomes a museum-quality memory with a shaky hand-shadow dinosaur.',
        tone: 'good',
      },
      {
        id: 'un_power_early',
        text: 'Declare it bedtime and claim the extra rest',
        effects: { health: 4, happiness: 2 },
        outcomeText: 'The grid returns at 2am. You have already met the midnight.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_concert_pass',
    text: 'A spare ticket to a decent show lands in your hands from a friend with a plan change.',
    minAge: 10,
    maxAge: 120,
    weight: 40,
    tone: 'good',
    category: 'universal',
    tags: ['culture'],
    choices: [
      {
        id: 'un_concert_go',
        text: 'Go and sing along badly',
        effects: { happiness: 8 },
        outcomeText: 'The bad singing is the best part of the recording.',
        tone: 'good',
      },
      {
        id: 'un_concert_gift',
        text: 'Regift the ticket to someone who\'ll love it more',
        effects: { karma: 4, happiness: 3 },
        outcomeText: 'Their review comes back with exclamation marks. Worth it.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_bus_kindness',
    text: 'On the bus, someone covers your fare before you can fumble your change.',
    minAge: 0,
    maxAge: 120,
    weight: 50,
    tone: 'good',
    category: 'universal',
    tags: ['community'],
    choices: [
      {
        id: 'un_bus_thank',
        text: 'Thank them properly and mean it',
        effects: { happiness: 5, karma: 2 },
        outcomeText: 'A stranger\'s act, pocketed and remembered.',
        tone: 'good',
      },
      {
        id: 'un_bus_forward',
        text: 'Pay it forward at the next stop',
        effects: { happiness: 6, karma: 4 },
        outcomeText: 'The chain continues a few stops further, quietly on time.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_meteor_shower',
    text: 'Word goes around that tonight the sky will do something worth standing outside for.',
    minAge: 5,
    maxAge: 120,
    weight: 40,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_meteor_stay',
        text: 'Stay up and watch with a blanket',
        effects: { happiness: 9, health: -1 },
        outcomeText: 'Three streaks in two minutes, then a long quiet wow.',
        tone: 'good',
      },
      {
        id: 'un_meteor_sleep',
        text: 'Sleep through and read about it tomorrow',
        effects: { health: 3, smarts: 1 },
        outcomeText: 'The photo essay is stunning. Your sleep schedule remains intact.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_overheard_praise',
    text: 'You overhear someone saying something generously kind about you, meaning it.',
    minAge: 0,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_praise_absorb',
        text: 'Let yourself believe it',
        effects: { happiness: 7 },
        outcomeText: 'The sentence stays with you for days.',
        tone: 'good',
      },
      {
        id: 'un_praise_repay',
        text: 'Pay the kindness back with one of your own',
        effects: { happiness: 5, karma: 3 },
        outcomeText: 'The good words multiply by being passed on.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_cloud_sky',
    text: 'The clouds stage an amateur but very committed pantomime above the street.',
    minAge: 0,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'un_cloud_point',
        text: 'Point out the best shapes to whoever is nearby',
        effects: { happiness: 5 },
        outcomeText: 'You see a dragon; they see a teapot. Both are correct.',
        tone: 'funny',
      },
      {
        id: 'un_cloud_walk',
        text: 'Walk with one eye on the sky',
        effects: { happiness: 4, health: 1 },
        outcomeText: 'The clouds make the shortest walk ten minutes longer. Fine.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_stranger_help',
    text: 'A stranger without any cue just... helps. Reaches the thing, holds the door, passes the bag.',
    minAge: 0,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['community'],
    choices: [
      {
        id: 'un_help_thank',
        text: 'Thank them with your full attention',
        effects: { happiness: 5, karma: 1 },
        outcomeText: 'They nod, and somewhere the day gets 1% shinier.',
        tone: 'good',
      },
      {
        id: 'un_help_note',
        text: 'Notice it, and do the same for someone later',
        effects: { happiness: 6, karma: 3 },
        outcomeText: 'The helping chain now has your link welded in.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_sunrise_kinetic',
    text: 'You are up early enough to catch the sunrise, and the sky is officiating with full ceremony.',
    minAge: 9,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'sunrise_watch',
        text: 'Stop and watch it all the way up',
        effects: { happiness: 6 },
        outcomeText: 'The ceiling of the world goes slowly pink. Worth the early alarm.',
        tone: 'good',
      },
      {
        id: 'sunrise_proceed',
        text: 'Nod at it and carry on with the day',
        effects: { happiness: 2, smarts: 1 },
        outcomeText: 'You caught a minute of it. Later, you will remember that minute.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'un_icecream_negotiation',
    text: 'An ice-cream stand has a decision of enormous gravity: swirl or cone, and with what.',
    minAge: 3,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'icecream_classic',
        text: 'Classic cone, classic flavour, zero regrets',
        effects: { happiness: 6, health: -1 },
        outcomeText: 'A perfect cone. A perfect five minutes. Nothing to apologise for.',
        tone: 'good',
      },
      {
        id: 'icecream_wild',
        text: 'Order the wildest combo on the board',
        effects: { happiness: 8, health: -2 },
        outcomeText: 'It is either genius or chaos. You decide genius. Your wallet agrees.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'un_forgotten_umbrella',
    text: 'The rain starts at the precise moment you discover you do not have your umbrella.',
    minAge: 0,
    maxAge: 120,
    weight: 45,
    tone: 'funny',
    category: 'universal',
    tags: ['daily-life'],
    choices: [
      {
        id: 'umbrella_brave',
        text: 'Walk through it and arrive dramatically damp',
        effects: { health: -3, happiness: 5 },
        outcomeText: 'Damp, laughing, and five minutes late. The rain was in on the joke.',
        tone: 'funny',
      },
      {
        id: 'umbrella_recover',
        text: 'Retrace your steps and find it',
        effects: { smarts: 2, happiness: 3, health: 1 },
        outcomeText: 'The umbrella waits where you left it, precisely, like a loyal dog.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_coat_pocket_note',
    text: 'A winter coat returns with a season of pocket-surprises you had forgotten.',
    minAge: 2,
    maxAge: 120,
    weight: 45,
    tone: 'good',
    category: 'universal',
    tags: ['small-win'],
    choices: [
      {
        id: 'pocket_keep',
        text: 'Line up the treasures on the table',
        effects: { happiness: 5 },
        outcomeText: 'A receipt, a sticker, a coin. A tiny museum of last winter.',
        tone: 'funny',
      },
      {
        id: 'pocket_note_send',
        text: 'Send the best find to a friend',
        effects: { happiness: 4, karma: 3 },
        outcomeText: 'The friend gets the sticker. The story gets retold all week.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_solar_eclipse_gathering',
    text: 'The afternoon sky dims into twilight as a solar eclipse begins. Neighbors gather with {cardboard pinhole projectors|dark polarized viewing film}.',
    minAge: 5,
    maxAge: 120,
    weight: 60,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'eclipse_view_crescent',
        text: 'Watch the silver crescent silhouette of the sun through safety lenses',
        effects: { smarts: 6, happiness: 10, fame: 2 },
        outcomeText: 'An eerie stillness fell over the world as birds chirped in confusion. A cosmic spectacle!',
        tone: 'good',
      },
      {
        id: 'eclipse_share_glasses',
        text: 'Pass your viewing filter around to excited children and neighbors',
        effects: { karma: 10, happiness: 8 },
        outcomeText: 'Gasps of joy and wonder shared together across generations.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_street_vendor_flute',
    text: 'A roaming bamboo flute maker walks past playing {a hauntingly beautiful folk melody|a playful spring raga}.',
    minAge: 3,
    maxAge: 120,
    weight: 65,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'flute_buy_bamboo',
        text: 'Buy a handcrafted bamboo flute and ask the artisan for a quick fingering lesson',
        effects: { money: -2, happiness: 12, smarts: 4 },
        outcomeText: 'The simple instrument filled your home with sweet, earthy melodies.',
        tone: 'good',
      },
      {
        id: 'flute_listen_appreciate',
        text: 'Pause and listen until the soothing notes drift away into the distance',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'A moment of serene musical poetry in the middle of a busy day.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_migratory_butterfly_swarm',
    text: 'A migratory swarm of {hundreds of yellow and lime butterflies|velvet monarch butterflies} descends upon blossoming neighborhood bushes.',
    minAge: 2,
    maxAge: 120,
    weight: 65,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'butterfly_stand_still',
        text: 'Stand motionless with outstretched finger until a butterfly lands gently on your hand',
        effects: { happiness: 14, looks: 4, karma: 6 },
        outcomeText: 'Its delicate wings opened and closed softly. A magical moment of pure harmony.',
        tone: 'good',
      },
      {
        id: 'butterfly_snap_photo',
        text: 'Capture a stunning macro photograph of the iridescent wing patterns',
        effects: { smarts: 4, happiness: 8, fame: 4 },
        outcomeText: 'The photo won hundreds of appreciative likes from fellow nature lovers.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_rainbow_after_storm',
    text: 'As the thunderstorm passes, the setting sun breaks through {illuminating a vivid double rainbow across the sky|casting a golden honey glow over rain-washed roofs}.',
    minAge: 1,
    maxAge: 120,
    weight: 70,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'rainbow_rooftop_marvel',
        text: 'Step out onto the terrace to soak in the majestic dual arches of color',
        effects: { happiness: 16, health: 3 },
        outcomeText: 'Vibrant indigo, emerald, and gold framing the storm clouds. Breath-taking awe.',
        tone: 'good',
      },
      {
        id: 'rainbow_call_family',
        text: 'Shout for everyone in the house to look out the window at the sky',
        effects: { happiness: 12, karma: 6 },
        outcomeText: 'The whole family stood side by side in silent, smiling appreciation.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_found_vintage_coin',
    text: 'While cleaning behind an antique wooden wardrobe, you unearth {a rare silver scallop-edged coin|a commemorative historical medal from a bygone era}.',
    minAge: 6,
    maxAge: 120,
    weight: 60,
    tone: 'good',
    category: 'universal',
    tags: ['wealth', 'smarts'],
    choices: [
      {
        id: 'coin_research_archives',
        text: 'Polish the coin gently and research its mint date and mintmaster in library records',
        effects: { smarts: 8, happiness: 8, money: 4 },
        outcomeText: 'Discovered it is a prized collector edition with fascinating historical heritage.',
        tone: 'good',
      },
      {
        id: 'coin_lucky_pocket',
        text: 'Keep it as your personal lucky pocket charm',
        effects: { happiness: 8, karma: 4 },
        outcomeText: 'Its cool metallic weight in your pocket brings a reassuring spark of good fortune.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_neighborhood_kite_festival',
    text: 'During the winter kite festival, the azure sky fills with {hundreds of colorful diamond fighting kites|a giant dragon kite with streaming tails}.',
    minAge: 6,
    maxAge: 120,
    weight: 70,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'kite_pilot_duels',
        text: 'Launch your paper kite high into the thermals and engage in friendly mid-air duels',
        effects: { happiness: 16, fame: 6, smarts: 4 },
        outcomeText: 'Triumphant cuts and joyful shouts of victory echoing across the rooftops!',
        tone: 'good',
      },
      {
        id: 'kite_spiced_chana',
        text: 'Munch on hot roasted chickpeas while cheering rooftop kite flyers below',
        effects: { happiness: 10, health: 2 },
        outcomeText: 'Breezy sunshine, laughter, and colorful paper dancing on the wind.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'un_shooting_star_wish',
    text: 'Watching the midnight sky during a clear meteor shower, you catch sight of {a brilliant shooting star blazing across Orion|a green fire meteor leaving a glowing trail}.',
    minAge: 4,
    maxAge: 120,
    weight: 65,
    tone: 'good',
    category: 'universal',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'star_whisper_wish',
        text: 'Close eyes tight and whisper a deep, heartfelt wish for health and happiness',
        effects: { happiness: 14, karma: 8 },
        outcomeText: 'A serene sense of peace settled deep into your soul. Dreams feel within reach.',
        tone: 'good',
      },
      {
        id: 'star_astronomy_chart',
        text: 'Trace the radiant constellation path on your star chart with fascinated curiosity',
        effects: { smarts: 6, happiness: 8 },
        outcomeText: 'Marveling at cosmic rock dust incinerating harmlessly thousands of miles above.',
        tone: 'good',
      },
    ],
  },
];