import type { LifeEventDef } from '@/lib/engine/types';

export const YOUNG_ADULT_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'ya_school_decisions',
    text: 'স্কুল-কলেজ তো শেষ! এহন বাপে বাঁশ নিয়া খাড়ায়া আছে, "বড় হইছোস, হালায় এহন করবি কী?"',
    minAge: 18,
    maxAge: 20,
    weight: 100,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education', 'life-choice'],
    choices: [
      {
        id: 'ya_uni_enrol',
        text: 'আতেল সাইজা ভার্সিটিতে ভর্তির ফাপড় নে!',
        effects: { addFlag: 'education_university' },
        outcomeText: 'চান্স পাইছোস ঠিকই, কিন্তু ভার্সিটির ক্যান্টিনের ডাইল খায়া তোর এমুন ডাইরিয়া হইলো, তুই পুরাই হাগু-হিরো!',
        tone: 'funny',
      },
      {
        id: 'ya_trade_school',
        text: 'পড়াশোনার গুষ্টি কিলাইয়া কারিগরি কাজ শিখতে যা!',
        effects: { addFlag: 'education_vocational' },
        outcomeText: 'কারেন্টের তার জোড়া লাগাইতে গিয়া এমুন ছ্যাঁকা খাইলি, তোর ঠোঁট ফুইলা বান্দরের পাছা হইয়া গেলো!',
        tone: 'bad',
      },
      {
        id: 'ya_work_now',
        text: 'সব ছাইড়া ডাইরেক্ট কাজে ঢুইকা ট্যাকা কামা!',
        effects: { addFlag: 'job_service' },
        outcomeText: 'রেস্টুরেন্টে ওয়েটারের চাকরি পাইছোস! কাস্টমার তোর মুখে এঁঠো পানি ছিটাইয়া দিলো, তুই পুরাই চাকর হালায়!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_uni_freshman',
    text: 'ভার্সিটির পয়লা সপ্তাহ! পোলাপাইন সব ভাব নিতাছে, আর তুই হালায় কনফিউজড হইয়া বাথরুম খুঁজতাছোস!',
    minAge: 18,
    maxAge: 24,
    weight: 90,
    tone: 'funny',
    category: 'young-adult',
    tags: ['education'],
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_fresh_pick_stem',
        text: 'বুক ফুলাইয়া ইঞ্জিনিয়ারিং বা সায়েন্স সাবজেক্ট ল!',
        effects: { smarts: 6, addFlag: 'major_stem' },
        outcomeText: 'প্রোগ্রামিং করতে গিয়া তোর চান্দির চুল সব পইড়া টাকলু হইয়া গেলি! মাইয়ারা তোরে দেইখা হাসে, তুই আজীবন সিঙ্গেল!',
        tone: 'bad',
      },
      {
        id: 'ya_fresh_pick_business',
        text: 'কোট-টাই পইড়া বিজনেসের সাবজেক্ট নিয়া ফাপড় নে!',
        effects: { smarts: 4, money: 5, addFlag: 'major_business' },
        outcomeText: 'প্রেজেন্টেশন দিতে গিয়া প্যান্টের চেইন খোলা আছিলো! পুরা ক্লাস তোর লাল আন্ডারওয়ার দেইখা হাসতে হাসতে কাইত!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_uni_allnighter',
    text: 'কালকা ৩টা অ্যাসাইনমেন্ট আর এক্সাম! আর তুই হালায় রাইত ১২টা পর্যন্ত ফেসবুকে মাইয়াগো ছবিতে কমেন্ট করছোস!',
    minAge: 18,
    maxAge: 25,
    weight: 70,
    tone: 'bad',
    category: 'young-adult',
    tags: ['education', 'health'],
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_night_cram',
        text: 'যা থাকে কপালে, ঘুমাইয়া সকালে যা পারি লিখুম!',
        effects: { smarts: 2, health: 3, happiness: 2 },
        outcomeText: 'ঘুমাইলি ঠিকই, কিন্তু পরীক্ষার হলে গিয়া দেখস প্রশ্ন সব মাথার উপ্রে দিয়া যায়! তুই পুরাই আন্ডা পাইলি!',
        tone: 'bad',
      },
      {
        id: 'ya_night_coffee',
        text: 'এক মগ ব্ল্যাক কফি মাইরা সারারাত জাগার ট্রাই কর!',
        effects: { smarts: 8, health: -6, happiness: -3 },
        outcomeText: 'কফি খায়া তোর এমুন গ্যাস্ট্রিকের পেইন উঠলো, পরীক্ষার হলে তুই এমুন এক পাদ দিলি, স্যার তোরে ঘাড়ধাক্কা দিয়া বাইর কইরা দিলো!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_grad_decision',
    text: 'ভার্সিটি তো শেষ করলি! এহন সার্টিফিকেট দিয়া কি মুড়ি খাবি নাকি বিয়া করবি?',
    minAge: 21,
    maxAge: 25,
    weight: 80,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education', 'milestone'],
    moment: 'diploma',
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_grad_work',
        text: 'চাকরি খোঁজার লাইগা জুতার তলা ক্ষয়া ফ্যাল!',
        effects: { happiness: 6, addFlag: 'education_graduate', removeFlag: 'gpa_low' },
        outcomeText: 'ইন্টারভিউ দিতে গিয়া বসের সামনে ডরে মুইতা দিলি! চাকরি তো পাইলিই না, উল্টা তুই এহন "মুতা-গ্রাজুয়েট"!',
        tone: 'bad',
      },
      {
        id: 'ya_grad_gap',
        text: 'চিল মারার লাইগা এক বছর গ্যাপ নিয়া বাপের ট্যাকা উড়া!',
        effects: { happiness: 10, money: -10, addFlag: 'education_graduate' },
        outcomeText: 'চিল মারতে গিয়া আব্বা তোরে ঘর থিকা লাথি দিয়া বাইর কইরা দিছে! তুই এহন রাস্তায় বইসা ভিক্কা করতাছোস!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_first_jobs',
    text: 'চাকরির বাজারে তোর ভ্যালু ২ টাকার কয়েনের চাইতেও কম! এহন কী করবি?',
    minAge: 18,
    maxAge: 24,
    weight: 85,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'ya_job_retail',
        text: 'লজ্জা ছাইড়া শপিং মলে সেলসম্যানের চাকরিতে ঢোক!',
        effects: { money: 6, happiness: 2, addFlag: 'job_retail' },
        outcomeText: 'কাস্টমার মাইয়ারা তোরে শাড়ি বাইর করতে দিয়া পরে কিছু না কিন্না চইলা যায়! তুই হালায় পুরাই ফইন্নি চাকর!',
        tone: 'bad',
      },
      {
        id: 'ya_job_office_temp',
        text: 'অফিসে কেরানি সাইজা ফাইল টানার চাকরি ল!',
        effects: { money: 7, smarts: 4, happiness: -2, addFlag: 'job_office' },
        outcomeText: 'বসের চা আনতে গিয়া বসের গায়ের উপ্রে চা ফালায়া দিলি! বস তোরে দিয়া বাথরুম পরিষ্কার করাইলো এক মাস!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_roommates',
    text: 'ব্যাচেলর মেসে উঠছোস। বাথরুম একটাই, আর মেসের পোলাপাইনগুলা পুরাই ড্রেনের ইঁদুর!',
    minAge: 18,
    maxAge: 24,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['daily-life'],
    choices: [
      {
        id: 'ya_room_chart',
        text: 'রুটিন বানাইয়া পোলাপাইনরে বাথরুম আর ডিউটি বুঝাইয়া দে!',
        effects: { smarts: 3, happiness: 5 },
        outcomeText: 'তোর রুটিন দিয়া পোলাপাইন পাছা মুইছা ফালায়া দিছে! তুই একলা পুরা মেসের টয়লেট ধুইলি হালায়!',
        tone: 'bad',
      },
      {
        id: 'ya_room_petty',
        text: 'নিজের খাবার আর সাবান লুকাইয়া চিপায় রাইখা দে!',
        outcomeText: 'রাইতে পোলাপাইন তোর সাবান দিয়া প্যান্ট ধুইয়া রাখছে আর তোর তরকারিতে তেলাপোকা ফালাইয়া দিছে! তুই পুরাই বাঁশ খাইলি!',
        tone: 'funny',
        effects: { smarts: 3, happiness: 5},
      },
    ],
  },
  {
    id: 'ya_gym_first',
    text: 'বডিবিল্ডার হওয়ার শখে জিমে ভর্তি হইছোস। তোর ভুঁড়ি দেইখা জিমের মাইয়ারা হাসতাছে!',
    minAge: 18,
    maxAge: 26,
    weight: 65,
    tone: 'funny',
    category: 'young-adult',
    tags: ['activity', 'health'],
    choices: [
      {
        id: 'ya_gym_go',
        text: 'ভাব নিয়া ৫০ কেজির ডাম্বেল তুইলা ফাপড় নে!',
        effects: { health: -10, looks: -5, happiness: -15 },
        outcomeText: 'ডাম্বেল তুলতে গিয়া তোর প্যান্ট ফাইট্টা হাগু বাইর হইয়া গেলো! পুরা জিমের মানুষ গন্ধ শুইকা বেহুঁশ, তুই ডাইরেক্ট ভাইরাল!',
        tone: 'bad',
      },
      {
        id: 'ya_gym_member',
        text: 'ট্যাকা দিয়া ভর্তি হইয়া জিমের বদলে কাচ্চি খাইতে যা!',
        effects: { money: -8, health: -15, happiness: -2 },
        outcomeText: 'ভুঁড়ি ফুইলা এমুন হইছে যে তুই নিজের নুনু নিজেই দেখতে পারস না! বাথরুমে গিয়া মুততে গেলে এহন আয়না লাগে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_crypto_fever',
    text: 'দোস্ত ফাপড় দিলো: "DogeElonDhakaiya কয়েন কিন, কাইলকাই কোটিপতি!"',
    minAge: 18,
    maxAge: 30,
    weight: 45,
    tone: 'funny',
    category: 'young-adult',
    tags: ['finance', 'risk'],
    choices: [
      {
        id: 'ya_crypto_risky',
        text: 'কিডনি বেইচা সব ট্যাকা ক্রিপ্টোতে ঢাইলা দে!',
        effects: { money: -50, happiness: -40, addFlag: 'has_investment' },
        outcomeText: 'কয়েনের দাম জিরো! স্ক্যাম খাইয়া তুই এহন রাস্তায় বইসা ভিক্কা করতাছোস আর দোস্ত আমেরিকায় চিল করতাছে!',
        tone: 'bad',
      },
      {
        id: 'ya_crypto_pass',
        text: 'ফাপড়ে না পইড়া নিজের জমানো ট্যাকা পকেটে রাখ!',
        effects: { money: 10, smarts: 15 },
        outcomeText: 'কয়েন স্ক্যাম হইছে! তুই বাঁচলি, কিন্তু দোস্ত তোর কাছে ধার চাইতে আইসা এমুন কান্দন কান্দলো, তুই তার পাছায় লাথি দিলি!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_dating_first',
    text: 'টিংটিং! ডেটিং অ্যাপে একখান মাইয়া তোরে রাইট সোয়াইপ মারছে! তোর লালা বাইর হইয়া গেছে!',
    minAge: 18,
    maxAge: 26,
    weight: 80,
    tone: 'funny',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'ya_date_go',
        text: 'সেন্ট মাইখা ডাইরেক্ট ডেটে গিয়া কফি খাওয়া!',
        effects: { happiness: -20, money: -30, looks: -10 },
        outcomeText: 'গিয়া দেখস মাইয়া না, এইডা একটা হিজড়া! তোরে ধইরা এমুন ড্যান্স দেওয়াইলো, তোর প্যান্টের সব ট্যাকা নিয়া ফুড়ুৎ!',
        tone: 'bad',
      },
      {
        id: 'ya_date_no',
        text: 'স্মার্ট সাইজা মাইয়ারে ইগনোর কইরা সিন খাইয়া রাইখা দে!',
        effects: { happiness: -5, smarts: 10 },
        outcomeText: 'মাইয়া তোরে গালাগালি দিয়া ব্লক মারছে! তুই হালায় আজীবন নিজের হাত দিয়াই কাজ চালাবি, সিঙ্গেল মইরা যাবি!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_flat_fire_drill',
    text: 'রাইত ২টায় ফ্লাটে ফায়ার এলার্ম বাজতাছে! ডরে তোর প্যান্টে আধা কেজি মুত চইলা আইছে!',
    minAge: 18,
    maxAge: 30,
    weight: 40,
    tone: 'funny',
    category: 'young-adult',
    tags: ['daily-life'],
    choices: [
      {
        id: 'ya_fire_socks',
        text: 'কিছু না বুইঝা হাফ প্যান্ট পইড়াই রাস্তায় দৌড় দে!',
        effects: { smarts: -5, happiness: -15, looks: -25 },
        outcomeText: 'রাস্তায় গিয়া দেখস এইডা ফলস এলার্ম! কিন্তু তোর প্যান্টের পিছনে মুতের বিশাল দাগ দেইখা পুরা ফ্ল্যাটের মানুষ হাসতাছে!',
        tone: 'bad',
      },
      {
        id: 'ya_fire_phone',
        text: 'আগে দামি আইফোনটা পকেটে ঢুকা, পরে জান বাঁচা!',
        effects: { happiness: 10, health: -15 },
        outcomeText: 'দৌড়াইতে গিয়া সিঁড়িতে হোঁচট খাইয়া তুই ডাইরেক্ট নিচতলায়! মোবাইল ঠিক আছে, কিন্তু তোর নাক ভাইঙ্গা চ্যাপ্টা!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_kitchen_lessons',
    text: 'বাপের বাড়ি ছাইড়া মেসে উঠছোস। এহন নিজের রান্ধন নিজে করতে গিয়া তুই হালায় কান্দতাছোস!',
    minAge: 18,
    maxAge: 28,
    weight: 60,
    tone: 'funny',
    category: 'young-adult',
    tags: ['health', 'daily-life'],
    choices: [
      {
        id: 'kitchen_learn',
        text: 'ইউটিউব দেইখা ডাল আর ডিম ভাজার ট্রাই কর!',
        effects: { health: -10, money: 3, smarts: -5 },
        outcomeText: 'ডিম ভাজতে গিয়া গরম তেল তোর মুখে ছিইটা তুই পুরাই পোড়া বেগুন! ডাইল এমুন পুড়ছে, গন্ধে পুরা মেস তোরে বাইর কইরা দিছে!',
        tone: 'bad',
      },
      {
        id: 'kitchen_takeout',
        text: 'রান্ধনের গুষ্টি কিলাইয়া ফুডপান্ডায় সস্তা বিরিয়ানি অর্ডার দে!',
        effects: { happiness: -15, money: -20, health: -25 },
        outcomeText: 'সস্তা বিরিয়ানি খায়া তোর এমুন ডাইরিয়া হইলো, বাথরুমে বইসা তুই সারারাত কোঁকাইলি! গু-এর গন্ধে তুই নিজেই বেহুঁশ!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_speed_dating',
    text: 'ধানমন্ডির এক ক্যাফেতে স্পিড ডেটিংয়ে গেছস। সামনে এক কড়া মাইয়া বসা!',
    minAge: 19,
    maxAge: 28,
    weight: 75,
    tone: 'funny',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'speed_witty_banter',
        text: 'শাহরুখ খান সাইজা রোমান্টিক ডায়লগ মার!',
        effects: { looks: -15, happiness: -25, fame: -10 },
        outcomeText: 'ডায়লগ মারতে গিয়া তোর মুখ দিয়া এমুন থুতু ছিইটা মাইয়ার মুখে পড়লো, মাইয়া তোরে স্যান্ডেল দিয়া পিটাইয়া বাইর কইরা দিলো!',
        tone: 'bad',
      },
      {
        id: 'speed_deep_question',
        text: 'আতেল সাইজা তারে জীবনের ফিলোসফি নিয়া জ্ঞান দে!',
        effects: { smarts: -10, karma: -5, happiness: -15 },
        outcomeText: 'তোর জ্ঞান শুইনা মাইয়া বোরিং খাইয়া ঘুমায়া গেলো! তুই হালায় আজীবন সিঙ্গেলই থাকবি, ফইন্নি কোথাকার!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_rooftop_candlelight',
    text: 'ওয়াইফিরে নিয়া ছাদে ক্যান্ডেললাইট ডিনারের ফাপড় নিছোস! পুরাই রোমান্টিক মুড!',
    minAge: 20,
    maxAge: 29,
    weight: 80,
    tone: 'funny',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'rooftop_cook_pasta',
        text: 'নিজের হাতে পাস্তা রান্ধা ওয়াইফিরে খাওয়া!',
        effects: { happiness: -30, looks: -10, health: -20 },
        outcomeText: 'তোর পাস্তা খায়া ওয়াইফির পেট খারাপ! ছাদে বইসাই সে এমুন পাদ দিলো, ক্যান্ডেল নিইভা গেলো! ব্রেকআপ এক্কেরে কনফার্ম!',
        tone: 'bad',
      },
      {
        id: 'rooftop_order_kacchi',
        text: 'কাচ্চি বিরিয়ানি অর্ডার দিয়া নবাবের লাহান খাইতে বয়!',
        effects: { money: -50, happiness: -20 },
        outcomeText: 'খাইতে বসতেই একখান বিশাল সাইজের কাক আইসা তোর কাচ্চির উপ্রে ডাইরেক্ট হাগু কইরা দিলো! ওয়াইফি ঘিন্না খায়া তোরে থাপ্পড় মারলো!',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_meeting_the_parents',
    text: 'ওয়াইফি তোরে তার বাপের লগে দেখা করতে ডাকছে। শ্বশুর হালায় ডাইরেক্ট রিভলবার নিয়া খাড়ায়া আছে!',
    minAge: 21,
    maxAge: 29,
    weight: 75,
    tone: 'bad',
    category: 'young-adult',
    tags: ['romance', 'family'],
    choices: [
      {
        id: 'parents_bring_sweets',
        text: 'মিষ্টির বাক্স নিয়া গিয়া শ্বশুরের পাও ধইরা সালাম কর!',
        effects: { karma: -20, happiness: -35, looks: -15 },
        outcomeText: 'সালাম করতে গিয়া তুই ডরে মুইতা দিলি! শ্বশুর তোর প্যান্টের ভিজা দাগ দেইখা তোরে ঘাড়ধাক্কা দিয়া বাইর কইরা দিলো! কাপুরুষ হালায়!',
        tone: 'bad',
      },
      {
        id: 'parents_debate_career',
        text: 'বুক ফুলাইয়া ক: "আপনার মাইয়ারে আমি সুখে রাখুম, ট্যাকা কোনো ব্যাপার না!"',
        effects: { smarts: -15, happiness: -30 },
        outcomeText: 'শ্বশুর তোর পকেটে হাত দিয়া দেখলো তুই পুরাই ফইন্নি! কুত্তা লেলাইয়া দিয়া তোরে এমুন দৌড়ানি দিলো, তুই প্যান্ট রাইখা ভাগছোস!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_cng_fare_meter',
    text: 'গুলিস্তানের জ্যামে সিএনজিয়ালা ফাপড় নিতাছে: "মামা, আরও ১০০ ট্যাকা না দিলে নামেন!"',
    minAge: 18,
    maxAge: 32,
    weight: 75,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'cng_haggle_firm',
        text: 'কলার ধইরা গাইল দে: "চিনস আমারে? কাইট্টা ফালামু!"',
        effects: { smarts: -10, money: -20, health: -25 },
        outcomeText: 'সিএনজিয়ালা তার লোকাল গ্যাং ডাইকা তোরে উলংগ কইরা এমুন মাইর দিলো! ইজ্জত পুরাই গুলিস্তানের রাস্তায় গড়াইতাছে!',
        tone: 'bad',
      },
      {
        id: 'cng_walk_exercise',
        text: 'ডরে মুইতা দিয়া সিএনজি থিকা লাফ দিয়া নর্দমার পানি পাড়াইয়া হাঁটা ধর!',
        effects: { health: -15, money: 10, happiness: -20 },
        outcomeText: 'পচা কাদা ছিইটা তোর শার্ট পুরাই ডাস্টবিন! অফিসে গিয়া বসের কাছে ছাগলের লাহান ঝাড়ি খাইলি, তুই পুরাই গু-মামা!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_street_fuchka_challenge',
    text: 'দোস্তরা তোরে চ্যালেঞ্জ দিছে: "২০টা বোম্বাই মরিচের ফুচকা খাইতে পারলে তুই বাপের বেটা!"',
    minAge: 18,
    maxAge: 30,
    weight: 75,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'fuchka_champion_eat',
        text: 'বুক ফুলাইয়া সবডি ফুচকা গপাগপ গিল্যা ফ্যাল!',
        effects: { health: -30, happiness: -25, fame: 20 },
        outcomeText: 'খাইতে খাইতে তোর চোখ-নাক দিয়া ধোঁয়া! বাথরুমে গিয়া তুই এমুন চিল্লান দিলি, তোর পাছা পুইড়া এক্কেরে কাবাব হইয়া গেলো!',
        tone: 'bad',
      },
      {
        id: 'fuchka_sensible_mild',
        text: 'ডরে চ্যালেঞ্জ বাদ দিয়া মিষ্টি দই ফুচকা খা ফইন্নির লাহান!',
        effects: { health: 5, happiness: -15, fame: -20 },
        outcomeText: 'দোস্তরা তোরে "হাফ-লেডিস" বইলা ক্ষ্যাপাইলো! মাইয়াগো সামনে তোর ইজ্জত এক্কেরে পাংচার, থুতু দিয়া ডুব দে!',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_office_printer_jam',
    text: 'বসের জরুরি মিটিংয়ের আগে প্রিন্টার হালায় কাগজ আটকাইয়া গ্যাঞ্জাম লাগাইছে!',
    minAge: 21,
    maxAge: 35,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'printer_surgical_fix',
        text: 'ইঞ্জিনিয়ার সাইজা প্রিন্টারের ভিতরে হাত ঢুকাইয়া কাগজ টান দে!',
        effects: { smarts: -10, fame: -15, health: -5 },
        outcomeText: 'কাগজ টানতে গিয়া তোর হাতের লগে প্রিন্টারের কালি লাইগা পুরা মুখ কালা! তুই "কালা মকসদ" সাইজা মিটিংয়ে গেলি, বস হাসতে হাসতে বেহুঁশ!',
        tone: 'bad',
      },
      {
        id: 'printer_digital_tablet',
        text: 'প্রিন্টারে লাথি মাইরা ভাইঙ্গা ফ্যাল রাগের চোটে!',
        effects: { smarts: -20, money: -50, happiness: -30 },
        outcomeText: 'প্রিন্টার ভাইঙ্গা তুই বসরে গালি দিলি! বস তোরে ডাইরেক্ট ঘাড়ধাক্কা দিয়া চাকরি থিকা বাইর কইরা দিলো! এহন রাস্তায় বইসা মুড়ি বেচ!',
        tone: 'bad',
      },
    ],
  },
];