import type { LifeEventDef } from '@/lib/engine/types';

/**
 * Young-adult pool (ages 18–25): leaving school, first jobs, first serious
 * relationships, first money. Education/career entry events award the flags
 * later events gate on. Original prose per AGENT.md §9.
 */
export const YOUNG_ADULT_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'ya_school_decisions',
    text: 'Your last school year ends and suddenly the adult world wants a plan out of you.',
    minAge: 18,
    maxAge: 20,
    weight: 100,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education', 'life-choice'],
    choices: [
      {
        id: 'ya_uni_enrol',
        text: 'Apply to university',
        effects: { addFlag: 'education_university' },
        outcomeText: 'Your acceptance letter is comically heavy. Scholarship forms await.',
        tone: 'good',
      },
      {
        id: 'ya_trade_school',
        text: 'Go to a trade school instead',
        effects: { addFlag: 'education_vocational' },
        outcomeText: 'Six months in and you can wire a socket and explain it to a sceptical aunt.',
        tone: 'good',
      },
      {
        id: 'ya_work_now',
        text: 'Skip more schooling and start working',
        effects: { addFlag: 'job_service' },
        outcomeText: 'Your first badge is pinned on over a polo shirt. It smells faintly of fries.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_uni_freshman',
    text: 'Your first university week is a blur of maps, names, and one very aggressive photocopier.',
    minAge: 18,
    maxAge: 24,
    weight: 90,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education'],
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_fresh_pick_stem',
        text: 'Pick a science and technology major',
        effects: { smarts: 6, addFlag: 'major_stem' },
        outcomeText: 'You now talk confidently about algorithms and carry a calculator for morale.',
        tone: 'good',
      },
      {
        id: 'ya_fresh_pick_arts',
        text: 'Pick an arts major',
        effects: { happiness: 6, looks: 2, addFlag: 'major_arts' },
        outcomeText: 'Your first critique panel nods slowly. Nobody throws anything. Progress.',
        tone: 'good',
      },
      {
        id: 'ya_fresh_pick_business',
        text: 'Pick a business major',
        effects: { smarts: 4, money: 5, addFlag: 'major_business' },
        outcomeText: 'You learn to say "leverage" in three different accents.',
        tone: 'neutral',
      },
      {
        id: 'ya_fresh_pick_medicine',
        text: 'Pick a medicine major',
        effects: { smarts: 6, health: 2, addFlag: 'major_medicine' },
        outcomeText: 'Your first anatomy chart goes proudly on the wall above the kettle.',
        tone: 'neutral',
      },
      {
        id: 'ya_fresh_pick_law',
        text: 'Pick a law major',
        effects: { smarts: 6, happiness: 1, addFlag: 'major_law' },
        outcomeText: 'You learn the word "notwithstanding" and use it twice that same week.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_uni_allnighter',
    text: 'Three essays, one exam, and a group project share a deadline that has clearly been cursed.',
    minAge: 18,
    maxAge: 25,
    weight: 70,
    tone: 'bad',
    category: 'young-adult',
    tags: ['education', 'health'],
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_night_cram',
        text: 'Sleep, and hand in work you are 60% proud of',
        effects: { smarts: 2, health: 3, happiness: 2 },
        outcomeText: 'You sleep like royalty and the grade is fine. Who is the real winner?',
        tone: 'good',
      },
      {
        id: 'ya_night_coffee',
        text: 'Caffeinate through dawn with your footnotes',
        effects: { smarts: 8, health: -6, happiness: -3 },
        outcomeText: 'The essay is beautiful. Your soul is a faint humming noise.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_uni_exam_storm',
    text: 'Exam week arrives like a very large, very organised cat.',
    minAge: 19,
    maxAge: 25,
    weight: 65,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education'],
    requiredFlags: ['education_university'],
    antiFlags: ['gpa_low'],
    choices: [
      {
        id: 'ya_exam_steady',
        text: 'Study in steady blocks, no panic',
        effects: { smarts: 5, health: 2, addFlag: 'gpa_high' },
        outcomeText: 'You emerge from exams like a ship from a storm: intact and smug.',
        tone: 'good',
      },
      {
        id: 'ya_exam_party',
        text: 'Party first, panic later',
        effects: { happiness: 8, smarts: -4, addFlag: 'gpa_low' },
        outcomeText: 'The party was world-class. The exam was not.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_grad_decision',
    text: 'Your degree is done. The certificate feels like it should make a noise when handed over.',
    minAge: 21,
    maxAge: 25,
    weight: 80,
    tone: 'good',
    category: 'young-adult',
    tags: ['education', 'milestone'],
    moment: 'diploma',
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_grad_work',
        text: 'Start job hunting in your field',
        effects: { happiness: 6, addFlag: 'education_graduate', removeFlag: 'gpa_low' },
        outcomeText: 'Cover letters everywhere. One replies. That is all it takes.',
        tone: 'good',
      },
      {
        id: 'ya_grad_gap',
        text: 'Take a year off to think (mostly bikes)',
        effects: { happiness: 10, money: -10, addFlag: 'education_graduate' },
        outcomeText: 'You return with a tan, a great story, and no savings.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_graduate_degree',
    text: 'A professor suggests you stay for a postgraduate degree. The library sighs in anticipation.',
    minAge: 22,
    maxAge: 26,
    weight: 40,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education'],
    requiredFlags: ['education_graduate', 'gpa_high'],
    choices: [
      {
        id: 'ya_grad_school_yes',
        text: 'Stay and specialise',
        effects: { smarts: 10, money: -15, happiness: -2 },
        outcomeText: 'You now know a stunning amount about a vanishingly small thing.',
        tone: 'neutral',
      },
      {
        id: 'ya_grad_school_no',
        text: 'Decline politely, your wallet takes the wheel',
        effects: { money: 10, happiness: 4 },
        outcomeText: 'The library will have to sigh at somebody else.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_first_jobs',
    text: 'The job market splinters into a dozen hopeful doors, most barely ajar.',
    minAge: 18,
    maxAge: 24,
    weight: 85,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'ya_job_retail',
        text: 'Take a retail job with zero interviews and free staff discount',
        effects: { money: 6, happiness: 2, addFlag: 'job_retail' },
        outcomeText: 'Folding marathon. Over the tannoy they call your name like a summons.',
        tone: 'neutral',
      },
      {
        id: 'ya_job_apprentice',
        text: 'Apprentice for a city trade crew',
        effects: { health: -3, money: 8, smarts: 3, addFlag: 'job_trade' },
        outcomeText: 'You learn what "up" really costs in coffee and blisters.',
        tone: 'neutral',
      },
      {
        id: 'ya_job_office_temp',
        text: 'Take an office temp gig filing spreadsheets',
        effects: { money: 7, smarts: 4, happiness: -2, addFlag: 'job_office' },
        outcomeText: 'You become the reigning champion of the mail room.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_promotion_whiff',
    text: 'A senior position opens at work and the grapevine mentions your name once, tentatively.',
    minAge: 20,
    maxAge: 25,
    weight: 60,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'ya_promo_apply',
        text: 'Apply with flair and a slight exaggeration',
        effects: { money: 10, smarts: 3, addFlag: 'perf_high' },
        outcomeText: 'You get the role. The tiny lie dies quietly inside a footnote.',
        tone: 'good',
      },
      {
        id: 'ya_promo_wait',
        text: 'Play it safe and wait for next year',
        effects: { happiness: 3, addFlag: 'perf_low' },
        outcomeText: 'The position goes to Derek, who has never once folded a shirt.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_roommates',
    text: 'Your new flat has four roommates, one bathroom, and a schedule written in a sacred language.',
    minAge: 18,
    maxAge: 24,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['daily-life'],
    choices: [
      {
        id: 'ya_room_chart',
        text: 'Create a heroic shared cleaning chart',
        effects: { smarts: 3, happiness: 5 },
        outcomeText: 'For three glorious weeks, the kitchen is spotless. Then it backslides.',
        tone: 'good',
      },
      {
        id: 'ya_room_petty',
        text: 'Defend your single shelf with your life',
        effects: { happiness: -2, money: 3 },
        outcomeText: 'Your shelf survives. Your social life does not.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_meditate',
    text: 'A friend swears that ten minutes of breathing will fix "everything, genuinely".',
    minAge: 18,
    maxAge: 30,
    weight: 50,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['activity', 'health'],
    choices: [
      {
        id: 'ya_meditate_try',
        text: 'Try it for a week',
        effects: { health: 4, happiness: 4, smarts: 2 },
        outcomeText: 'Your brain still yells, but now from a more comfortable chair.',
        tone: 'good',
      },
      {
        id: 'ya_meditate_skip',
        text: 'Call it "breathing with extra steps"',
        effects: { happiness: -2 },
        outcomeText: 'The app keeps sending you encouraging pings. You ignore them lovingly.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_gym_first',
    text: 'You buy gym shoes and immediately have to explain the purchase to your wallet.',
    minAge: 18,
    maxAge: 26,
    weight: 65,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['activity', 'health'],
    choices: [
      {
        id: 'ya_gym_go',
        text: 'Actually go three times a week',
        effects: { health: 7, looks: 5, happiness: 2, addFlag: 'fitness_good' },
        outcomeText: 'The second week physically hurts. The third week you start winning at stairs.',
        tone: 'good',
      },
      {
        id: 'ya_gym_member',
        text: 'Pay the membership, never go',
        effects: { money: -8, health: -1, happiness: -2 },
        outcomeText: 'The card in your wallet is pristine. That counts as gains, right?',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_first_salary_rush',
    text: 'Payday lands for the first time and the number is bigger than your pocket money ever was.',
    minAge: 18,
    maxAge: 25,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['finance'],
    moment: 'money',
    choices: [
      {
        id: 'ya_salary_save',
        text: 'Put half into savings like the spreadsheets promised',
        effects: { money: 12, smarts: 3 },
        outcomeText: 'Future-you sends a small nod of approval.',
        tone: 'good',
      },
      {
        id: 'ya_salary_splurge',
        text: 'Buy the headphones you have been eyeing for a year',
        effects: { happiness: 9, money: -5 },
        outcomeText: 'The headphones are life-changing. The receipt is a small funeral.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_crypto_fever',
    text: 'A cousin explains an "unmissable" coin and shows you a chart that only goes up.',
    minAge: 18,
    maxAge: 30,
    weight: 45,
    tone: 'funny',
    category: 'young-adult',
    tags: ['finance', 'risk'],
    choices: [
      {
        id: 'ya_crypto_risky',
        text: 'Go all in, what could possibly go wrong',
        effects: { money: 18, happiness: 6, addFlag: 'has_investment' },
        outcomeText: 'For one magical week you are a genius. Then the chart remembers gravity.',
        tone: 'bad',
      },
      {
        id: 'ya_crypto_pass',
        text: 'Nod politely and keep your savings boring',
        effects: { money: 3, smarts: 4 },
        outcomeText: 'Your cousin is now rich. You are calm. Different kinds of winning.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_dating_first',
    text: 'A dating app pings: someone actual and not a bot liked your profile.',
    minAge: 18,
    maxAge: 26,
    weight: 80,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'ya_date_go',
        text: 'Go on the date with zero expectations',
        effects: { happiness: 10, looks: 2 },
        outcomeText: 'The coffee is forgettable. The conversation is not. You swap numbers.',
        tone: 'good',
      },
      {
        id: 'ya_date_no',
        text: 'Reply with a thumbs-up emoji and nothing else',
        effects: { happiness: -2, smarts: 1 },
        outcomeText: 'The thumbs-up is studied like a cryptic manuscript. No reply arrives.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_friend_migration',
    text: 'School friends scatter for jobs and towns until the group chat is mostly memes and silence.',
    minAge: 18,
    maxAge: 26,
    weight: 55,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['relationships'],
    choices: [
      {
        id: 'ya_friend_keep',
        text: 'Organise a monthly video call to hold the crew together',
        effects: { happiness: 6 },
        outcomeText: 'Nobody talks about "fairweather". You are all just still here.',
        tone: 'good',
      },
      {
        id: 'ya_friend_drift',
        text: 'Let the group chat quietly die',
        effects: { happiness: -3, smarts: 2 },
        outcomeText: 'The chat becomes a shrine of inside jokes nobody dares reopen.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_flu_hits',
    text: 'The office runs a viral relay race and you accept the baton.',
    minAge: 18,
    maxAge: 30,
    weight: 60,
    tone: 'bad',
    category: 'young-adult',
    tags: ['health'],
    choices: [
      {
        id: 'ya_flu_rest',
        text: 'Call in sick and actually sleep',
        effects: { health: 6, happiness: 2 },
        outcomeText: 'Two days of soup and blankets. You rejoin the world at 90%.',
        tone: 'good',
      },
      {
        id: 'ya_flu_power',
        text: 'Power through it heroically',
        effects: { health: -7, smarts: -2 },
        outcomeText: 'Your heroism extends the illness by a full and miserable week.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_side_hustle',
    text: 'A friend mentions selling custom prints of your little doodles. People seem to like them.',
    minAge: 20,
    maxAge: 30,
    weight: 55,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career', 'hobby'],
    choices: [
      {
        id: 'ya_hustle_start',
        text: 'Open the shop',
        effects: { money: 9, happiness: 4, addFlag: 'side_hustle' },
        outcomeText: 'Your first sale goes to a stranger in another country. You frame the shipping label.',
        tone: 'good',
      },
      {
        id: 'ya_hustle_drop',
        text: 'Keep drawing just for yourself',
        effects: { happiness: 5, smarts: 1 },
        outcomeText: 'Some joys do not need a storefront.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_symbolic_dinner',
    text: 'Your parents request a dinner at the nice restaurant. You can now afford to look at the menu.',
    minAge: 18,
    maxAge: 26,
    weight: 60,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['family'],
    choices: [
      {
        id: 'ya_dinner_good',
        text: 'Show up with a bottle and good stories',
        effects: { happiness: 8 },
        outcomeText: 'The check is enormous and worth every coin. Your parents glow.',
        tone: 'good',
      },
      {
        id: 'ya_dinner_sketchy',
        text: 'Make it a five-minute drive-by visit instead',
        effects: { happiness: -3, money: 3 },
        outcomeText: 'They wave from the porch as you circle the block softly.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_volunteer_shift',
    text: 'The community centre needs hands for the weekend food drive.',
    minAge: 18,
    maxAge: 30,
    weight: 45,
    tone: 'good',
    category: 'young-adult',
    tags: ['activity', 'community'],
    choices: [
      {
        id: 'ya_volunteer_help',
        text: 'Spend the day hauling boxes',
        effects: { happiness: 7, health: -3, karma: 4, addFlag: 'volunteer' },
        outcomeText: 'Your back aches and your heart is embarrassingly full.',
        tone: 'good',
      },
      {
        id: 'ya_volunteer_skip',
        text: 'Say yes, then accidentally sleep in',
        effects: { happiness: -3, karma: -1 },
        outcomeText: 'The guilt is free and the weekend is quiet.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_flat_fire_drill',
    text: 'The fire alarm in your building blares at midnight. Everyone stands in the car park in pyjamas.',
    minAge: 18,
    maxAge: 30,
    weight: 40,
    tone: 'funny',
    category: 'young-adult',
    tags: ['daily-life'],
    choices: [
      {
        id: 'ya_fire_socks',
        text: 'Grab the document folder, forget the phone',
        effects: { smarts: 3, happiness: -1 },
        outcomeText: 'Worst-resident priorities, best-safety instincts.',
        tone: 'funny',
      },
      {
        id: 'ya_fire_phone',
        text: 'Grab the phone, whirl round the room forever',
        effects: { happiness: 2, health: -3 },
        outcomeText: 'The alarm was a drill. The embarrassment is real.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_first_real_paycheck_dent',
    text: 'Rent, groceries, transport, and a mystery "misc" line eat most of your first real paycheck.',
    minAge: 18,
    maxAge: 26,
    weight: 65,
    tone: 'bad',
    category: 'young-adult',
    tags: ['finance'],
    choices: [
      {
        id: 'ya_budget_now',
        text: 'Build a real budget with alarming honesty',
        effects: { smarts: 5, money: 6, happiness: -2 },
        outcomeText: 'You now know exactly where every coin sleeps. Mostly not with you.',
        tone: 'neutral',
      },
      {
        id: 'ya_budget_deny',
        text: 'Refuse to look, it is fine, probably',
        effects: { happiness: 2, money: -6 },
        outcomeText: 'The mystery "misc" line grows a pet in month two.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_military_enlist',
    text: 'A recruiting office door stands open with a poster about purpose, travel, and discipline.',
    minAge: 18,
    maxAge: 26,
    weight: 35,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career', 'life-choice'],
    choices: [
      {
        id: 'ya_military_go',
        text: 'Enlist and see where it goes',
        effects: { health: 6, smarts: 3, money: 8, addFlag: 'job_military' },
        outcomeText: 'Boot camp is cold, loud, and honestly great for your posture.',
        tone: 'neutral',
      },
      {
        id: 'ya_military_pass',
        text: 'Thank them and keep walking',
        effects: { smarts: 1 },
        outcomeText: 'You decide your purpose lives in a quieter uniform: a hoodie.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_entertainer_dare',
    text: 'A street fair has an open mic, and someone with a megaphone is daring you to go up.',
    minAge: 18,
    maxAge: 28,
    weight: 40,
    tone: 'funny',
    category: 'young-adult',
    tags: ['career', 'fame'],
    choices: [
      {
        id: 'ya_mic_go',
        text: 'Get on stage and wing it',
        effects: { fame: 3, happiness: 8, looks: 2, addFlag: 'job_entertainer' },
        outcomeText: 'You bomb for a minute, then a joke lands and the crowd cheers. Dangerous hobby.',
        tone: 'good',
      },
      {
        id: 'ya_mic_no',
        text: 'Smile, clap, and become furniture',
        effects: { karma: 1 },
        outcomeText: 'The comedian on stage thanks the crowd, including future-you.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_sports_club',
    text: 'An amateur sports league is holding tryouts for absolute beginners, proudly labelled as such.',
    minAge: 18,
    maxAge: 30,
    weight: 45,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['activity', 'sports'],
    choices: [
      {
        id: 'ya_sports_join',
        text: 'Join and get gloriously mediocre',
        effects: { health: 6, happiness: 5, addFlag: 'hobby_sport' },
        outcomeText: 'Three seasons later you are captaining the worst team in the league, fondly.',
        tone: 'good',
      },
      {
        id: 'ya_sports_watch',
        text: 'Watch from the fence with a hot drink',
        effects: { happiness: 2 },
        outcomeText: 'Support from the touchline is also athletic, in a spiritual sense.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_travel_first',
    text: 'A cheap ticket to a coastal city appears in your inbox and taunts you daily.',
    minAge: 20,
    maxAge: 30,
    weight: 50,
    tone: 'good',
    category: 'young-adult',
    tags: ['activity', 'travel'],
    choices: [
      {
        id: 'ya_travel_book',
        text: 'Book it and go alone',
        effects: { happiness: 12, money: -10, addFlag: 'traveler' },
        outcomeText: 'You get lost, eat three breakfasts, and come home with a new laugh.',
        tone: 'good',
      },
      {
        id: 'ya_travel_stay',
        text: 'Stare at the ticket, never book',
        effects: { smarts: 2 },
        outcomeText: 'The taunting email self-deletes in defeat.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_bad_habit_launch',
    text: 'Late nights and machine snacks have quietly become a personality trait.',
    minAge: 20,
    maxAge: 30,
    weight: 50,
    tone: 'bad',
    category: 'young-adult',
    tags: ['health'],
    choices: [
      {
        id: 'ya_habit_fix',
        text: 'Swap the window for a doorway walk at 11pm',
        effects: { health: 5, happiness: 2, addFlag: 'fitness_good' },
        outcomeText: 'Your sleep rhythm is still odd, but now with more fresh air.',
        tone: 'good',
      },
      {
        id: 'ya_habit_indulge',
        text: 'Lean into it; your twenties can take it',
        effects: { health: -6, happiness: 3 },
        outcomeText: 'Your twenties agree, publicly and with witnesses.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_roommate_wedding_seat',
    text: 'A distant cousin invites you to their wedding. "No plus-one, sorry, small venue."',
    minAge: 21,
    maxAge: 30,
    weight: 40,
    tone: 'funny',
    category: 'young-adult',
    tags: ['family'],
    choices: [
      {
        id: 'ya_wedding_go',
        text: 'Go anyway, dance with the older aunties',
        effects: { happiness: 6, karma: 3 },
        outcomeText: 'You are the life of the corner table and family legend material.',
        tone: 'good',
      },
      {
        id: 'ya_wedding_skip',
        text: 'Send a card and a vague excuse',
        effects: { happiness: -1, money: -3 },
        outcomeText: 'The card arrives a week late and is still loved.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_repair_costs',
    text: 'The washing machine declares a strike and the plumber quotes a heroic number.',
    minAge: 18,
    maxAge: 30,
    weight: 55,
    tone: 'bad',
    category: 'young-adult',
    tags: ['finance', 'daily-life'],
    choices: [
      {
        id: 'repair_fix',
        text: 'Pay for it and buy the fight a peace treaty',
        effects: { money: -10, happiness: 2 },
        outcomeText: 'The machine hums again. You understand invoices now. Apologetically.',
        tone: 'neutral',
      },
      {
        id: 'repair_deal',
        text: 'Make it a coin trick: fix the pump yourself',
        effects: { smarts: 5, money: 4 },
        outcomeText: 'Three videos and one triumph later, You have conquered the pump.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_workplace_friend',
    text: 'The least-likely colleague brings identical lunch boxes to the staff room and grins.',
    minAge: 20,
    maxAge: 35,
    weight: 50,
    tone: 'good',
    category: 'young-adult',
    tags: ['relationships'],
    antiFlags: ['retired'],
    choices: [
      {
        id: 'workpal_sit',
        text: 'Sit with them and swap the story behind them',
        effects: { happiness: 6, karma: 2 },
        outcomeText: 'By Friday you have a work friend, a running joke, and a lunch table.',
        tone: 'good',
      },
      {
        id: 'workpal_headphones',
        text: 'Nod and keep your headphones on',
        effects: { happiness: -1, smarts: 1 },
        outcomeText: 'The headphones are polite. The invitation, withdrawn at a snail\'s pace.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_kitchen_lessons',
    text: 'A sudden adult realization: you will be feeding yourself for the foreseeable future.',
    minAge: 18,
    maxAge: 28,
    weight: 60,
    tone: 'funny',
    category: 'young-adult',
    tags: ['health', 'daily-life'],
    choices: [
      {
        id: 'kitchen_learn',
        text: 'Learn four honest recipes of the pancake family',
        effects: { health: 4, money: 3, smarts: 2 },
        outcomeText: 'Your pancake family line goes back generations of one week.',
        tone: 'funny',
      },
      {
        id: 'kitchen_takeout',
        text: 'Contract out the cooking to the delivery apps',
        effects: { happiness: 3, money: -8, health: -2 },
        outcomeText: 'The apps know your address by heart and your sauces by name.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_uni_festival_week',
    text: 'The university festival assigns whole days to colour, noise, and small competitive dances.',
    minAge: 18,
    maxAge: 28,
    weight: 50,
    tone: 'good',
    category: 'young-adult',
    tags: ['education', 'social'],
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'uni_fest_participate',
        text: 'Enter the group dance with zero practice',
        effects: { happiness: 9, fame: 2 },
        outcomeText: 'You are gloriously off-time and the crowd loves the chaos.',
        tone: 'good',
      },
      {
        id: 'uni_fest_stall',
        text: 'Run a food stall with your classics',
        effects: { money: 5, happiness: 5 },
        outcomeText: 'Eleven pancakes sold, one friendship started, zero wash-up complaints.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_bookclub',
    text: 'Someone starts a neighbourhood book club and the venue of choice is a very comfy sofa.',
    minAge: 22,
    maxAge: 40,
    weight: 45,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['hobby', 'social'],
    choices: [
      {
        id: 'bookclub_join',
        text: 'Join and actually finish the book',
        effects: { smarts: 5, happiness: 4 },
        outcomeText: 'The discussion is fierce and the biscuits are legendary. You return.',
        tone: 'good',
      },
      {
        id: 'bookclub_dip',
        text: 'Come for the biscuits and moral support',
        effects: { happiness: 3, karma: 1 },
        outcomeText: 'The spoilers wait politely for you every month.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_flatshare_move',
    text: 'A new flat materialises, closer to work, with a window that has opinions about the sun.',
    minAge: 19,
    maxAge: 30,
    weight: 50,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['daily-life', 'finance'],
    choices: [
      {
        id: 'flatshare_move',
        text: 'Move and mystery-box the new room',
        effects: { money: -6, happiness: 6 },
        outcomeText: 'The first night, slightly haunted by boxes. The second week, home.',
        tone: 'good',
      },
      {
        id: 'flatshare_stay',
        text: 'Stay where the rent is known and the sink is loyal',
        effects: { money: 5, happiness: 1 },
        outcomeText: 'The sink remains loyal. The commute remains eternal.',
        tone: 'neutral',
      },
    ],
  },
];