import type { LifeEventDef } from '@/lib/engine/types';

/**
 * Young-adult pool (ages 18–25): leaving school, first jobs, first serious
 * relationships, first money. Education/career entry events award the flags
 * later events gate on. Original prose per AGENT.md §9.
 */
export const YOUNG_ADULT_EVENTS: readonly LifeEventDef[] = [
  {
    id: 'ya_school_decisions',
    text: 'Your last school year ends and suddenly the adult world wants a plan out of you.',
    minAge: 18,
    maxAge: 20,
    weight: 100,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education', 'life-choice'],
    choices: [
      {
        id: 'ya_uni_enrol',
        text: 'Apply to university',
        effects: { addFlag: 'education_university' },
        outcomeText: 'Your acceptance letter is comically heavy. Scholarship forms await.',
        tone: 'good',
      },
      {
        id: 'ya_trade_school',
        text: 'Go to a trade school instead',
        effects: { addFlag: 'education_vocational' },
        outcomeText: 'Six months in and you can wire a socket and explain it to a sceptical aunt.',
        tone: 'good',
      },
      {
        id: 'ya_work_now',
        text: 'Skip more schooling and start working',
        effects: { addFlag: 'job_service' },
        outcomeText: 'Your first badge is pinned on over a polo shirt. It smells faintly of fries.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_uni_freshman',
    text: 'Your first university week is a blur of maps, names, and one very aggressive photocopier.',
    minAge: 18,
    maxAge: 24,
    weight: 90,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education'],
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_fresh_pick_stem',
        text: 'Pick a science and technology major',
        effects: { smarts: 6, addFlag: 'major_stem' },
        outcomeText: 'You now talk confidently about algorithms and carry a calculator for morale.',
        tone: 'good',
      },
      {
        id: 'ya_fresh_pick_arts',
        text: 'Pick an arts major',
        effects: { happiness: 6, looks: 2, addFlag: 'major_arts' },
        outcomeText: 'Your first critique panel nods slowly. Nobody throws anything. Progress.',
        tone: 'good',
      },
      {
        id: 'ya_fresh_pick_business',
        text: 'Pick a business major',
        effects: { smarts: 4, money: 5, addFlag: 'major_business' },
        outcomeText: 'You learn to say "leverage" in three different accents.',
        tone: 'neutral',
      },
      {
        id: 'ya_fresh_pick_medicine',
        text: 'Pick a medicine major',
        effects: { smarts: 6, health: 2, addFlag: 'major_medicine' },
        outcomeText: 'Your first anatomy chart goes proudly on the wall above the kettle.',
        tone: 'neutral',
      },
      {
        id: 'ya_fresh_pick_law',
        text: 'Pick a law major',
        effects: { smarts: 6, happiness: 1, addFlag: 'major_law' },
        outcomeText: 'You learn the word "notwithstanding" and use it twice that same week.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_uni_allnighter',
    text: 'Three essays, one exam, and a group project share a deadline that has clearly been cursed.',
    minAge: 18,
    maxAge: 25,
    weight: 70,
    tone: 'bad',
    category: 'young-adult',
    tags: ['education', 'health'],
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_night_cram',
        text: 'Sleep, and hand in work you are 60% proud of',
        effects: { smarts: 2, health: 3, happiness: 2 },
        outcomeText: 'You sleep like royalty and the grade is fine. Who is the real winner?',
        tone: 'good',
      },
      {
        id: 'ya_night_coffee',
        text: 'Caffeinate through dawn with your footnotes',
        effects: { smarts: 8, health: -6, happiness: -3 },
        outcomeText: 'The essay is beautiful. Your soul is a faint humming noise.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_uni_exam_storm',
    text: 'Exam week arrives like a very large, very organised cat.',
    minAge: 19,
    maxAge: 25,
    weight: 65,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education'],
    requiredFlags: ['education_university'],
    antiFlags: ['gpa_low'],
    choices: [
      {
        id: 'ya_exam_steady',
        text: 'Study in steady blocks, no panic',
        effects: { smarts: 5, health: 2, addFlag: 'gpa_high' },
        outcomeText: 'You emerge from exams like a ship from a storm: intact and smug.',
        tone: 'good',
      },
      {
        id: 'ya_exam_party',
        text: 'Party first, panic later',
        effects: { happiness: 8, smarts: -4, addFlag: 'gpa_low' },
        outcomeText: 'The party was world-class. The exam was not.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_grad_decision',
    text: 'Your degree is done. The certificate feels like it should make a noise when handed over.',
    minAge: 21,
    maxAge: 25,
    weight: 80,
    tone: 'good',
    category: 'young-adult',
    tags: ['education', 'milestone'],
    moment: 'diploma',
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'ya_grad_work',
        text: 'Start job hunting in your field',
        effects: { happiness: 6, addFlag: 'education_graduate', removeFlag: 'gpa_low' },
        outcomeText: 'Cover letters everywhere. One replies. That is all it takes.',
        tone: 'good',
      },
      {
        id: 'ya_grad_gap',
        text: 'Take a year off to think (mostly bikes)',
        effects: { happiness: 10, money: -10, addFlag: 'education_graduate' },
        outcomeText: 'You return with a tan, a great story, and no savings.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_graduate_degree',
    text: 'A professor suggests you stay for a postgraduate degree. The library sighs in anticipation.',
    minAge: 22,
    maxAge: 26,
    weight: 40,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education'],
    requiredFlags: ['education_graduate', 'gpa_high'],
    choices: [
      {
        id: 'ya_grad_school_yes',
        text: 'Stay and specialise',
        effects: { smarts: 10, money: -15, happiness: -2 },
        outcomeText: 'You now know a stunning amount about a vanishingly small thing.',
        tone: 'neutral',
      },
      {
        id: 'ya_grad_school_no',
        text: 'Decline politely, your wallet takes the wheel',
        effects: { money: 10, happiness: 4 },
        outcomeText: 'The library will have to sigh at somebody else.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_first_jobs',
    text: 'The job market splinters into a dozen hopeful doors, most barely ajar.',
    minAge: 18,
    maxAge: 24,
    weight: 85,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'ya_job_retail',
        text: 'Take a retail job with zero interviews and free staff discount',
        effects: { money: 6, happiness: 2, addFlag: 'job_retail' },
        outcomeText: 'Folding marathon. Over the tannoy they call your name like a summons.',
        tone: 'neutral',
      },
      {
        id: 'ya_job_apprentice',
        text: 'Apprentice for a city trade crew',
        effects: { health: -3, money: 8, smarts: 3, addFlag: 'job_trade' },
        outcomeText: 'You learn what "up" really costs in coffee and blisters.',
        tone: 'neutral',
      },
      {
        id: 'ya_job_office_temp',
        text: 'Take an office temp gig filing spreadsheets',
        effects: { money: 7, smarts: 4, happiness: -2, addFlag: 'job_office' },
        outcomeText: 'You become the reigning champion of the mail room.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_promotion_whiff',
    text: 'A senior position opens at work and the grapevine mentions your name once, tentatively.',
    minAge: 20,
    maxAge: 25,
    weight: 60,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'ya_promo_apply',
        text: 'Apply with flair and a slight exaggeration',
        effects: { money: 10, smarts: 3, addFlag: 'perf_high' },
        outcomeText: 'You get the role. The tiny lie dies quietly inside a footnote.',
        tone: 'good',
      },
      {
        id: 'ya_promo_wait',
        text: 'Play it safe and wait for next year',
        effects: { happiness: 3, addFlag: 'perf_low' },
        outcomeText: 'The position goes to Derek, who has never once folded a shirt.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_roommates',
    text: 'Your new flat has four roommates, one bathroom, and a schedule written in a sacred language.',
    minAge: 18,
    maxAge: 24,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['daily-life'],
    choices: [
      {
        id: 'ya_room_chart',
        text: 'Create a heroic shared cleaning chart',
        effects: { smarts: 3, happiness: 5 },
        outcomeText: 'For three glorious weeks, the kitchen is spotless. Then it backslides.',
        tone: 'good',
      },
      {
        id: 'ya_room_petty',
        text: 'Defend your single shelf with your life',
        effects: { happiness: -2, money: 3 },
        outcomeText: 'Your shelf survives. Your social life does not.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_meditate',
    text: 'A friend swears that ten minutes of breathing will fix "everything, genuinely".',
    minAge: 18,
    maxAge: 30,
    weight: 50,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['activity', 'health'],
    choices: [
      {
        id: 'ya_meditate_try',
        text: 'Try it for a week',
        effects: { health: 4, happiness: 4, smarts: 2 },
        outcomeText: 'Your brain still yells, but now from a more comfortable chair.',
        tone: 'good',
      },
      {
        id: 'ya_meditate_skip',
        text: 'Call it "breathing with extra steps"',
        effects: { happiness: -2 },
        outcomeText: 'The app keeps sending you encouraging pings. You ignore them lovingly.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_gym_first',
    text: 'You buy gym shoes and immediately have to explain the purchase to your wallet.',
    minAge: 18,
    maxAge: 26,
    weight: 65,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['activity', 'health'],
    choices: [
      {
        id: 'ya_gym_go',
        text: 'Actually go three times a week',
        effects: { health: 7, looks: 5, happiness: 2, addFlag: 'fitness_good' },
        outcomeText: 'The second week physically hurts. The third week you start winning at stairs.',
        tone: 'good',
      },
      {
        id: 'ya_gym_member',
        text: 'Pay the membership, never go',
        effects: { money: -8, health: -1, happiness: -2 },
        outcomeText: 'The card in your wallet is pristine. That counts as gains, right?',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_first_salary_rush',
    text: 'Payday lands for the first time and the number is bigger than your pocket money ever was.',
    minAge: 18,
    maxAge: 25,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['finance'],
    moment: 'money',
    choices: [
      {
        id: 'ya_salary_save',
        text: 'Put half into savings like the spreadsheets promised',
        effects: { money: 12, smarts: 3 },
        outcomeText: 'Future-you sends a small nod of approval.',
        tone: 'good',
      },
      {
        id: 'ya_salary_splurge',
        text: 'Buy the headphones you have been eyeing for a year',
        effects: { happiness: 9, money: -5 },
        outcomeText: 'The headphones are life-changing. The receipt is a small funeral.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_crypto_fever',
    text: 'A cousin explains an "unmissable" coin and shows you a chart that only goes up.',
    minAge: 18,
    maxAge: 30,
    weight: 45,
    tone: 'funny',
    category: 'young-adult',
    tags: ['finance', 'risk'],
    choices: [
      {
        id: 'ya_crypto_risky',
        text: 'Go all in, what could possibly go wrong',
        effects: { money: 18, happiness: 6, addFlag: 'has_investment' },
        outcomeText: 'For one magical week you are a genius. Then the chart remembers gravity.',
        tone: 'bad',
      },
      {
        id: 'ya_crypto_pass',
        text: 'Nod politely and keep your savings boring',
        effects: { money: 3, smarts: 4 },
        outcomeText: 'Your cousin is now rich. You are calm. Different kinds of winning.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_dating_first',
    text: 'A dating app pings: someone actual and not a bot liked your profile.',
    minAge: 18,
    maxAge: 26,
    weight: 80,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'ya_date_go',
        text: 'Go on the date with zero expectations',
        effects: { happiness: 10, looks: 2 },
        outcomeText: 'The coffee is forgettable. The conversation is not. You swap numbers.',
        tone: 'good',
      },
      {
        id: 'ya_date_no',
        text: 'Reply with a thumbs-up emoji and nothing else',
        effects: { happiness: -2, smarts: 1 },
        outcomeText: 'The thumbs-up is studied like a cryptic manuscript. No reply arrives.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_friend_migration',
    text: 'School friends scatter for jobs and towns until the group chat is mostly memes and silence.',
    minAge: 18,
    maxAge: 26,
    weight: 55,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['relationships'],
    choices: [
      {
        id: 'ya_friend_keep',
        text: 'Organise a monthly video call to hold the crew together',
        effects: { happiness: 6 },
        outcomeText: 'Nobody talks about "fairweather". You are all just still here.',
        tone: 'good',
      },
      {
        id: 'ya_friend_drift',
        text: 'Let the group chat quietly die',
        effects: { happiness: -3, smarts: 2 },
        outcomeText: 'The chat becomes a shrine of inside jokes nobody dares reopen.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_flu_hits',
    text: 'The office runs a viral relay race and you accept the baton.',
    minAge: 18,
    maxAge: 30,
    weight: 60,
    tone: 'bad',
    category: 'young-adult',
    tags: ['health'],
    choices: [
      {
        id: 'ya_flu_rest',
        text: 'Call in sick and actually sleep',
        effects: { health: 6, happiness: 2 },
        outcomeText: 'Two days of soup and blankets. You rejoin the world at 90%.',
        tone: 'good',
      },
      {
        id: 'ya_flu_power',
        text: 'Power through it heroically',
        effects: { health: -7, smarts: -2 },
        outcomeText: 'Your heroism extends the illness by a full and miserable week.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_side_hustle',
    text: 'A friend mentions selling custom prints of your little doodles. People seem to like them.',
    minAge: 20,
    maxAge: 30,
    weight: 55,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career', 'hobby'],
    choices: [
      {
        id: 'ya_hustle_start',
        text: 'Open the shop',
        effects: { money: 9, happiness: 4, addFlag: 'side_hustle' },
        outcomeText: 'Your first sale goes to a stranger in another country. You frame the shipping label.',
        tone: 'good',
      },
      {
        id: 'ya_hustle_drop',
        text: 'Keep drawing just for yourself',
        effects: { happiness: 5, smarts: 1 },
        outcomeText: 'Some joys do not need a storefront.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_symbolic_dinner',
    text: 'Your parents request a dinner at the nice restaurant. You can now afford to look at the menu.',
    minAge: 18,
    maxAge: 26,
    weight: 60,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['family'],
    choices: [
      {
        id: 'ya_dinner_good',
        text: 'Show up with a bottle and good stories',
        effects: { happiness: 8 },
        outcomeText: 'The check is enormous and worth every coin. Your parents glow.',
        tone: 'good',
      },
      {
        id: 'ya_dinner_sketchy',
        text: 'Make it a five-minute drive-by visit instead',
        effects: { happiness: -3, money: 3 },
        outcomeText: 'They wave from the porch as you circle the block softly.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_volunteer_shift',
    text: 'The community centre needs hands for the weekend food drive.',
    minAge: 18,
    maxAge: 30,
    weight: 45,
    tone: 'good',
    category: 'young-adult',
    tags: ['activity', 'community'],
    choices: [
      {
        id: 'ya_volunteer_help',
        text: 'Spend the day hauling boxes',
        effects: { happiness: 7, health: -3, karma: 4, addFlag: 'volunteer' },
        outcomeText: 'Your back aches and your heart is embarrassingly full.',
        tone: 'good',
      },
      {
        id: 'ya_volunteer_skip',
        text: 'Say yes, then accidentally sleep in',
        effects: { happiness: -3, karma: -1 },
        outcomeText: 'The guilt is free and the weekend is quiet.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_flat_fire_drill',
    text: 'The fire alarm in your building blares at midnight. Everyone stands in the car park in pyjamas.',
    minAge: 18,
    maxAge: 30,
    weight: 40,
    tone: 'funny',
    category: 'young-adult',
    tags: ['daily-life'],
    choices: [
      {
        id: 'ya_fire_socks',
        text: 'Grab the document folder, forget the phone',
        effects: { smarts: 3, happiness: -1 },
        outcomeText: 'Worst-resident priorities, best-safety instincts.',
        tone: 'funny',
      },
      {
        id: 'ya_fire_phone',
        text: 'Grab the phone, whirl round the room forever',
        effects: { happiness: 2, health: -3 },
        outcomeText: 'The alarm was a drill. The embarrassment is real.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_first_real_paycheck_dent',
    text: 'Rent, groceries, transport, and a mystery "misc" line eat most of your first real paycheck.',
    minAge: 18,
    maxAge: 26,
    weight: 65,
    tone: 'bad',
    category: 'young-adult',
    tags: ['finance'],
    choices: [
      {
        id: 'ya_budget_now',
        text: 'Build a real budget with alarming honesty',
        effects: { smarts: 5, money: 6, happiness: -2 },
        outcomeText: 'You now know exactly where every coin sleeps. Mostly not with you.',
        tone: 'neutral',
      },
      {
        id: 'ya_budget_deny',
        text: 'Refuse to look, it is fine, probably',
        effects: { happiness: 2, money: -6 },
        outcomeText: 'The mystery "misc" line grows a pet in month two.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_military_enlist',
    text: 'A recruiting office door stands open with a poster about purpose, travel, and discipline.',
    minAge: 18,
    maxAge: 26,
    weight: 35,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career', 'life-choice'],
    choices: [
      {
        id: 'ya_military_go',
        text: 'Enlist and see where it goes',
        effects: { health: 6, smarts: 3, money: 8, addFlag: 'job_military' },
        outcomeText: 'Boot camp is cold, loud, and honestly great for your posture.',
        tone: 'neutral',
      },
      {
        id: 'ya_military_pass',
        text: 'Thank them and keep walking',
        effects: { smarts: 1 },
        outcomeText: 'You decide your purpose lives in a quieter uniform: a hoodie.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_entertainer_dare',
    text: 'A street fair has an open mic, and someone with a megaphone is daring you to go up.',
    minAge: 18,
    maxAge: 28,
    weight: 40,
    tone: 'funny',
    category: 'young-adult',
    tags: ['career', 'fame'],
    choices: [
      {
        id: 'ya_mic_go',
        text: 'Get on stage and wing it',
        effects: { fame: 3, happiness: 8, looks: 2, addFlag: 'job_entertainer' },
        outcomeText: 'You bomb for a minute, then a joke lands and the crowd cheers. Dangerous hobby.',
        tone: 'good',
      },
      {
        id: 'ya_mic_no',
        text: 'Smile, clap, and become furniture',
        effects: { karma: 1 },
        outcomeText: 'The comedian on stage thanks the crowd, including future-you.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_sports_club',
    text: 'An amateur sports league is holding tryouts for absolute beginners, proudly labelled as such.',
    minAge: 18,
    maxAge: 30,
    weight: 45,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['activity', 'sports'],
    choices: [
      {
        id: 'ya_sports_join',
        text: 'Join and get gloriously mediocre',
        effects: { health: 6, happiness: 5, addFlag: 'hobby_sport' },
        outcomeText: 'Three seasons later you are captaining the worst team in the league, fondly.',
        tone: 'good',
      },
      {
        id: 'ya_sports_watch',
        text: 'Watch from the fence with a hot drink',
        effects: { happiness: 2 },
        outcomeText: 'Support from the touchline is also athletic, in a spiritual sense.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_travel_first',
    text: 'A cheap ticket to a coastal city appears in your inbox and taunts you daily.',
    minAge: 20,
    maxAge: 30,
    weight: 50,
    tone: 'good',
    category: 'young-adult',
    tags: ['activity', 'travel'],
    choices: [
      {
        id: 'ya_travel_book',
        text: 'Book it and go alone',
        effects: { happiness: 12, money: -10, addFlag: 'traveler' },
        outcomeText: 'You get lost, eat three breakfasts, and come home with a new laugh.',
        tone: 'good',
      },
      {
        id: 'ya_travel_stay',
        text: 'Stare at the ticket, never book',
        effects: { smarts: 2 },
        outcomeText: 'The taunting email self-deletes in defeat.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_bad_habit_launch',
    text: 'Late nights and machine snacks have quietly become a personality trait.',
    minAge: 20,
    maxAge: 30,
    weight: 50,
    tone: 'bad',
    category: 'young-adult',
    tags: ['health'],
    choices: [
      {
        id: 'ya_habit_fix',
        text: 'Swap the window for a doorway walk at 11pm',
        effects: { health: 5, happiness: 2, addFlag: 'fitness_good' },
        outcomeText: 'Your sleep rhythm is still odd, but now with more fresh air.',
        tone: 'good',
      },
      {
        id: 'ya_habit_indulge',
        text: 'Lean into it; your twenties can take it',
        effects: { health: -6, happiness: 3 },
        outcomeText: 'Your twenties agree, publicly and with witnesses.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_roommate_wedding_seat',
    text: 'A distant cousin invites you to their wedding. "No plus-one, sorry, small venue."',
    minAge: 21,
    maxAge: 30,
    weight: 40,
    tone: 'funny',
    category: 'young-adult',
    tags: ['family'],
    choices: [
      {
        id: 'ya_wedding_go',
        text: 'Go anyway, dance with the older aunties',
        effects: { happiness: 6, karma: 3 },
        outcomeText: 'You are the life of the corner table and family legend material.',
        tone: 'good',
      },
      {
        id: 'ya_wedding_skip',
        text: 'Send a card and a vague excuse',
        effects: { happiness: -1, money: -3 },
        outcomeText: 'The card arrives a week late and is still loved.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_repair_costs',
    text: 'The washing machine declares a strike and the plumber quotes a heroic number.',
    minAge: 18,
    maxAge: 30,
    weight: 55,
    tone: 'bad',
    category: 'young-adult',
    tags: ['finance', 'daily-life'],
    choices: [
      {
        id: 'repair_fix',
        text: 'Pay for it and buy the fight a peace treaty',
        effects: { money: -10, happiness: 2 },
        outcomeText: 'The machine hums again. You understand invoices now. Apologetically.',
        tone: 'neutral',
      },
      {
        id: 'repair_deal',
        text: 'Make it a coin trick: fix the pump yourself',
        effects: { smarts: 5, money: 4 },
        outcomeText: 'Three videos and one triumph later, You have conquered the pump.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_workplace_friend',
    text: 'The least-likely colleague brings identical lunch boxes to the staff room and grins.',
    minAge: 20,
    maxAge: 35,
    weight: 50,
    tone: 'good',
    category: 'young-adult',
    tags: ['relationships'],
    antiFlags: ['retired'],
    choices: [
      {
        id: 'workpal_sit',
        text: 'Sit with them and swap the story behind them',
        effects: { happiness: 6, karma: 2 },
        outcomeText: 'By Friday you have a work friend, a running joke, and a lunch table.',
        tone: 'good',
      },
      {
        id: 'workpal_headphones',
        text: 'Nod and keep your headphones on',
        effects: { happiness: -1, smarts: 1 },
        outcomeText: 'The headphones are polite. The invitation, withdrawn at a snail\'s pace.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_kitchen_lessons',
    text: 'A sudden adult realization: you will be feeding yourself for the foreseeable future.',
    minAge: 18,
    maxAge: 28,
    weight: 60,
    tone: 'funny',
    category: 'young-adult',
    tags: ['health', 'daily-life'],
    choices: [
      {
        id: 'kitchen_learn',
        text: 'Learn four honest recipes of the pancake family',
        effects: { health: 4, money: 3, smarts: 2 },
        outcomeText: 'Your pancake family line goes back generations of one week.',
        tone: 'funny',
      },
      {
        id: 'kitchen_takeout',
        text: 'Contract out the cooking to the delivery apps',
        effects: { happiness: 3, money: -8, health: -2 },
        outcomeText: 'The apps know your address by heart and your sauces by name.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_uni_festival_week',
    text: 'The university festival assigns whole days to colour, noise, and small competitive dances.',
    minAge: 18,
    maxAge: 28,
    weight: 50,
    tone: 'good',
    category: 'young-adult',
    tags: ['education', 'social'],
    requiredFlags: ['education_university'],
    choices: [
      {
        id: 'uni_fest_participate',
        text: 'Enter the group dance with zero practice',
        effects: { happiness: 9, fame: 2 },
        outcomeText: 'You are gloriously off-time and the crowd loves the chaos.',
        tone: 'good',
      },
      {
        id: 'uni_fest_stall',
        text: 'Run a food stall with your classics',
        effects: { money: 5, happiness: 5 },
        outcomeText: 'Eleven pancakes sold, one friendship started, zero wash-up complaints.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_bookclub',
    text: 'Someone starts a neighbourhood book club and the venue of choice is a very comfy sofa.',
    minAge: 22,
    maxAge: 40,
    weight: 45,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['hobby', 'social'],
    choices: [
      {
        id: 'bookclub_join',
        text: 'Join and actually finish the book',
        effects: { smarts: 5, happiness: 4 },
        outcomeText: 'The discussion is fierce and the biscuits are legendary. You return.',
        tone: 'good',
      },
      {
        id: 'bookclub_dip',
        text: 'Come for the biscuits and moral support',
        effects: { happiness: 3, karma: 1 },
        outcomeText: 'The spoilers wait politely for you every month.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_flatshare_move',
    text: 'A new flat materialises, closer to work, with a window that has opinions about the sun.',
    minAge: 19,
    maxAge: 30,
    weight: 50,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['daily-life', 'finance'],
    choices: [
      {
        id: 'flatshare_move',
        text: 'Move and mystery-box the new room',
        effects: { money: -6, happiness: 6 },
        outcomeText: 'The first night, slightly haunted by boxes. The second week, home.',
        tone: 'good',
      },
      {
        id: 'flatshare_stay',
        text: 'Stay where the rent is known and the sink is loyal',
        effects: { money: 5, happiness: 1 },
        outcomeText: 'The sink remains loyal. The commute remains eternal.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_speed_dating',
    text: 'A hip Dhanmondi café hosts an indie speed-dating night with {cardboard prompts|three-minute sand timers|acoustic music}.',
    minAge: 19,
    maxAge: 28,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'speed_witty_banter',
        text: 'Deploy your quickest wit and humorous observations',
        effects: { looks: 4, happiness: 12, fame: 3 },
        outcomeText: 'You scored three match cards by the end of the evening! A resounding triumph.',
        tone: 'good',
      },
      {
        id: 'speed_deep_question',
        text: 'Skip small talk and ask about childhood dreams and life philosophies',
        effects: { smarts: 4, karma: 3, happiness: 8 },
        outcomeText: 'One conversation ran overtime as you both forgot the timer existed.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_blind_date_disaster',
    text: 'A well-meaning cousin sets you up on a blind date with someone who {talks exclusively about crypto conspiracies|brought their mother along|forgot their wallet entirely}.',
    minAge: 20,
    maxAge: 28,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'blind_fake_emergency',
        text: 'Have a trusted friend call you with an urgent fictional water pipe burst',
        effects: { smarts: 4, happiness: 5 },
        outcomeText: 'Polite excuses made, bill split, and a swift tactical retreat achieved.',
        tone: 'funny',
      },
      {
        id: 'blind_endure_for_dessert',
        text: 'Endure the eccentricity patiently and order the most expensive molten chocolate cake',
        effects: { happiness: 4, health: -1, money: -8 },
        outcomeText: 'The chocolate cake was heavenly. The storytelling material for friends: priceless.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_rooftop_candlelight',
    text: 'You plan a surprise dinner for your partner on your {rooftop with fairy lights|balcony with acoustic tunes|living room floor with takeout}.',
    minAge: 20,
    maxAge: 29,
    weight: 80,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'rooftop_cook_pasta',
        text: 'Cook creamy garlic chicken pasta from scratch with fresh herbs',
        effects: { happiness: 16, looks: 4, karma: 4 },
        outcomeText: 'The pasta was restaurant-quality, and the city skyline glowed in warm intimacy.',
        tone: 'good',
      },
      {
        id: 'rooftop_order_kacchi',
        text: 'Order premium mutton kacchi biryani and feast under the stars',
        effects: { money: -12, happiness: 14 },
        outcomeText: 'Nothing says true romantic passion quite like a mountain of spiced fragrant rice.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_monsoon_boat_ride',
    text: 'During a balmy overcast afternoon, you and your romantic interest rent a wooden paddle boat on {Dhanmondi Lake|Gulshan Lake|the riverfront}.',
    minAge: 19,
    maxAge: 28,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'boat_gentle_paddle',
        text: 'Paddle out toward the weeping willows and drift peacefully',
        effects: { happiness: 14, looks: 3 },
        outcomeText: 'Gentle water ripples, quiet confessions, and fingers intertwining.',
        tone: 'good',
      },
      {
        id: 'boat_race_couples',
        text: 'Challenge another couple to a fiercely competitive paddle race',
        effects: { health: 4, happiness: 10, fame: 2 },
        outcomeText: 'Laughter echoed across the water as you both splashed to victory.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_meeting_the_parents',
    text: 'Your partner invites you to Sunday family lunch to meet {their traditional father|their eagle-eyed mother|an interrogation panel of aunts}.',
    minAge: 21,
    maxAge: 29,
    weight: 75,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['romance', 'family'],
    choices: [
      {
        id: 'parents_bring_sweets',
        text: 'Bring a box of premium Roshomalai and compliment the home decor respectfully',
        effects: { karma: 8, happiness: 12, looks: 4 },
        outcomeText: 'The mother beamed, the father nodded with approval, and you were offered a second plate.',
        tone: 'good',
      },
      {
        id: 'parents_debate_career',
        text: 'Articulate your long-term career ambition and financial stability calmly',
        effects: { smarts: 6, happiness: 8 },
        outcomeText: 'They appreciated your grounded maturity. The test was passed with flying colors.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_moving_in_together',
    text: 'You and your partner decide to take the leap and sign a lease on a {bright sunlit flat in Lalmatia|cozy 2-bedroom in Banani}.',
    minAge: 21,
    maxAge: 29,
    weight: 80,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance', 'lifestyle'],
    choices: [
      {
        id: 'movein_paint_walls',
        text: 'Spend the first weekend painting the accent walls teal and building flat-pack shelves',
        effects: { happiness: 18, looks: 2, money: -20 },
        outcomeText: 'Paint stains on your nose, takeout eaten from cardboard boxes: officially home.',
        tone: 'good',
      },
      {
        id: 'movein_housewarming_party',
        text: 'Host a boisterous housewarming night with all your mutual friends',
        effects: { fame: 6, happiness: 15, money: -15 },
        outcomeText: 'The living room was packed with warmth, music, and celebratory house plants.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_shared_hoodie_dispute',
    text: 'You open your closet looking for your favorite comfortable fleece hoodie, only to find {your partner wearing it with rolled sleeves|it hanging in their wardrobe}.',
    minAge: 19,
    maxAge: 28,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'hoodie_surrender',
        text: 'Concede defeat: it officially belongs to them now and they look adorable in it',
        effects: { happiness: 10, karma: 3 },
        outcomeText: 'You gained boyfriend/girlfriend points, but lost your warmest garment permanently.',
        tone: 'good',
      },
      {
        id: 'hoodie_playful_heist',
        text: 'Steal their oversized knitted cardigan in an act of retaliatory fashion',
        effects: { looks: 3, happiness: 8 },
        outcomeText: 'A balanced trade war of cozy knitwear that left both of you chuckling.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_couples_getaway_coxs',
    text: 'A long weekend approaches. You and your partner book train tickets for a spontaneous trip to {Cox Bazar beach|the tea hills of Sreemangal|Sylhet waterfalls}.',
    minAge: 20,
    maxAge: 29,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance', 'adventure'],
    choices: [
      {
        id: 'getaway_sunrise_walk',
        text: 'Wake up at dawn to walk barefoot along the tide as fishermen haul their nets',
        effects: { health: 5, happiness: 16, looks: 3 },
        outcomeText: 'Golden morning mist, crashing waves, and uninterrupted romantic tranquility.',
        tone: 'good',
      },
      {
        id: 'getaway_seafood_feasting',
        text: 'Gorge on grilled tiger prawns and crab masala at a beachside shack',
        effects: { money: -15, happiness: 14 },
        outcomeText: 'Spicy, charred, fresh seafood devoured while listening to the roar of the sea.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_celebrity_encounter_cafe',
    text: 'While working from a quiet rooftop café, {a famous rising pop star|an acclaimed indie film director} sits at the table beside you.',
    minAge: 19,
    maxAge: 29,
    weight: 65,
    tone: 'good',
    category: 'young-adult',
    tags: ['social'],
    choices: [
      {
        id: 'celeb_friendly_compliment',
        text: 'Politely say you admire their recent work without making a scene',
        effects: { fame: 5, happiness: 10, looks: 2 },
        outcomeText: 'They smiled warmly, thanked you sincerely, and chatted about coffee for five minutes.',
        tone: 'good',
      },
      {
        id: 'celeb_give_space',
        text: 'Respect their privacy and let them enjoy their iced Americano in peace',
        effects: { karma: 5, smarts: 2 },
        outcomeText: 'They gave you an appreciative nod as they gathered their notebook to leave.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_flirtatious_barista',
    text: 'The charming barista at your regular morning coffee spot draws a heart on your cup lid and {winks warmly|writes their personal phone number}.',
    minAge: 18,
    maxAge: 27,
    weight: 70,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'barista_text_back',
        text: 'Send a playful text thanking them for the extra espresso shot',
        effects: { looks: 4, happiness: 12 },
        outcomeText: 'A fun, flirty exchange begins before your work shift even starts.',
        tone: 'good',
      },
      {
        id: 'barista_polite_tip',
        text: 'Tip extra generously in the tip jar with a thankful smile',
        effects: { karma: 4, money: -2, happiness: 5 },
        outcomeText: 'Kept it professional and friendly. You now get free extra foam every visit.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_anniversary_surprise_hunt',
    text: 'Your dating anniversary is coming up. You search through {old city antique shops|boutique artisan studios} for a truly meaningful gift.',
    minAge: 20,
    maxAge: 29,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'anniv_custom_locket',
        text: 'Commission a custom silver pendant engraved with your first date coordinates',
        effects: { money: -15, happiness: 16, karma: 4 },
        outcomeText: 'Tears welled in your partner eyes when they opened the velvet box. Priceless.',
        tone: 'good',
      },
      {
        id: 'anniv_photo_album',
        text: 'Handcraft a scrapbook album featuring tickets, polaroids, and inside jokes',
        effects: { smarts: 4, happiness: 14 },
        outcomeText: 'You spent hours reminiscing together over laughter and warm tea.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_jealousy_party',
    text: 'At a bustling rooftop party, a charismatic stranger attempts to {openly flirt with your partner|monopolize your partner attention}.',
    minAge: 19,
    maxAge: 28,
    weight: 70,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'jealousy_arm_around',
        text: 'Walk over smoothly, wrap an arm around your partner waist, and introduce yourself',
        effects: { looks: 4, happiness: 8 },
        outcomeText: 'Your partner kissed your cheek and smiled: "There is my favorite person!"',
        tone: 'good',
      },
      {
        id: 'jealousy_trust_partner',
        text: 'Watch calmly from the bar, trusting your partner to handle it gracefully',
        effects: { smarts: 4, karma: 5, happiness: 6 },
        outcomeText: 'Your partner politely excused themselves and immediately walked over to you.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_late_night_rickshaw',
    text: 'Leaving a midnight party, the roads are deserted and a cool breeze flows. You hail a {hood-down rickshaw|painted colorful carriage} with your partner.',
    minAge: 18,
    maxAge: 29,
    weight: 80,
    tone: 'good',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'rickshaw_hold_hands',
        text: 'Interlock fingers and lean your head against their shoulder under streetlights',
        effects: { happiness: 15, looks: 2 },
        outcomeText: 'Yellow sodium lights streaked past in a quiet, dreamlike city trance.',
        tone: 'good',
      },
      {
        id: 'rickshaw_sing_along',
        text: 'Sing nostalgic 90s pop choruses softly together as the wheels hum',
        effects: { happiness: 12, karma: 3 },
        outcomeText: 'Even the rickshaw puller whistled along to the melody.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_ikea_furniture_meltdown',
    text: 'A flat-pack wardrobe arrives with {sixty identical screws|confusing pictorial instructions|missing wooden dowels}.',
    minAge: 21,
    maxAge: 29,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['romance', 'lifestyle'],
    choices: [
      {
        id: 'ikea_teamwork_patience',
        text: 'Put on a jazz playlist, distribute screwdriver duties, and work as a unit',
        effects: { smarts: 5, happiness: 10 },
        outcomeText: 'Three hours later, the wardrobe stood sturdy and perfectly aligned.',
        tone: 'good',
      },
      {
        id: 'ikea_order_pizza_giveup',
        text: 'Call a truce, sit on the unfinished planks, and order a large pizza',
        effects: { money: -8, happiness: 8 },
        outcomeText: 'The wardrobe was finished Sunday. The pizza was demolished in fifteen minutes.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_accidental_double_date',
    text: 'You sit down at an upscale Italian restaurant on a romantic date, only to find {your ex seated at the adjacent booth|your former crush walking in}.',
    minAge: 20,
    maxAge: 29,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'ex_polite_nod',
        text: 'Give a brief polite nod and focus 100% of your energy on your current date',
        effects: { looks: 3, happiness: 6, karma: 2 },
        outcomeText: 'Your date appreciated your total undivided attention. Smoothly handled.',
        tone: 'good',
      },
      {
        id: 'ex_change_tables',
        text: 'Quietly tip the host to move you to a secluded candlelit balcony table',
        effects: { money: -5, happiness: 10 },
        outcomeText: 'The balcony view was twice as romantic. Disaster elegantly avoided.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_hostel_maggi_cooking',
    text: 'At 2 AM during exam week, your dormitory floor pools resources to cook {spicy instant noodles with boiled eggs|masala potatoes} on an illegal burner.',
    minAge: 18,
    maxAge: 24,
    weight: 75,
    tone: 'funny',
    category: 'young-adult',
    tags: ['education'],
    choices: [
      {
        id: 'maggi_head_chef',
        text: 'Take command of seasoning packets, chopped onions, and chilies',
        effects: { smarts: 3, happiness: 10, fame: 4 },
        outcomeText: 'A culinary masterpiece served on newspaper sheets. You are crowned the Hostel Legend.',
        tone: 'good',
      },
      {
        id: 'maggi_guard_watchout',
        text: 'Keep guard at the corridor stairs in case the hall warden prowls',
        effects: { smarts: 4, karma: 4 },
        outcomeText: 'You gave the all-clear whistle just in time. The feast was saved!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_thesis_defense_jitters',
    text: 'Your undergraduate final thesis defense is scheduled. The panel includes {the most demanding department chair|external examiners with thick glasses}.',
    minAge: 21,
    maxAge: 25,
    weight: 80,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education'],
    choices: [
      {
        id: 'thesis_flawless_data',
        text: 'Present rigorous methodology, robust charts, and answer every critique crisply',
        effects: { smarts: 12, fame: 8, happiness: 14 },
        outcomeText: 'The chair stood to shake your hand: "Distinction grade, exemplary scholarship!"',
        tone: 'good',
      },
      {
        id: 'thesis_humble_defense',
        text: 'Acknowledge scope limitations honestly and emphasize practical applications',
        effects: { smarts: 8, happiness: 8 },
        outcomeText: 'Solid, credible, and approved without revisions. Graduation is in sight!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_first_salary_celebration',
    text: 'Your very first professional monthly paycheck lands in your bank account with {a triumphant SMS alert|crisp withdrawal notes}.',
    minAge: 21,
    maxAge: 27,
    weight: 85,
    tone: 'good',
    category: 'young-adult',
    tags: ['wealth', 'career'],
    choices: [
      {
        id: 'salary_treat_family',
        text: 'Take your parents and siblings to a grand celebration dinner',
        effects: { money: -15, karma: 12, happiness: 18 },
        outcomeText: 'Seeing the proud, beaming tears in your parents eyes is worth everything.',
        tone: 'good',
      },
      {
        id: 'salary_smart_invest',
        text: 'Save eighty percent into an emergency fund and treat yourself to a book',
        effects: { money: 25, smarts: 6, happiness: 10 },
        outcomeText: 'The disciplined foundation of future financial freedom is laid.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_first_motorbike',
    text: 'You save enough to purchase your first two-wheeler: a {gleaming retro scooter|reliable 125cc commuter bike}.',
    minAge: 19,
    maxAge: 28,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['lifestyle', 'wealth'],
    choices: [
      {
        id: 'bike_flyover_cruise',
        text: 'Take a sunset spin across the elevated expressway with a helmet and jacket',
        effects: { money: -40, looks: 6, happiness: 15 },
        outcomeText: 'Dhaka traffic no longer controls your schedule. Pure uninhibited liberty.',
        tone: 'good',
      },
      {
        id: 'bike_defensive_rider',
        text: 'Install crash guards, high-visibility mirrors, and drive conservatively',
        effects: { money: -35, health: 3, smarts: 4 },
        outcomeText: 'Reliable, economical transport that saves two hours every single day.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_remote_work_burnout',
    text: 'Working three consecutive weeks on a remote contract, your desk has merged with {your mattress|empty coffee mugs|tangled cables}.',
    minAge: 22,
    maxAge: 30,
    weight: 70,
    tone: 'bad',
    category: 'young-adult',
    tags: ['health', 'career'],
    choices: [
      {
        id: 'burnout_nature_detox',
        text: 'Shut the laptop at 5 PM sharp, go for a long jog, and sit in a park',
        effects: { health: 6, happiness: 10 },
        outcomeText: 'Fresh air and green trees restored your exhausted eyes and drained spirit.',
        tone: 'good',
      },
      {
        id: 'burnout_power_through',
        text: 'Chug an energy drink and keep coding through midnight',
        effects: { money: 25, health: -6, happiness: -6 },
        outcomeText: 'The project shipped on time, but your body demanded two days of bedrest.',
        tone: 'bad',
      },
    ],
  },
  {
    id: 'ya_wedding_biryani_crashing',
    text: 'A cousin invites you to accompany them to an extravagant wedding hall where {they barely know the groom|the banquet aroma of roast and kacchi is hypnotic}.',
    minAge: 18,
    maxAge: 28,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['social'],
    choices: [
      {
        id: 'crash_infiltrate_buffet',
        text: 'Dress in formal panjabi, smile politely, and pile mutton onto your plate',
        effects: { happiness: 14, looks: 2, karma: -2 },
        outcomeText: 'Tender mutton, fragrant potato, and zero questions asked. Masterclass banquet raid.',
        tone: 'good',
      },
      {
        id: 'crash_greet_couple',
        text: 'Hand over an envelope with polite well-wishes before eating',
        effects: { karma: 4, money: -5, happiness: 8 },
        outcomeText: 'You earned your feast honestly. The bride family appreciated the gesture.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_side_hustle_baking',
    text: 'You post photos of your homemade {fudge brownies|sourdough loaves|churro bites} online, and sudden customer orders pour in.',
    minAge: 19,
    maxAge: 29,
    weight: 70,
    tone: 'good',
    category: 'young-adult',
    tags: ['wealth', 'career'],
    choices: [
      {
        id: 'bake_package_boxes',
        text: 'Tie brown craft boxes with twine and deliver orders across the city',
        effects: { money: 35, happiness: 12, smarts: 4 },
        outcomeText: 'Customers posted rave reviews! Your home bakery has an official fan club.',
        tone: 'good',
      },
      {
        id: 'bake_hire_assistant',
        text: 'Partner with a classmate to scale production into a real micro-business',
        effects: { money: 50, smarts: 6, fame: 4 },
        outcomeText: 'A legitimate small enterprise born out of flour, butter, and sheer grit.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_gym_transformation',
    text: 'You sign up at a local fitness center with a personal trainer who believes in {heavy barbell squats|rigorous circuit training}.',
    minAge: 18,
    maxAge: 30,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['health', 'looks'],
    choices: [
      {
        id: 'gym_consistent_grind',
        text: 'Show up four days a week without fail and master clean lifting form',
        effects: { health: 10, looks: 8, happiness: 8 },
        outcomeText: 'Posture improved, shoulder breadth expanded, and energy levels doubled.',
        tone: 'good',
      },
      {
        id: 'gym_protein_shake_only',
        text: 'Buy flashy gym clothes and take plenty of mirror selfies',
        effects: { looks: 3, money: -10, happiness: 4 },
        outcomeText: 'The aesthetic game was on point, even if the barbell was barely touched.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_thrift_vintage_find',
    text: 'Rummaging through export surplus racks, you uncover an authentic {heavy trench coat|vintage aviator jacket} for pennies.',
    minAge: 18,
    maxAge: 28,
    weight: 70,
    tone: 'good',
    category: 'young-adult',
    tags: ['looks'],
    choices: [
      {
        id: 'thrift_tailor_fit',
        text: 'Take it to a local master tailor to adjust the sleeve length and shoulders',
        effects: { looks: 8, happiness: 10, money: -4 },
        outcomeText: 'It fits like bespoke couture. Colleagues ask which designer brand it is.',
        tone: 'good',
      },
      {
        id: 'thrift_resell_profit',
        text: 'Dry-clean it and flip it on a curated vintage shop for quadruple the price',
        effects: { money: 20, smarts: 4 },
        outcomeText: 'An effortless profit pocketed from sharp retail eyes.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_job_interview_bluff',
    text: 'In an interview for a promising junior role, the director asks if you know how to use an advanced {analytics tool|financial modeling software}.',
    minAge: 21,
    maxAge: 28,
    weight: 75,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'interview_honest_learner',
        text: 'Admit you are a beginner, but describe how quickly you learn new systems',
        effects: { karma: 6, smarts: 4, fame: 2 },
        outcomeText: 'They appreciated your integrity: "We hire character, we teach software. You are hired!"',
        tone: 'good',
      },
      {
        id: 'interview_bluff_study',
        text: 'Claim total competence, then spend 48 frantic hours watching YouTube tutorials',
        effects: { smarts: 6, health: -2, money: 20 },
        outcomeText: 'You pulled off the miracle. By Monday morning, you actually knew the tool.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_street_rescue_dog',
    text: 'A friendly community dog with a wounded paw limps up to your doorway seeking {shelter from the cold|scraps of food}.',
    minAge: 18,
    maxAge: 30,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['pets'],
    choices: [
      {
        id: 'dog_vet_bandage',
        text: 'Take it to the veterinary clinic for stitches and vaccinations',
        effects: { money: -15, karma: 15, happiness: 12 },
        outcomeText: 'The pup healed completely and now faithfully guards your building entrance.',
        tone: 'good',
      },
      {
        id: 'dog_feed_warm_meal',
        text: 'Provide warm boiled rice with chicken broth and a cozy blanket',
        effects: { karma: 8, happiness: 8 },
        outcomeText: 'A full belly and a warm bed. A soul deeply grateful for your kindness.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_campus_protest_unity',
    text: 'Students organize a peaceful march to demand {lower tuition fees|better university bus transit}.',
    minAge: 18,
    maxAge: 25,
    weight: 70,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['education', 'social'],
    choices: [
      {
        id: 'protest_chant_banner',
        text: 'Help paint banners and march shoulder-to-shoulder with student leaders',
        effects: { fame: 6, karma: 6, happiness: 6 },
        outcomeText: 'The administration listened. Three new campus transit routes were approved!',
        tone: 'good',
      },
      {
        id: 'protest_library_focus',
        text: 'Focus on your upcoming midterms in the quiet sanctuary of the library',
        effects: { smarts: 6 },
        outcomeText: 'Uninterrupted study hours secured high marks on your engineering exam.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_intercity_train_trip',
    text: 'You take the morning express train to {Chittagong|Rajshahi|Sylhet}. Outside the window, endless green paddy fields rush past.',
    minAge: 19,
    maxAge: 29,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['adventure'],
    choices: [
      {
        id: 'train_doorway_breeze',
        text: 'Stand securely by the open doorway drinking tea as rural landscapes glide by',
        effects: { happiness: 12, health: 2 },
        outcomeText: 'Wind in your face, the rhythmic clatter of tracks, and a soul at peace.',
        tone: 'good',
      },
      {
        id: 'train_cozy_nap',
        text: 'Recline in your window seat with a mystery novel and drift into a nap',
        effects: { health: 4, happiness: 8 },
        outcomeText: 'Arrived at your destination fully refreshed and rejuvenated.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_office_secret_santa',
    text: 'Your corporate office organizes a holiday gift exchange. You draw the name of {the stern managing director|your quiet cubicle neighbor}.',
    minAge: 21,
    maxAge: 30,
    weight: 65,
    tone: 'funny',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'gift_artisan_tea',
        text: 'Gift a premium tin of organic whole-leaf silver needle tea',
        effects: { money: -6, fame: 5, karma: 4 },
        outcomeText: 'The director cracked a rare smile: "You have immaculate taste." Major brownie points.',
        tone: 'good',
      },
      {
        id: 'gift_funny_mug',
        text: 'Wrap a hilarious ceramic mug reading "World Best Problem Solver"',
        effects: { money: -4, happiness: 8 },
        outcomeText: 'It became the talk of the breakroom and earned hearty chuckles.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_rooftop_monsoon_tea',
    text: 'A sudden afternoon rainstorm cools the city. Neighbors assemble on the rooftop with {hot samosas|crunchy onion pakoras|piping hot ginger tea}.',
    minAge: 18,
    maxAge: 30,
    weight: 80,
    tone: 'good',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'rain_dance_soak',
        text: 'Run into the downpour and dance with pure childlike abandonment',
        effects: { happiness: 16, health: -1, looks: 2 },
        outcomeText: 'Drenched in rainwater and laughter. A memory that washes away all adult stress.',
        tone: 'good',
      },
      {
        id: 'rain_shed_chai',
        text: 'Sit under the corrugated tin canopy listening to the soothing percussion of raindrops',
        effects: { happiness: 10, health: 3 },
        outcomeText: 'Hot ginger tea warming your hands as silver torrents fall from the sky.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_cng_fare_meter',
    text: 'During evening rush hour, an auto-rickshaw driver refuses the meter and demands {double the usual fare|an outrageous round figure}.',
    minAge: 18,
    maxAge: 32,
    weight: 75,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'cng_haggle_firm',
        text: 'Counter-offer reasonably with theatrical indignation',
        effects: { smarts: 4, money: -2, happiness: 4 },
        outcomeText: 'He shook his head, chuckled, and said "Hop in, you drive a hard bargain!"',
        tone: 'good',
      },
      {
        id: 'cng_walk_exercise',
        text: 'Politely refuse and walk the three kilometers enjoying the evening breeze',
        effects: { health: 6, money: 3, happiness: 2 },
        outcomeText: 'Saved some cash and hit your daily step goal before dinner.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_wedding_sherwani_crisis',
    text: 'The morning of your cousin grand wedding, you realize your rented traditional outfit is {two sizes too large|missing its decorative buttons}.',
    minAge: 20,
    maxAge: 35,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle', 'family'],
    choices: [
      {
        id: 'sherwani_tailor_rush',
        text: 'Dash to the local corner tailor with emergency plea and extra tip',
        effects: { money: -5, smarts: 3, looks: 6 },
        outcomeText: 'Master tailor worked lightning magic in twenty minutes flat. You looked majestic!',
        tone: 'good',
      },
      {
        id: 'sherwani_safety_pins',
        text: 'Improvise using heavy-duty safety pins and strategic draping',
        effects: { smarts: 5, looks: -2, happiness: 4 },
        outcomeText: 'Held together by pure willpower and concealed brass pins. Nobody noticed.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_street_fuchka_challenge',
    text: 'Your group of friends challenges you to eat {twenty extra-spicy tamarind fuchkas|the hottest street chili snacks in town}.',
    minAge: 18,
    maxAge: 30,
    weight: 75,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'fuchka_champion_eat',
        text: 'Accept the dare boldly without touching the sweet yogurt sauce',
        effects: { health: -3, happiness: 12, fame: 6 },
        outcomeText: 'Sweat poured down your temples, but you finished every single one to deafening cheers!',
        tone: 'good',
      },
      {
        id: 'fuchka_sensible_mild',
        text: 'Laugh and stick to your gentle mild plate with extra crunchy crisps',
        effects: { health: 2, happiness: 5 },
        outcomeText: 'Your stomach thanked you sincerely the next morning.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_freelance_payment_delay',
    text: 'An overseas freelance client promises payment {upon next milestone review|next Monday morning without fail}.',
    minAge: 20,
    maxAge: 35,
    weight: 70,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career', 'finance'],
    choices: [
      {
        id: 'freelance_firm_invoice',
        text: 'Send a professional reminder detailing payment terms and late fees',
        effects: { smarts: 6, money: 12, happiness: 4 },
        outcomeText: 'The accounting team apologized profusely and processed the wire transfer immediately.',
        tone: 'good',
      },
      {
        id: 'freelance_pause_work',
        text: 'Pause all repository commits until the outstanding balance clears',
        effects: { smarts: 4, karma: -2, money: 8 },
        outcomeText: 'Client quickly took note and settled up to unblock the milestone.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_gym_supplements_hype',
    text: 'A muscular gym trainer pitches you {an imported mega-protein tub|a mysterious herbal stamina potion}.',
    minAge: 19,
    maxAge: 34,
    weight: 65,
    tone: 'funny',
    category: 'young-adult',
    tags: ['health'],
    choices: [
      {
        id: 'gym_natural_diet',
        text: 'Decline politely and stick to eggs, bananas, and homemade lentils',
        effects: { smarts: 5, health: 5, money: 4 },
        outcomeText: 'Real food, steady gains, and a much fuller bank account.',
        tone: 'good',
      },
      {
        id: 'gym_buy_powder',
        text: 'Buy the flashy tub with gold holographic lettering',
        effects: { money: -8, looks: 3, health: 2 },
        outcomeText: 'Tastes like chalk and vanilla dreams, but the placebo effect feels legendary.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_indie_rock_jam',
    text: 'A neighborhood underground band invites you to jam on {the electric bass guitar|the vintage synthesizers}.',
    minAge: 18,
    maxAge: 30,
    weight: 65,
    tone: 'good',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'band_jam_soul',
        text: 'Plug in and improvise a soulful groove that sets the whole room nodding',
        effects: { fame: 6, happiness: 12, looks: 3 },
        outcomeText: 'The drummer yelled: "You are officially part of our lineup!" Great vibes.',
        tone: 'good',
      },
      {
        id: 'band_enjoy_listener',
        text: 'Applaud from the couch and offer constructive feedback on song arrangements',
        effects: { smarts: 4, karma: 5, happiness: 6 },
        outcomeText: 'The band treated you to milk tea and appreciated your sharp musical ear.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_book_fair_crowd',
    text: 'At the annual national book fair, hundreds of readers surround a pavilion to meet {a beloved novelist|a young poet sensation}.',
    minAge: 18,
    maxAge: 36,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['education', 'lifestyle'],
    choices: [
      {
        id: 'book_fair_queue_autograph',
        text: 'Wait patiently in the festive line to get your copy inscribed',
        effects: { smarts: 5, happiness: 8, karma: 4 },
        outcomeText: 'The author smiled warmly and wrote an inspiring note specifically to you.',
        tone: 'good',
      },
      {
        id: 'book_fair_explore_stalls',
        text: 'Wander off to quiet independent publishers and uncover forgotten history gems',
        effects: { smarts: 8, money: -4, happiness: 6 },
        outcomeText: 'Discovered two rare poetry collections and enjoyed an unhurried literary evening.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_flatmate_chore_wheel',
    text: 'Your shared apartment sink is filled with dishes. Roommates propose creating {a strict chore wheel schedule|a fine penalty jar for dirty pots}.',
    minAge: 19,
    maxAge: 32,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'flat_lead_system',
        text: 'Draft an equitable color-coded whiteboard schedule and hold everyone accountable',
        effects: { smarts: 5, karma: 6, happiness: 5 },
        outcomeText: 'Peace was restored. The kitchen finally smelled like lemon detergent.',
        tone: 'good',
      },
      {
        id: 'flat_hire_cook',
        text: 'Propose pooling small funds together to hire a dedicated part-time cleaner',
        effects: { money: -5, happiness: 10, smarts: 3 },
        outcomeText: 'Unanimous applause. No more arguments over who left the tea strainer.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_startup_pitch_deck',
    text: 'You have twenty minutes to present your tech startup slide deck before {a panel of seasoned angel investors|a prestigious venture accelerator committee}.',
    minAge: 21,
    maxAge: 38,
    weight: 65,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career', 'finance'],
    choices: [
      {
        id: 'pitch_metrics_focus',
        text: 'Lead with hard user traction data, retention curves, and path to profitability',
        effects: { smarts: 8, money: 18, fame: 8, happiness: 8 },
        outcomeText: 'The lead partner leaned forward: "Clean unit economics. We want in for seed round."',
        tone: 'good',
      },
      {
        id: 'pitch_visionary_story',
        text: 'Tell an emotional story about solving everyday community struggles with technology',
        effects: { fame: 10, looks: 4, karma: 6 },
        outcomeText: 'Earned enthusiastic nods and two immediate invites to follow-up diligence calls.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_old_dhaka_biryani_hunt',
    text: 'Past midnight, your friends persuade you to venture into narrow heritage alleys to hunt for {legendary saffron mutton biryani|fragrant slow-cooked beef tehari}.',
    minAge: 18,
    maxAge: 32,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'biryani_midnight_feast',
        text: 'Feast by lantern light surrounded by steaming giant copper pots',
        effects: { happiness: 14, health: -2, looks: -1 },
        outcomeText: 'Melt-in-your-mouth potatoes and rich spices. An unforgettable gastronomic adventure.',
        tone: 'good',
      },
      {
        id: 'biryani_takeaway_home',
        text: 'Pack generous parcels for family members sleeping back home',
        effects: { karma: 8, happiness: 8, money: -5 },
        outcomeText: 'Your siblings woke up to the heavenly aroma and declared you family hero.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_office_printer_jam',
    text: 'Ten minutes before a high-stakes board presentation, the departmental printer displays {a cryptic error code|a stubborn paper jam deep in the rollers}.',
    minAge: 21,
    maxAge: 35,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'printer_surgical_fix',
        text: 'Carefully slide gears and extract the crumpled sheet without snapping pins',
        effects: { smarts: 6, fame: 4, happiness: 6 },
        outcomeText: 'The machine whirred back to life! You walked into the meeting room like a conqueror.',
        tone: 'good',
      },
      {
        id: 'printer_digital_tablet',
        text: 'Pivot instantly: project digital slides onto the big wall monitor instead',
        effects: { smarts: 8, fame: 6 },
        outcomeText: 'The director remarked: "Modern, eco-friendly, and sharp. Excellent agility."',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_coffee_shop_remote_work',
    text: 'You set up your laptop in an air-conditioned boutique cafe with {fast optic fiber internet|chic jazz background music}.',
    minAge: 19,
    maxAge: 35,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['career', 'lifestyle'],
    choices: [
      {
        id: 'cafe_deep_focus',
        text: 'Order a second cappuccino and enter four uninterrupted hours of deep flow work',
        effects: { smarts: 8, money: 8, happiness: 6 },
        outcomeText: 'Finished two complex deliverables ahead of deadline. Pure productivity.',
        tone: 'good',
      },
      {
        id: 'cafe_people_watch',
        text: 'Spend half the time observing eccentric clients and scribbling witty journal entries',
        effects: { happiness: 10, looks: 2, smarts: 4 },
        outcomeText: 'Relaxing afternoon filled with creative sparks and fragrant roasted beans.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_used_motorbike_deal',
    text: 'A classified advertisement lists a gleaming vintage motorcycle at {half the market price|an irresistible bargain rate}.',
    minAge: 19,
    maxAge: 34,
    weight: 65,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['finance', 'lifestyle'],
    choices: [
      {
        id: 'bike_mechanic_inspect',
        text: 'Bring an experienced mechanic friend along to inspect chassis and engine compression',
        effects: { smarts: 7, money: -4, happiness: 5 },
        outcomeText: 'Mechanic found a hidden radiator crack: saved you from buying a costly lemon!',
        tone: 'good',
      },
      {
        id: 'bike_test_drive_thrill',
        text: 'Take it for an exhilarating spin down the bypass expressway',
        effects: { health: 2, happiness: 12, fame: 4 },
        outcomeText: 'Wind roaring against your jacket. You felt alive and unstoppable.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_family_curfew_negotiation',
    text: 'At 10:00 PM, your phone rings: your parents demand to know {why you are not at home yet|if you have eaten proper dinner}.',
    minAge: 18,
    maxAge: 27,
    weight: 75,
    tone: 'funny',
    category: 'young-adult',
    tags: ['family'],
    choices: [
      {
        id: 'curfew_share_live_location',
        text: 'Send live location, send a picture with coworkers, and speak with calming reassurance',
        effects: { karma: 8, happiness: 4, smarts: 3 },
        outcomeText: 'Parents felt assured and set aside a warm plate of rice in the microwave.',
        tone: 'good',
      },
      {
        id: 'curfew_rush_back_taxi',
        text: 'Catch an immediate cab to respect family house rules',
        effects: { money: -3, karma: 6, happiness: 2 },
        outcomeText: 'Arrived home on time to welcoming smiles and hot tea.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_first_credit_card_limit',
    text: 'Your bank approves your first credit card with a {temptingly high credit line|generous welcome rewards program}.',
    minAge: 21,
    maxAge: 36,
    weight: 70,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['finance'],
    choices: [
      {
        id: 'card_discipline_autopay',
        text: 'Set up auto-pay in full every month and treat it strictly as a cash debit card',
        effects: { smarts: 8, money: 8, happiness: 5 },
        outcomeText: 'Your credit score soared while racking up free air miles with zero interest paid.',
        tone: 'good',
      },
      {
        id: 'card_gadget_splurge',
        text: 'Celebrate with a brand-new noise-cancelling headphone set on zero-interest EMI',
        effects: { looks: 4, happiness: 10, money: -6 },
        outcomeText: 'Audio quality is cinematic, though monthly installments remind you of reality.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_traffic_jam_audiobook',
    text: 'Vehicles stand completely motionless for two hours on the flyover beneath {a blazing afternoon sun|a steady drizzle}.',
    minAge: 18,
    maxAge: 38,
    weight: 80,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'jam_audiobook_learn',
        text: 'Pop in earphones and listen to a captivating history audiobook',
        effects: { smarts: 8, happiness: 6 },
        outcomeText: 'By the time traffic cleared, you had learned the entire rise and fall of Rome.',
        tone: 'good',
      },
      {
        id: 'jam_chat_strangers',
        text: 'Chat and trade jokes with weary fellow bus passengers',
        effects: { happiness: 8, karma: 5, fame: 2 },
        outcomeText: 'Shared roasted peanuts and laughter transformed a miserable delay into camaraderie.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_cousin_startup_advice',
    text: 'Your enthusiastic cousin pitches you a venture: {an artisan organic soap subscription|a gourmet chai delivery bike fleet}.',
    minAge: 20,
    maxAge: 36,
    weight: 65,
    tone: 'funny',
    category: 'young-adult',
    tags: ['family', 'career'],
    choices: [
      {
        id: 'cousin_branding_critique',
        text: 'Offer honest marketing feedback and help refine target customer persona',
        effects: { smarts: 7, karma: 6, happiness: 5 },
        outcomeText: 'Cousin took notes eagerly and reworked the proposal into a viable business model.',
        tone: 'good',
      },
      {
        id: 'cousin_small_angel_check',
        text: 'Write a small friendly micro-check to back their dream',
        effects: { money: -6, karma: 8, happiness: 8 },
        outcomeText: 'First batch went live and your family applauded your generous mentorship.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_night_shift_callcenter',
    text: 'On the graveyard shift at the international helpdesk, a caller has {an absurdly complicated billing issue|a bizarre complaint about smart appliances}.',
    minAge: 20,
    maxAge: 32,
    weight: 65,
    tone: 'funny',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'shift_diplomatic_patience',
        text: 'Walk through every troubleshooting step with soothing vocal warmth',
        effects: { smarts: 6, fame: 5, money: 6 },
        outcomeText: 'Customer submitted a glowing five-star review praising your exceptional customer care.',
        tone: 'good',
      },
      {
        id: 'shift_coffee_break_reset',
        text: 'Transfer smoothly to specialized tier-two team while taking a quick espresso breath',
        effects: { health: 2, happiness: 4 },
        outcomeText: 'Handled protocol by the book and preserved your sanity until shift change.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_art_gallery_exhibition',
    text: 'A trendy municipal art space features your original creative work in {a contemporary youth showcase|an indie photographic display}.',
    minAge: 20,
    maxAge: 38,
    weight: 65,
    tone: 'good',
    category: 'young-adult',
    tags: ['lifestyle', 'fame'],
    choices: [
      {
        id: 'art_opening_mingle',
        text: 'Attend opening night in a crisp dark blazer and explain your visual inspirations',
        effects: { fame: 12, looks: 5, happiness: 10 },
        outcomeText: 'Two art collectors praised your evocative use of shadow and local textures.',
        tone: 'good',
      },
      {
        id: 'art_sell_prints',
        text: 'Offer limited signed art prints to enthusiastic visitors at affordable prices',
        effects: { money: 10, smarts: 4, karma: 5 },
        outcomeText: 'Every single print sold out before the evening concluded!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_monsoon_waterlogged_street',
    text: 'A sudden tropical deluge leaves your neighborhood streets knee-deep under {crystal-clear rain pools|murky swirling floodwater}.',
    minAge: 18,
    maxAge: 38,
    weight: 75,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'flood_wooden_boat',
        text: 'Pay a few coins to cross on a makeshift wooden dinghy with neighbor children',
        effects: { money: -2, happiness: 8, karma: 3 },
        outcomeText: 'Felt like an intrepid explorer crossing a mighty jungle river. Kept shoes completely dry.',
        tone: 'good',
      },
      {
        id: 'flood_roll_trousers',
        text: 'Roll up trousers, hoist sandals on shoulders, and march forward with grin',
        effects: { health: 3, happiness: 6 },
        outcomeText: 'Cool water, splashing laughter, and pure monsoon resilience.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_blind_date_awkward',
    text: 'Your matchmaker aunt insists you have coffee with {a polite chartered accountant|an introverted software architect}.',
    minAge: 22,
    maxAge: 35,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['romance'],
    choices: [
      {
        id: 'date_witty_banter',
        text: 'Break the awkward ice by discussing your mutual eccentric family relatives',
        effects: { looks: 4, happiness: 10, fame: 3 },
        outcomeText: 'Both erupted in laughter. What started stiff turned into a delightful two-hour chat.',
        tone: 'good',
      },
      {
        id: 'date_cordial_goodbye',
        text: 'Enjoy polite coffee, pay your half, and agree you would make great mutual acquaintances',
        effects: { karma: 4, smarts: 3, happiness: 4 },
        outcomeText: 'No drama, mature mutual respect, and your aunt received a positive report.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_corporate_town_hall',
    text: 'At the annual company town hall, the CEO opens the microphone for {unfiltered employee questions|feedback on workplace culture}.',
    minAge: 22,
    maxAge: 38,
    weight: 65,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'townhall_constructive_idea',
        text: 'Propose flexible hybrid work hours with clear focus on output metrics',
        effects: { smarts: 8, fame: 8, happiness: 6 },
        outcomeText: 'Applause rippled through the auditorium; senior HR requested a follow-up policy draft.',
        tone: 'good',
      },
      {
        id: 'townhall_listen_quietly',
        text: 'Listen intently while analyzing leadership body language and subtext',
        effects: { smarts: 5, karma: 2 },
        outcomeText: 'Gained sharp political insight into where the company priorities are shifting.',
        tone: 'neutral',
      },
    ],
  },
  {
    id: 'ya_thrift_market_vintage',
    text: 'In a bustling weekend flea market, you spot {a genuine handwoven vintage jacket|a rare antique brass pocket watch}.',
    minAge: 18,
    maxAge: 34,
    weight: 70,
    tone: 'good',
    category: 'young-adult',
    tags: ['lifestyle', 'wealth'],
    choices: [
      {
        id: 'thrift_negotiate_gem',
        text: 'Bargain gracefully and take home the unique heirloom treasure',
        effects: { looks: 8, money: -4, happiness: 10 },
        outcomeText: 'Friends constantly stop to ask where you found such an iconic piece.',
        tone: 'good',
      },
      {
        id: 'thrift_gift_friend',
        text: 'Buy it as an unexpected surprise birthday present for your closest companion',
        effects: { money: -5, karma: 10, happiness: 8 },
        outcomeText: 'They were moved to tears by your thoughtfulness. Unbreakable bond.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_stray_cat_adoption',
    text: 'A tiny calico kitten with huge green eyes sits on your doorstep, meowing gently through {a chilly evening breeze|the early morning mist}.',
    minAge: 18,
    maxAge: 38,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'cat_adopt_forever',
        text: 'Bring the kitten inside, provide warm milk, and welcome a new companion',
        effects: { happiness: 16, karma: 8, money: -3 },
        outcomeText: 'Curled up into a purring ball on your lap. Your home instantly feels warmer.',
        tone: 'good',
      },
      {
        id: 'cat_vet_foster',
        text: 'Take it to the local animal clinic for health check and find a loving foster home',
        effects: { karma: 12, smarts: 4, money: -2 },
        outcomeText: 'Found a lovely family with a backyard within forty-eight hours.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_neighbor_roof_gardening',
    text: 'An elderly neighbor invites you upstairs to inspect {fragrant jasmine blooms|thriving heirloom coriander and mint pots}.',
    minAge: 18,
    maxAge: 38,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'garden_help_soil',
        text: 'Help haul fresh fertile potting soil and learn organic grafting tricks',
        effects: { karma: 8, smarts: 5, happiness: 8, health: 3 },
        outcomeText: 'The elder gifted you sweet fresh mint cuttings and delicious homemade sweetmeats.',
        tone: 'good',
      },
      {
        id: 'garden_admire_tea',
        text: 'Sip cardamom tea while listening to neighborhood historical folklore',
        effects: { happiness: 6, smarts: 4, karma: 4 },
        outcomeText: 'A relaxing sunset hour overlooking the terracotta roofs of the city.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_podcast_interview_invite',
    text: 'A popular digital lifestyle podcast invites you to discuss {balancing ambitious side gigs with sanity|navigating career pivots in modern times}.',
    minAge: 21,
    maxAge: 38,
    weight: 65,
    tone: 'good',
    category: 'young-adult',
    tags: ['fame', 'career'],
    choices: [
      {
        id: 'podcast_authentic_wisdom',
        text: 'Speak candidly with self-deprecating humor and practical advice',
        effects: { fame: 12, happiness: 8, smarts: 5 },
        outcomeText: 'Listeners flooded the comment section praising your grounded authenticity.',
        tone: 'good',
      },
      {
        id: 'podcast_promote_portfolio',
        text: 'Showcase your team latest creative projects and upcoming releases',
        effects: { fame: 10, money: 8, smarts: 4 },
        outcomeText: 'Inbound client inquiries doubled over the subsequent fortnight.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_cooking_biryani_disaster',
    text: 'Hosting friends for the weekend, you attempt to cook authentic aromatic biryani from scratch, but {the bottom layer starts smelling smoky|the rice threatens to get overcooked}.',
    minAge: 20,
    maxAge: 35,
    weight: 70,
    tone: 'funny',
    category: 'young-adult',
    tags: ['lifestyle'],
    choices: [
      {
        id: 'biryani_tawa_technique',
        text: 'Quickly transfer pot onto a heavy iron griddle to disperse heat gently',
        effects: { smarts: 6, happiness: 8, looks: 2 },
        outcomeText: 'Saved the day! The tender meat and aromatic grains drew unanimous praise.',
        tone: 'good',
      },
      {
        id: 'biryani_order_emergency_kebabs',
        text: 'Laugh, order emergency fresh naan and kebabs from nearby grill',
        effects: { money: -6, happiness: 10, fame: 2 },
        outcomeText: 'The banquet turned into a merry evening of storytelling and joke swapping.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_exam_admit_card_panic',
    text: 'Arriving at the university examination center, you realize your printed registration slip is {sitting on your study desk|in your other messenger bag}.',
    minAge: 18,
    maxAge: 26,
    weight: 65,
    tone: 'bad',
    category: 'young-adult',
    tags: ['education'],
    choices: [
      {
        id: 'exam_emergency_print',
        text: 'Sprint to the corner photocopy stall and print a duplicate copy from cloud storage',
        effects: { smarts: 6, health: 2, happiness: 4 },
        outcomeText: 'Made it into the examination hall with two minutes to spare. Heart pounding, but safe.',
        tone: 'good',
      },
      {
        id: 'exam_plead_proctor',
        text: 'Show student ID card and explain the situation respectfully to chief invigilator',
        effects: { karma: 4, smarts: 4, happiness: 2 },
        outcomeText: 'They checked the master roll sheet and permitted you to sit for the paper.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_train_ticket_queue',
    text: 'To visit grandparents for the festive holidays, you line up at the central railway station at dawn among {thousands of eager holidaymakers|vendors selling hot spiced tea}.',
    minAge: 18,
    maxAge: 36,
    weight: 75,
    tone: 'neutral',
    category: 'young-adult',
    tags: ['family', 'lifestyle'],
    choices: [
      {
        id: 'train_patient_vigil',
        text: 'Hold your spot steadfastly with a thermos flask and morning newspaper',
        effects: { smarts: 4, happiness: 10, karma: 4 },
        outcomeText: 'Secured two lower-berth window tickets! The family cheered upon hearing the news.',
        tone: 'good',
      },
      {
        id: 'train_digital_app_snipe',
        text: 'Keep refreshing the mobile railway booking portal on high-speed data',
        effects: { smarts: 7, money: -2, happiness: 8 },
        outcomeText: 'Payment gateway cleared right at 8:01 AM. Modern technology wins!',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_office_gossip_crossfire',
    text: 'While brewing coffee in the pantry, you overhear two senior managers arguing about {an upcoming departmental merger|who stole the imported tea bags}.',
    minAge: 22,
    maxAge: 38,
    weight: 65,
    tone: 'funny',
    category: 'young-adult',
    tags: ['career'],
    choices: [
      {
        id: 'gossip_silent_ninja',
        text: 'Quietly slip away without clinking your spoon or making a sound',
        effects: { smarts: 6, karma: 5, happiness: 4 },
        outcomeText: 'Masterful stealth. Kept your hands completely clean of workplace politics.',
        tone: 'good',
      },
      {
        id: 'gossip_innocent_cough',
        text: 'Cough cheerfully and ask if anyone wants fresh hot water',
        effects: { smarts: 4, fame: 3, happiness: 4 },
        outcomeText: 'Both managers blushed, cleared their throats, and immediately changed the subject.',
        tone: 'funny',
      },
    ],
  },
  {
    id: 'ya_badminton_winter_tournament',
    text: 'On chilly winter nights, neighborhood youth set up an outdoor badminton court with {white chalk lines on tarmac|a string of hanging incandescent bulbs}.',
    minAge: 18,
    maxAge: 36,
    weight: 75,
    tone: 'good',
    category: 'young-adult',
    tags: ['health', 'lifestyle'],
    choices: [
      {
        id: 'badminton_smash_champion',
        text: 'Team up with a childhood friend and unleash ferocious jumping smashes',
        effects: { health: 8, happiness: 12, fame: 6 },
        outcomeText: 'Won the doubles trophy! Celebrated with steaming mustard-spiced puffed rice.',
        tone: 'good',
      },
      {
        id: 'badminton_cheer_snack',
        text: 'Cheer loudly from the sidelines while keeping the tea kettle boiling',
        effects: { karma: 6, happiness: 8 },
        outcomeText: 'Warm camaraderie, laughter, and vapor rising in the winter air.',
        tone: 'good',
      },
    ],
  },
  {
    id: 'ya_tech_hackathon_weekend',
    text: 'You join a weekend hackathon where teams must code and ship a working product within {thirty-six relentless hours|a non-stop coding sprint}.',
    minAge: 19,
    maxAge: 32,
    weight: 70,
    tone: 'good',
    category: 'young-adult',
    tags: ['career', 'education'],
    choices: [
      {
        id: 'hackathon_demo_triumph',
        text: 'Build an elegant AI tool to translate regional dialects in real time',
        effects: { smarts: 10, fame: 10, money: 12, health: -2 },
        outcomeText: 'The judges awarded your team Best Technical Innovation! A trophy and cash prize!',
        tone: 'good',
      },
      {
        id: 'hackathon_network_mentors',
        text: 'Connect with industry mentors and pitch your engineering skills',
        effects: { smarts: 7, fame: 6, happiness: 6 },
        outcomeText: 'Received two direct internship job offers from visiting tech executives.',
        tone: 'good',
      },
    ],
  },
];